### ISSUE TITLE
On develop startegy, if the develop branch and release merge base are the same version should not be bump

### ISSUE THREAD

**Issue by qetza** [GitTools/GitVersion#1001]
Hi,
Here's the scenario using the develop version strategy
- base version is 1.0.0
- commit on develop => develop version is 1.1.0-alpha.1
- create release/2.0.0 => release version is 2.0.0, develop version is 2.1.0-alpha.0

Since i haven't done any changes on develop, the version should still be 1.1.0-alpha.1. Version should be bump only after a new commit on develop.

See pull request #1000

**Comment by JakeGinnivan** [comment]
Fixed by #1000
