### ISSUE TITLE
Using date in version

### ISSUE THREAD

**Issue by fleed** [GitTools/GitVersion#1007]
I'd like to use year and month value numbers of the current date/timestamp as part of my version:

`[major].[minor].[yyMM].[progressive_ count]`

Where `major` and `minor` are statically assigned, `yyMM` is based on date and the `progressive_count` is of course generated. Example:

`2.1.1608.123`

Can I achieve this thorough configuration? I haven't found references to date in configuration help.

**Comment by JakeGinnivan** [comment]
GitVersion uses the source control history to calculate the version. That means if I rebuild the same commit tomorrow it will be the same version, so no, this is not possible using GitVersion.

This can be solved pretty easily outside gitversion. 

Most build servers allow using dates in version numbers and also Have an incrementing build counter.
