### ISSUE TITLE
Base version from non-merged branch?

### ISSUE THREAD

**Issue by pdeffendol** [GitTools/GitVersion#1008]
One of my projects uses a rather non-conventional flow, and I'm trying to configure GitVersion to deal with it.
- Feature branches are merged into `master` when complete
- When a new release is made, `master` is merged into a `production` branch.
- The commit on the `production` branch is tagged with the release version number.
- The `production` branch is never merged back into master

The problem with GitVersion is that when calculating prerelease build numbers on the `master` branch, none of the release tags are "accessible" and are not used as base versions.  As a result, the base version is calculated as 0.1.0.

Is there a way to tell GitVersion to always look at the `production` branch when calculating base versions?

**Comment by pdeffendol** [comment]
![cdraw](https://cloud.githubusercontent.com/assets/8208/17673954/9e8134a8-62e0-11e6-9305-49acc9782df4.png)

For example, running GitVersion on `master` after v3.20.0 is tagged on `production` should result in `3.21.0-unstable.1` or similar.

**Comment by JakeGinnivan** [comment]
This is not something which is supported out of the box. My only suggestion is that we can add another strategy similar to https://github.com/GitTools/GitVersion/blob/master/src/GitVersionCore/VersionCalculation/DevelopVersionStrategy.cs#L13

Then introduce some configuration to specify that tags on this branch should be included as base versions. The issue then comes to commit counting, unsure if the current approach will work with your flow. 
Did you want to spike something out and see what happens?

**Comment by pdeffendol** [comment]
The commit counting is definitely an issue.  I'd probably rather push that team to change their workflow.

Thanks for the feedback - if I do have anything in the future I'll add it here.
