### ISSUE TITLE
The argument /c should invalidate the cache file

### ISSUE THREAD

**Issue by taborda** [GitTools/GitVersion#1010]
If i understand this argument correctly, it specifies the commit id to calculate the version from.
The problem is when using it, GitVersion returns the last cached result.

It works only after deleting the cache file.

**Comment by asbjornu** [comment]
@taborda As I suggested in https://github.com/GitTools/GitVersion/issues/870#issuecomment-221521424, we need to include the whole command line argument string passed to `GitVersion.exe` in the cache key. Are you up for a PR on that? :smiley:

**Comment by taborda** [comment]
I can try :)

Should we just use the command line arguments as they are issued or should we build some string from the arguments/value parsed?

If so, should it use reflection to get the fields/values?

**Comment by asbjornu** [comment]
I'm not sure, but I think we can use the verbatim argument string without any further logic. 

@GitTools/developers, do you see any issue with this approach? Are there any command line arguments that should be excluded from cache key computation? On the top of my mind, I can't think of any.

**Comment by qetza** [comment]
An argument to force not using the cache like `/nocache` could also be useful when you are doing some tests to find the correct configuration you want.

**Comment by asbjornu** [comment]
@qetza I would be happy to accept a PR implementing that! :smiley:

**Comment by ferventcoder** [comment]
I found this when exploring having a command that cleans out the cache, this seems to be the same thing. Subscribing to this. 👍

**Comment by asbjornu** [comment]
`nocache` was implemented in #1020. Closing.
