### ISSUE TITLE
Output properties file with GitVersionTask for CI consumption

### ISSUE THREAD

**Issue by AGBrown** [GitTools/GitVersion#1016]
In the docs it says that GitVersionExe can output a java properties file for consumption by Jenkins, for instance. However GitVersionTask cannot do this.

Workaround: it is possible to add a Target to the msbuild file (csproj or other) which will write the properties to a properties file of the desired format. However it would be better to be able to set a build property for msbuild which would allow this to happen.

Benefit: This will allow the GitVersionTask NuGet to be used in an MsBuild project which can then output properties to be consumed by CI tools. As it is, both GitVersionTask and GitVersionExe have to be present in the build job, or the workaround has to be manually added to the msbuild file.

ref. [Gitter chat](https://gitter.im/GitTools/GitVersion?at=57bafc0987f779f069199e66):

> Andrew Brown @AGBrown Aug 22 14:20
> If I'm running GitVersionTask inside my MSBuild, should it output a Jenkins gitversion.properties file (like it says here: http://gitversion.readthedocs.io/en/latest/build-server-support/build-server/jenkins/), or do I also need to run GitVersion.exe in its own build step?
> The logs indicate that it knows about Jenkins, as it logs " INFO [08/22/16 14:03:21:38] Applicable build agent found: 'Jenkins'."
> 
> Asbjørn Ulsberg @asbjornu Aug 22 14:32
> @AGBrown I’m not intimately familiar with Jenkins, but you can see the code for the build server provider here: https://github.com/GitTools/GitVersion/blob/master/src/GitVersionCore/BuildServers/Jenkins.cs
> Looks like it should output a gitversion.properties file
> 
> Andrew Brown @AGBrown Aug 22 14:35
> @asbjornu thank you - That's what I thought, but I'm not seeing it written to the workspace. I'm seeing Jenkins recognised in the log, and later in the log I see it say "Executing GenerateBuildLogOutput for 'Jenkins'.", and it logs all the outputs into the log (like GitVersion_Major=0), but no gitversion.properties file
> 
> Gary Ewan Park @gep13 Aug 22 14:35
> @AGBrown @asbjornu only if Output = BuildServer:
> https://github.com/GitTools/GitVersion/blob/35c696aa910548165b120fe293c8ee09249b4440/src/GitVersionExe/SpecifiedArgumentRunner.cs#L35
> which I don't think it will be when running GitVersionTask?!?
> or can you set that property on the Task?
> 
> Andrew Brown @AGBrown Aug 22 14:36
> I could do, but I wonder if that is a GitVersionExe only feature?
> or is there no difference between the .exe and the GitVersionTask.dll in the nuget?
> Seems like GitVersionTask.csproj references GitVersionCore, not GitVersionExe, so the SpecifiedArgumentRunner is out of the picture.
> 
> Asbjørn Ulsberg @asbjornu Aug 22 14:43
> Hmyea, the functionality discrepancy between task and exe is unfortunate. See #883.
> 
> Andrew Brown @AGBrown Aug 22 14:45
> @asbjornu, @gep13 thank you both for your help. At least I now have an idea of what yak I have to shave to output the version numbers to the jenkins environment variables
> 
> Asbjørn Ulsberg @asbjornu Aug 22 14:45
> @AGBrown We would be eternally greatful for a PR tackling this.

**Comment by asbjornu** [comment]
This is somewhat related to #983.
