### ISSUE TITLE
Assembly attributes are duplicated

### ISSUE THREAD

**Issue by jakubro** [GitTools/GitVersion#1025]
Assembly version attributes are not matched when they contain the trailing `Attribute` postfix. Furthermore attributes are duplicated as shown in example which makes it impossible to compile the solution.

This incorrect behavior occurs when using the command line tool v3.6.1.

**Current behavior**

Excerpt from AssemblyInfo.cs
```cs
[assembly: AssemblyVersionAttribute("1.0.5")]
[assembly: AssemblyFileVersionAttribute("1.0.5")]
[assembly: AssemblyInformationalVersionAttribute("1.0.5")]
```

After executing `GitVersion.exe /updateassemblyinfo` this is the resulting AssemblyInfo.cs:

```cs
[assembly: AssemblyVersionAttribute("1.0.5")]
[assembly: AssemblyFileVersionAttribute("1.0.5")]
[assembly: AssemblyInformationalVersionAttribute("1.0.5")]

[assembly: AssemblyVersion("0.1.0.0")]
[assembly: AssemblyInformationalVersion("0.1.0+0.Branch.master.Sha.6d96beb1cc51db3c0b4c52a42b039741e7463fc9")]
[assembly: AssemblyFileVersion("0.1.0.0")]
```

**Expected behavior**

Resulting AssemblyInfo.cs should look like this:
```cs
[assembly: AssemblyVersionAttribute("0.1.0.0")]
[assembly: AssemblyFileVersionAttribute("0.1.0+0.Branch.master.Sha.6d96beb1cc51db3c0b4c52a42b039741e7463fc9")]
[assembly: AssemblyInformationalVersionAttribute("0.1.0.0")]
```

**Comment by embix** [comment]
The detection is a bit brittle, I just got an "Duplicate 'AssemblyInformationalVersion' attribute" because I had a redundant parenthesis `[assembly: AssemblyInformationalVersion(("1.0.1"))]`.

**Comment by asbjornu** [comment]
@embix: Yes, the detection is brittle because it's just a few dumb regexes. 😕
