### ISSUE TITLE
Got a SIGABRT under mono (ubuntu 16.04)

### ISSUE THREAD

**Issue by zlolik** [GitTools/GitVersion#1030]
I have downloaded GitVersion_3.6.3.zip from https://github.com/GitTools/GitVersion/releases/latest
Under Windows 7 it works ok.
Under Ubuntu 16.04 I tried this:
```
sudo apt-get install mono
cd /d/bin/gitversion-3.6.3
mono GitVersion.exe   # got a SIGABRT
sh -c "MONO_LOG_LEVEL=debug mono GitVersion.exe 2>&1" > gitversion3.6.3_ubuntu16.04_log.txt
mono --version
Mono JIT compiler version 4.2.1 (Debian 4.2.1.102+dfsg2-7ubuntu4)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	LLVM:          supported, not enabled.
	GC:            sgen
```
Detailed logfile: [gitversion3.6.3_ubuntu16.04_log.txt](https://github.com/GitTools/GitVersion/files/444297/gitversion3.6.3_ubuntu16.04_log.txt)
What am I doing wrong?

**Comment by JakeGinnivan** [comment]
@asbjornu any ideas?

**Comment by asbjornu** [comment]
Hm, this is strange. We are, after all, dogfooding the executable in the Travis build. I wonder if we should expand the matrix of OS and Mono versions we're testing on.

**Comment by asbjornu** [comment]
@zlolik Seems like the [`libmono-system-core4.0-cil` package](http://packages.ubuntu.com/trusty/libmono-system-core4.0-cil) is missing by default on Ubuntu. Can you install it and see if that helps in any way? The error message causing the SIGABRT is this:

```
Mono: The following assembly referenced from /d/bin/gitversion-3.6.3/GitVersion.exe could not be loaded:
     Assembly:   System.Core    (assemblyref_index=1)
     Version:    4.0.0.0
     Public Key: b77a5c561934e089
```

**Comment by zlolik** [comment]
Hm, interesting, I've tried on another notebook with the same ubuntu-16.04-server install but with lubuntu-desktop installed - and latest version are ok - 3.6.3, 3.6.4., 4.0.0-beta0007.

**Comment by zlolik** [comment]
After `sudo apt-get install libmono-system-core4.0-cil`:
`System.DllNotFoundException: lib/linux/x86_64/libgit2-381caf5.so`

To see more `MONO_LOG_LEVEL=debug mono /d/bin/gitversion-3.6.3/GitVersion.exe`
`Mono: DllImport error loading library '/d/bin/gitversion-3.6.3/lib/linux/x86_64/libgit2-381caf5.so': 'libcurl.so.4: cannot open shared object file: No such file or directory'.`

After `sudo apt-get install libcurl3` - everything is ok!

**Comment by asbjornu** [comment]
@zlolik Excellent! It would be good to have #994 implemented to simplify the installation on Debian based systems like Ubuntu. However, if everything is working, can this issue now be closed?

**Comment by zlolik** [comment]
@asbjornu Sure. Thank you for help!
