### ISSUE TITLE
Change default versioning mode in v4

### ISSUE THREAD

**Issue by asbjornu** [GitTools/GitVersion#1038]
Seeing how often it occurs that the default `mode` of `ContinuousDelivery` leads to duplicate version numbers and the havoc it can lead to in naïve release management processes, I'm wondering if we should change the default mode to `ContinuousDeployment` in version 4?

I do understand that a new default mode is also going to cause problems for those who expect it to be `ContinuousDelivery`, but in that case I think it's better to default and err on the safe side of creating too many (unique) versions than the current, where collisions happen all too often.

@GitTools/developers, @GitTools/owners: Thoughts?

**Comment by GeertvanHorrik** [comment]
You mean when you create a release, then start counting for the new one, then release a hotfix and the counter starts again?

**Comment by asbjornu** [comment]
@GeertvanHorrik Yes, something like that. It's a bit surprising to every developer I've talked to about GitVersion that two successive builds of a feature branch end up with the same full semantic version (such as `4.0.2-notification0001`).

**Comment by GeertvanHorrik** [comment]
I am currently facing the same issue. I am working towards v5 of a library and was at 5.-unstable0020. Then I released a hotfix (4.5.1) and counting started at 0 again on the develop branch. Maybe we shouldn't reset develop counter for hotfixes?

**Comment by JakeGinnivan** [comment]
Few things, @GeertvanHorrik try v4 beta, the commit counting has been fixed a lot since v3.

Second, if we were to change the default we should change to Mainline mode. It bumps releases each *merge* not each commit, meaning the bumping is way more consistent. It also bumps pull requests/feature branches per commit because it treats direct commits on a branch as a merge. IMO Mainline mode feels really natural and takes the best of both modes.

**Comment by asbjornu** [comment]
@JakeGinnivan By your description, I agree that `mode: Mainline` sounds like a sensible default in v4. Do we need to have any defaults in to override it on certain branches (like it is for `develop` in v3)?

**Comment by JakeGinnivan** [comment]
I have no idea how mainline mode works with GitFlow. Mainline can only be set at the top level, gitversion will give you an error if you try to set on a branch.

**Comment by maxraab** [comment]
@JakeGinnivan Is there a roadmap for the v4 release?

**Comment by gep13** [comment]
@JakeGinnivan @asbjornu I have no issues with changing the default, since this is a major revision. What I would say though is that we would need to document how people who are happy with the current default can get back to the same setup once they upgrade to v4.

**Comment by pascalberger** [comment]
Not sure about this. While default certainly can be changed in a major release, IMHO default should be suitable for the most common workflow. Do you think a mainline compatible workflow is more common than GitFlow and similar?

**Comment by asbjornu** [comment]
@pascalberger Not sure what workflow is most common, but even with GitFlow, I've seen the current default lead to duplicate version numbers (on feature branches, hotfixes, etc.), since only `develop` has `mode: ContinuousDeployment`. Perhaps the right thing to do is to change this around so the default is `mode: ContinuousDeployment`, but overridden to `mode: ContinuousDelivery` on `master`?

**Comment by gep13** [comment]
@asbjornu over at Cake, we run GitFlow and GitVersion, and can honestly say, we have never run into any real issues when using the default configuration that GitVersion offers.

**Comment by JakeGinnivan** [comment]
I think we should just keep the defaults as is. We have made fixes to GitFlow to use alpha instead of unstable and improved commit counting in v4.

Each mode has it's pros/cons.

@maxraab I will create a milestone and sort issues

**Comment by JakeGinnivan** [comment]
I don't think we should change the default, each mode is valid in different scenarios. Happy to continue discussion but i don't think it's worth changing
