### ISSUE TITLE
Custom Branch Names

### ISSUE THREAD

**Issue by roly445** [GitTools/GitVersion#1044]
Hi I'm using v4.0.0-beta.7 and I am not using gitflow.

I have a branch for each of our environments, so:
develop:- code where the developers work from.
staging:- this code is pushed into our staging environment.
master:- this code is pushed into our production environment. 

I do I set up a custom configuration for 'staging' that can be picked up by gitversion?

Thanks

**Comment by asbjornu** [comment]
@roly445 You can [configure](https://gitversion.readthedocs.io/en/latest/configuration/) the regular expressions that should match the branch names for each branch configuration. When you get the regular expression right, it should just be to add the configuration properties you want underneath to adjust GitVersion's behavior according to how you want it to behave for the matched branch(es).

I would assume, though, that GitVersion's default behavior would be a good fit for a `stage` release. What is it you want to change? Also, which version and variant (task or `.exe`) of GitVersion are you using?

**Comment by JakeGinnivan** [comment]
Yeah as @asbjornu says, you can either edit the regex for an existing branch type to use it's configuration or create a new branch type configuration. The docs give you an example of the default config so have a look at that and it should be able to be configured to match your needs.

If not just drop a comment in this issue, going to close for now.
