### ISSUE TITLE
Duplicated version for release branch observed

### ISSUE THREAD

**Issue by eugene-sivachenko** [GitTools/GitVersion#1046]
Hi, 

I am using recent version of gitversion (v4.0.0-beta0007) installed from chocolatey.

In default configuration I observed duplicated FullSemVer for different commits. It seems that first commit in release branch has wrong metadata +1, but should have +0.

Screen shot of my test repository: 

![issue](https://cloud.githubusercontent.com/assets/12886670/18814885/78e09136-8328-11e6-9e2d-9b1c769cbe05.png)

Branches started with 'ver' are auto-generated from FullSemVer variable.

Commit 7842238c9e4777d31cb3c4274949793969e4b9ef on 'release/1.0.0' branch has version '1.0.0-beta.1+1'.
Gitversion generates the same version for commit ad54234fc1329bfd64191b83d08e1fcb491ab7c7. That is why my script cannot add a branch with version - it will be duplicated branch name in git.

But the third commit c5c52f748426f9316e393a585b66818ad2be9d96 has correct version '1.0.0-beta.1+2'

It looks like this is a bug and version for 7842238c9e4777d31cb3c4274949793969e4b9ef  should be '1.0.0-beta.1+0'.

I have attached test repo and script to reproduce this issue in zip archive: 
[test-repo.zip](https://github.com/GitTools/GitVersion/files/491603/test-repo.zip)

Many thanks,
Yevgen.

**Comment by JakeGinnivan** [comment]
Hi @eugene-sivachenko 

Can you create a github repository or even better write a test which reproduces this, I am not a fan of downloading random zip files from issues.

**Comment by JakeGinnivan** [comment]
Though it does look like a legit bug based on your comment.

**Comment by czesiu** [comment]
I think that I have similar problem. Here's the test repository: https://github.com/czesiu/GitVersion.Test

Looks like the problem is related with merge release branch to develop. After this merge and commit something on develop counter on release branch resets.

Here's screen describing problem:
![gitversion](https://cloud.githubusercontent.com/assets/9153975/21546583/f86dfbe4-cddf-11e6-9a1a-c33859516b6a.png)

Take a look at "Third release commit". Before commit #ec1af0d on develop it has proper version: 0.2.0-beta0003, but after this commit version was changed to 0.2.0-beta0003 (merge commit resets counter).

I'm using GitVersion 3.6.4.

**Comment by asbjornu** [comment]
@czesiu: Would it be too much to ask for you to reproduce this in a unit test? It's fairly easy to perform the Git actions required in the `RepositoryFixture` based tests, and that would pinpoint the problem and make it much easier to fix. Also, does upgrading to version 4 of GitVersion help?

**Comment by czesiu** [comment]
I tested on 4.0.0-beta.9 and the same problem occurs.

Here's the unit test:

    [Test]
    public void Test()
    {
        var config = new Config
        {
            VersioningMode = VersioningMode.ContinuousDeployment
        };

        using (var fixture = new EmptyRepositoryFixture())
        {
            // Initial master commit
            fixture.Repository.MakeACommit();

            // Create develop from master
            fixture.Repository.CreateBranch("develop");
            Commands.Checkout(fixture.Repository, "develop");

            // Create release from develop
            fixture.Repository.CreateBranch("release-0.2.0");
            Commands.Checkout(fixture.Repository, "release-0.2.0");

            fixture.AssertFullSemver(config, "0.2.0-beta.0");

            // Make some commits on release
            var releaseCommit1 = fixture.Repository.MakeACommit();
            var releaseCommit2 = fixture.Repository.MakeACommit();

            fixture.AssertFullSemver(config, "0.2.0-beta.2");

            // Merge release to develop
            Commands.Checkout(fixture.Repository, "develop");
            fixture.Repository.Merge(releaseCommit2,
                new Signature(new Identity("czesiu", "czesiu@github.com"), DateTimeOffset.Now),
                new MergeOptions { FastForwardStrategy = FastForwardStrategy.NoFastForward });

            // Make some new commit on release
            Commands.Checkout(fixture.Repository, "release-0.2.0");
            fixture.Repository.MakeACommit();

            fixture.AssertFullSemver(config, "0.2.0-beta.3"); // Here version is ok

            // Make new commit on develop
            Commands.Checkout(fixture.Repository, "develop");
            fixture.Repository.MakeACommit();

            // Checkout to release (no new commits) 
            Commands.Checkout(fixture.Repository, "release-0.2.0");

            fixture.AssertFullSemver(config, "0.2.0-beta.3"); // Shouldly.ShouldAssertException : variables.FullSemVer should be "0.2.0-beta.3" but was "0.2.0-beta.1"
        }
    }

**Comment by czesiu** [comment]
Something new on this topic?

**Comment by asbjornu** [comment]
@czesiu: Sorry, I haven't had time to open up the GitVersion solution in a while, so no time to look at this. Would you be up for the task of providing the failing test and perhaps even a fix for it as a pull request? Just shout out if you wonder about any step of the process, and I'll assist you as best I can. Joining [our Gitter channel](https://gitter.im/GitTools/GitVersion) might give you a bit more immediate response when you're in the middle of it.

**Comment by czesiu** [comment]
I added PR #1136 with test & fix proposition. More info in PR.

**Comment by asbjornu** [comment]
@czesiu: Thanks, excellent!
@eugene-sivachenko: Does #1136 describe and fix your problem as well?

**Comment by czesiu** [comment]
I think we can close this issue. There is no response from @eugene-sivachenko from about 4 months.

**Comment by mlooise** [comment]
Hi All,

I know this thread is closed, but I think i'm having a problem with this 'fix'. With gitversion 3.6.4 I had some problems with commits as 'merge branch release/1.2 with ...' being treated as a versionsource. 

This was fixed in 4.0.0-beta9. Now however when I update to 4.0.0-beta10 i suddenly get a commitcount since versionsource of a way to high. It looks like it now counts commits of the original source-branch or something. I see a lot of `Merge base was due to a forward merge, next merge base is `. What is this log-message telling me? I am currenlty on release but I also see a lot of these messages concerning branches nog yet in this release (not yet finished features) like : 


>     INFO [02/26/17 16:44:02:25] Begin: Finding merge base between 'release/1.2' and 'feature/xxx'.
>       INFO [02/26/17 16:44:02:26] Found merge base of 795757e5560ab97813e06d3c4cf00e6d0acfd9d2
>       INFO [02/26/17 16:44:02:27] Merge base was due to a forward merge, next merge base is 36e431de73515051717cb6269e03efb72570f5ee
>       INFO [02/26/17 16:44:02:28] Merge base was due to a forward merge, next merge base is c2e089ab63ab450f4f2164e7b250cf0953c979e5
>     INFO [02/26/17 16:44:02:29] End: Finding merge base between 'release/1.2' and 'feature/xxx'. (Took: 40.00ms)


We currently have this behaviour on our internal TFS-Git repo. How would I go about investigating this. I'm having a lot of difficulties understanding the behavour of gitversion in this case. 

Regards, Martin

**Comment by czesiu** [comment]
Finding merge base is a process which searches for all merges beetwen 2 branches from newest to oldest. Oldest merge base is a commit from first branch, from which second branch was branched off - place from which second branch was created.

**Example:**
There are 2 branches. Blue is develop. Violet is release. There are 2 merge base beetwen this branches marked as 1 and 2.
![f86dfbe4-cddf-11e6-9a1a-c33859516b6a](https://cloud.githubusercontent.com/assets/9153975/23476732/03c258c0-febc-11e6-8d4a-442af59d4d89.png)

Log for this 2 branches will look similiar to:

    INFO [02/26/17 16:44:02:25] Begin: Finding merge base between 'release/2.0' and 'develop'.
      INFO [02/26/17 16:44:02:26] Found merge base of (sha of commit marked by 2)
      INFO [02/26/17 16:44:02:27] Merge base was due to a forward merge, next merge base is (sha of commit marked by 1)
    INFO [02/26/17 16:44:02:29] End: Finding merge base between 'release/1.2' and 'feature/xxx'. (Took: 40.00ms)

Could you post image representing your commits and branch structure ('release/1.2' and 'feature/xxx') which will contain this 3 commits from log?

Or maybe you can reproduce this structure in a unit test? [Here's an example](https://github.com/GitTools/GitVersion/blob/master/src/GitVersionCore.Tests/IntegrationTests/ReleaseBranchScenarios.cs#L370)

**Comment by JakeGinnivan** [comment]
@czesiu I have revised your fix at https://github.com/GitTools/GitVersion/pull/1179, if you could have a look and see what you think that would be great

**Comment by czesiu** [comment]
@JakeGinnivan Looks ok. All tests passed and I also tested your changes on my problematic repository and version is same as in my fix. If there will be new problems I will report it.
