### ISSUE TITLE
Global Parameters not accessible in VS 2015 post build event.

### ISSUE THREAD

**Issue by torsten-github** [GitTools/GitVersion#1051]
Using GitVersionTask 3.6.3 Nuget Package in a Visual Studio 2015 Windows Application project and a Post-build event commandline (project properties) does not give a version number.

`Echo GitVersion: $(GitVersion_InformationalVersion)` 

But running the same build on a **TFS Build Server agent (vnext)** gives the correct version number.

Seems that the global variable is not set, when running a build on a developer machine.
VS variables like $(ConfigurationName) work fine.

**Comment by JakeGinnivan** [comment]
In VSTS we write commands out to tell VSTS about new environmental variables. 

Is this in a single .csproj file?

**Comment by torsten-github** [comment]
Yes, a single csproj file. 
Not quite shure what you mean. I only know of single project files. but we habve ofcourse multiple projects in a solution. But I'm talking about a single csproj file.

My problem is straight forward. Maybe your package doesn't support this:
On the build server (VSTS) the variable is set.
On developer machine (local Visual Studio installation) the global variables are not set.

BTW: Since we have a lot of small projects to build (in VSTS) I hade to switch a way from the Nuget package and try to use the command line tool for now, since each project is using 30..45 sec only for versioning.

PS: I realy like GitVersion. Thanks.
Is there a other channel for support communication?

**Comment by pascalberger** [comment]
You use the GitVersion NuGet package locally but on the build server the command line tool?

Regarding support, you can also join our [Gitter channel](https://gitter.im/GitTools/GitVersion).

**Comment by torsten-github** [comment]
I used the Nuget package on both (local and build server). Now I removed the package and use the command line tool.
In both cases I have the same problem:
On the build server the global variables work fine. 
On the local developer machine the $(GitVersion__InformationalVersion) is not set.
I use the Pre-build and Post-build events in the .csproj file:
Pre-build: `$(SolutionDir)\..\_Automation\GitVersion\GitVersion.exe /output buildserver /nofetch`
Post-build: `makensis.exe" /DVER=$(GitVersion_InformationalVersion) _installer.nsi`

**Comment by pascalberger** [comment]
Please note that the `buildserver` flag works differently on a real build server and a local developer machine (eg. for TFS vNext it checks for the `TF_BUILD` environment variable).

How are you building on the local machine? The same way as on the build server (eg. by calling msbuild) or by building from Visual Studio?

I'm not sure if Pre- and Post-builds run in individual processes from Visual Studio, and therefore the environment variable won't be available in the Post-build.

@gep13 @asbjornu Any idea?

**Comment by JakeGinnivan** [comment]
Correct

The way the /buildserver works is that it writes out to the console commands which are picked up by the build server. Which in turn sets environmental variables. Either use the task or you need to call gitversion from a build script without `/output buildserver` and parse the json response yourself.

This issue is pretty old now so closing, if you have futher questions just open a new issue or post in here.
