### ISSUE TITLE
Write the tag for the current commit to the GitVersion properties, if it exists

### ISSUE THREAD

**Issue by AGBrown** [GitTools/GitVersion#1052]
The current output (in the cache files) looks like the below. This doesn't include the tag for the commit, even if it is tagged.

Knowing the tag for the current commit would be very useful. This could be extended to knowing the tag used to create the current version number, and an additional property saying if the tag describes the current commit exactly.

Use case: I can use the tag or the abbreviated sha (in that order of preference) to then refer to the exact commit on the git server. e.g.:

 - https://github.com/GitTools/GitVersion/tree/a61138a8 (if this commit is not tagged)
 - https://github.com/GitTools/GitVersion/tree/v4.0.0-beta.7 (if it is tagged)

My current workaround (when using GitVersionTask with msbuild files) is to use an msbuild Exec with `git describe --tags --exact-match`. If it doesn't error then I use the output, otherwise I use `GitVersion_Sha`. I don't think that outputting this property should be limited to GitVersionTask though as I can see it being useful for tools that use Core as well.

This is the current output for a commit which is sha `fbd3f8dc`, branch `master` and tag `v1.3.2`. There is no property to get to the tag for the commit.

```
Major: 1
Minor: 3
Patch: 2
PreReleaseTag: 
PreReleaseTagWithDash: 
PreReleaseLabel: 
PreReleaseNumber: 
BuildMetaData: ''
BuildMetaDataPadded: ''
FullBuildMetaData: Branch.master.Sha.fbd3f8dce7e56665ee9e274ffb32d95b2596910c
MajorMinorPatch: 1.3.2
SemVer: 1.3.2
LegacySemVer: 1.3.2
LegacySemVerPadded: 1.3.2
AssemblySemVer: 1.3.2.0
FullSemVer: 1.3.2
InformationalVersion: 1.3.2+Branch.master.Sha.fbd3f8dce7e56665ee9e274ffb32d95b2596910c
BranchName: master
Sha: fbd3f8dce7e56665ee9e274ffb32d95b2596910c
NuGetVersionV2: 1.3.2
NuGetVersion: 1.3.2
CommitsSinceVersionSource: 4
CommitsSinceVersionSourcePadded: 0004
CommitDate: 2016-09-21
```

**Comment by JakeGinnivan** [comment]
This is similar to #901. Would you be able to submit a pull request, if you need a hand just ask on that issue or drop into the gitter channel
