### ISSUE TITLE
Remove commas from tags section in nuspec

### ISSUE THREAD

**Issue by gep13** [GitTools/GitVersion#1055]
When the latest package version was pushed to Chocolatey, it was met with this error:

![image](https://cloud.githubusercontent.com/assets/1271146/19035887/4b1eec92-8964-11e6-83df-8244f6f24083.png)

https://chocolatey.org/packages/GitVersion.Portable/3.6.3

Upon checking, this indeed correct for both Chocolatey and NuGet:

![image](https://cloud.githubusercontent.com/assets/1271146/19035899/5fe8ad20-8964-11e6-9088-be6fd312f0a1.png)

https://docs.nuget.org/ndocs/schema/nuspec

I will send a PR to remove the commas, and I will manually modify the 3.6.3 package version on Chocolatey so that it goes through validation

**Comment by pascalberger** [comment]
Fixed with #1056
