### ISSUE TITLE
GitVersionTask not getting restored using Project.json

### ISSUE THREAD

**Issue by tapvirvirk** [GitTools/GitVersion#1060]
Hi,

I'm trying the same and getting the below error ,
Restoring packages for C:\project.json...
GitVersionTask 4.0.0-beta0007 is not compatible with .NETFramework,Version=v4.5.
Some packages are not compatible with .NETFramework,Version=v4.5.
GitVersionTask 4.0.0-beta0007 is not compatible with .NETFramework,Version=v4.5 (win).
Some packages are not compatible with .NETFramework,Version=v4.5 (win).
GitVersionTask 4.0.0-beta0007 is not compatible with .NETFramework,Version=v4.5 (win-x64).
Some packages are not compatible with .NETFramework,Version=v4.5 (win-x64).
GitVersionTask 4.0.0-beta0007 is not compatible with .NETFramework,Version=v4.5 (win-x86).
Some packages are not compatible with .NETFramework,Version=v4.5 (win-x86).

My project.json file looks like below,
{

"frameworks": {

"net452": {
  "imports": "portable-net+sl+win+wpa+wp"
}
},
"runtimes": {
"win": {},
"win-x86": {},
"win-x64": {}
},
"dependencies": {
"AWSSDK.Core": "3.3.0.2",
"AWSSDK.S3": "3.3.0.1",
"log4net": "2.0.5",
"GitVersionTask" : "4.0.0-beta0007"
}
}
Can you please help me out in retoring the GitVersionTask using project.json?

**Comment by twsouthwick** [comment]
This is fixed with #1040, but requires a new build to be released. @JakeGinnivan Is there a date we can expect a new prerelease of GitVersionTask?

**Comment by JakeGinnivan** [comment]
This should all be released and fixed. Let me know if not
