### ISSUE TITLE
Package GitVersionTask is not compatible with .NETCoreApp,Version=v1.0 or .NETFramework,Version=v4.6

### ISSUE THREAD

**Issue by cedric-cazin** [GitTools/GitVersion#1061]
Hello
I am starting a new project on VS2015 with Asp.net 
and i wanted to have GitVersion
But I got this error

with .net core
Package GitVersionTask 4.0.0-beta0007 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0)

or 

with .net
Package GitVersionTask 3.6.4 is not compatible with net46 (.NETFramework,Version=v4.6).

Can you help?

Thanks Regards

**Comment by GeertvanHorrik** [comment]
I am having the same issues:

- GitVersionTask 3.6.5
- .NET 4.6.2 app

**Comment by GeertvanHorrik** [comment]
Installing 4.0.0-beta0009 solves the issue.

**Comment by Rajivhost** [comment]
The 4.0.0-beta0009 installation works, but I can't see my assembly tagged.

**Comment by asbjornu** [comment]
@Rajivhost: What do you mean with "tagged"?

**Comment by JakeGinnivan** [comment]
Looks like v4 resolves this issue.

@Rajivhost can you open up a new issue with more details if you are still having issues. Thanks
