### ISSUE TITLE
NuGet pre-release

### ISSUE THREAD

**Issue by shmulikah** [GitTools/GitVersion#1062]
Hi,
love your tool but currently struggling with overriding the InformationalVersion variable.
i want to override it with my way of pre-release tag. i saw few threads of issues here but i dont know if the issue was resolved.
can you please assist here on how to override the  InformationalVersion which is the "AssemblyInformationalVersion" attribute?

**Comment by asbjornu** [comment]
Have you tried [configuring the `assembly-informational-format`](http://gitversion.readthedocs.io/en/latest/configuration/#assembly-informational-format)?

**Comment by shmullikah** [comment]
i want to insert my own value which i cannot achieve by using one of the existing configuration variables.
i want to pass the following to VSTS gitVersion task:
$(GITVERSION_MajorMinorPatch)-CI-$(build.buildid)

**Comment by shmulikah** [comment]
Any update here? Anyone?

**Comment by asbjornu** [comment]
@shmulikah: I don't think what you ask for is possible. But with https://github.com/GitTools/GitVersion/issues/544#issuecomment-246792230 it might be possible to make it more flexible. As I mention there, pull requests are welcome!

**Comment by asbjornu** [comment]
#1130 should provide the necessary functionality. Closing.
