### ISSUE TITLE
Doesn't work with git worktrees

### ISSUE THREAD

**Issue by AuthorProxy** [GitTools/GitVersion#1063]
On build there is an error while working in git worktree:

> Failed to prepare or find the .git directory in path

```
MyProject/
-- .git/
-- folder_with_project/
---- MyProj.proj
-- worktree/
-- MySln.sln
```

Inside worktree the same structure as in `MyProject/` directory

**Comment by ghuntley** [comment]
Confirmed.

![image](https://user-images.githubusercontent.com/127353/31337174-cfbc3c24-ad45-11e7-8a83-998eb8fcde25.png)

**Comment by ermshiperete** [comment]
Would be nice if GitVersion would work with worktrees.

**Comment by ermshiperete** [comment]
> Inside worktree the same structure as in `MyProject/` directory

The difference is that instead of a .git subdirectory, in a worktree there is a file `.git` that contains the path to the main working tree:

```
gitdir: /path//to/MyProject/.git/worktrees/worktree
```

**Comment by MarkBinghamS** [comment]
This is a lot closer to working now.

This is the output I get:-
INFO [08/19/19 14:55:20:09] Working directory: C:\worktreedir
INFO [08/19/19 14:55:20:10] IsDynamicGitRepository: False
INFO [08/19/19 14:55:20:11] Returning Project Root from DotGitDirectory: C:\repodir\.git\worktrees\worktreedir - C:\repodir\.git\worktrees
INFO [08/19/19 14:55:20:11] Running on Windows.
INFO [08/19/19 14:55:20:13] IsDynamicGitRepository: False
INFO [08/19/19 14:55:20:13] Returning Project Root from DotGitDirectory: C:\repodir\.git\worktrees\worktreedir - C:\repodir\.git\worktrees
INFO [08/19/19 14:55:20:13] Project root is: C:\repodir\.git\worktrees
INFO [08/19/19 14:55:20:13] DotGit directory is: C:\repodir\.git\worktrees\worktreedir
ERROR [08/19/19 14:55:20:13] An unexpected error occurred:
System.ArgumentException: Value does not fall within the expected range.
   at GitVersion.GitVersionCacheKeyFactory.CalculateDirectoryContents(String root)
   at GitVersion.GitVersionCacheKeyFactory.GetGitSystemHash(GitPreparer gitPreparer)
   at GitVersion.GitVersionCacheKeyFactory.Create(IFileSystem fileSystem, GitPreparer gitPreparer, Config overrideConfig
, ConfigFileLocator configFileLocator)
   at GitVersion.ExecuteCore.ExecuteGitVersion(String targetUrl, String dynamicRepositoryLocation, Authentication authentication, String targetBranch, Boolean noFetch, String workingDirectory, String commitId, Config overrideConfig, Boolean
 noCache)
   at GitVersion.SpecifiedArgumentRunner.Run(Arguments arguments, IFileSystem fileSystem)
   at GitVersion.Program.VerifyArgumentsAndRun()
INFO [08/19/19 14:55:20:13]
INFO [08/19/19 14:55:20:13] Attempting to show the current git graph (please include in issue):
INFO [08/19/19 14:55:20:13] Showing max of 100 commits
INFO [08/19/19 14:55:20:30] * 8be0661 65 seconds ago  (HEAD -> mybranch, master)

(This is with a newly-created nearly-empty repository in c:\repodir and then running "git worktree add ..\worktreedir mybranch". gitversion works correctly in c:\repodir but not in c:\worktreedir)

**Comment by MarkBinghamS** [comment]
I think that the fix should be in  GitVersion/src/GitVersionCore/GitPreparer.cs .

In GetProjectRootDirectory, Directory.GetParent is used, which is incorrect in the case of worktrees. Would creating a Repository and calling Info.WorkingDirectory not be more reliable/correct?

**Comment by ermshiperete** [comment]
#1759 will fix this. #1792 is probably just a cosmetic fix.
