### ISSUE TITLE
Version calculation performance on tfs build

### ISSUE THREAD

**Issue by IAfanasov** [GitTools/GitVersion#1065]
Hi guys!

tnx for the tool!

I use GitVersionTask nuget package and have problem with really slow version calculation on the build sever. In total it (version calc) takes up to 10 minutes. For some reason GitVersion firstly get all commits and then filter them by commit date. It adds up several minutes. Also it branching same thing 3 times. I didn't get why it needs even one brunching. Tried to find some configuration tweeks in [documentation](https://gitversion.readthedocs.io/en/latest/configuration/) without any success. Is it possible to optimize performance of GitVersion?

[Extract from VSO log attached](https://github.com/GitTools/GitVersion/files/519435/VSOLog.txt)

**Comment by normanhh3** [comment]
I"m seeing similarly long times and the one section that seems to be taking up the most time shows up as this in the log:

`2018-01-11T13:36:06.9090877Z INFO [01/11/18 8:36:06:90] Begin: Calculating base versions
 
2018-01-11T13:37:50.1101969Z   INFO [01/11/18 8:37:50:11] Fallback base version: 0.1.0 with commit count source 11812048b0b32dfac4f661d54bbe31ab6428ed87
 
2018-01-11T13:40:54.6097161Z   INFO [01/11/18 8:40:54:60] Base version used: Fallback base version: 0.1.0 with commit count source 11812048b0b32dfac4f661d54bbe31ab6428ed87
 
2018-01-11T13:40:54.6097161Z INFO [01/11/18 8:40:54:60] End: Calculating base versions (Took: 287,700.63ms)`

Any ideas why this might be taking a long time?

I'm running on a Windows 8-based Build Agent right now.

**Comment by normanhh3** [comment]
Turns out that this PR seems to have resolved the issue for us.  https://github.com/GitTools/GitVersion/pull/1100

**Comment by asbjornu** [comment]
Ok, great. Closing.
