### ISSUE TITLE
Create a new `GitVersion.NugetCompatibleVersion` variable

### ISSUE THREAD

**Issue by nshenoy** [GitTools/GitVersion#1067]
As referenced by [issue 1359 in the NuGet repo](https://github.com/NuGet/Home/issues/1359#issuecomment-153477217), there has been a longstanding bug in NuGet where prerelease tags cannot exceed 20 characters. It would be great to create a new `GitVersion.NugetCompatibleVersion` variable which will do some maths and spit out a NuGet friendly string if a prerelease tag is found (i.e. the presence of a `-`, for example). This would allow us to easily use the variable in build steps when creating a NuGet package with `nuget pack --version` .

**Comment by aarondandy** [comment]
There are some other restrictions too:

**Comment by pascalberger** [comment]
See also #608 and #781 which are different cases where the generated version number is not compatible with NuGet.

**Comment by nshenoy** [comment]
With the RTM of NuGet 3.5.0, which supports SemVer 2.0, this is issue is irrelevant now. I'll close this.

**Comment by asbjornu** [comment]
@nshenoy: Excellent, thanks for the update and for closing the issue!
