### ISSUE TITLE
Release version increment based on commits

### ISSUE THREAD

**Issue by pascalnaber** [GitTools/GitVersion#1068]
After creating a new release branch. In this sample 0.7.0, Gitversion 4.0.0 beta 7 returns 0.7.0-beta0001 as NuGetVersionV2. Which is what I expected.
After committing a change to this branch the NuGetVersionV2 is not changed (actually not any version is changed). I expected 0.7.0-beta0002. 
Why does Gitversion not increment the version? 
What is the way to get the expected version (0.7.0-beta0002)?

Below the output after creating the 0.7.0 release and the version after a commit.
{
  "Major":0,
  "Minor":7,
  "Patch":0,
  "PreReleaseTag":"beta.1",
  "PreReleaseTagWithDash":"-beta.1",
  "PreReleaseLabel":"beta",
  "PreReleaseNumber":1,
  "BuildMetaData":0,
  "BuildMetaDataPadded":"0000",
  "FullBuildMetaData":"0.Branch.release/v0.7.0.Sha.7b7f627c237425b32d91270fe2724
2801bf8a509",
  "MajorMinorPatch":"0.7.0",
  "SemVer":"0.7.0-beta.1",
  "LegacySemVer":"0.7.0-beta1",
  "LegacySemVerPadded":"0.7.0-beta0001",
  "AssemblySemVer":"0.7.0.0",
  "FullSemVer":"0.7.0-beta.1+0",
  "InformationalVersion":"0.7.0-beta.1+0.Branch.release/v0.7.0.Sha.7b7f627c23742
5b32d91270fe27242801bf8a509",
  "BranchName":"release/v0.7.0",
  "Sha":"7b7f627c237425b32d91270fe27242801bf8a509",
  "NuGetVersionV2":"0.7.0-beta0001",
  "NuGetVersion":"0.7.0-beta0001",
  "NuGetPreReleaseTagV2":"beta0001",
  "NuGetPreReleaseTag":"beta0001",
  "CommitsSinceVersionSource":0,
  "CommitsSinceVersionSourcePadded":"0000",
  "CommitDate":"2016-10-10"
}

{
  "Major":0,
  "Minor":7,
  "Patch":0,
  "PreReleaseTag":"beta.1",
  "PreReleaseTagWithDash":"-beta.1",
  "PreReleaseLabel":"beta",
  "PreReleaseNumber":1,
  "BuildMetaData":1,
  "BuildMetaDataPadded":"0001",
  "FullBuildMetaData":"1.Branch.release/v0.7.0.Sha.bc30911b4e34183ebeaa58fdc8b41
ec381a682e0",
  "MajorMinorPatch":"0.7.0",
  "SemVer":"0.7.0-beta.1",
  "LegacySemVer":"0.7.0-beta1",
  "LegacySemVerPadded":"0.7.0-beta0001",
  "AssemblySemVer":"0.7.0.0",
  "FullSemVer":"0.7.0-beta.1+1",
  "InformationalVersion":"0.7.0-beta.1+1.Branch.release/v0.7.0.Sha.bc30911b4e341
83ebeaa58fdc8b41ec381a682e0",
  "BranchName":"release/v0.7.0",
  "Sha":"bc30911b4e34183ebeaa58fdc8b41ec381a682e0",
  "NuGetVersionV2":"0.7.0-beta0001",
  "NuGetVersion":"0.7.0-beta0001",
  "NuGetPreReleaseTagV2":"beta0001",
  "NuGetPreReleaseTag":"beta0001",
  "CommitsSinceVersionSource":1,
  "CommitsSinceVersionSourcePadded":"0001",
  "CommitDate":"2016-10-17"
}

**Comment by gep13** [comment]
>@pascalnaber said...
actually not any version is changed

That isn't true.

Your version number has gone from:

```
"FullSemVer":"0.7.0-beta.1+0",
"InformationalVersion":"0.7.0-beta.1+0.Branch.release/v0.7.0.Sha.7b7f627c23742
```

to:

```
"FullSemVer":"0.7.0-beta.1+1",
"InformationalVersion":"0.7.0-beta.1+1.Branch.release/v0.7.0.Sha.bc30911b4e341
```

The reason that the NuGetVersion number hasn't changed is because as far as GitVersion, as it is currently configured, you are still working towards beta1.  The beta number won't bump until you tag the release branch to indicate that you have released beta1.

If this is not how you want this to function, then I "think" there are ways to make this happen, but off the top of my head, I am not sure how.  Perhaps @JakeGinnivan @pascalberger or @asbjornu might be able to point you in the right direction.

**Comment by gep13** [comment]
Also, it comes down to the fact that with NuGetVersion2, we are limited by the nuspec specification as to what exactly you can include within the version number.

**Comment by pascalnaber** [comment]
I would really appreciate some pointers in the right direction to get a nuget version like 0.7.0-beta0002.
The current release version is 0.7.0-beta0001. After multiple commits on the release branch the output looks like this:
 "NuGetVersionV2":"0.7.0-beta0001",
 "NuGetVersion":"0.7.0-beta0001",
 "NuGetPreReleaseTagV2":"beta0001",
 "NuGetPreReleaseTag":"beta0001",
 "CommitsSinceVersionSource":2,
 "CommitsSinceVersionSourcePadded":"0002",
It's unclear for me where the 0001 is coming from in 0.7.0-beta0001. Looks like it's CommitsSinceVersionSourcePadded. But than the output of NuGetVersionV2 looks like a bug. It's 0.7.0-beta0001. I expect 0.7.0-beta0002.  
I would like to know how to raise the 0001 in NuGetVersionV2.

**Comment by gep13** [comment]
@pascalnaber Add a tag to the release branch with `0.7.0-beta0001`, this should then bump the beta number.

**Comment by pascalnaber** [comment]
Thanks, this bumps the version indeed. But only for once. The first commit after the tag raised the version to 0002. After the second commit it stays 0002. With this behavior I'm forced to tag the commits on a release. I think it should be possible for GitVersion to raise the number on each commit automatically without tags.

**Comment by gep13** [comment]
@pascalnaber best I can suggest is some additional configuration based on this: http://gitversion.readthedocs.io/en/latest/more-info/incrementing-per-commit/

Personally, I wouldn't want the beta number to change on every commit, but that is just me.

**Comment by JakeGinnivan** [comment]
This is resolved by Mainline mode in v4 I think. Also the ContinuousDeployment mode can also help here.

@pascalnaber can you try v4 beta mainline mode and open a new issue if it does not solve your issue.
