### ISSUE TITLE
Create a GitVersion.PreReleaseLabelWithDash variable

### ISSUE THREAD

**Issue by MrHinsh** [GitTools/GitVersion#1069]
Guys,

 It would be really useful if there was a GitVersion.PreReleaseLabelWithDash variable! This would be the Label but with a single "-" at the front.

GitVersion.PreReleaseLabel: Preview
GitVersion.PreReleaseLabelWithDash: -Preview

For many tools you require to postfix the name / id / key with something to allow you to create multiple streams of the same package. That way I can publish a preview version as well as a production version.

**Comment by asbjornu** [comment]
Two quick questions:

1. Can't you just prefix the dash yourself?
2. Why do you need the label separately from the version number, i.e. why isn't something like `SemVer` which has the label prefixed with dash in it, good enough?

**Comment by MrHinsh** [comment]
Yes I can prefix the Dash but that would require me to run a bunch of scripts after GitVersion to go create this variable. I'm in a continuous delivery environment and have a single build that decides based on the value of PreReleaseLabel if it is a production or non-production build. If non-production I usually have to tag a bunch of places with the re-release label, and many places don't allow spaces. 

Since there are already variables with the "-" added, I thought that it would make sense to have one for the "PreReleaseLabel" as well... Seams like its missing based on an assessment of the other variables...

**Comment by asbjornu** [comment]
Ok. So just to get this correct: If you have a look at [the variables](http://gitversion.readthedocs.io/en/latest/more-info/variables/), they contain these three:

```json
{
  "PreReleaseTag":"beta.1",
  "PreReleaseTagWithDash":"-beta.1",
  "PreReleaseLabel":"beta",
}
```

If I understand you correctly, you want to add a fourth:

```json
{
  "PreReleaseLabelWithDash":"-beta",
}
```

Correct? If so, I would give that a 👍  and welcome a pull request implementing it.
