### ISSUE TITLE
AssemblyVersion not updated to SemVer

### ISSUE THREAD

**Issue by ben-foster-cko** [GitTools/GitVersion#1071]
According to [the docs](https://gitversion.readthedocs.io/en/latest/usage/command-line/):

> AssemblyVersion will be set to the AssemblySemVer variable.
> AssemblyFileVersion will be set to the MajorMinorPatch variable with a appended .0.
> AssemblyInformationalVersion will be set to the InformationalVersion variable.

When I run `gitversion /updateassemblyinfo` I get the following output:

```
{
  "Major":3,
  "Minor":1,
  "Patch":0,
  "PreReleaseTag":"unstable.39",
  "PreReleaseTagWithDash":"-unstable.39",
  "PreReleaseLabel":"unstable",
  "PreReleaseNumber":39,
  "BuildMetaData":"",
  "BuildMetaDataPadded":"",
  "FullBuildMetaData":"Branch.develop.Sha.aaab2e90d7b65a677f73aab9e2df58eb31d7
  "MajorMinorPatch":"3.1.0",
  "SemVer":"3.1.0-unstable.39",
  "LegacySemVer":"3.1.0-unstable39",
  "LegacySemVerPadded":"3.1.0-unstable0039",
  "AssemblySemVer":"3.1.0.0",
  "FullSemVer":"3.1.0-unstable.39",
  "InformationalVersion":"3.1.0-unstable.39+Branch.develop.Sha.xxx...
  "BranchName":"develop",
  "Sha":"aaab2e90d7b65a677f73aab9e2df58eb31d7b267",
  "NuGetVersionV2":"3.1.0-unstable0039",
  "NuGetVersion":"3.1.0-unstable0039",
  "CommitsSinceVersionSource":39,
  "CommitsSinceVersionSourcePadded":"0039",
  "CommitDate":"2016-10-23"
}
```

But the `AssemblyVersion` is set to `3.1.0.0` not `3.1.0-unstable.39` which I would expect.

**Comment by kierenj** [comment]
1) "AssemblyVersion will be set to the AssemblySemVer variable."
2) `  "AssemblySemVer":"3.1.0.0",`
3) But the `AssemblyVersion` is set to `3.1.0.0`

Looks like everything works as documented to me?

**Comment by JakeGinnivan** [comment]
Because assembly version is used by .net to validate strong naming versions we were pretty conservative with it. By default we only use MajorMinor and you can make it use majorMinorPatchTag. 

#1145 is a good improvement to this though, going to close this in favor of 1145 which has a resolution to this issue
