### ISSUE TITLE
"Update AssemblyInfo files" effect?

### ISSUE THREAD

**Issue by ygeelen-tb** [GitTools/GitVersion#1076]
We're using the VSTS GitVersion build step as the first step in our build definition.
"0.1.0-unstable.5" is the current SemVer version, but our AssemblyInfo files remain unchanged, is this normal?
The output DLL's File Version and Product Version attributes are changed though as expected.

**Comment by FunnyFry** [comment]
VSTS fetches your repo/branch on the build agent machine and the GitVersion task will search and edit the AssemblyInfo.cs files that it finds and update them there. It will not push any changes back to your repo after editing these files. The files edited are the ones used when building and thus why you see the correct versioning within your output DLL as intended. 

Does this answer your question? If not please elaborate on what you mean by "*AssemblyInfo files remain unchanged*"

**Comment by ygeelen-tb** [comment]
Yes this answers my question, thanks!
