### ISSUE TITLE
GitPreparer incorrectly throws error of a not existing .git folder in the root of a drive

### ISSUE THREAD

**Issue by neothor** [GitTools/GitVersion#1077]
The following line in GitPreparer removes the last backslash even when it is just the drive, eg: K:\.
```
this.targetPath = targetPath.TrimEnd('/', '\\');
```

The following line than results a null value which results in an exitcode 1
```
var dotGitDirectory = Repository.Discover(targetPath);
```

**Comment by asbjornu** [comment]
@neothor: I've seen this causing problems elsewhere in the codebase as well, so this is certainly something that should be fixed. Are you up for submitting a pull request for this, preferably with a test (first) that exposes the problem?
