### ISSUE TITLE
PreRelease tag inserted on master branch

### ISSUE THREAD

**Issue by mdkf** [GitTools/GitVersion#1084]
We have a repo with 2 branches, master and develop. The develop branch builds are tagged with a pre-release tag, the master branch builds are not. When merging in a commit from develop branch tagged 1.2.0-dev0005b0013 git version tagged the next build of master 1.2.0-dev0005b0014. There are two issues. There should not be a pre-release tag on master, and even if there should have been a pre-release tag , it should not have incremented the last digit of the meta-data. My config is attached.
[GitVersion.txt](https://github.com/GitTools/GitVersion/files/590328/GitVersion.txt)

 Can some one help me debug this? Thanks,
-Michael

**Comment by mdkf** [comment]
Still facing this issue. Here is the simplest test case demonstrating the issue: 
![gitversion](https://cloud.githubusercontent.com/assets/19290661/21059151/2488c366-be0f-11e6-9805-a21227f56152.png). I inserted all of the tags. When GitVersion runs on the merge into master, it suggests using version 1.1.0-dev0002. There should be no prerelease tag, and the version should be either 1.1.0 or 1.0.1. 

> INFO [12/09/16 12:51:31:04] Running against branch: master (81423dcb8f1acf29bd7fbfb71a72e9362d60b043)
INFO [12/09/16 12:51:31:05] Begin: Calculating base versions
  INFO [12/09/16 12:51:31:07] Fallback base version: 0.1.0 with commit count source 694d400f0ad335cfd6f359399b5285de23648b83 (Incremented: None)
  INFO [12/09/16 12:51:31:15] Git tag 'v1.1.0-dev0001': 1.1.0-dev.1 with commit count source 47fa47c1e99fa834d008a529049f771ffc2bf39d (Incremented: 1.1.0-dev.2)
  INFO [12/09/16 12:51:31:18] Git tag 'v1.0.0': 1.0.0 with commit count source dbb6d40342930971cb9655e4588ea515bee7ac33 (Incremented: 1.0.1)
  INFO [12/09/16 12:51:31:21] Git tag 'v0.1.0-dev0001': 0.1.0-dev.1 with commit count source 5c0174fc4563d45f4474b3e55f55fd8e1e8cee9f (Incremented: 0.1.0-dev.2)
  INFO [12/09/16 12:51:31:23] Found multiple base versions which will produce the same SemVer (1.1.0-dev.2), taking oldest source for commit counting (Git tag 'v1.1.0-dev0001')
  INFO [12/09/16 12:51:31:24] Base version used: Git tag 'v1.1.0-dev0001': 1.1.0-dev.1 with commit count source 47fa47c1e99fa834d008a529049f771ffc2bf39d (Incremented: 1.1.0-dev.2)
INFO [12/09/16 12:51:31:24] End: Calculating base versions (Took: 195.80ms)
INFO [12/09/16 12:51:31:25] 2 commits found between 47fa47c1e99fa834d008a529049f771ffc2bf39d and 81423dcb8f1acf29bd7fbfb71a72e9362d60b043

**Comment by mdkf** [comment]
Tried in 4.0 beta with the attached configuration, same result.

[gitversion (2).txt](https://github.com/GitTools/GitVersion/files/646681/gitversion.2.txt)

**Comment by mdkf** [comment]
I wrote a test case for the issue:
```
    [Test]
    public void MergedDevelopBranchesToMasterImpliesRelease()
    {
        using (var fixture = new EmptyRepositoryFixture())
        {
            fixture.Repository.MakeACommit("1");
            fixture.MakeATaggedCommit("1.0.0");

            fixture.BranchTo("develop", "foo");
            fixture.MakeACommit("2");
            fixture.AssertFullSemver(config, "1.1.0-alpha.1");
            fixture.MakeACommit("2.1");
            fixture.AssertFullSemver(config, "1.1.0-alpha.2");
            fixture.Checkout("master");
            fixture.MergeNoFF("develop");

            fixture.AssertFullSemver(config, "1.1.0");      // fails with "1.0.1"

            Console.WriteLine(fixture.SequenceDiagram.GetDiagram());
        }
    }
```

**Comment by mdkf** [comment]
any ideas @pascalberger or @JakeGinnivan ? Is this a bug or have I misunderstood something?

**Comment by asbjornu** [comment]
I think this is a bug, but just out of curiosity: Why are you tagging on develop?

**Comment by mdkf** [comment]
Hi @asbjornu . the tags are created by the build server after gitversion runs so that you can see the version generated from within your git client. Do you think removing the tags would solve the problem?

**Comment by asbjornu** [comment]
@mdkf: Yes, I believe removing the tags would fix the problem.

**Comment by mdkf** [comment]
@asbjornu If you check out the test case I posted above, you can see I only tag the first commit on master and nothing on develop. While it does not insert the pre-release tag, it does insert an incorrect version number on the merge into master, so there is likely more than one problem.

**Comment by pcoombe** [comment]
@mdkf our build server (TFS) was also set to tag on release builds for the dev branch and we experienced similar issues. We have currently turned off tagging dev and it appears to be working better (not perfect), but we probably do need to go back and remove the unstable tags.
Was hoping to wait for v4, as we dont really follow gitflow, hoping the mainline would be a better fit.

**Comment by asbjornu** [comment]
@pcoombe: If you could test out v4 and `mode: Mainline` and report your experience back here, that would be very much appreciated!

**Comment by mdkf** [comment]
It seems mainline only works if you use +semver to bump versions. If you let GitVersion automatically bump versions on a branch according to the increment setting, it will version incorrectly.

**Comment by mdkf** [comment]
Any hope of this getting fixed?

**Comment by JakeGinnivan** [comment]
Hey @mdkf 

The reason you are seeing 1.0.1 in your version is that the last known version for both branches is 1.0.0, then develop has an increment of Minor and master has a increment of Patch.

The way to resolve this is to use `release/` branches, so you branch from `develop` to `release/1.1.0`, then merge that into `master`. GitVersion then can pick up the 1.1.0 from the merge message on master and it will work properly. You could also change the increment from Patch to Minor on master and it would reduce the issue.

> If you let GitVersion automatically bump versions on a branch according to the increment setting, it will version incorrectly.

Unsure what you mean here? Mainline will bump every time a branch is merged into the mainline branch, even if `+semver: ` is used or not.

The issue of the tag not matching (the original issue) I think will be fixed in the next beta release by https://github.com/GitTools/GitVersion/pull/1166. You can give it a go by downloading the build results from https://ci.appveyor.com/project/GitTools/gitversion/build/4.0.0-PullRequest1166.1254.build.1237/artifacts // @pcoombe 

Does that help? In all honesty I am unsure how to fix your example test, there is no way in git to know the merge actually came from develop (this is what we try and infer when we inherit branch configs). This logic is pretty complex and the only reason it works with reasonable success is we pretty much only use it on feature branches, not one of the main branches. Sorry my response took so long, have had a busy few months.

**Comment by mdkf** [comment]
I tested GitVersion_4.0.0-pullrequest1179-1260 and it still attempted to put the pre-release tag on master. 
INFO [03/06/17 23:10:37:16] Found multiple base versions which will produce the same SemVer (1.1.0-dev.2), taking oldest source for commit counting (Git tag 'v1.1.0-dev0001')
  INFO [03/06/17 23:10:37:17] Base version used: Git tag 'v1.1.0-dev0001': 1.1.0-dev.1 with commit count source 47fa47c1e99fa834d008a529049f771ffc2bf39d (Incremented: 1.1.0-dev.2)
INFO [03/06/17 23:10:37:17] End: Calculating base versions (Took: 196.02ms)
ERROR [03/06/17 23:10:37:18] An unexpected error occurred:
System.NotSupportedException: Mainline development mode doesn't yet support pre-release tags on master

**Comment by JakeGinnivan** [comment]
You will have to ignore the commits which are tagged in your gitversion.yml config file.

i.e:

```
ignore:
  sha:
    - 47fa47c1e99fa834d008a529049f771ffc2bf39d
```

**Comment by mdkf** [comment]
@JakeGinnivan Ignoring the commit doesn't fix the issue.

**Comment by JakeGinnivan** [comment]
https://github.com/GitTools/GitVersion/pull/1166 fixes this, will be released shortly

**Comment by mdkf** [comment]
Hi @JakeGinnivan Unfortunately, it's still not fixed.
`D:\Jenkins_Home\workspace\GitVersionDec Master4>"C:\GitVersion_4.0.0-beta0012\GitVersion.exe" /showconfig 
assembly-versioning-scheme: MajorMinorPatch
assembly-file-versioning-scheme: MajorMinorPatch
mode: Mainline
tag-prefix: '[vV]'
continuous-delivery-fallback-tag: ci
major-version-bump-message: '\+semver:\s?(breaking|major)'
minor-version-bump-message: '\+semver:\s?(feature|minor)'
patch-version-bump-message: '\+semver:\s?(fix|patch)'
no-bump-message: '\+semver:\s?(none|skip)'
legacy-semver-padding: 4
build-metadata-padding: 4
commits-since-version-source-padding: 4
commit-message-incrementing: Enabled
branches:
  develop:
    mode: ContinuousDeployment
    tag: alpha
    increment: Minor
    prevent-increment-of-merged-branch-version: false
    track-merge-target: true
    regex: dev(elop)?(ment)?$
    tracks-release-branches: true
    is-release-branch: false
    is-mainline: false
  master:
    mode: Mainline
    tag: ''
    increment: Patch
    prevent-increment-of-merged-branch-version: true
    track-merge-target: false
    regex: master
    tracks-release-branches: false
    is-release-branch: false
    is-mainline: true
  release:
    mode: Mainline
    tag: beta
    increment: Patch
    prevent-increment-of-merged-branch-version: true
    track-merge-target: false
    regex: releases?[/-]
    tracks-release-branches: false
    is-release-branch: true
    is-mainline: false
  feature:
    mode: Mainline
    tag: useBranchName
    increment: Inherit
    prevent-increment-of-merged-branch-version: false
    track-merge-target: false
    regex: features?[/-]
    tracks-release-branches: false
    is-release-branch: false
    is-mainline: false
  pull-request:
    mode: Mainline
    tag: PullRequest
    increment: Inherit
    prevent-increment-of-merged-branch-version: false
    tag-number-pattern: '[/-](?<number>\d+)'
    track-merge-target: false
    regex: (pull|pull\-requests|pr)[/-]
    tracks-release-branches: false
    is-release-branch: false
    is-mainline: false
  hotfix:
    mode: Mainline
    tag: beta
    increment: Patch
    prevent-increment-of-merged-branch-version: false
    track-merge-target: false
    regex: hotfix(es)?[/-]
    tracks-release-branches: false
    is-release-branch: false
    is-mainline: false
  support:
    mode: Mainline
    tag: ''
    increment: Patch
    prevent-increment-of-merged-branch-version: true
    track-merge-target: false
    regex: support[/-]
    tracks-release-branches: false
    is-release-branch: false
    is-mainline: true
ignore:
  sha: []

D:\Jenkins_Home\workspace\GitVersionDec Master4>"C:\GitVersion_4.0.0-beta0012\GitVersion.exe" /output buildserver /diag 
INFO [06/15/17 16:26:43:57] Dumping commit graph: 
INFO [06/15/17 16:26:43:88] *   81423dc 6 months ago  (HEAD -> master, origin/master)
|\  
| * 47fa47c 6 months ago  (tag: v1.1.0-dev0001, origin/develop)
* |   dbb6d40 6 months ago  (tag: v1.0.0)
|\ \  
| |/  
| * 5c0174f 6 months ago  (tag: v0.1.0-dev0001)
|/  
* 694d400 1 year, 9 months ago 

INFO [06/15/17 16:26:43:88] Working directory: D:\Jenkins_Home\workspace\GitVersionDec Master4
INFO [06/15/17 16:26:43:88] IsDynamicGitRepository: False
INFO [06/15/17 16:26:43:90] Returning Project Root from DotGitDirectory: D:\Jenkins_Home\workspace\GitVersionDec Master4\.git - D:\Jenkins_Home\workspace\GitVersionDec Master4
INFO [06/15/17 16:26:43:90] Running on Windows.
INFO [06/15/17 16:26:43:91] Applicable build agent found: 'Jenkins'.
INFO [06/15/17 16:26:43:91] Branch from build environment: master
INFO [06/15/17 16:26:43:91] Begin: Normalizing git directory for branch 'master'
  INFO [06/15/17 16:26:44:03] One remote found (origin -> 'http://git.atg.analog.com/scm/atgap/gitversiondec.git').
  INFO [06/15/17 16:26:44:04] Skipping fetching, if GitVersion does not calculate your version as expected you might need to allow fetching or use dynamic repositories
  INFO [06/15/17 16:26:44:05] Updating local branch refs/heads/master to match ref master
  INFO [06/15/17 16:26:44:09] Creating local branch from remote tracking 'refs/remotes/origin/develop'.
  INFO [06/15/17 16:26:44:14] HEAD points at branch 'refs/heads/master'.
INFO [06/15/17 16:26:44:14] End: Normalizing git directory for branch 'master' (Took: 226.00ms)
INFO [06/15/17 16:26:44:14] IsDynamicGitRepository: False
INFO [06/15/17 16:26:44:14] Returning Project Root from DotGitDirectory: D:\Jenkins_Home\workspace\GitVersionDec Master4\.git - D:\Jenkins_Home\workspace\GitVersionDec Master4
INFO [06/15/17 16:26:44:14] Project root is: D:\Jenkins_Home\workspace\GitVersionDec Master4
INFO [06/15/17 16:26:44:14] DotGit directory is: D:\Jenkins_Home\workspace\GitVersionDec Master4\.git
INFO [06/15/17 16:26:44:21] IsDynamicGitRepository: False
INFO [06/15/17 16:26:44:21] Returning Project Root from DotGitDirectory: D:\Jenkins_Home\workspace\GitVersionDec Master4\.git - D:\Jenkins_Home\workspace\GitVersionDec Master4
INFO [06/15/17 16:26:44:22] IsDynamicGitRepository: False
INFO [06/15/17 16:26:44:22] Returning Project Root from DotGitDirectory: D:\Jenkins_Home\workspace\GitVersionDec Master4\.git - D:\Jenkins_Home\workspace\GitVersionDec Master4
INFO [06/15/17 16:26:44:35] Using latest commit on specified branch
INFO [06/15/17 16:26:44:38] Running against branch: master (81423dcb8f1acf29bd7fbfb71a72e9362d60b043)
INFO [06/15/17 16:26:44:39] Begin: Calculating base versions
  INFO [06/15/17 16:26:44:42] Fallback base version: 0.1.0 with commit count source 694d400f0ad335cfd6f359399b5285de23648b83 (Incremented: None)
  INFO [06/15/17 16:26:44:62] Git tag 'v1.1.0-dev0001': 1.1.0-dev.1 with commit count source 47fa47c1e99fa834d008a529049f771ffc2bf39d (Incremented: 1.1.0-dev.2)
  INFO [06/15/17 16:26:44:64] Git tag 'v1.0.0': 1.0.0 with commit count source dbb6d40342930971cb9655e4588ea515bee7ac33 (Incremented: 1.0.1)
  INFO [06/15/17 16:26:44:66] Git tag 'v0.1.0-dev0001': 0.1.0-dev.1 with commit count source 5c0174fc4563d45f4474b3e55f55fd8e1e8cee9f (Incremented: 0.1.0-dev.2)
  INFO [06/15/17 16:26:44:68] Found multiple base versions which will produce the same SemVer (1.1.0-dev.2), taking oldest source for commit counting (Git tag 'v1.1.0-dev0001')
  INFO [06/15/17 16:26:44:69] Base version used: Git tag 'v1.1.0-dev0001': 1.1.0-dev.1 with commit count source 47fa47c1e99fa834d008a529049f771ffc2bf39d (Incremented: 1.1.0-dev.2)
INFO [06/15/17 16:26:44:69] End: Calculating base versions (Took: 296.00ms)
ERROR [06/15/17 16:26:44:70] An unexpected error occurred:
System.NotSupportedException: Mainline development mode doesn't yet support pre-release tags on master
   at GitVersion.VersionCalculation.NextVersionCalculator.FindMainlineModeVersion(BaseVersion baseVersion, GitVersionContext context)
   at GitVersion.VersionCalculation.NextVersionCalculator.FindVersion(GitVersionContext context)
   at GitVersion.GitVersionFinder.FindVersion(GitVersionContext context)
   at GitVersion.ExecuteCore.<>c__DisplayClass6_0.<ExecuteInternal>b__0(IRepository repo)
   at GitVersion.GitPreparer.WithRepository[TResult](Func`2 action)
   at GitVersion.ExecuteCore.ExecuteGitVersion(String targetUrl, String dynamicRepositoryLocation, Authentication authentication, String targetBranch, Boolean noFetch, String workingDirectory, String commitId, Config overrideConfig, Boolean noCache)
   at GitVersion.SpecifiedArgumentRunner.Run(Arguments arguments, IFileSystem fileSystem)
   at GitVersion.Program.VerifyArgumentsAndRun()
INFO [06/15/17 16:26:44:71] 
INFO [06/15/17 16:26:44:71] Attempting to show the current git graph (please include in issue): 
INFO [06/15/17 16:26:44:71] Showing max of 100 commits
INFO [06/15/17 16:26:44:78] *   81423dc 6 months ago  (HEAD -> master, origin/master)
|\  
| * 47fa47c 6 months ago  (tag: v1.1.0-dev0001, origin/develop, develop)
* |   dbb6d40 6 months ago  (tag: v1.0.0)
|\ \  
| |/  
| * 5c0174f 6 months ago  (tag: v0.1.0-dev0001)
|/  
* 694d400 1 year, 9 months ago 

INFO [06/15/17 16:26:43:57] Dumping commit graph: 
INFO [06/15/17 16:26:43:88] *   81423dc 6 months ago  (HEAD -> master, origin/master)
|\  
| * 47fa47c 6 months ago  (tag: v1.1.0-dev0001, origin/develop)
* |   dbb6d40 6 months ago  (tag: v1.0.0)
|\ \  
| |/  
| * 5c0174f 6 months ago  (tag: v0.1.0-dev0001)
|/  
* 694d400 1 year, 9 months ago 

INFO [06/15/17 16:26:43:88] Working directory: D:\Jenkins_Home\workspace\GitVersionDec Master4
INFO [06/15/17 16:26:43:88] IsDynamicGitRepository: False
INFO [06/15/17 16:26:43:90] Returning Project Root from DotGitDirectory: D:\Jenkins_Home\workspace\GitVersionDec Master4\.git - D:\Jenkins_Home\workspace\GitVersionDec Master4
INFO [06/15/17 16:26:43:90] Running on Windows.
INFO [06/15/17 16:26:43:91] Applicable build agent found: 'Jenkins'.
INFO [06/15/17 16:26:43:91] Branch from build environment: master
INFO [06/15/17 16:26:43:91] Begin: Normalizing git directory for branch 'master'
  INFO [06/15/17 16:26:44:03] One remote found (origin -> 'http://git.atg.analog.com/scm/atgap/gitversiondec.git').
  INFO [06/15/17 16:26:44:04] Skipping fetching, if GitVersion does not calculate your version as expected you might need to allow fetching or use dynamic repositories
  INFO [06/15/17 16:26:44:05] Updating local branch refs/heads/master to match ref master
  INFO [06/15/17 16:26:44:09] Creating local branch from remote tracking 'refs/remotes/origin/develop'.
  INFO [06/15/17 16:26:44:14] HEAD points at branch 'refs/heads/master'.
INFO [06/15/17 16:26:44:14] End: Normalizing git directory for branch 'master' (Took: 226.00ms)
INFO [06/15/17 16:26:44:14] IsDynamicGitRepository: False
INFO [06/15/17 16:26:44:14] Returning Project Root from DotGitDirectory: D:\Jenkins_Home\workspace\GitVersionDec Master4\.git - D:\Jenkins_Home\workspace\GitVersionDec Master4
INFO [06/15/17 16:26:44:14] Project root is: D:\Jenkins_Home\workspace\GitVersionDec Master4
INFO [06/15/17 16:26:44:14] DotGit directory is: D:\Jenkins_Home\workspace\GitVersionDec Master4\.git
INFO [06/15/17 16:26:44:21] IsDynamicGitRepository: False
INFO [06/15/17 16:26:44:21] Returning Project Root from DotGitDirectory: D:\Jenkins_Home\workspace\GitVersionDec Master4\.git - D:\Jenkins_Home\workspace\GitVersionDec Master4
INFO [06/15/17 16:26:44:22] IsDynamicGitRepository: False
INFO [06/15/17 16:26:44:22] Returning Project Root from DotGitDirectory: D:\Jenkins_Home\workspace\GitVersionDec Master4\.git - D:\Jenkins_Home\workspace\GitVersionDec Master4
INFO [06/15/17 16:26:44:35] Using latest commit on specified branch
INFO [06/15/17 16:26:44:38] Running against branch: master (81423dcb8f1acf29bd7fbfb71a72e9362d60b043)
INFO [06/15/17 16:26:44:39] Begin: Calculating base versions
  INFO [06/15/17 16:26:44:42] Fallback base version: 0.1.0 with commit count source 694d400f0ad335cfd6f359399b5285de23648b83 (Incremented: None)
  INFO [06/15/17 16:26:44:62] Git tag 'v1.1.0-dev0001': 1.1.0-dev.1 with commit count source 47fa47c1e99fa834d008a529049f771ffc2bf39d (Incremented: 1.1.0-dev.2)
  INFO [06/15/17 16:26:44:64] Git tag 'v1.0.0': 1.0.0 with commit count source dbb6d40342930971cb9655e4588ea515bee7ac33 (Incremented: 1.0.1)
  INFO [06/15/17 16:26:44:66] Git tag 'v0.1.0-dev0001': 0.1.0-dev.1 with commit count source 5c0174fc4563d45f4474b3e55f55fd8e1e8cee9f (Incremented: 0.1.0-dev.2)
  INFO [06/15/17 16:26:44:68] Found multiple base versions which will produce the same SemVer (1.1.0-dev.2), taking oldest source for commit counting (Git tag 'v1.1.0-dev0001')
  INFO [06/15/17 16:26:44:69] Base version used: Git tag 'v1.1.0-dev0001': 1.1.0-dev.1 with commit count source 47fa47c1e99fa834d008a529049f771ffc2bf39d (Incremented: 1.1.0-dev.2)
INFO [06/15/17 16:26:44:69] End: Calculating base versions (Took: 296.00ms)
ERROR [06/15/17 16:26:44:70] An unexpected error occurred:
System.NotSupportedException: Mainline development mode doesn't yet support pre-release tags on master
   at GitVersion.VersionCalculation.NextVersionCalculator.FindMainlineModeVersion(BaseVersion baseVersion, GitVersionContext context)
   at GitVersion.VersionCalculation.NextVersionCalculator.FindVersion(GitVersionContext context)
   at GitVersion.GitVersionFinder.FindVersion(GitVersionContext context)
   at GitVersion.ExecuteCore.<>c__DisplayClass6_0.<ExecuteInternal>b__0(IRepository repo)
   at GitVersion.GitPreparer.WithRepository[TResult](Func`2 action)
   at GitVersion.ExecuteCore.ExecuteGitVersion(String targetUrl, String dynamicRepositoryLocation, Authentication authentication, String targetBranch, Boolean noFetch, String workingDirectory, String commitId, Config overrideConfig, Boolean noCache)
   at GitVersion.SpecifiedArgumentRunner.Run(Arguments arguments, IFileSystem fileSystem)
   at GitVersion.Program.VerifyArgumentsAndRun()
INFO [06/15/17 16:26:44:71] 
INFO [06/15/17 16:26:44:71] Attempting to show the current git graph (please include in issue): 
INFO [06/15/17 16:26:44:71] Showing max of 100 commits
INFO [06/15/17 16:26:44:78] *   81423dc 6 months ago  (HEAD -> master, origin/master)
|\  
| * 47fa47c 6 months ago  (tag: v1.1.0-dev0001, origin/develop, develop)
* |   dbb6d40 6 months ago  (tag: v1.0.0)
|\ \  
| |/  
| * 5c0174f 6 months ago  (tag: v0.1.0-dev0001)
|/  
* 694d400 1 year, 9 months ago `

**Comment by pcoombe** [comment]
@JakeGinnivan 
just an update from me, we have switched over to 4b12 with mainline.
we have also gone through and removed all our -prerelease tags
appears to be working pretty well for us, thanks
