### ISSUE TITLE
Uploading AppVeyor artifacts fails when doing Pull Request

### ISSUE THREAD

**Issue by gep13** [GitTools/GitVersion#1088]
This is due to the fact that an attempt is made to upload the releasenotes.md file, however, this file does not exist, since it will ONLY be created when a GitHub Token exists, and this will only be the case when running on the master branch, as this is the only time the Environment Variable will exist.

**Comment by asbjornu** [comment]
Wasn't this fixed by @JakeGinnivan over the last weekend?

**Comment by pascalberger** [comment]
This should be fixed by #1093

**Comment by gep13** [comment]
@pascalberger agreed.
