### ISSUE TITLE
when ran as buildserver doesn't retrieve tags if inside a subfolder

### ISSUE THREAD

**Issue by alefranz** [GitTools/GitVersion#1098]
When GitVersion.CommandLine is executed from a subfolder with the `/output buildserver` parameter, even if it detect the proper repository root, doesn't retrieve tags/master.

It would be nice to at least display a warning.

**Comment by JakeGinnivan** [comment]
This appears to be fixed in the v4 betas. I just tested locally. If this is not the case please open a new issue with the version you tried
