### ISSUE TITLE
Mono not working on windows?

### ISSUE THREAD

**Issue by JakeGinnivan** [GitTools/GitVersion#1099]
```
λ & "C:\Program Files (x86)\Mono\bin\mono" .\tools\gitversion\GitVersion.exe
INFO [11/25/16 11:30:48:23] Working directory: ...
INFO [11/25/16 11:30:48:26] IsDynamicGitRepository: False
ERROR [11/25/16 11:30:48:30] An unexpected error occurred:
System.DllNotFoundException: git2-381caf5
```

Any ideas?

**Comment by JakeGinnivan** [comment]
This is the latest released v4

**Comment by JakeGinnivan** [comment]
Also failing on linux it seems

**Comment by asbjornu** [comment]
I have no idea what's causing this, but @mclang reported this in in #1097 yesterday. Perhaps the upgrade of LibGit2Sharp in #1045 is the source of the problems?

**Comment by JakeGinnivan** [comment]
`sudo apt-get install libcurl3` sorted it :)

**Comment by JakeGinnivan** [comment]
Found the solution in https://github.com/libgit2/libgit2sharp/issues/1273

We need to document this..

**Comment by JakeGinnivan** [comment]
Documented in #1101
