### ISSUE TITLE
Unable to increment builds using +semver: major etc

### ISSUE THREAD

**Issue by NotABadPerson** [GitTools/GitVersion#1113]
I'm currently using Git Version Task 3.6.5 with TFS 2017.  
We are using +semver: major to force the versioning but are finding that this doesn't work for us as it's not incrementing when we commit and build.  I thought it was set to use these as default.  I would appreciate any help on this as I've spent 3 days trying to implement it.  In theory the product sounds great as some of the other solutions available are cumbersome.

**Comment by JakeGinnivan** [comment]
Hi @NotABadPerson 

`+semver: major` is a hint about the SemVer changes. These are aggregated between releases. So if you tag 2.0.0, then use `+semver: minor` and `+semver: minor` and `+semver: major` on different commits the result would be v3.0.0.

There are plenty of closed issues on this subject and information in our docs about it. Mainline mode in v4 beta might work better for you though

**Comment by JakeGinnivan** [comment]
Here is the relevant docs. https://gitversion.readthedocs.io/en/latest/more-info/version-increments/
