### ISSUE TITLE
Help: how do I achieve the following configuration

### ISSUE THREAD

**Issue by brazilbean** [GitTools/GitVersion#1114]
I saw in the documentation somewhere that if we can't figure out how to accomplish our design, to open an issue asking for help. Here goes!

My group develops two kinds of packages: libraries and console apps that use those libraries. We use TeamCity to build/test and NuGet to internally distribute our packages. 

We would like `develop` to auto-increment the `minor` version number with every check-in. We would like to be able to manually increment the `major` version number on develop. The develop branch should be tagged as a pre-release in NuGet. 

On occasion we need to make long-term-stable releases of a library or app. We would like to branch from the relevant commit on develop to a `prerelease/` branch, stabilize the code-base, and then branch to a `support/` branch. All versions on `support/` branches are stable releases and auto-increment the `patch` version with subsequent check-ins to the branch. The name of the support branch may include a business driven version number that should not be used to semantically version the code base.

All other branches should inherit the version from the source branch, use a prerelease tag named by the branch, and auto-increment the commit counter.

Example:
```
develop         feature/foo     stable/NSv5
0.1.0-dev.1
<commit>
0.2.0-dev.2
<branch>------->0.2.0-foo.0
    |           <commit>
    |           0.2.0-foo.1
<commit>            |
0.3.0-dev.3         |
<merge>         <merge>
0.4.0-dev.4
<branch>----------------------->0.4.0
    |                           <commit>
    |                           0.4.1
```

I have tried using flavors of all three modes: ContinuousDelivery, ContinuousDevelopment, and Mainline; but I haven't worked out the desired behavior yet.

Is this design achievable using current versions of GitVersion? If so, how?

Thank you!

**Comment by JakeGinnivan** [comment]
A config like this should work fine:

```
mode: ContinuousDevelopment
assembly-versioning-scheme: MajorMinorPatch
branches:
  develop:
    tag: dev
    increment: minor
  stable:
     regex: stable?[/-]
     increment: patch
ignore:
  sha: []
```

To make it work I think you would need to tag the first commit on the stable branch to lock the version on that branch.

**Comment by JakeGinnivan** [comment]
If you can give this a go, if it doesn't work can you submit a pull, request which has a failing test with this configuration then I can probably have a quick play around and find something which could work. 

Going to close this issue for now.
