### ISSUE TITLE
Add debug switch to launch debugger

### ISSUE THREAD

**Issue by aateeque** [GitTools/GitVersion#1117]
I wonder if it'll be of any use to the majority if we had a `/debug` that helped attach a debugger. My argument is that I download _GitVersion.exe_ from nuget and launch it via CI process; when I am debugging it'll make the workflow easier if I could attach the debugger at that point.

**Comment by JakeGinnivan** [comment]
I do not know of any other tools offering this functionality. I would prefer /debug to enable debug level logs which give enough information to diagnose the issue. If you are at the point you need a debugger attached you should just pull the code down and launch that way.

Going to close, if you have any examples of other tools doing this and want to continue the conversation just drop a comment and I will reopen
