### ISSUE TITLE
Error executing GitVersion : exception during deserialization ---> System.ArgumentException: Requested value 'MainLine' was not found.

### ISSUE THREAD

**Issue by chili512** [GitTools/GitVersion#1120]
## System.ArgumentException: Requested value 'MainLine' was not found.
We are using GitVersion in MainLine mode. 
15-12-2016 we suddenly found deployment build would fail early with the above exception. We have worked around this by moving to ContinuousDelivery mode, but that is a more manual approach and less desirable. 
So we would like to understand why we have suddenly run into this problem.
We have confirmed the Bamboo agents the build is executed on have not recently been updated.
We have also confirmed that the difference in the repository between the last successful build and the first failed build is only source code and not configuration.
[FullLog.txt](https://github.com/GitTools/GitVersion/files/656217/FullLog.txt)

**Comment by asbjornu** [comment]
Perhaps the setting is case sensitive? Does it work with `mode: Mainline` as [per the documentation](http://gitversion.readthedocs.io/en/latest/reference/mainline-development/)?

**Comment by chili512** [comment]
Good point. I will check that. However the value was set via the command line interview that you can invoke, and it was until yesterday working as is. Nevertheless I will certainly check and thanks for your advise. Much appreciated!

**Comment by chili512** [comment]
I can confirm it appears case makes no difference. Moving back to Mainline results in an exception. Thanks for the suggestion all the same. Appreciated!

**Comment by asbjornu** [comment]
@chili512: Can you please post your `gitversion.yml` configuration file?

**Comment by chili512** [comment]
I can. Here it is

[GitVersion.zip](https://github.com/GitTools/GitVersion/files/663331/GitVersion.zip)

Note that right now we are using ContinuousDeployment as temp replacement for Mainline

Version 2.6.1.windows.1 on this machine. Unable to determine on server at this moment in time

**Comment by asbjornu** [comment]
@chili512: `mode: Mainline` is only supported from version 4 and up, which is currently in beta. Try upgrading to [beta 9](https://www.nuget.org/packages/GitVersion/4.0.0-beta0009) and see how that goes.

**Comment by chili512** [comment]
I see. I will speak with IT. Thanks heaps for your assistance. Much appreciated!!

**Comment by chili512** [comment]
Oops I misled you. I misread GitVersion to be Git Version. Silly me. I think I now know what our problem is. We did install the Beta some time back for the very reason you state. It all makes sense now. Our CI server inexplicably lost a number of apps about the same time. Octopack, 7zip. It is clear that the Beta version of GitVersion we were using was included. I just did not realise. The penny dropped. Thank you so much for your assistance. As soon as I saw the Nuget install statement I realised.

**Comment by chili512** [comment]
I will close this issue.

**Comment by asbjornu** [comment]
@chili512: I'm glad you figured it out and that I could be of assistance. Can the issue be closed?

**Comment by chili512** [comment]
And I am grateful for your assistance. All the best, and yes I will close the issue.

**Comment by dropsonic** [comment]
Facing the same issue on AppVeyor. Version: GitVersion.Portable v4.0.0-beta0012
