### ISSUE TITLE
Solution with multiple projects and submodules

### ISSUE THREAD

**Issue by nmain** [GitTools/GitVersion#1121]
Consider the following scenario:

Repository A contains sub-repository B.
Repository A contains solution C and project D.
Repository B contains project E.
Solution C references project D and project E.
Both D and E have GitVersionTask installed to them.

When I run GitVersion commandline, from the location of either D or E, I get version numbers that I want:  D gets version numbers from A, and E gets version numbers from B.  But when I build C, both D and E get version metadata for A.

Looking into the code, I think I see why this is happening:  GitVersionTask uses the SolutionDirectory to make its calculations.  Maybe this is intended, but it seems like the ProjectDirectory would make more sense?

**Comment by JakeGinnivan** [comment]
GitVersion has a hard requirement that history is linked to the git history, and everything in the repository is the same version. Can you elaborate on the specific values you are seeing and what you would like to see?

**Comment by nmain** [comment]
I have created a small reproducing case that illustrates what I'm seeing.  Clone and build nmain/GitVersionExample@ea92fc64efe488fc3838e54e5676faea2b224828

Actual output:

Hello, world!
I am version 0.1.0+3.Branch.master.Sha.ea92fc64efe488fc3838e54e5676faea2b224828
My library is version 0.1.0+3.Branch.master.Sha.ea92fc64efe488fc3838e54e5676faea2b224828

Expected output:

Hello, world!
I am version 0.1.0+3.Branch.master.Sha.ea92fc64efe488fc3838e54e5676faea2b224828
My library is version 0.1.0+2.Branch.master.Sha.ecbf940e02cee7a70ea495d9703a285b23aaac0a

**Comment by JakeGinnivan** [comment]
I think this is fixed with https://github.com/GitTools/GitVersion/pull/1163

It will now use the .git folder closest to the project rather than the solution.
