### ISSUE TITLE
GitVersion is not working on CentOS 7

### ISSUE THREAD

**Issue by omallo** [GitTools/GitVersion#1125]
I would like to use GitVersion inside the [OpenShift Jenkins 2 Docker image](https://github.com/openshift/jenkins/tree/master/2) which is based on CentOS 7. Unfortunately, I'm getting the following error:
```
System.TypeInitializationException: The type initializer for 'LibGit2Sharp.Core.NativeMethods' threw an exception. ---> System.DllNotFoundException: lib/linux/x86_64/libgit2-baa87df.so
  at (wrapper managed-to-native) LibGit2Sharp.Core.NativeMethods:git_libgit2_init ()
  at LibGit2Sharp.Core.NativeMethods+LibraryLifetimeObject..ctor () [0x00006] in <1a5aafd5a5444cd6a1420741ccbb6f8a>:0 
  at LibGit2Sharp.Core.NativeMethods..cctor () [0x00058] in <1a5aafd5a5444cd6a1420741ccbb6f8a>:0 
   --- End of inner exception stack trace ---
  at LibGit2Sharp.Core.NativeMethods+LibraryLifetimeObject.Finalize () [0x00000] in <1a5aafd5a5444cd6a1420741ccbb6f8a>:0
```

I do have `libcurl` installed but I guess the problem is that CentOS uses `libcurl` 4 and not 3.

I have created a standalone Docker image to reproduce the problem which you can execute as follows:
```
docker run omallo/git-version-centos7
```

The contents of the `Dockerfile` are the following:
```
FROM centos:centos7

RUN yum install -y yum-utils && \
    rpm --import "http://keyserver.ubuntu.com/pks/lookup?op=get&search=0x3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF" && \
    yum-config-manager --add-repo http://download.mono-project.com/repo/centos/ && \
    yum -y install libcurl && \
    yum -y install mono-complete && \
    yum clean all && \
    curl -L -o /tmp/GitVersion_3.6.5.zip https://github.com/GitTools/GitVersion/releases/download/v3.6.5/GitVersion_3.6.5.zip && \
    unzip /tmp/GitVersion_3.6.5.zip -d /usr/local/GitVersion_3.6.5 && \
    rm -f /tmp/GitVersion_3.6.5.zip

ENTRYPOINT ["mono", "/usr/local/GitVersion_3.6.5/GitVersion.exe"]
```

Can you say whether the problem indeed is that CentOS uses version 4 of `libcurl` and, if so, is there any possibility to get GitVersion running with that version?

**Comment by JakeGinnivan** [comment]
It is indeed CentOS and is a downstream issue..

See https://github.com/libgit2/libgit2sharp/issues/1391

**Comment by omallo** [comment]
Thanks a lot for the quick reply and for the reference to the downstream issue.

For now, I've created an OpenShift Jenkins image based on Ubuntu on which GitVersion is working fine but I will give it another try with the original CentOS image once the downstream issue is fixed.

**Comment by JakeGinnivan** [comment]
Unsure if anyone is working on the downstream issue is the only problem. If you are interested you could try and progress the issue (maybe get a CI build going for the native binaries or something?)

**Comment by ristaloff** [comment]
I just had a simililar issue using a docker image based on mono:latest which in turn is based on debian:wheezy.
I got the same System.TypeInitializationException as above, because I was missing GLIBC_2.14 and GLIBC_2.15. The the version of debian in the debian:wheezy image is Debian 7.11. Debian 7.11 only has GLIBC_2.13.  I followed the instructions here to update glibc and fix the problem: http://stackoverflow.com/questions/10863613/how-to-upgrade-glibc-from-version-2-13-to-2-15-on-debian

**Comment by asbjornu** [comment]
@omallo: Can you please attempt to do what @ristaloff's describes and see if it fixes your problem?

**Comment by mr-exz** [comment]
Solution for CentOS you can see here in https://github.com/GitTools/GitVersion/pull/1571

**Comment by asbjornu** [comment]
Closing as this due to inactivity and because it should be proven to work in #1571.
