### ISSUE TITLE
Does it work on TFS 2017

### ISSUE THREAD

**Issue by RonaldDelta** [GitTools/GitVersion#1127]
Trouble using it on a TFS 2017 server.

I am using the GitVErsion Build Task addin.
I am trying to bump the version using the show methode for manually increase
https://gitversion.readthedocs.io/en/latest/more-info/version-increments/
But the versions are never increased. (using a develop branch from a GitFlow setup)

I have a GitVersion.yml with:

next-version: 10.0 
assembly-versioning-scheme: MajorMinorPatch
mode: ContinuousDelivery
continuous-delivery-fallback-tag: ci
major-version-bump-message: '\+semver:\s?(breaking|major)'
minor-version-bump-message: '\+semver:\s?(feature|minor)'
patch-version-bump-message: '\+semver:\s?(fix|patch)'
legacy-semver-padding: 4
build-metadata-padding: 4
commits-since-version-source-padding: 4
commit-message-incrementing: Enabled
branches:
  master:
    mode: ContinuousDelivery
    tag: ''
    increment: Patch
    prevent-increment-of-merged-branch-version: true
    track-merge-target: false
  releases?[/-]:
    mode: ContinuousDelivery
    tag: beta
    increment: Patch
    prevent-increment-of-merged-branch-version: true
    track-merge-target: false
  features?[/-]:
    mode: ContinuousDelivery
    tag: useBranchName
    increment: Inherit
    prevent-increment-of-merged-branch-version: false
    track-merge-target: false
  (pull|pull\-requests|pr)[/-]:
    mode: ContinuousDelivery
    tag: PullRequest
    increment: Inherit
    prevent-increment-of-merged-branch-version: false
    tag-number-pattern: '[/-](?<number>\d+)[-/]'
    track-merge-target: false
  hotfix(es)?[/-]:
    mode: ContinuousDelivery
    tag: beta
    increment: Patch
    prevent-increment-of-merged-branch-version: false
    track-merge-target: false
  support[/-]:
    mode: ContinuousDelivery
    tag: ''
    increment: Patch
    prevent-increment-of-merged-branch-version: true
    track-merge-target: false
  dev(elop)?(ment)?$:
    mode: ContinuousDeployment
    tag: develop
    increment: Minor
    prevent-increment-of-merged-branch-version: false
    track-merge-target: true
ignore:
  sha: []

**Comment by JakeGinnivan** [comment]
Unsure what the problem is here, please open up a new issue with the build logs and an example of the git repo. There is just not enough information here to work with. Thanks!
