### ISSUE TITLE
Default value for null BuildMetadataPadded variable

### ISSUE THREAD

**Issue by jdshkolnik** [GitTools/GitVersion#1128]
When the build has no metadata(0.1.0 vs 0.1.0+43), the BuildMetadataPadded variable isn't present which makes it difficult to use. Can it default to "0000"?

**Comment by JakeGinnivan** [comment]
Can you give me more information about what scenario is difficult. This is not something I have encountered and it we added it, it could be confusing. I would imagine defaulting should happen in your build script.

**Comment by jdshkolnik** [comment]
@JakeGinnivan If you want to assemble a version with the build number, like (major + "." + minor + "." + patch + "." + paddedbuild) then that last variable can't be empty.
