### ISSUE TITLE
Support depth=x on VSTS

### ISSUE THREAD

**Issue by tomap** [GitTools/GitVersion#1131]
Hi,

VSTS recently introduced a new option to clone code with depth=x
https://www.visualstudio.com/en-us/docs/build/define/repository#git
It is particularly interesting for large codebase with a large history.
It only extracts the last revision.

When doing that, GitVersion stops working with exceptions like:
```
ERROR [01/06/17 13:17:46:62] An unexpected error occurred:
 LibGit2Sharp.NotFoundException: Object not found - no match for id (dbd3d817d1e2ef396863ebf6322a82a18a6b5c76)
    at LibGit2Sharp.Core.Ensure.HandleError(Int32 result)
    at LibGit2Sharp.Core.Proxy.git_revwalk_next(RevWalkerHandle walker)
    at LibGit2Sharp.CommitLog.CommitEnumerator.MoveNext()
    at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
    at GitVersion.VersionCalculation.FallbackBaseVersionStrategy.<GetVersions>d__0.MoveNext()
    at System.Linq.Enumerable.<SelectManyIterator>d__16`2.MoveNext()
    at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
    at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
    at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
    at GitVersion.VersionCalculation.BaseVersionCalculator.GetBaseVersion(GitVersionContext context)
    at GitVersion.VersionCalculation.NextVersionCalculator.FindVersion(GitVersionContext context)
    at GitVersion.GitVersionFinder.FindVersion(GitVersionContext context)
    at GitVersion.ExecuteCore.<>c__DisplayClass6_0.<ExecuteInternal>b__0(IRepository repo)
    at GitVersion.GitPreparer.WithRepository[TResult](Func`2 action)
    at GitVersion.ExecuteCore.ExecuteGitVersion(String targetUrl, String dynamicRepositoryLocation, Authentication authentication, String targetBranch, Boolean noFetch, String workingDirectory, String commitId, Config overrideConfig)
    at GitVersion.SpecifiedArgumentRunner.Run(Arguments arguments, IFileSystem fileSystem)
    at GitVersion.Program.VerifyArgumentsAndRun()

```
Those exceptions are expected because part of the history is not available.
Could it be possible to adapt GitVersion to ignore those error and work with the little information they have to produce a version number?

Regards,

Thomas P.

**Comment by gep13** [comment]
@tomap In order to correctly assert the current semantic version of your repository, GitVersion requires the history of the repository.  If you limit the clone depth of the repository, it is not going to be able to correctly assert the correct version number.

**Comment by MarioZG** [comment]
I'm using MSBuild task. Just encountered same problem.

It would be really useful if it could handle some scenarios with limited history, as long as at least one commit is tagged. In my scenario I'm checking out tagged commit, so version number is available.

**Comment by tomap** [comment]
Yes, this is exactly what I was thinking, in some case, I know that with depth=2, I am sure that I will have enough tags to determine the version number.

**Comment by asbjornu** [comment]
An important feature of GitVersion, I think, is that every commit will produce the same version number, no matter how or where GitVersion is executed (on a local development machine, on the build server, etc.). 

The problem with limited history is that a commit after a tag can have multiple parents from long before the tagged commit, which may or may not affect the version number. This means that being able to generate a stable version number for a given commit becomes impossible, because the version number may be different for different clone depths.

Some may be willing to exchange this safety and stability over some clone depth flexibility, but that should be a configurable opt-in at best. If you have ideas for how such a configuration option should look like, behave and possibly be implemented, please throw your suggestions up here and we'll see what sticks. 😃

**Comment by tomap** [comment]
Hi,

I will try to code something if I have time.
As you said, there need to be a switch to enable this behavior

Maybe another way to see that would be to make some assumption about the codebase and suppose that version always increase.
So if you find a v5.0.0 in the code, no need to look below that tag in this branch because you can assume that you will only find v4.9, v4.8, ... but no v5.1

So you would go over the history of a branch and stop as soon as you find a tag.
And maybe throw a warning/exception if you did not find a tag on a parent branch that you are suppose to take into account
(not sure I use the right words: history/branches. I hope you see what I mean)

Thomas

**Comment by MarioZG** [comment]
> The problem with limited history is that a commit _**after a tag**_ can have multiple parents from long before the tagged commit, which may or may not affect the version number.

If given commit is tagged, can any parent affect version number? I didn't have time to analise in details how you guys generate number and what can affect it in more complex scenarios, but I'd imagine tag is a way to explicitly say "it's 4.3", isn't it?.  Should this need any switch  or setting?

As for cases where commit has parents which might came from different branches, i agree that this should be explicit setting changed by user to allow "best guess" based on available history.

**Comment by asbjornu** [comment]
@MarioZG: I haven't analysed this thoroughly either, but I think the commit counting might be wrong if you cut off a parent branch at an arbitrary depth.

**Comment by JakeGinnivan** [comment]
GitVersion is already really complex as is, and while it would be great to support arbitrary clone depths the reality is as soon as the merge base of the current feature branch drops out, or you don't fetch other tracking branches you will start seeing different version numbers. It's just not a scenario we can support at the moment. The thing is depth would need to be calculated to know what is relevant. In mainline mode you probably would be safe if you fetched all branches to a depth of 100 or so, as long as you were tagging your mainline.

I think the long term way to allow this is to use something like https://github.com/Microsoft/GVFS with dynamic repositories. Or if we could query all the branch and metadata remotely without downloading all of the blobs. 

Not sure any of these options are viable at the moment so unsure it's worth keeping this issue open. Going to close, if you think we should keep the issue open just post and I will reopen.
