### ISSUE TITLE
Is it possible to specify location of msbuild.exe?

### ISSUE THREAD

**Issue by alkampfergit** [GitTools/GitVersion#1141]
We are using gitversion in teamcity with meta-runner, our problem is that msbuild runs from location c:\Windows\Microsoft.NET\Framework\v4.0.30319\

Looking at source code, in file *src/GitVersionExe/SpecifiedArgumentRunner.cs* it seems that the location of msbuild is hardcoded in source. Could you please read this value from some Environment variable to allow choosing the right version of Msbuild?

![image](https://cloud.githubusercontent.com/assets/358545/22106212/eecb6b76-de47-11e6-9425-76c282c76677.png)

**Comment by asbjornu** [comment]
@alkampfergit: Sure, this sounds like something that should be fairly easy to implement. Are you up for creating a pull request for it? It would be good if the PR included documentation on this feature for the [Command Line interface](http://gitversion.readthedocs.io/en/latest/usage/command-line/).

**Comment by alkampfergit** [comment]
Ok, I'm quite busy but I think that I can create a PR,
