### ISSUE TITLE
CommitsSinceVersionSource number moving backwards

### ISSUE THREAD

**Issue by jamesharling** [GitTools/GitVersion#1146]
I'm using GitVersion v3.6.4 (updated through Chocolatey) in TeamCity 10.0.3. As you'll see from the attached image, my CommitsSinceVersionSource property in GitVersion is yoyoing around (see arrows), which means sometimes it moves backwards; this causes issues as we are using Continuous Deployment mode to support Octopus for deployment of releases. What would be causing this property to change in a non-linear way? All of the branches merged back to `develop` are `feature/*` branches - some are a simple commit or two, others live for longer and have merges of `develop` in to them to avoid merge conflicts at the time of actioning our pull requests.

![commits](https://cloud.githubusercontent.com/assets/17457947/22204411/c31822b0-e169-11e6-981a-41814c44b191.png)

**Comment by asbjornu** [comment]
Without a look at the graph, it's hard to give a good answer. Can you please paste the result of the following into a Gist and link it here?

```bash
git log --graph --format=""%h %cr %d"" --decorate --date=relative --all --remotes=* -n 100
```

**Comment by jamesharling** [comment]
Here you go:

https://gist.github.com/jamesharling/368d7ab044d85691a310ce26f3a51c7b

**Comment by JakeGinnivan** [comment]
Can you try the beta of v4. I rewrote the commit counting logic so it should be far more robust in v4.

**Comment by jamesharling** [comment]
@JakeGinnivan I've upgraded to 4.0.0-beta0008. I've seen a few changes (e.g. it's now `alpha` not `unstable`), and our commit counter has moved down to about ~160. We'll need a week or two to see how stable things are now. Thanks for the help!

**Comment by jamesharling** [comment]
This version is definitely more reliable for us - not sure exactly what aspect of our repository structure was causing v3 to have its issues.

**Comment by asbjornu** [comment]
@jamesharling: Excellent! Can this issue be closed, then?

**Comment by jamesharling** [comment]
I think so. Looking forward to the official v4 release!
