### ISSUE TITLE
CommitsSinceVersionSource is zero in release branch

### ISSUE THREAD

**Issue by dermeister0** [GitTools/GitVersion#1148]
GitVersion 3.6.1+32, 4.0.0-beta0009

I have a working copy with a release branch. GitVersion returns CommitsSinceVersionSource correctly there. However, it does not work in Jenkins ('checkout to specific local branch' option is enabled, plugin is updated).

I started to investigate and reproduced the case on my local machine. Unfortunately I can't create a small test repository to reproduce.

Everything works in main working copy:

```
C:\Work\MyProject>git branch
  develop
  master
* release/205.2

C:\Work\MyProject>gitversion
{
  "Major":205,
  "Minor":2,
  "Patch":0,
  "PreReleaseTag":"beta.5",
  "PreReleaseTagWithDash":"-beta.5",
  "PreReleaseLabel":"beta",
  "PreReleaseNumber":5,
  "BuildMetaData":"",
  "BuildMetaDataPadded":"",
  "FullBuildMetaData":"Branch.release/205.2.Sha.fd4a7618a5c76dc6414867654b4f2071eb5ba84c",
  "MajorMinorPatch":"205.2.0",
  "SemVer":"205.2.0-beta.5",
  "LegacySemVer":"205.2.0-beta5",
  "LegacySemVerPadded":"205.2.0-beta0005",
  "AssemblySemVer":"205.2.0.0",
  "FullSemVer":"205.2.0-beta.5",
  "InformationalVersion":"205.2.0-beta.5+Branch.release/205.2.Sha.fd4a7618a5c76dc6414867654b4f2071eb5ba84c",
  "BranchName":"release/205.2",
  "Sha":"fd4a7618a5c76dc6414867654b4f2071eb5ba84c",
  "NuGetVersionV2":"205.2.0-beta0005",
  "NuGetVersion":"205.2.0-beta0005",
  "CommitsSinceVersionSource":5,
  "CommitsSinceVersionSourcePadded":"0005",
  "CommitDate":"2017-01-31"
}
```

Cloning it, GitVersion can't determine the correct CommitsSinceVersionSource value:

```
C:\Temp>git clone C:\Work\MyProject AnotherTest
Cloning into 'AnotherTest'...
done.
Checking out files: 100% (12068/12068), done.

C:\Temp\AnotherTest>git branch
* release/205.2

C:\Temp\AnotherTest>gitversion
{
  "Major":205,
  "Minor":2,
  "Patch":0,
  "PreReleaseTag":"beta.0",
  "PreReleaseTagWithDash":"-beta.0",
  "PreReleaseLabel":"beta",
  "PreReleaseNumber":0,
  "BuildMetaData":"",
  "BuildMetaDataPadded":"",
  "FullBuildMetaData":"Branch.release/205.2.Sha.fd4a7618a5c76dc6414867654b4f2071eb5ba84c",
  "MajorMinorPatch":"205.2.0",
  "SemVer":"205.2.0-beta.0",
  "LegacySemVer":"205.2.0-beta0",
  "LegacySemVerPadded":"205.2.0-beta0000",
  "AssemblySemVer":"205.2.0.0",
  "FullSemVer":"205.2.0-beta.0",
  "InformationalVersion":"205.2.0-beta.0+Branch.release/205.2.Sha.fd4a7618a5c76dc6414867654b4f2071eb5ba84c",
  "BranchName":"release/205.2",
  "Sha":"fd4a7618a5c76dc6414867654b4f2071eb5ba84c",
  "NuGetVersionV2":"205.2.0-beta0000",
  "NuGetVersion":"205.2.0-beta0000",
  "CommitsSinceVersionSource":0,
  "CommitsSinceVersionSourcePadded":"0000",
  "CommitDate":"2017-01-31"
}
```

I tried to check out other branches, but it did not help.

```
C:\Temp\AnotherTest>git checkout master
Branch master set up to track remote branch master from origin.
Switched to a new branch 'master'

C:\Temp\AnotherTest>git checkout develop
Switched to branch 'develop'
Your branch is up-to-date with 'origin/develop'.

C:\Temp\AnotherTest>git checkout release/205.2
Switched to branch 'release/205.2'
Your branch is up-to-date with 'origin/release/205.2'.

C:\Temp\AnotherTest>git branch
  develop
  master
* release/205.2

C:\Temp\AnotherTest>gitversion
{
  "Major":205,
  "Minor":2,
  "Patch":0,
  "PreReleaseTag":"beta.0",
  "PreReleaseTagWithDash":"-beta.0",
  "PreReleaseLabel":"beta",
  "PreReleaseNumber":0,
  "BuildMetaData":"",
  "BuildMetaDataPadded":"",
  "FullBuildMetaData":"Branch.release/205.2.Sha.fd4a7618a5c76dc6414867654b4f2071eb5ba84c",
  "MajorMinorPatch":"205.2.0",
  "SemVer":"205.2.0-beta.0",
  "LegacySemVer":"205.2.0-beta0",
  "LegacySemVerPadded":"205.2.0-beta0000",
  "AssemblySemVer":"205.2.0.0",
  "FullSemVer":"205.2.0-beta.0",
  "InformationalVersion":"205.2.0-beta.0+Branch.release/205.2.Sha.fd4a7618a5c76dc6414867654b4f2071eb5ba84c",
  "BranchName":"release/205.2",
  "Sha":"fd4a7618a5c76dc6414867654b4f2071eb5ba84c",
  "NuGetVersionV2":"205.2.0-beta0000",
  "NuGetVersion":"205.2.0-beta0000",
  "CommitsSinceVersionSource":0,
  "CommitsSinceVersionSourcePadded":"0000",
  "CommitDate":"2017-01-31"
}
```

GitVersion.yml
```
mode: ContinuousDeployment
branches: {}
ignore:
  sha: []
```

**Comment by dermeister0** [comment]
I ran the app with */diag* flag and found that base version is calculated differently.


MyProject
```
INFO [01/31/17 11:16:56:08] End: Finding branch source of 'release/205.2' (Took: 564.35ms)
  INFO [01/31/17 11:16:56:08] Version in branch name: 205.2.0 with commit count source 36ec6c60af1fdf782439252169c594eca35a9e3a (Incremented: None)
  INFO [01/31/17 11:17:03:97] Found multiple base versions which will produce the same SemVer (205.2.0), taking oldest source for commit counting (Version in branch name)
  INFO [01/31/17 11:17:03:97] Base version used: Version in branch name: 205.2.0 with commit count source 36ec6c60af1fdf782439252169c594eca35a9e3a (Incremented: None)
INFO [01/31/17 11:17:03:97] End: Calculating base versions (Took: 13,113.24ms)
```

AnotherTest
```
  INFO [01/31/17 11:05:24:83] End: Finding branch source of 'release/205.2' (Took: 86.01ms)
  INFO [01/31/17 11:05:24:83] Version in branch name: 205.2.0 with commit count source fd4a7618a5c76dc6414867654b4f2071eb5ba84c (Incremented: None)
  INFO [01/31/17 11:05:24:83] Found multiple base versions which will produce the same SemVer (205.2.0), taking oldest source for commit counting (Version in branch name)
  INFO [01/31/17 11:05:24:83] Base version used: Version in branch name: 205.2.0 with commit count source fd4a7618a5c76dc6414867654b4f2071eb5ba84c (Incremented: None)
INFO [01/31/17 11:05:24:83] End: Calculating base versions (Took: 4,696.22ms)
INFO [01/31/17 11:05:24:84] Skipping version increment
INFO [01/31/17 11:05:24:84] 0 commits found between fd4a7618a5c76dc6414867654b4f2071eb5ba84c and fd4a7618a5c76dc6414867654b4f2071eb5ba84c
```

**Comment by bravecobra** [comment]
I'm experiencing the same thing. I'm using git flow as a branching strategy. As for my gitversion.yml: 

> assembly-informational-format: '{FullSemVer}+Sha.{Sha}'
branches:
  master:
    tag: ""
  develop:
    tag: "unstable"
  features?[/-]:
    tag: "feature-{BranchName}"
  hotfix[/-]:
    tag: "hotfix"
  support[/-]:
    tag: "support"
  release[/-]:
    tag: "beta"
ignore:
  sha: []

**Comment by JakeGinnivan** [comment]
You will have to do a `git fetch --unshallow` to fetch all the other tags and ensure you have all the git history. 

I think running that before you run GitVersion should fix your issues, if it doesn't just post an update and I will reopen the issue. If you do can you run gitversion with the following command line args `gitversion /log console /output buildserver` - this should give you a full log which will help diagnose.

**Comment by gbanister** [comment]
I'm seeing this same behavior where CommitsSinceVersionSource  is always 0 regardless of the number of commits on the release branch.  develop and feature branches do not exhibit this behavior.  The Jenkins project is using the default Jenkins Git Plugin options to clone the entire repo, so it's not doing a shallow clone.

PS C:\opt\Jenkins\jobs\GeoServices-Releases\workspace> gitversion /l console /output buildserver
INFO [04/27/17 14:24:52:42] Working directory: C:\opt\Jenkins\jobs\GeoServices-Releases\workspace
INFO [04/27/17 14:24:52:44] IsDynamicGitRepository: False
INFO [04/27/17 14:24:52:46] Returning Project Root from DotGitDirectory: C:\opt\Jenkins\jobs\GeoServices-Releases\works
ace\.git - C:\opt\Jenkins\jobs\GeoServices-Releases\workspace
INFO [04/27/17 14:24:52:47] Running on Windows.
INFO [04/27/17 14:24:52:48] IsDynamicGitRepository: False
INFO [04/27/17 14:24:52:48] Returning Project Root from DotGitDirectory: C:\opt\Jenkins\jobs\GeoServices-Releases\works
ace\.git - C:\opt\Jenkins\jobs\GeoServices-Releases\workspace
INFO [04/27/17 14:24:52:48] Project root is: C:\opt\Jenkins\jobs\GeoServices-Releases\workspace
INFO [04/27/17 14:24:52:48] DotGit directory is: C:\opt\Jenkins\jobs\GeoServices-Releases\workspace\.git
INFO [04/27/17 14:24:52:49] IsDynamicGitRepository: False
INFO [04/27/17 14:24:52:49] Returning Project Root from DotGitDirectory: C:\opt\Jenkins\jobs\GeoServices-Releases\works
ace\.git - C:\opt\Jenkins\jobs\GeoServices-Releases\workspace
INFO [04/27/17 14:24:52:57] Begin: Loading version variables from disk cache
  INFO [04/27/17 14:24:52:58] Begin: Deserializing version variables from cache file C:\opt\Jenkins\jobs\GeoServices-Re
eases\workspace\.git\gitversion_cache\4547ED6FC0341BB4F9AF738CABD2A330F369315C.yml
  INFO [04/27/17 14:24:52:74] End: Deserializing version variables from cache file C:\opt\Jenkins\jobs\GeoServices-Rele
ses\workspace\.git\gitversion_cache\4547ED6FC0341BB4F9AF738CABD2A330F369315C.yml (Took: 161.01ms)
INFO [04/27/17 14:24:52:74] End: Loading version variables from disk cache (Took: 162.01ms)
PS C:\opt\Jenkins\jobs\GeoServices-Releases\workspace>
