### ISSUE TITLE
Publish beta versions to VSTS marketplace

### ISSUE THREAD

**Issue by pascalberger** [GitTools/GitVersion#1150]
VSTS marketplace seems to now support pre-release versions and the ability to select the version of an extension which should be used (See discussion [here](https://gitter.im/GitTools/GitVersion?at=5892f1664c04e9a44e5ed0c9)). Therefore we can publish the VSTS extension also for beta versions.

Required changes:
* [ ] In case of beta release the VSTS extension needs to be build with the [preview flag](https://www.visualstudio.com/en-us/docs/integrate/extensions/develop/manifest#preview-flag) in the manifest
* [ ] For beta releases the VSTS extension needs to be deployed to the VSTS marketplace

**Comment by SamirHafez** [comment]
Is this gonna go soon? Anything I can help with?

**Comment by pascalberger** [comment]
@SamirHafez Are you interested in writing a PR implementing this?

There currently also is an effort undergoing to rewrite the VSTS task to use the Node handler instead of the PowerShell one, also affecting the build pipeline (See #1139). But this still takes some time until it is ready to be merged.

**Comment by sandorfr** [comment]
Interesting, @pascalberger I'll think about it as we definitely want this feature for our other extensions.

**Comment by SamirHafez** [comment]
@pascalberger seems simple but I'd need input on what exactly to do on what files. Someone who implemented this build mechanism can probably turn this into a 5min PR lol

**Comment by Franklin89** [comment]
@pascalberger any news on this? the vsts task in the market place is already pretty old and is missing things like Mainline mode which i would like to use.

**Comment by pascalberger** [comment]
@Franklin89 The version in the marketplace is still the latest stable release since no stable 4.0 release is out.

The switch to use the Node handler instead of the PowerShell one is now merged with https://github.com/GitTools/GitVersion/pull/1189, but there was no development done yet for supporting beta releases to be pushed to the marketplace.

**Comment by andrassy** [comment]
+1

Anything me our my team can help with? Which libgit2sharp ticket still needs work?

As a short term workaround could anyone provide some step-by-step installation instructions. I'm struggling to figure out how to get the vsix installed into TFS - just getting an error about an invalid version in the manifest when attempting to install the betas (beta 11).

**Comment by Tankatronic** [comment]
This would be great. I'd love to to have the fix for #1074 available.

**Comment by asbjornu** [comment]
@andrassy, @Tankatronic: The problem mentioned by @SamirHafez in https://github.com/GitTools/GitVersion/issues/1150#issuecomment-277409952 still needs to be performed before pre-releases can be published to VSTS. If any of you are up for submitting a PR removing `.WithCriteria(() => !tag.Contains("-"))`, I'll be happy to merge it!

**Comment by Tankatronic** [comment]
@asbjornu I opened PR #1312

**Comment by JakeGinnivan** [comment]
Gonna give the PR a go, lets see what happens during the next release!

**Comment by marceloavf** [comment]
Any update on this ?

**Comment by Daniel-Svensson** [comment]
Would really like to se version 4 as an option for the build task, is there a planned update?

**Comment by dennisroche** [comment]
I just hit this as wanted to use `mainline`. Temporary workaround was to bundle a copy of `GitVersion.Commandline` in a `tools` folder (remember to set `.gitattributes` for the binary files).

**Comment by dennisroche** [comment]
To summarise what is needed to get pre-release versions published to VSTS.

- [x] Remove the `WithCriteria()` from Cake Build
- [x] Switch to use the Node handler instead of the PowerShell
- [ ]  Supporting beta releases to be pushed to the marketplace

**Comment by asbjornu** [comment]
Now that a lot of people want to get their hands on #1713, I assume it would be good to get a beta version out to Azure DevOps. It doesn't seem like much work, have you looked into what's required, @arturcic?

**Comment by arturcic** [comment]
> Now that a lot of people want to get their hands on #1713, I assume it would be good to get a beta version out to Azure DevOps. It doesn't seem like much work, have you looked into what's required, @arturcic?

I think the same issue - we need a valid PAT token for publishing. I'll get back to this soon

**Comment by asbjornu** [comment]
I see. I thought we had made progress on that front. Anything I can assist with?

**Comment by arturcic** [comment]
I'll let you know when I need some assistance in that area. For now I guess we can manually publish the artifacts from the build to the marketplace to have the people test it

**Comment by arturcic** [comment]
Will be fixed by #1492
