### ISSUE TITLE
AssemblyInfo.cs file has last modified updated even when nothing changed

### ISSUE THREAD

**Issue by kjjuno** [GitTools/GitVersion#1151]
My team is trying to put together a build system that will only build things incrementally. Using GitVersion to set the version in my AssemblyInfo.cs file works really well, except that it touches the file even when nothing actually changed. This breaks the incremental build because it assumes the file has changed which causes a ripple effect throughout the projects, meaning we have to build everything even when no code has changed.

Is there a way to have GitVersion not touch the file if the version has not changed?

**Comment by chris1248** [comment]
I agree, this is an issue.

**Comment by gep13** [comment]
If, like me, you use the Assembly Informational attribute, which includes the commit number, and the sha1 hash of the commit that triggered the build, then updating the assemblyinfo.cs file is a requirement.  Granted, the higher level semantic version number might not have changed, i.e. it is still say `1.2.0`, however, the lower level information has changed, and therefore has to be included in the file.

**Comment by chris1248** [comment]
We do not include the commit number, nor include the sha1 commit hash that triggered the build. So we do not have that requirement.

**Comment by chris1248** [comment]
In discussing this with @kjjuno our requirements have changed. We will no longer invoke this task as part of every build. Thanks @kjjuno

**Comment by kjjuno** [comment]
I still think this is an issue. Yes, we found a work around that meets our needs. However, if there are no new commits and I run GitVersion twice, the second run will always produce the same version, including the hash etc...

If that is the same, there is no need to update the last modified on the AssemblyInfo.cs file. An incremental build system shouldn't get ruined just because you wanted to ensure that things were versioned properly.

**Comment by gep13** [comment]
>@kjjuno said...
However, if there are no new commits and I run GitVersion twice, the second run will always produce the same version, including the hash etc...

This I don't disagree with.  In your situation, I would advice NOT using the /updateassemblyinfo flag, and rather run GitVersion (collecting the asserted versions) and then verify for yourself whether the assemblyinfo file should be updated.  

I am not sure if this check is something that should be added into GitVersion core or not. @JakeGinnivan @asbjornu @pascalberger

**Comment by gep13** [comment]
>@chris1248 said...
We do not include the commit number, nor include the sha1 commit hash that triggered the build.

At the end of the day, GitVersion is a library for asserting the Semantic Version number of the current Git Repository.  This includes the sha1 and the commit count.  As a result, I would say that there is an expectation, unless you are running a build on the exact same commit (as @kjjuno pointed out above) that the assemblyinfo files would be updated on each unique build.  The fact that you are not including that information in your assemblyinfo file is your choice of course.

**Comment by asbjornu** [comment]
I'm not sure what do do in this scenario. I think we would need to add another command line switch, because I assume some people expect GitVersion to actually update the assembly when executed with the `/updateAssemblyInfo` switch.

**Comment by gep13** [comment]
>@asbjornu said...
because I assume some people expect GitVersion to actually update the assembly when executed with the /updateAssemblyInfo switch.

That is a valid point.

**Comment by kjjuno** [comment]
I agree

**Comment by kjjuno** [comment]
Would something like this work? `GitVersion.exe /UpdateAssemblyInfo /OnlyWhenDifferent`

If there is ever a feature to update the version in a nuspec file (another feature I would love) this could pair with that option as well. Maybe something like `GitVersion.exe /UpdateNuspec /OnlyWhenDifferent`

**Comment by JakeGinnivan** [comment]
This is actually super easy to fix, have submitted a PR at https://github.com/GitTools/GitVersion/pull/1167
