### ISSUE TITLE
Feature Request: Ability to update the version in a nuspec file

### ISSUE THREAD

**Issue by kjjuno** [GitTools/GitVersion#1152]
`GitVersion.exe /UpdateAssemblyInfo` does wonders for embedding version information in the assemblies themselves. However, if you use the full build metadata in the AssemblyInformationalVersion you cannot use the `$version$` replacement token to set the version.

Often this isn't a big deal because you can capture the GitVersion output of the NuGetVersion variable and pass it in as the variable during a pack command.

However, if you want to do automatic dependency resolution for referenced projects you run into an issue. My team's solution so far has been to use the NuGetVersion variable as the AssemblyInformationalVersion. This has the huge drawback of losing all the information about the SHA1 and the branch etc...

If we could have GitVersion update the nuspec file with the version, similar to what it's doing with AssemblyInfo.cs this problem gets resolved. We could use the full build metadata, and also correctly determine nuget dependencies for referenced projects.

My initial suggestion for the flag would be `GitVersion.exe /UpdateNuspec` for updating all .nuspec files in the repository, and `GitVersion.exe /UpdateNuspec <path>` to update a specific nuspec file.

**Comment by JakeGinnivan** [comment]
I am going to push back on this, I want to move GitVersion to be less aligned with the .net namespace and a more generic tool across multiple ecosystems.

Other things we could update: wix, clickonce, project.json, package.json, gems etc. The list is endless. In fact I would like to see it only available in the MSBuild task. Then in the cake wrappers, or build server integrations we can make it easy to use their versons of the update * functions. Either that or create some small external utilities to do the updates. That way we can focus on better ways of capturing the variables that gitversion generates and making them available to other tools

I suggest at build time you embed all the information you need into the NuSpec so it's available downstream.

**Comment by kjjuno** [comment]
I'm planning to write this as a separate app designed to be run by the gitversion exec workflow. The project url is
https://github.com/kjjuno/GitVersion.FileWriters.Nuspec

I would love contrubutions and or feedback as to the interest in this project. @JakeGinnivan  had a good point that a lot of files could potentially be update targets. This method should make it possible to target all of these files without making GitVersion be the one in charge.

**Comment by gep13** [comment]
@kjjuno when it comes to this sort of thing, I normally turn to this:

https://github.com/sergeyzwezdin/magic-chunks

Which already handles most file types, and has integrations into most build systems.
