### ISSUE TITLE
When support the deployment version of Clickonce?

### ISSUE THREAD

**Issue by maikebing** [GitTools/GitVersion#1153]
Is already supported but i will not use it? Still do not support?

**Comment by gep13** [comment]
@maikebing what sort of support are you looking for?

**Comment by maikebing** [comment]
The release of the ClickOnce version number

**Comment by fwinkelbauer** [comment]
@gep13 ClickOnce doesn't care about the information provided in `AssemblyInfo.cs`. All configuration for ClickOnce is provided in the `.csproj` file. An example would be:

```xml
    <ApplicationRevision>116</ApplicationRevision>
    <ApplicationVersion>1.0.0.%2a</ApplicationVersion>
```

or

```xml
    <ApplicationVersion>1.0.0.116</ApplicationVersion>
```

`%2a` is a replacement character (`*`) and inserts the `<ApplicationRevision>` data. In other words: both snippets result in the same version 1.0.0.116. ClickOnce uses a bunch of other XML configuration tags, but these two define the current version. (Examples of other tags include: upload location, auto update enabled/disabled, enforcing a minimum version and many more)

So if I would like to use GitVersion with ClickOnce I'd have to write a script which either throws the output of GitVersion into a `.csproj` file, or I'd write a script which reads the `AssemblyInfo.cs` after running GitVersion to inject the version data into `.csproj`.

I might look into this on the weekend

**Comment by fwinkelbauer** [comment]
@gep13 I've looked more into this. As far as I can tell my assumption was right: ClickOnce only supports numerical version strings in the form A.B.C.D. This means that the properties `AssemblySemVer` and `MajorMinorPatch` (as found in the JSON output of GitVersion) would be a perfect fit.

**Solution Draft 1**

Here is a small snippet which injects the version information into a `.csproj` file:

```csharp
public static void WriteClickOnceVersion(string csproj, string version)
{
    var doc = new XmlDocument();
    doc.Load(csproj);

    var versionNodes = doc.GetElementsByTagName("ApplicationVersion");

    foreach (XmlNode node in versionNodes)
    {
        node.InnerText = version;
    }

    var revisionNodes = doc.GetElementsByTagName("ApplicationRevision");

    for (int i = revisionNodes.Count - 1; i >= 0; i--)
    {
        revisionNodes[i].ParentNode.RemoveChild(revisionNodes[i]);
    }

    doc.Save(csproj);
}
```

This code will:

- Search for all tags named `ApplicationVersion` and inject a `A.B.C.D` style version
- Search and remove all tags named `ApplicationRevision` as they would not be used (no `2%a` in `ApplicationVersion`)

**Solution Draft 2**

Another approach could look like this:

- Search for all tags named `ApplicationVersion` and inject a `A.B.C.2%a` style version
- Add a tag (if it doesn't exist) `ApplicationRevision` with value `0`

The benefit of this approach is that it is a little bit more flexible. The `A.B.C.2%a` style version can be used to inject a rolling build number into a ClickOnce application.

Is this something you would like to include in GitVersion, or is this requirement in general "too specific"?

**Comment by thoemmi** [comment]
@fwinkelbauer @maikebing 
I'm using gitversion in an internal clickonce application. It's quite easy to setup. I've added following target in my .csproj file:
```xml
<Target Name="MyApp_SetClickOnceVersion" AfterTargets="UpdateAssemblyInfo" DependsOnTargets="GetVersion" BeforeTargets="_DeploymentComputeClickOnceManifestInfo">
  <CreateProperty Value="$(GitVersion_AssemblySemVer)">
    <Output TaskParameter="Value" PropertyName="ApplicationVersion" />
  </CreateProperty>
</Target>
```
This will set the property `ApplicationVersion` dynamically to the correct value.

**Comment by fwinkelbauer** [comment]
@thoemmi yeah I agree, this is another simple solution that works. I was providing all this input so that we could consider if it is a good idea to integrate ClickOnce support into GitVersion. This way we wouldn't need to touch the `.csproj` file at all.

By the way what does the `PublishVersion` tag do? I know that this is the name provided in the Visual Studio settings panel, but from what I know `ApplicationVersion` and `ApplicationRevision` are the only tags that influence the ClickOnce version. Am I missing something?

**Comment by thoemmi** [comment]
I've implemented it already a couple of month ago. If I remember correcty, `PublishVersion` was necessary to get the deployment working, i.e. calling `msbuild.exe` with `publish` target.

**Comment by JakeGinnivan** [comment]
Agree with the general consensus that it's easy to workaround not putting support in. If we did the solution wouldn't work for those using mage anyways, so it wouldn't even be a complete solution.

I have written up a more complete response at https://github.com/GitTools/GitVersion/issues/1152, but the tl;dr is that I do not want us to put built in updating anything into GitVersion. Instead we should spin up a collection of smaller utilities which take the output of GitVersion and do the updates. This reduces the complexity and scope of GitVersion which is a good thing.

**Comment by JakeGinnivan** [comment]
If anyone would like to take these workarounds and add them into the docs, that would be great though :) pull requests welcome
