### ISSUE TITLE
Version incremented on the feature branch for each commit when master is merged to the branch (Mainline mode)

### ISSUE THREAD

**Issue by jmansar** [GitTools/GitVersion#1154]
Consider the scenario:
1. `branch1` created from `master`
2. `branch2` created from `master`
3. Commits made on `branch1`
4. Commits made on `branch2`
5. `branch1` merged to `master`
6. `master` merged to `branch2`

which produces the following git history:
```
*   25f7623 (feature/branch2) Merge branch 'master' into feature/branch2
|\
| *   8817493 (HEAD -> master) Merge branch 'feature/branch1'
| |\
| | * c13b6d5 (feature/branch1) Added file2.txt
| | * 9ae1abc Added file1.txt
| |/
* | 6797857 Added file5.txt
* | e7d0682 Added file4.txt
* | 0e82f7b Added file3.txt
|/
* 260cada Initial
```

When the mode is set to Mainline, the generated version for the `master` is `0.1.1`, which is correct as the initial is `0.1.0` and the patch number got incremented by the merge of the `branch1`.
However, for the `branch2` it is `0.1.4-branch2.4`. Shouldn't it be `0.1.2-branch2.4` instead, which is the next increment?

The diagnostics output shows that it treats commits on the `branch2` as direct commits on `master`:
```
  INFO [02/11/17 19:23:17:68] Direct commit on master 0e82f7b18cc0a9e502e5d0f17f0fe16472232d12 incremented base versions Patch, now 0.1.1
  INFO [02/11/17 19:23:17:68] Direct commit on master e7d0682dfae7b9b53dd506a882bb711de5d0405c incremented base versions Patch, now 0.1.2
  INFO [02/11/17 19:23:17:69] Direct commit on master 6797857a21ca608588dbf82f05cc6aae7d0190e6 incremented base versions Patch, now 0.1.3
```
Here is the link to the repo for the reference: [Test Repository](https://github.com/jmansar/gitversion-mainline-test)

**Comment by JakeGinnivan** [comment]
Looks like a legit issue, thanks for reporting! Here is a test which replicates it:

```
    [Test]
    public void VerifyIssue1154_CanForwardMergeMasterToFeatureBranch()
    {
        using (var fixture = new EmptyRepositoryFixture())
        {
            fixture.MakeACommit();
            fixture.BranchTo("feature/branch2");
            fixture.BranchTo("feature/branch1");
            fixture.MakeACommit();
            fixture.MakeACommit();

            fixture.Checkout("master");
            fixture.MergeNoFF("feature/branch1");

            fixture.Checkout("feature/branch2");
            fixture.MakeACommit();
            fixture.MakeACommit();
            fixture.MakeACommit();
            fixture.MergeNoFF("master");

            fixture.AssertFullSemver(config, "0.1.2-branch2.4");
        }
    }
```

Looking into a solution now

**Comment by JakeGinnivan** [comment]
Took a while, but got to the bottom of it. There were some flaws in the mainline logic. The behavior is now:

* Before calculating the mainline version to base the feature branch version off
    * Remove all commits which are not on the mainline
* Then only increment a feature branch finally if the feature branch has been merged into mainline (for pull request HEAD build refs)

This actually highlighted a bad assertion in another test. This will be a good improvement to mainline. Thanks!
