### ISSUE TITLE
Identify multiple builds against same commit/tag/branch on Team Foundation Build (vNext)

### ISSUE THREAD

**Issue by ralphhendriks** [GitTools/GitVersion#1157]
Dear all,

I am trying to figure out the best practice to distinguish between multiple builds against the same commit/tag/branch.  My current project is on TFS (on premise). TFS (as well VSTS) stores the build configuration separately from the source repository.  Hence, multiple builds against the same commit/tag/branch could result in different artifacts.  I would like the build metadata to reflect this.

Before using GitVersion we have solved this by using the revision counter from the TFS Build.  The default mechanism of TFS determines the build number before any build task is invoked.  There is a build number replacement token `$(Rev:.r)` that can be used to make the build number unique when nothing else changed ([docs](https://www.visualstudio.com/en-us/docs/build/define/general#tokens)).  We used to rely on the build number, and parse the SemVer and build metadata from it.

As explained in the [docs](http://gitversion.readthedocs.io/en/latest/build-server-support/build-server/tfs-build-vnext/#using-gitversion-variables-in-build-name), GitVersion doesn't play nice with the revision number replacement token on the build number because of delayed expansion in the GitVersion TFS task.  That leaves the problem that multiple builds against the same commit/tag/branch will result in the same output of GitVersion.

I am wondering how others cope with this issue.  I am willing to contribute to the docs if there is a clear consensus on how to handle this.  If there isn't, then adding something to the GitVersion output that is sufficiently unique and sortable (i.e. a timestamp) might be a way forward.

I am interested in hearing you opinions.

**Comment by JakeGinnivan** [comment]
I think the ideal solution is to allow GitVersion to take some sort of build_number or revision parameter which can be used, surfaced in variables and in the build metadata. That way you can pass in an external variable into GitVersion and it will affect the build number.

Would love a PR for this :)

**Comment by JakeGinnivan** [comment]
The discussion at https://github.com/GitTools/GitVersion/issues/648 raised a similar issue. Going to close it in favor of this. I am now more keen on the idea than I was then

**Comment by asbjornu** [comment]
Where would the build number be used? If it's in any of the `Assembly*Version` attributes, I think the route of adding support for environment variables and adding a `-format` version for the ones that currently only have `-scheme` variants in the configuration might be a good solution (as mentioned in https://github.com/GitTools/GitVersion/issues/1145#issuecomment-372080318 and https://github.com/GitTools/GitVersion/issues/1367#issuecomment-372081440).

I'm envisioning something like this:

```yaml
assembly-versioning-format: '{Major}.{Minor}.{Patch}.{env:BUILD_NUMBER}'
assembly-file-versioning-format: '{Major}.{Minor}.{Patch}'
assembly-informational-format: '{InformationalVersion}-{env:MY_ENV_VAR}'
```

The novel thing here is the `{env:}` syntax, which allows you to reference any environment variable available at build time in `GitVersion.yml`. Would this suffice?

**Comment by jbaehr** [comment]
Regarding the discussion in #648: I think the conclusion over there is still valid. But here we're taking about something else. As  far as I understood, the decision was against the expansion of env-vars within the config.yml (`buildMetadata: $ENV['BUILD_NUMBER'] || 1313`). The current approach is the expansion of env vars in format strings (`assembly-file-versioning-format: '{Major}.{Minor}.{Patch}.{$JENKINS_BUILD_NUMBER}'`). That is something else and in my eyes a much better idea, indeed.

We need some fall-back though in case the env var is not set. In our case we want the build number from the CI-server as forth digit in the AssemblyFileVersion (and only there; to properly support Windows Installer's "Major Upgrades", see #1366). On a developer's machine I don't want to set dummy build server env vars. What do you think about the following?
```
mode: ContinuousDeployment
assembly-versioning-scheme: Major
assembly-file-versioning-format: '{Major}.{Minor}.{Patch}.{$JENKINS_BUILD_NUMBER??0}'
tag-prefix: '[vV]'
...
```
In a format string we could have either
- `{GitVersionVariable}` (e.g. `{Major}`),
- `{$ENV_VAR}`, every placeholder prefixed by `$` is treated as environmental variable
- `{$ENV_VAR??fall-back-string}`. The syntax as well as the function is inspired by C#'s null-propagation operator.

**Comment by sanderaernouts** [comment]
@ruhullahshah can I use this `{env:VARIABLE_NAME}` notation as well for versioning the pre-release tag? 

I'm currently pushing NuGet packages as part of my PR builds in Azure DevOps. But if I use merge commits to keep my commits clean GitVersion will give the exact semantic version number, for example: `2.0.0-pr5566.10`. What I would like to do to ensure my version is unique is to get something like `2.0.0-pr5566.10.<BUILD_ID>`. The build id in azure DevOps is in an incrementing ID that is always unique so I would be sure that my next build results in a higher SemVer 2 version number.

**Comment by ruhullahshah** [comment]
@sanderaernouts For the first part of your query, AFAIK you will have to add support for enabling `{env:VARIABLE_NAME}` notation to affect the `PreReleaseTag` in [variables](https://gitversion.readthedocs.io/en/latest/more-info/variables/).

For the second part, you could achieve this without any changes by setting the `assembly-file-versioning-format` config. value (for more details, see [configuration](https://gitversion.readthedocs.io/en/latest/configuration/)). 

An example might help. In your GitVersion.yml, set:
`assembly-file-versioning-format: {Major}.{Minor}.{Patch}.{PreReleaseTag}.{env:AZURE_BUILD_ID}`. After running GitVersion.exe with this configuration value set, you could use the output of either `AssemblySemVer` or `AssemblySemFileVer`(i am a bit rusty on this part, please verify) to get a unique version number.

**Comment by miketonguk** [comment]
This issue appeared to be getting some consensus, but then unfortunately has gone stale without any resolution. Are there still plans to add the ENV variable expansion in build format strings, or has it been done already?

**Comment by asbjornu** [comment]
This was added in #1385.
