### ISSUE TITLE
Documentation for https://gitversion.readthedocs.io/en/latest/reference/pull-requests/ is empty

### ISSUE THREAD

**Issue by ghuntley** [GitTools/GitVersion#1159]
Happy to send a PR back uptown. Can one of the main contributors provide an outline/toc of what they would like to explain on this page?

I got here as I'm after enlightenment (which I''m digging through the source to find out.... good codebase btw... really enjoying the unit tests) as to how a pull-request affects the versioning outcome.

**Comment by JakeGinnivan** [comment]
Unsure what the goal of that particular reference was when it was created but the TL;DR of this is:

 - GitVersion will automatically fetch the remote pull request refs
 - If it sees the current branch matches a PR ref then it will extract the pull request number out of the PR branch ref
 - It will then try and figure out how many commits are on that PR
 - The version will then be: {majorMinorPatch} of the branch it originated from with the prerelease of `-PullRequest.{pullRequestNumber}-{CommitCount} or something like that.

If you want me to expand on any of the sections just ask
