### ISSUE TITLE
Add Username+Password support to MSBuild Task

### ISSUE THREAD

**Issue by SimonCropp** [GitTools/GitVersion#116]
similar to this https://github.com/Particular/GitVersion/issues/21#issuecomment-38317051

**Comment by asbjornu** [comment]
Isn't this supported through the use of environmental variables?

**Comment by GeertvanHorrik** [comment]
That will be difficult if you have multiple accounts for multiple repositories. But to be honest, I only use GitVersion on the server, and then I prefer the command line tool anyway.

For this to work via environmental variables, we need something like *GitVersion_[RepoName]_UserName*.

**Comment by asbjornu** [comment]
With TeamCity, environment variables are per build configuration which is scoped to one VCS anyway, so within that context, there shouldn't be a problem. But in other contexts, I agree that they probably need some kind of namespacing or other scoping mechanisms.
