### ISSUE TITLE
Question: 4.x availability

### ISSUE THREAD

**Issue by steelerc** [GitTools/GitVersion#1160]
Any clue when a 4.x version can be expected in the TFS marketplace?  

Awesome tool, just really want the new features.

Thanks
Rob

**Comment by mlooise** [comment]
What I did for now (need the 4.0 functionality also) is copied the choco version of gitversion 4 to the buildserver and then changed the gitversion.exe location as so:

![image](https://cloud.githubusercontent.com/assets/2109791/23318518/157e5b32-fad3-11e6-9f2b-d5a289e54418.png)

This works and allows me to use the 4.0 version and also the normal plugin.

**Comment by JakeGinnivan** [comment]
Two things need to be done:

 - Enable publishing a pre-release to the VSTS marketplace, when I setup the build you could only publish stable
 - Ensure mainline mode is ready and well enough documented

I want to do a sweep of issues and close as many legit bugs for v4 as I can then I will likely just release stable in the next week or so.

**Comment by brettpostin** [comment]
Any update on this? Looking forward to mainline mode!

**Comment by pvandervelde** [comment]
Any idea on when 4.0 is going to be released. It's got a ton of bug fixes we would love to use!

**Comment by JakeGinnivan** [comment]
Builds are fixed, going to try and do a pass on open issues this week and I think we should just release....

**Comment by tesharp** [comment]
Any progress on open issues? Waiting for some bug fixes so we do not have to do a lot of manual cleanup when its versioning our packages incorrect.

**Comment by pvandervelde** [comment]
@JakeGinnivan Any chance this is going out soon. I just noticed the first beta was on June 20th last year. We would love to get our hands on this, it fixes a number of issues we're seeing with 3.6.5

**Comment by dschuermans** [comment]
@JakeGinnivan VSTS supports tasks with preview versions.. I don't see the issue in pushing the beta builds onto the marketplace as preview versions?
Let the consumer decide whether they want to use 3.* or 4.* beta...

**Comment by pcoombe** [comment]
Except the latest 4 beta version is not in nuget

**Comment by dschuermans** [comment]
@pccoombe The latest latest version is not available indeed. But as you can see in my screenshot, 4.0.0-beta12 is
