### ISSUE TITLE
Problem with AssemblyVersion being higher than pre-release when dealing with nuspec files

### ISSUE THREAD

**Issue by Eregrith** [GitTools/GitVersion#1161]
I have a visual studio (2015) solution which contains multiple projects with cross dependencies.
I have set up a .nuspec file for each project so these are treated as package dependencies when I use nuget pack -IncludeReferencedProjects
Those nuspec files simply contain $id$ and $version$ and are used through a pack command on the corresponding csproj

My problem comes from the fact that I need to set the package version to Major.Minor.Patch-prerelease, which I do using -Version option of nuget pack

BUT

GitVersionTask sets the assembly version to Major.Minor.Patch without the prerelease string.
This means at calculated version 1.0.1-develop I have projects depending on assemblies versionned 1.0.1
Thus, all my nuget packages are 1.0.1-develop (Which is < 1.0.1) but depend on >= 1.0.1 of referenced projects.

Because of that I can't effectively do anything else than stable versionning, which I need to do.

Is there any way to either:
 Configure GitVersionTask to add prerelease to AssemblyVersion,
 Have NuGet understand i depend on the equivalent prerelease 
 Do anything else to make it work?

**Comment by asbjornu** [comment]
Can't you use one of the GitVersion variables that include the prerelease tag as the argument to `nuget pack -Version`? Either way, as far as I can tell, depending on a prerelease package is basically not supported by `nuget.exe` until NuGet/NuGet.Client#1073 is released.

**Comment by Eregrith** [comment]
I am. Currently my nuget pack looks like this:

nuget pack my.csproj -Version 1.0.1-a0009-develop -IncludeReferencedProjects

Visual studio allows depending on prerelease packages (there is a "show prerelease" checkbox in the NuGet window). The problem comes from the fact that the actual version is equivalent to 1.0.1-prerelease while GitVersionTask sets AssemblyVersion to 1.0.1 : this makes the process behind -IncludeReferencedProjects think the dependency is on 1.0.1 (stable).
When I try to use one package, nuget raises an error because there is no 1.0.1 stable to satisfy the (>=1.0.1) dependency.
GitVersionTasks sets the AssemblyVersion to a stable version on something that is not yet stable, which becomes a problem when we need to differentiate 1.0.1-develop ; 1.0.1-feature-foo ; 1.0.1-feature-bar for example.

The packages.config in the projects can use a prerelease-version such as 1.0.1-develop but using -IncludeReferencedProjects makes nuget select the version referenced based on the AssemblyVersion of the dlls referenced (which csproj have a corresponding nuspec). That AssemblyVersion is not a prerelease string ans is actually higher than the "real" version

**Comment by asbjornu** [comment]
Won't you say this is a bug in NuGet, though? If it bases its version comparison on the `AssemblyVersion` alone (which must be a valid `System.Version` in the strict `Major.Minor.Build.Revision` format), this will never work. There is no way we can inject a version between the stable versions `1.0.0` and `1.0.1` without using prerelease tags. If NuGet gets the version number for comparison purposes from the assembly, it should use `AssemblyInformationalVersion` instead, which includes the prerelease tag and will evaluate as a lower version number than the same without a prerelease tag as per [SemVer 2.0](http://semver.org/).

**Comment by Eregrith** [comment]
Maybe you're right it might be better if NuGet based that info on AssemblyInformationalVersion

Why doesn't GitVerdionTask use prerelease tags in the AssemblyVersion though? Is it forbidden by the format of that value?

I'm aware you can't simply let the lower version in AssemblyVersion because that would be impossible to guess.

Seems i am screwed with that ... I'll try changing my strategy to gather the dll and package them accordingly. The 1-nuspec-per-csproj has failed.

I'll go over to NuGet and leave them an issue about that on their side though. Who knows...

**Comment by Eregrith** [comment]
Oops Sorry I didn't see you already answered the format question

**Comment by Eregrith** [comment]
Oh well, looks like this issue :https://github.com/NuGet/Home/issues/1794

Tells me my problem is still maybe solvable with your help.
AssemblyInformationalVersion contains the full SemVer 2.0 prerelease version (something like 1.0.1-Branch.develop+9)
Apparently NuGet fails to read that. Is there any way to set the format of AssemblyInformationalVersion to something like Major.Minor.Patch-[A-Za-z0-9-] ? Maybe that would work

**Comment by asbjornu** [comment]
@Eregrith: Please correct me if I'm wrong, but I believe NuGet expects the format of `AssemblyInformationalVersion` to be `System.Version` as well, so no matter what we append at the end of the version number, it's going to fail.

**Comment by Eregrith** [comment]
:(

I'll check on that and get back to you.
In the meantime, is there a mean to setup that value's format in GitVersionTask's config?

**Comment by asbjornu** [comment]
#886 asks for something similar.

**Comment by Eregrith** [comment]
In the [NuGet Docs](https://docs.microsoft.com/fr-fr/nuget/create-packages/prerelease-packages#semantic-versioning) there is an example where the AssemblyInformationalVersion is :
`[assembly: AssemblyInformationalVersion("1.0.1-beta")]`
So I guess following issue #886 will solve my problem.
Thanks for your help, I guess you can close this one as #886 is already on "the actual problem"

**Comment by asbjornu** [comment]
@Eregrith: Ok, cool.
