### ISSUE TITLE
GitVersionTask uses .git relative to SolutionDir

### ISSUE THREAD

**Issue by mrswain** [GitTools/GitVersion#1162]
The targets and coding for GitVersionTask seem to use the .git repository relative to the SolutionDir instead of the project folder. This has started to cause versioning issues for projects in sub repositories. I am not sure when this change occurred but it used to not be this way. Ideally it should use the .git repository closest to the project being built and only fall back to the solution repository via option (i.e. when explicitly wanted.)

For now I worked around this by manually editing the targets file to use MSBuildProjectDirectory instead of SolutionDir.

**Comment by asbjornu** [comment]
I agree that the closest `.git` folder should be used. Want to tackle this in a pull request?

**Comment by mrswain** [comment]
PR #1163 has been submitted for review, though this only address the targets file, the task assembly should probable be cleaned up as well to reflect using path instead of explicitly using the solution dir, just so the semantics are clear.

**Comment by JakeGinnivan** [comment]
Appreciate the PR @mrswain
