### ISSUE TITLE
Configuration question

### ISSUE THREAD

**Issue by ermshiperete** [GitTools/GitVersion#1174]
Sorry if this is obvious or documented somewhere - I couldn't find anything.

We use a workflow where the development happens on `master`. From time to time we merge to a `qa` branch that gets manually tested. If the tests are satisfactory we merge to `live` which then gets deployed.

For each merge to `live` we'd like to increment our version. `master` and `qa` should have pre-release labels appended.

Example:

    master                    qa                  live
    <-------------------------<-------------------tag: 1.0.0
    <commit>
    1.0.1-alpha.1
    <commit>
    1.0.1-alpha.2
    merge-------------------->1.0.1-beta.1
	                          merge-------------->1.0.1
    <---------------------------------------------merge
    <commit>
    1.0.2-alpha.1

It looks like `Mainline` would partially give me that, but I have a hard time to get the settings for the `master` branch right. Any suggestions how the configuration should look like?

Thanks!

**Comment by asbjornu** [comment]
Since you're pretty much using a simplified variant of Git flow already, I would simply suggest you label your branches differently. Here's a suggestion:

1. `master` → `develop`
2. `qa` → `release/*`
3. `live` → `master`

Then I assume GitVersion would be better in sync with what you're trying to do and you won't have to configure anything at all, really.

**Comment by ermshiperete** [comment]
That's an idea. I can also look at the default configuration and then adjust the branches.

However, the Git flow approach requires to tag each version which I though I could get around by using `Mainline`. But it looks like that only works for one branch plus feature branches.
