### ISSUE TITLE
Question: GitVersion Configuration

### ISSUE THREAD

**Issue by Tankatronic** [GitTools/GitVersion#1178]
I have spent a lot of time trying to wrap my head around GitVersion and what it is doing. Just when I think I understand the workflow, I realize I don't! I wanted to give an example workflow with how we would like GitVersion to work, and if it is possible to configure it to behave this way or not.

Our master branch is our release branch. Development happens on develop, where we branch off for features/bugs. We really like the idea of using the commit bump messages to control when and what versions increment. I have not been able to get them to work, at least in the way that I would expect. 

Say develop is currently version 2.0.0. I branch off featureA, and finish it and it's ready to merge back into develop. Another team member reviews featureA, determines that it is just a minor version difference, and merges it back in with +semver: minor in the merge message. bugA was also branched off and when it is merged back into develop a +semver: fix is put into the merge message. 

Now what I would _expect_ to happen would be that when develop merges in featureA, it is incremented to version 2.1.0. When it merges in bugA it is incremented to version 2.1.1. I understand that this isn't really what is going to happen because it has not been released yet. develop stays at version 2.0.0 through this entire process. Please correct me if I am wrong here.

After doing some research and going through issues, what I think should happen is that once development is done on develop and we merge it into master, that is when the version will be incremented. Since there was a +semver: minor and a +semver: fix, only the minor version will change and the patch version will remain at zero with a resulting version of 2.1.0 on master. When development resumes on develop, it should see that master has had the version incremented and then increment its own version to 2.1.0.

The problem is, I have not been able to get master to increment its version. It remains at 2.0.0. What mode should I be using to get this to function?

**Comment by asbjornu** [comment]
Does @JakeGinnivan's answer https://github.com/GitTools/GitVersion/issues/1137#issuecomment-282482205 help in any way?

**Comment by Tankatronic** [comment]
Sorry for the delayed response. This question can be closed. The comment did help slightly but I think we figured out a configuration that worked for us.
