### ISSUE TITLE
Static revision number

### ISSUE THREAD

**Issue by matkoch** [GitTools/GitVersion#1182]
Is it possible to have a static revision number (apart from assemblying it myself) ?

Background is, that I'm compiling a plugin against a certain product which has a version itself. For convenience, I would like to include that version number (without dots) into my revision number.

**Comment by JakeGinnivan** [comment]
Can you give an example? Just to be clear what you mean about a revision number. Also how does it fit into pre-release tags etc?

**Comment by matkoch** [comment]
This [ReSharper plugin](https://resharper-plugins.jetbrains.com/packages/ReSharper.ImplicitNullability/) is a good example.

There are several versions of another application (here ReSharper) that you want to support. The codebase of the plugin is basically the same for all different ReSharper verions (except small `#ifdef` workarounds). And in order to identify for which version the plugin was build, I would like to put the `Major.Minor` version into the revision number. The rest would be as usual.

**Comment by jbaehr** [comment]
Our proposal to support of env-vars in format strings (see pull request #1385) could also address this issue. Currently format strings are only supported for the informational version and (with #1385) for the assembly file version. However, allowing them for the assembly version, too, should be easy.

**Comment by asbjornu** [comment]
Support for using environment variables was introduced with the `env:` prefix in #1385. Closing.
