### ISSUE TITLE
What is the current stable version?

### ISSUE THREAD

**Issue by ilovezfs** [GitTools/GitVersion#1184]
I notice the release marked "latest release" (4.0.0-beta.10)  is also marked "beta." Is that the latest stable release? In other words does it supersede 3.6.5, or is 3.6.5 still the latest stable version? I'm asking because I'm not sure what actually belongs in the stable spec for Homebrew.

**Comment by asbjornu** [comment]
`3.6.5` is still the latest stable version of GitVersion. Version 4 is still in beta because its commit counting has been extensively rewritten.

**Comment by ilovezfs** [comment]
OK. Thanks for clarifying. Just my two cents: in the GitHub GUI it would probably be best to designate 3.6.5 as the "latest release," not v4.0.0-beta.10.

**Comment by gep13** [comment]
>@ilovezfs said...
in the GitHub GUI it would probably be best to designate 3.6.5 as the "latest release," not v4.0.0-beta.10.

Can you confirm exactly what you are referring to?

**Comment by ilovezfs** [comment]
Scroll through https://github.com/GitTools/GitVersion/releases where you'll see that v4.0.0-beta.10 think it's the latest release.

**Comment by ilovezfs** [comment]
If you go to https://github.com/GitTools/GitVersion/releases you can click "Edit" on the right side or if you go to https://github.com/GitTools/GitVersion/releases/tag/v4.0.0-beta.10 you can click "Edit release" in the upper right. Then at the bottom, check the box for "This is a pre-release" and save.

**Comment by gep13** [comment]
Yip, was already doing that :smile: should now be done.

**Comment by ilovezfs** [comment]
@gep13 thanks. Much better!
