### ISSUE TITLE
Support for new VS2017 project style

### ISSUE THREAD

**Issue by roryprimrose** [GitTools/GitVersion#1185]
I've just installed VS2017 RTM and am trying to convert an existing net40 project to target netstandard1.3;net452. I've replaced the proj files and then run install-package gitversiontask -pre.

This is what my proj file looks like now.

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard1.3;net452</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'netstandard1.3'">
    <PackageReference Include="System.Reflection.TypeExtensions">
      <Version>4.3.0</Version>
    </PackageReference>
    <PackageReference Include="System.Xml.XmlSerializer">
      <Version>4.3.0</Version>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="gitversiontask" Version="4.0.0-beta0011" />
  </ItemGroup>
  
</Project>
```

Looks like GitVersionTask is not invoked during the build of the project. Am I missing something?

**Comment by asbjornu** [comment]
I have no idea how project imports should look like in Visual Studio 2017, but this is how it looks like in the old `.csproj` format:

```xml
<Import Project="..\..\packages\GitVersionTask.3.5.4\build\dotnet\GitVersionTask.targets" Condition="Exists('..\..\packages\GitVersionTask.3.5.4\build\dotnet\GitVersionTask.targets')" />
```

Without this `.targets` file imported, GitVersionTask won't really **do** anything. A `PackageReference` isn't the same thing, I believe.

**Comment by roryprimrose** [comment]
I would assume the same for packages wanting to use imports. So the issue here then is that GitVersionTask did not update the project to include the new target.

**Comment by roryprimrose** [comment]
Ah, the target is imported under the obj folder. Looks like it is working fine. :)
