### ISSUE TITLE
Manually bumping version doesn't work as expected

### ISSUE THREAD

**Issue by bendetat** [GitTools/GitVersion#1187]
I'm trying to bump the semver version manually to allow TeamCity build to flow to Octopus Deploy with a configuration change on OD (since OD requires a new build & version to deploy changed a changed configuration).

I was expecting to be able to push an empty commit `git commit --allow-empty -m "+semver: patch"` to master resulting in an increment to the patch version. It turns out that this doesn't work. The actual codebase uses a `GitVersion.yml` file with `commit-message-incrementing: Enabled` (the default) however I can replicate the behaviour in a new repo.

I suspect that I'm doing something wrong. It does appear from looking at the GitVersion code that it just looks for any commits since the last version bump that match the triggering regex, and doesn't count them to implement multiple version increments, which matches the behaviour I'm seeing.

Even adding `GitVersion.yml` specifying the next version doesn't work as expected (as per the end of the below).

What then is the best way to bump versions manually?

```
git init

<path-to>\gitversion.exe    -> null reference exception, no commits (expected)

git commit --allow-empty -m "1"
<path-to>\gitversion.exe    -> 0.1.0 (as expected), FullSemVer: 0.1.0+0

git commit --allow-empty -m "+semver: patch"
<path-to>\gitversion.exe    -> 0.1.1 (as expected), FullSemVer: 0.1.1+1

git commit --allow-empty -m "+semver: patch"
<path-to>\gitversion.exe    -> 0.1.1 (expected 0.1.2), FullSemVer: 0.1.1+2

git commit --allow-empty -m "2"
<path-to>\gitversion.exe    -> 0.1.1 (as expected), FullSemVer: 0.1.1+3
git commit --allow-empty -m "+semver: patch"
<path-to>\gitversion.exe    -> 0.1.1 (expected 0.1.2), FullSemVer: 0.1.1+4

touch readme.me
git add -A
git commit -m "3"
<path-to>\gitversion.exe    -> 0.1.1 (as expected), FullSemVer: 0.1.1+5
git commit --allow-empty -m "+semver: patch"
<path-to>\gitversion.exe    -> 0.1.1 (expected 0.1.2), FullSemVer: 0.1.1+6

git commit --allow-empty -m "+semver: minor"
<path-to>\gitversion.exe    -> 0.2.0 (as expected), FullSemVer: 0.2.0+7

git commit --allow-empty -m "+semver: patch"
<path-to>\gitversion.exe    -> 0.2.0 (expected 0.2.1), FullSemVer: 0.2.0+8

git commit --allow-empty -m "+semver: minor"
<path-to>\gitversion.exe    -> 0.2.0 (expected 0.3.0), FullSemVer: 0.2.0+9

add a GitVersion.yml file:
branches: {}
ignore:
  sha: []
commit-message-incrementing: Enabled
next-version: 0.3.0

<path-to>\gitversion.exe    -> 0.4.0 (expected 0.3.0), FullSemVer: 0.4.0+9

```

**Comment by asbjornu** [comment]
Which version of GitVersion are you using?

**Comment by bendetat** [comment]
I'm using 3.6.4 - specifically https://www.nuget.org/packages/GitVersion.CommandLine/3.6.4

**Comment by asbjornu** [comment]
@bendetat: Can you please try version 4 beta 11 and see if that works better?

**Comment by bendetat** [comment]
@asbjornu I get the same behaviour on 4 beta 11.

From what I understand from scanning [`IncrementStrategyFinder`](https://github.com/GitTools/GitVersion/blob/61efda5fa0ecd9d955c021c22608c6527850fcd4/src/GitVersionCore/IncrementStrategyFinder.cs#L83) the increment is the max of the intermediate commits based on the commit message, not the _sum_, so what I'm seeing is probably as intended. Which is why I think I'm holding it wrong, so I'm not sure how to manually rev the version or if this is even supported easily by GitVersion.

**Comment by asbjornu** [comment]
@bendetat: Does @JakeGinnivan's answer https://github.com/GitTools/GitVersion/issues/1137#issuecomment-282482205 help explain this in any way?

**Comment by fokkoru** [comment]
@asbjornu @bendetat Hi guys, any updates? It looks that I have the same problem.

**Comment by asbjornu** [comment]
@fokkoru: Did you see my comment about @JakeGinnivan's comment? 😄

**Comment by bendetat** [comment]
@asbjornu _I_ didn't see your comment about @JakeGinnivan 's comment ;-). Makes sense, although it's obviously not what I was expecting. I would suggest a config option where it does count the commits, for instances where there is either a clear gatekeeper or a single maintainer, but I would probably get asked for the PR. Meanwhile @fokkoru my current workflow for this scenario (using github and parts of gitflow) involves setting the version in a release branch name:

1. Check out develop
2. git commit --allow-empty -m "bump version"
3. git push develop:release/0.1.3
4. Create a PR with the new branch
5. Change the "base" to master
6. Merge the PR

The normal workflow (releasing work in `develop` to `master`) is:

1. Check out develop locally & get it up to date with what you want in the release candidate
2. Push the new branch: git push develop:release/0.1.2 (obviously replace the version number with the intended new semver version)
3. Create a PR with the new branch
4. Change the "base" to master
5. Merge the PR

Again, I'm sure there's a better way but it's working for _this_ project at least.
