### ISSUE TITLE
VS2017 package build include gitversiontask as a dependency

### ISSUE THREAD

**Issue by roryprimrose** [GitTools/GitVersion#1188]
I have a new VS2017 project that targets netstandard1.3, builds a nuget package on compile and defines the following dependencies:

```
  <ItemGroup>
    <PackageReference Include="Ensure.That" Version="5.0.0" />
    <PackageReference Include="gitversiontask" Version="4.0.0-beta0011" />
    <PackageReference Include="nodatime" Version="2.0.0-beta20170123" />
  </ItemGroup>
```

The nuspec included in the nupkg then contains the following dependencies:

```
    <dependencies>
      <group targetFramework=".NETStandard1.3">
        <dependency id="gitversiontask" version="4.0.0-beta0011" exclude="Build,Analyzers" />
        <dependency id="NETStandard.Library" version="1.6.1" exclude="Build,Analyzers" />
        <dependency id="nodatime" version="2.0.0-beta20170123" exclude="Build,Analyzers" />
        <dependency id="Ensure.That" version="5.0.0" exclude="Build,Analyzers" />
      </group>
    </dependencies>
```

This would result in gitversiontask being installed into any project that consumes this package. Is there an equivalent version of the development dependency flag that there was in the VS2015 world?

**Comment by roryprimrose** [comment]
I suspect this is a bug in VS2017 as the nuspec of GitVersionTask contains the development dependency flag

https://github.com/GitTools/GitVersion/blob/master/src/GitVersionTask/NugetAssets/GitVersionTask.nuspec#L16

**Comment by roryprimrose** [comment]
This has already been raised by @onovotny at https://github.com/NuGet/Home/issues/4125

**Comment by tofutim** [comment]
Has this been resolved?
