### ISSUE TITLE
Why tracks-release-branches:false for feature?

### ISSUE THREAD

**Issue by DixonDs** [GitTools/GitVersion#1192]
I am fairly new to GitVersion, and trying to understand the reasoning for versions in GitFlow. If we have master tagged as 4.5.3, and then we have release/4.6.0 branch created, then develop branch uses version 4.7.0-alphaX. So far so good. What I don't understand is that if there is feature/YYY, then it uses version 4.5.4-XXX. Shouldn't it be 4.7.0-XXX?

**Comment by asbjornu** [comment]
Sorry you never got an answer. If this is still an issue in the latest v5 beta, please reopen.
