### ISSUE TITLE
dirty flag?

### ISSUE THREAD

**Issue by Trass3r** [GitTools/GitVersion#1198]
Couldn't find a way to get a dirty flag, like `git describe [...] --dirty`

**Comment by asbjornu** [comment]
What is it you want to achieve?

**Comment by Trass3r** [comment]
Well a dirty flag in the informational version when there are locally modified files.

**Comment by asbjornu** [comment]
Ah, yes that would be a good thing to have, I agree. We welcome pull requests! 😄

**Comment by Sam13** [comment]
I did some prototyping on that. Since the git versions are cached in the _.git_ folder, I don't know how the dirty flag should behave. Causes wrong results when caching that. @asbjornu what do you propose?

**Comment by asbjornu** [comment]
Makes sense. Perhaps when calculating `--dirty`, you need to disable caching altogether?

**Comment by brdmllr** [comment]
I hope this isn't a naive solution as I haven't spent a lot of time looking at the GitVersion source, but could the output of the "git status --porcelain" command act as input for this feature and if that input has a non-zero length, something is added to the informational version?

**Comment by Sam13** [comment]
The thing which should be achieved by this issue, is that the informal assembly version contains an information whether the working copy has local modifications or not.

If _git status_ provides this information as well we may also use this command as source for that information.

**Comment by Sam13** [comment]
Still a useful feature in my opinion

**Comment by asbjornu** [comment]
@Sam13, I agree, but unless someone submits a PR that implements this, the feature won't make its way into GitVersion.

**Comment by simonbuehler** [comment]
hi,

i found how this got handled in another project, could this be incooperated?
   https://github.com/desaster/gitrevsubst/commit/544462be2a60cf4ebf53543329147f40a1071302#diff-a8d7dc4a2b96ae65d37ab09ad03939dd

basicaly its testing `describe --always --dirty` if it ends with "dirty"

**Comment by sbyholm** [comment]
I was searching for this, would be happy to have a dirty flag in GitVersion

**Comment by asbjornu** [comment]
A PR implementing this would be merged, I'm sure.
