### ISSUE TITLE
Documentation references to unstable versus alpha

### ISSUE THREAD

**Issue by thegersh** [GitTools/GitVersion#1200]
I'm seeing that develop and features are being SemVer tagged as unstable rather than alpha, yet I don't see any call out to unstable anywhere in the docs. The docs to date mention alpha, yet that is not what the tool is set up to do. In addition, I've seen a recent communication regarding this which gives a reason for the change from alpha to unstable. Calling this out in the docs would help clarify things. If there is some information that's more up to date regarding the use of unstable for a prerelease tag please point me at it.

**Comment by asbjornu** [comment]
If I'm not mistaken, this is a change between `3.x` and `4.x`. Which version of GitVersion are you using?

**Comment by thegersh** [comment]
I'm using version 3.6.4.

**Comment by asbjornu** [comment]
Right. The latest documentation is for `master`, which has been switched over to version 4. A bit confusing since version 4 is still in beta, but we haven't invested any time in trying to make this more intuitive on ReadTheDocs. I do think versioning the documentation there is possible, so if you know how and want to submit a pull request for it, it would be highly appreciated! 😄

**Comment by JakeGinnivan** [comment]
http://gitversion.readthedocs.io/en/stable/ is for v3. I have added the latest v3.x tag also.

![image](https://cloud.githubusercontent.com/assets/453152/26053219/9413f424-399a-11e7-9284-0d121f736312.png)

**Comment by DanubeRS** [comment]
Just out of curiosity, what was the reason behind the change? I understand that develop in a GitFlow context is rarely published, to me it seems like it breaks SemVer 2.0.0 convention that pre-release identifiers are ordered alphabetically

> Example: 1.0.0-alpha < 1.0.0-alpha.1 < 1.0.0-alpha.beta < 1.0.0-beta < 1.0.0-beta.2 < 1.0.0-beta.11 < 1.0.0-rc.1 < 1.0.0.

Not sure I am interpreting the workflow properly though...
