### ISSUE TITLE
Develop branch not updating correctly with GitFlow settings (based on example)

### ISSUE THREAD

**Issue by kyberias** [GitTools/GitVersion#1206]
I tried to replicate the examples for GitFlow with the default config here: [https://gitversion.readthedocs.io/en/latest/git-branching-strategies/gitflow-examples/](https://gitversion.readthedocs.io/en/latest/git-branching-strategies/gitflow-examples/)

I have branches, tags and commits set up as follows:

![image](https://cloud.githubusercontent.com/assets/958404/25306929/832aff24-27a0-11e7-9e30-8c310c033213.png)

I've initialized GitVersion with the default config (gitversion init, GitFlow, continuous deployment for develop branch)

GitVersion now reports:

- Correctly 0.6.0 for the **master** branch (because of tag)
- Correctly 0.7.0-beta.1 for the **release/0.7.0** branch (because of branch name)
- Incorrectly (I suspect) 0.7.0-unstable for **develop** branch. It's two commits ahead, so it should report something (as in the above example) like 0.8.0-alpha.2

What have I missed? If I have incorrect configuration, please advice how to configure to get the results as in the above examples for GitFlow.

**Comment by kyberias** [comment]
Ok I was using GitVersion.exe version provided by Chocolatey (3.6.0??). The latest version built from git repo seems to work just fine. Maybe this has been fixed earlier?

**Comment by asbjornu** [comment]
@kyberias: Which branch did you compile from source? `master` represents v4, which is a major (in many ways backwards incompatible) upgrade from v3. Also, the latest version of v3 is `3.6.5`.

**Comment by kyberias** [comment]
I think I compiled from master branch (v4).

**Comment by asbjornu** [comment]
Right. Just upgrade to v4 then?
