### ISSUE TITLE
Gitversion performance for big repositories

### ISSUE THREAD

**Issue by tihobrazov** [GitTools/GitVersion#1208]
For our repo running gitversion takes about 2 mins. Recently we imported another repo with history to our main repo and now it takes up to 15 min to run gitversion. Is it possible to add lightweight mode for version generation? 
Possible options:
- add mode for skipping commits count since last version tag (so, 1.0.0-beta.1 tag will force next commit to be 1.0.0-beta.2+1 - now it counts since the beginning of branch. What is more important here is for gitversion to stop calculating any other details)
- optimize commits-before configuration option, now it continues walking over commits, but just skips them (according to log)

**Comment by hazzik** [comment]
Have you tried `/nofetch`?

**Comment by JakeGinnivan** [comment]
I'd love to optimise this stuff, are you able to post the full log in a gist so we can see what is slow?

Any pull requests in this area welcome.

**Comment by zpavic** [comment]
We have a similar situation with a large team and repo and GitVersion takes minutes to run and sometimes crashes. It may be exacerbated with our team workflow of personal forks, PRs, and merge commits but it still makes using GitVersion basically unworkable.

**Comment by JakeGinnivan** [comment]
Can you post your config and log?
