### ISSUE TITLE
Mono compatibility?

### ISSUE THREAD

**Issue by alexreg** [GitTools/GitVersion#1213]
What is the minimum version of Mono required to run GitVersion?

**Comment by asbjornu** [comment]
@alexreg: We don't really know. On Travis, we're using latest, so we don't really have a way to ensure compatibility with older versions of Mono. If you would like to add a [build matrix](https://docs.travis-ci.com/user/customizing-the-build/#Build-Matrix) for older versions of Mono to Travis through a pull request, we can see there what works and what doesn't.

**Comment by alexreg** [comment]
I mean, I'm not too bothered about old versions. Maybe we could keep the current version in for backward compatibility though (4.8.1)?

**Comment by asbjornu** [comment]
@alexreg: Sure. Pull requests welcome! 😃
