### ISSUE TITLE
/updateassemblyinfo should add fully qualified attribute names

### ISSUE THREAD

**Issue by tpluscode** [GitTools/GitVersion#1214]
I've just noticed that when I run `gitversion /updateassemblyinfo` it only adds attributes using only its class name which fails build if `using System.Reflection` is missing. 

I think that the safest path is to always add fully qualified type names which will work regardless of the usings.

**Comment by asbjornu** [comment]
@tpluscode: Agreed. I believe it's best practice for generated code to use the `global::` prefix and fully qualified names. Pull requests are welcome! 😄
