### ISSUE TITLE
Docker improvements

### ISSUE THREAD

**Issue by JakeGinnivan** [GitTools/GitVersion#1218]
I am pretty new with Docker, what we have works but I wonder if anyone can make what we have better.

We have a base image at https://github.com/GitTools/GitVersion/tree/master/src/DockerBase, the mono image doesn't run libgit2 because wheezy is super old and glib2.15 doesn't run on it without adding experimental repos and updating.

So I went with an Ubuntu base image and put mono on it, this seems pretty heavy but seems to work.

Then https://github.com/GitTools/GitVersion/blob/master/Dockerfile builds off the base. Then we publish through our deploy script at https://github.com/GitTools/GitVersion/blob/master/deploy.cake#L196

If you can improve it, send a pull request, it would be greatly appreciated.

**Comment by mkoertgen** [comment]
Hi @JakeGinnivan. I did a quick evaluation on how to wrap GitVersion inside docker.
First i tried dotnetcore & mono-slim base images but finally arrived at adding `gitversion` (latest github release) and `git` to the latest mono image.

You can review my evaluation experiment here: https://github.com/mkoertgen/docker.gitversion/blob/master/Dockerfile

**Comment by asbjornu** [comment]
I believe this can be closed due to the merging of #1215, #1269, #1344, #1422, #1432 and #1485 which all improve our Docker story. I've also created #1572 to discuss which further, concrete, improvements we can make to the current naming scheme.
