### ISSUE TITLE
Minimal linux mono packages

### ISSUE THREAD

**Issue by bryceschober** [GitTools/GitVersion#1229]
The docs say mono-complete is required, which installs >170 MB more than mono-runtime on my system (Ubuntu 14.04). 

After some fooling around, it seems that mono-mcs is sufficient for at least a trivial execution, and that installs only 6 MB more than mono-runtime.

Could someone verify with a more complete test suite (or some less experimental approach) whether mono-mcs is truly sufficient?

**Comment by asbjornu** [comment]
@bryceschober: You're free to tweak [the `.travis.yml` configuration file](https://github.com/GitTools/GitVersion/blob/master/.travis.yml) to see how much dependency weight you can shave off. Not sure it's possible, but this shaving should perhaps be reflected in [GitVersion's Homebrew Formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/gitversion.rb) as well. If you manage to shave off a few megabytes and the Travis tests are still green, we're happy to accept a pull request. 😃

**Comment by bryceschober** [comment]
@asbjornu: I don't see a way any place to specify a minimal mono installation except in the [src/DockerBase/Dockerfile](https://github.com/GitTools/GitVersion/blob/master/src/DockerBase/Dockerfile). Is the docker image actually used in any of your automated testing?

I'm not sure how I could test a different build environment (which would require a pretty complete mono install) than the test environment...

**Comment by asbjornu** [comment]
Good point. I supposed neither Homebrew nor Travis allows for that sort of specificity. Could we test the Docker image somehow, though? If we got that set up, we could adjust it to only use the bare minimum dependencies required to execute successfully.

**Comment by bryceschober** [comment]
Sorry, I'm just a user-level newbie and have no idea if your test suite could run from the docker image, or if the nature of the test infrastructure is that it would require a full mono install just to run any test.

**Comment by JakeGinnivan** [comment]
This sounds like a good change to me! I would be happy to change it and see if anyone complains. As long as GitVersion runs the normalisation properly (when on a build server for instance) then I think it's probably fine to say it works.

**Comment by asbjornu** [comment]
@JakeGinnivan: Sure, that's a viable approach as well. Let's do it! 😄

**Comment by dazinator** [comment]
Once #1269 is done, you should also be able to run on linux under dotnet core if that is something that interests you.
