### ISSUE TITLE
Release merged to develop but not pushed produced different versions

### ISSUE THREAD

**Issue by tpluscode** [GitTools/GitVersion#1232]
We've found that when we merge a `release` branch to `develop`, gitversion produces a different version on `develop` branch.

Here's an illustration of the issue. Locally, we commited to release branch and merged it to `develop` and the version is `1.104.0-alpha.13`

![ver13](https://user-images.githubusercontent.com/588128/26917381-5d89660e-4c2e-11e7-961b-71ea8481a19d.png)

But the same graph with release branch moved back, which happened by pushing `develop` only without the commits to `release`, resulted in version `1.104.0-alpha.9`.

![ver09](https://user-images.githubusercontent.com/588128/26917514-d8b4a38e-4c2e-11e7-934c-51b0f4b7acff.png)

How and why does the `HEAD` of our release branch affect the version on `develop`? Bug or design?

**Comment by tpluscode** [comment]
Using latest 4.0 prerlease

**Comment by asbjornu** [comment]
Isn't this just a case of `HEAD` pointing to different branches? Unless I interpret your screenshots incorrectly, **bold** means where `HEAD` is pointing, which means in the first case it's on `develop` and in the second it's on `release/1.103.0`. It will therefore count differently depending on which branch you're on.

What version numbers were you expecting? Are you using Task or `.exe`? Do you have the build log of the two different scenarios?

**Comment by tpluscode** [comment]
My bad. Both calculations were made on `develop` branch, not where it's bold. We expected `1.104.0-alpha.13` either way.

In essence, the difference is only in where `release/1.103` is pointing. I'll try to create a minimal reproduction.

And we're using `.exe`.
