### ISSUE TITLE
Prerelease versions are incorrect

### ISSUE THREAD

**Issue by alefranz** [GitTools/GitVersion#1235]
Quoting an example from documentation:

https://github.com/GitTools/GitVersion/blob/master/docs/git-branching-strategies/gitflow.md#release-branches

> So on a branch named release-1.2 with a tag 1.2.0-alpha1 and 4 commits after that tag the version would be 1.2.0-alpha1.4

However the behaviour is different.

Given a repository like:
```
* 1dde0ce - (HEAD -> release-1.2) nothing 4 (3 minutes ago) <Alessio Franceschelli>
* 4da90d3 - nothing 3 (3 minutes ago) <Alessio Franceschelli>
* 932bd7e - nothing 2 (3 minutes ago) <Alessio Franceschelli>
* cb41f53 - nothing 1 (3 minutes ago) <Alessio Franceschelli>
* 06c9a69 - (tag: 1.2.0-alpha1) 1.2.0-alpha1 (3 minutes ago) <Alessio Franceschelli>
* 21faebc - (master) Initial commit (7 minutes ago) <Alessio Franceschelli>
```
Running GitVersion 4.0.0-beta0012 would return

* `1.2.0-alpha.1` for the commit tagged 1.2.0-alpha1 (06c9a69)
* `1.2.0-beta.1` for the tip of the release branch (1dde0ce)

**Comment by pi3k14** [comment]
Wouldn't that be because the tag for release is set to be beta in your example, in the documentation it is alpha.
