### ISSUE TITLE
Option for trimmed SHA in description

### ISSUE THREAD

**Issue by DanubeRS** [GitTools/GitVersion#1238]
Asked on [SO](https://stackoverflow.com/questions/44639767), but wanted to head straight to the source and see if this was available. Added an example of the Spotify macOS client for a sample in the wild.
<img width="224" alt="screen shot 2017-06-20 at 8 15 55 am" src="https://user-images.githubusercontent.com/2668630/27308204-c634320e-5590-11e7-8d37-e68a5fde677a.png">

If not, could this be considered an FR, possibly extending to customised info version formats?

**Edit**
Found [configuration](http://gitversion.readthedocs.io/en/latest/configuration/#branch-configuration) that allows string interpolation, however, I'm not sure if formatters are allowed, or if there is even a standardised one for substring formatting.

**Comment by asbjornu** [comment]
@DanubeRS: I haven't used the different formatting options that much, so I'm not entirely sure what works and what doesn't. But #544 and #886 seems related. If you have concrete ideas for improvements and implementation, please feel free to submit a pull request!

**Comment by asbjornu** [comment]
Perhaps related to #1240 too.

**Comment by DanubeRS** [comment]
Found the section on [RTD](https://gitversion.readthedocs.io/en/latest/configuration/) about custom informational version formats. Haven't tinkered much yet, and unfortunately string formatters doesn't contain a substring formatter so kind of put it on hiatus for the moment. Will definitely revisit at some point, though and participate in #1240 (y)

**Comment by asbjornu** [comment]
Excellent! Looking forward to your participation in getting all of these formatting wishes fulfilled once and for all. 😄
