### ISSUE TITLE
FileVersion inconsistency between UpdateAssemblyInfo and UpdateVersionProperties

### ISSUE THREAD

**Issue by bording** [GitTools/GitVersion#1241]
The new `UpdateVersionProperties` section in the 4.0 `GitVersionTask.targets` file is using a different value for  `FileVersion` than the `UpdateAssemblyInfo` task.

`UpdateAssemblyInfo` is using [AssemblySemFileVer](https://github.com/GitTools/GitVersion/blob/master/src/GitVersionTask/AssemblyInfoBuilder/CSharpAssemblyInfoBuilder.cs#L45).

`UpdateVersionProperties` is using [$(GitVersion_MajorMinorPatch).$(GitVersion_CommitsSinceVersionSource)](https://github.com/GitTools/GitVersion/blob/master/src/GitVersionTask/NugetAssets/build/GitVersionTask.targets#L108) in both versions of the targets file.

To maintain consistency with previous behavior, I think `UpdateVersionProperties` should be changed to match `UpdateAssemblyInfo`.

I'd be happy to submit a PR if you agree that this should be changed.

**Comment by asbjornu** [comment]
I assume this inconsistency will be easier to deal with after https://github.com/GitTools/GitVersion/issues/1242#issuecomment-311842461 is completed?

**Comment by bording** [comment]
Well, it would be easy to submit a quick PR that fixed this one thing, since it would just be a matter updating the two targets files to have the correct value.

The larger refactoring being considered in #1242 would also end up taking this into account, but maybe it would be worth fixing this up in the existing code first?

**Comment by bording** [comment]
@asbjornu I went ahead and fixed this up: #1247.
