### ISSUE TITLE
source-branches and is-source-branch-for configuration removed in v4 ?

### ISSUE THREAD

**Issue by doubret** [GitTools/GitVersion#1246]
Hi,
I tried to use source-branches and is-source-branch-for configuration in the v4 beta and the configuration parser raised an error.
Looking at the source code, i don't see these properties in GitVersion.BranchConfig.

Were these properties removed definitely ? Or is this just beacause it's a beta ?

Thanks

**Comment by nphmuller** [comment]
They have been added after the latest beta release. So they'll probably be part of the next beta release.
