### ISSUE TITLE
LibGit2Sharp Support for  .NET Framework 4.7 

### ISSUE THREAD

**Issue by rajendratripathy** [GitTools/GitVersion#1250]
Currently we are migrating a project to .Net Core(4.7 Framework) 
While Application getting deployed I am getting exception saying 

**Exception thrown: 'LibGit2Sharp.LibGit2SharpException' in LibGit2Sharp.dll**
Using LibGit2Sharp - 0.24.0.0 Version

**Comment by asbjornu** [comment]
Can you please post the full stack trace and perhaps even the full GitVersion log in a Gist?

**Comment by rajendratripathy** [comment]
As I debug internal, In "LibGit2Sharp.dll" some of the things are obsolete and deprecated, sometimes it’s trying to access the container, which is locked and can't be changed after the first call.
The behaviour is also not consistent.

**My 1st question** : Whether you are supporting .NET4.7 framework or not ? If yes please let me know the details. Currently I am using Using LibGit2Sharp - 0.24.0.0 Version.

**Comment by asbjornu** [comment]
GitVersion does not fully work with .NET Core yet, no.

**Comment by asbjornu** [comment]
As .NET Standard support was implemented in #1269 and LibGit2Sharp was upgraded to version 0.26 in #1713, I hope that the .NET 4.7 and .NET Core support in GitVersion should be quite excellent. Can you please try [the latest build of GitVersion](https://www.nuget.org/packages/GitVersionCore/5.0.0-beta4-1) and report back whether it fixes this problem or not? Please reopen this issue if the problem persists.
