### ISSUE TITLE
Need some help to configure

### ISSUE THREAD

**Issue by jeandemonceau** [GitTools/GitVersion#1251]
Hi, 
I'm trying GitVersion v3 and I cannot figure out how to configure it properly.

I have 
master branch
develop branch
feature/xxx branches 

I would like to start with 0.1.0
All feature branches are merged to develop via pull requests.
When I create a feature branch without any breaking change, and it is merged on develop, I want my Minor to be increased. 0.2.0
Then I create another feature branch that is also merged to develop I want the Minor to be increased again so it is 0.3.0
When I create a feature branch with a **breaking change**,  (so, for this specific change I commit on the feature branch the comment +semver: breaking.) Then I continue commiting regular comments.
When this feature branch is merged on develop, I want my Major to be increased and Minor, Patch to be reset. 1.0.0
If two feature branches in parallel have both one or several commit(s) with +semver: breaking, I don't want my Major to be increased more than ones when they both will be merged on develop (don't know if that one is possible)
If I commit directly on develop (thing that should not happen :)) I want the Minor or Major to be increased only if I specify it manually in the commit.
(By the way, I tried commiting on develop +semver: minor and the Minor did increase properly. I did it once again and it doesn't increase anymore... What am I missing ?)

and so on...
When I release something, Nothing is increased. Releasing is like fixing a version.

Could you help me to configure it that way please ?
Thanks a lot !
J

**Comment by asbjornu** [comment]
@jeandemonceau: Sorry for the late reply. Did you figure it out?

**Comment by jeandemonceau** [comment]
Hi.
No problem.
Yes I figured out how to configure the yml properly. Thx !
