### ISSUE TITLE
Wrong variable names in documentation

### ISSUE THREAD

**Issue by aronsky** [GitTools/GitVersion#1252]
The description in the [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=gittools.gitversion) suggests using variables formatted as `$(GitVersion_NuGetVersion)` and `$(GitVersion_SemVer)`. However, when using VSTS, one should format the variables as `$(GitVersion.NuGetVersion)` and `$(GitVersion.SemVer)` (period instead of an underscore). I'm not sure where the text is hosted, so I can't make a PR to fix that.

**Comment by asbjornu** [comment]
Perhaps @pascalberger has an idea where this text is entered? Manually by someone with admin access to the Marketplace, I presume?

**Comment by pascalberger** [comment]
No this is the [overview.md](https://github.com/GitTools/GitVersion/blob/master/src/GitVersionTfsTask/overview.md) file. Which also has issues with images not being rendered correctly I just saw.

**Comment by aronsky** [comment]
Hm, that file definitely looks similar to the description in the Marketplace, but the variables are correct in the file, while appearing incorrect in the Marketplace. If the Marketplace is pulling it automatically from the overview file, any chance it undergoes some pre-processing (to avoid XSS and such), which generates a wrong output?

**Comment by pascalberger** [comment]
Marketplace is still version 3.6.5. This was already fixed in https://github.com/GitTools/GitVersion/commit/d9248c35284fd0b3afc443262aca5ea2369f0bce but there was no new version released since then to the marketplace
