### ISSUE TITLE
Branching off release branch resets commit counter

### ISSUE THREAD

**Issue by tpluscode** [GitTools/GitVersion#1253]
Here's another issue I've been having although it may be that I'm misusing branching flow? I think there were similar issues in the past though.

GitVersion == 4.0.0-beta.12

The scenario is that I have a release branch `release/0.5` using `mode: ContinuousDeployment`. Adding commits to it increments the counter: `0.5.0-beta.1`, `0.5.0-beta.2`, `0.5.0-beta.3` and so on.

Next I want to create a branch to fix something and submit a pull request. As soon as I do, the version on `HEAD` of `release/0.5` resets to `0.5.0-beta.0` and subsequent commits start from scratch.

See this illustration:

![image](https://user-images.githubusercontent.com/588128/27912556-ab5ae4e4-625d-11e7-99a3-adcaa2fa88d1.png)

* Initially the commit `gitver config` produced version `0.5.0-beta.4`
* Merely creating branch `some-fix` resets the version on that commit
* The merge commit is now back to `0.5.0-beta.1`

Here's the repo:
[release-branching.zip](https://github.com/GitTools/GitVersion/files/1127917/release-branching.zip)

**Comment by tpluscode** [comment]
This is an issue with `mode: ContinuousDeployment` ofc.

With `mode: ContinuousDelivery` I would tag the release branch when necessary. But, is tagging release branch a sensible thing to do?

**Comment by asbjornu** [comment]
@tpluscode: With `ContinuousDelivery` it is expected that every release will be tagged, no matter which branch it came from, afaik. If you don't want to tag every release, you'll need to figure out how `ContinuousDeployment` can work for you. :)

**Comment by tpluscode** [comment]
> no matter which branch it came from

OK

> figure out how `ContinuousDeployment` can work for you

Well, it doesn't but I do think it's a bug :)
