### ISSUE TITLE
How To handle this scenario

### ISSUE THREAD

**Issue by mcnallys** [GitTools/GitVersion#1254]
We are using gitflow

The only difference from the default configuration I am having trouble with is in release branches.

At some point we want to consider a release branch to be moved from "beta" to "rc"

I've tried putting in a tag, and playing with the config file - just can't seem to get it right.   It either stays beta or everything goes rc.

**Comment by asbjornu** [comment]
If something in the release branch changes so significantly that it should be named differently, don't you think it warrants the creation of a new branch? Branches are cheap! 😃

**Comment by mcnallys** [comment]
Nothing is changing significantly, an RC for us means we shipped it off for external testing.

**Comment by asbjornu** [comment]
Hm. Sounds like something a tag would be fitting for, but it won't change the name of the prerelease label of the version number, afaik.

**Comment by mcnallys** [comment]
Yeah right now if we commit any fixes to the release branch I tag a commit as the appropriate rc, seems like defeating the purpose though.  Just need a way to tag and have the prerelease label changed from 'beta' to 'rc'.
