### ISSUE TITLE
TFS build number overwritten fully instead of only replacing gitversion variables

### ISSUE THREAD

**Issue by dpurge** [GitTools/GitVersion#1257]
In the TFS build definition, I am trying to use this build number format: `$(GITVERSION.SemVer).Build-$(Build.BuildId)`

As the build starts, `$(Build.BuildId)` is replaced correctly. But later GitVersion is replacing the whole thing with the generated semantic version - ie. I am losing the `.Build-12345` suffix.

I think this is not a correct behaviour - gitversion should replace only the `$(GITVERSION.SemVer)` part, leaving the rest of the build number untouched. TFS configuration as TFS users expect it to work should be respected.

Using bare semver for build number is not satisfactory, because build artifacts depend not only on the source code, but also on the version of the build definition and its parameters and possibly other things too (in real life builds may not be quite repeatable, which of course is not proper ALM, but it happens). BuildId is unique and having it in the build number allows to differentiate the output of different builds from the same commit.

**Comment by asbjornu** [comment]
Does TFS use the [`VsoAgent` build provider](https://github.com/GitTools/GitVersion/blob/master/src/GitVersionCore/BuildServers/VsoAgent.cs)? If so, please have a peek and see whether something can be adjusted there to better accommodate your use-case. If you're able to fix it, a pull request would be welcome! 😄

**Comment by dpurge** [comment]
VsoAgent that you linked to seems to be exactly the place,  thank you for pointing it out.
I am not a programmer, but this looks easy eanough :) If I manage to fix it, I'll send you a pull request :)

**Comment by pascalberger** [comment]
With https://github.com/GitTools/GitVersion/pull/990 documentation for the VSTS/TFS task was changed that variables are in the form `GITVERSION.*` instead of `GITVERSION_*`. This seems to not be reflected in [this RegEx](https://github.com/GitTools/GitVersion/blob/master/src/GitVersionCore/BuildServers/VsoAgent.cs#L39).
