### ISSUE TITLE
GitVersionTask.targets for buildMultitarget does not output AssemblyInfo

### ISSUE THREAD

**Issue by conniey** [GitTools/GitVersion#1265]
I noticed that my assemblies were being stamped with version information 0.0.0.0... and it was because `UpdateAssemblyInfo` target in [build\GitVersionTask.targets](https://github.com/GitTools/GitVersion/blob/master/src/GitVersionTask/NugetAssets/build/GitVersionTask.targets#L52-L63) doesn't exist in its [buildMultiTargeting](https://github.com/GitTools/GitVersion/blob/master/src/GitVersionTask/NugetAssets/buildMultiTargeting/GitVersionTask.targets) counterpart.

Is this a bug or was there a reason for removing it? (I manually added that target back manually and it appears to work for me.)

Thanks!
Connie

**Comment by asbjornu** [comment]
I have no idea. I think we would have to ask @bording, @onovotny or @JakeGinnivan about that one. It sounds like an oversight (and thus; a bug), though.

**Comment by onovotny** [comment]
With the SDK style projects, the assembly info / version is part of the build itself. The `buildMultiTargeting` version is the "outer loop" that doesn't affect the `AssemblyInfo` of each assembly. For each of the "inner" builds", the `build` one should be used.

Do you have a repro?

**Comment by conniey** [comment]
*facepalm* Sorry. I looked into it and it was because I had added `<UpdateAssemblyInfo>false</UpdateAssemblyInfo>` because I had some AssemblyInfo items already set (ie. Company, Title.) I individually added tags not to generate them.
