### ISSUE TITLE
Normalization takes a very long time

### ISSUE THREAD

**Issue by JoshSchreuder** [GitTools/GitVersion#1266]
Not sure if this belongs here or in the [GitTools.Core](https://github.com/GitTools/GitTools.Core/blob/master/src/GitTools.Core/GitTools.Core.Shared/Git/Helpers/GitRepositoryHelper.cs#L21) repo so apologies in advance.

I'm investigating our long running builds in Jenkins - found that the GitVersion step takes 6+ minutes to execute. When I run it locally on the build server it is nearly instantaneous, as there is no build server detection.

Anyway, I loaded up GV 4 to test and log out, and found it took 6.39 minutes in the normalization step:

```
2017-07-26 11:37:23		INFO [07/26/17 11:37:23:42] End: Normalizing git directory for branch 'origin/js.buildspeed' (Took: 383,852.08ms)
```

Perhaps unconventionally we have a LOT of branches (most of which need to be deleted as they have been merged already 😞 ), and this step runs through all of them doing this over and over

```
2017-07-26 11:37:23		  INFO [07/26/17 11:37:23:40] Skipping update of 'refs/remotes/origin/a-branch' as it already matches the remote ref.
```

Question - how do I make this quicker, and is it a bug or a failing on my end for having so many branches? 

I assume that by deleting the branches that the time taken will increase, but is the normalization step required given I can run the command locally on the build server and get the same output nearly instantly?

Thanks in advance!

**Comment by JoshSchreuder** [comment]
I've delete my 450+ merged branches and it's relatively quick again 😄 

Still, it's going to take longer and longer as the branch list grows - anything I can do besides keeping the branch list small?

**Comment by asbjornu** [comment]
I assume @JakeGinnivan's work in #1243 will make **everything** GitVersion does faster, so there's hope. But 450 branches is a high number and I would recommend you to just delete branches immediately after they are merged (excluding `mater` and `develop`, of course).

**Comment by JoshSchreuder** [comment]
This is still an issue by the way, even on 5.0 beta.

With repo normalisation = ~7 minutes
Without repo normalisation (eg. setting env variable `JENKINS_URL=` per #1701) = ~40 seconds

Of course, without it my version is not detected correctly, so this is not a real solution :)

I don't know if there's any plans to implement the in memory stuff mentioned, so I guess I might need to look for alternative solutions.

**Comment by asbjornu** [comment]
@JoshSchreuder, can you please try with the latest beta? #1838 contains some performance improvements, but I'm unsure whether they affect the issue you're seeing or not.
