### ISSUE TITLE
List of matching versions once incremented doesn't include maxVersion (3.6.5)

### ISSUE THREAD

**Issue by novabe** [GitTools/GitVersion#1267]
In BaseVersionCalculator.cs, after finding a maxVersion the code finds all the matching versions once incremented, but the where clause includes "b != maxVersion" which means we aren't including maxVersion in this list.

Afterwards, the code finds the oldest source from that list, but theoretically maxVersion could be the oldest one, and if it is not included we don't end up using it.

GitVersion version 3.6.5.

**Comment by asbjornu** [comment]
@novabe: Does GitVersion 4 exhibit the same behaviour? If so, can you please submit a pull request with a test proving the problem? Even better if the PR fixes the problem too, of course. 😄

**Comment by novabe** [comment]
The problem I saw here may have actually been what is described in #1275 and for that one I have created a repo that reproduces the problem. (I don't know yet if this is a separate bug)
