### ISSUE TITLE
VSTS GitVersion variables are not resolved when tagging sources

### ISSUE THREAD

**Issue by BiribiriJaNai** [GitTools/GitVersion#1270]
Using the GitVersion task from [VSTS Marketplace](https://marketplace.visualstudio.com/items?itemName=gittools.gitversion), it's working fine updating assembly info and nuget version, but when I want to use any GitVersion variable to tag or label my sources, the variable is not expanded.

![gitversion-01](https://user-images.githubusercontent.com/29836717/28753150-e16df636-752f-11e7-823f-e7403a33dc32.PNG)

and so here is the result in the log file 

![gitversion-02](https://user-images.githubusercontent.com/29836717/28753185-4b839332-7530-11e7-8df0-34f5edf3cba4.PNG)

If I use a user-defined variable in the build process, i.e. **$(tagVersion)** and assigning a value **(1.2.3.4)** then the tag is correctly labeled with the variable's value.

**Comment by dpurge** [comment]
https://connect.microsoft.com/VisualStudio/feedback/details/2743528/invalid-source-label-format-when-labeling-sources-on-successful-build

I think this is not GitVersion issue, but TFS not making variables created by task running on the build agent to be used on the server when tag in the source control is created. Such variables are available for other tasks in the same build (but not for the very task that is creating the variable - try it ;-) )

User-defined variable is created on the server and made available to the build on the agent.

**Comment by BiribiriJaNai** [comment]
@dpurge thanks for the workaround!
Indeed, GitVersion already updates the $(Build.BuildNumber) variable, and using it, as is, for tagging works like a charm.
Now I just have to set this variable to the Nuget version.

**Comment by bastianjohn** [comment]
I have a similar problem. I want to use the $(GitVersion_FullSemVer) for the Build number format but also want to pass the $(GitVersion_AssemblySemVer) to another VSTS Task (see the screenshot).
The BuildNumber will be correctly replaced, but all variables with $(GitVersion are not working and will be displayed as "$(GitVersion_AssemblySemVer)" instead of i.e. "1.0.0.0".

![image](https://user-images.githubusercontent.com/12729982/29119547-d6754ad4-7d06-11e7-81f9-88fb6bf1c227.png)

Do you have any idea?
Thanks!

ps: Great VSTS Task! Thanks!

**Comment by pascalberger** [comment]
@bastianjohn VSTS variables created by GitVersion are in the form `GitVersion.*` not `GitVersion_*`. See [documentation](http://gitversion.readthedocs.io/en/latest/build-server-support/build-server/tfs-build-vnext/#running-inside-tfs).

**Comment by pascalberger** [comment]
As @dpurge mentioned this is not an issue with GitVersion but with how variables are scoped on VSTS. Setting of build number is handled specially by GitVersion by using the appropriate service message.

Closing this since I don't see anything which we can do here from GitVersion side.
