### ISSUE TITLE
Allow for brach names to start with reserved names

### ISSUE THREAD

**Issue by tgbarnett** [GitTools/GitVersion#1271]
The current implementation of GitVer has a specific behavior for branches called _master_
Unfortunately the way that this is implemented it is for branches that start with _master_ which means that _masterfix_ has the same rules applied (though _fixmaster_ would be treated differently.

I think that _masterfix_ and _fixmaster_ should be treated the same (i.e. not the same as _master_)

**Comment by asbjornu** [comment]
Closing as #1273 is merged.
