### ISSUE TITLE
GitVersion produces version with wrong commit count (release branch with feature branches on it)

### ISSUE THREAD

**Issue by novabe** [GitTools/GitVersion#1275]
Versions 3.5.3, 3.6.5, 4.0.0-beta0009, 4.0.0-beta0012

**EDIT**: see #1277 for some unit tests showing this.

Here is a repo that demonstrates the problem: https://github.com/novabe/GitVersionTesting.FeatureOnRelease/tree/release/WD/4.5.0

I expect branch release/WD.4.5.0 to produce a FullSemVer of 4.5.0-beta.9 but instead it produces 4.5.0-beta.5

**Steps to reproduce:**
- Checkout branch release/WD/4.5.0
- Run gitversion.bat located in subdirectory /gitversion
- Check the properties*.json files (and also the log files) located in subdirectory /gitversion/output

**Comment by novabe** [comment]
The .bat file is windows only, to conduct the same tests on another OS you can use the same repo but manually use the specific version of GitVersion you are testing with, and use the gitversion.yml files placed in the subdirectories inside /gitversion of the provided repo.

**Comment by novabe** [comment]
I suspect this has to do with the hardcoded string "into" in line 51 of `\src\gitversioncore\versioncalculation\baseversioncalculators\mergemessagebaseversionstrategy.cs` in version 3.6.5:

`var lastIndexOf = commitMessage.LastIndexOf("into", StringComparison.OrdinalIgnoreCase);`

Note that in my Atlassian Bitbucket the default merge message doesn't include "into", and it goes something like this:

> Merge pull request #\<PR-number> in \<repo-name> from \<source-branch> to \<dest-branch>

**Comment by mexmirror** [comment]
I do have a similar issue. The CommitsSinceVersionSource variable does not correctly sum the commits on the release branch. I am using 4.0.0-beta.12. Is there any known workaround?
