### ISSUE TITLE
How to create vsix package from updated code?

### ISSUE THREAD

**Issue by RichK67** [GitTools/GitVersion#1283]
Hi. I've created a small update that I'd like to deploy on our TFS server as an extension. I have proved that it builds OK, and all Unit Tests are fine. Result is what I want.
How do I now turn that GitVersion.exe with associated .dlls into the .vsix package? No instructions anywhere I can find?
Can anyone help?
Thanks
RichK

**Comment by asbjornu** [comment]
What is the update you've created? If it's something that can benefit all GitVersion users, we would love to have it as a [pull request](https://help.github.com/articles/creating-a-pull-request/) so we can integrate it and then publish a new version with your change in it.

**Comment by RichK67** [comment]
We have a non standard (nearly gitflow) workflow, and there was an issue with commit count numbering. Normal gitflow is feature branches complete and go into develop. Then release is branched off that. No merges into release.

Due to real world issues, we had to create release off develop with what had been done to that point so that QA could get going. Then as the features were completed, they were merged to develop and release directly. (Develop by this point contained some features we did not want in the release, so we couldnt merely use develop). This merge reset the numbering back to N.N.**0**-rc.**1+0** every time.

What I have added is the ability (via a ReleaseBaseVersionShaStrategy) to nominate a specific commit sha as the release version base. So instead of resetting on every merge from a feature branch, it counts back from the version base sha specified. So our release build now has a stable start point. (1st commit after branch creation).

I will be sorting this out as a proper pull request (if I can work out how) after my holiday!

Its non-standard way of doing things, and probably we should be tagging the release branch to end the rc cycle prior to each merge (we use release candidate acronym rc as tag instead of beta). Alternatively if the system had bumped the rc from rc.1 to rc.2 etc on each merge, then things would be fine. Each merge always reset all the way back to N.N.0-rc.**1**+0.

Any info on how I can create the .vsix (or replace the current executable used in each TFS build), as that would really help :)

**Comment by RichK67** [comment]
Hi
Does anyone have any info on how to get the packaging to work? Ive installed npm, tfx, but still no joy with getting the Create-vsix.ps1 to work. MS page on creating vsix says I should be in the "home" folder. Which is that in this repo? Is it GitVersionTfsTask, GitVersionTask, bin\Release under GitVersionTask... none seem to work.

**Comment by RichK67** [comment]
OK, I found the solution eventually. The AfterBuild tasks in the project GitVersion.csproj only execute if there is a SemVer and it is on a build server. So set up TFS to build the project and out came a .vsix package.

Granted, that is now having issues, because it generates a GitVersion.js with "use strict;", which requires a change to the search path order in the VS2015 Options\Tools\Projects and Solutions\External Web Tools. ($PATH must be topmost).

Having got past that one, I now have a new error from the generated GitVersion.js file. That will be a new ticket.

This can be closed.
