### ISSUE TITLE
Package Version not updating under VSO Build Server and .net standard

### ISSUE THREAD

**Issue by DaleKBurrell** [GitTools/GitVersion#1290]
Sorry I don't know if this is a bug or not, but wasn't sure where best to ask.

I'm building a .net standard component using VSO and GitVersion. And because its .net standard I'm having to use "msbuild /t:pack" instead of the nuget pack step.

This has resulted in the package version number always being 1.0.0 which I assume means that "PackageVersion" isn't being set. The documentation says "the following MSBuild properties are set when UpdateVersionProperties is true" but there doesn't appear to be an option for that.

**Comment by dazinator** [comment]
You could try passing in the version argument into msbuild via /p:PackageVersion="x.y.z" but you would have to run gitversion first to calculate that value so that you can pass it in.

Perhaps UpdateVersionProperties is a property you need to add to your csproj file - have you tried that?

**Comment by torsten-github** [comment]
I have the same problem. My dotnet core .csproj variables do not get updated. Using 4.0.0-beta.12
`<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
    <DockerComposeProjectPath>..\docker-compose.dcproj</DockerComposeProjectPath>
    <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
    <UpdateVersionProperties>true</UpdateVersionProperties>
    <Version>0.1</Version>
    <AssemblyVersion>0.1.2.0</AssemblyVersion>
    <FileVersion>0.1.1.2</FileVersion>
  </PropertyGroup>` 

Any ideas what I'm missing?
thanks in advance.

**Comment by dazinator** [comment]
You might want to take a look at #1269
