### ISSUE TITLE
GitVersion is exteremely slow within TFS build agent context

### ISSUE THREAD

**Issue by lucom** [GitTools/GitVersion#1292]
When GitVersion is run as part of a build definition in TFS (as GitVersion TFS Task or inside a PowerShell script) it takes around 8 minutes to determine the version and to finish. 

The command (typed in and also generated by GitVersion Task for TFS):
`D:\agent\tasks\GitVersion\3.6.5\GitVersion.exe D:\agent\_work\13\s /output buildserver /nofetch /ensureassemblyinfo /updateassemblyinfo VersionInfo.cs`

Running exactly the same command with the same parameters as a normal user on the same repository only takes around one second.

This was tested with the following:
- GitVersion 3.6.5 and 3.6.4 (from GitVersion Task for TFS or installed via Chocolately)
- GitVersion as TFS Task or as command within a PowerShell build task
- On a freshly fetched repo and on an already checked out repo

ProcessMonitor shows that GitVersion behaves differently when run within a build agent. It checks way more files and directories and seems to iterate through the checked out files instead of only changing `VersionInfo.cs` which lies in the root of the repo.

**Comment by asbjornu** [comment]
Sounds like a duplicate of #1065?
