### ISSUE TITLE
[Question] Is this Version flow possible?

### ISSUE THREAD

**Issue by JonCubed** [GitTools/GitVersion#1295]
I've been playing around with GitVersion trying to get the following version calculation flow to work

```
master
  * (HEAD, calulated version: 1.1.0)
  |
  * (tag: release/v1.0.0, calculated version: 1.0.0)
  |
  * (calulated version: 0.4.1)
  |\
  | \
  |  * (branch: feature/bar, calculated version: 0.4.1-bar)
  |  |
  |  * (branch: feature/bar, +semver: patch, calculated version: 0.4.1-bar)
  | /
  |/
  * (calulated version: 0.4.0)
  |\
  | \
  |  * (branch: feature/foo, calculated version: 0.4.0-foo)
  |  |
  |  * (branch: feature/foo, calculated version: 0.4.0-foo)
  | /
  |/
  * (calculated version: 0.3.0)
  |
  * (calculated version: 0.2.0)
  |
  * (initial commit, calculated version: 0.1.0)
```

but haven't had much luck. Is it possible with v3 or v4?

It seems like I want to use `Mainline` but that seems to only increment `Patch` and I want it to increment `Minor`

**Comment by asbjornu** [comment]
@JonCubed: Can't you just set the [`increment`](http://gitversion.readthedocs.io/en/latest/configuration/#increment) configuration property to `Minor`?

**Comment by JonCubed** [comment]
@asbjornu I've tried that but it only increments `Patch` regardless what I have as `increment`

**Comment by JonCubed** [comment]
I've dug into the code tonight and this seems to be a bug with `Mainline` version calculation defaulting to `Patch` if no message bump is found.
