### ISSUE TITLE
Question: New v4 Beta?

### ISSUE THREAD

**Issue by pcoombe** [GitTools/GitVersion#1296]
I've been noticing a steady stream of commits flowing in since beta 12.
any idea when a new beta release will be published?

**Comment by MagneIngvaldsen** [comment]
👍  Waiting for pr #1297. Want to get rid of the current hack I did with the MinorVersionBumpMessage regex :)

**Comment by LarsAndreasEk** [comment]
Would be nice with new beta!

**Comment by JonCubed** [comment]
@MagneIngvaldsen I have a build of #1297 available that I have been using if you want to test it in the meantime
https://github.com/JonCubed/GitVersion/releases/tag/v4.0.0-beta12%2B0001

**Comment by leovic0101** [comment]
I am also very interested with version 4, when do you intend to release?

Thanks.

**Comment by JakeGinnivan** [comment]
Working on beta 14 now, then will let that settle for a week or two then release v4 for real. Just had lots of changes since beta 12 and want to make sure it's good
