### ISSUE TITLE
[Question] Is this workflow possible?

### ISSUE THREAD

**Issue by Toby-VandenBerge** [GitTools/GitVersion#1298]
We use a modified GitFlow where there is no 'develop' branch. This approach allows us to have have deployable release branches that we can use in our testing environments and only deploy to production from master.

Our software is installed through MSIs and given that the underlying Windows ProductVersion is only Major.Minor.Patch, we need to increment at least the Patch in order for the update to be applied.
We were drawn to the Mainline verioning mode as it seems to offering the versioning scheme that fits our situation.
Through testing we are finding that branches off of a release branch (namely bugfix or feature) are not getting the correct parent version (the release branch) but instead falling back to the master. 

In the attached image, I expected the version for feature/my-first-feature to have been 0.2.1-my-first-feature.0 but instead it was 0.1.1-my-first-feature.0. 

We do not deploy from feature or bugfix branches but it helps to track where those changes are targeting through our builds and unit tests.

Is there a configuration that will suite our needs?

![CompanyGitFlow](https://user-images.githubusercontent.com/32305589/30881475-9b01ff48-a2cb-11e7-8594-8754053ff899.JPG)

**Comment by asbjornu** [comment]
Since you're using release branches, I think your flow is closer to Git Flow than Mainline. How does GitVersion handle your flow out of the box (without `mode: Mainline`)?

**Comment by Toby-VandenBerge** [comment]
Using the default configuration from the nuget package GitVersion.CommandLine v3.6.5 and running through the above example, I get the following:
* On the fresh branch release/0.2, I get 0.2.0-beta.1+0
* One the fresh branch feature/my-first-feature (which was branched from release/0.2), I get 0.1.0-my-first-feature.1+0
* The next commit on feature/my-first-feature, I get 0.1.0-my-first-feature.1+1.
* Merging feature/my-first-feature into release/0.2, I get 0.2.0-beta.1+1.

I expected the feature branch to be 0.2.* and after merging into the release branch, I need the Patch to increment.

**Comment by asbjornu** [comment]
Right. I'm not sure exactly how to configure this, but will `tracks-release-branches: true` on `feature/*` help (in any `mode`)?

**Comment by Toby-VandenBerge** [comment]
In order to change the `trackes-release-branches` value, I had to upgrade to the beta v4 (non-existent in v3.6.5). So now I am the using GitVersion.CommandLine.4.0.0-beta0012 NuGet package. Using all default values, but setting `tracks-release-branches` to true, I have the same result. By "in any `mode`" do you mean for the feature branch config's `mode` or the global `mode`?

**Comment by asbjornu** [comment]
I see. With `mode` I mean the `mode` property in `GitVersion.yml`, regardless of level. You said you tried `Mainline`, but perhaps you can try `ContinuousDelivery` as well.

**Comment by Toby-VandenBerge** [comment]
I was able to accomplish a versioning scheme that works for us. We ended up using global `mode: Mainline` and under the feature branch config set `tracks-release-branches: true`. This allowed us to have the patch incremented on the release branch as well as the feature/bugfix branches branched off of the release branch use the correct base version (from the release branch). 

I think my initial issue was due to the master and release branch being on the same commit so the feature couldn't determine which was the correct parent. If I did an "initial" commit on the release so it is above master and then branched the feature branch from the new commit, the feature uses the release as the base version (which is what we were looking for).

One last issue I found was when I merged my release branch into master, the patch was reset to 0, even though the release branch was at 0.2.2-beta, for example. Is that intended?

**Comment by asbjornu** [comment]
Yes, I think that makes sense. Please read the [documentation on Mainline](http://gitversion.readthedocs.io/en/latest/reference/mainline-development/) for details.

**Comment by Toby-VandenBerge** [comment]
But in the example for Mainline development, the first feature branch (feature/foo) has a version of 1.0.1-foo.1+1 and when it gets merged in, master is now at 1.0.1+2. I understand why the subsequent patches are reset to 0 because of the `+semver:` comments. But why, when merging a release branch into master with a >0 patch, does it get reset?

**Comment by asbjornu** [comment]
Oh, sorry, I somehow thought about build metadata (commits since last release) and not patch. So when you merge `0.2.2-beta` into `master`, the version number on `master` ends up as `0.2.0`?

**Comment by Toby-VandenBerge** [comment]
Sorry for the confusion. Yes, that is correct

**Comment by asbjornu** [comment]
Ah, that's not correct. The version number should have stayed at `0.2.2` or incremented. It should never decrement. That is indeed weird and something we should attempt to fix. Are you up for submitting a failing `RepositoryFixture` test for this and possibly also fixing the problem?

**Comment by Toby-VandenBerge** [comment]
Sure, I can try to get to it this weekend.

**Comment by Toby-VandenBerge** [comment]
Stepping through the unit test in #1304, during the final AssertFullSemver, I noticed that I am only getting 2 possible base versions: 
FallbackBaseVersionStrategy - `{ IncrementedVersion = {0.1.0}, Version = {Fallback base version: 0.1.0 with commit count source 141869e24c209a8ae789b22edbaac7b535257657 (Incremented: None)} }`

MergeMessageBaseVersionStrategy - `{ IncrementedVersion = {0.2.0}, Version = {Merge message 'Merge branch 'release/0.2'': 0.2.0 with commit count source e529fa58604b6203c075e265dee52992f64ac63e (Incremented: None)} }`.

It doesn't appear to be traversing the release branch for any increments (given default configuration with `mode: Mainline` only) thus only pulling the 0.2 out of the merge message. @asbjornu thoughts?

**Comment by asbjornu** [comment]
Does different values of `mode` have any effect on the logic? If not, I would attempt to apply the `VersionInBranchNameBaseVersionStrategy` and see what happens. If that or other tweaks fixes your scenario and doesn't break anything, I'm happy to merge it.

**Comment by Toby-VandenBerge** [comment]
I am unable to make any of the other modes work. I did however found a code change result in release (0.2.2-beta.4) -> master (0.2.3) when merging release into master. 
The code change is in the FindMainelineModeVersion method of MainlineVersionCalculator, specifically changing `FirstParentOnly = false` to `FirstParentOnly = true` in the `commitLog` `CommitFilter` instantiation. This allows the feature/my-feature merge into release/0.2 to be accounted for when determining the new master version. 
Unfortunately, this change breaks 5 other MainlineDevelopmentMode unit tests. Namely, `VerifyIssue1154_CanForwardMergeMasterToFeatureBranch`
`VerifyMergingMasterIntoAFeatureBranchWorksWithMultipleBranches`
`VerifyMergingMasterToFeatureDoesNotCauseBranchCommitsToIncrementVersion`
`VerifyMergingMasterToFeatureDoesNotStopMasterCommitsIncrementingVersion`
`VerifySupportForwardMerge`
In every case, the Patch was higher than expected. 

I still need to try more use cases, but is this something we could make configurable? Is this even a change that actually solves the issue or is it a coincidence? Also, would you like me to commit the change to #1304 so you can see what the change was?

**Comment by asbjornu** [comment]
Yes, please commit the change so I can have a look. I have no idea yet whether this is the correct way to fix it or not, but the 5 failing tests indicate that it's not. 😉

**Comment by Toby-VandenBerge** [comment]
I committed the change. Haha I agree, the failing tests aren't ideal. I haven't had much time to test some other use cases to see what the change is actually doing. I hope to get back to that in the next day or 2.

**Comment by asbjornu** [comment]
Ok, cool.
