### ISSUE TITLE
Add configuration parameter to format CommitDate

### ISSUE THREAD

**Issue by ccHanibal** [GitTools/GitVersion#1305]
We use the last commit date of a repository to build artifact names on Jenkins.
Currently we extract it with `git log -1 --format=COMMIT_DATE=%%cd --date=format:%%Y%%m%%d > gitdate.prop` and inject it later on.
We now plan to use gitversion for calculating version numbers. In this step it would be perfect if we could replace our current step to get the date with gitversion as well, but we need it formatted without dashes.

Any chance to add a configuration parameter commit-date-format so that one can customize the output of gitversion?

**Comment by asbjornu** [comment]
Can't you use one of [the `variables` GitVersion output](http://gitversion.readthedocs.io/en/latest/more-info/variables/) to format this yourself?

**Comment by ccHanibal** [comment]
Of course I could do that but it would be easier to maintain for us if GetVersion does it directly.
Would it be ok if I implement it myself?
