### ISSUE TITLE
It looks like the branch being examined is a detached Head 

### ISSUE THREAD

**Issue by benfoster** [GitTools/GitVersion#1314]
Hey guys,

Trying to get https://github.com/benfoster/Flo building on Travis and push packages to Nuget when tagged. Unfortunately I'm getting the following error:

> WARN [10/21/17 17:08:07:38] An error occurred:
It looks like the branch being examined is a detached Head pointing to commit '90769ab'. Without a proper branch name GitVersion cannot determine the build version.

Any ideas?

**Comment by asbjornu** [comment]
Here's the source of the message:

https://github.com/GitTools/GitVersion/blob/master/src/GitVersionCore/GitVersionFinder.cs#L43

And here's the `IsDetachedHead` extension method:

https://github.com/GitTools/GitVersion/blob/master/src/GitVersionCore/LibGitExtensions.cs#L65

So, for some reason, the checked out branch has a canonical name of `(no branch)`. Ideas why that might be?

**Comment by gep13** [comment]
Testing...

https://github.com/GitTools/GitVersion/blob/master/src/GitVersionCore/GitVersionFinder.cs#L43-L47

**Comment by gep13** [comment]
https://github.com/GitTools/GitVersion/blob/6d90d2665c776f06b0158799f55580bc0c6a43ae/src/GitVersionCore/GitVersionFinder.cs#L43-L47

**Comment by gep13** [comment]
@asbjornu just used that link that I sent you to create the above 😄

**Comment by asbjornu** [comment]
@gep13: Aha, I need to both link to the blob as well as have from and to line numbers. Thanks!
