### ISSUE TITLE
Add support for VS2017 projects

### ISSUE THREAD

**Issue by baurzhan** [GitTools/GitVersion#1315]
In new format version information moved from AssemblyInfo.cs to .csproj file like this
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net461</TargetFramework>
    <Version>1.2.3.4</Version>
    <Authors>Author 1</Authors>
    <Company>Company XYZ</Company>
    <Product>Product 2</Product>
    <PackageId>MyApp</PackageId>
    <AssemblyVersion>2.0.0.0</AssemblyVersion>
    <FileVersion>3.0.0.0</FileVersion>
    <NeutralLanguage>en</NeutralLanguage>
    <Description>Description here</Description>
    <Copyright>Copyright</Copyright>
    <PackageLicenseUrl>License URL</PackageLicenseUrl>
    <PackageProjectUrl>Project URL</PackageProjectUrl>
    <PackageIconUrl>Icon URL</PackageIconUrl>
    <RepositoryUrl>Repo URL</RepositoryUrl>
    <RepositoryType>Repo type</RepositoryType>
    <PackageTags>Tags</PackageTags>
    <PackageReleaseNotes>Release</PackageReleaseNotes>
  </PropertyGroup>
```

**Comment by asbjornu** [comment]
I believe this is something that is being worked on in #1269.

**Comment by dazinator** [comment]
@asbjornu is correct!

**Comment by Liryna** [comment]
Hi @dazinator ,

Thank you for your work 👍 
Does your PR also add the support of command line gitversion ? (update csproj assembly info)
If not, I can probably take a look at it.

**Comment by dazinator** [comment]
@Liryna - not exactly sure what you mean - but please feel free to take a look at the PR - read the top description to get an overview of what there is that's new, and where to get it. If you have any questions let me know. The easiest way to keep your assembly versions in line with the new `sdk` proj format would be to use `GitVersionTask` imho. `gitversion.exe` does have functionality for updating assemblyinfo files yes - but not other kinds of files as far as I know (like csproj files). 
If running on full net framework (or mono I believe as well) the gitversion exe also has the ability to run msbuild and inject some msbuild properties in to the build for the version number - so in theory you could probably also call gitversion.exe and get it to build your csproj, passing in the version params as msbuild properties - which you could use in your csproj to set `<AssemblyVersion>` etc - I haven't tested this myself however!

**Comment by Liryna** [comment]
This will be needed more and more.

Le sam. 29 juin 2019 à 10:50, stale[bot] <notifications@github.com> a
écrit :

**Comment by asbjornu** [comment]
@Liryna, please provide specific information on how you feel #1269 did not do what you ask for.

**Comment by Liryna** [comment]
Oh I thought this wasn't done since the ticket was still opened. Will need
to give a try thanks.

Le dim. 30 juin 2019 à 21:26, Asbjørn Ulsberg <notifications@github.com> a
écrit :
