### ISSUE TITLE
Failing to ignore commit messages in VSTS

### ISSUE THREAD

**Issue by DaleKBurrell** [GitTools/GitVersion#1317]
I am using GitVersion with my VSTS build definition and I need to configure it to ignore commit messages "commit-message-incrementing: Disabled" because I have an old commit message with a totally wrong version number.
I've added a gitversion.yml file with the above line to the root of my solution repo but its being ignored.
How do I configure this setting for my VSTS build definition?

**Comment by baltie** [comment]
There's a different option for ignoring specific commits. For instance:
```
ignore:
    sha: [<commit ids]
    commits-before: <datetime in ISO format>
```

**Comment by DaleKBurrell** [comment]
I'm happy to ignore all commit messages - but how do I get VSTS to read/respect my config?

**Comment by baltie** [comment]
Well, we're using VSTS and the GitConfig task there, and with the GitVersion.yml file in the root of the repository, it is happily ignoring old commit messages. We're using the ignore commits-before option.

**Comment by gep13** [comment]
@DaleKBurrell Which version of GitVersion are you using? Is this on hosted build agent, or are you running your own build agent? If the latter, are you doing a fresh clone of the repository each time?

**Comment by DaleKBurrell** [comment]
Hosted with VSTS.

**Comment by gep13** [comment]
@DaleKBurrell and to confirm, as I am not a big user of VSTS, does that build agent do a fresh clone of the repository on each build?  The reason that I ask is that I am worried about the cached asserted version number that is stored in the repository.  If this has already been asserted, then a configuration change may not cause this to be replaced.

**Comment by DaleKBurrell** [comment]
Yes it does a fresh clone of the repo each build.

**Comment by gep13** [comment]
@DaleKBurrell ok, again, which version of GitVersion are you using?  If you are using the current beta, it would be good to grab the output of the `/diag` flag, to see what is going on.

**Comment by gep13** [comment]
Also, can you show the folder structure that you are using?  i.e. where have you placed the configuration file?

**Comment by gep13** [comment]
Would also be good to confirm the output from `gitversion /showconfig`.

**Comment by DaleKBurrell** [comment]
I'm not 100% sure of the version - its what is available to add as a task in VSTS - it says version 3.* but I don't know if thats the actual version of GitVersion or not.

Top level of repo, where solution file it.

![image](https://user-images.githubusercontent.com/17735105/32269462-509f9160-bf57-11e7-999f-415992cd4ce5.png)

How does one use the /diag flag and the /showconfig flag when running under VSTS?

**Comment by gep13** [comment]
@DaleKBurrell the `/diag` flag is only available in the latest pre-release version of GitVersion, so you won't have access to that.  For running the `/showconfig` flag, you should be able to test that out locally, on the repo on your machine, just by running GitVersion.exe.

**Comment by gep13** [comment]
@DaleKBurrell Is this a public repository?

**Comment by DaleKBurrell** [comment]
OK - will try that when next in the office. No its a private repo.

**Comment by baltie** [comment]
You could try to install the command line version of GitVersion and run it in your repo folder locally. That should produce the same result as on VSTS. Locally, you can use the /diag command to see what happens.

**Comment by DaleKBurrell** [comment]
Having done some testing with a local copy of GitVersion I think its a misunderstanding on my part, 'commit-message-incrementing: Disabled` most likely doesn't apply to the base version calculation? Can someone confirm please.
And I have confirmed that I can ignore commits as suggested by @baltie.

**Comment by asbjornu** [comment]
@DaleKBurrell: Correct. Disabling commit message incrementing only disables that feature, to avoid unintended increments and to improve the speed of the version calculation.
