### ISSUE TITLE
Expose the tag and sha of source commit

### ISSUE THREAD

**Issue by mdesousa** [GitTools/GitVersion#1320]
It would be useful if the tag and sha of the source commit chosen by GitVersion could be exposed as a variable. In our case, we need to use GitDiff to get the list of changes since the last release and getting it out of GitVersion would be useful. Thanks.

**Comment by asbjornu** [comment]
The SHA is already output as a [`Sha` variable](http://gitversion.readthedocs.io/en/latest/more-info/variables/), but the tag name might not be available from GitVersion. It's not hard to get with the Git command line, though:

```shell
git describe --abbrev=0 --tags
```

**Comment by mdesousa** [comment]
I believe that SHA is for the current commit... I was asking for the SHA for the commit chosen as the source (a.k.a. "the base version") as explained here: http://gitversion.readthedocs.io/en/latest/more-info/version-sources/

**Comment by asbjornu** [comment]
Aha. Sorry for misunderstanding. This is indeed not something we expose. Since the base commit is something we already "have", it shouldn't be too much work adding this. Would you be up for submitting a PR?

**Comment by mdesousa** [comment]
Hi @asbjornu , sorry got side-tracked for a bit. After thinking about this for a bit more, I realized that it won't solve my problem after all because in my build I need the last minor tag... which may be different from the source tag found by GitVersion. I still feel that this may be useful to other people and could help troubleshoot. If this becomes a need again for my project I'll definitely take a crack at it. Thanks for your responses.

**Comment by asbjornu** [comment]
Excellent. I'll close this for now, but please reopen or submit a PR if/when you feel like it.
