### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by penguat** [GitTools/GitVersion#1322]
Where I work, we'd love to use this, but I suspect we shouldn't, unless there is a suitable Open Source license. We're pretty happy with things like the Apache, MIT, BSD licenses - or of course the http://www.wtfpl.net/ 

I know you had this discussion (Issue #1?) - but I don't see any evidence of a license in your documentation.

Thanks!

**Comment by pascalberger** [comment]
GitVersion is licensed under the MIT license. See [here](https://github.com/GitTools/GitVersion/blob/master/LICENSE).

**Comment by penguat** [comment]
*facepalm* thanks!
