### ISSUE TITLE
UpdateAssemblyInfo converts ANSI to UTF8 which breaks WiX

### ISSUE THREAD

**Issue by davidarcher** [GitTools/GitVersion#1325]
REPRO STEPS

1) Have an AssemblyInfo.cs file with the following contents that does not contain any byte-order marker (shows as an ANSI file in Notepad++):

```
using System.Reflection;
[assembly: AssemblyCompany("FooCorp®")]
[assembly: AssemblyVersion("1.0.0.0")]
```

2) Run GitVersion -UpdateAssemblyInfo against it.

EXPECTED

The version inside the AssemblyVersion attribute should be updated to the new version.

ACTUAL

The file is converted to UTF8 and characters like the ® are being converted from their ASCII representation (0xAE) to their unicode multi-byte equivalents (0xEFBFBD). This then breaks other tools like WiX that do not support Unicode.

**Comment by asbjornu** [comment]
This shouldn't be too hard to fix if you're comfortable with `System.Text.Encoding`. Are you up for the challenge? 😃
