### ISSUE TITLE
WriteVersionInfoToBuildLog takes 20 minutes - possible reasons?

### ISSUE THREAD

**Issue by Krumelur** [GitTools/GitVersion#1326]
We are working on a larger ASP.NET MVC based project and whenever a file changes the build takes forever. Enabled verbose logs shows me these two lines as possible culprits:

1179903 ms  WriteVersionInfoToBuildLog                 1 calls
1179857 ms  WriteVersionInfoToBuildLog                 1 calls

That's two time almost 20 minutes. This happens when building locally on a Windows 10 machine with VS2017. All ideas are welcome and if I can help, please let me know what is needed to further analyse this.

I hope I'm looking at the right repo here. Searching for "WriteVersionInfoToBuildLog" brought me to https://github.com/GitTools/GitVersion/blob/master/src/GitVersionTask/WriteVersionInfoToBuildLog.cs

**Comment by asbjornu** [comment]
Are you using `GitVersionTask` or `GitVersion.exe`? Which version of GitVersion are you using?
