### ISSUE TITLE
MSBuild task does not create gitversion.properties file in Jenkins env

### ISSUE THREAD

**Issue by arabcewicz** [GitTools/GitVersion#1329]
We use GitVersion in form of MSBuild tasks. In our Jenkins build script we additionally have to execute GitVersion.exe /output buildserver to generate the gitversion.properties file, because we want to capture the FullSemVer and set it as a build label in Jenkins.
In that way GitVersion is executed twice. Shouldn't MSbuild tasks immediately generate the gitversion.properties file?

**Comment by asbjornu** [comment]
Yes, absolutely. This requirement is recorded in #983. Thanks for reporting, closing as duplicate.
