### ISSUE TITLE
dump log before Console.ReadKey();

### ISSUE THREAD

**Issue by Chaosmeister** [GitTools/GitVersion#1330]
https://github.com/GitTools/GitVersion/blob/ee5b77a3439b7e905ca8401c7d8ed15b2495b0d6/src/GitVersionExe/Program.cs#L17-L33

`Console.ReadKey();` halts execution without actually showing something.
I think it would be better to call it after dumping the log with `Console.Write(log.ToString());`

**Comment by asbjornu** [comment]
I agree. Want to submit a pull request for that?
