### ISSUE TITLE
No valid git object identified by 'refs/remotes/origin/HEAD' exists in the repository.

### ISSUE THREAD

**Issue by Chaosmeister** [GitTools/GitVersion#1331]
In `GetBranchesContainingCommit()`
my 'refs/remotes/origin/HEAD' is evaluated as well but `commits.Reference.Target` is null and `if (!commits.Any())` will then throw an exception.

I don't really know how I got it like this.

**Comment by Chaosmeister** [comment]
after switching between another branch and the branch with the issue a few times, the issue disappeared.

**Comment by asbjornu** [comment]
Ok, great! Closing.
