### ISSUE TITLE
Precedence of tag and branch names when deducing version

### ISSUE THREAD

**Issue by pi3k14** [GitTools/GitVersion#1348]
I think you should tune the rules for calculating version numbers a bit.

When a commit is a tip of branch and contains a tag, the tag should only have precedence if it equals the version number of the branch and contains som extra metadata (eg. 1.0.0-rc.3), or if the branch doesn't contain any version number.

Eg. develop branch is just updated and tagged with an alpha/beta number, then there is forked a release branch with a given version number. An initial build from the release branch will create a version number from the tag, since the commit are the same.

I can't se any use case where current functionality makes sense.

**Comment by asbjornu** [comment]
If you could provide this as a (failing) `RepositoryFixture` test in a pull request, it would be much easier to understand what behavior you want as well as fix it. If you're able to fix your issue in the same pull request, it would be even better. 😄

**Comment by pi3k14** [comment]
@asbjornu could you have a look at this (to re-open the issue)?

**Comment by asbjornu** [comment]
@pi3k14, if you could follow up https://github.com/GitTools/GitVersion/issues/1348#issuecomment-375480149, we can perhaps move this forward. In its current state, there's not much I can do, sorry.

**Comment by pi3k14** [comment]
@asbjornu not quit sure I follow you on 

> if you could follow up #1348 (comment)

[#1743](https://github.com/GitTools/GitVersion/pull/1743) is my first attempt to describe the issue as a test case.

**Comment by asbjornu** [comment]
Sorry, @pi3k14. I did not notice the existence of #1743 until you pointed it out now. The test looks good. If you have ideas on how to fix it, feel free to expand the PR.

**Comment by arturcic** [comment]
Closed by #1743
