### ISSUE TITLE
Gitversion Task for VS2017-style csproj

### ISSUE THREAD

**Issue by tofutim** [GitTools/GitVersion#1349]
Long time user of Gitversion Task here. I recently switched to VS2017-style netstandard 13 assemblies and the version number is no longer showing up. I get zeros, so sad.

![image](https://user-images.githubusercontent.com/157766/34472441-92c254a2-ef17-11e7-8889-87c3072c9e9e.png)

**Update.** I was able to make progress by using the command line and using gitversion /updateassemblyinfo - but still this does not make the VS2017 nuget package generation work. What is needed is to update the "Version" in the csproj:

```
  <PropertyGroup>
    <TargetFramework>netstandard1.4</TargetFramework>
    <Version>2.0.0</Version>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
  </PropertyGroup>
```

**Comment by TsengSR** [comment]
Did you add 

```
    <PackageReference Include="GitVersionTask" Version="4.0.0-beta0012">
      <PrivateAssets>All</PrivateAssets>
    </PackageReference>
```
To your csproj file? As the [documentation](https://gitversion.readthedocs.io/en/latest/usage/msbuild-task/) already notes, you need to add the above to every project where you want the `AssemblyInfo.cs` file modified as part of the build process

**Comment by tofutim** [comment]
There is no AssemblyInfo.cs in the new VS2017 scheme.

**Comment by tofutim** [comment]
I ended up using 'msbuild /t:restore /p:Version=x.x.x.x'. This will set the
nuget package version, the assembly version and the file version
simultaneously.

**Comment by TsengSR** [comment]
Technically not fully true. While none `AssemblyInfo.cs` is created by the default template, you can still use it by creating one yourself.

Typically during the build process the `AssemblyInfo.cs` will be created in the output (in `obj/Debug/<releaseplatform>/<YourProjectName>.AssemblyInfo.cs`) directory and the attribute added to it, based on values set in your `*.csproj` file. 

You can disable the creation of `AssemblyInfo.cs` globally via 

```
  <PropertyGroup>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>
```

or you can selectively disable specific attributes via 

```
  <PropertyGroup>
    <GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
    <GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
    <GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
  </PropertyGroup>
```

if you have that attributes already defined in your own `AssemblyInfo.cs` (or any other file, the name is not important here)

**Comment by yohsk10** [comment]
Hi,

I'm interested about this issue. So, to fully understand what you mean, you recommend to create an AssemblyInfo.cs file in each project and specify in our *.csproj the attributes that we do not want generated automatically ?

Thank you in advance.
Yohsk

**Comment by jayoungers** [comment]
Using @tofutim 's solution, I just added this to my `MSBuild()` step:

.WithProperty("Version", version.AssemblySemVer)

**Comment by JoshSchreuder** [comment]
GitVersionTask 4.0.0-beta* seems to work with the new format, as long as you don't have anything like

```
<GenerateAssemblyFileVersionAttribute>false</GenerateAssemblyFileVersionAttribute>
<GenerateAssemblyInformationalVersionAttribute>false</GenerateAssemblyInformationalVersionAttribute>
<GenerateAssemblyVersionAttribute>false</GenerateAssemblyVersionAttribute>
```

In your .csproj. I also don't have any AssemblyInfo.cs files, and it seems fine.
