### ISSUE TITLE
GitVersionTask v4.0.0-beta.13 is not available in nuget.org

### ISSUE THREAD

**Issue by kpanwar** [GitTools/GitVersion#1354]
Is this by design or did you guys forget to push to nuget?

**Comment by gjonespf** [comment]
Indeed, would be great to have these prerelease versions auto-published to nuget/chocolatey.

**Comment by asbjornu** [comment]
Sorry, but we don't have a fully automated build pipeline yet, but we're working to fix it (see #1338).

**Comment by cosminpopescu** [comment]
Any updated on this, it's been 5 months since beta 13.

**Comment by D3-LucaPiombino** [comment]
Sorry,
but can someone who have the required permissions, 
push the package for the `beta.13` to nuget?

We are using the command line package in our CI scripts from nuget, 
and it would be nice to use this version, as there are some fixes that we 
need.

Thanks

**Comment by danijam** [comment]
@asbjornu Would you be able to or know who can push build beta 13 to NuGet. I'd like to try it out to see if it helps with the performance issues faced #1448

**Comment by asbjornu** [comment]
@danijam: Sorry, but until #1445 is fixed, it's going to be tough getting a new version out the door.

**Comment by JakeGinnivan** [comment]
This is sorted. Please open up fresh issues if there are any more, will aim to not let it get stale again :)
