### ISSUE TITLE
How Can I include the TeamCity build number in the metadata

### ISSUE THREAD

**Issue by RobSmyth** [GitTools/GitVersion#1358]
Hi,

I want to include the TeamCity build number in the SemVer (AssemblyInformationVersion) metadata. How can I do this?

I want the build server's build number so that releases can be traced back to a particular build in an environment were builds of the same `<major>.<minor>.<patch>` version number could (in theory) be built multiple times. We need traceability to the build logs.

I'm hoping somebody has already done this. I know that TeamCity sets an environment variable with this number so it is both possible to detect if the build is running from a TeamCity server and what the build number is.

**Comment by RobSmyth** [comment]
I've had some success by adding the TC build number to the env.Git_Branch TC parameter:

 

>  %teamcity.build.vcs.branch.XXXXX%**.B%system.build.number%**

Seems to work, the build number is visible as .B123.

Will doing this break something else? Will 'Git_Branch' work as expected?

**Comment by asbjornu** [comment]
Wow, this is quite a hack. I'm surprised and impressed that it works! 😄 I can't guarantee that it'll work in all scenarios, though. Request-wise, this seems to be a duplicate of #1157 (and #648 before that). Is that correct? If so, can this be closed as a duplicate?

**Comment by RobSmyth** [comment]
Hi, yes it is quite a hack and it does not work properly. I forget why.

As for be a duplicate - that depends on the solution. #1157 is for TFS so I cannot say a solution for TFS would be usable with TeamCity. Using environment variables (#648) may well be workable with TeamCity as I think I can get it push out the build number to an environment variable.

If youre going to implement environment variables, then I think I can use that solution and this can be closed as a duplicate.

Rob

**Comment by asbjornu** [comment]
After thinking about this for a while and reading all the requirements and ideas for solution, I think environment variables is the way to go. We don't have anything near an implementation yet, though. Are you up for the challenge?

**Comment by asbjornu** [comment]
If what I describe in https://github.com/GitTools/GitVersion/issues/1157#issuecomment-372108985 sounds like a fitting solution to this problem, I propose that we close this as a duplicate of #1157.

**Comment by RobSmyth** [comment]
> Are you up for the challenge?

Maybe LOL. I'll see how i go.

**Comment by asbjornu** [comment]
Excellent! Just shout out if you need any assistance!

**Comment by jbaehr** [comment]
Please try/comment the PR #1385. It allows you to use environment variables in format strings. I think this would solve your issue.
