### ISSUE TITLE
Gitversion slows down dramatically with dotnet 4.7.1

### ISSUE THREAD

**Issue by joewaid** [GitTools/GitVersion#1361]
[dllsdotnet470.txt](https://github.com/GitTools/GitVersion/files/1648129/dllsdotnet470.txt)
[dllsdotnet471.txt](https://github.com/GitTools/GitVersion/files/1648130/dllsdotnet471.txt)

I've been chasing a strange performance issue with gitversion on some build servers.  On most build servers gitversion takes about 1 minute to run and calculate the version number for a specific repo. On some new build servers it takes 10 minutes to do the same calculation on the same repo.

I reviewed the dlls loaded by gitversion on a slow machine and on a fast machine and was able to determine that the slow machines were running dotnet 4.7.1 and the fast machines had dotnet 4.7.0.

I installed dotnet 4.7.1, via chocolatey, onto a machine that was running quickly, taking about 1 minute to calculate the version number, and after rebooting that time has increased to about 10 minutes.

I'm running the command: gitversion from the root of my repo with no command line arguments in this test. I'm running the latest version of gitversion 3.6.4. 

I've attached a list of the dlls loaded by gitversion and their version information with both dotnet4.7 and dotnet4.7.1 from the same machine.

**Comment by joewaid** [comment]
![perfanalysis](https://user-images.githubusercontent.com/5883543/35177857-52b780c4-fd38-11e7-8c66-7794faecbf1f.png)
I think this is being caused by this performance issue related to StackTrace. https://github.com/Microsoft/dotnet/issues/529

I did some profiling and found the majority of the time the performance was spent in System.Diagnostics.StackTrace.ctor 

I'm not sure if it's worth doing the workaround mentioned in this thread or not. It depends when the fix from Microsoft is actually released.

**Comment by springy76** [comment]
4.7.1. fix has been released 17 days ago. (KB4054856)

**Comment by asbjornu** [comment]
It might be that #1374 helps in this regard, so I've merged that. If you're able to test that without a package being produced, please report back your findings.

It would be great to have some [BenchmarkDotNet](https://github.com/dotnet/BenchmarkDotNet) tests for stuff like this. Preferably coupled with an online analysis server that can report back to Github when the performance deteriorates in a pull request.
