### ISSUE TITLE
Move packaging logic to cake

### ISSUE THREAD

**Issue by dazinator** [GitTools/GitVersion#1363]
In my nestandard branch, i'm moving the ILMerge and packaging mabuild logic out of the GitVersion.exe csproj file AfterBuild event, and into the cake build script instead. I expect to replace pepita with a dotnet cli pack or a nuget pack operation in the process as well..

Let me know if anyone forsees any issue with this.

The main reason I started doing this is because the AfterBuild event wasnt fired anymore since I upgraded the csproj to sdk style,  and I think its probably better for all that packaging logic to be in cake anyway.

Im just raising this here for visibility.

**Comment by asbjornu** [comment]
Sounds like a good idea. The more we can do with Cake, the better, imho.

**Comment by dazinator** [comment]
Great - I suceeded in doing this in the end.

**Comment by dazinator** [comment]
done in #1269
