### ISSUE TITLE
Montonically increasing AssemblyFileVersion to satisfy the MSI 

### ISSUE THREAD

**Issue by ruhullahshah** [GitTools/GitVersion#1366]
We use GitFlow as our branching model and GitVersion 3 for versioning our Assemblies. 

The versioning scheme in use is:
assembly-file-versioning-scheme: MajorMinorPatchTag.

GitVersion resets the Tag in beta releases at times and MSI requirement of strictly increasing FileVersion is violated. 

Is there a solution existing for this issue? In case it is not, how about reading the Tag from environment if  presented with a special syntax such as {$TAG}? We can then use the build number which is strictly increasing as the Tag

Issue https://github.com/GitTools/GitVersion/issues/1157 has a similar requirement and so does Issue https://github.com/GitTools/GitVersion/issues/648

**Comment by asbjornu** [comment]
Yes, I think this is a duplicate of #1157. We would love a PR solving this.

**Comment by ruhullahshah** [comment]
Fixed with the https://github.com/GitTools/GitVersion/pull/1385
