### ISSUE TITLE
Unable to increment patch with VSTS and GitVersion plugin version 3.6.5

### ISSUE THREAD

**Issue by DerekChasse** [GitTools/GitVersion#1370]
I'm looking to do mainline development using VSTS and with GitVersion 3.6.5 currently installed.

This is essentially what I am trying to configure:
![cdraw](https://user-images.githubusercontent.com/1869236/36107604-953fcf9c-0fe8-11e8-9753-44b9dec7902f.png)

I need to do so because these are libraries which are uploaded to internal Nuget repositories.  Only master is packaged and uploaded to these repositories, feature branches are not.

What I'm noticing is that when using the +semver: XXX values in the pull request comments I do not seem to be able to update the patch number.

Is this configuration supported?  Reading the documentation this seems like it's a primary use-case, however much of the documentation seems to elaborate how to configure GitVersion when you are in total control of your build servers, unlike using Hosted Agents as I am.

**Comment by AlirezaInGitHub** [comment]
Mode _MainLine_ was introduced in version 4. Currently, GitVersion VSTS task is using version _3.*_. You should get an error, if you set mode to _MainLine_ in _GitVersion.yml_.

**Comment by DerekChasse** [comment]
So if I understand correctly, this will not work until an updated version of the plugin is pushed to VSTS?

**Comment by stoopered** [comment]
When is this plugin going to be updated? I am trying to use the NuGet, but I am having no luck. I have spent 3 days looking at this.

**Comment by NiekGr** [comment]
Oh, so that is why I can't get this working...

Maybe the documentation should say something about this.

**Comment by alpeshv** [comment]
try [this](https://github.com/GitTools/GitVersion/issues/1160#issuecomment-381517122)
