### ISSUE TITLE
GitFlow: Merging back a hotifx branch to develop shouldn't bump the version

### ISSUE THREAD

**Issue by alexiwonder** [GitTools/GitVersion#1372]
Following GitFlow, when I merge a hotfix branch to master and then merge back it to develop, it makes the _minor_ part of the version of develop bump. So if the hotfix branch name is _hotfix/1.2.3_, master will have _1.2.3_ but develop will have _1.2.4_. In other words, hotfix is treated as a feature in develop.
I tried Including _+semver: skip_ but it didn't work.

Any suggestion?

**Comment by asbjornu** [comment]
Which version of GitVersion are you using?

**Comment by alexiwonder** [comment]
@asbjornu:
GitVersion 4.0.0-beta.12+1315.Branch.master.Sha.9c70946f68973b3b31b2861913c247fbe6c3f0ec

**Comment by asbjornu** [comment]
`develop` will always be +1 of either `Major`, `Minor` or `Patch` depending on what you have set `increment` to compared to `master`.

**Comment by alexiwonder** [comment]
@asbjornu But why doesn't it respect _+semver: skip_ at all?

**Comment by asbjornu** [comment]
Good question. I guess @JakeGinnivan will have to answer that, I haven't looked so much at the commit message feature to be able to provide you with an answer.
