### ISSUE TITLE
GitVersion as an Build Feature on teamcity

### ISSUE THREAD

**Issue by neslekkim** [GitTools/GitVersion#1382]
Is it possible to setup GitVersion as an build feature?, I'm using it in a build step to create versionnumber, which works fine, but when I need to create nuget packages, I also need to inject this version number inside my nuspec file.
Using the file-content replacer for this fails, since it is run before any build steps.

Or do GitVersion know abut nuspec files and can be used there also?

**Comment by mexmirror** [comment]
Maybe your issue could be solved using nuget cli. When building with nuget cli you can specify the version as paramter without replace the string inside the nuspec file.

 ```
 <metadata>
    <id>Package</id>
    <version>$version$</version>
    <description>Description</description>
    <authors>Author</authors>
  </metadata> 
```

and then call nuget pack package.nuspec -Properties version=1.2.3

**Comment by neslekkim** [comment]
It seems like there is an parameter Version also, so I did this:
Version=%system.build.number%
It seems to work, but I'm not sure how nuget creates the filename afterwards, the full number is not going there, but inside the nuspec it is correct, so at the moment it seems to be working.

Not sure if %system.build.number% is the correct property, but it looks like it.
Properties parameter seems like an even better alternative for more control, thanks for that tip!

**Comment by asbjornu** [comment]
How are you using GitVersion in TeamCity? What's the "Build number" set to in the general settings of the build configuration?
