### ISSUE TITLE
GitVersion.exe - dotnetcore

### ISSUE THREAD

**Issue by dazinator** [GitTools/GitVersion#1388]
Let's build GitVersion.exe for `dotnet core`.
We can then create a `dotnet core` based docker image as an alternative to the `mono` one.

Note: I have done most of the work already in #1269  and I think it makes sense to continue with this work there.

1. There are a few commands in `GitVersion.exe` that I will remove from the `dotnet core` version:

    /exec           Executes target executable making GitVersion variables available as environmental variables
    /execargs       Arguments for the executable specified by /exec
    /proj           Build a msbuild file, GitVersion variables will be passed as msbuild properties
    /projargs       Additional arguments to pass to msbuild

 Those all use the `ProcessHelper` util class which won't compile for dotnetcore. 

Also:

    /diag

Because this calls `DumpGraph` which isn't available for dotnet core version either.

2. May as well remove Fody from GitVersion.exe - we only appear to use `Caseless` extension, but as far as I can tell, we specify `StringComparison` everywhere anyway. By removing Fody completely it means we can build using dotnetcore sdk i.e `dotnet build` - the fody msbuild task doesn't work with that. This may help us if we eventaully want to orchestrate builds fully with dotnet sdk,

**Comment by asbjornu** [comment]
👍 from me.

**Comment by dazinator** [comment]
Done in #1269
