### ISSUE TITLE
GitVersion configuration

### ISSUE THREAD

**Issue by martinfletcher** [GitTools/GitVersion#1391]
I am trying to achieve the following with commits:

master: No increment
support/*: No increment
hotfix/*: Patch increment via pull request to support/* or master
feature/*: Minor increment via pull request to support/* or master

Can you give any guidance on how to achieve this?

Thank

Martin

**Comment by asbjornu** [comment]
You can set [`increment`](http://gitversion.readthedocs.io/en/latest/configuration/#increment)  to `None` in config, but that would also include merges, so auto-increment from merges wouldn't increment. Is it impossible for you to add a tag on the merge-commits or as an annotated commit after so that ensures an increment?

**Comment by martinfletcher** [comment]
Sorry I should have added more detail.

We have a large number of developers, and require the versioning to be controlled through branch work flow, rather than using the commit messages. 

What I am trying to achieve is to control the versioning from the format of the branching model,  github.com flow with additions, without the need to know about several or how the commit messages work.

Master - only accept pull requests
Support - only accept pull requests
Feature - increments minor from pull request to master
Hotfix - increments patch from pull request to master or support/*

Hope this makes the issue clearer.

**Comment by martinfletcher** [comment]
Is there anyway to achieve this?

Also, I am using gitversion in a vsts build.

**Comment by asbjornu** [comment]
I don't quite understand this:

> We have a large number of developers, and require the versioning to be controlled through branch work flow, rather than using the commit messages.

GitVersion works just fine without commit messages. For git flow, the default behavior is that GitVersion finds a version source from `master` &mdash; usually a tag &mdash; and then increments the major, minor or patch of a derived branch such as `develop` based on that.

Please review [the example in the documentation](http://gitversion.readthedocs.io/en/latest/examples/) for more information.

From what I understand from your initial question, you don't want this behavior. The only alternative I can see then is to increment manually, either with commit messages or tags.

**Comment by martinfletcher** [comment]
Thanks for your reply.

To clarify, our development process is based on the github flow model, with the addition of hotfix, bug and support branching as follows:

**master and support/***

- Tags only created on commit to **master/support/*** (via a CI build, not manually) 
- Only accepts pull requests
- Should increment version based on branch being merged in
  - Patch when **hotfix/bug** merged
  - Minor when **feature/*** merged

The issue I have, is that the branch being merged into **master/support/*** is refs/pull, and so gitversion can not work out which part of the version to increment.

Am I mistaken, or Is there a config that allows this?

**Comment by asbjornu** [comment]
This sounds like a very bespoke flow, so I doubt GitVersion can accommodate your needs. You could try Mainline mode, but you're going to have problems with your increments unless you can get the CI to tag merges for you.
