### ISSUE TITLE
New release?? (or new beta)

### ISSUE THREAD

**Issue by jogibear9988** [GitTools/GitVersion#1398]
Is it possible to create a New Release (or new beta Release)?

**Comment by sebastianlux** [comment]
A new release would be indeed great because in case of beta versions, the produced _Team Foundation Server build task extension_  (the _vsix_ file of the release artifacts) is permitted to be installed on our on-premise TFS because the TFS extension versioning does not support semver.

**Comment by vfabregat** [comment]
A new release it would be great, the version 4 has nice improvements ( such as the mainline mode). Also, the last Beta has more than a year.

How can we help to distribute a new release?

**Comment by NiekGr** [comment]
> How can we help to distribute a new release?

I would like to know this as well.

**Comment by jogibear9988** [comment]
it is released
