### ISSUE TITLE
`dotnet build` command always fails with GitVersionTask 4.0.0-beta

### ISSUE THREAD

**Issue by walterlv** [GitTools/GitVersion#1399]
When a totally new .NET Standard project is created and GitVersionTask is installed on it, `dotnet build` command certainly fails with this message below:

> C:\Users\walterlv\.nuget\packages\gitversiontask\4.0.0-beta0012\build\GitVersionTask.targets(49,5): error MSB4062: The "GitVersionTask.WriteVersionInfoToBuildLog" task could not be loaded from the assembly C:\Users\walterlv\.nuget\packages\gitversiontask\4.0.0-beta0012\build\GitVersionTask.dll. **Could not load file or assembly** 'Microsoft.Build.Utilities.v4.0, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL'. **The system cannot find the file specified.** **Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.** [C:\Users\walterlv\Desktop\XxxYyyZzz\XxxYyyZzz\XxxYyyZzz.csproj]

The raw error message is here:

```
> dotnet build
Microsoft (R) Build Engine version 15.6.84.34536 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 42.12 ms for C:\Users\walterlv\Desktop\XxxYyyZzz\XxxYyyZzz\XxxYyyZzz.csproj.
C:\Users\walterlv\.nuget\packages\gitversiontask\4.0.0-beta0012\build\GitVersionTask.targets(49,5): error MSB4062: The "GitVersionTask.WriteVersionInfoToBuildLog" task could not be loaded from the assembly C:\Users\walterlv\.nuget\packages\gitversiontask\4.0.0-beta0012\build\GitVersionTask.dll. Could not load file or assembly 'Microsoft.Build.Utilities.v4.0, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL'. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask. [C:\Users\walterlv\Desktop\XxxYyyZzz\XxxYyyZzz\XxxYyyZzz.csproj]

Build FAILED.

C:\Users\walterlv\.nuget\packages\gitversiontask\4.0.0-beta0012\build\GitVersionTask.targets(49,5): error MSB4062: The "GitVersionTask.WriteVersionInfoToBuildLog" task could not be loaded from the assembly C:\Users\walterlv\.nuget\packages\gitversiontask\4.0.0-beta0012\build\GitVersionTask.dll. Could not load file or assembly 'Microsoft.Build.Utilities.v4.0, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL'. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask. [C:\Users\walterlv\Desktop\XxxYyyZzz\XxxYyyZzz\XxxYyyZzz.csproj]
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:01.40
```

Fortunately, if I build it using msbuild.exe or Visual Studio 2017, it succeeds.

My environment:

- Windows 10.0.16299.371
- Visual Studio 2017 (15.6.6)

**Comment by walterlv** [comment]
I found some related issues in other repositories:

- .NET Core MSBuild cannot load tasks built against MSBuild 4.0 Microsoft/msbuild#2111
- Should the SDK include Microsoft.Build.Utilities.v4.0? dotnet/sdk#1870

It seems that we should change our way to write UsingTask following .NET Core MSBuild hint.

**Comment by elestedt** [comment]
Is there a workaround or must I look for another library if I've run into this? I'm going to build it CLI in a docker container in my CI environment and msbuild does not exist there

**Comment by dazinator** [comment]
What version of dotnet sdk are you building under? Please add a global.json file to lock to sdk version 2.0.0 or below. Support for building under > 2 has not bren merged yet. Please also try latest beta15 package from appveyor project nuget feed or failing that, beta14 from nuget.org

**Comment by dazinator** [comment]
P.s we do multitarget and you should see netstandard1.5 compiled gitversiontask assembly in the nuget package.

**Comment by walterlv** [comment]
@dazinator This issue was posted four months ago and .NET Core 2.0 was the latest version at that time. Maybe I can try the newest version now.

**Comment by dazinator** [comment]
@walterlv Sure. I think there is still an issue with the latest version if using VS2017 latest update (15.8.X). I uninstalled VS2017 15.8.2 and installed VS2017 15.7.6 and it works. I have just created an issue using VS's send feedback to report the issue. Also I have reported here in case its a utilpack thing: https://github.com/CometaSolutions/UtilPack/issues/30

**Comment by walterlv** [comment]
@dazinator Actually, it's not the bug of MSBuild or Visual Studio. I've written my own NuGet package which is used to generate git version and it works both on `MSBuild` and `dotnet build`.
- [How to build a cross-platform-NuGet-tool-package - walterlv](https://walterlv.github.io/post/create-a-cross-platform-msbuild-task-based-nuget-tool.html)
- [Shipping a cross-platform MSBuild task in a NuGet package](https://natemcmaster.com/blog/2017/07/05/msbuild-task-in-nuget/)

**Comment by dazinator** [comment]
@walterlv - The issue we are seeing at #1458 only seems to occur when building with VS 2017 Community version 15.8.X.  When building from msbuild on the command line, or from dotnet build on the command line it works. Are you saying you can build also fine from VS 2017? If so would you mind confirming what version of VS2017 you are using? Thanks

**Comment by walterlv** [comment]
@dazinator   
Mine: 15.8.1  
It works fine, too.

**Comment by dazinator** [comment]
@walterlv  ok thanks for confirming. I think we can close this one then. If you do ever update VS to 15.8.2 and it starts failing (or not) please drop a comment on #1458 to let us know :-) Thanks

**Comment by walterlv** [comment]
@dazinator OK!

**Comment by walterlv** [comment]
@dazinator I've updated to vs 2017 15.8.2 and all builds still work fine.

> Microsoft Visual Studio Professional 2017  
> Version 15.8.2  
> © 2017 Microsoft Corporation.  
> All rights reserved.

```
1>------ Rebuild All started: Project: CovulisGatarTeani, Configuration: Debug Any CPU ------
1>C:\Users\lvyi\Desktop\CovulisGatarTeani\CovulisGatarTeani\CovulisGatarTeani.csproj : warning NU1701: Package 'GitVersion 4.0.0-beta0012' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.1'. This package may not be fully compatible with your project.
1>CovulisGatarTeani -> C:\Users\lvyi\Desktop\CovulisGatarTeani\CovulisGatarTeani\bin\Debug\netcoreapp2.1\CovulisGatarTeani.dll
1>Done building project "CovulisGatarTeani.csproj".
========== Rebuild All: 1 succeeded, 0 failed, 0 skipped ==========
```

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.1</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="GitVersion" Version="4.0.0-beta0012" />
  </ItemGroup>
</Project>
```
