### ISSUE TITLE
TfsTask - Add 'path' parameter

### ISSUE THREAD

**Issue by Rora** [GitTools/GitVersion#1401]
## Context
We're using the gitversion tfs task, gitversion with multiple solutions in 1 repository. Our repository tree is the following:

Root
   - Solution A
      - gitversion.yml
      - Project A1
         - Program.cs
   - Solution B
      - gitversion.yml

We have a separate build for each solution. Since the build uses the root of our repo as working directory we have to setup most build steps to look in the solution dir. For example, when building we provide 'Solution A/**/*.csproj'.

Since this isn't supported at the moment by the gitversion task, gitversion isn't able to find our gitversion file.

## Desired behavior
At the moment the GitVersion task calls GitVersion.exe with the path to the working directory of the build. It would be great if we could add a parameter 'Target path' that allows users to change the path to a deeper level. The gitversion would use this path and combine it with the working directory path changing:

``C:\Agent-1\_work\_tasks\GitVersion_e5983830-3f75-11e5-82ed-81492570a08e\3.6.5\GitVersion.exe C:\Agent-1\_work\16\s /output buildserver /nofetch``

to

``C:\Agent-1\_work\_tasks\GitVersion_e5983830-3f75-11e5-82ed-81492570a08e\3.6.5\GitVersion.exe C:\Agent-1\_work\16\s\Solution A /output buildserver /nofetch`` 

**I'm willing to write a PR if you agree with this enhancement**

**Comment by asbjornu** [comment]
This sounds related to #1170. Is it?

**Comment by Roraa** [comment]
Correct, I however try to fix it by running gitversion in a specific directory. If we'd allow for gitversion.yml to exist in subdirectories, then how would we handle multiple gitversion files? For example:

/SolutionA/Gitversion.yml
/SolutionB/Gitversion.yml


________________________________
Van: Asbjørn Ulsberg <notifications@github.com>
Verzonden: maandag 28 mei 2018 11:54
Aan: GitTools/GitVersion
CC: Rob; Author
Onderwerp: Re: [GitTools/GitVersion] TfsTask - Add 'path' parameter (#1401)


This sounds related to #1170<https://github.com/GitTools/GitVersion/issues/1170>. Is it?

**Comment by asbjornu** [comment]
The closest one to the project/solution being built, wins?

**Comment by Roraa** [comment]
That could result in a tie, also when running in a tfs build, the gitversion task is ran without context of any project or solution. We use it as follows:

1. Start build
1. Run the gitversion task (which sets the Gitversion.NugetVersion var)
1. Compile project X
1. Pack project X artifacts (gets the version from the Gitversion.NugetVersion var)

When we ran the gitversion task, it didn't know that we would be using it for packing project X so it wouldn't know which gitversion.yml to use.

If we'd allow for a path parameter on the task the user could point gitversion to the right directory. This would solve all problems IMO.

**Comment by asbjornu** [comment]
In cases where there's a tie, an explicit working directory given as an argument makes sense, but otherwise I think a sensible convention of closest `GitVersion.yml`, `*.csproj`, `*.sln` or `.git` folder would be neat. Thoughts?

**Comment by Roraa** [comment]
I'm sorry but I don't understand yet how that would work in our usage, how would the GitVersion build task know what yml file to use at the start of a build?

**Comment by Rora** [comment]
I wish it could, but I'm using the GitVersion tfs build task, I cant set it's working directory or insert a CD command on it. My PR however allows the user to set a path variable

**Comment by asbjornu** [comment]
Yes, I was thinking with your PR merged, that would be the solution. Just trying to think this through along other requested features such as #1170.

**Comment by arturcic** [comment]
closed in #1594
