### ISSUE TITLE
Update LibGit2Sharp.NativeBinaries to 1.0.192+, to fix Linux/OpenSSL 1.1

### ISSUE THREAD

**Issue by directhex** [GitTools/GitVersion#1408]
libgit is built against libcurl, for HTTP support

libcurl has a pluggable back-end for which SSL library to use, but the choice is made at compile-time and can't be swapped out

For old, esoteric, stupid reasons, `libcurl.so.3` can be built against OpenSSL 1.1 or OpenSSL 1.0, but not both at once - and on systems where one is installed, the other breaks.

e.g.:

```
MSBUILD : warning : WARN [05/11/18 16:26:23:16] Could not determine assembly version: System.TypeInitializationException: The type initializer for 'LibGit2Sharp.Core.NativeMethods' threw an exception. ---> System.DllNotFoundException: lib/linux/x86_64/libgit2-baa87df.so [x.csproj]
MSBUILD : warning :   at (wrapper managed-to-native) LibGit2Sharp.Core.NativeMethods.git_libgit2_init() [x.csproj]
```

This was fixed in LibGit2Sharp.NativeBinaries 1.0.192, which switched to using GNUTLS as its SSL library (which is less prone to breakage than OpenSSL).

As-is, this breaks on Ubuntu 18.04

**Comment by directhex** [comment]
This is actually worse than I thought - The bundled libgit2 links against OpenSSL directly as well as transitively through libcurl. And it links against the exact ABI version 1.0.0 - which was obsoleted when SSLv3 support was removed, affecting not only distributions with OpenSSL 1.1, but even ones with 1.0.x where x isn't 0 (e.g. Debian 9)

**Comment by jrkoch** [comment]
i'm not sure if this is the right place to post this, but I'm using Cake and GitVersion for .NET development on Ubuntu.  Upgrading to 18.04 broke it.  If I install `libcurl3` per GitVersion's README, apt will uninstall `libcurl4` which will uninstall `curl`.. my temporary workaround is to add an Artful mirror back to sources.list and install version `7.55.1-1ubuntu2.5` of both `curl` and `libcurl3`.

**Comment by directhex** [comment]
Yes that's the same bug. libcurl3 is libcurl.so.4 built with OpenSSL 1.0, libcurl4 is libcurl.so.4 built with OpenSSL 1.1

NativeBinaries 1.0.192 depends on libcurl-gnutls.so.3 which doesn't cause conflicts with curl or cmake on modern distributions

**Comment by dazinator** [comment]
I am curious if #1269 might help you.. It enables gitversion to run on .netstandard platforms - so it can run under mono on linux (as per previoulsy) - but it can also run under `dotnet core` on linux. It uses a different version of `libgitsharp` and the native binaries to do that. If you read the description at the top of the PR it should explain where you can get that version of gitversion from.

**Comment by bravecobra** [comment]
I just ran into the same issue. Any progress on this?

**Comment by asbjornu** [comment]
After upgrading to LibGit2Sharp 0.26 in #1713, I hope this problem is fixed. Please try [the latest build of GitVersion](https://www.nuget.org/packages/GitVersionCore/5.0.0-beta4-1) and report back whether it fixes this problem or not. Reopen this issue if the problem persists.
