### ISSUE TITLE
Update libgit2sharp to 0.24+ to fix path issues with escape sequences

### ISSUE THREAD

**Issue by nlowe** [GitTools/GitVersion#1415]
`libgit2sharp` can't load the native DLL if the path contains `%2F`, which happens frequently on Jenkins when building pipelines in nested folders.

libgit2/libgit2sharp#1389 was fixed in libgit2/libgit2sharp#1409, which appears to be in 0.24+. It looks like GitVersion `master` is still targeting a prerelease of `0.23`. Any chance we can upgrade to 0.24+ and cut a release? I'd be happy to send a PR if that is acceptable.

We can work around this by setting a `customWorkspace` on the Jenkins node definition, but I'd really like to not have to update all my builds with custom workspace naming logic just to get nice versioning.

**Comment by nlowe** [comment]
It seems like #1248 may solve this.

**Comment by asbjornu** [comment]
After upgrading to LibGit2Sharp 0.26 in #1713, I hope this problem is fixed. Please try [the latest build of GitVersion](https://www.nuget.org/packages/GitVersionCore/5.0.0-beta4-1) and report back whether it fixes this problem or not. Reopen this issue if the problem persists.
