### ISSUE TITLE
Question: How to configure GitVersion to not have a version increment on a pull request on release branch during stabilization

### ISSUE THREAD

**Issue by marc-mueller** [GitTools/GitVersion#1417]
Hi Guys

We are currently facing the following situation in a project and haven't found a solution for it.
- When the software goes into QA, we isolate it by creating a release branch (`releases\v1.2.0`)
- During the testing phase, found bugs will be fixed on that release branch (since development is further)
- To also control the bugfix changes to release branches, the developer creates a pull request for integrating this bugfix into the release branch.
- The version of the pull request is then `1.3.0` and after the merge into the release branch has been done, the version of the release branch is again `1.2.0`.

How do we get the config right that the bugfix PR has the same version as the release branch?

Thanks
Marc

**Comment by stoopered** [comment]
Did you ever get an answer??

I would also like to know this. Same issue. This is a popular branching strategy, you should always merge to Master first, then GitVersion should pick up Release branches version as the base. i.e Release\v1.2.10 so ever merged commit should be 1.2.11, 1.2.12, 1.2.13 etc etc.

If this is fixed then my entire branching strategy will be beautiful!
