### ISSUE TITLE
Versioning all assemblies

### ISSUE THREAD

**Issue by AndersLindPedersen** [GitTools/GitVersion#1420]
Having a solution with multiple projects, how does one go about versioning all assemblies?

I have added GitversionTask and created a GitVersion.yml that fit our needs. But when building with MSBUILD, only the executable is versioned? I would like all dll from different projects also to be versioned.

Looks like I could add GitVersionTask to all projects, but that seems like a workaround. Would like that we do not have to think of remebering to add GitVersionTask when new dlls is added.

I have tried the VSTS GitVersion extension which does this by default. Unfortunaly at the moment we are not allowed to use the VSTS extension. :(

**Comment by JakeGinnivan** [comment]
The command line can update all assembly info files. The two main choices are using the command line (the VSTS extension is a wrapper for the CLI) or install the task into each assembly.

Hope that helps, please re-open the issue if that doesn't answer the question :)

**Comment by AndersLindPedersen** [comment]
Thanks that helps alot. And after your comment i actually also found that in the documentation. Thank you for your time
