### ISSUE TITLE
Question: AssemblySemFileVer of release version less than previous commit

### ISSUE THREAD

**Issue by Sam13** [GitTools/GitVersion#1426]
I'm using GitVersion 4.0.0-beta.12 and have configured
`assembly-file-versioning-scheme: MajorMinorPatchTag`
Reason I do this is to have a different file version for each build.

This causes the problem that the file version of a release is smaller than the one of the commits before the released version. SemVer ordering would correct but if you just look at the file version (as e.g. Installer tools do) it isn't.

Example:
Release tag: v5.1.6
`{
  "Major":5,
  "Minor":1,
  "Patch":6,
...
  "PreReleaseNumber":"",
...
  "SemVer":"5.1.6",
  "AssemblySemVer":"5.1.6.0",
  "AssemblySemFileVer":"5.1.6.0",
  "FullSemVer":"5.1.6",
...
  "CommitsSinceVersionSource":83,
  "CommitsSinceVersionSourcePadded":"0000083", 
}`

Commit before release tag v5.1.6
`
{
  "Major":5,
  "Minor":1,
  "Patch":6,
...
  "PreReleaseNumber":82,
...
  "SemVer":"5.1.6-Branch-13e7f29.82",
...
  "AssemblySemVer":"5.1.6.82",
  "AssemblySemFileVer":"5.1.6.82",
  "FullSemVer":"5.1.6-Branch-13e7f29.82",
...
  "CommitsSinceVersionSource":82,
  "CommitsSinceVersionSourcePadded":"0000082",
}
`

If you just compare the AssemblySemFileVer 5.1.6.0 and 5.1.6.82 the released files have a smaller version than the commit before. The ordering of FullSemVer is the opposite (which is correct).

Any ideas how to resolve that?
Thanks in advance

**Comment by jbaehr** [comment]
There is #1385 available as solution right now, and an even better solution already implemented but not yet merged in #1433.
