### ISSUE TITLE
Remove Mono dependecy

### ISSUE THREAD

**Issue by RouR** [GitTools/GitVersion#1447]
From this [comment](https://github.com/nuke-build/nuke/issues/104#issuecomment-408683322) - If I want to use GitVersion, Mono must have installed.

I try to use it on Travic CI server ubuntu.14.04-x64 without any dependency to Mono, and it`s fail.

Is it really necessary to use Mono? 
.NET Core 2.0.2 work`s fine on ubuntu.14.04-x64 without any dependency to Mono

**Comment by dazinator** [comment]
The latest beta packages should run under dotnet core sdk <= 2.0.0 now. If you have 2.1.0 installed youll need a global.json file to pin sdk version to 2.0.0 until we merge a Pr that adds support for > 2.0.0

**Comment by dazinator** [comment]
We also have a dotnet core 2.0 based docker image.

**Comment by nlowe** [comment]
@dazinator Assuming you're talking about [gittools/gitversion-dotnetcore:0.0.0-alpha0015](https://hub.docker.com/r/gittools/gitversion-dotnetcore/tags/) (The most recent tag for [gittools/gitversion](https://hub.docker.com/r/gittools/gitversion/tags/) is over a year old) It would appear that image is windows based. Can we get a linux image with the dotnet core version?

**Comment by dazinator** [comment]
@nlowe I don't see why not. Is this something you would consider contributing? The docker files are pretty simple - you can see them here: https://github.com/GitTools/GitVersion/tree/master/src/Docker/

I assume you just want a copy of the dotnetcore one, just using the linux base image right?

**Comment by nlowe** [comment]
Sure. I'd be happy to contribute. Do you want a separate issue to track this, or can I just send in a PR?

**Comment by nlowe** [comment]
So It looks like `microsoft/dotnet:2.0-runtime` has a split tag (it's windows and linux, it depends on what mode you're in when you pull / run / build it). Can we rebuild it in linux mode and push it? I don't think there's an automated process that does that just yet (#1445)

**Comment by dazinator** [comment]
I see. I think there is automation for the docker build and push, check this script: https://github.com/GitTools/GitVersion/blob/master/deploy.cake#L211

Perhaps you could lool at adjusting that in a PR to cater for the linux version?

**Comment by JakeGinnivan** [comment]
Getting the docker images deployed is high on my priority list, because it's what I use because all our build servers are centOS and can't run GitVersion at all

**Comment by JakeGinnivan** [comment]
Will probably sort out on Saturday

**Comment by derwasp** [comment]
@JakeGinnivan if I may, why can't one run GitVersion on CentOS? [libgit2sharp.nativebinaries](https://github.com/libgit2/libgit2sharp.nativebinaries) supports rhel RID.

**Comment by JakeGinnivan** [comment]
I had the issue quite some time ago @derwasp . But it was due to libssl or something from memory. Can try running natively again though!

**Comment by derwasp** [comment]
@JakeGinnivan I built an AWS lambda function, which runs on something very close to [rhel.7.2-x64](https://github.com/aws/aws-extensions-for-dotnet-cli/blob/ad25a4bf9ff84b1cba874e1bff8496a20fdec784/src/Amazon.Lambda.Tools/LambdaConstants.cs#L28) and I am using gitversion lib in there. Works like charm.

**Comment by RouR** [comment]
Has there been any progress made on this?
I use dotnet core sdk 2.1 for now

**Comment by arturcic** [comment]
@RouR could you have a look at the new docker images? you can find them here https://hub.docker.com/r/gittools/gitversion-dotnetcore/tags/

**Comment by RouR** [comment]
I don`t know how to use it directly in my project.
I use "nuke-build", which have dependency to "gitversion".

This [script](https://github.com/RouR/ToDo-ToBuy/blob/dev/.travis.yml#L39) will call [gitversion](https://github.com/RouR/ToDo-ToBuy/blob/dev/build/Versioning.cs#L36) and it will throw this [error](https://travis-ci.org/RouR/ToDo-ToBuy/jobs/440998797#L862) (See [initial issue](https://github.com/nuke-build/nuke/issues/104))

**Comment by arturcic** [comment]
I seems the nuke-build you're using depends on a version of GitVersion that runs on mono only https://github.com/nuke-build/nuke/blob/develop/source/Nuke.GlobalTool/templates/_build.sdk.csproj#L15. There is a PR in progress that adds support for .net core sdk 2.1 and global tools

**Comment by gep13** [comment]
@arturcic Regarding the Global Tool, I noticed this on NuGet.org:

https://www.nuget.org/packages/dotnet-gitversion/

Is that going to cause a problem?  Or what were you thinking about naming the package?

**Comment by arturcic** [comment]
Btw related to that, probably we should consider reviewing the nuget packages IDs by making them shorter and add the GitTools as prefix to avoid confusions with other packages on nuget.org? As far as I can see this is not a global tool, meaning it will not cause issues when running the global tool

**Comment by arturcic** [comment]
probably we need to open an issue regarding the package IDs, and have the discussion there

**Comment by gep13** [comment]
>@arturcic said...
probably we need to open an issue regarding the package IDs, and have the discussion there

Sounds like a good idea to me.

**Comment by asbjornu** [comment]
As #1528 implemented the global tool and #1572 discussed the naming scheme, I feel this issue can be closed. If there's still naming scheme issues to discuss, please open a new issue.
