### ISSUE TITLE
Auto increment pre-release version?

### ISSUE THREAD

**Issue by Spiralis** [GitTools/GitVersion#1450]
Our build-server/script is set up to create NuGet packages and push these to our private development NuGet feed for our release-branch builds. 

The difference is that we do this in a CI way. So, each commit or merge to the release/M.m.p branch should bump the pre-release.

When the branch is created GitVersion names it "1.0.0-beta.1". From this point on I want every commit/merge to bump the pre-release number. Sort of the same as it adding the BuildMetadata counter to the tag-pre-release count. One commit later the version is "1.0.0-beta.2".

This way our feed will have all builds available and our testers can test each of the changes. If it isn't bumped in the pre-release then the package created will have the same name as the previous one and depending on the configuration of the NyGet server it allows overwriting the package or not...

Even if we set the build-server up to do nightly builds for this branch, I would still want this setup. Granted, with more than one commit/merge per day it would skip some pre-release-packages. Which is not how semver wants the packages (not sure if this also regards to pre-release-tags actually). However, these are only internal releases, so skipping versions would be ok anyway.

We would actually prefer this scheme also for our feature branches (also CI), as we easily can get the releases we want from the feed. We have been considering nightly builds here too, but sometimes one want to get a package right after it has a new commit, so...

I have tried to make this work by tuning the configs, but I have been unable to figure this out. Is this possible with GitVersion?

**Comment by jbaehr** [comment]
I think what you want is https://gitversion.readthedocs.io/en/latest/reference/continuous-deployment/
