### ISSUE TITLE
Branch config should merge regexes between default and user-specified

### ISSUE THREAD

**Issue by akshay1992** [GitTools/GitVersion#1456]
Let's assume I decide to configure GitVersion.yml using the getting started wizard and and get fairly simple config file:

    mode: ContinuousDeployment
    branches: {} 
    ignore:
      sha: []

To this, I have added a branch-specific configuration for all branches that match the regex `dev(el)?(op)?(ment)?`:

    mode: ContinuousDeployment
    branches: 
        dev(el)?(op)?(ment)?:
          mode: ContinuousDeployment
          tag: unstable
          increment: Patch
          prevent-increment-of-merged-branch-version: false
          track-merge-target: true
    ignore:
      sha: []

If I run `gitversion.exe /showconfig` I see the following: 

      assembly-versioning-scheme: MajorMinorPatch
      mode: ContinuousDeployment
      tag-prefix: '[vV]'
      continuous-delivery-fallback-tag: ci
      major-version-bump-message: '\+semver:\s?(breaking|major)'
      minor-version-bump-message: '\+semver:\s?(feature|minor)'
      patch-version-bump-message: '\+semver:\s?(fix|patch)'
      legacy-semver-padding: 4
      build-metadata-padding: 4
      commits-since-version-source-padding: 4
      commit-message-incrementing: Enabled
      branches:
        dev(el)?(op)?(ment)?:
          mode: ContinuousDeployment
          tag: unstable
          increment: Patch
          prevent-increment-of-merged-branch-version: false
          track-merge-target: true
        master:
          mode: ContinuousDeployment
          tag: ''
          increment: Patch
          prevent-increment-of-merged-branch-version: true
          track-merge-target: false
        releases?[/-]:
          mode: ContinuousDeployment
          tag: beta
          increment: Patch
          prevent-increment-of-merged-branch-version: true
          track-merge-target: false
        features?[/-]:
          mode: ContinuousDeployment
          tag: useBranchName
          increment: Inherit
          prevent-increment-of-merged-branch-version: false
          track-merge-target: false
        (pull|pull\-requests|pr)[/-]:
          mode: ContinuousDeployment
          tag: PullRequest
          increment: Inherit
          prevent-increment-of-merged-branch-version: false
          tag-number-pattern: '[/-](?<number>\d+)[-/]'
          track-merge-target: false
        hotfix(es)?[/-]:
          mode: ContinuousDeployment
          tag: beta
          increment: Patch
          prevent-increment-of-merged-branch-version: false
          track-merge-target: false
        support[/-]:
          mode: ContinuousDeployment
          tag: ''
          increment: Patch
          prevent-increment-of-merged-branch-version: true
          track-merge-target: false
        dev(elop)?(ment)?$:
          mode: ContinuousDeployment
          tag: unstable
          increment: Minor
          prevent-increment-of-merged-branch-version: false
          track-merge-target: true
      ignore:
        sha: []

I see two different branch configurations, one for `dev(el)?(op)?(ment)?` containing the config from my GitVersion.yml, and another for `dev(elop)?(ment)?$` from the default config. 

Which configuration would take precedence for a branch named say, `akshay-dev`? 

More generally, are the branch-specific configurations intended to be a union of the configs from GitVersion.yml and the default?

**Comment by JakeGinnivan** [comment]
I think this has been fixed in the latest gitversion v4 betas. The regex has moved into a configuration item on the `development` branch config.

It was a mistake to put the regexes as the key, thankfully we fixed before the offical 4.0 release.

**Comment by JakeGinnivan** [comment]
If the above is not the case, let me know!
