### ISSUE TITLE
Why is the Build number overwritten in Azure Dev Ops

### ISSUE THREAD

**Issue by kirkone** [GitTools/GitVersion#1457]
Hi,

I am using the VSTS task to get my nuget packages versioned on build in VSTS ans I was wondering why the "BUILD_BUILDNUMBER" environment variable is being overwritten completely when there is no GitVersion variable in it. I can not see the benefit of this behavior. Did I miss something?

It would be nice to have a name for a build while using GitVersion.

I think here should be a slightly different logic:
https://github.com/GitTools/GitVersion/blob/8b302e164aefc09d50c3465f7cc8eb48b9f0d136/src/GitVersionCore/BuildServers/VsoAgent.cs#L42

Thank you for your help.
KirK

**Comment by kirkone** [comment]
@JakeGinnivan I know it is a long time ago, but what was the intention behind this change?
I found this commit:
https://github.com/GitTools/GitVersion/commit/e98f68b89148e3e0353a5e80d0c3b75ca293c616
but there I can not see why this change had be made.

If someone want his build number to be replaced I think the better solution would be to set his build number to something like `$(GITVERSION_NuGetVersionV2)`

Did I miss something here?

Best regards
KirK

**Comment by paule96** [comment]
any updates @JakeGinnivan?

**Comment by JakeGinnivan** [comment]
Don't remember really, but a wild guess would be that we couldn't detect we were in VSTS, or there were restrictions on updates. I see no reason to change

**Comment by kirkone** [comment]
hi,
there are cases where you don not need the GitVersion string in the name of the build number. I would even claim it's more the exception to have that. The problem is, that changing the `BUILD_BUILDNUMBER` variable also overrides the name of the build itself. This is not a good behavior that a random task renames the build even it has nothing to do with it.

Maybe for better compatibility it is an option to have an parameter like `--skipbuildnumber` or something equal.
I looked into it if I can provide an PR but I did not find the point where to add such a thing.

I hope this explains a bit more why I opened this issue.

**Comment by rodchenkov** [comment]
I have the same problem, any update on this?

**Comment by kirkone** [comment]
@rodchenkov I opend a PR #1770  for this. We will see how this will come out.

**Comment by roryprimrose** [comment]
This probably should be an option to set on the task in the pipeline. Some people won't want the build number to be updated, others will, others will set the build number to a GitVersion variable for which a substitution could happen.

I previously set the BuildNumber to `$(GitVersion_NuGetVersionV2)`. The thing I didn't like about that is the build numbers were meaningless if the build failed before the substitution of the build number happened. Off the top of my head I can't remember if the substitution even happened or whether the Task itself just went over the top of my build number variable hack.

As I prefer a different GitVersion variable to be used in my build numbers, I just overwrite what GitVersion uses to overwrite whatever is defined in the pipeline definition.

**Comment by kirkone** [comment]
This is resolved in #1770 , so I will close this.
