### ISSUE TITLE
GitVersionTask 4.0.0-beta0014 does not work with MSBuild-14.0

### ISSUE THREAD

**Issue by jbaehr** [GitTools/GitVersion#1466]
When I reference the GitVersionTask in version 4.0.0-beta0014 from a csproj I can't build it any more using MSBuild v14. It used to work fine with beta13, but now I get the following error
```
C:\...\packages\GitVersionTask\build\UtilPack.Version.props(1,1): error MSB4041: The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format. [C:\...\Foo.csproj]
```

The issue is quite easy to fix: just add the namespace declaration to `src/GitVersionTask/UtilPack.Version.props`:
```xml
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
....
```

**Comment by dazinator** [comment]
Any chance of a PR?

**Comment by jbaehr** [comment]
@dazinator Any chance of taking care of the PR? (and #1465, too)

**Comment by dazinator** [comment]
@jbaehr  PR merged, sorry for the delay, and thank you for the contribution!

**Comment by dazinator** [comment]
Will have a look next at #1465
