### ISSUE TITLE
Sudden jump in version with 4.0.0-beta0014

### ISSUE THREAD

**Issue by kierenj** [GitTools/GitVersion#1468]
Hi - my config:

https://gist.github.com/kierenj/ccc4a3db7775f97554ef2c11543bca72

I have a freshly-created branch, `release/1.0.19`.  GitVersion awards it `1.1.0-rc.1+777.1` - whereas every time previously we've created a release branch (up to and including `release/1.0.18`), it's correctly done something like  `1.0.18-rc.1+333.1`.

We're not using semver commit messages, and there aren't any tags.

What can I do to diagnose/does this make any sense?

**Comment by dazinator** [comment]
You could try running gitversion.exe with the /diag switch - that should output some more details about the graph which you could paste in a gist, it might help us reason about how its calculating this version.

**Comment by kierenj** [comment]
Ah - it seems it comes down to:

`  INFO [09/07/18 9:02:17:28] Base version used: Merge message 'Merge branch 'build/pin-net-sdk-to-1.1' into develop': 1.1.0 with commit count source 18130611e3339eb41ddd62cc3005b55b98b511f2 (Incremented: None)`

We did indeed merge a branch called `build/pin-net-sdk-to-1.1` that - but given my config, I'm not sure why this would count?

**Comment by dazinator** [comment]
I'm not that familiar with the config myself yet. I don't usually have to delve into it :-)
Does changing this line make a difference: https://gist.github.com/kierenj/ccc4a3db7775f97554ef2c11543bca72#file-gitversion-yml-L12

**Comment by kierenj** [comment]
I'm not sure - but I'd like to keep that if possible. We do use it occassionally?

**Comment by dazinator** [comment]
@kierenj I think GitVersion has the ability to ignore certain SHA's that you think are interfering with version calculation. You could try that - should be mentioned in the docs, you add the SHA's to the config somewhere.

**Comment by tgharold** [comment]
We're getting bit by this bug as well.  We run a forked workflow in Github and one of the developers named their branch 'upgrade-to-package-xyz-4.3.0' which has now confused GitVersion beta 14, while beta 12 would ignore that branch name.

**Comment by konne** [comment]
@kierenj I have the same issue. We use dependabot and now I get strange version numbers.
So the new version of gitversiontask use this for example this number:
Merge message 'Merge pull request #11 from q2g/dependabot/nuget/src/development/NLog-4.5.10

@dazinator this doesn't help: commit-message-incrementing: Disabled
to add for each PR from dependabot and ignore SHA is not an solution
I think we need a possibilibity to exlude Version numbers from PR complete or do define an exclude regex

**Comment by jbaehr** [comment]
@asbjornu: is this issue also fixed by #1541?

**Comment by asbjornu** [comment]
@jbaehr: #1541 ignores branch names of non-release branches, not commit messages. However, it will perhaps also affect commit messages made in ignored branches... I haven't tested. Regarding ignoring commit-messages, #1507 tries to tackle that problem.

**Comment by jbaehr** [comment]
@asbjornu I think this issue is also about branch names. But not about a name of an existing branch, but a branch name reconstructed from a merge commit message:

From https://github.com/GitTools/GitVersion/issues/1468#issuecomment-419357543 
> `INFO [09/07/18 9:02:17:28] Base version used: Merge message 'Merge branch 'build/pin-net-sdk-to-1.1' into develop': 1.1.0 with commit count source 18130611e3339eb41ddd62cc3005b55b98b511f2 (Incremented: None)`

i.e. the faulty "1.1" does not result from a currently existing branch `build/pin-net-sdk-to-1.1`, but a previously existing, merged and removed, one.

**Comment by asbjornu** [comment]
@jbaehr, thanks for the clarification. Then I definitely think #1507 is going to be a possible fix.

**Comment by asbjornu** [comment]
Since #1507 was closed as per https://github.com/GitTools/GitVersion/pull/1507#issuecomment-506308652, I'm closing this as well. Please submit a new PR fixing this problem if it still exists.
