### ISSUE TITLE
Provide NuGet package to allow easier reading of GitVersionInformation

### ISSUE THREAD

**Issue by dhilgarth** [GitTools/GitVersion#1475]
The approach with Reflection to read GitVersionInformation is rather messy, I think. It would be great to have a tiny NuGet package that would provide a more friendly interface to this information.

**Comment by youfoundkris** [comment]
Reflection?

I think in most cases it hands over the version information over to the build server automatically. There is support for all the big ones. Then there is also the ability to get the version output as json, so you may manually retrieve any version part.

It is distributed in various forms including nuget.

What issue are you running into?

**Comment by dhilgarth** [comment]
Thanks for your prompt reply. I am talking about the injected variables by the MSBuild Task: https://gitversion.readthedocs.io/en/latest/usage/msbuild-task/

I want to show some of these variables in my application. The page I just mentioned provides a reflection based approach to getting this data.

**Comment by youfoundkris** [comment]
Yes, the class is internal an therefore requires some reflection which is very clearly explained there.

**Comment by dhilgarth** [comment]
Sure, I understand that.
I am asking for a facade in a NuGet package that makes getting this information friendlier, more accessible.

**Comment by dhilgarth** [comment]
I just wrote the code for it: https://gist.github.com/dhilgarth/2fb710f51d20767ccb1a3c25e4b6e412

I would however love to see this as an official NuGet package from you guys :)

**Comment by dhilgarth** [comment]
I have now put this into its own repository: https://github.com/dhilgarth/ReadGitVersionInformation and published it to NuGet: https://www.nuget.org/packages/ReadGitVersionInformation/1.0.0

Still, would love to move it to your repo, to make it more official.
