### ISSUE TITLE
VSTS Marketplace Task doesn't work in a Linux build agent

### ISSUE THREAD

**Issue by dracan** [GitTools/GitVersion#1476]
Looks like the VSTS build task doesn't work in a "Linux Preview" build agent. I'm using Linux containers, Docker, and AKS - so need to use the Linux build agent. Are there any other options for using GitVersion in VSTS?

Thanks for any help with this - awesome work with GitVersion btw! :)

**Comment by gep13** [comment]
@dracan thanks for raising this.

As you have spotted, the Azure Pipelines (formerly known as VSTS) Task for GitVersion currently only supports Windows Build Agents.

There have been discussions about updating the Task to support more operating systems, and I believe the plan is to finalise the migration to .NET Core/Standard, and from there, update the external tooling to support it, including updating the Task, etc.

**Comment by pascalberger** [comment]
The Azure DevOps task itself should be cross-plattform since #1189 where it was rewritten from using a PowerShell script to using Node scripts. This version is not released on the marketplace yet though.

The other issue is GitVersion itself and its dependencies as @gep13 has pointed out

**Comment by gep13** [comment]
@pascalberger where was that change merged to?

Looking at the current master branch:

https://github.com/GitTools/GitVersion/tree/master/src/GitVersionTfsTask

It is still the PowerShell version.

**Comment by pascalberger** [comment]
@gep13 This uses the node engine: https://github.com/GitTools/GitVersion/blob/master/src/GitVersionTfsTask/task.json#L70_L74

The powershell scripts in there are only for building and packaging the task. 

Or where do you see that it uses PowerShell?

**Comment by gep13** [comment]
Oh, hold on... Sorry, I completely read that wrong.  Ok, move along, nothing to see here 😄

**Comment by pascalberger** [comment]
The script executed by the tasks is this one, which has some OS specific code in here: https://github.com/GitTools/GitVersion/blob/master/src/GitVersionTfsTask/GitVersion.ts#L42-L47

**Comment by dracan** [comment]
Just adding a comment to stop this issue from being closed by the stale bot.

**Comment by evanrobertson** [comment]
Is there any progress or planned progress on this issue?

**Comment by arturcic** [comment]
@evanrobertson can you try the new extension? https://marketplace.visualstudio.com/items?itemName=gittools.usegitversion-preview

**Comment by NightFox7** [comment]
Is there any progress or planned progress on this issue?

**Comment by arturcic** [comment]
@NightFox7 
can you try this one https://marketplace.visualstudio.com/items?itemName=gittools.usegitversion

**Comment by NightFox7** [comment]
I got this error:
```
2020-02-04T13:07:11.1237309Z --------------------------
2020-02-04T13:07:11.1237597Z Installing GitVersion.Tool version 5.x
2020-02-04T13:07:11.1237880Z --------------------------
2020-02-04T13:07:11.1239306Z Found tool in cache: GitVersion.Tool 5.1.3 x64
2020-02-04T13:07:11.1284425Z ##[error]Error: ENOENT: no such file or directory, readlink ''
```

**Comment by NightFox7** [comment]
@arturcic I had to install dotnet core on my linux build agent and now it works. Thanks !

**Comment by arturcic** [comment]
great! Closing this issue

**Comment by Vijay-Nirmal** [comment]
Still getting this error

```
--------------------------
Installing GitVersion.Tool version 5.x
--------------------------
Found tool in cache: GitVersion.Tool 5.2.4 x64
##[error]Error: EINVAL: invalid argument, readlink '/appdata/agent/_work/_tool/dotnet/dotnet'
```

I have installed dotnet core as mentioned by @NightFox7. This is my Build Task to install dotnet core on my linux build agent. I have tried with vertion 3.1.100, 3.0.103, 2.2.203

```yml
- task: UseDotNet@2
  displayName: 'Install .NET Core sdk'
  inputs:
    packageType: sdk
    version: 3.1.100
    installationPath: $(Agent.ToolsDirectory)/dotnet
```
