### ISSUE TITLE
GitVersion Mainline - Version increment on every push

### ISSUE THREAD

**Issue by alpeshv** [GitTools/GitVersion#1478]
This is a question, not an issue.

I am using GitVersion with Mainline mode. With default settings, it increases patch number with every commit in master. Is there a way to increase patch number on every push rather than on every commit?

If I push 3 commits together, patch gets increased by 3. In this case I would get version jump from 2.0.4 to 2.0.7 on VSTS build.

GitVersion.yml

`mode: Mainline`

Note: I have got only one branch, which is 'master' and I will be keep pushing my changes to master directly. I am not looking to use any branching strategy yet.

**Comment by PrestonII** [comment]
try this @alpeshv 

https://stackoverflow.com/a/53270015/1732184
