### ISSUE TITLE
prevent-increment-of-merged-branch-version not working in 4.0.0-beta.14

### ISSUE THREAD

**Issue by konne** [GitTools/GitVersion#1481]
Hi,
can it be that the config flag prevent-increment-of-merged-branch-version: true is not any more working in this beta?
I tested this on version 3.6.2 and this was working fine after I set this to true on my dev branch, but with
the 4.0.0-beta.14 it still uses the Merge Messages

**Comment by konne** [comment]
@dazinator please can you have a look a this issue
thx

**Comment by dazinator** [comment]
@konne sorry I won't have any free time to look at this for you.
I haven't made any changes around this. Perhaps you could see if there is a test in the test suite for this scenario, or add one to show it failing?

**Comment by konne** [comment]
If missunderstod the config but the issue #1468 describes perfect my issue with the newest nugets of gitversiontask. I will close this issue here.
