### ISSUE TITLE
Create Github Release with ReleaseNotes.md

### ISSUE THREAD

**Issue by dazinator** [GitTools/GitVersion#1493]
We should look to automatically create a GitHub release, with generate ReleaseNotes.md file using GitReleaseNotes or similar tool, as part of the build.

I know we would want this for stable builds.
For pre-release builds, it's unclear whether we need this or not. Perhaps there would be no harm to also create pre-releases on GitHub in the same way.

The concencus as per #1445 was to trigger the next stable build by publishing a tag. We should also try and make the build servers (app veyor etc) automatically build when a new tag is published if they don't detect tags already (save having to go and manually trigger them after tagging).

**Comment by arturcic** [comment]
Closed by #1630

**Comment by gep13** [comment]
@arturcic I got an email saying that the build failed for the PR that I merged, but I haven't looked into what went on there.  Any ideas?

**Comment by arturcic** [comment]
Yes, it failed when publishing the windows container to DockerHub, there is a 500 error from docker hub

**Comment by arturcic** [comment]
But some docker images were published as well as nuget/ chocolatey.

**Comment by gep13** [comment]
Gotcha, okay, just wanted to check.
