### ISSUE TITLE
GitVersion 4.0.0 missing at nuget.org

### ISSUE THREAD

**Issue by ermshiperete** [GitTools/GitVersion#1506]
It's great to finally see the 4.0.0 release. :1st_place_medal: 

Could this pleeeease be uploaded to nuget.org? Thanks!

**Comment by ermshiperete** [comment]
Oops, sorry, I looked at GitVersion package at nuget.org which is missing (and probably not needed). GitVersionTask is there.

**Comment by gep13** [comment]
@arturcic can you comment on this?  Is this expected?

If so, should we unlist the previous versions of this package?

**Comment by arturcic** [comment]
Hi there, looks like that was the way before I have re-written the scripts. The package name has changed between beta 13 and beta 14 and here is the commit that did that https://github.com/GitTools/GitVersion/commit/0bf5d63a4f027038534eb89e244025c062546362#diff-4d3634747586b964df9f7712bc3ec669, look at the commit message

**Comment by arturcic** [comment]
I think yes

**Comment by gep13** [comment]
@arturcic ok, let's wait until we get a consensus, and then we can do that work.

Do we have a "list" somewhere, of all the package ID's that we are currently publishing?  Other then looking at the build script?

**Comment by dazinator** [comment]
Should we close this now in favour of #1509 ?

**Comment by arturcic** [comment]
I think yes
