### ISSUE TITLE
GitVersion package IDs review

### ISSUE THREAD

**Issue by arturcic** [GitTools/GitVersion#1509]
As we have already published the v.4.0.0 version on all distribution channels it appears there are some confusions related to which package to use. There are some packages that have gitversion in name and also confuse the consumers.

So I would suggest to review the package ID-s and their purpose, and the ones that are already public to mark as obsolete and point to the new IDs.

Current status:
We have the following nuget packages:

- `GitVersionCore.4.0.0.nupkg` - this is the dll library that contains the logic
- `GitVersion.CommandLine.4.0.0.nupkg` - this is the exe (full framework), il-merged that has dependency on GitVersionCore
- `GitVersion.CommandLine.DotNetCore.4.0.0.nupkg` - this is the dotnet core version of the exe, and it can be run `dotnet GitVersion.dll`, has dependency on GitVersionCore
- `GitVersionTask.4.0.0.nupkg` - this is the msbuild task, has dependency on GitVersionCore
- `GitVersion.Portable.4.0.0.nupkg` - this is the chocolatey package, il-merged, has dependency on GitVersionCore 

- not yet merged, the GitVersion global tool, `GitVersion.CommandLine.DotNetCore.Tool`

Exptected status:

Would be great if we could have meaningful names (probably shorter names), that avoid confusion with other existing packages (not part of gittools organization).  And probably we should prefix the package IDs with `GitTools.`

If we decide changing the IDs we'll have to make obsolete the existing ones and point to the new ones.

@GitTools/developers, we need your feedback.

**Comment by arturcic** [comment]
I'll propose to have these ID changes:
| Old ID                                   	|       	| New ID                           	|
|------------------------------------------	|-------	|----------------------------------	|
| `GitVersionCore`                         	| -&gt; 	| `GitTools.GitVersion.Core`       	|
| `GitVersion.CommandLine`                 	| -&gt; 	| `GitTools.GitVersion`            	|
| `GitVersion.CommandLine.DotNetCore`      	| -&gt; 	| `GitTools.GitVersion.DotNetCore` 	|
| `GitVersionTask`                         	| -&gt; 	| `GitTools.GitVersion.Task`       	|
| `GitVersion.Portable`                    	| -&gt; 	| `GitTools.GitVersion.Portable`   	|
| `GitVersion.CommandLine.DotNetCore.Tool` 	| -&gt; 	| `GitTools.GitVersion.Tool`       	|

**Comment by gep13** [comment]
For what it's worth, I think that this is a good idea.

**Comment by asbjornu** [comment]
I would love a change like this, especially if it was also reflected in the source code.

**Comment by gep13** [comment]
In my mind, the `GitTools` prefix provides the "link" back to this GitHub Organisation.  We have done this recently with Cake.  The main Cake package is just called Cake, but everything else is prefixed with Cake.  It also opens up the open of reserving this prefix on NuGet.org if we choose to go down that route as well.

**Comment by asbjornu** [comment]
Yes, I'm not against it. For Cake it's easy since Cake is the product. As `GitTools` is not a product, it's a bit less obvious what the right choice is, I think.

**Comment by gep13** [comment]
Hmm, good point.  Will have a think about this...
