### ISSUE TITLE
Can not get mainline - at least one tag required in code

### ISSUE THREAD

**Issue by MiroKov** [GitTools/GitVersion#1515]
Does GitVersionTask support .NET3.5 libraries?
I did the same procedure as with the standard libraries,
but when I copied the GitVersion.yaml file, it continued  to increment just the metadata.

Expected behaviour:  **should increment the patch** value.

**Comment by MiroKov** [comment]
Found where the problem was.
In code, I had no tags. Seems that GitVersion requires at least one tag in Code, in order to do the incrementation.

**Comment by MiroKov** [comment]
Feel free to close, if this is a wanted behaviour.

**Comment by gep13** [comment]
@MiroKov I think it is fair to say that this is expected.
