### ISSUE TITLE
Creating a bugfix/ branch configuration which increments patch

### ISSUE THREAD

**Issue by SamMackrill** [GitTools/GitVersion#1516]
I am trying to write a bugfix branch rule that should take its version from source with patch + 1

>    bugfix:
>     mode: ContinuousDeployment
>     tag: useBranchName
>     increment: patch
>     prevent-increment-of-merged-branch-version: false
>     track-merge-target: false
>     regex: bugfix(es)?[/-]
>     source-branches:
>     - develop
>     - feature
>     - hotfix
>     - bugfix
>     tracks-release-branches: false
>     is-release-branch: false
>     is-mainline: false

everything else is at default

I have a branch off develop called bugfix/versionTesting that GitVersion gives  "SemVer":"1.0.3-versionTesting.85",

The version for develop is: "SemVer":"1.2.0-alpha.64",

So I would expect my bugfix version to be 1.2.1-versionTesting.1

My repro looks like this:

![gitversion_deployer](https://user-images.githubusercontent.com/84898/47518028-c3abd800-d881-11e8-84de-4a59e2430d8e.png)

 If I set the increment to "inherit" then I get: "SemVer":"1.2.0-versionTesting.65",

Which is closer

Is this possible to achieve?

**Comment by mregni** [comment]
Where you able to fix this issue? I have the same problem at the moment.

**Comment by Heimo001** [comment]
Is there any solution for this? 

I want to increment patch level for bugfixes on release branches.
This is my config:

branches:
  bugfix:
    mode: ContinuousDelivery
    tag: useBranchName
    increment: Patch
    prevent-increment-of-merged-branch-version: false
    track-merge-target: false
    regex: ^bugfix(es)?[/-]
    source-branches:
    - release
    tracks-release-branches: true
    is-release-branch: false
    is-mainline: false
    pre-release-weight: 30000
