### ISSUE TITLE
VSTS GitVersion Task Icon is Missing in build

### ISSUE THREAD

**Issue by jmzagorski** [GitTools/GitVersion#1517]
First off excellent extension!

Not sure if this had been reported already, or if this is an issue with my azure pipelines, but when trying to add this extension to a new build the icon is missing (see image). My existing builds that use this extension still show the correct icon in the task list. I tried uninstalling and reinstalling the extension, but now all my pipelines that originally had the extension with a valid icon now show the gear as well

![image](https://user-images.githubusercontent.com/8404957/47566477-df52c500-d8f9-11e8-9b5d-17e832610400.png)

**Comment by gep13** [comment]
@arturcic any ideas on what has happened here?

**Comment by arturcic** [comment]
I'll check that

**Comment by arturcic** [comment]
Looks like the task needs an icon as well. We'll wait for #1499 to be merged first.

**Comment by arturcic** [comment]
Closed by 88916367ddde86845ce824aaf5058827859ce4a5
