### ISSUE TITLE
Develop minor version is bumped when merging a feature branch with a major version number

### ISSUE THREAD

**Issue by DOMZE** [GitTools/GitVersion#1519]
Hello,

I have a question on GitVersion. In the scenario shown in the diagram below, how come the minor version is bumped when the feature branch is merged back into develop?

I would expect the version in develop to stay the same as there's no release branches associated with 2.0.0 and no tags in develop with 2.0.0

![flow](https://user-images.githubusercontent.com/8238156/47590277-d8e43d80-d939-11e8-94bd-b4a5fb8f22ab.png)

Does the tool automatically update the minor version on the next commit when it is tracking a release branch (regardless of the version)?

For information this is my GitVersion.yml

`
mode: ContinuousDeployment
branches: {}
ignore:
  sha: []
`

Using GitVersion 4.0.0

Git commands to reproduce the behavior:

git init
gitversion init (selecting, 5,2,0)

git add GitVersion.yml; git commit -m "Initial commit"; git checkout -b develop;
git commit -m "First commit in develop" --allow-empty
git checkout -b release/1.0.0
git commit -m "bugfix in release/1.0.0" --allow-empty
git checkout develop; git checkout -b feature/2.0.0;
git commit -m "first commit in feature/2.0.0" --allow-empty;
git checkout develop
git merge feature/2.0.0 --no-ff

Thank you!

**Comment by gep13** [comment]
@DOMZE I believe the problem here may be down to the usage of the version number in the feature branch.  Can you try the above again without using `feature/2.0.0`.  Perhaps using something like `feature/add-page` or equivalent.  That does that result in?

**Comment by DOMZE** [comment]
@gep13 The idea behind the flow I mentioned was that I was hoping to increase a major version through a feature branch.

If this is not the intended behavior, do you think the tool should be fixed accordingly?

The idea behind was that I was hoping to update the major version through a feature branch, but I understand that one can do that with a commit message (+semver: major)

**Comment by DOMZE** [comment]
Bump

**Comment by DOMZE** [comment]
This has been hanging in for a while. Is this something that may be fixed (ignore versions in feature branch names) or should this issue be closed?

**Comment by asbjornu** [comment]
Didn't #1541 fix this?

**Comment by DOMZE** [comment]
ah cool then didn't see that PR :-) thanks!
