### ISSUE TITLE
Merging from develop to feature branch causes MinorPatch to change

### ISSUE THREAD

**Issue by DOMZE** [GitTools/GitVersion#1525]
Starting with a clean master branch with only a GitVersion.yml config file

The following scenario, after merging develop into feature/featureA causes gitversion (in feature/featureA) to display 1.1.1 as MajorMinorPatch. I would expect it to stay at 1.2.0 or move to 1.3.0 _if_ there's a release branch (release/1.2.0) created

Flow:
![bug](https://user-images.githubusercontent.com/8238156/48227098-69c20c80-e36f-11e8-9549-97fdc72d7071.png)

Git commands to reproduce issue
```
git tag 1.1.0
git checkout -b develop
git commit -m "commit in develop" --allow-empty # 1.2.0-alpha.1
git checkout -b feature/featureA
git commit -m "commit in featureA" --allow-empty # 1.2.0-featureA.2
git commit -m "commit in featureA" --allow-empty # 1.2.0-featureA.3
git checkout develop
git commit -m "commit in develop" --allow-empty # 1.2.0-alpha.2
git commit -m "commit in develop" --allow-empty # 1.2.0-alpha.3
git checkout feature/featureA # 1.2.0-featureA.3
git merge develop --no-ff
```

Using GitVersion 4.0.0 and ContinuousDeployment in all branches

**Comment by DOMZE** [comment]
@arturcic @asbjornu @dazinator @gep13 @pascalberger any thoughts?

**Comment by asbjornu** [comment]
@DOMZE: How does your `GitVersion.yml` file look like?

**Comment by DOMZE** [comment]
@asbjornu as follow:

```
mode: ContinuousDeployment
branches: {}
ignore:
  sha: []
```

**Comment by dazinator** [comment]
My assumptions are inline with DOMZE but I could easily be missing something. Would be good to examine what test cases we have around this, and add a few to verify the behaviour we expect!

**Comment by asbjornu** [comment]
@DOMZE: Are you able to write a test that provokes this problem and submit it as a PR?

**Comment by DOMZE** [comment]
@asbjornu @dazinator Please see PR https://github.com/GitTools/GitVersion/pull/1533 for the demonstration of this bug.
The test fails

**Comment by DOMZE** [comment]
@asbjornu any updates, especially on PR #1526 as this is a blocker for us for our CI pipeline

**Comment by jbaehr** [comment]
Some months ago we also provided a demonstration for what I believe is the very same problem: #1446. We still see this from time to time, but not always. I have repos where merging develop into a feature works four times and the fifths shows this problem (without any releases or tagging in between).

**Comment by ruhullahshah** [comment]
I have added a fix for this issue, that is waiting to get merged
https://github.com/GitTools/GitVersion/pull/1446

**Comment by asbjornu** [comment]
Since #1446 is merged, I suppose this can be closed.
