### ISSUE TITLE
Using GitVersion without git

### ISSUE THREAD

**Issue by jawn** [GitTools/GitVersion#1530]
Given 
* TFS 2017 Update 1 server
* Team Foundation Version Control (TFVC), so no git repo.

Reading the docs on [updateassemblyinfo](https://gitversion.readthedocs.io/en/latest/usage/command-line/) it seems I should be able to set the *InformationalVersion* to anything and use `GitVersion.exe /updateassemblyinfo` to update my AssemblyInfo files.

Is that assumption correct and safe to make?

Disclaimer or why I would consider abusing GitVersion for this:  it's actively maintained and popular. Alternatives (a number of extensions on the TFS/Azure DevOps marketplace that focus on AssemblyInfo updating alone) are either not kept up to date, have many open issues/PRs or concerning issue reports.

**Comment by roryprimrose** [comment]
@jawn Have a look at using a PowerShell task instead to update your AssemblyInfo files. See https://www.neovolve.com/2017/06/08/tfvc-build-versioning/ for an example.

**Comment by jawn** [comment]
Sounds like a godo idea.
