### ISSUE TITLE
Issues with normalization

### ISSUE THREAD

**Issue by tpluscode** [GitTools/GitVersion#1535]
I have recently noticed on several projects that GitVersion fails with the `GitTools.Git.BugException: GitTools.Core has a bug, your HEAD has moved after repo normalisation.` message.

The output of [this build](https://ci.appveyor.com/project/tpluscode/dotnetrdf/builds/20378090#L332) caught my attention. Notice that first you see a successfully output and then the error. This is because I run GitVersion twice through cake. First time to get the variables in script and second time to set CI environment:

```
Task("GitVersion")
     .Does(() => {
         version = GitVersion(new GitVersionSettings {
             UpdateAssemblyInfo = true,
         });

         if (BuildSystem.IsLocalBuild == false) 
         {
             GitVersion(new GitVersionSettings {
                 OutputType = GitVersionOutput.BuildServer
             });
         }
     });
```

I wonder why the second execution actually performs any calculation. Shouldn't it it simply get the same value from cache?

Also, I found this to happen on AppVeyor and Jenkins. This never happens locally, using the same script.

**Comment by mycroes** [comment]
> Also, I found this to happen on AppVeyor and Jenkins. This never happens locally, using the same script.

Repo normalization only happens when a buildserver is detected. On Jenkins you can use `set JENKINS_URL=&& <build command>` to bypass detection, which will let it skip normalization as well.
