### ISSUE TITLE
Add support for Azure Repos pull requests messages

### ISSUE THREAD

**Issue by janpieterz** [GitTools/GitVersion#1543]
Been struggling for a while to get the Pull Request merge versions right. Either Azure Repos/VSTS changed something or we did it manually for a while, overriding the default.

I just tested and the default message is:
`Merge pull request 443 from hotfix/2.17.7 into master`.

It'd be great if someone could confirm the above is indeed the default message for them as well (couldn't find any docs).

If this'd be appreciated I'd be very happy to shoot in a pull request for it.

**Comment by godzillar** [comment]
This is what our Azure devops merge message looks like:
**Merged PR 1234: A custom PR title**

What I do when creating a release is actually changing the title to the merge message GitVersion expect, as in: **Merge branch 'release/1.0'**. This way the git message is detected by GitVersion. 

It would be great if GitVersion would just look for the branch name **release/1.0** when the pull request is merged with master branch.

**Comment by janpieterz** [comment]
Confirmed the `Merged PR X: Y` flow here too, not sure where `Merge pull request` came from.
