### ISSUE TITLE
GitVersionTask changes component resource identifiers

### ISSUE THREAD

**Issue by DanielKuehner** [GitTools/GitVersion#1545]
### In Short
I have recently updated from `v4.0.0-beta0012` to `v4.0.0`. Because of #1465 my application does not start anymore. The problem is that the `AssemblyVersion` gets added to URIs in the generated C# files and at start it tries to initialize the resources twice - which results in this error:

```
System.Windows.Markup.XamlParseException
  HResult=0x80131501
  Message=Zeilennummer "4" und Zeilenposition "21" von "Beim Festlegen der Eigenschaft "System.Windows.ResourceDictionary.DeferrableContent" wurde eine Ausnahme ausgelöst.".
  Source=PresentationFramework
  StackTrace:
   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at MyApp.App.InitializeComponent() in D:\...\MyApp\src\MyApp\App.xaml:line 1

Inner Exception 1:
InvalidOperationException: Die ResourceDictionary-Instanz kann nicht erneut initialisiert werden.
```

### Possible Solutions
For the moment I can image these solutions:
1. Go back to an older GitVersion version
2. Version hundrets of URIs in my code and update them with every new version
3. Revert #1472 in my local code
4. Add a switch to enable or disable adding the version to the URI

The 3rd solution is my current workaround. I would really appreciate the 4th solution.

**Comment by jbaehr** [comment]
@DanielKuehner there is already a switch (`UpdateVersionProperties`) to tell GitVersion not to set the version properties in msbuild, see https://github.com/GitTools/GitVersion/blob/master/src/GitVersionTask/NugetAssets/build/functionality/GitVersionBuild.targets#L77
Please note however that the property "AssemblyVersion" is used in many places through the build process, Microsoft.WinFx.targets being only one of them. And GitVersion is not the only candidate setting it, too...

Anyway, can you please elaborate *why* having the version number in the URI causes your resource to get initialized twice? I've never heard of such a problem and it may has another root cause.
Maybe it's the *format* of your assembly version? Over at Nerdbank.GitVersioning there has been a similar issue when not following the four-integer-convention: https://github.com/AArnott/Nerdbank.GitVersioning/issues/26

**Comment by DanielKuehner** [comment]
@jbaehr first of all I am not that firm with the MSBuild build process or even with others than C#/WPF like you. I really understand your needs and no matter if this was a bug or not, it was really frustrating to update and run into such a breaking change for me. But thanks for the hint with the existing switch - it worked for me, so I can continue with the original sources of GitVersion 👍 

I hope the german exception was not the problem for you (`InvalidOperationException: Cannot re-initialize ResourceDictionary instance`) - but because of this exception, your ticket, some guessing with the background of the code and the confirmation of a workmate, it seams to me that it tries to load the `ResourceDictionary` a second time.
No, we have a correct 4-digit assembly version format because of GitVersions `GitVersionTaskAssemblyInfo.g.cs`:
```
[assembly: AssemblyFileVersion("18.2.0.0")]
[assembly: AssemblyVersion("18.2.0.0")]
[assembly: AssemblyInformationalVersion("18.2.0-alpha.123+Branch.develop.Sha.1234567890")]
```

I will give you some code snippets. We use no version within the URIs when we reference our own files, e.g. `App.xaml`:
```
<Application x:Class="MyApp.App"
             xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">
    <Application.Resources>
        <ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>
                <ResourceDictionary Source="/MyApp.UserControls;component/Resources/CommonResourceDictionary.xaml" />
                <ResourceDictionary Source="/MyApp.Core;component/Views/Resources/CommonResourceDictionary.xaml" />
            </ResourceDictionary.MergedDictionaries>
        </ResourceDictionary>
    </Application.Resources>
</Application>
```

The URIs within the generated `*.g.cs` files with `v4.0.0-beta0012` were like this one:
```
System.Uri resourceLocater = new System.Uri("/MyApp;component/app.xaml", System.UriKind.Relative);
```
and with `v4.0.0`:
```
System.Uri resourceLocater = new System.Uri("/MyApp;V18.2.0.0;component/app.xaml", System.UriKind.Relative);
```

After I saw this I came up with the idea that the files get loaded one time without a version and a second time with a version. Or do you see another problem behind this?

**Comment by PatrickKursawe** [comment]
This behavior is also a problem when using SmartAssembly for postprocessing. You don't notice anything during the build, but you get runtime errors because some resources from merged assemblies can't be found. Took me a day to trace this back to the GitVersionTask update.

**Comment by jbaehr** [comment]
@DanielKuehner, @PatrickKursawe, WPF makes is really hard to share resources in a safe way... The price to pay for the highly dynamic nature of XAML/WPF. Fortunately, there is a recipe for doing so, if you need it: https://alexfeinberg.wordpress.com/2015/08/16/safely-export-wpf-resources/  
(If you don't need that safety/compleity, as your project is simple enough, lucky you. You may just turn of GitVersion's setting of the respective MSBuild Properties as mentioned in my first comment)

The key is the usage of `XmlnsDefinitionAttribute`. To quote from it's documentation (emphasis by me):
  - a XAML processor searches each *referenced assembly* for [XmlnsDefinitionAttribute](https://docs.microsoft.com/en-us/dotnet/api/system.windows.markup.xmlnsdefinitionattribute) applications
  - the XAML processor uses the [ClrNamespace](https://docs.microsoft.com/en-us/dotnet/api/system.windows.markup.xmlnsdefinitionattribute.clrnamespace) and [AssemblyName](https://docs.microsoft.com/en-us/dotnet/api/system.windows.markup.xmlnsdefinitionattribute.assemblyname) stored in the [XmlnsDefinitionAttribute](https://docs.microsoft.com/en-us/dotnet/api/system.windows.markup.xmlnsdefinitionattribute) for type resolution against types *in the assembly*
  - If the assembly name is not set in the attribute itself, then you [i.e.: the consumer if the attribute, aka the XAML processor] should determine the information based on *the assembly that the attribute is applied to*

That means you don't have to specify the version information in *every* XAML reference to the resource dictionary (via managed resource/pack-URI in "Source='...' or via namespace "clr-namespace:...;assembly=...") but only reference the assembly in the csproj. However, the responsibility of finding the correct types is still in the hands of the XAML processor, not in the CLR. (This would have required a reference the resource *in code* in every *consuming* project. That may had also solved the issue but is cumbersome.) The way with linking XML namespaces to CLR namespaces for specific assemblies offers a very elegant way to doing this at the *providers* side.

**Comment by DanielKuehner** [comment]
@jbaehr I cannot proceed with this because I do not have access to the code anymore.
@PatrickKursawe Can you please take over?

**Comment by PatrickKursawe** [comment]
@DanielKuehner The 
`  <PropertyGroup>
    <UpdateVersionProperties>false</UpdateVersionProperties>
	<UpdateAssemblyInfo>true</UpdateAssemblyInfo>
  </PropertyGroup>`
in the .csproj fixed the issue for me, so I'm not sure how I could take over.

**Comment by DanielKuehner** [comment]
@PatrickKursawe great to hear. Then I will delegate it to a former colleague.
