### ISSUE TITLE
Latest doc about usage of class GitVersionInformation is old

### ISSUE THREAD

**Issue by DanielKuehner** [GitTools/GitVersion#1546]
Refering to [MSBuild Task - Other injected Variables](https://gitversion.readthedocs.io/en/latest/usage/msbuild-task/#other-injected-variables)

In the current version `v4.0.0` (while I came from `v4.0.0-beta0012`) the class `GitVersionInformation` moved out of the `AssemblyName` namespace while the class also moved from the file `GitVersionTaskAssemblyInfo.g.cs` to the new file `GitVersionInformation.g.cs`.

So the correct call would be:
```
var gitVersionInformationType = assembly.GetType("GitVersionInformation");
```

**Comment by Gwynnbleid1** [comment]
I can confirm that above solution fixes the problem.

**Comment by larsk2009** [comment]
I can also confirm this fixed the problem for me. Maybe this should be changed in the doc as it has apparently been over a year since this change?
