### ISSUE TITLE
How to configure GitVersion when using GitVersionTask

### ISSUE THREAD

**Issue by NArnott** [GitTools/GitVersion#1558]
How do I run command line tools, such as `init` when using the GitVersionTask nuget package? This doesn't provide a GetVersion.exe to run against, and I can't find any documentation for this case.

My test project is a simple dot net standard class library that I want to try GitVersion on, and it builds with the task nuget package just fine. I now want to configure how versioning works, but I can't figure out how to run `init`.

**Comment by joaosantana** [comment]
You need to install GitVersion.portable package from Chocolatey and run it against your repository. See https://gitversion.readthedocs.io/en/latest/usage/command-line/
