### ISSUE TITLE
Please support homebrew 3.6.5 for compatibility

### ISSUE THREAD

**Issue by ltvan** [GitTools/GitVersion#1560]
We have many repos which is using v3 configuration. Now they are broken with v4. But on the new build machine, I cannot install gitversion 3.6.5.

**Comment by Shereef** [comment]
Install-Package GitVersionTask -Version 3.6.5

**Comment by gep13** [comment]
@ltvan between v3 and v4, there are breaking changes in the way that GitVersion works.  As a result, it is highly unlikely that v4 will support v3 configuration going forward.  If you "need" to use that configuration, I would suggest pinning to using GitVersion v3 in your builds.

**Comment by Shereef** [comment]
@GeertvanHorrik Sorry about that, My mistake, I wasn't aware homebrew = Mac

**Comment by Shereef** [comment]
@ltvan Sorry about that, My mistake, I wasn't aware homebrew = Mac

**Comment by ltvan** [comment]
> @ltvan between v3 and v4, there are breaking changes in the way that GitVersion works. As a result, it is highly unlikely that v4 will support v3 configuration going forward. If you "need" to use that configuration, I would suggest pinning to using GitVersion v3 in your builds.

Yeah, I have many repos so I cannot migrate them all at once. So that's why I need to install v3 on my new build machine but homebrew only has v4. I cannot install older version using homebrew. I suggest that you should keep v3 on homebrew (like adding gitversion@3).

**Comment by gep13** [comment]
@ltvan did you try the following:

```
brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/8e1966b3d4d06641e91e4d40192e0e3532a3a397/Formula/gitversion.rb
```

**Comment by gep13** [comment]
@ltvan sorry, I am unfamiliar with that error message.

**Comment by ltvan** [comment]
@gep13 it seems that due to this part:

```
    (bin/"gitversion").write <<-EOS.undent
```

I updated as same as the latest version to a local file and it works:

```
    (bin/"gitversion").write <<~EOS
```

**Comment by gep13** [comment]
>@ltvan said...
I will consider pull request later, or somebody can do that.

If you could, that would be great.
