### ISSUE TITLE
GitVersion.exe is misspelled as GiVersion.exe

### ISSUE THREAD

**Issue by iosgitr** [GitTools/GitVersion#1562]
https://github.com/GitTools/GitVersion/blob/e2148e056520c25941843a399fe29cc97b7b3407/src/GitVersionTfsTask/GitVersionTask/task.json#L63

**Comment by arturcic** [comment]
A PR is welcomed

**Comment by arturcic** [comment]
Fixed in 043e4d88e39cc5978a798b14d7b93e2e947968d9
