### ISSUE TITLE
[Question] Pre-release tag version in hotfix and custom branches.

### ISSUE THREAD

**Issue by Dobriy33** [GitTools/GitVersion#1569]
Hello.
[Documentation ](https://gitversion.readthedocs.io/en/latest/git-branching-strategies/gitflow/)says that hotfix branch contains commits count in pre-release tag:
> pre-release: beta{n} where n = number of commits on branch ('0' padded to 4 characters)

But commits on branch passes to metadata variable and prerelease contains counter by tags in hotfix..
Example:
We have hotfix/0.2.1 branch. Version is 0.2.1-beta.1+0
After two commits to hotfix we have version 0.2.1.-beta.1+2, but expected 0.2.1-beta.2 (commits count = 2).
Why we need to create tag in the branch to pin the version? (see [pic ](https://gitversion.readthedocs.io/en/latest/git-branching-strategies/img/f26ae57adbd9b74f74c4_hotfix.png)from docs)

Following [semver](https://semver.org/#spec-item-10) NuGet will ignore build metadata, and prohibit to add a package with the same version.
I think if we make a package we need to increment pre-release tag instead of build metadata because source code is changed with new commit.

Custom branches should follow the same logic.

**Comment by asbjornu** [comment]
Which version of GitVersion are you using?

**Comment by Dobriy33** [comment]
It reproduces in the latest version of GitVersion.

**Comment by Dobriy33** [comment]
> 
> 
> Which version of GitVersion are you using?
