### ISSUE TITLE
Increment version number when local changes are detected

### ISSUE THREAD

**Issue by casz** [GitTools/GitVersion#1570]
Checking out a project that produces nuget packages on build with GitVersionTask where master branch's latest commit is tagged with 2.0.0. It would be nice to increment the patch number when local changes are detected.

Or when you create a feature branch from master that is still tagged with 2.0.0 it should bump the minor version when local changes are detected.

**Comment by marcusl** [comment]
+1 for me. Will think about creating PR for this.

**Comment by casz** [comment]
We solved it MSBuild.Tasks nuget package with a build target that adds VersionSuffix

```
<Target Name="NugetCreator_BeforeCreateNuspecChangesAndOutput"
          BeforeTargets="GenerateNuspec"
          AfterTargets="GetVersion"
          Condition="'$(GetVersion)' != '' and '$(DisableNugetCreatorForThisSolution)' != 'true'">
    <PropertyGroup>
      <VersionSuffix Condition="'$(CIBuild)' != 'true'">local$([System.DateTime]::Now.ToString(yyyyMMddHHmmss))</VersionSuffix>
      <PackageVersion Condition="'$(CIBuild)' != 'true'">$(VersionPrefix)-$(VersionSuffix)</PackageVersion>
    </PropertyGroup>
</target>
```

**Comment by asbjornu** [comment]
It would be awesome if you, @marcusl or @casz, could submit a PR that fixes this.

**Comment by casz** [comment]
Actually I'd like to get back to this!

**Comment by casz** [comment]
@marcusl @julianbartel see #2069

**Comment by casz** [comment]
Should be handled outside of GitVersion.
