### ISSUE TITLE
Use latest Tags as base version on Release Branches -- Request Release Flow support

### ISSUE THREAD

**Issue by stoopered** [GitTools/GitVersion#1576]
My branching strategy is like this:

(Azure DevOps)
Tag is at 1.2
Master >branch to users/username/workitem
|
|
PR Into Master (now at 1.2.3 increments with Mainline so every commit) and Cherry Pick change into release/release-1.1

I want release 1.1 to build to 1.1.XXX in this case 1.1.15. I have tried it so that NextVersion is 1.1.15 but it keeps picking up 1.2 as the base version. I need to overwrite that version, but cant do it via Commit Message because it will get picked up in the Master.

I have spent a long time trying to figure this out, but I am stuck. And it is best practice to always go into master before cherry picking to release. Never go from Release to master.

I have posted a better explanation below.

**Comment by marius-stanescu** [comment]
I don't know how to answer your question, but can you post the configuration you're using? I want to try it.

**Comment by stoopered** [comment]
My question is the same as yours 1577.

I have a Release branch, and I am merging changes into it, but it picks up the Version of Master and increments it.

I have played around with many configs, and have yet to get any to work. I have also tried to Set Next version by modifying the yml during the pull request but that does not work. 

assembly-versioning-scheme: MajorMinorPatch
mode: Mainline
branches:
  release:
    mode: ContinuousDelivery
    increment: Patch
    prevent-increment-of-merged-branch-version: true
    track-merge-target: false
    regex: releases?[/-]
    tracks-release-branches: false
    is-release-branch: true
ignore:
  sha: []

**Comment by stoopered** [comment]
This is what I am wanting.
![releaseflow](https://user-images.githubusercontent.com/14861898/52664197-03004200-2ece-11e9-9813-61e45467aa92.jpg)

**Comment by stoopered** [comment]
I tried to work around it by adding a 1.2.3 tag to release, but when the cherry pick occurs, it picks up the 1.3 version.

**Comment by stoopered** [comment]
Still hoping that GitVersion will eventually support release flow. It is a much simpler way of branching and is being used by Microsofts own Azure DevOps team.

https://docs.microsoft.com/en-us/azure/devops/learn/devops-at-microsoft/release-flow

**Comment by stoopered** [comment]
For anyone having the same issue, if you use the anti-pattern of doing a hotfix from the release branch, then release flow will work
