### ISSUE TITLE
No "latest" tagged docker image?

### ISSUE THREAD

**Issue by matthewgonzalez** [GitTools/GitVersion#1602]
Running into some issues with system dependence on the `gittools/gitversion:latest` tagged docker image.

Error received when trying to pull image:
```
Unable to find image 'gittools/gitversion:latest' locally
docker: Error response from daemon: manifest for gittools/gitversion:latest not found.
```

**Comment by arturcic** [comment]
it is related to #1572. Migrating from 2 repositories into gittools/gitversion repository. I'll update you when the migration is done

**Comment by arturcic** [comment]
Please use `gittools/gitversion:latest-windows` or `gittools/gitversion:latest-linux` as this are the tags that we'll be using

**Comment by matthewgonzalez** [comment]
When one tries to pull using the default command (i.e. `docker pull gittools/gitversion`), it tries to pull the `latest` tagged image.

I am thinking this decision will have negative consequences for others.

**Comment by arturcic** [comment]
I will manually tag the latest-windows and latest-linux as latest only for now, on next release it will be updated to the new version as part of the changes I did in that PR

**Comment by arturcic** [comment]
I have pushed a gittools/gitversion:latest image.
