### ISSUE TITLE
GitVersion cannot find remote master or develop from inherited branch config

### ISSUE THREAD

**Issue by tvoyle** [GitTools/GitVersion#1606]
The most recent beta release changes the default branch regexes in a way that prevents them from matching remote branches if GitVersion can't find the parent.  

https://github.com/GitTools/GitVersion/blob/14b736584840bae5878b565e7d92caea6afc6c7d/src/GitVersionCore/BranchConfigurationCalculator.cs#L130

The use of Branch.FriendlyName with the default master regex of ^master$ means that it will never match a remote branch.

see also
https://github.com/GitTools/GitVersion/pull/1410

**Comment by asbjornu** [comment]
@tvoyle: Thanks for the bug report and suggested fix. I've submitted #1613 that hopefully should fix the problem.
