### ISSUE TITLE
Add VersionSourceSha to output

### ISSUE THREAD

**Issue by hayhay27** [GitTools/GitVersion#1607]
I think this can be useful.
On dev branch we use commits between BaseSha and Sha to collect issues from comments and setup fix version in jira.

This should be simple because MetaDataCalculator already contains base commit info. 
I can make pull request.

**Comment by asbjornu** [comment]
By `BaseSha`, do you mean the SHA corresponding to the "version source", i.e. the commit GitVersion has found to use as its base for calculating the version number?

**Comment by hayhay27** [comment]
Yes, I mean `baseVersionSource.Sha`.
Perhaps `BaseSha` is not the best name. Maybe `BaseVersionSourceSha`, `PreviousVersionSha`, etc.

**Comment by asbjornu** [comment]
I think `VersionSourceSha` is terse, unambiguous and goes well with the already existing `CommitsSinceVersionSource`. Are you up for implementing that in a PR, @hayhay27?

**Comment by hayhay27** [comment]
Good. I'll make PR soon.
