### ISSUE TITLE
Fallback String with {env:BUILD_NUMBER ?? somestring} expression not working

### ISSUE THREAD

**Issue by tknerr** [GitTools/GitVersion#1626]
Following the [docs about `assembly-file-versioning-format`](https://gitversion.readthedocs.io/en/latest/configuration/#assembly-file-versioning-format) we should be able to provide a fallback string if the given env var is not set.

Without a fallback string this behaves correctly:

```yaml
assembly-informational-format: '{FullSemver}.Build.{env:BUILD_NUMBER}.Sha.{Sha}'
```
...and produces:
```
$ BUILD_NUMBER=123 gitversion -showvariable InformationalVersion
0.1.0-alpha.1+1964.Build.123.Sha.a83a90e4785eb281f4dab36a21f7b39f8ef02b9b
```

However, when a fallback string is provided, it would completely ignore the `$BUILD_NUMBER` and always output the fallback string:

```yaml
assembly-informational-format: '{FullSemver}.Build.{env:BUILD_NUMBER ?? local}.Sha.{Sha}'
```
incorrectly produces:
```
$ BUILD_NUMBER=123 gitversion -showvariable InformationalVersion
0.1.0-alpha.1+1964.Build.local.Sha.a83a90e4785eb281f4dab36a21f7b39f8ef02b9b
```

This is
```
$ gitversion -version
4.0.0+Branch.master.Sha.e715eb5dd515037d90a257f527e62442cae8c1c5
```

**Comment by ruhullahshah** [comment]
Hi @tknerr 

Assuming that you are using the version that supports this feature, I tried out the scenario you mentioned with `GitVersion-4.0.0` and it works as expected. The problem in your case might be that `GitVersion` is reading the value of `InformationalVersion` from the `cache`. Could you please run `GitVersion.exe /nocache` and check if the `BUILD_NUMBER` and `local` are picked up in the respective scenarios.

**Comment by tknerr** [comment]
Hi @ruhullahshah 

Thanks for the hint, using `-nocache` indeed does the trick:

```
$ BUILD_NUMBER=123 gitversion -showvariable InformationalVersion
1.3.0+3.Branch.master.Build.local.Sha.2e073b3323305a12407348feba18cc5da38e52c1
 
$ BUILD_NUMBER=123 gitversion -showvariable InformationalVersion -nocache
1.3.0+3.Branch.master.Build.123.Sha.2e073b3323305a12407348feba18cc5da38e52c1
```

Not sure if this is expected in this case, but `-nocache` provides a valid workaround / solution for me

I'm fine with closing the issue, but leave it up to you

**Comment by ruhullahshah** [comment]
This is the expected behavior. GitVersion always picks up the values from the cache(if available), by default and in order to override this behavior, one has to use `nocache`

**Comment by ruhullahshah** [comment]
@tknerr Also, I am OK with closing this issue.
