### ISSUE TITLE
Bad branch version detection

### ISSUE THREAD

**Issue by tatouft** [GitTools/GitVersion#1629]
Hello,

I have had a branch named "hotfix/SDIS-211-1080p-29.97hz-not-supported" and since all versions are detected to be 29.97.1
But this is not a branch version, this is just the description of a defect.
The branch has been deleted but I think gitverion still find it in the merge pull request commit message.
I have had new manual tags since, but still, this is the version that gitversion choose.
I cannot get rid of this problem. It's too late to amend the merge pull request message.

The only workaround I found is to tag manually before the call to gitversion, which is not a viable solution.

I don't need gitversion to detect a version number in the branch names. Is it possible to disable?

Thank in advance.

P.S. I use gitversion 4.0.0

**Comment by tatouft** [comment]
For people who could have the same problem, I had not thought about this solution but just had to ignore the merge commit containing the bad branch name in the GitVersion.yml:
branches: {}
ignore:
  sha: [3bed00e44c5]

**Comment by arturcic** [comment]
So you found a solution by ignoring in the `GitVersion.yml`. I'll close it
