### ISSUE TITLE
assembly-informational-format empty fallback string

### ISSUE THREAD

**Issue by savornicesei** [GitTools/GitVersion#1649]
Hi all,

In GitVersion.yml I have set 
`assembly-informational-format: 'Product_name {Major}.{Minor}.{Patch}.{env:INTEGRATOR ?? some_string }{Sha}'`

In my scenario, I would like some_string to be empty if env:INTEGRATOR does not exist but it seems it's not parsed correctly. I have tried doubling the single quotes, with double quotes, ~, null but it still fails to parse it correctly.

This is how it looks if I pass double single quotes:
`"InformationalVersion":"Product_name 1.2.0.{env:INTEGRATOR ?? '' }acb6133",`

Thank you.

**Comment by koppor** [comment]
Similar issue here. I tried

    assembly-versioning-format: '{major}.{minor}.{buildmetadata ?? patch}'

because of

   "BuildMetaData":"",

but it fails to parse

```
Unable to format AssemblyVersioningFormat.  Check your format string: 'buildmetadata ?? patch' is not a member of type 'GitVersion.SemanticVersionFormatValues' (Parameter 'propertyOrFieldName')::error::SyntaxError: Unexpected token I in JSON at position 0
```
