### ISSUE TITLE
Any way to bump based on previous tag and increment rule only?

### ISSUE THREAD

**Issue by mariusGundersen** [GitTools/GitVersion#1667]
I'm struggling to get GitVersion to work the way I wish it would. All I want it to do is bump the version based on the previous git tag it found and the increment rules in the yaml file. For example:

```
o < master
|
o
|
o < v0.1.0
```

Given the above git log and a GitVersion.yml file containing only `increment: Minor` I would expect it to set the new version to be `v0.2.0`, but instead I get `v0.1.1`. 

Is there no way to make it work this way?

**Comment by tpaxatb** [comment]
Since the branch name "master" matches the default regex pattern ("^master$") for the branch master, you need to override the increment for that.
branch:
   master:
     increment: Minor

The global setting is the fallback setting for branches that don't match any patterns defined (INCLUDING the built-in default ones).

**Comment by tpaxatb** [comment]
And I'm not sure and can't test right now, but you MAY be able to set the mode to "mainline" as well so you'd have a yml of
mode: Mainline
increment: Minor

**Comment by mariusGundersen** [comment]
What are the default rules? Are they documented anywhere? Is there any way to reset them?
