### ISSUE TITLE
GITLAB using depreacted varaibles

### ISSUE THREAD

**Issue by joewashear007** [GitTools/GitVersion#1669]
In the source for the GitLab task, the environment variabke it uses to get the current branch is using an depreacted varaible, See: https://github.com/GitTools/GitVersion/blob/master/src/GitVersionCore/BuildServers/GitLabCi.cs#L40

Here is the depreaction and update notice: https://docs.gitlab.com/ee/ci/variables/deprecated_variables.html#gitlab-90-renamed-variables.

Thank for the good work.!

**Comment by zionyx** [comment]
Hi @joewashear007, how about an open pull request that addresses this issue for the project, on behalf of all its grateful user base? 😄

**Comment by arturcic** [comment]
Closed by #1741
