### ISSUE TITLE
Documentation needed for WiX Toolset MsBuild integration

### ISSUE THREAD

**Issue by tpaxatb** [GitTools/GitVersion#1681]
MsBuild projects can now support version information via `$(var.GitVersion_*)` variables, need to document their names and usage.

**Comment by gep13** [comment]
I am going to remove the stale label from this issue, as I believe it is still relevant, and there has been at least one request for it to be included.

@tpaxatb would you be in a position to provide some docs for this usage?

**Comment by asbjornu** [comment]
Could you please take a look at this, @tpaxatb?
