### ISSUE TITLE
Question - Are there known implementation methods for Gradle?

### ISSUE THREAD

**Issue by andreasbisiach** [GitTools/GitVersion#1682]
Hello,

I would like to integrate GitVersion inside Gradle build scripts.
Are there known wrappers/implementation that work inside Gradle?

**Comment by arturcic** [comment]
As far as I know in Gradle you can call a script or command https://docs.gradle.org/current/dsl/org.gradle.api.tasks.Exec.html. You can install the GitVersion global tool from [nuget](https://www.nuget.org/packages/GitVersion.Tool) call it from Gradle, but that means you need to install the dotnet core [runtime](https://dotnet.microsoft.com/download/dotnet-core/2.2).

Or you can invoke docker to generate the json file with Git information you can consume from [dockerhub](https://hub.docker.com/r/gittools/gitversion/)

**Comment by andreasbisiach** [comment]
> As far as I know in Gradle you can call a script or command https://docs.gradle.org/current/dsl/org.gradle.api.tasks.Exec.html. You can install the GitVersion global tool from [nuget](https://www.nuget.org/packages/GitVersion.Tool) call it from Gradle, but that means you need to install the dotnet core [runtime](https://dotnet.microsoft.com/download/dotnet-core/2.2).

Thanks a lot, it works fine. I will work on build a plug in based on Exec

**Comment by andreasbisiach** [comment]
I have created a first version of a gradle plugin that acts as wrapper for GitVersion (that has to be installed and in the path)

https://plugins.gradle.org/plugin/com.bisiach.gradle.gitversion-plugin

**Comment by arturcic** [comment]
That looks awesome!! Thanks a lot for the effort. Would be great if you could add a document about the wrapper here https://github.com/GitTools/GitVersion/tree/master/docs/usage. Thank you again!

**Comment by andreasbisiach** [comment]
I would not mind doing that but I am by no mean a skilled plug-in developer and I would prefer some validation/test of the plug-in.
