### ISSUE TITLE
[?] How release  schem version control ?

### ISSUE THREAD

**Issue by ProSerg** [GitTools/GitVersion#1684]
Hello! I try to release the next version control many times, but I don't understand how gitversion works.

Could you help me? 

There three type branches.
Name .   | Scheme version 
-------   | ----------------
feature   |  {major}.{minor}.{patch}-{branchName}.{idx}
develop  | {major}.{minor}.{patch}-dev.{idx}
master . | {major}.{minor}.{patch}

idx - increment +1 for every commit
About master:
minor - increment +1 for every Merge/ PullReqeust 
patch - increment +1 for every commit

Does gitVersion support these opportunities? 
If not How I can increment patch? not clear how I can up patch version.

I found only one way it adds a tag. But I don't like to add a tag for every PR and calculate new patch number . I hope gitVersion can do it.

Thanks!

**Comment by asbjornu** [comment]
Try changing [`mode`](https://gitversion.readthedocs.io/en/latest/reference/versioning-mode/) in the [configuration](https://gitversion.readthedocs.io/en/latest/reference/versioning-mode/) to `ContinuousDeployment` for the branches you want to increment on every commit.
