### ISSUE TITLE
Should ignore refs/head part of the branch name

### ISSUE THREAD

**Issue by aateeque** [GitTools/GitVersion#1687]
In TeamCity (v9.1.7) we use the variable `%%vcsroot.branch%` which is available by default _(side note: GitVersion should probably use this instead of requiring custom `%env.Git_Branch%`) which reports the branch name with the `refs/heads` prefix. GitVersion doesn't recognise branch name patterns like __release/2.0.0__ as bump indicators whereas it should. In this example in TeamCity you would get a version of the form: __blah.1.0.0.realease-refs-heads whereas running it locally it will report _(correctly)_: __blah.2.0.0__

**Comment by asbjornu** [comment]
This all sounds reasonable. A pull request fixing the issue with GitVersion not recognizing `refs/heads/release/2.0.0` as a release branch as well as using `%vcsroot.branch%` instead of requiring `env.Git_Branch`, with tests and updated documentation, would be accepted and merged.
