### ISSUE TITLE
PreReleaseNumber is string instead of integere in new repository

### ISSUE THREAD

**Issue by andreasbisiach** [GitTools/GitVersion#1688]
Hello,

during some test for a gradle wrapper plugin I have encountered a scenario where PreReleaseNumber returns a "" string instead of an integer.

To reproduce:

```
mkdir testrepo
cd testrepo
git init
touch somefile
git add .
git commit -m "added somefile"
gitversion

```

the output shows
"PreReleaseNumber":""

I would expect 0

**Comment by asbjornu** [comment]
`PrereleaseNumber` will always be an empty string on stable builds (on `master`) since it's set to `null`. As you can see from the source code, all version variables are of the type `string`:

https://github.com/GitTools/GitVersion/blob/master/src/GitVersionCore/OutputVariables/VersionVariables.cs#L78-L106

**Comment by andreasbisiach** [comment]
Sorry, I am a bit confused (and excuse my lack of knowledge in this matter),

when I run gitversion, the json output for several values is represented as number and not string (i.e Major, Minor, Patch).
The problem with PreReleaseNumber is that when empty it outputs an empty string, when not empty (like the following example), it outputs a number.

Since the code you link to shows that internally are all represented as string, how comes that the output of gitversion is number for some of them? And I would consider a bug the fact that  PreReleaseNumber changes from string to number (as output)


`Andreass-MacBook-Pro:testrepo andreas$ gitversion
{
  "Major":1,
  "Minor":1,
  "Patch":0,
  "PreReleaseTag":"alpha.1",
  "PreReleaseTagWithDash":"-alpha.1",
  "PreReleaseLabel":"alpha",
  "PreReleaseNumber":1,
  "BuildMetaData":"",
  "BuildMetaDataPadded":"",
  "FullBuildMetaData":"Branch.develop.Sha.312857aec2a85eb8b213fa9b2f078396cb1b0478",
  "MajorMinorPatch":"1.1.0",
  "SemVer":"1.1.0-alpha.1",
  "LegacySemVer":"1.1.0-alpha1",
  "LegacySemVerPadded":"1.1.0-alpha0001",
  "AssemblySemVer":"1.1.0.0",
  "AssemblySemFileVer":"1.1.0.0",
  "FullSemVer":"1.1.0-alpha.1",
  "InformationalVersion":"1.1.0-alpha.1+Branch.develop.Sha.312857aec2a85eb8b213fa9b2f078396cb1b0478",
  "BranchName":"develop",
  "Sha":"312857aec2a85eb8b213fa9b2f078396cb1b0478",
  "ShortSha":"312857a",
  "NuGetVersionV2":"1.1.0-alpha0001",
  "NuGetVersion":"1.1.0-alpha0001",
  "NuGetPreReleaseTagV2":"alpha0001",
  "NuGetPreReleaseTag":"alpha0001",
  "CommitsSinceVersionSource":1,
  "CommitsSinceVersionSourcePadded":"0001",
  "CommitDate":"2019-03-19"
}`

**Comment by asbjornu** [comment]
I can't recollect or I simply don't know why the variables are serialized to integer when they have a value. You would have to plow through the source code to figure it out – that's what I would have to do as well to give you an answer.
