### ISSUE TITLE
GitVersion.Tool does not populate environment variables in Azure Pipeline

### ISSUE THREAD

**Issue by alex-zyl** [GitTools/GitVersion#1695]
When installing GitVersion.Tool from script task and executing, output variables are not populated into environment variables.

STR: 
1. Create PS script task to install GitVersion.Tool 
```
dotnet tool install GitVersion.Tool --tool-path $(Build.BinariesDirectory)/tools --version=5.0.0-beta3-4 --ignore-failed-sources
```

2. Run GitVersion
```
$(Build.BinariesDirectory)/tools/dotnet-gitversion.exe /output buildserver /nofetch
```

Expected results:
GitVersion environment variables created

Actual results:
No environment variables created

**Comment by mweinand** [comment]
I was experiencing the same thing but I had the `dotnet-gitversion /output builderserver` in the same task as trying to use the variables.  Putting the `dotnet-gitversion /output builderserver` in its own task makes the variables available in later tasks.

**Comment by kirkone** [comment]
Hi,

I use this to get the variables for later use:
https://github.com/kirkone/KK.DotNet.BackgroundTasks.Scheduled/blob/master/pipelines/tools/Run-GitVersion.ps1

The main reason why I use this is because of the `dotnet-gitversion /output builderserver` command also overrides the name of the build.

maybe this is useful

**Comment by asbjornu** [comment]
@alex-zyl, IIRC, it is pretty common across all build servers that the build variables are not made available in the current "scope" (build step, process, task, etc.), but for the subsequent ones. As @mweinand writes, try separating the place you run GitVersion from the place you're using its variables and it should work. This should probably be clarified in the documentation. A PR for that would be highly appreciated.
