### ISSUE TITLE
Pre-release tag is not referring to git tag on subsequent commits 

### ISSUE THREAD

**Issue by Kiran1207** [GitTools/GitVersion#1699]
GitVersion is considering the git tag **only** for that particular commit. 
When there is a subsequent commit, GitVersion considers just the _major.minor.patch_ from the tag. Pre-release is computed based on the branch name and commit count and not continuing from the git tag.

For instance, consider the GitVersions generated below 
Commit 1 : 0.1.45-test-branch0215
Commit 2 : 0.1.45-test-branch0216
git tag 0.1.50-test-new01 : 0.1.45-test-new0001
commit 3:  0.1.45-test-branch0001
commit 4: 0.1.45-test-branch0002

But expectation is to get 0.1.45-test-new0002 on a commit after git tag

We are using GitVersion on **ContinuousDeployment** mode.
The purpose we are attempting to achieve is to generate unique GitVersion upon squashing all the commits to a single commit on a branch. Could you suggest how to achieve this behaviour please.

**Comment by asbjornu** [comment]
Since with squashing all commits usually end up in the `master` branch, the mode you're having here is `Mainline` more than `ContinuousDeployment`. Can you see whether `mode: Mainline` supports your use-case better?
