### ISSUE TITLE
InheritBranchConfiguration use a weak master regex

### ISSUE THREAD

**Issue by jdombier** [GitTools/GitVersion#1705]
In the function InheritBranchConfiguration from BranchConfigurationCalculator.cs, when runing this code

```c#
var developBranchRegex = config.Branches[ConfigurationProvider.DevelopBranchKey].Regex;
var masterBranchRegex = config.Branches[ConfigurationProvider.MasterBranchKey].Regex;

var chosenBranch = repository.Branches.FirstOrDefault(b => Regex.IsMatch(b.FriendlyName, developBranchRegex, RegexOptions.IgnoreCase) || Regex.IsMatch(b.FriendlyName, masterBranchRegex, RegexOptions.IgnoreCase));
```

The regex for master is very weak (`master`) and match any branch that contains master in it's name.  It happens for us whit this branch `feature/xyz-1234-merge-from-master`.

Due to this, gitversion is stuck in an infinite loop `InheritBranchConfiguration`, `GetBranchConfiguration`, `InheritBranchConfiguration`, `GetBranchConfiguration`, ...

We prevent this by forcing us to not use master or dev/develop/development/devment in our branch names, but is there a way to fix this weakness?

Thanks,
Jeremy

**Comment by jdombier** [comment]
It's also seem strange to not use the MasterBranchRegex from the same class as the MasterBranchKey

**Comment by mchippingtonderrick-afl** [comment]
I assuming that this is the same branch regex as in the config?
If so, you should be able to change the regex expression for master to `^master$` to exactly match `master` and nothing else.
