### ISSUE TITLE
DotNetCliToolReference NuGet package?

### ISSUE THREAD

**Issue by wjrogers** [GitTools/GitVersion#1707]
I would like to use GitVersion as a command-line tool as the first step of my CI process, to set the build number and provide a consistent source of version information for all subsequent steps. There is a .NET Core Global Tool package called [GitVersion.Tool](https://www.nuget.org/packages/GitVersion.Tool), but that requires that I a) manually install it on the build agent and b) use the same version for all build configurations because it's a global tool.

Could you please offer a package that provides a `DotNetCliToolReference` so that I can use e.g. `dotnet gitversion` on the project file to guarantee the availability of the desired release of GitVersion in a clean build environment?

**Comment by arturcic** [comment]
I'm not sure we have the time to implement DotNetCliToolReference version. As alternative you could use the GitVersionTask package - it has msbuild tasks, or wait for the local tools implementation when .net core 3.0 support will be added in later versions.

**Comment by wjrogers** [comment]
I am using GitVersionTask already -- does it provide an MSBuild target I
can use to simulate the GitVersion CLI; i.e., compute the version and get
the build server output without actually compiling the project?

**Comment by wjrogers** [comment]
I was able to get the outcome I wanted using the GitVersionTask package (version 5.0.0-beta5.9) by running the MSBuild target `WriteVersionInfoToBuildLog` as a TeamCity build step. Thanks!
