### ISSUE TITLE
"GitVersion for Bamboo" is no longer supported.

### ISSUE THREAD

**Issue by GrayPockets** [GitTools/GitVersion#1710]
The "GitVersion for Bamboo" app is no longer supported, and has been officially archived.

/docs/build-server-support/build-server/bamboo.md

Clicking the download link leads you to the archive: https://marketplace.atlassian.com/plugins/com.carolynvs.gitversion

Links to this app should be removed from the documentation.

**Comment by arturcic** [comment]
Closed by #1711
