### ISSUE TITLE
Mainline: Starting new release branch from develop results in unexpected version increment

### ISSUE THREAD

**Issue by NightOwl888** [GitTools/GitVersion#1728]
This is my first crack at GitFlow, so I am trying to follow [the docs](https://nvie.com/posts/a-successful-git-branching-model/) as much as I can. So, I am not sure if this is a bug with GitVersion or something I am doing wrong.

Here is the scenario:

1. master at version 1.2.152 (tagged)
2. `git checkout -b develop master` -> results in build of version `1.3.0-alpha.1` (as expected)
3. New commit added to develop -> results in build of version `1.3.0-alpha.2` (as expected)
4. `git checkout -b release-1.3 develop` -> results in build of version `1.3.1-beta.2` **(expected `1.3.0-beta.1`)**
5. New commit added to release-1.3 -> results in build of version `1.3.1-beta.3` (as expected)

Do note, my plan is to **only tag stable prereleases and releases (after the release)**, so no other tags than on the master branch have been used during this simple scenario. There are also no commits tagged with `+semver:`.

I have tried the following release branch formats, but always get the version number `1.3.0-beta.1`

```
release/v1.3
release/1.3
release/1.3.0
release-1.3.0
release-1.3
```

### GitVersion.yml
```
mode: Mainline
assembly-versioning-scheme: Major # Use strong-named assembly version format always (even when not strong naming)
assembly-informational-format: '{NuGetVersion}.Branch.{BranchName}.Sha.{ShortSha}'
branches: {}
ignore:
  sha: []
```

I have read #695, but that only seems to have applied when `alpha` was named `unstable`. Now that it is `alpha`, I would expect the version incrementing to be correct.

Why is the release branch not calculating the expected version number in this case?

**Comment by asbjornu** [comment]
If you are using GitFlow, why have you declared that you use `mode: Mainline`? Just removing `mode: Mainline` should make GitVersion behave more predictable when you're using GitFlow.

**Comment by NightOwl888** [comment]
Basically, I started by following [this post](http://loudandabrasive.com/effective-nuget-versioning-in-azure-devops), which is using Mainline mode. From what I gather from the docs, that is supposed to be the mode to use if making NuGet packages. Is that correct?

**Comment by asbjornu** [comment]
Which `mode` you use depends on which flow you use for development. If you use any sort of [trunk-based development](https://trunkbaseddevelopment.com/), you tell GitVersion that by setting [`mode`](https://gitversion.readthedocs.io/en/latest/reference/versioning-mode/) to [`Mainline`](https://gitversion.readthedocs.io/en/latest/reference/mainline-development/). If you're using [GitFlow](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow) as your development flow in Git, you can just use GitVersion's default `mode` which is [`ContinuousDelivery`](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow).
