### ISSUE TITLE
'GitVersion init' doesn't take any input

### ISSUE THREAD

**Issue by sp4rc** [GitTools/GitVersion#1736]
I have justed installed the following two packages into empty template project targeting .Net 4.7. 

- GitVersion.CommandLine (4.0.0)
- GitVersionTask (4.0.0)

When I run `GitVersion init` from the `Package Manager Console` it nicely prints this prompt: 

> PM> gitversion init
> INFO [07/09/19 8:52:51:86] Working directory: C:\Dev\Repos\Template
> INFO [07/09/19 8:52:51:88] IsDynamicGitRepository: False
> INFO [07/09/19 8:52:51:90] Returning Project Root from DotGitDirectory: C:\Dev\Repos\Template\.git - C:\Dev\Repos\Template
> GitVersion init will guide you through setting GitVersion up to work for you
> 
> Which would you like to change?
> 
> 0) Save changes and exit
> 1) Exit without saving
> 2) Run getting started wizard
> 3) Set next version number
> 4) Branch specific configuration
> 5) Branch Increment mode (per commit/after tag) (Current: )
> 6) Assembly versioning scheme (Current: )
> 7) Setup build scripts

However I am not able to give any numbers as input to the PowerShell script. It seems just stuck. 

I am running the latest version of Visual Studio 2017 Enterprise, which currently is  15.9.13, together with git version `2.17.1.windows.2`

When I run `GitVersion diag` the following shows up: 

> PM> gitversion diag
> WARN [07/09/19 9:02:31:99] The working directory 'diag' does not exist.
> INFO [07/09/19 9:02:32:01] IsDynamicGitRepository: False
> ERROR [07/09/19 9:02:32:03] An unexpected error occurred:
> System.IO.DirectoryNotFoundException: Can't find the .git directory in diag
>    at GitVersion.GitPreparer.GetDotGitDirectory()
>    at GitVersion.GitPreparer.GetProjectRootDirectory()
>    at GitVersion.ConfigurationProvider.Verify(GitPreparer gitPreparer, IFileSystem fileSystem)
>    at GitVersion.Program.VerifyArgumentsAndRun()
> INFO [07/09/19 9:02:32:03] 
> INFO [07/09/19 9:02:32:03] Attempting to show the current git graph (please include in issue): 
> INFO [07/09/19 9:02:32:03] Showing max of 100 commits
> ERROR [07/09/19 9:02:32:04] Couldn't dump the git graph due to the following error: System.ComponentModel.Win32Exception (0x80004005): The directory name is invalid
>    at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
>    at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
>    at GitTools.ProcessHelper.Start(ProcessStartInfo startInfo)
>    at GitTools.ProcessHelper.Run(Action`1 output, Action`1 errorOutput, TextReader input, String exe, String args, String workingDirectory, KeyValuePair`2[] environmentalVariables)
>    at GitTools.LibGitExtensions.DumpGraph(String workingDirectory, Action`1 writer, Nullable`1 maxCommits)
>    at GitVersion.Program.VerifyArgumentsAndRun()
> PM> pwd
> 
> Path                 
> ----                 
> C:\Dev\Repos\Template
> 
> 
> PM> dir .\.git
> 
> 
>     Directory: C:\Dev\Repos\Template\.git
> 
> 
> Mode                LastWriteTime         Length Name                                                                                                                                                
> ----                -------------         ------ ----                                                                                                                                                
> d-----       09.07.2019     08:47                gitversion_cache                                                                                                                                    
> d-----       28.06.2019     11:02                hooks                                                                                                                                               
> d-----       28.06.2019     11:02                info                                                                                                                                                
> d-----       28.06.2019     11:02                logs                                                                                                                                                
> d-----       08.07.2019     18:01                objects                                                                                                                                             
> d-----       28.06.2019     11:02                refs                                                                                                                                                
> -a----       08.07.2019     18:01             12 COMMIT_EDITMSG                                                                                                                                      
> -a----       28.06.2019     11:02            341 config                                                                                                                                              
> -a----       28.06.2019     11:02             73 description                                                                                                                                         
> -a----       08.07.2019     15:39            140 FETCH_HEAD                                                                                                                                          
> -a----       28.06.2019     11:02             23 HEAD                                                                                                                                                
> -a----       08.07.2019     18:01           1600 index                                                                                                                                               
> -a----       09.07.2019     08:41            150 ms-persist.xml                                                                                                                                      
> -a----       08.07.2019     15:39             41 ORIG_HEAD                                                                                                                                           
> -a----       28.06.2019     11:02            114 packed-refs

**Comment by sp4rc** [comment]
Na, missed the forward slash... so please find again here the shortened output of `GitVersion /diag`

> PM> gitversion /diag
> INFO [07/09/19 9:05:13:29] Dumping commit graph: 
> INFO [07/09/19 9:05:13:47] * 42f0fec 15 hours ago  (HEAD -> master, origin/master, origin/HEAD)
> * 117626b 16 hours ago  (tag: v1.2.3.4)
> [...]
> * b5b01be 11 days ago 
> 
> INFO [07/09/19 9:05:13:47] Working directory: C:\Dev\Repos\Template
> INFO [07/09/19 9:05:13:47] IsDynamicGitRepository: False
> INFO [07/09/19 9:05:13:49] Returning Project Root from DotGitDirectory: C:\Dev\Repos\Template\.git - C:\Dev\Repos\Template
> INFO [07/09/19 9:05:13:49] Running on Windows.
> INFO [07/09/19 9:05:13:50] IsDynamicGitRepository: False
> INFO [07/09/19 9:05:13:50] Returning Project Root from DotGitDirectory: C:\Dev\Repos\Template\.git - C:\Dev\Repos\Template
> INFO [07/09/19 9:05:13:50] Project root is: C:\Dev\Repos\Template
> INFO [07/09/19 9:05:13:50] DotGit directory is: C:\Dev\Repos\Template\.git
> INFO [07/09/19 9:05:13:51] IsDynamicGitRepository: False
> INFO [07/09/19 9:05:13:51] Returning Project Root from DotGitDirectory: C:\Dev\Repos\Template\.git - C:\Dev\Repos\Template
> INFO [07/09/19 9:05:13:55] IsDynamicGitRepository: False
> INFO [07/09/19 9:05:13:55] Returning Project Root from DotGitDirectory: C:\Dev\Repos\Template\.git - C:\Dev\Repos\Template
> INFO [07/09/19 9:05:13:57] Using latest commit on specified branch
> INFO [07/09/19 9:05:13:59] Running against branch: master (42f0fec90ac7147a6cf89aee8f441fe674e98dd3)
> INFO [07/09/19 9:05:13:60] Begin: Calculating base versions
>   INFO [07/09/19 9:05:13:64] Fallback base version: 0.1.0 with commit count source b5b01bed1b36f17088c9de73a626e5972fdd176f (Incremented: None)
>   INFO [07/09/19 9:05:13:76] Git tag 'v1.2.3.4': 1.2.3+4 with commit count source 117626be95940a02ce34227ff49f715944d0a674 (Incremented: 1.2.4)
>   INFO [07/09/19 9:05:13:78] Git tag 'v1.2.2.0': 1.2.2+0 with commit count source f097aedf5e304e02b15a9e50a3dbafe0cb5591c7 (Incremented: 1.2.3)
>   INFO [07/09/19 9:05:13:80] Found multiple base versions which will produce the same SemVer (1.2.4), taking oldest source for commit counting (Git tag 'v1.2.3.4')
>   INFO [07/09/19 9:05:13:81] Base version used: Git tag 'v1.2.3.4': 1.2.3+4 with commit count source 117626be95940a02ce34227ff49f715944d0a674 (Incremented: 1.2.4)
> INFO [07/09/19 9:05:13:81] End: Calculating base versions (Took: 210.47ms)
> INFO [07/09/19 9:05:13:83] 1 commits found between 117626be95940a02ce34227ff49f715944d0a674 and 42f0fec90ac7147a6cf89aee8f441fe674e98dd3

**Comment by phatcher** [comment]
I have the same issue with 5.0.1

**Comment by asbjornu** [comment]
I have no idea where to even begin investigating this problem.

**Comment by phatcher** [comment]
I'm going to downgrade my local install to 4.x tomorrow to see if I can isolate it a bit more.

**Comment by demaree** [comment]
Just run into the same issue, I was using Powershell ISE. I switched to run powershell as admin and it worked for me. Hope this helps someone.
