### ISSUE TITLE
branch version creator

### ISSUE THREAD

**Issue by 387119** [GitTools/GitVersion#1742]
get versions from branches work well for next branch name format "release/4.3.2", "release/4.3", but it doesn`t work for "release/4", on my understanding it should take this number  as major version with 0.0 for minor.patch, can it be updated? looks like only regex needs to be updated 

[root@test-gy-vm0 GitVersionCore]# cat SemanticVersion.cs | grep "new Regex" -C 2
        public static SemanticVersion Empty = new SemanticVersion();

        static Regex ParseSemVer = new Regex(
            @"^(?<SemVer>(?<Major>\d+)(\.(?<Minor>\d+))(\.(?<Patch>\d+))?)(\.(?<FourthPart>\d+))?(-(?<Tag>[^\+]*))?(\+(?<BuildMetaData>.*))?$",
            RegexOptions.Compiled);

**Comment by raulplanas** [comment]
Question also on versioning from branch name that could be related. My build team has set the Release branch schema to be Release_<version> where I know most use either release/<version> or release-<version>. I was able to modify the GitVersion.yml to use the regex for recognizing Release branches and can see that from the pre-release tag it applies. However it does not recognize the version # from branch name when I use this format. Is there a way to indicate how version # should be parsed from branch name?
