### ISSUE TITLE
Documentation is not a source of truth

### ISSUE THREAD

**Issue by triccaj** [GitTools/GitVersion#1749]
Hi,

I'm doing my best to get GitVersion working in our Azure DevOps build pipeline, and frankly, I cannot work out from your documentation exactly what I should be doing.

I have tried merely adding the NuGet package to the project, which works beautifully locally, however the version variable is not exposed in the Azure build agent.

I have tried using the build pipeline task as the first task in the agent task list, and this still doesn't output the build number. It also fails with error code 1, after outputting a lot of info around branches etc into the log (will attach).

Is there any way for the documentation to be revised so that, based on the information written, I can actually get this tool working?

If there is anything I can do to aid in this, I'm happy to contribute, but right now, I'm not sure my knowledge is worth writing down.

**Comment by triccaj** [comment]
[GitVersion AzureDevOpsBuild Error.txt](https://github.com/GitTools/GitVersion/files/3406527/GitVersion.AzureDevOpsBuild.Error.txt)

**Comment by asbjornu** [comment]
I think you need to pay attention to what this log line says:

```
  INFO [07/18/19 12:28:13:21] Skipping fetching, if GitVersion does not calculate your version as expected you might need to allow fetching or use dynamic repositories
```

Your repository might be a shallow clone or one where not all branches are fetched. GitVersion requires the full repository history and at least the `master` (and for `ContinuousDevelopment`, even `develop`) branch to calculate a version number.

**Comment by triccaj** [comment]
Thanks for getting back so quickly.

The Azure DevOps GitVersion Task has no way, as far as I can see, to remove the /nofetch flag from the command. Like, it appears I can add more flags, but I cannot remove that one.

You're correct though, we only fetch 10 commits. I'll try removing the commit limit and see if that resolves it.

Nonetheless, I feel the spirit of this issue stands - the documentation is great compared to a number of open source packages I have used, so commendations to all involved, but unfortunately at times no documentation can be better than documentation that's out of date.

**Comment by asbjornu** [comment]
Try doing a `git fetch --unshallow` before GitVersion is run and see if that helps. You might have to explicitly fetch the `master` and `develop` branches (as well as creating local tracking branches of them) too in order for GitVersion to work properly. It's unfortunate that this is necessary, but that's just the way it is.

If you get this to work and have ideas for how to improve the documentation in this area, please submit a PR.

**Comment by triccaj** [comment]
Hhmm. So this is executing in a Hosted Agent, so it's less than ideal to need to do this every time. I may look into having a reserved agent so the IO is reduced, but that's my problem ha!

Yea I think tbh the whole TFS blah needs to just go you can't even buy that product anymore.

Anywho - it's been executing for a very long time so this is promising.

As an aside and whilst I have you - is there anything I can do to speed this up? I get the impression it's going to do all of these checks every single build?

**Comment by asbjornu** [comment]
Executing GitVersion itself shouldn't take long, although there's reports of it being very slow for some repositories. We have yet to get our hands on a public repository that exposes this problem, though, so it's been impossible for us to hunt down. The act of doing a full `git clone` compared to a shallow one will of course have a performance impact.

**Comment by GrimGadget** [comment]
Did you ever have any success with this?

At this point (using GitHub repositories and Azure DevOps pipelines), I'm thinking that just manually maintaining the versions in my projects is a simpler solution than trying to guess at how to get stuff working right in GitVersion and guess at what the propery names are for the different calculated values.

**Comment by triccaj** [comment]
Hi,

Apologies for the delay Google hid this in another folder!

We gave up, and are now manually managing the version in our config files
:(.

It would appear this doesn't respect the tag when running in Azure as I
gave my branch a tag and it still sat there for like 1.5 hours processing
all our old branches.

Joe
