### ISSUE TITLE
is source available for images?

### ISSUE THREAD

**Issue by WallStProg** [GitTools/GitVersion#1750]
I really like the approach of using sequence diagrams to illustrate branching strategies in git, and would like to crib some of the examples to create my own.

However, I only see the png files checked in -- presumably those were generated from some other files using a tool (PlantUML?).  It would be very helpful to get access to source for the png files.

Thanks!

**Comment by asbjornu** [comment]
I'm not sure where the diagrams were created, but the source is unfortunately not available afaik. It would indeed be great if we instead of just PNG had the source in something like PlantUML or [Mermaid](https://mermaidjs.github.io/).

**Comment by JakeGinnivan** [comment]
Looks like they are generated from https://github.com/GitTools/GitVersion/commit/3f6bc9e8a01a7bc206bbaf0271f19bf07808a916#diff-1ed45f23563b9ded3375f75776a23896

**Comment by JakeGinnivan** [comment]
// @WallStProg

**Comment by WallStProg** [comment]
Thanks Jake!  I was hoping for a template of some kind that I could use, but such is life...

**Comment by JakeGinnivan** [comment]
If you run those tests, the plant Uml gets printed in the test output. You can then just paste that into something like the plant text website to generate the image
________________________________

**Comment by WallStProg** [comment]
Thanks again Jake.  As I'm on mac, running tests presents some difficulties ;-) If you happen to run across the text output, pls forward (or better yet push to repo).
