### ISSUE TITLE
gitversion and gitversion /diag produces different semver results

### ISSUE THREAD

**Issue by Crono1981** [GitTools/GitVersion#1760]
Running v5.0.0 through dotnet tool.

I'm having an issue in which the tool doesn't calculate the appropriate version number. So I'm trying to run the following to get more details on what is going on:

```
dotnet-gitversion -diag
```

Oddly enough though, according to the output, the correct version is calculated.

```console
INFO [08/02/19 10:44:34:66] Working directory: C:\mydir
INFO [08/02/19 10:44:34:66] IsDynamicGitRepository: False
INFO [08/02/19 10:44:34:67] Returning Project Root from DotGitDirectory: C:\mydir\.git - C:\mydir
INFO [08/02/19 10:44:34:68] Running on Windows.
INFO [08/02/19 10:44:34:68] IsDynamicGitRepository: False
INFO [08/02/19 10:44:34:68] Returning Project Root from DotGitDirectory: C:\mydir\.git - C:\mydir
INFO [08/02/19 10:44:34:68] Project root is: C:\mydir
INFO [08/02/19 10:44:34:68] DotGit directory is: C:\mydir\.git
INFO [08/02/19 10:44:34:69] IsDynamicGitRepository: False
INFO [08/02/19 10:44:34:69] Returning Project Root from DotGitDirectory: C:\mydir\.git - C:\mydir
INFO [08/02/19 10:44:34:72] IsDynamicGitRepository: False
INFO [08/02/19 10:44:34:72] Returning Project Root from DotGitDirectory: C:\mydir\.git - C:\mydir
INFO [08/02/19 10:44:34:74] Using latest commit on specified branch
INFO [08/02/19 10:44:34:77] Running against branch: develop (26a94e2396ad1f9b80f6b24e9140c4bc8b49d544)
INFO [08/02/19 10:44:34:78] Begin: Calculating base versions
  INFO [08/02/19 10:44:34:79] Fallback base version: 0.1.0 with commit count source 12c8a6272d37ef7645d8c17b843245e936403289 (Incremented: None)
  INFO [08/02/19 10:44:34:86] Git tag '0.4.0-alpha.8': 0.4.0-alpha.8 with commit count source 462423889a7edb569a8cd4b675866685cff8e098 (Incremented: 0.4.0-alpha.9)
  INFO [08/02/19 10:44:34:87] Git tag '0.4.0-alpha.7': 0.4.0-alpha.7 with commit count source 3270ef18a6a9bfdc62989a18ccafdecef54bb909 (Incremented: 0.4.0-alpha.8)
  INFO [08/02/19 10:44:34:88] Git tag '0.4.0-alpha.2': 0.4.0-alpha.2 with commit count source 8bca055c145ed896460917fa39dd49145fd0f6f3 (Incremented: 0.4.0-alpha.3)
  INFO [08/02/19 10:44:34:89] Git tag '0.4.0-alpha.6': 0.4.0-alpha.6 with commit count source 8bca055c145ed896460917fa39dd49145fd0f6f3 (Incremented: 0.4.0-alpha.7)
  INFO [08/02/19 10:44:34:90] Git tag '0.4.0-alpha.5': 0.4.0-alpha.5 with commit count source 622abd66fa646067c736657cc3495b8a14acc6f6 (Incremented: 0.4.0-alpha.6)
  INFO [08/02/19 10:44:34:92] Git tag '0.1.0-alpha.25': 0.1.0-alpha.25 with commit count source 122c021124f57b9a13f414cba04351ac1bad3ff8 (Incremented: 0.1.0-alpha.26)
  INFO [08/02/19 10:44:34:93] Git tag '0.4.0-alpha.0': 0.4.0-alpha.0 with commit count source 122c021124f57b9a13f414cba04351ac1bad3ff8 (Incremented: 0.4.0-alpha.1)
  INFO [08/02/19 10:44:35:00] Git tag '0.1.0-alpha.25': 0.1.0-alpha.25 with commit count source 122c021124f57b9a13f414cba04351ac1bad3ff8 (Incremented: 0.1.0-alpha.26)
  INFO [08/02/19 10:44:35:01] Git tag '0.4.0-alpha.0': 0.4.0-alpha.0 with commit count source 122c021124f57b9a13f414cba04351ac1bad3ff8 (Incremented: 0.4.0-alpha.1)
  INFO [08/02/19 10:44:35:02] Found multiple base versions which will produce the same SemVer (0.4.0-alpha.9), taking oldest source for commit counting (Git tag '0.4.0-alpha.8')
  INFO [08/02/19 10:44:35:03] Base version used: Git tag '0.4.0-alpha.8': 0.4.0-alpha.8 with commit count source 462423889a7edb569a8cd4b675866685cff8e098 (Incremented: 0.4.0-alpha.9)
  INFO [08/02/19 10:44:35:03] End: Calculating base versions (Took: 250.88ms)
  INFO [08/02/19 10:44:35:03] 2 commits found between 462423889a7edb569a8cd4b675866685cff8e098 and 26a94e2396ad1f9b80f6b24e9140c4bc8b49d544

```

BUT! Running the following:

```
dotnet-gitversion
```

... produces the following JSON output:

```json
{
  "Major":0,
  "Minor":4,
  "Patch":0,
  "PreReleaseTag":"alpha.2",
  "PreReleaseTagWithDash":"-alpha.2",
  "PreReleaseLabel":"alpha",
  "PreReleaseNumber":2,
  "WeightedPreReleaseNumber":2,
  "BuildMetaData":"",
  "BuildMetaDataPadded":"",
  "FullBuildMetaData":"Branch.develop.Sha.26a94e2396ad1f9b80f6b24e9140c4bc8b49d544",
  "MajorMinorPatch":"0.4.0",
  "SemVer":"0.4.0-alpha.2",
  "LegacySemVer":"0.4.0-alpha2",
  "LegacySemVerPadded":"0.4.0-alpha0002",
  "AssemblySemVer":"0.4.0.0",
  "AssemblySemFileVer":"0.4.0.0",
  "FullSemVer":"0.4.0-alpha.2",
  "InformationalVersion":"0.4.0-alpha.2+Branch.develop.Sha.26a94e2396ad1f9b80f6b24e9140c4bc8b49d544",
  "BranchName":"develop",
  "Sha":"26a94e2396ad1f9b80f6b24e9140c4bc8b49d544",
  "ShortSha":"26a94e2",
  "NuGetVersionV2":"0.4.0-alpha0002",
  "NuGetVersion":"0.4.0-alpha0002",
  "NuGetPreReleaseTagV2":"alpha0002",
  "NuGetPreReleaseTag":"alpha0002",
  "VersionSourceSha":"462423889a7edb569a8cd4b675866685cff8e098",
  "CommitsSinceVersionSource":2,
  "CommitsSinceVersionSourcePadded":"0002",
  "CommitDate":"2019-08-02"
}
```

So basically, the normal run gives **0.4.0-alpha.2** (which is wrong) while the diagnostic reports that **0.4.0-alpha.9** should be the next version (as expected).

What could possibly cause this?

**Comment by Crono1981** [comment]
Can't anyone help with this? I would really appreciate some insight.

**Comment by asbjornu** [comment]
@Crono1981, do you have a public repository that portrays this behaviour?

**Comment by Crono1981** [comment]
> @Crono1981, do you have a public repository that portrays this behaviour?

I'm afraid I do not. This is happening on a Windows 10 based Build Agent for Azure DevOps, in a private repository.

We did try to reproduce it in a side project but we couldn't make it happen. Might have to do about our particular repo's history. Unfortunately I am not authorized to push that repo outside of our servers.

I wished somebody else had a similar issue and could put me on the right track.

**Comment by asbjornu** [comment]
This is indeed a weird one we need to be able to reproduce to fix. I'm unable to reproduce locally so far. 😕

**Comment by asbjornu** [comment]
Is this still a problem in v5.2?

**Comment by lukecamilleri1982** [comment]
I believe I have this happening in 5.8.1 on WIndows Server.
`gitversion.exe
{
  "Major": 1,
  "Minor": 2,
  "Patch": 7,
  "PreReleaseTag": "ci.78",
  "PreReleaseTagWithDash": "-ci.78",
  "PreReleaseLabel": "ci",
  "PreReleaseLabelWithDash": "-ci",
  "PreReleaseNumber": 78,
  "WeightedPreReleaseNumber": 55078,
  "BuildMetaData": null,
  "BuildMetaDataPadded": "",
  "FullBuildMetaData": "Branch.master.Sha.b1c61ee6d6146971afbedc678499ee1af8ea7fa2",
  "MajorMinorPatch": "1.2.7",
  "SemVer": "1.2.7-ci.78",
  "LegacySemVer": "1.2.7-ci78",
  "LegacySemVerPadded": "1.2.7-ci0078",
  "AssemblySemVer": "1.2.7.0",
  "AssemblySemFileVer": "1.2.7.0",
  "FullSemVer": "1.2.7-ci.78",
  "InformationalVersion": "1.2.7-ci.78+Branch.master.Sha.b1c61ee6d6146971afbedc678499ee1af8ea7fa2",
  "BranchName": "master",
  "EscapedBranchName": "master",
  "Sha": "b1c61ee6d6146971afbedc678499ee1af8ea7fa2",
  "ShortSha": "b1c61ee",
  "NuGetVersionV2": "1.2.7-ci0078",
  "NuGetVersion": "1.2.7-ci0078",
  "NuGetPreReleaseTagV2": "ci0078",
  "NuGetPreReleaseTag": "ci0078",
  "VersionSourceSha": "d38d4ef2a9b617292d674d96f3d466cc529175b9",
  "CommitsSinceVersionSource": 78,
  "CommitsSinceVersionSourcePadded": "0078",
  "UncommittedChanges": 0,
  "CommitDate": "2023-09-18"
}`

and this is with diagnostic output:
`{
  "Major": 1,
  "Minor": 3,
  "Patch": 0,
  "PreReleaseTag": "",
  "PreReleaseTagWithDash": "",
  "PreReleaseLabel": "",
  "PreReleaseLabelWithDash": "",
  "PreReleaseNumber": null,
  "WeightedPreReleaseNumber": 60000,
  "BuildMetaData": null,
  "BuildMetaDataPadded": "",
  "FullBuildMetaData": "Branch.master.Sha.b1c61ee6d6146971afbedc678499ee1af8ea7fa2",
  "MajorMinorPatch": "1.3.0",
  "SemVer": "1.3.0",
  "LegacySemVer": "1.3.0",
  "LegacySemVerPadded": "1.3.0",
  "AssemblySemVer": "1.3.0.0",
  "AssemblySemFileVer": "1.3.0.0",
  "FullSemVer": "1.3.0",
  "InformationalVersion": "1.3.0+Branch.master.Sha.b1c61ee6d6146971afbedc678499ee1af8ea7fa2",
  "BranchName": "master",
  "EscapedBranchName": "master",
  "Sha": "b1c61ee6d6146971afbedc678499ee1af8ea7fa2",
  "ShortSha": "b1c61ee",
  "NuGetVersionV2": "1.3.0",
  "NuGetVersion": "1.3.0",
  "NuGetPreReleaseTagV2": "",
  "NuGetPreReleaseTag": "",
  "VersionSourceSha": "b1c61ee6d6146971afbedc678499ee1af8ea7fa2",
  "CommitsSinceVersionSource": 0,
  "CommitsSinceVersionSourcePadded": "0000",
  "UncommittedChanges": 0,
  "CommitDate": "2023-09-18"
}`

The VersionSourceSha is the onlt thing I can notice to be different

**Comment by asbjornu** [comment]
Sorry for the late reply. Are you able to test this with the latest v6 beta, @lukecamilleri1982?
