### ISSUE TITLE
AzureDevOps Environment not being updated with GitVersion generate value

### ISSUE THREAD

**Issue by MarkCBS** [GitTools/GitVersion#1772]
Originally raised on StackOverflow: https://stackoverflow.com/questions/57251970/azure-devops-pipeline-environment-gitversion-name

Then to Microsoft: https://developercommunity.visualstudio.com/content/problem/668222/azure-devops-pipeline-environment-gitversion-name.html

Who have closed and suggested I raise it here as they suggest it's a problem with GitVersion.

I'm using a multi-stage YAML build pipeline on Azure DevOps. After GitVersion runs the build status is updated with the new build number generated by GitVersion, however after deploying the build to a specified Environment, the Environments area in Azure DevOps is still showing the pre-GitVersion template value of the build number.

See StackOverflow link above for screenshots and configuration

**Comment by FISHMANPET** [comment]
I've also run into this, and I've found a little bit digging into this.

It appears somehow the Gitversion task is overwriting the name value of the pipeline with the calculated SemVer.  I can't figure out how the task is setting the name but it may have something to do with that and when the gitversion variables are available.

Also it doesn't just happen in environments, if you look at your Agent Pools (either the MS hosted or your onprem agents if you're using them) and look at the jobs, all the jobs the raw variable name instead the value that GitVersion is assigning.

**Comment by asbjornu** [comment]
Might #1980 solve this?
