### ISSUE TITLE
Latest change to Azure Devops task breaks builds v4  and v5 with duplicate Version in AssemblyInfo

### ISSUE THREAD

**Issue by joel100** [GitTools/GitVersion#1775]
Last night ~10:30pm US EST our Azure Devops builds started breaking with the following errors

```
\src\XXX.XXXX.XXXX.Contracts\Properties\AssemblyInfo.cs(37,12): Error CS0579: Duplicate 'AssemblyFileVersion' attribute
\src\XXX.XXXX.XXXX.Contracts\Properties\AssemblyInfo.cs(38,12): Error CS0579: Duplicate 'AssemblyInformationalVersion' attribute
Process 'msbuild.exe' exited with code '1'.
```

We're using version 4 of the Azure Devops task from the marketplace to build .Net Framework. We have update AssemblyInfo files checked so we get matching assembly versions with our packages.

I've tried updating to version 5 but get the same error. 

This is the command line from the version 4 version of the task
`[command]C:\ProgramData\Chocolatey\bin\GitVersion.exe D:\a\1\s /output buildserver /nofetch /updateassemblyinfo true`

I updated to version 5 and this is the command line
`[command]D:\a\_tasks\GitVersion_e5983830-3f75-11e5-82ed-81492570a08e\5.0.1\full\GitVersion.exe D:\a\1\s /output buildserver /nofetch /config D:\a\1\s\GitVersion.yml /updateassemblyinfo true`

It looks like there was an update to the task yesterday. Any help would be greatly appreciated

**Comment by arturcic** [comment]
There were no changes made to the task itself from version 5.0.0 to version 5.0.1. So it might be version 5.0.0 is not working properly, but I think it might be a configuration issue. Can you check you have this in your project? https://gitversion.readthedocs.io/en/latest/usage/msbuild-task/ (Remove AssemblyInfo attributes). This is for regular csproj files (not sdk based)

**Comment by joel100** [comment]
We don't. This has been working about 10 months until last night and broke last night

**Comment by arturcic** [comment]
Can you remove the AssemblyFileVersion and AssemblyInformationalVersion from Contracts\Properties\AssemblyInfo.cs? And try again?

**Comment by joel100** [comment]
This is our unchanged AssemblyInfo file (company info redacted). Aside from Title and product our AssemblyInfo files are all the same.

This was built unchanged in our PR build pipeline on 8/7 and in our Release pipeline yesterday at 14:44 but both pipelines began failing last night.

```
using System.Reflection;
using System.Runtime.InteropServices;

// General Information about an assembly is controlled through the following 
// set of attributes. Change these attribute values to modify the information
// associated with an assembly.
[assembly: AssemblyTitle("XXX.XXXX.XXXX.Contracts")]
[assembly: AssemblyDescription("")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("")]
[assembly: AssemblyProduct("XXX.XXXX.XXXX.Contracts")]
[assembly: AssemblyCopyright("Copyright ©  2016")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]

// Setting ComVisible to false makes the types in this assembly not visible 
// to COM components.  If you need to access a type in this assembly from 
// COM, set the ComVisible attribute to true on that type.
[assembly: ComVisible(false)]

// The following GUID is for the ID of the typelib if this project is exposed to COM
[assembly: Guid("xxxxx-f174-40ad-965c-5defa3339d69")]

// Version information for an assembly consists of the following four values:
//
//      Major Version
//      Minor Version 
//      Build Number
//      Revision
//
// You can specify all the values or you can default the Build and Revision Numbers 
// by using the '*' as shown below:
// [assembly: AssemblyVersion("1.0.*")]
[assembly: AssemblyVersion("1.0.*")]

```

**Comment by arturcic** [comment]
> [assembly: AssemblyVersion("1.0.*")]
Can you remove/ comment that?

**Comment by joel100** [comment]
Same error after commenting and running PR build. 

I noticed version 4 of the task is using Gitversion from a Chocolatey folder. Is it pulling in the correct version or is Chocolatey now pulling in version 5?

**Comment by arturcic** [comment]
hmmm, I guess you're using the GitVersion that is part of the Azure devops image. Can you use the embedded version? (Prefer bundled GitVersion)

**Comment by joel100** [comment]
That fixed it!

`[command]D:\a\_tasks\GitVersion_e5983830-3f75-11e5-82ed-81492570a08e\4.0.3\GitVersion.exe D:\a\1\s /output buildserver /nofetch /updateassemblyinfo true`

It might be a good change to make that option the default in future versions of the task

Thank you for being so responsive! It's very much appreciated

**Comment by arturcic** [comment]
You're welcome
