### ISSUE TITLE
Allow version # in branch name to be parsed using the regex expression in the GitVersion.yml

### ISSUE THREAD

**Issue by raulplanas** [GitTools/GitVersion#1778]
Currently GitVersion supports providing regex expression in GitVersion.yml to identify branch type (e.g. master vs develop vs feature vs release vs hotfix). However in order for for GitVersion to parse the version # from the branch name it only works if using format "release-<version>" or "hotfix\<version>".

For organizations that have different branch naming schemes, GitVersion should be able to strip the regex pattern from release branch names and use the remaining as possible version # assignment as it does with the above default naming conventions.

One example could be if branch name was _Release_1.2.3_, with Regex identifying the _Release__ prefix it should still be able to recognize the assignment of _1.2.3_ as the version #.

**Comment by raulplanas** [comment]
After looking at the code in more detail Rather than using the regex other alternative would be to expand the GitVersion.yml file and add extra field to specify custom delimiters either in addition or in replacement of the default "-" or "/" delimiters used by default.

**Comment by snhall** [comment]
Using a separate field for the delimiter could possibly remove the edge-case option of having no delimiter.  However, it may be easier to implement than including the separator in the branch type prefix, since it is already dealt with separately now.

**Comment by raulplanas** [comment]
Can anyone consider this issue please

**Comment by asbjornu** [comment]
@raulplanas, this project is being developed on voluntary basis. No one receives money to work on this project. If you are able to write and submit a pull request that implements support for what you are suggesting, I think it might be merged. I am, however, a bit unsure of exactly what is being asked for here. Can you please elaborate?

**Comment by asbjornu** [comment]
More importantly: How should configuration for what you want look like if it was implemented?
