### ISSUE TITLE
GitVersion on Azure always uses /noFetch option

### ISSUE THREAD

**Issue by p1971** [GitTools/GitVersion#1781]
I'm checking why GitVersion doesn't appear to generate the correct version on a master branch when building on azure pipelines, works locally.

I get the message:
_"Skipping fetching, if GitVersion does not calculate your version as expected you might need to allow fetching or use dynamic repositories"_ 

The logs indicate the task is running with the /noFetch option
_GitVersion.exe d:\a\1\s /output buildserver /nofetch /config d:\a\1\s\src\GitVersion.yml_

So thought I'd try to force a fetch, checking the code there doesn't appear to be a way to override this:

https://github.com/GitTools/GitVersion/blob/f9532574212bc48db5c8d099ceec05ec13bb55da/src/GitVersionTfsTask/GitVersion.ts#L61

Is this intentional ?

**Comment by p1971** [comment]
appears I hadn't sync'd the tags to the github repo.... doh.

**Comment by nzandy** [comment]
Sorry can I ask exactly what you mean by "hadnt syncd the tags to the github repo"? I'm having this same issue.

**Comment by p1971** [comment]
I had tagged my repo locally but not pushed them to the remote repo
