### ISSUE TITLE
Updating .net core Assembly files with the generated version number in Azure DevOps 

### ISSUE THREAD

**Issue by makhaly** [GitTools/GitVersion#1783]
I am using Azure DevOps Pipelines to build my ASP.NET core application. recently i have added the Git Version Task between the Restore and Build .NET Core Tasks.

GitVersion is working perfect and generating a version number.
But after downloading the Artifacts i checked the Assembly version and file version and it has version 1.0.0.0 without applying the version number generated by the GitVersion Task.

I am using GitVersion Task Version 5

![image](https://user-images.githubusercontent.com/10495343/63258167-27c1e180-c284-11e9-87eb-b57305fc97f6.png)

I am using the below configuration to force the use of the generated version in the Build Task
--configuration $(BuildConfiguration) -p:Version=$(GitVersion.SemVer)

![image](https://user-images.githubusercontent.com/10495343/63258208-4031fc00-c284-11e9-8376-a5d9ca6ccc33.png)

**Comment by roryprimrose** [comment]
Hi @makhaly, this is probably a duplicate of #1611. Have a look at the powershell I use in that issue. That is how I got around this until GitVersion supports updating versions in the sdk project format.
