### ISSUE TITLE
GitVersion.NuGetVersion truncates the suffix to 20 characters

### ISSUE THREAD

**Issue by bperkins24** [GitTools/GitVersion#1784]
I run my builds within TeamCity as follows:

1. Run GitVersion command line (version 5.0.0-beta2-26)
2. Pack my projects using GitVersion.NuGetVersion
3. The resulting NuGet package has the suffix truncated to 20 characters

The expected behavior is that the suffix not be truncated per this NuGet restriction that was removed.

https://github.com/NuGet/Home/issues/2735

Is there a specific reason that GitVersion maintains this restriction?

**Comment by asbjornu** [comment]
For backward compatibility. We could of course change that in a new major version, but `FullSemVer` would be a better candidate for environments which have no length restrictions and full SemVer 2.0 support.
