### ISSUE TITLE
GitVersion: Process returned an error (exit code -2146232576)

### ISSUE THREAD

**Issue by ars75** [GitTools/GitVersion#1790]
So I have `.NetFramework 4.6.1` on my local, and when I build my C# Solution it builds successfully. Then when I execute the command `GitVersion.exe -output json` it prints it successfully too!

Problem starts when I try doing the same on Jenkins build. It exits every time with `One or more errors occurred. GitVersion: Process returned an error (exit code -2146232576).` and a dialog box that says `.NETFramework, Version=v4.7.2` required. (see screenshot below)

The thing that I don't understand is that my local and Jenkins have the exact same configuration and are both on net461, so if it works locally why doesn't it work on the Jenkins build?

![GitVersion-requires-net472](https://user-images.githubusercontent.com/12216749/63699954-740ea380-c7e7-11e9-9b11-219e060e0667.PNG)

**Comment by arturcic** [comment]
Which version of the tool are you using?

**Comment by arturcic** [comment]
You probably have locally version 4.7.2 even if you target 4.6.1. That's usually when you have visual studio installed.

**Comment by arturcic** [comment]
Gitversion version 5.0.1 uses 4.7.2, if you need .net 4.6.2 use 5.0.0.
