### ISSUE TITLE
Inconsistencies between assembly-versioning-scheme and assembly-file-version-format

### ISSUE THREAD

**Issue by chrbkr** [GitTools/GitVersion#1791]
This might be a duplicate of some older, closed issues, especially #1406 and #544.

According to the documentation, `assembly-versioning-scheme` and `assembly-file-version-format` have exactly the same possible values, but that is not the case.

`'{MajorMinorPatch}.{CommitsSinceVersionSource}'` is possible for `assembly-file-version-format`, but doesn't work when used in `assembly-versioning-scheme`.

It would be nice to have the same flexibility in `assembly-versioning-scheme`, as that is what's accessible from the application. Right now, it's confusing that right-click in Explorer doesn't show the same info as the version shown in the application itself.

**Comment by asbjornu** [comment]
`format` and `scheme` are two different things, indeed. When you write "accessible from the application", which *application* are you thinking of?
