### ISSUE TITLE
GitVersionTask breaks incremental builds

### ISSUE THREAD

**Issue by srehm** [GitTools/GitVersion#1796]
Everytime the UpdateAssemblyInfo or GenerateGitVersionInformation target is executed, a randomized file is generated in the intermediate output directory (as implemented in the GetFileWriteInfo extension).
However, this interferes with the update logic at the end of AssemblyInfoFileUpdater.Update() and GitVersionInformationGenerator.Generate(), where the respective file is only updated if its content has changed.
The effect is that even if there were no changes to the project between two builds, the assembly will always be recompiled.

**Comment by ivan-danilov** [comment]
Moreover, if the project is built inside VS - it generates a new randomized file every couple of seconds for every project's intermediate output directory.

**Comment by asbjornu** [comment]
Do you have ideas on how this can be done differently?

**Comment by ivan-danilov** [comment]
@asbjornu why do you need different filename every time? Why defaulting to `$(IntermediateOutputPath)\GitVersionAssemblyInfo.cs` (and allowing to override the path through MSBuild variable) does not work for GitVersion?

And maybe read the previous result first and write to the file only if something is different (incremental-friendly)?

Probably I don't understand something but atm failing to see what...

**Comment by srehm** [comment]
Same here. I dont get the rationale behind the randomization.

**Comment by batzen** [comment]
Created a PR to fix this issue.
