### ISSUE TITLE
Update ownership on RubyGems

### ISSUE THREAD

**Issue by adamralph** [GitTools/GitVersion#1798]
Currently @danielmarbach, @JakeGinnivan, and [Particular Software](https://github.com/Particular) are listed as the owners of the [gitversion gem](https://rubygems.org/gems/gitversion).

Because of this, at Particular Software we are receiving multiple email notifications every day about new versions being released. As I understand it, all of the currently listed owners are no longer involved in this project.

Please update the listed owners to reflect the current owners. I guess you may need one of the current owners to make this change.

**Comment by arturcic** [comment]
Thanks for letting us know, I'll have a look on what we can do.

**Comment by arturcic** [comment]
I removed it

**Comment by gep13** [comment]
@arturcic does it make sense to get a common user added to this Gem?  I know we set up a GitTools email address at some point, which could be used instead of an individual?

**Comment by arturcic** [comment]
I would prefer to have the GitTools account if possible to recover the access.
