### ISSUE TITLE
GitVersion dotnet requirements are not explicit

### ISSUE THREAD

**Issue by mpalmujoki** [GitTools/GitVersion#1799]
We use Azure Devops in a project, and have a local build server to build an application that has requirements that don't fit the cloud build.

When I updated GitVersion task to 5.*, I noticed that the build started failing. The issue is that dotnet is not found:

![image](https://user-images.githubusercontent.com/8876090/64164558-1ebc3d00-ce4c-11e9-8497-4a0140a6b2b3.png)

I suspected I'd need a dotnet runtime on the machine. So, I installed the dotNet Core 2.2 runtime, but did not bother about enabling IIS since we don't use it.

However, the build still fails with that same error. I checked the Path variable on the machine, and it seems correct:

![image](https://user-images.githubusercontent.com/8876090/64164779-79ee2f80-ce4c-11e9-886d-fca4a7d2ecd4.png)

Why does GitVersion not find dotNet on the build machine?

And if it's part of my configuration, I'd love to see some place documented the exact needs regarding dotnet versions and such.

**Comment by arturcic** [comment]
When you configure the task you can chose the runtime, either core or full. I guess you used it the full version before, so when configuring please use the full runtime.

**Comment by mpalmujoki** [comment]
Apparently it was simple as that. Switched over to Full framework instead, and it started working. Thanks @arturcic !
