### ISSUE TITLE
GitVersion.CommandLine throws exception using CakeBuild

### ISSUE THREAD

**Issue by hugo-paredes** [GitTools/GitVersion#1804]
I've the following, very basic, example of a CakeBuild script.

```
#tool "nuget:?package=GitVersion.CommandLine&version=5.0.1"

var target = Argument("target", "default");

Task("version")
  .Does(() =>
{
  try
  {
    var version = GitVersion(new GitVersionSettings
    {
        OutputType = GitVersionOutput.BuildServer
    });  
  }
  catch (System.Exception ex)
  {
      Error(ex);
      throw;
  }
});

Task("default").IsDependentOn("version");

RunTarget(target);
```

The outcome is was expecting was to get the current Git tag. However, what I get is this:
```
dotnet cake build.cake

========================================
version
========================================
Cake.Core.CakeException: GitVersion: Process returned an error (exit code 8).
   at Cake.Core.Tooling.Tool`1.ProcessExitCode(Int32 exitCode) in C:\projects\cake\src\Cake.Core\Tooling\Tool.cs:line 139
   at Cake.Core.Tooling.Tool`1.Run(TSettings settings, ProcessArgumentBuilder arguments, ProcessSettings processSettings, Action`1 postAction) in C:\projects\cake\src\Cake.Core\Tooling\Tool.cs:line 119
   at Cake.Common.Tools.GitVersion.GitVersionRunner.Run(GitVersionSettings settings) in C:\projects\cake\src\Cake.Common\Tools\GitVersion\GitVersionRunner.cs:line 71
   at Submission#0.GitVersion(GitVersionSettings settings)
   at Submission#0.<<Initialize>>b__0_0()
An error occurred when executing task 'version'.
Error: One or more errors occurred. (GitVersion: Process returned an error (exit code 8).)
	GitVersion: Process returned an error (exit code 8).
```

To make sure it works, I ran the Docker image `gittools/gitversion-dotnetcore:linux-5.0.0` and it returned the expected result.

I'm using a Mac running macOS Mojave, version *10.14.6 (18G95)*.
The .net core version is *2.2.401*
And the CakeBuild version is *cake.tool 0.34.1*

Is this an issue or am I doing something wrong?

**Comment by asbjornu** [comment]
Perhaps this question is better asked in the Cake build repository?

**Comment by gep13** [comment]
@asbjornu yes, possibly.  @hugo-paredes there are no known issues with the GitVersion integration with Cake, I use it all the time, and Cake itself uses it for it's own build process.  I would suggest running Cake with [Diagnostic verbosity](https://stackoverflow.com/questions/38658660/how-to-enable-diagnostic-verbosity-for-cake), to find the exact command that is being executed, and verify that this is working if executed directly.

**Comment by hugo-paredes** [comment]
@asbjornu, @gep13 

I don't know, but if I use a different image the exception is gone. I'll close the issue because I have a workaround and it seems that I'm the only one affected.

Thanks.
