### ISSUE TITLE
dotnet Tool: Named Config file throws warning if Working and Repo root directories are the same

### ISSUE THREAD

**Issue by pianomanjh** [GitTools/GitVersion#1808]
GitVersion.Tool 5.0.1

If I have a named config file in the root of my repository, and attempt to specify it, an exception is thrown.  For example:
`dotnet gitversion /config ./myGitVersion.yml`
throws a warning:
`Ambiguous config file selection from 'C:\Projects\MyRepo\GitVersion-foobar.yml' and 'C:\Projects\MyRepo\GitVersion-foobar.yml'`

**Comment by asbjornu** [comment]
Can you please elaborate? "throws a warning" sounds a bit conflicting to me. Warnings are usually printed to the console without aborting the application, while errors (that are raised with `throw`) cause the application to halt and fail. If GitVersion only prints a warning to the console, is there an issue here?

**Comment by pianomanjh** [comment]
It causes the application to halt, so yes, an error.
