### ISSUE TITLE
Ignore numbers in release branch

### ISSUE THREAD

**Issue by gthvidsten** [GitTools/GitVersion#1811]
This is very similar to #1500 / #1541 , but sort of in a reverse sense.

The team I'm on use a flow similar (but not identical) to "gitflow". Our release branches gets PRs from feature branches. Seeing as one feature branch may require a 0.0.1 version update, and another branch requires a 0.1.0 verison update (based on the `major/minor/patch-version-bump-message` commit messages), and I don't know in advance which features are part of the next release, I therefore don't know which version number the next release will have and can't name it accordingly. I therefore want to just name them sequentially.
However, if I create a release branch called `release/42.1` (a hotfix for `release/42`) this will be versioned as `42.1.0`, whereas I would like the version of this to be the next logical version .

How can I get GitVersion to ignore the numbers in release branches?

**Comment by asbjornu** [comment]
Perhaps you can figure out a regex pattern that matches your release-branches and then declare them as not being release branches with [`is-release-branch: false`](https://gitversion.readthedocs.io/en/latest/configuration/#is-release-branch)?
