### ISSUE TITLE
Source branch name incorrectly parsed from GitHubPull merge message format

### ISSUE THREAD

**Issue by jim-paton** [GitTools/GitVersion#1832]
The source branch name as presented in the comment for a GitHub PR contains the owner of the source repository, _e.g._ from this repo's history:
[Merge pull request #1793 from ermshiperete/ImproveWorktree](https://github.com/GitTools/GitVersion/commit/ea2a10c11ac402d661f6154e36521fb721a8ac8e)

The Regex defined for "GitHubPull" doesn't correctly match this format:

https://github.com/GitTools/GitVersion/blob/7f3ae3f926c64796fe7208214d72ad0152ffe2de/src/GitVersionCore/MergeMessage.cs#L16

The `<SourceBranch>` named capture group in the regex captures the repository owner as part of the branch name _e.g._ `some-repo-owner/release/1.0.0` instead of simply `release/1.0.0`. The default rules for branch names therefore fail to correctly identify _e.g._ `feature/*` or `release/*` branches due to the inclusion of the repository owner in the parsed name.

**Comment by asbjornu** [comment]
That's correct, @jim-paton. Are you up for submitting a pull request accompanied with some tests to have this fixed?

**Comment by jim-paton** [comment]
Happy to give it a go. Will need to read the contributing guidelines first, though!
