### ISSUE TITLE
Error running on Team City build server. DllNotFoundException:  'git2-572e4d8'

### ISSUE THREAD

**Issue by DouglasHammon** [GitTools/GitVersion#1834]
Hello. Hoping someone can point me in the right direction. I'm getting this error when running GitVersion.exe on Team City build serve (windows agent)

> [17:47:54][Step 1/5] ERROR [09/30/19 17:47:54:09] An unexpected error occurred:
> [17:47:54][Step 1/5] System.TypeInitializationException: The type initializer for 'LibGit2Sharp.Core.NativeMethods' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'git2-572e4d8': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
> [17:47:54][Step 1/5]    at LibGit2Sharp.Core.NativeMethods.git_libgit2_init()
> [17:47:54][Step 1/5]    at LibGit2Sharp.Core.NativeMethods.InitializeNativeLibrary()
> [17:47:54][Step 1/5]    at LibGit2Sharp.Core.NativeMethods..cctor()
> [17:47:54][Step 1/5]    --- End of inner exception stack trace ---
> [17:47:54][Step 1/5]    at LibGit2Sharp.Core.NativeMethods.git_buf_dispose(GitBuf buf)
> [17:47:54][Step 1/5]    at LibGit2Sharp.Core.Handles.GitBuf.Dispose()
> [17:47:54][Step 1/5]    at LibGit2Sharp.Core.Proxy.ConvertPath(Func`2 pathRetriever)
> [17:47:54][Step 1/5]    at LibGit2Sharp.Repository.Discover(String startingPath)
> [17:47:54][Step 1/5]    at GitVersion.GitPreparer.GetDotGitDirectory()
> [17:47:54][Step 1/5]    at GitVersion.GitPreparer.GetProjectRootDirectory()
> [17:47:54][Step 1/5]    at GitVersion.ConfigFileLocator.Verify(GitPreparer gitPreparer, IFileSystem fileSystem)
> [17:47:54][Step 1/5]    at GitVersion.Program.VerifyArgumentsAndRun()
> [17:47:54][Step 1/5] INFO [09/30/19 17:47:54:09] 
> [17:47:54][Step 1/5] INFO [09/30/19 17:47:54:09] Attempting to show the current git graph (please include in issue): 
> [17:47:54][Step 1/5] INFO [09/30/19 17:47:54:09] Showing max of 100 commits

I have the above mentioned missing dll in "\lib\win32\x86" and "x64" folders. So not sure why its not finding it.

**Comment by DouglasHammon** [comment]
Anyone?

**Comment by asbjornu** [comment]
Is this reproducible with version 5.1.1 of GitVersion?

**Comment by DouglasHammon** [comment]
So after digging into this some more.. ended up being a dumb mistake on my part. My .gitignore file was not checking in x86/x64 folders, which was causing issues for GitVersion because those folders exist under Lib/win32. 

Thanks for the reply @asbjornu
