### ISSUE TITLE
GitVersion.yml can not be found when using GitVersionTask in a Git Submodule

### ISSUE THREAD

**Issue by Koekiewollie** [GitTools/GitVersion#1836]
When building C# code in VS2019, GitVersionTask looks for the GitVersion.yml file in the repository root. However, when using a Git Submodule, the file can not be found. This problem only happens for projects located within the submodule.

Info about my setup:

- I am using visual studio 2019 to build a C# application
- The C# application is located in a main repository and also uses projects located in a Git Submodule
- All projects use nuget package GitVersionTask version 5.0.1

It appears the issue is caused by the file ".git". Removing the file will fix the issue, but causes Git to lose track of changes in the submodule. 
This file is located in the root of the Submodule, and appears to be used to find the .git folder in the parent repository.

I think GitVersionTask expects a folder by the name ".git", but when it encounters a file with an equal name, the process is interrupted and the default GitVersion settings are used.

I looked at the build output, but couldn't find any related errors.

More information about submodules can be found here:
https://git-scm.com/book/en/v2/Git-Tools-Submodules

Pay attention to this section at the bottom of the page: 
> It’s important to note that submodules these days keep all their Git data in the top project’s .git directory, so unlike much older versions of Git, destroying a submodule directory won’t lose any commits or branches that you had.

**Comment by Koekiewollie** [comment]
I am currently working on reproducing the issue using the source code. Maybe I can fix it myself.

**Comment by Koekiewollie** [comment]
I am having difficulty reproducing the issue, using the source files. The issue still persists when using the nuget package. I'll keep trying when I have the time, but I'm not sure when i'll be able to continue.

**Comment by asbjornu** [comment]
That's ok, @Koekiewollie. Just submit a PR when you're ready.
