### ISSUE TITLE
GitVersion.Tool is not runnable from nanoserver container

### ISSUE THREAD

**Issue by casz** [GitTools/GitVersion#1837]
When running `mcr.microsoft.com/dotnet/core/sdk:3.0` the installed tool cannot run to due incompatible framework version

```
It was not possible to find any compatible framework version
The specified framework 'Microsoft.NETCore.App', version '2.1.0' was not found.
  - The following frameworks were found:
      3.0.0 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

You can resolve the problem by installing the specified framework and/or SDK.

The .NET Core frameworks can be found at:
  - https://aka.ms/dotnet-download
```

**Comment by arturcic** [comment]
We're working on .net 3.0 support for GitVersion

**Comment by casz** [comment]
🙇 Thanks looking forward to it

**Comment by arturcic** [comment]
#1849

**Comment by arturcic** [comment]
@casz can you try the version 5.0.2-beta.1+95 when it gets indexed?

**Comment by casz** [comment]
Sure can!

**Comment by casz** [comment]
Works just fine from GitVersion.Tool point of view.

NanoServer have not yet fixed path to `.dotnet/tools` folder to be on PATH
