### ISSUE TITLE
Merge message increment

### ISSUE THREAD

**Issue by RobSmyth** [GitTools/GitVersion#1856]
Hi,

Is it possible to increment the version number by keywords imbedded in the merge message like "+semver:minor"?

Our process is that all merges to a release branch go via a BitBucket pull request. We want to review version bump as part of the pull request. My testing shows that "+semver:minor" works if in a commit message but not if in the merge message.

Am I wrong or easy?

**Comment by RobSmyth** [comment]
Since asking this I realise that Bitbucket pull request description is not accessible from Git. So my question may not be appropriate for GitVersion. However, any thoughts feedback would be appreciated.

**Comment by asbjornu** [comment]
A merge commit is also a commit with a message, but I'm not clear on how that message is edited on Bitbucket. I'm not sure whether `+semver:minor` works in merge messages or not, though. Perhaps not, as I have the impression version increments via commit messages is mostly used for `mode: Mainline` where squashed "merges" seem to be more common than feature branches and real dual-parent merges?
