### ISSUE TITLE
TargetBranch command line option ignored on Jenkins

### ISSUE THREAD

**Issue by nickdalt** [GitTools/GitVersion#1857]
Example command line:-

/url https://example.com/project.git /p password /u user /b master

Environment:-

Windows, Jenkins, Bitbucket Multibranch Pipeline

In this environment, the target branch selected is ignored by GitVersion.

The expected outcome is that GitVersion clones project branch master calculates the version. In practice what happens is that the project is cloned and whatever branch Jenkins is building is used to calculate the version.

Additionally, the behaviour of GitVersion running under Jenkins should be documented i.e. the fact that its behaviour is heavily controlled by Jenkins environment variables.

**Comment by asbjornu** [comment]
I would happily merge a PR documenting how the Jenkins integration works.
