### ISSUE TITLE
tag-prefix does not exclude tags without prefix

### ISSUE THREAD

**Issue by marcussonestedtbarium** [GitTools/GitVersion#1860]
I am trying to introduce gitversion for a nuget package in a repo that has tags without prefixes for the entire thing, and GitVersion counts seems the tags without tag-prefix as well. Running /diag shows how it selects these commits and computes an increment too

**Repro:**

```
>git commit -a -m"final fix before release"
>git tag 1.42.0
>git tag subpacket/v0.3
>git commit -a -m"new stuff"
>gitversion /overrideconfig tag-prefix=subpacket/v /showvariable majorminorpatch
1.43.0
```

**Expected output:** 

```
0.4.0
```

Love this tool though. Will see about PR or workarounds. (We could rename all existing tags of course, but I'm trying to introduce this in a gentle manner). Current workaround is to ignore ~120 hashes, and having to update these for each new main release of the product.

**Comment by asbjornu** [comment]
If you are able to add a PR that fixes this and it doesn't break a lot of other tests, it will be happily merged. If other tests fail, let's discuss whether adjusting their expectancy is correct or not.

**Comment by Daniel-Svensson** [comment]
A workaround is to go back to version 4.
Version 4 works fine for us, but nut version 5 of gitversion

**Comment by marcusl** [comment]
I encountered this again in a new repo @ a new customer. Will see if I can fix this some evening.
