### ISSUE TITLE
Depreciation of GitVersion.CommandLine.DotNetCore

### ISSUE THREAD

**Issue by Techcadia** [GitTools/GitVersion#1864]
With the commit of c172e8f58ea9f0edea212fde8ccf0f472b443847 we can see that versions of `GitVersion.CommandLine.DotNetCore` are no longer being created. I understand the goal was to move everything into ` GitVersion.CommandLine` since 29caeeeecec323d380e993eeceb66fe177c55758 dropped support for `net472`

My command I used to run was
```
dotnet ~/.nuget/packages/gitversion.commandline.dotnetcore/5.0.2-beta1.71/tools/GitVersion.dll
```

Now the price of admission went from the dotnet sdk that I already have installed for building to adding mono to my images. 

https://pkgs.alpinelinux.org/package/edge/testing/x86/mono which is 80MB extra to download and 250MB of storage.

even with that said it does not work as expected
```
/build # mono ~/.nuget/packages/gitversion.commandline/5.0.2-beta1.99/tools/GitVersion.exe
Cannot open assembly '/root/.nuget/packages/gitversion.commandline/5.0.2-beta1.99/tools/GitVersion.exe': File does not contain a valid CIL image.
```

I am not sure if
1. The ` GitVersion.CommandLine` should contain the DLLs
1. the package `GitVersion.CommandLine.DotNetCore` should continue to be maintained.
1. The GitVersion.exe should work with mono

**Comment by Techcadia** [comment]
it seems there is a note in PR #1849 that states in the future the command line tools will support MacOS and linux. But curently do not.

**Comment by arturcic** [comment]
The `GitVersion.CommandLine.DotNetCore` was deprecated in favor of GitVersion.Tool not `GitVersion.CommandLine`, and you can use the global tool as local tool if needed. There is no need to run mono. Second, `GitVersion.CommandLine` is just a single exe file that is actually the self-container version of the dotnet core, it includes the runtime and the executable. It has specific version for each of the platforms, comparing with the global tool

**Comment by arturcic** [comment]
And the Global tool runs on all 3 platforms.
