### ISSUE TITLE
Adding Razor pages using Entity Framework (CRUD) scaffolding fails when GitVersionInformation is used in .Net Core 3

### ISSUE THREAD

**Issue by mrhoeve** [GitTools/GitVersion#1870]
I'm working on a new .Net Core 3 project in VisualStudio 2019 and I'm using GitVersionTask 5.0.1 that I installed via NuGet. I'm using GitVersionInformation to display version information to the user. However, I'm running into a bug with it.

When using GitVersionInformation anywhere in the project, I'm not able to add Razor pages via scaffolding. The error message I'm receiving is:
There was an error running the selected code generator:
'Could nog get the reflection type for DbContext:  TestCore3.Models.TestCore3Context'

In de code generation log I find this output:
Finding the generator 'razorpage'...
Running the generator 'razorpage'...
Attempting to compile the application in memory.
Could not get the reflection type for DbContext : TestCore3.Models.TestCore3Context
   at Microsoft.VisualStudio.Web.CodeGeneration.ActionInvoker.<BuildCommandLine>b__6_0()
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Microsoft.VisualStudio.Web.CodeGeneration.ActionInvoker.Execute(String[] args)
   at Microsoft.VisualStudio.Web.CodeGeneration.CodeGenCommand.Execute(String[] args)

When I'm just commenting out the lines where I use GitVersionInformation, the scaffolding works perfectly.

**Comment by asbjornu** [comment]
Sorry, but I don't even know where to begin with this one. 🤷‍♂ Do you have any ideas why GitVersion might be causing the build to fail?

**Comment by mrhoeve** [comment]
Your guess is as good as mine... I did experience it on the project I'm working on, and validated the problem by setting up a band new .Net Core 3 project, adding only Entity Framework Core and GitVersionTask, defining a model and a context en trying to scaffold... Same behaviour...

**Comment by arturcic** [comment]
@mrhoeve, can you create a test repo that you could share with us so that we can have a look? I think it should not be too difficult to create one, am I right?

**Comment by mrhoeve** [comment]
@arturcic Sure, no problem! Take a look here: https://github.com/mrhoeve/GitVersionTaskNetCore3Example
In the readme.md I specified what steps to take to reproduce the error.

**Comment by mrhoeve** [comment]
Thank you @asbjornu for removing the stale label.
Can I do something to resolve this issue? Am I the only one experiencing this problem?

**Comment by asbjornu** [comment]
I don't understand how removing `System.Console.WriteLine($"{GitVersionInformation.Major}");` from `Program.cs` should help in any way or why it should cause problems in the first place. Sorry, but this makes no sense to me.

**Comment by mrhoeve** [comment]
I'm sorry, but I don't know either... It works without it, and it doesn't work with it.
Maybe I am doing something wrong, but I can't figure this one out... Hence the project with the error...
