### ISSUE TITLE
GitVersion 4 differing on Windows/Ubuntu DevOps

### ISSUE THREAD

**Issue by phatcher** [GitTools/GitVersion#1890]
I'm running GitVersion 4.11 in Azure DevOps as 5 didn't generate the correct numbers, although it worked locally.

I'm finding that I get a different version number depending on whether GitVersion is executed on Windows or Linux, here's the two logs...

[gitversion-win.txt](https://github.com/GitTools/GitVersion/files/3816077/gitversion-win.txt)
[gitversion-linux.txt](https://github.com/GitTools/GitVersion/files/3816079/gitversion-linux.txt)

The main difference seems to be that the Linux version does not detect the mainline development mode.

Ideas?

**Comment by Sang-ShinLEE** [comment]
I have kind of the same problem: windows and ubuntu does not return same version.
In my case, on ubuntu, on master branch, commit messages are processed, even with following configuration in GitVersion.yml:
no-bump-message: '\+semver:\s?(none|skip)'
commit-message-incrementing: Disabled

**Comment by phatcher** [comment]
GV 5 now returns correct values for both Windows and Ubuntu on DevOps

**Comment by Jonesie** [comment]
I have the same issue with v 5.6.6 x64, also on Azure Dev Ops.

[gitversion-linux.txt](https://github.com/GitTools/GitVersion/files/6080188/gitversion-linux.txt)
[gitversion-windows.txt](https://github.com/GitTools/GitVersion/files/6080189/gitversion-windows.txt)

Main problem for me is the assemblysemver in windows has the patch as 0.  Im sure this has been working - not sure what has changed.
