### ISSUE TITLE
Outdated DockerHub image

### ISSUE THREAD

**Issue by natenho** [GitTools/GitVersion#1900]
I could not find the latest GitVersion version in DockerHub.

It seems that [Azure Pipelines](https://dev.azure.com/GitTools/GitVersion/_build/results?buildId=1238&view=logs&s=d1587781-abcf-5ffe-6a5f-6b4c8dc4f832&j=0062e705-95f1-59e4-04b8-550cc8caf3f4) are not doing anything to publish there:

```
========================================
Publish-DockerHub
========================================
Executing task: Publish-DockerHub
Finished executing task: Publish-DockerHub
```

Could someone update the image with the latest versions? 
Thanks!

**Comment by arturcic** [comment]
Can you check these? https://hub.docker.com/r/gittools/gitversion/tags

**Comment by natenho** [comment]
I see, maybe we should review docker hub's README.md content.
Thanks!

**Comment by asbjornu** [comment]
@natenho:

> I see, maybe we should review docker hub's README.md content.

In what way? A PR containing a suggested rewrite of the content would be appreciated. :)
