### ISSUE TITLE
GitVersionCore in NuGet is no longer up to date

### ISSUE THREAD

**Issue by derwasp** [GitTools/GitVersion#1902]
I am using [GitVersionCore](https://www.nuget.org/packages/GitVersionCore/) as a part of my project and noticed that it is no longer being published as a nuget package.
Was there a specific reason for this? And can it be reverted as I'd rather have the official version instead of a custom-built one.

@arturcic

**Comment by Elufimov** [comment]
I just stumbled on this with GitVersion.CommandLine.DotNetCore package. What one should use instead?

**Comment by derwasp** [comment]
@arturcic would really appreciate some feedback on this one

**Comment by arturcic** [comment]
Some time ago I decided to stop publishing the GitversionCore package as later I implemented some changes by adding the Dependency injection. I think we could continue publishing it but we'll have to make some adjustments, and to document the way it should be loaded (the Dependency injection part)

**Comment by derwasp** [comment]
@arturcic I am fine with breaking changes as long as I can have the package and fix the issues :)
It wasn't really documented before and I managed to use it in my project. I would really appreciate it if you could get the package back as I really want to grab the latest changes.

**Comment by arturcic** [comment]
ok, I'll add to my list, publishing it back

**Comment by derwasp** [comment]
awesome, thank you a ton

**Comment by derwasp** [comment]
@Elufimov see if the tool mentioned by @arturcic here:
https://github.com/GitTools/GitVersion/issues/1908
is something that will work for ya

**Comment by arturcic** [comment]
@derwasp, just curiousity, is your project public? I would like to see how it's used in the wild, the core part

**Comment by derwasp** [comment]
@arturcic I have plans on making it public, it's just not ready for it, yet. As I have some things tailored to the company needs and the codebase it a bit weird here and there.

I am happy to tell you what it is though.
It's a [GitHub app](https://developer.github.com/apps/) for GitHub -> [CodeBuild](https://aws.amazon.com/codebuild/) integration, similar to [stork](https://github.com/mapbox/stork), but written in .NET. GitVersion is used there to generate the build version for all the commits, as the one available from CodeBuild is very basic.
My app is further integrated with [OctopusDeploy](https://octopus.com/), where this same gitversion is used to generate a release.

So on every webhook I get the whole repo, run gitversion on it and then set the result as an environment variable in the codebuild job.

I can't use the compiled binary as I am running this whole thing inside an [aws lambda function](https://aws.amazon.com/lambda/) (same as azure functions, iron functions etc) and it's not very flexible.

CodeBuild also doesn't allow to set any variables from inside the build so they can be visible to my service, so I can only generate this version right before I start the job. And this is the reason the GitVersion is embedded in the application that processes the webhooks

I hope it gives at least some insight :)

**Comment by arturcic** [comment]
Thanks for the details, it's really interesting to see the usages
