### ISSUE TITLE
Deprecated task execution handler in use on Azure DevOps Task

### ISSUE THREAD

**Issue by timvandenhof** [GitTools/GitVersion#1906]
**GitVersion Task for Azure DevOps**
**Version:** 3.6.5
**Pool:** Azure Pipelines
**Image:** windows-2019

When the GitVersion task is initialized in a build pipline, Azure DevOps throws a warning about the Task using a deprecated feature.  This is visible in the build log and in the summary UI.

**Buidlog:**
`##[warning]Task 'GitVersion' (3.6.5) is using deprecated task execution handler. The task should use the supported task-lib: https://aka.ms/tasklib`

**Build UI:**
<img width="947" alt="Screen Shot 2019-11-13 at 10 41 28 PM" src="https://user-images.githubusercontent.com/2083464/68806798-e06ea580-0666-11ea-9190-9e8daa17818c.png">

Well, all I can say at this moment it's time to consider and/or plan moving over to the newer SDK's. Information should be available at the link in the build log: https://aka.ms/tasklib

**Additional information:**
- Issue describing the need of additional guidance: https://github.com/microsoft/azure-pipelines-task-lib/issues/562
- Similar issue on other build task: https://github.com/microsoft/azure-pipelines-extensions/issues/652

**Comment by arturcic** [comment]
Version 3.6.5 is really old. Can you try the newest from https://marketplace.visualstudio.com/manage/publishers/gittools/extensions/usegitversion/hub?_a=acquisition

**Comment by timvandenhof** [comment]
Thanks for pointing out that I should upgrade. I did the wrong assumption that we were already running the latest task version. Verifying our build pipelines, showed that we have the newer 5.* version available, but are stil using the old 3.* version.

![image](https://user-images.githubusercontent.com/2083464/68835002-61558d80-06b7-11ea-8ac2-40aeda1dc41e.png)

Will upgrade to the newer version, thanks again.

**Comment by arturcic** [comment]
Closing

**Comment by arturcic** [comment]
@timvandenhof I would still recommend the new extension, as that one is supported, the old one is deprecated
