### ISSUE TITLE
gitversion.commandline support for linux?

### ISSUE THREAD

**Issue by derwasp** [GitTools/GitVersion#1908]
I just tried using the latest version (`5.1.2`) with my [Fake](https://github.com/fsharp/FAKE) script and got an error, when it tried running it via mono.
As far as I can see, you are now publishing a self-contained executable, which works on Windows.

But what about Linux? Is there an alternative? My build scripts (and it's the case for many other people) come bundled with a specific GitVersion.
I was waiting for the 5x branch to be stable so I can finally use it on ubuntu 18.04, and it even works when deployed manually.

However, I rely on NuGet to get the valid binary, which would work on both Windows and Linux and so far I can't seem to find it.

This is what I get when I tried running `dotnet GitVersion.exe`:
```
root@d633c9c26093:/tmp-repo/packages/build/GitVersion.CommandLine/tools# dotnet GitVersion.exe
A fatal error was encountered. The library 'libhostpolicy.so' required to execute the application was not found in '/tmp-repo/packages/build/GitVersion.CommandLine/tools/'.
Failed to run as a self-contained app. If this should be a framework-dependent app, add the /tmp-repo/packages/build/GitVersion.CommandLine/tools/GitVersion.runtimeconfig.json file specifying the appropriate framework.
```

What would be your suggestion?

Related to #1907

**Comment by arturcic** [comment]
@derwasp you could use the GitVersion.Tool instead https://www.nuget.org/packages/GitVersion.Tool/

**Comment by derwasp** [comment]
Thank you @arturcic! With some custom magic, I managed to get it working :)
