### ISSUE TITLE
GitVersion 5.1.x fails on Windows

### ISSUE THREAD

**Issue by knoxi** [GitTools/GitVersion#1925]
I am using GitVersion 5.1.2 on a Windows 10 Pro 1903 VM (Build Agent) and it fails with:
```
C:\tools\GitVersion\5.1.2\GitVersion.exe
Error:
  An assembly specified in the application dependencies manifest (GitVersion.deps.json) was not found:
    package: 'Microsoft.Extensions.Configuration.Binder', version: '3.0.0'
    path: 'lib/netcoreapp3.0/Microsoft.Extensions.Configuration.Binder.dll'
```

With GitVersion 5.1.1 it fails with:
```
C:\tools\GitVersion\5.1.1\GitVersion.exe
The application to execute does not exist: 'C:\Users\Build\AppData\Local\Temp\.net\GitVersion\wqpiv0bz.rqg\GitVersion.dll'.
```

Does someone has an idea?

**Comment by jfaixo** [comment]
Same problem here

**Comment by mattsalmon** [comment]
Same error here as the original post, GitVersion 5.1.3 running on Windows 10 Enterprise (10.0.16299)

**Comment by Sventric** [comment]
This problem still exists in 5.1.3.

On day 1 GitVersion did exactly what i hoped... en after the weekend it just stopped with this error.

Edit:
Clearing the TMP folder did fix it for me for now.

**Comment by asbjornu** [comment]
>  Clearing the TMP folder did fix it for me for now.

Thanks for that important tidbit of information, @Sventric. Does this also fix the problem for you, @mattsalmon, @jfaixo, @knoxi?

**Comment by abogarsukov** [comment]
Same issue with GitVersion 5.1.3 on MacOS Sierra. Restarting the OS fixes it for some time, than it breaks again.

**Comment by arturcic** [comment]
Looks like it's related to the path where the single executable file gets extracted.
We can override the path by setting DOTNET_BUNDLE_EXTRACT_BASE_DI env var https://docs.microsoft.com/en-us/windows-server/upgrade/upgrade-2016-to-2019
