### ISSUE TITLE
Add Github Actions BuildAgent

### ISSUE THREAD

**Issue by arturcic** [GitTools/GitVersion#1931]

**Comment by VikingTristan** [comment]
Hey, I have a question. I'm having some trouble wrapping GitVersion environment variables together with github action workflows. Is this related?

**Comment by arturcic** [comment]
This issue is for adding GitHub Action support as build agent, basically when running inside of a GithubAction agent it will have the context of the agent available and it will consume the env variables, and/ or set the env vars

**Comment by arturcic** [comment]
https://github.com/GitTools/GitVersion/tree/master/src/GitVersionCore/BuildServers as examples

**Comment by StanleyGoldman** [comment]
I'm starting this pull request now.

**Comment by StanleyGoldman** [comment]
The PR is good to go!

**Comment by StanleyGoldman** [comment]
@VikingTristan if you want to give my pull request a try, I could use the validation that it works.

**Comment by VikingTristan** [comment]
Sure! Is it possible for me to tell my agent to download your specific gitversion pull request build?

With something like `choco install gitversion.portable x.x.x-xx`
