### ISSUE TITLE
Commented out AssemblyVersion tags still causing GitVersion to not generate versions correctly

### ISSUE THREAD

**Issue by KiLLeRRaT** [GitTools/GitVersion#1939]
Hi All,

I found the following problem.  I installed GitVersionTask, and commented out my AssemblyVersion tags from my AssemblyInfo.cs file.

After building, GitVersion would version my dll as 0.0.0.0.

I received the warning:

`File contains assembly version attributes which conflict with the attributes generated by GitVersion`

I looked in the code for the detection, and it looks like it expects a full line, https://github.com/GitTools/GitVersion/blob/2dd6bd1aa664d41814dab83b0a6d4f97b28807a9/src/GitVersionTask/FileHelper.cs#L108

My AssemblyInfo.cs looks like this:

```
//[assembly: AssemblyVersion("1.0.*")]
//[assembly: AssemblyFileVersion("19.04.15")]
//[assembly: AssemblyInformationalVersion("19.04.15-1822afec")][END OF FILE]
```

Updating my AssemblyInfo to the following did the trick:

```
//[assembly: AssemblyVersion("1.0.*")]
//[assembly: AssemblyFileVersion("19.04.15")]
//[assembly: AssemblyInformationalVersion("19.04.15-1822afec")]
[END OF FILE]
```

Not sure if you want to fix this, but here it is anyway, in case someone else runs into the same problem.

Cheers,

**Comment by asbjornu** [comment]
This can be fixed either by documenting that `AssemblyInfo.cs` should have a blank line at the end, or by adjusting the regex. Which solution do you prefer and which solution would you be up for submitting a PR for? 😃

**Comment by arturcic** [comment]
> This can be fixed either by documenting that `AssemblyInfo.cs` should have a blank line at the end, or by adjusting the regex. Which solution do you prefer and which solution would you be up for submitting a PR for? 😃

I'd prefer to fix the Regex

**Comment by KiLLeRRaT** [comment]
I just had a look and found that for me, the easiest way is to just append a newline to `allText` like so 

Here is the .NET Fiddle: https://dotnetfiddle.net/uFh63I

You can test the cases by uncommenting, or  commenting out the last line of `allText` which contains the Assembly*Version tab.

```
using System;
using System.Text.RegularExpressions;

public class Program
{
	public static void Main()
	{
		Console.WriteLine("Hello World");
		
		if (CSharpFileContainsVersionAttribute("", ""))
		{
			Console.WriteLine("Yup");
		}
		else
		{
			Console.WriteLine("Nup");
		}	
	}
	
	private static bool CSharpFileContainsVersionAttribute(string compileFile, string projectFile)
        {
            //var combine = Path.Combine(Path.GetDirectoryName(projectFile), compileFile);
            //var allText = File.ReadAllText(combine);
			var allText = @"
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("""")]
[assembly: AssemblyDescription("""")]
[assembly: AssemblyConfiguration("""")]
[assembly: AssemblyProduct(""test"")]
[assembly: AssemblyTrademark("""")]
[assembly: AssemblyCulture("""")]
[assembly: ComVisible(false)]
[assembly: Guid(""9ea78210-6c37-430d-9999-92c740f2900e"")]

[assembly: InternalsVisibleTo(""test"")]
[assembly: InternalsVisibleTo(""test"")]
//[assembly: AssemblyVersion(""1.0.0.0"")]
//[assembly: AssemblyFileVersion(""1.0.0.0"")]
//[assembly: AssemblyInformationalVersion(""1.0.0.0"")]";

			allText += System.Environment.NewLine; // Always add a new line, this handles the case for when a file ends with the EOF marker and no new line. If you don't have this newline, the regex will match commented out Assembly*Version tags on the last line.
            var blockComments = @"/\*(.*?)\*/";
            var lineComments = @"//(.*?)\r?\n";
            var strings = @"""((\\[^\n]|[^""\n])*)""";
            var verbatimStrings = @"@(""[^""]*"")+";

            var noCommentsOrStrings = Regex.Replace(allText,
                blockComments + "|" + lineComments + "|" + strings + "|" + verbatimStrings,
                me => me.Value.StartsWith("//") ? System.Environment.NewLine : string.Empty,
                RegexOptions.Singleline);

            return Regex.IsMatch(noCommentsOrStrings, @"(?x) # IgnorePatternWhitespace
\[\s*assembly\s*:\s*                    # The [assembly: part
(System\s*\.\s*Reflection\s*\.\s*)?     # The System.Reflection. part (optional)
Assembly(File|Informational)?Version    # The attribute AssemblyVersion, AssemblyFileVersion, or AssemblyInformationalVersion
\s*\(\s*\)\s*\]                         # End brackets ()]");
        }
}
```

**Comment by arturcic** [comment]
If You don't mind in case you send a PR to also add a failing test before the actual fix so that we can see the fix is working

**Comment by arturcic** [comment]
If You don't mind in case you send a PR to also add a failing test before the actual fix so that we can see the fix is working

**Comment by KiLLeRRaT** [comment]
Here you go: https://github.com/GitTools/GitVersion/pull/2150
