### ISSUE TITLE
Tagged trees and blobs cause GitVersion to crash

### ISSUE THREAD

**Issue by cyanite** [GitTools/GitVersion#1944]
In git it's legal (and used e.g. in the Git and Linux repositories; see https://git-scm.com/book/en/v2/Git-Internals-Git-References) to tag non-commit objects, i.e. trees or blobs. GitVersion crashes if it encounters such an object, however, due to an invalid cast.

Such tags should instead be ignored. I've created a pull request to fix it.

**Comment by arturcic** [comment]
Closed by #1945
