### ISSUE TITLE
Control Version with Commit Tags Only

### ISSUE THREAD

**Issue by CoolDadTx** [GitTools/GitVersion#1948]
We're trying to see if GitVersion can do versioning the way we want and we have a couple of scenarios where it doesn't seem possible. Maybe I'm missing something here.

Desired restrictions:
- We only want to control versioning using tags on commits, not commit messages.
- Versioning is handled by an automated system and therefore is not customized on a per-repo basis. We have a lot of repos and therefore uniform behavior is critical.
- Avoid using yet another configuration file in our builds to control yet another tool so there is no gitversion.yaml file. If this were absolutely needed we'd end up pushing the settings into existing config files and have our automated build extract the values out.
- Using Githubflow (feature branches with don't care version # are merged into master which controls the version #).
- Don't want to have to make a commit just to change the version #. We can already do this with our existing versioning system and GitVersion was the planned solution to needing to do this.
- Devs aren't going to remember/know that a change might require a major/minor version change so assuming they will do it right is not reasonable.

The biggest thing I see right now is that there is no way to get an X.0.0 or X.Y.0 version # from GitVersion using just commit tags. As soon as any commit occurs on master it is going to increment patch. So if we have a new repo the version # is 0.1.0 but we want it to be 1.0.0. There is no way to do this with just a tag on a commit. We have to commit a (probably meaningless) change with the correctly formatted commit message to get to the version we want.

I see us using GitVersion 1 of 2 ways. The first way is that we simply set the version we want as a tag on a commit and that base version is used for all builds until we change it again (excluding build metadata, etc). This is basically equivalent to how we do it now except we handle this via a file. On a release we create a new tag against the last commit with the version incremented based upon what we know at the time (e.g. from 1.5 to 1.5.1). Subsequent builds on this repo would use the new version. If we return to this repo later and realize we need major changes we'll retag the commit accordingly (e.g. 1.6 or 2.0).

The alternative approach is that we start work on a repo and let GitVersion increment the current tag by one (ideally minor, not patch though). So if the last release was 1.0.0 then GitVersion returns 1.0.1. This seems more natural to how GitVersion works. However we cannot figure out how to get even versions (e.g. 1.2.0, 2.0.0) via GitVersion because there is no value we can set the commit tag to that would allow it to "add 1" and come up with 0. So if the last commit was tagged as 1.2.3 and we know the next batch of work is a major change we could tag the repo with 1.3.0 but GitVersion increments the patch to 1.3.1.

**Comment by pi3k14** [comment]
Are you saying that 
`git tag -f 1.1.0
git push origin 1.1.0`
doesn't work?
We are using this in all our repos in PR's to master, release and develop, and version numbers in hotfix/release branch names (using GitFlow) - works like a dream :)

**Comment by CoolDadTx** [comment]
I'm saying that after setting that tag as 1.1.0 then any commits to that branch will result in 1.1.1 if you're using patch increments or if you push 1.0.0 then any commits to that branch will result in 1.1.0 if you're using minor increments.  Therefore if your app last shipped as 1.9 and you now want to start work on 2.0 there doesn't seem to be any way to have the tool generate 2.0.0 version #s using just git tags unless you also disable the increment options temporarily.

**Comment by pi3k14** [comment]
Do you think the first part of your statement is something wrong (incrementing after tag'ing)?
When you merge a 2.0 branch/tag into develop gitversion should start increment that branch from 2.0, don't you see this behavior?

**Comment by CoolDadTx** [comment]
We're using GithubFlow so there is no `develop` branch. Nor do we version a feature branch. The master branch has the tag from our last release (say 1.9). We begin work on new changes and we know it will be major changes so we want this to be 2.0. The devs branch from master into their feature branches (version doesn't matter at this point). However when they merge back into master this triggers a CI build and we want that to be 2.0. 

From my understanding of how GitVersion works there is no way with just tagging the repo directly to get it to increment to 2.0. You have to either temporarily modify the YAML file to tell it to increment the major version and then remember to change it back on your next version or you have to resort to something other than tagging such as commit messages or something. In our team the devs do not have control over the version #s. Versioning is controlled by higher level decisions so using tagging seemed the best approach.

At this point I think the only option to use GitVersion would be to tell it to never increment anything and then explicitly set the tag on the repo accordingly. After a release we branch master to a `release/v1.2.3` branch which we use for hotfixes and we can configure the YAML to increment the patch version here as that would make sense for a hotfix release.

**Comment by pi3k14** [comment]
You are using GithubFlow and hotfix branches? Wouldn't GitFlow be a better option?

GitVersion supports tagging of repo to manually bump a version, but since your flow depends on internal decisions about bumping when a new feature are released it makes sense to use the commit message for that feature to bump the version.

When you are triggering at CI build that build should tag your repo with the version number GitVersion is calculating, then you wouldn't need to create your hotfix branch until it is needed.
Merging to master should, in your case, always increment - either manually or automatic.

I guess you have read up on the documentation of GithubFlow merging strategies in the GitVersion documentation?

**Comment by CoolDadTx** [comment]
> You are using GithubFlow and hotfix branches? 

I never said anything about a hotfix branch. We use master and feature branches. Just like documented [here](https://gitversion.net/docs/git-branching-strategies/githubflow). The only thing we do beyond that is to branch master into a `release/x.y.z` branch when it is officially deployed so we have a copy of what got built. There is nothing related to hotfixes here.

> it makes sense to use the commit message for that feature to bump the version.
Again, as I mentioned in the original post we DO NOT want to bump versions by commit messages. There is absolutely no situation in our dev process where this would ever be appropriate, desired or allowed. Devs do not make this decision and therefore cannot know the situations under which incrementing the version is appropriate. This is the way we work and we aren't changing that. 

Really all I want is to be able to put the version in a tag on the master branch and version against that. I guess the only way I see this working with GitVersion is to have it not increment the master branch version under any circumstances. We will manually tag the master branch when we want to change the version. This isn't quite ideal and pretty much defeats the purpose of using a tool as we can already do this easily vis Powershell. What we were hoping to be able to do was use it's ability to review existing branches (e.g. the release branches) and increment the minor version from there (unless a Git tag existed). No scanning of commits, no looking at feature branches, just take the latest `release/x.y.z` branch and increment by one.

**Comment by pi3k14** [comment]
>  just take the latest release/x.y.z branch and increment by one

You can do that, but you have to merge that branch into whatever branch you want an increase in version number (and configure GitVersion to track the source branch). What you describe here is GitFlow.

You seems to have an workflow where you decides the version number after you have created a new version, that is not what neither GithubFlow nor GitFlow is about (from GitVersion perspective).

Nevertheless, tag your code, don't create a branch when you are defining a new version. Create a branch from this tag when you need to create an out-of-line fix for this release (a hotfix branch).

If the devs don't know when to bump versions, how should GitVersion do?

If I understands you correctly you would like no increase in version after feature merge but increase in major after tag?

**Comment by CoolDadTx** [comment]
Thanks but I think we've decided that Gitversion cannot do what we want with incremental versioning. We think we'll just use it for fetching git tags and/or stick with Powershell. We were just hopeful that it could do more for us. I'll close this issue as by design for the tool. Thanks.
