### ISSUE TITLE
Identical config files are reported as ambiguous

### ISSUE THREAD

**Issue by cyanite** [GitTools/GitVersion#1964]
If you're standing in your repository root, you have to use an absolute path to a non-standard configuration file, or get the following bizarre error:

`WARN [12/04/19 10:07:23:94] An error occurred:
Ambiguous config file selection from 'C:\foo\bar\GitVersion.yml' and 'C:\foo\bar\GitVersion.yml'`

Surely, identical files aren't ambiguous.

**Comment by arturcic** [comment]
Closed by #1965

**Comment by arturcic** [comment]
Thank you so much for your contributions, @cyanite 👍
