### ISSUE TITLE
Hotfix version in merge message is ignored

### ISSUE THREAD

**Issue by cadull** [GitTools/GitVersion#1977]
Using GitFlow with the default GitVersion configuration, we can merge release/3.2 to master and the version will become 3.2.0.

Without adding a tag, merging hotfix/3.2.1 to master leaves the version as 3.2.0. I expected the version to become 3.2.1.

A workaround is to use the following configuration, but I'm not sure if this has other implications.

```
branches:
  hotfix:
    is-release-branch: true
```

**Comment by Dobriy33** [comment]
Wrong version for hotfix branches also generating when target branch is hotfix/3.2.2. Expected 3.2.2-beta.*, but actual is 3.2.0-beta.*
3.2.0 is last version of release branch that was merged into master.

**Comment by asbjornu** [comment]
Using hotfix branches as release branches is not supported without configuration. Adding `is-release-branch: true` is the correct way to make the version number in the branch name significant for version calculation.

**Comment by Dobriy33** [comment]
Yes. My mistake.
