### ISSUE TITLE
gitversion /c <commit_id_1> /url <repo_url> does not checkout the correct commit_id

### ISSUE THREAD

**Issue by SamuelEtterlen** [GitTools/GitVersion#1978]
Hi There !

I'm in a Jenkins pipeline and I try to get the release's version number .
For this, I start gitversion from the jenkinsfile like this:

bat "gitversion /output json /diag /showconfig /c c33d6cdc982eed1cb313da11d7bc17d2bfa8c06f  /url http://****:****@git.xxx.ch/scm/myrepo.git"

The commit id c33d6cdc982eed1cb313da11d7bc17d2bfa8c06f  corresponds to the HEAD of my branch, where a git Tag labelled 1.0.0 is set.

The output json file looks like this:

{
  "Major":19,
  "Minor":57,
  "Patch":1,
  "PreReleaseTag":"1-0-0.1",
  "PreReleaseTagWithDash":"-1-0-0.1",
  "PreReleaseLabel":"1-0-0",
  "PreReleaseNumber":1,
  "WeightedPreReleaseNumber":1,
  "BuildMetaData":365,
  "BuildMetaDataPadded":"0365",
  "FullBuildMetaData":"365.Branch.1.0.0.Sha.2245d03b82fe0ca2301e3a73a10e49f082b4832b",
  "MajorMinorPatch":"19.57.1",
  "SemVer":"19.57.1-1-0-0.1",
  "LegacySemVer":"19.57.1-1-0-0-1",
  "LegacySemVerPadded":"19.57.1-1-0-0-0001",
  "AssemblySemVer":"19.57.1.0",
  "AssemblySemFileVer":"19.57.1.0",
  "FullSemVer":"19.57.1-1-0-0.1+365",
  "InformationalVersion":"19.57.1-1-0-0.1+365.Branch.1.0.0.Sha.2245d03b82fe0ca2301e3a73a10e49f082b4832b",
  "BranchName":"1.0.0",
  "Sha":"2245d03b82fe0ca2301e3a73a10e49f082b4832b",
  "ShortSha":"2245d03",
  "NuGetVersionV2":"19.57.1-1-0-0-0001",
  "NuGetVersion":"19.57.1-1-0-0-0001",
  "NuGetPreReleaseTagV2":"1-0-0-0001",
  "NuGetPreReleaseTag":"1-0-0-0001",
  "VersionSourceSha":"72acdf255123a69c6df4af9904ccc1db41f90c3e",
  "CommitsSinceVersionSource":365,
  "CommitsSinceVersionSourcePadded":"0365",
  "CommitDate":"2019-12-09"
}

As you can see, the Sha value 2245d03b82fe0ca2301e3a73a10e49f082b4832b is different as the given commit id c33d6cdc982eed1cb313da11d7bc17d2bfa8c06f.

2245d03b82fe0ca2301e3a73a10e49f082b4832b is just a previous commit from the branch where the tag is set:

![image](https://user-images.githubusercontent.com/26928746/70506100-d76bd980-1b29-11ea-9e85-56827da2ce8c.png)

The previous existing tag in the correct semantic format is 19.57.0. Thus, the calculated new version number is 19.57.1. But, as I said before, I gave the commit id c33d6cdc982eed1cb313da11d7bc17d2bfa8c06f which is pointing to the tag 1.0.0. Thus, the version number should be extracted from the tag name and not calculated from the previous version.

Have somebody a clue ?

**Comment by asbjornu** [comment]
1. Which version of GitVersion are you using?
2. Are you passing the environment variable `Git_Branch` to GitVersion?
3. Have you ensured that the Git repository that Jenkins builds from isn't a shallow clone?
