### ISSUE TITLE
Use only Commit Hash in Directory.Build.Props and .Net Core

### ISSUE THREAD

**Issue by baruchiro** [GitTools/GitVersion#1987]
My repository is not fully compatible with `GitFlow` or something, and my task is to add the commit hash to the DLL properties.

# Initial Example

First, I created a `dotnet new console` project.

Then, I added a `Directory.Build.props` file to the project directory:

```xml
<Project InitialTargets="Version" 
  xmlns="http://schemas.microsoft.com/developer/msbuild/2003">

  <Target Name="Version">
    <CallTarget Targets="dllProps" />
  </Target>

  <Target Name="dllProps">
    <PropertyGroup>
      <Product>My Product</Product>
      <Version>1.2.3</Version>
    </PropertyGroup>
  </Target>
</Project>
```

And after `build`, the properties are:

> File version: 1.2.3.0
> Product name: My Product
> ProductVersion: 1.2.3

So, it works.

# Add `GitVersionTask`

Now I adding the `GitVersionTask` nuget to the `Directory.Build.props`:

```xml
<!-- The file above -->
  <ItemGroup>
    <PackageReference Include="GitVersionTask" Version="5.1.2">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>
</Project>
```
And the DLL properties is:

> File version: 0.1.0.0
Product name: My Product
ProductVersion: 0.1.0+0.Branch.master.Sha.4fa0d07f22b397da80265e6f82fa59efebad3297

So I think it's mean that the nuget works.

# Use `GitVersionTask` without effect

Now, I want the version to be `1.2.3`, and say, add the commit hash to the `Product` property (Just for disable auto version and using MSBuild generated property).

I trying to use:

- `<GetVersion SolutionDirectory=".">`
- `<UpdateVersionProperties>false</UpdateVersionProperties>`
- `<GenerateAssemblyInfo>false</GenerateAssemblyInfo>`
- `$(GitVersion_BranchName)`
- `<Output TaskParameter="BranchName" PropertyName="Product" />`
and any combination I can think about, but I always get this:

> File version: 0.1.0.0
Product name:
ProductVersion: 0.1.0+0.Branch.master.Sha.4fa0d07f22b397da80265e6f82fa59efebad3297

or

> File version: 0.1.0.0
Product name: MyCsprojName
ProductVersion: 0.1.0+0.Branch.master.Sha.4fa0d07f22b397da80265e6f82fa59efebad3297

I ended with this `Directory.Build.props`:

```xml
<Project InitialTargets="Version" 
  xmlns="http://schemas.microsoft.com/developer/msbuild/2003">

  <Target Name="Variables" BeforeTargets="SetGitVersion">
    <PropertyGroup>
      <!-- <UpdateVersionProperties>false</UpdateVersionProperties> -->
      <!-- <GenerateAssemblyInfo>false</GenerateAssemblyInfo> -->
    </PropertyGroup>
  </Target>

  <Target Name="dllProps" AfterTargets="SetGitVersion">
    <PropertyGroup>
      <Version>1.2.3</Version>
      <Company>My Company ;$(GitVersion_InformationalVersion);$(GitVersion_BranchName);</Company>
    </PropertyGroup>
  </Target>

  <Target Name="Version">
    <CallTarget Targets="Variables" />
    <CallTarget Targets="dllProps" />
  </Target>

  <ItemGroup>
    <PackageReference Include="GitVersionTask" Version="5.1.2">
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

  <Target Name="SetGitVersion" BeforeTargets="Build">
    <GetVersion SolutionDirectory=".">
      <Output TaskParameter="BranchName" PropertyName="Product" />
    </GetVersion>
  </Target>
</Project>
```

**Comment by asbjornu** [comment]
I'm not sure how GitVersionTask interacts with the `Version` property in MSBuild, but the way you get version `1.2.3` with GitVersion is to do `git tag 1.2.3` on the `master` branch. The idea is that you shouldn't have to hard code the version number anywhere else than in Git (through a `tag`, commit messages or the other ways it supports).
