### ISSUE TITLE
Add GitHub actions CI similar to AppVeyor

### ISSUE THREAD

**Issue by arturcic** [GitTools/GitVersion#1989]

**Comment by asbjornu** [comment]
Resolved by #1966.

**Comment by asbjornu** [comment]
Hm, I just realized this issue may be about setting up GitHub Actions for the GitVersion repository on GitHub, and not about GitVersion itself supporting GitHub Actions... 🤔

**Comment by asbjornu** [comment]
Looks like #1975 is taking a jab at this?

**Comment by arturcic** [comment]
This one was implemented
