### ISSUE TITLE
Commit count resets to 0 on merging from feature branches to develop

### ISSUE THREAD

**Issue by aryak007** [GitTools/GitVersion#1992]
Our gitflow is an obvious one and we're using `ContinuousDeployment` 

- A branch named `feature/something` is branched off from `develop`.
-  Some work is done on `feature/something`.
- Meanwhile, other branches are also created from `develop` and are worked upon.
- The branches are merged to `develop` by submitting a `PR` from the `feature` branches.
- The number of commits on the `develop` keeps on incrementing until one `merge` resets the commit count. 

We're using the docker image `gittools/gitversion-dotnetcore:linux-4.0.1` (so, our version is 4.0.1) and our issue is very closely related to these:

https://github.com/GitTools/GitVersion/issues/700
https://github.com/GitTools/GitVersion/issues/814
https://github.com/GitTools/GitVersion/issues/681

What I've figured out so far is that the counting starts as **Gitversion** detects the **merge base** and detects the count from that point. Since, we're not **rebasing**, can that be a possible reason for this behaviour? 

_Also, **will taking a new version of `GitVersion` improve our chances** of mitigating this error?_ 

The point where the **reset** happened is highlighted in blue.

**Comment by asbjornu** [comment]
As asked in https://github.com/GitTools/GitVersion/issues/814#issuecomment-566071527 it would be great if you could try out a more recent version of GitVersion to see if it behaves the same way.
