### ISSUE TITLE
Failure after shallow clone via GitHub actions/checkout@v2

### ISSUE THREAD

**Issue by gitfool** [GitTools/GitVersion#1993]
See https://github.com/actions/checkout/issues/113. I presume GitVersion can't do anything about this, except maybe improve the error message at non-diagnostic verbosity, although that may be more of a Cake build issue?

**Comment by StanleyGoldman** [comment]
This should be fixed by https://github.com/GitTools/GitVersion/pull/1966

**Comment by StanleyGoldman** [comment]
You can test it out by using the artifacts from that pull request in the appveyor artifacts from that PR.
https://ci.appveyor.com/project/GitTools/gitversion/builds/29570366/artifacts

**Comment by gitfool** [comment]
@StanleyGoldman thanks for the heads up!

**Comment by gep13** [comment]
@gitfool from the looks of your build script:

https://github.com/gitfool/Cake.Dungeon/blob/master/scripts/version.cake#L6

You aren't calling GitVersion with the buildserver argument, so I don't think that the work @StanleyGoldman is doing will take effect until to call that argument.

**Comment by matilote** [comment]
GitVersion keep failing on Github Actions due to 
> InvalidOperationException: Could not find a 'develop' or 'master' branch, neither locally nor remotely.
even after prior fetching all branches and tags

**Comment by gitfool** [comment]
@gep13 I'm looking at this just now and not sure about using `buildserver` as I also need the GitVersion variables for local builds. I guess there's no harm in calling GitVersion twice, [as done](https://github.com/cake-contrib/Cake.Recipe/blob/develop/Cake.Recipe/Content/gitversion.cake#L27) in Cake.Recipe, although I'm wondering why it [reads](https://github.com/cake-contrib/Cake.Recipe/blob/develop/Cake.Recipe/Content/gitversion.cake#L52-L57) the environment variables when it [overwrites](https://github.com/cake-contrib/Cake.Recipe/blob/develop/Cake.Recipe/Content/gitversion.cake#L72-L77) them soon after. 🤔

**Comment by gep13** [comment]
@gitfool running it twice shouldn't cause any problems.  The first execution will cache the asserted version number into the local cache file, and the second execution will simply read from that file.

The Cake.Recipe logic could well be something that needs to be looked at again, it has gone through a number of iterations, and perhaps is now wrong.

**Comment by gitfool** [comment]
@gep13 FTR, that makes [no difference](https://github.com/gitfool/Cake.Dungeon/runs/364363950#step:6:284) and it looks like I still need to avoid a shallow clone.
