### ISSUE TITLE
Infer next semantic version on any branch

### ISSUE THREAD

**Issue by nfantone** [GitTools/GitVersion#1996]
I was drawn into `GitVersion` after reading the tag line in your `README.md`:

> GitVersion looks at your git history and works out the semantic version of the commit being built.

...but I couldn't quite make that work.

I've been trying to setup `GitVersion` to infer next version numbers on a project following GitFlow. However, I noticed that the only property that seems to matter when computing the next SemVer number is `increment`. The actual git log and commits messages are completely ignored.

Here's what I mean. Given a project with a latest tag of `0.4.0` and three more `fix:` commits added afterwards + the `GitVersion.yml` shown below:

```sh
$ git log

commit ee6cc4d1317588b62307f15e9ea55e0d0de24863 (HEAD -> develop, origin/develop, refs/pipelines/1336)
Date:   Mon Dec 16 20:51:02 2019 -0300

    fix(session): extend session timeout to six months

commit a38af3f6ea94573da234bf92635b6cfa844889a7
Date:   Mon Dec 16 20:50:00 2019 -0300

    fix(sfs): prevent common js files from being downloaded from sfs

commit da8c2d2f80dc608d77f4b9de1c6504116847000a
Date:   Mon Dec 16 08:54:51 2019 -0800

    fix: include in the attachment the file used to create encounter (#217699)

commit 1aeff2869e840dbe5029205cd869c68020b7a253
Merge: af74a2f79 98f9a8e23
Date:   Fri Dec 13 12:50:18 2019 -0800

    Merge tag '0.4.0' into develop

    foo-project 0.4.0

commit 98f9a8e2304b363a686f5aa78597ad903308d661 (tag: 0.4.0, origin/master, master)
Merge: b19e0cbe4 eb317b818
Date:   Fri Dec 13 12:50:18 2019 -0800

    Merge branch 'release/0.4.0'
```

```yml
# GitVersion.yml
major-version-bump-message: "BREAKING CHANGES?:"
minor-version-bump-message: "^(feature|feat)"
patch-version-bump-message: "^fix"
```

I would expect `GitVersion` to output `0.4.1` as the next version to be released when on `develop` branch (matching log above). Instead, it **always bumps the minor version**, producing releases such as `0.5.0`, `0.6.0`, `0.7.0`, etc. forced by the `increment` setting value.

I do not want/need to _set_ the `increment` value. That would defeat the purpose of the whole automated processed. Instead, I'd need the tool to tell me which version component (major, minor or patch) needs incrementing.

How should I go about producing the expected result? Any help would be appreciated.

**Comment by asbjornu** [comment]
I think message increments work best in [`mode: Mainline`](https://gitversion.net/docs/reference/versioning-modes/mainline-development).
