### ISSUE TITLE
Regenerate for ARM64

### ISSUE THREAD

**Issue by tkstanczak** [GitTools/GitVersion#1998]
To our knowledge it will be enough to just regenerate to get ARM64 support.

        // The following tables were generated by scripts/RuntimeIdMapGenerator.csx.
        // Regenerate when upgrading LibGit2Sharp to a new version that supports more platforms.

Are we correct?

**Comment by asbjornu** [comment]
I suppose that's correct. If you regenerate and submit the results in a PR, I'm sure it will be accepted.

**Comment by arturcic** [comment]
It also depends on Libgit2Sharp to support that
