### ISSUE TITLE
GitVersionTask 5.1.3 fails on appveyor FileLoadException

### ISSUE THREAD

**Issue by casz** [GitTools/GitVersion#2009]
GitVersionTask is unable to load `Newtonsoft.Json`

Unsure what makes it fail on appveyor: https://ci.appveyor.com/project/nmklotas/gitlabapiclient/builds/29753347#L138

works just fine locally and on GitHub Action

**Comment by casz** [comment]
@arturcic seems this commit might have changed this related to packing
https://github.com/GitTools/GitVersion/commit/9d18780536c6bcaf1b46fd64dfcb1972d8edfca5

**Comment by casz** [comment]
Tested both with MSBuild and dotnet cli on AppVeyor Visual Studio 2019

```
Microsoft (R) Build Engine version 16.4.0+e901037fe for .NET Framework
Microsoft (R) Build Engine version 16.4.0+e901037fe for .NET Core
```

**Comment by casz** [comment]
Applied workaround for FileLock mentioned in #1031 which also meant I worked around the file loading issue with `Newtonsoft.Json`.

**Comment by asbjornu** [comment]
@casz, would @rose-a's suggested reorganization in https://github.com/GitTools/GitVersion/issues/1031#issuecomment-561285533 help?

**Comment by casz** [comment]
I would prefer if I could use GitVersionTask without any issues.
I believe the suggested would perhaps solve the file locking.

However unrelated to loading issues with `Newtonsoft.Json`

**Comment by asbjornu** [comment]
Thanks for the feedback, @casz. I hope we figure out the `FileLoadException` with `Newtonsoft.Json`, although I don't have any good ideas what the problem might be as of now. Do you have many other projects referencing (different versions of) `Newtonsoft.Json` in the same solution?

**Comment by casz** [comment]
GitLabApiClient reference Newtonsoft.Json v12.0.3

**Comment by casz** [comment]
I'll see if I can provide a repro :)

**Comment by casz** [comment]
https://ci.appveyor.com/project/casz/gitversiontask-fileloadexception-repro
https://github.com/casz/gitversiontask-fileloadexception-repro

I'll try some variants on the some branches

**Comment by casz** [comment]
Okay looking into the differences on the GitVersionCore.dll

v5.1.2
```
LibGit2Sharp, Version=0.26.0.0, Culture=neutral, PublicKeyToken=7cbde695407f0333
Microsoft.Extensions.DependencyInjection.Abstractions, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
Microsoft.Extensions.Options, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
YamlDotNet, Version=8.0.0.0, Culture=neutral, PublicKeyToken=ec19458f3c15af5e
```

v5.1.3
```
LibGit2Sharp, Version=0.26.0.0, Culture=neutral, PublicKeyToken=7cbde695407f0333
Microsoft.Extensions.DependencyInjection.Abstractions, Version=3.0.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
Microsoft.Extensions.Options, Version=3.0.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
Newtonsoft.Json, Version=12.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed
YamlDotNet, Version=8.0.0.0, Culture=neutral, PublicKeyToken=ec19458f3c15af5e
```

Seems that without referencing `Newtonsoft.Json` we still manage to work because GitVersionTask is running inside the MSBuild context which has Newtonsoft.Json loaded.

**Comment by casz** [comment]
I'd like to question the usage of newtonsoft.json as it is only used here: https://github.com/GitTools/GitVersion/blob/0e9abcdc2ee4cae30ae41d715bb25169368f76ae/src/GitVersionCore/BuildServers/AppVeyor.cs

**Comment by asbjornu** [comment]
Seeing how `/output json` manages to do without `Newtonsoft.Json`, I have to agree, @casz. The `JsonOutputFormatter.ToJson()` method could probably be duplicated and modified to serve the need of AppVeyor as well.

https://github.com/GitTools/GitVersion/blob/0e9abcdc2ee4cae30ae41d715bb25169368f76ae/src/GitVersionCore/OutputFormatters/JsonOutputFormatter.cs#L11-L28

When this code is touched, I'd like to see `JsonOutputFormatter` removed and the `ToJson` method moved to the `VersionVariables` class as its overridden `ToString` method. A PR that removes the `Newtonsoft.Json` dependency would be warmly welcomed. 🙏

**Comment by casz** [comment]
@asbjornu I doubt you need to refactor as all.

I would simply write the JSON inside appveyor. We are talking about two objects, first one is with one key value, second is with two key value.

**Comment by asbjornu** [comment]
I agree that AppVeyor's needs don't require a refactor. I still would like to see a refactor, though. 😄 You decide how large you want the PR to be, it will be appreciated no matter how small or large. 😃

**Comment by dazinator** [comment]
I am seeing this error too with one of my builds: https://ci.appveyor.com/project/dazinator/dotnet-glob/builds/30988507 - i.e unable to use json. I assume I need to revert back to 5.1.2 for this to work until a fixed release is issued i.e 5.1.4?

**Comment by ermshiperete** [comment]
Downgrading to 5.1.2 seems to work.
