### ISSUE TITLE
Dependency Microsoft.Extensions.DependencyInjection copied to project output folder

### ISSUE THREAD

**Issue by ThomasBarnekow** [GitTools/GitVersion#2020]
GitVersionTask v5.1.3 introduces a dependency on `Microsoft.Extensions.DependencyInjection` for .NETFramework 4.7.2 as well as .NETCoreapp 2.1 and 3.1. 

After retargeting my solution to net472, the above dependency (and indirectly `Microsoft.Extensions.DependencyInjection.Abstraction`) is added to my solution as well. Further, both DLLs are copied to the project output folders, where they will be harvested by my WiX installer and, thus, included in the redistributable I am building.

I would expect `GitVersionTask` and all of its dependencies to be build-time dependencies. Like `GitVersionTask` itself, those DLLs should not be copied to the output folders.

**Comment by ThomasBarnekow** [comment]
Looking at [GitVersionTask.csproj](https://github.com/GitTools/GitVersion/blob/master/src/GitVersionTask/GitVersionTask.csproj), I found that all dependencies are marked as private, except for `Microsoft.Extensions.DependencyInjection`:

```xml
<ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="3.0.1" />
    <PackageReference Include="LibGit2Sharp" Version="$(PackageVersion_LibGit2Sharp)" PrivateAssets="All" />
</ItemGroup>

<ItemGroup>
    <ProjectReference Include="..\GitVersionTask.MsBuild\GitVersionTask.MsBuild.csproj" PrivateAssets="All" />
    <ProjectReference Include="..\GitVersionCore\GitVersionCore.csproj" PrivateAssets="All" />
</ItemGroup>
```

This seems to be an oversight. Right?

**Comment by arturcic** [comment]
Actually not, I have tried to put it to private but for some reason when publishing the dll does not get copied to the output, and that's only for that particular package. Did not have the time to investigate why

**Comment by ThomasBarnekow** [comment]
@arturcic, that's interesting. I built and deployed my fix and the output folder includes the dependencies. Have a look at the GitVersionTask NuGet package in my GitHub release [5.1.4-fix-make-dependency-injection-private.1+17.build.1](https://github.com/ThomasBarnekow/GitVersion/releases/tag/5.1.4-fix-make-dependency-injection-private.1%2B17.build.1).

When you download and look at GitVersionTask.5.1.4-fix-make-dependency1.17.nupkg (e.g., appending .zip to the file name), you should see the following in the `tools\net472` folder:

![image](https://user-images.githubusercontent.com/8481516/71781576-a10e6680-2fd0-11ea-8cbc-040e88e6bb79.png)

An interesting difference is that the `tools\netstandard2.0` folder does not include the `Microsoft.Extensions.DependencyInjection.dll` assembly.

![image](https://user-images.githubusercontent.com/8481516/71781645-5b05d280-2fd1-11ea-9ca0-e79ac4c0ee97.png)

However, I am not sure whether this is the issue you were having. If so, it might be possible to solve that by defining conditions on that one `PackageReference`.

**Comment by dazinator** [comment]
> An interesting difference is that the tools\netstandard2.0 folder does not include the Microsoft.Extensions.DependencyInjection.dll assembly.

Any ideas why that assembly isn't output when doing a `dotnet build` or `dotnet publish` of GitVersionTask project?

I can see that it is inside the `5.1.4-beta1.220` version of the package but wondering how it gets there..

I am doing a `dotnet publish -f netcoreapp2.1` and this is my output in the publish folder:

![image](https://user-images.githubusercontent.com/3176632/75994141-6783aa00-5ef2-11ea-803c-a7b5bb2d9544.png)

**Comment by dazinator** [comment]
This is the only way I could force it to be published, by modifying the csproj file. Will include this in my eventual PR:
```

 <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="$(PackageVersion_MicrosoftExtensions)" PrivateAssets="All">
            <Publish>true</Publish>
        </PackageReference>
```

**Comment by arturcic** [comment]
@dazinator https://github.com/GitTools/GitVersion/blob/7fba886494820a33ae9104fd238a318464603c5a/src/GitVersionTask/nuget-files.props#L34

**Comment by arturcic** [comment]
I also noticed it was not copied on publish, I guess we can use your approach instead
