### ISSUE TITLE
Ignore version range

### ISSUE THREAD

**Issue by wiruzman** [GitTools/GitVersion#2027]
Is it possible to ignore/skip a range of versions?

I'm currently on version 0.1.1 and want to skip 0.2.1-0.2.5.

I could possibly write a commit message when I reach version 0.2.1 to bump to 0.3.0, but is it possible to do it in the yml file so I dont have to remember when to do the commit message hack?

**Comment by asbjornu** [comment]
I'm not sure exactly what you mean. You can perform a `git tag <version-number>`  or write `next-version: <version-number>` in `GitVersion.yml` to enforce a version number of your `master` branch.

**Comment by wiruzman** [comment]
Yes, then I need to do it now, but I want to use still all version from 0.1.1 to 0.2.0, but skip 0.2.1 to 0.2.5 and continue 0.2.6 and so on.

**Comment by asbjornu** [comment]
Then do that manually with `git tag <version-number>`?
