### ISSUE TITLE
GitVersionTask 5.1.3: Bad Dependency on Microsoft.Extensions.DependencyInjection

### ISSUE THREAD

**Issue by rose-a** [GitTools/GitVersion#2029]
The newly introduced dependency on `Microsoft.Extensions.DependencyInjection (>= 3.0.1)` prevents the package from installing in projects which use older SDKs!

![grafik](https://user-images.githubusercontent.com/15836594/71972846-cc31c980-320d-11ea-9f96-d7a81acddbfc.png)

![grafik](https://user-images.githubusercontent.com/15836594/71972962-0ac78400-320e-11ea-8272-2c561aba5947.png)

Since the App packages are explicitly referenced by the SDK, you cannot simply upgrade to v3.0.1.

Therefore the targeted builds should reference the proper version of this dependency, i.e. `.NETCoreApp,Version=v2.1 => Microsoft.Extensions.DependencyInjection (>=2.1.0)`

**Comment by sandfield-kiwirail** [comment]
I'm using .NET Framework 4.7.2 and I'm having an issue with this too.  It says there is no dependency on `Microsoft.Extensions.DependencyInjection` but my builds fail.

I used NuGet to install `Microsoft.Extensions.DependencyInjection` manually but that doesn't resolve the problem either, it still fails to build.

I tried this with a new Console C# application and only installing GitVersionTask via NuGet

```
GitVersionTask.5.1.4-beta1.99\build\GitVersionTask.targets(10,9): error : FileNotFoundException: Could not load file or assembly 'Microsoft.Extensions.DependencyInjection.Abstractions, Version=3.0.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies. The system cannot find the file specified.
1>C:\Users\Albert\source\repos\GitVersionTaskTestApp\packages\GitVersionTask.5.1.4-beta1.99\build\GitVersionTask.targets(10,9): error :    at GitVersion.MSBuildTask.GitVersionTasks.BuildServiceProvider(GitVersionTaskBase task)
1>C:\Users\Albert\source\repos\GitVersionTaskTestApp\packages\GitVersionTask.5.1.4-beta1.99\build\GitVersionTask.targets(10,9): error :    at GitVersion.MSBuildTask.GitVersionTasks.ExecuteGitVersionTask[T](T task, Action`1 action) in D:\a\1\s\src\GitVersionTask\GitVersionTasks.cs:line 25
```

**Comment by KiLLeRRaT** [comment]
I'm using .NET Framework 4.7.2 and I'm having an issue with this too.  It says there is no dependency on `Microsoft.Extensions.DependencyInjection` but my builds fail.

I used NuGet to install `Microsoft.Extensions.DependencyInjection` manually but that doesn't resolve the problem either, it still fails to build.

I tried this with a new Console C# application and only installing GitVersionTask via NuGet

```
GitVersionTask.5.1.4-beta1.99\build\GitVersionTask.targets(10,9): error : FileNotFoundException: Could not load file or assembly 'Microsoft.Extensions.DependencyInjection.Abstractions, Version=3.0.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies. The system cannot find the file specified.
1>C:\Users\Albert\source\repos\GitVersionTaskTestApp\packages\GitVersionTask.5.1.4-beta1.99\build\GitVersionTask.targets(10,9): error :    at GitVersion.MSBuildTask.GitVersionTasks.BuildServiceProvider(GitVersionTaskBase task)
1>C:\Users\Albert\source\repos\GitVersionTaskTestApp\packages\GitVersionTask.5.1.4-beta1.99\build\GitVersionTask.targets(10,9): error :    at GitVersion.MSBuildTask.GitVersionTasks.ExecuteGitVersionTask[T](T task, Action`1 action) in D:\a\1\s\src\GitVersionTask\GitVersionTasks.cs:line 25
```
