### ISSUE TITLE
Gitversion searches on Google take you to an empty readthedocs site

### ISSUE THREAD

**Issue by Alkrun** [GitTools/GitVersion#2030]
Googling for [gitversion](https://www.google.com/search?q=gitversion) or [gitversion docs](https://www.google.com/search?q=gitversion+docs), the first hit is to [gitversion.readthedocs.io](https://gitversion.readthedocs.io/en/latest/) that has no index, etc...

I don't know the reason, maybe the docs were published there originally and they moved?  But it probably feels like a bit of a dead-end for it to be the first hit for someone trying to figure out what gitversion is.

**Comment by gep13** [comment]
@Alkrun we recently changed our documentation from being hosted on readthedocs, to now being hosted on GitHub Pages, under our own domain:

https://gitversion.net/docs/

Google search indexes should hopefully catch up soon, but in the meantime, we might want to add "something" onto the site above to re-direct folks to the new location.

**Comment by digitalsigi** [comment]
@gep13 OK I understand that thing emerge, but now there seems do be no install guidance.
I am using gitversion now for a couple of years in good old fashioned .NET projects. Now I want to use it in asp.cet core 3.1 project. When trying to install via package manager in VS 2019 I a bunch of gitversion entries. No idea which one to select. Even more, here [https://stackoverflow.com/questions/49990026/how-can-i-get-gitversion-updateassemblyinfo-to-work-with-asp-net-core-2-0-proje](url) it sounds that everything is different. OMG!
Where to find some more information / guidance how to proceed?

**Comment by gep13** [comment]
@Alkrun GitVersion comes in a number of different flavours.  There is a .Net Global Tool, there is a standard .Net Framework exe, and there are MSBuild tasks that can be added via NuGet packages.  I personally prefer using the .Net Global Tool and executing that as part of my overall build process for my projects.

Yes, things have changed, but that is more to do with how MSBuild projects have changed, rather than GitVersion itself.

**Comment by asbjornu** [comment]
@gep13, would it be possible to build an RTD site that references the new documentation on gitversion.net or, even better, redirects to the new site? It looks like [redirects should be possible in RTD](https://docs.readthedocs.io/en/stable/user-defined-redirects.html), but I have never tried to use them myself.

**Comment by gep13** [comment]
I "think" something will be possible, but I would need to dig into it a little bit.

**Comment by digitalsigi** [comment]
@gep13 Oh yea, you are right, thats not a problem ob gitversion. However it would be of great help to have some info about the different flavors in the docs. 
I personally installed gitversion via choco and use the command line version and have to investigate the .net global variant. I am unclear what the actual difference means to me in my environment.
I have to care for old fashioned .NET 4.x and .net core solutions, but do not have build servers.

**Comment by gep13** [comment]
@digitalsigi we know that our docs aren't perfect, and we certainly welcome any help in this area.  We do try to break down the different forms that GitVersion comes in:

https://gitversion.net/docs/usage/usage

Although looking at that again just now, it is clear it needs some updating, as it doesn't mention the .Net Global Tool, or the GitHub actions that exist.

**Comment by gep13** [comment]
@Alkrun @digitalsigi I have been through the docs, and I have created redirects for all the original pages in the readthedocs site.  If you find any pages that aren't redirecting, please let me know.

**Comment by Alkrun** [comment]
Looks good.  I'll mention that [google search results](https://www.google.com/search?q=site%3Areadthedocs.io+gitversion) still show quite a few links to specific versions of the documentation and those [pages don't redirect](https://gitversion.readthedocs.io/en/v3.6.5/more-info/how-it-works/) but... clicking any of the links in the tree on the left takes you to the new docs site so that's a huge improvement.

Personally I wouldn't worry about that, I just figured I'd mention it.  Thanks a lot for cleaning this up, I'm sure it'll help newcomers quite a bit to end up in the right spot.

**Comment by digitalsigi** [comment]
@gep13 Thanks for your work. 
I can confirm what @Alkrun already told. Its really very, very helpful.

**Comment by gep13** [comment]
@Alkrun @digitalsigi thank you both for confirming.  I have it on my list to add specific redirects for the versioned URL's as well, but that is a bigger task.  I wanted to get "something" out there initially, and I will work on the others when I have some more time.
