### ISSUE TITLE
[Question] - How to pass paths to multiple assembly.cs in Azure DevOps Build Task

### ISSUE THREAD

**Issue by cytron201** [GitTools/GitVersion#2033]
After selecting "Update AssemblyInfo files" on the Azure DevOps Build Task (v5), the parameter for "Update Assembly File" becomes available. I can't work out how to pass multiple paths to this or if it is indeed possible. Documentation in Read The Docs and the Task Tooltip don't offer any further clarity.

If it is infact only capable of taking a single path, what's the best practice for updating a number of these in a targeted fashion? Considering the case where there are Solutions containing SDK style csproj files and the odd old style project with Assembly.cs files.

Cheers!

**Comment by asbjornu** [comment]
Sounds like a limitation in the AZDO Build Task, as [the documentation states](https://gitversion.net/docs/usage/command-line#inject-version-metadata-into-the-assembly):

> By adding `/updateassemblyinfo <filenames>` the name of AssemblyInfo file to update can be set. **This switch can accept multiple files** with the path to the file specified relative to the working directory.

**Comment by cytron201** [comment]
@asbjornu ah, i didn't check the command line docs, good spot.

As for the AZDO Build Task, i tried ; , and space separated. Perhaps i missed something like putting it all in brackets? I thought better to ask then to trial and error every combination. Happy to do a PR to the docs and help tooltip of the Task once there's a confirmed answer (unless of course it is a limitation of the Task and isn't possible).

**Comment by phatcher** [comment]
This should support the usual globbing style pattern i.e. **/*/AssemblyInfo.cs for example.

Without this you need to update the yaml everytime you add a project to the solution

**Comment by arturcic** [comment]
@phatcher I do agree with that. There are 2 ways we can achieve this,
- to handle globbing at the GitVersion tool side (I prefer this one)
- handle the globbing at the azure devops task level (in that case we need to move the issue to [actions](https://github.com/GitTools/actions) repo

**Comment by asbjornu** [comment]
I agree it would be good to support globbing internally in GitVersion. I have no idea what kind of dependencies we would have to take on to accomplish that, though.

**Comment by phatcher** [comment]
@arturcic I think this should be part of the task rather than GitVersion per se, though I suppose doing it that way makes it difficult to have equivalence for the command line tool rather than the task,

A quick first-cut might use https://www.nuget.org/packages/Glob/

**Comment by timvandenhof** [comment]
Might be related, but enabling 'update assembly info files' in the Azure DevOps task requires filling in a path to the assemblyinfo file(s). Since I have multiple and cannot specify a wildcard/glob, this was not working. The workaround I've found is not enabling 'update assembly info files' but specificying '/updateassemblyinfo' als additional argument. The GitVersion.exe does support updateassemblyinfo without specifying a path.

**Comment by hexhead404** [comment]
> Might be related, but enabling 'update assembly info files' in the Azure DevOps task requires filling in a path to the assemblyinfo file(s). Since I have multiple and cannot specify a wildcard/glob, this was not working. The workaround I've found is not enabling 'update assembly info files' but specificying '/updateassemblyinfo' als additional argument. The GitVersion.exe does support updateassemblyinfo without specifying a path.

Nice catch @timvandenhof !  That does the trick.
