### ISSUE TITLE
Random Versioning when integrated with Azure Dev Ops

### ISSUE THREAD

**Issue by samwdp** [GitTools/GitVersion#2036]
# Issue
Versioning seems to be wonkey when using Azure Dev Ops CI pipeline

# Explanation
I have got a simple GitVersion.yml file that was generated by the GitVersion.exe:

``` yaml
mode: ContinuousDeployment
branches: {}
ignore:
  sha: []
merge-message-formats: {}
```

- I am following a GitFlow brancing strategy. Initially everything was working fine. I created a feature branch and the resulting NuGet package was published 0.1.0-feature-Myfeature name.
- I then did a managed pull request into develop and the resulting build made a build version "0.1.0-alpha0049". 
I then created a RELEASE branch called release/0.1.0. This resulted in a build "0.1.0-beta0050".
-  I then did 2 pull requests from the release branch. 1 to go to master that resulted in a build number "0.1.0-ci0051", the other went into develop and the version number went to 1.1.0-alpha0006.
- I have subsequently noticed that there is a bug so i created a bug branch which resulted in a build "0.2.0-bug-mybug0007".

What am I doing wrong as the versioning from the last release does not correlate to the next beta. And how do I remove the build numbers from the build.

For extra, here is the build pipeline I am using
![Annotation 2020-01-14 095632](https://user-images.githubusercontent.com/7193913/72333955-8913a280-36b4-11ea-9207-c48d6bc34674.png)

**Comment by samwdp** [comment]
I checked the GitVersion.exe on the develop branch and this is the result

''' json
{
  "Major":0,
  "Minor":2,
  "Patch":0,
  "PreReleaseTag":"alpha.2",
  "PreReleaseTagWithDash":"-alpha.2",
  "PreReleaseLabel":"alpha",
  "PreReleaseNumber":2,
  "WeightedPreReleaseNumber":2,
  "BuildMetaData":"",
  "BuildMetaDataPadded":"",
  "FullBuildMetaData":"Branch.develop.Sha.cf675e888ace302859b1d30d7fae472a8d2eddd2",
  "MajorMinorPatch":"0.2.0",
  "SemVer":"0.2.0-alpha.2",
  "LegacySemVer":"0.2.0-alpha2",
  "LegacySemVerPadded":"0.2.0-alpha0002",
  "AssemblySemVer":"0.2.0.0",
  "AssemblySemFileVer":"0.2.0.0",
  "FullSemVer":"0.2.0-alpha.2",
  "InformationalVersion":"0.2.0-alpha.2+Branch.develop.Sha.cf675e888ace302859b1d30d7fae472a8d2eddd2",
  "BranchName":"develop",
  "Sha":"cf675e888ace302859b1d30d7fae472a8d2eddd2",
  "ShortSha":"cf675e8",
  "NuGetVersionV2":"0.2.0-alpha0002",
  "NuGetVersion":"0.2.0-alpha0002",
  "NuGetPreReleaseTagV2":"alpha0002",
  "NuGetPreReleaseTag":"alpha0002",
  "VersionSourceSha":"08f4f8fbe022d1ab51f936730475d1406be63ab6",
  "CommitsSinceVersionSource":2,
  "CommitsSinceVersionSourcePadded":"0002",
  "CommitDate":"2020-01-10"
}
'''

**Comment by asbjornu** [comment]
Are the release branches merged? Is the release-merge on `master` tagged?

**Comment by samwdp** [comment]
We use the Pull Request feature as we have a policy that means we cannot directly push to the master and develop branches unless its a Pull Request. The pull request will do whatever it does. We have not got a tag. I will try to do it manually in Azure Dev Ops and see if that is the problem

**Comment by samwdp** [comment]
I have added the tag to master and ran the pipeline again and it works. Is there a Dev Ops build pipeline task to add the tag that will use the GitVersion version number as the tag?

**Comment by asbjornu** [comment]
I don't use AZDO, so I have no idea. I would, however, recommend adding tags as a manual step, possibly assisted by tools such as [GitReleaseManager](https://github.com/GitTools/GitReleaseManager).
