### ISSUE TITLE
ContinuousDeployment - increase build metadata number always

### ISSUE THREAD

**Issue by Xandrr** [GitTools/GitVersion#2049]
Hello. Please, help me. I use GitVersion 5.
1. I have master, feature/#XXX, release/1.2.3 and feature/sprintY branches.
2. feature/sprintY is analogue for develop branch, but I recreate it every 2 weeks from master (on sprint).
3. I deploy every commit in feature/sprintY to test environment (teamcity + octopus deploy), so I turned on feature:  mode: ContinuousDeployment
4. Everyting is ok, build metadata number increased constantly, for example 1.35.0-sprint7.263 -> 1.35.0-sprint7.265.
5. I create release branch release/1.34.0 (from feature branches, because not all features from sprint branch are releasing), build it (1.34.0-beta7.+156), deploy to production and then merge to master.
6. I merge master branch to feature/sprint7 branch.
6. After this point, "build metadata counter" resets for feature/sprintY branch. So I have decreased version number and octopus deploys wrong package! 1.35.0-sprint7.265 -> 1.35.0-sprint7.**4**.

Can I do something? I need always increase my version number for "ContinuousDeployment" branch.
![GitVersionHelp](https://user-images.githubusercontent.com/41330560/72510680-ecd7d000-385a-11ea-9c19-82c86c160778.png)

**Comment by asbjornu** [comment]
Why would you create a release-branch numbered `1.34.0` when you're working on `1.35.0`? If you number the release-branch one minor increment higher than your current version, it should also increment the minor on your `feature/sprintY` branches. The build metadata will reset (by design), but since the minor is higher, you should not have version collissions.

**Comment by Xandrr** [comment]
> Why would you create a release-branch numbered `1.34.0` when you're working on `1.35.0`? If you number the release-branch one minor increment higher than your current version, it should also increment the minor on your `feature/sprintY` branches. The build metadata will reset (by design), but since the minor is higher, you should not have version collissions.

Hello. Thank you for your answer.
1) First, the version was:
```
master  hotfix/1.33.9           release/1.34.0          feature/sprint7 (current sprint)
1.33.8   1.33.9-hotfix.2+14  1.34.0-beta.1+15      1.35.0-sprint7.069
```
2) Then, 
```
master                                 release/1.34.0            feature/sprint7 (current sprint)
1.33.8                                   1.34.0-beta.6+154    1.35.0-sprint7.265
```
2) We released version 1.34, I merged release/1.34.0 to master, then master to feature/sprint7. After this merge, GitVersion generates "sprint7" version less than was before - this is my problem:
```
master  hotfix/1.34.1                                          feature/sprint7 (current sprint)
1.34.0   1.34.1-hotfix.1+6                                   1.35.0-sprint7.004
```

If I undestood you correctly, on 1) and 2) I should have versions: 1.3**4**.0-sprint7.069 and 1.3**4**.0-sprint7.265? But I have 1.**35**.0-sprint7.069 and 1.**35**.0-sprint7.265 (maybe, because release/1.34.0 branch already existed?) How can I fix it?

**Comment by Xandrr** [comment]
And, as I can see, tagging feature/sprint7 branch also resets count? But I want to tag my revisions in ContinuousDeployment mode from TeamCity - to link git and TeamCity successfull build!
![GitVersionHelp2](https://user-images.githubusercontent.com/41330560/72916333-ee216500-3d52-11ea-87e2-1e9d7fa6ca0b.png)

**Comment by asbjornu** [comment]
Yes, the count is the number of commits since the last base version. Whenever the base version moves, the commit count will reset. As long as the base version increases, this is the intended and wanted behavior.
