### ISSUE TITLE
broken image url on marketplace 

### ISSUE THREAD

**Issue by AlexKeySmith** [GitTools/GitVersion#2050]
There's a couple of broken images on: https://marketplace.visualstudio.com/items?itemName=gittools.gitversion

Both of these 404

https://raw.githubusercontent.com/GitTools/GitVersion/master/src/GitVersionTfsTask/images/build-task.png

https://raw.githubusercontent.com/GitTools/GitVersion/master/src/GitVersionTfsTask/images/builds.png

**Comment by neolution-ch** [comment]
Has this extension been discontinued? We're on Version 5.1.3, but the extension on the marketplace is on Version 5.0.1

**Comment by arturcic** [comment]
@neolution-ch, yes that one was discontinued in favor of https://marketplace.visualstudio.com/items?itemName=gittools.usegitversion. That is a temporary solution. We have moved the Azure pipeline task altogether from this repo into https://github.com/GitTools/actions. There we'll host the GitHub Actions and Azure Pipeline task for both GitVersion and the other tool GitReleaseManager. The new extension is available at https://marketplace.visualstudio.com/items?itemName=gittools.gittools but it's not ready for consumption yet.

**Comment by neolution-ch** [comment]
Alright, thanks for the quick answer 👍

**Comment by arturcic** [comment]
The links were fixed, Closing
