### ISSUE TITLE
Version is overwritten when running an Azure DevOps build with multile configurtaions

### ISSUE THREAD

**Issue by wpschaub** [GitTools/GitVersion#2057]
We're observing some strange (or works as designed) behaviour when we run the GitVersion task in a build with multiple build configurations and the build number format: PREVENTION.IAS_$(GITVERSION_MAJORMINORPATCH)_$(date:yyyyMMdd).$(date:HHmmss)($(Build.SourceBranchName))

**The first time** it works as expected:
...
Executing GenerateSetVersionMessage for 'VsoAgent'.
Executing GenerateBuildLogOutput for 'VsoAgent'.
INFO [01/20/20 23:25:54:01] Updating assembly info files
INFO [01/20/20 23:25:54:05] Found 6 files
Async Command Start: Update Build Number
Update build number to **PREVENTION.IAS_0.1.0_20200120.152545(Develop)** for build 283234
Async Command End: Update Build Number
Finishing: GitVersion

**The second time** the build is triggered it results in an unexpected behaviour:
...
Executing GenerateSetVersionMessage for 'VsoAgent'.
Executing GenerateBuildLogOutput for 'VsoAgent'.
INFO [01/20/20 23:27:02:70] Updating assembly info files
INFO [01/20/20 23:27:02:77] Found 6 files
Async Command Start: Update Build Number
Update build number to **0.1.0-alpha.7** for build 283234
Async Command End: Update Build Number
Finishing: GitVersion

Is this because the build number format is PREVENTION.IAS_**0.1.0**_20200120.152545(Develop) at this point and contains no **$(GITVERSION_MAJORMINORPATCH)** token?

**Comment by asbjornu** [comment]
How does your `GitVersion.yml` file look like?

**Comment by wpschaub** [comment]
It's a classic build pipeline, but the yaml translates to:

> steps:
> - task: gittools.gitversion.gitversion-task.GitVersion@4
>   displayName: GitVersion
>   inputs:
>     updateAssemblyInfo: true
>     preferBundledVersion: false

**Comment by wpschaub** [comment]
Has anyone tried this extension with a multi-environment build? We are moving all our continuous delivery pipelines to a single-build artifact, but have a few existing pipelines that will remain in the multi-env build model ... which seems to be breaking the GitVersion task.

**Comment by wpschaub** [comment]
Is this extension supported for Azure DevOps build pipelines in which the build does multiple transformation builds?

**Comment by mcblair** [comment]
Bump.
