### ISSUE TITLE
Configuration question

### ISSUE THREAD

**Issue by Sventric** [GitTools/GitVersion#2075]
Hi,,

It probably is just me... but i'm not understanding the configuration nor its documentation. 

Until now we always gave our nuget-packages version info by hand... the flow is pretty simplistic, we have a develop branch which is used for releasing minor versions and feature branches for prerelease packages.

The feature-branches are getting beautiful versions like 0.1.0-issues-123-0001, but after merging via a PR back to the develop branch i wish to see 0.2.0.

I set the mode to ContinuousDeployment. Set the tag to '' (empty string); increment was already Minor, so that looked good...

But I get 0.1.0-ci20, had 3 commits on the develop branch, but nothing changes; setting continuous-delivery-fallback-tag to an empty string removes the CI, but still does not increase the minor.

How can achieve this kind of versioning?

**Comment by asbjornu** [comment]
If you are able to describe your flow and the versions you expect along the way through a `RepositoryFixture`, it would be much easier to understand preceisely what you're after. Do you think you could submit a PR with one?

https://github.com/GitTools/GitVersion/blob/f0e5275d974d7bd694dad8dce0ac85e57e33b19f/src/GitVersionCore.Tests/IntegrationTests/DevelopScenarios.cs#L14-L28

**Comment by Sventric** [comment]
A PR with one is not possible from here, my employer does not allow git connections to external repositories it seems :)

But i would like to use it like below...
```C#
        [Test]
        public void NuGetPackageVersioningWithNvieBranchingModel_Light()
        {
            /*
             * In prerelease packages have the next version number with a postfix/suffix.
             *
             * We wish to make minor releases of the develop-branch and major releases from the master.
             *
             * Prerelease packages (only for internal use) are created of their feature-branches.
             *
             * For NuGet-packages we don't use release branches.
             */

            // This is active config
            var config = new Config
            {
                // ... what comes here?
            };


            using var fixture = new EmptyRepositoryFixture();

            // Begin the master-branch with a single commit.
            fixture.MakeACommit("Initial commit");
            fixture.AssertFullSemver("0.1.0");
            AssertPackageVersion("0.1.0");

            // Create the default develop-branch (version does nothing).
            fixture.BranchTo("develop");
            fixture.AssertFullSemver("0.1.0");
            AssertPackageVersion("0.1.0");

            // Create a feature-branch; a prerelease version for the next release is born.
            fixture.BranchTo("feature-issue-123");
            fixture.AssertFullSemver("0.2.0-issue-123-000");
            AssertPackageVersion("0.2.0-issue-123-000");

            // A new commit on the feature increases the commit-padding
            fixture.MakeACommit("First commit on 'feature'");
            fixture.AssertFullSemver("0.2.0-issue-123-001");
            AssertPackageVersion("0.2.0-issue-123-001");

            fixture.MakeACommit("Second commit on 'feature'");
            fixture.AssertFullSemver("0.2.0-issue-123-002");
            AssertPackageVersion("0.2.0-issue-123-002");

            // Finish the feature by merge it into the develop branch.
            fixture.Checkout("develop");
            fixture.MergeNoFF("feature-issue-123");
            fixture.AssertFullSemver("0.2.0");
            AssertPackageVersion("0.2.0");

            void AssertPackageVersion(string packageVersion)
            {
                var versionInfo = fixture.GetVersion(config);
                versionInfo.NuGetVersionV2.ShouldBe(packageVersion);
            }
        }
```

I tried a couple of different configurations but the version never seem to increase, only the commit-padding value.

**Comment by asbjornu** [comment]
Have you tried `mode: ContinuousDeployment`? See [
Incrementing per commit
](https://gitversion.net/docs/more-info/incrementing-per-commit) for more information.
