### ISSUE TITLE
How to use in docker ?

### ISSUE THREAD

**Issue by maikebing** [GitTools/GitVersion#2084]
dockerfile:
```
#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-buster-slim AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/core/sdk:3.1-buster AS build
WORKDIR /src
COPY ["IoTSharp/IoTSharp.csproj", "IoTSharp/"]
COPY ["IoTSharp.Extensions/IoTSharp.Extensions.csproj", "IoTSharp.Extensions/"]
COPY ["IoTSharp.Extensions.AspNetCore/IoTSharp.Extensions.AspNetCore.csproj", "IoTSharp.Extensions.AspNetCore/"]
RUN dotnet restore "IoTSharp/IoTSharp.csproj"
COPY . .
WORKDIR "/src/IoTSharp"
RUN dotnet build "IoTSharp.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "IoTSharp.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "IoTSharp.dll"]
```
> root/.nuget/packages/gitversiontask/5.1.3/build/GitVersionTask.targets(10,9): error : DirectoryNotFoundException: Can't find the .git directory in  [/src/IoTSharp.Extensions/IoTSharp.Extensions.csproj]
> /root/.nuget/packages/gitversiontask/5.1.3/build/GitVersionTask.targets(10,9): error :    at GitVersion.GitPreparer.GetDotGitDirectoryInternal() in D:\a\1\s\src\GitVersionCore\GitPreparer.cs:line 75 [/src/IoTSharp.Extensions/IoTSharp.Extensions.csproj]
> /root/.nuget/packages/gitversiontask/5.1.3/build/GitVersionTask.targets(10,9): error :    at GitVersion.GitPreparer.GetDotGitDirectory() in D:\a\1\s\src\GitVersionCore\GitPreparer.cs:line 25 [/src/IoTSharp.Extensions/IoTSharp.Extensions.csproj]
> /root/.nuget/packages/gitversiontask/5.1.3/build/GitVersionTask.targets(10,9): error :    at GitVersion.GitVersionCalculator.CalculateVersionVariables() in D:\a\1\s\src\GitVersionCore\GitVersionCalculator.cs:line 54 [/src/IoTSharp.Extensions/IoTSharp.Extensions.csproj]
> /root/.nuget/packages/gitversiontask/5.1.3/build/GitVersionTask.targets(10,9): error :    at GitVersion.MSBuildTask.GitVersionTaskExecutor.WriteVersionInfoToBuildLog(WriteVersionInfoToBuildLog task) in D:\a\1\s\src\GitVersionTask\GitVersionTaskExecutor.cs:line 65 [/src/IoTSharp.Extensions/IoTSharp.Extensions.csproj]
> /root/.nuget/packages/gitversiontask/5.1.3/build/GitVersionTask.targets(10,9): error :    at GitVersion.MSBuildTask.GitVersionTasks.<>c__DisplayClass3_0.<WriteVersionInfoToBuildLog>b__0(IGitVersionTaskExecutor executor) in D:\a\1\s\src\GitVersionTask\GitVersionTasks.cs:line 20 [/src/IoTSharp.Extensions/IoTSharp.Extensions.csproj]
> /root/.nuget/packages/gitversiontask/5.1.3/build/GitVersionTask.targets(10,9): error :    at GitVersion.MSBuildTask.GitVersionTasks.ExecuteGitVersionTask[T](T task, Action`1 action) in D:\a\1\s\src\GitVersionTask\GitVersionTasks.cs:line 31 [/src/IoTSharp.Extensions/IoTSharp.Extensions.csproj]
> /root/.nuget/packages/gitversiontask/5.1.3/build/GitVersionTask.targets(10,9): error :  [/src/IoTSharp.Extensions/IoTSharp.Extensions.csproj]
> /root/.nuget/packages/gitversiontask/5.1.3/build/GitVersionTask.targets(10,9): error : DirectoryNotFoundException: Can't find the .git directory in  [/src/IoTSharp.Extensions.AspNetCore/IoTSharp.Extensions.AspNetCore.csproj]
> /root/.nuget/packages/gitversiontask/5.1.3/build/GitVersionTask.targets(10,9): error :    at GitVersion.GitPreparer.GetDotGitDirectoryInternal() in D:\a\1\s\src\GitVersionCore\GitPreparer.cs:line 75 [/src/IoTSharp.Extensions.AspNetCore/IoTSharp.Extensions.AspNetCore.csproj]
> /root/.nuget/packages/gitversiontask/5.1.3/build/GitVersionTask.targets(10,9): error :    at GitVersion.GitPreparer.GetDotGitDirectory() in D:\a\1\s\src\GitVersionCore\GitPreparer.cs:line 25 [/src/IoTSharp.Extensions.AspNetCore/IoTSharp.Extensions.AspNetCore.csproj]
> /root/.nuget/packages/gitversiontask/5.1.3/build/GitVersionTask.targets(10,9): error :    at GitVersion.GitVersionCalculator.CalculateVersionVariables() in D:\a\1\s\src\GitVersionCore\GitVersionCalculator.cs:line 54 [/src/IoTSharp.Extensions.AspNetCore/IoTSharp.Extensions.AspNetCore.csproj]
> /root/.nuget/packages/gitversiontask/5.1.3/build/GitVersionTask.targets(10,9): error :    at GitVersion.MSBuildTask.GitVersionTaskExecutor.WriteVersionInfoToBuildLog(WriteVersionInfoToBuildLog task) in D:\a\1\s\src\GitVersionTask\GitVersionTaskExecutor.cs:line 65 [/src/IoTSharp.Extensions.AspNetCore/IoTSharp.Extensions.AspNetCore.csproj]
> /root/.nuget/packages/gitversiontask/5.1.3/build/GitVersionTask.targets(10,9): error :    at GitVersion.MSBuildTask.GitVersionTasks.<>c__DisplayClass3_0.<WriteVersionInfoToBuildLog>b__0(IGitVersionTaskExecutor executor) in D:\a\1\s\src\GitVersionTask\GitVersionTasks.cs:line 20 [/src/IoTSharp.Extensions.AspNetCore/IoTSharp.Extensions.AspNetCore.csproj]
> /root/.nuget/packages/gitversiontask/5.1.3/build/GitVersionTask.targets(10,9): error :    at GitVersion.MSBuildTask.GitVersionTasks.ExecuteGitVersionTask[T](T task, Action`1 action) in D:\a\1\s\src\GitVersionTask\GitVersionTasks.cs:line 31 [/src/IoTSharp.Extensions.AspNetCore/IoTSharp.Extensions.AspNetCore.csproj]
> /root/.nuget/packages/gitversiontask/5.1.3/build/GitVersionTask.targets(10,9): error :  [/src/IoTSharp.Extensions.AspNetCore/IoTSharp.Extensions.AspNetCore.csproj]
> 
> Build FAILED.
> 
> /root/.nuget/packages/gitversiontask/5.1.3/build/GitVersionTask.targets(10,9): error : DirectoryNotFoundException: Can't find the .git directory in  [/src/IoTSharp.Extensions/IoTSharp.Extensions.csproj]
> /root/.nuget/packages/gitversiontask/5.1.3/build/GitVersionTask.targets(10,9): error :    at GitVersion.GitPreparer.GetDotGitDirectoryInternal() in D:\a\1\s\src\GitVersionCore\GitPreparer.cs:line 75 [/src/IoTSharp.Extensions/IoTSharp.Extensions.csproj]
> /root/.nuget/packages/gitversiontask/5.1.3/build/GitVersionTask.targets(10,9): error :    at GitVersion.GitPreparer.GetDotGitDirectory() in D:\a\1\s\src\GitVersionCore\GitPreparer.cs:line 25 [/src/IoTSharp.Extensions/IoTSharp.Extensions.csproj]
> /root/.nuget/packages/gitversiontask/5.1.3/build/GitVersionTask.targets(10,9): error :    at GitVersion.GitVersionCalculator.CalculateVersionVariables() in D:\a\1\s\src\GitVersionCore\GitVersionCalculator.cs:line 54 [/src/IoTSharp.Extensions/IoTSharp.Extensions.csproj]
> /root/.nuget/packages/gitversiontask/5.1.3/build/GitVersionTask.targets(10,9): error :    at GitVersion.MSBuildTask.GitVersionTaskExecutor.WriteVersionInfoToBuildLog(WriteVersionInfoToBuildLog task) in D:\a\1\s\src\GitVersionTask\GitVersionTaskExecutor.cs:line 65 [/src/IoTSharp.Extensions/IoTSharp.Extensions.csproj]
> /root/.nuget/packages/gitversiontask/5.1.3/build/GitVersionTask.targets(10,9): error :    at GitVersion.MSBuildTask.GitVersionTasks.<>c__DisplayClass3_0.<WriteVersionInfoToBuildLog>b__0(IGitVersionTaskExecutor executor) in D:\a\1\s\src\GitVersionTask\GitVersionTasks.cs:line 20 [/src/IoTSharp.Extensions/IoTSharp.Extensions.csproj]
> /root/.nuget/packages/gitversiontask/5.1.3/build/GitVersionTask.targets(10,9): error :    at GitVersion.MSBuildTask.GitVersionTasks.ExecuteGitVersionTask[T](T task, Action`1 action) in D:\a\1\s\src\GitVersionTask\GitVersionTasks.cs:line 31 [/src/IoTSharp.Extensions/IoTSharp.Extensions.csproj]
> /root/.nuget/packages/gitversiontask/5.1.3/build/GitVersionTask.targets(10,9): error :  [/src/IoTSharp.Extensions/IoTSharp.Extensions.csproj]
> /root/.nuget/packages/gitversiontask/5.1.3/build/GitVersionTask.targets(10,9): error : DirectoryNotFoundException: Can't find the .git directory in  [/src/IoTSharp.Extensions.AspNetCore/IoTSharp.Extensions.AspNetCore.csproj]
> /root/.nuget/packages/gitversiontask/5.1.3/build/GitVersionTask.targets(10,9): error :    at GitVersion.GitPreparer.GetDotGitDirectoryInternal() in D:\a\1\s\src\GitVersionCore\GitPreparer.cs:line 75 [/src/IoTSharp.Extensions.AspNetCore/IoTSharp.Extensions.AspNetCore.csproj]
> /root/.nuget/packages/gitversiontask/5.1.3/build/GitVersionTask.targets(10,9): error :    at GitVersion.GitPreparer.GetDotGitDirectory() in D:\a\1\s\src\GitVersionCore\GitPreparer.cs:line 25 [/src/IoTSharp.Extensions.AspNetCore/IoTSharp.Extensions.AspNetCore.csproj]
> /root/.nuget/packages/gitversiontask/5.1.3/build/GitVersionTask.targets(10,9): error :    at GitVersion.GitVersionCalculator.CalculateVersionVariables() in D:\a\1\s\src\GitVersionCore\GitVersionCalculator.cs:line 54 [/src/IoTSharp.Extensions.AspNetCore/IoTSharp.Extensions.AspNetCore.csproj]
> /root/.nuget/packages/gitversiontask/5.1.3/build/GitVersionTask.targets(10,9): error :    at GitVersion.MSBuildTask.GitVersionTaskExecutor.WriteVersionInfoToBuildLog(WriteVersionInfoToBuildLog task) in D:\a\1\s\src\GitVersionTask\GitVersionTaskExecutor.cs:line 65 [/src/IoTSharp.Extensions.AspNetCore/IoTSharp.Extensions.AspNetCore.csproj]
> /root/.nuget/packages/gitversiontask/5.1.3/build/GitVersionTask.targets(10,9): error :    at GitVersion.MSBuildTask.GitVersionTasks.<>c__DisplayClass3_0.<WriteVersionInfoToBuildLog>b__0(IGitVersionTaskExecutor executor) in D:\a\1\s\src\GitVersionTask\GitVersionTasks.cs:line 20 [/src/IoTSharp.Extensions.AspNetCore/IoTSharp.Extensions.AspNetCore.csproj]
> /root/.nuget/packages/gitversiontask/5.1.3/build/GitVersionTask.targets(10,9): error :    at GitVersion.MSBuildTask.GitVersionTasks.ExecuteGitVersionTask[T](T task, Action`1 action) in D:\a\1\s\src\GitVersionTask\GitVersionTasks.cs:line 31 [/src/IoTSharp.Extensions.AspNetCore/IoTSharp.Extensions.AspNetCore.csproj]
> /root/.nuget/packages/gitversiontask/5.1.3/build/GitVersionTask.targets(10,9): error :  [/src/IoTSharp.Extensions.AspNetCore/IoTSharp.Extensions.AspNetCore.csproj]

**Comment by flookami** [comment]
The problem is that your .git folder is not copied to the image
in your .dockerignore file, comment this line : 
#**/.git
