### ISSUE TITLE
How to retrieve GitVersion variables in GitLab CI ?

### ISSUE THREAD

**Issue by pitetb** [GitTools/GitVersion#2085]
Hello,

Thanks for this amazing library.

I'am using dotnet core 3.1 for a library project. I added GitVersionTask nuget package in my project. I setup a custom Gitversion.yml file to manage branches and my workflow.
When I generate the project with dotnet build or dotnet pack commands locally (windows env), everything is fine.

Then, I try to put use the Gitlab-Ci tool to generate my project. My runner is the official microsoft linux container: mcr.microsoft.com/dotnet/core/sdk.
The build is working, the nuget package has the correct name following rules defined in my GitVersion.yml file... However, I would like to access later in my CI script to all the variables generated by GitVersion. How can I do that ?
The documentation is not very clear for me, apparently Gitversion task should have generated a 'gitversion.properties' file but I can't find it. The "Gitversion variables" (like GitVersion_NuGetVersion, etc..) are not exported in my environment variables.

How can I do to have access to them to use them later in my CI file?

Thank you for any help.

**Comment by asbjornu** [comment]
When GitVersion is executed, it usually just serves one purpose through its `output` argument. When run in a CI environment, the default is to output the version variables to the CI server and not to the environment. To get hold of the version variables, you might need to execute GitVersion one more time with `/output json`. We have #983 to track the wish for writing version variables to disk regardless of the `output` type.

**Comment by arturcic** [comment]
what if we allow both /output json and /output buildserver at the same time?

**Comment by asbjornu** [comment]
I don't want to think how hacky that will be to implement in the current argument parser, but that's a good alternative, @arturcic.

**Comment by arturcic** [comment]
At least something to consider

**Comment by pitetb** [comment]
Hello,
Thank you for your answer!
On my understanding, a file with all variables is already created with extension ".g.cs" on each run. With not just provide an option to copy it with to a custom path with the name "gitversion.properties". Then any CI server can read it or consider it as an artefact to use it later...

**Comment by asbjornu** [comment]
I just discovered #12, but a search of `WriteEnvVariable` through the current codebase yields no results. Not sure why this has been removed.

**Comment by gep13** [comment]
@asbjornu I wanted to re-open this, as I thought writing environment variables was still something that GitVersion did, I know I made use of this in the past.

This came up recently in the conversation with @mholo65 who also expected that this functionality existed.

@arturcic Do you know when this functionality, i.e. the writing of process environment variables, was removed?

**Comment by arturcic** [comment]
@gep13 actually it was not removed see 
https://github.com/GitTools/GitVersion/blob/master/src/GitVersionCore/BuildAgents/GitLabCi.cs#L31
https://github.com/GitTools/GitVersion/blob/master/src/GitVersionCore/Core/BuildAgentBase.cs#L39 and
https://github.com/GitTools/GitVersion/blob/d0a1bea8f9355a4a4370026e6b9c56354bf073f4/src/GitVersionCore/VersionConverters/OutputGenerator/OutputGenerator.cs#L35

The last piece is writing to the console, in the build agent specific syntax. Maybe we need to adjust that. But as far as I know different build agents have different mechanism to set the environment varibales that are available to other steps/jobs

**Comment by gep13** [comment]
@artuic just to confirm though... running locally, I wouldn't see those environment variables being created, right?

**Comment by arturcic** [comment]
as far as I remember no, as you are not running in a build agent

**Comment by gep13** [comment]
@arturcic ok, I think this might explain why @mholo65 was seeing issues, as I think this was when testing locally.  I will wait for him to confirm, and then we can close this out again.

**Comment by mholo65** [comment]
Yes!

I however solved it like this when running on Windows:
```powershell
dotnet gitversion | ConvertFrom-Json | foreach { $_.PSObject.Properties } | foreach { Set-Item "ENV:GITVERSION_$($_.Name.ToUpper())" $_.Value }
```

**Comment by gep13** [comment]
@mholo65 thanks for confirming.  I will close out this issue again.

**Comment by justmatt25** [comment]
Hey guys, so I am not quite understanding how to access these variables from the Gitlab CI pipeline. What variables would I use to access?

**Comment by davidkeaveny** [comment]
I'm in the same boat as @justmatt25 ; I've set up my .gitlab-ci.yml as follows:

```
image: mcr.microsoft.com/dotnet/core/sdk:3.1

stages:
  - build

build:
  stage: build
  before_script:
    - export PATH="$PATH:/root/.dotnet/tools"
    - dotnet tool install --global GitVersion.Tool --version 5.3.7
  script:
    - dotnet gitversion
    - dotnet build
```

but when it comes to run the `dotnet gitversion` command, it produces the following in the logs:

```
Executing "step_script" stage of the job script
$ export PATH="$PATH:/root/.dotnet/tools"
$ dotnet tool install --global GitVersion.Tool --version 5.3.7
You can invoke the tool using the following command: dotnet-gitversion
Tool 'gitversion.tool' (version '5.3.7') was successfully installed.
$ dotnet gitversion
Cleaning up file based variables
ERROR: Job failed: exit code 1
```

I've tried using `/output buildserver` as an extra parameter when running `dotnet gitversion`, as well as `/updateprojectfiles`, which when I ran it locally, correctly updated my project files with the expected versioning details.

**Comment by ennovative-pl** [comment]
Issue that @davidkeany mentioned still exists with version 5.5.1. No way of checking output or error code. Simply refuses to work on GitLab CI.
