### ISSUE TITLE
GitVersion gets confused by Windows junctions

### ISSUE THREAD

**Issue by pvandervelde** [GitTools/GitVersion#2086]
Version: 5.1.2
OS: Windows 2016 - 1607 - 14393.3443

We have added a gitversion.yml file to our repository. On my local machine that works fine, however on the build server the workspace directory is a junction pointing to another drive. When I run our build on the build server GitVersion is confused because it finds two configuration files, one in the junction location and one in the actual location. The log file says

    2020-02-09 20:00:39		INFO [02/09/20 20:00:39:42] Working directory: c:\ops\jenkins\workspace\template-reso---19a6db01
    2020-02-09 20:00:39		INFO [02/09/20 20:00:39:44] IsDynamicGitRepository: False
    2020-02-09 20:00:39		INFO [02/09/20 20:00:39:51] Returning Project Root from DotGitDirectory: c:\ops\jenkins\workspace\template-reso---19a6db01\.git\ - D:\template-reso---19a6db01\
    2020-02-09 20:00:39		WARN [02/09/20 20:00:39:53] An error occurred:
    Ambiguous config file selection from 'c:\ops\jenkins\workspace\template-reso---19a6db01\GitVersion.yml' and 'D:\template-reso---19a6db01\GitVersion.yml'

The `c:\ops\jenkins\workspace` directory is a junction pointing to `d:\`

    PS C:\ops\jenkins> dir | ?{$_.LinkType} | select FullName,LinkType,Target

    FullName                 LinkType     Target
    --------                 --------     ------
    C:\ops\jenkins\workspace SymbolicLink {D:\}

So in reality (as far as that is a thing in computers), the two files that GitVersion has found are the same file, just with different paths.

**Comment by asbjornu** [comment]
How are junctions discovered in `System.IO.*`? The only information I can find regarding this deals with the win32 APIs directly, which are out of the question. If you figure out a way to detect junctions in a cross-platform way, we are happy to review and merge a pull request.
