### ISSUE TITLE
GitVersionTask NuGet package dependencies

### ISSUE THREAD

**Issue by vdachev** [GitTools/GitVersion#2088]
Hi,

I am trying to use the "GitVersionTask" NuGet package for my .NETStandard class libraries, but since version 5.1.3 the package targets the following frameworks:

- .NETCoreApp 2.1
- .NETCoreApp 3.1
- .NETFramework 4.7.2

The lack of .NETStandard among the target frameworks makes it impossible to use the package for class libraries that target it.

**Comment by asbjornu** [comment]
Hm, did we intentionally remove `NETStandard` as a target, @arturcic?

**Comment by arturcic** [comment]
Well actually we did not change the target. Look at the targets in latest 5.3.2 version
![image](https://user-images.githubusercontent.com/1760506/81525517-a81dfa80-935d-11ea-9dd1-d6042b13ee79.png)

**Comment by arturcic** [comment]
same for version 5.1.3
![image](https://user-images.githubusercontent.com/1760506/81525683-28dcf680-935e-11ea-8185-eb37f6b66b69.png)
