### ISSUE TITLE
Support for private git repositories

### ISSUE THREAD

**Issue by nhhagen** [GitTools/GitVersion#21]
When building from private git repos and the master branch is not yet tracked or up to date the builds fails with HTTP 401 (not authenticated) when trying to fetch the branch (TC only fetches the branch it is going to build)

For quick solution user/pass could be read from TC parameters before passing to libgit2sharp

Hopefully libgit2sharp can get propper ssh support and this will not be a problem.

**Comment by danielmue** [comment]
When running _TeamCity_ on Windows it is better to replace 

* ```git```

with

* ```"%env.TEAMCITY_GIT_PATH%"```

Or agents do not have ```git``` in the ```PATH``` variable.

However - SSH connections are a problem (unknown host key).
