### ISSUE TITLE
/config doesn't show message when file doesn't exist

### ISSUE THREAD

**Issue by dnperfors** [GitTools/GitVersion#2100]
When using `gitversion /config myconfig.yml` doesn't complain when the config file is not found.

GitVersion version: 5.1.3
Expected result: At least a warning message stating that default config is used
Actual result: No message and use of incorrect configuration

**Comment by beatcracker** [comment]
I'm using [GitVersion.CommandLine v5.2.4](https://www.nuget.org/packages/GitVersion.CommandLine/5.2.4) and it doesn't show message on missing config file.

Example:

```none
gitversion.exe /config foobar

-or-

gitversion.exe /config
```

These do not yield any errors and just GitVersion just proceeds with defaults.

**Comment by beatcracker** [comment]
@arturcic

Still reproducible in `5.6.6`
```none
C:\repo> dotnet-gitversion -version
5.6.6+Branch.main.Sha.80adc3f3b8919b655adca7b796b273fb10478c3f

C:\repo> dir wh@t3ver
 Volume in drive C is OS
 Volume Serial Number is 20AF-6F43

 Directory of C:\repo

File Not Found

C:\repo> dotnet-gitversion -config wh@t3ver
{
  "Major": 0,
...
```
