### ISSUE TITLE
'InformationalVersion' is not a member of type 'GitVersion.SemanticVersionFormatValues'

### ISSUE THREAD

**Issue by robertlarkins** [GitTools/GitVersion#2103]
I have created a GitVersion.yml file that has the line
```
assembly-informational-format: '{InformationalVersion}'
```
but running GitVersion (in Azure Devops) produces the message:
```
Unable to format AssemblyInformationalVersion.  Check your format string: 'InformationalVersion' is not a member of type 'GitVersion.SemanticVersionFormatValues' (Parameter 'propertyOrFieldName')
```
InformationVersion is a property in [SemanticVersionFormatValues](https://github.com/GitTools/GitVersion/blob/master/src/GitVersionCore/SemanticVersioning/SemanticVersionFormatValues.cs) but it doesn't seem to be found. Is this an expected message due to this line in GitVersion.yml being incorrect, or is this an issue that needs investigating?

This issue has also been asked about here: https://stackoverflow.com/questions/59919614/what-should-be-assembly-informational-format-be-set-to-in-gitversion-yml

**Comment by asbjornu** [comment]
This is a bug in the documentation that should have been fixed in #2051, but I don't think that's been published yet.

**Comment by fourpastmidnight** [comment]
One thing that could be an improvement here is differentiating "properties" from "variables", which is not clear from the output of GitVersion, nor from the documentation.

For example, in this issue, I found that `assembly-informational-format` is a variable, while `InformationalVersion` is a property. The value provided to the assembly-informational-format` variable is used to generate the value for the `InformationalVersion` property.

**Comment by asbjornu** [comment]
@fourpastmidnight, I agree. A cleanup in that department would be welcome. Would you be so kind to submit a PR? 🙏

**Comment by fourpastmidnight** [comment]
@asbjornu Sorry, this fell through the cracks. I really like this tool, and so this would be a welcome improvement. I have a lot going on right now, so it might take me a while. If someone gets to it before me, please say so. Otherwise, I love contributing to OSS and would like to take a look. It just might be a couple of weeks before I could reasonably get to this.

**Comment by asbjornu** [comment]
Thanks for that, @fourpastmidnight. Just take your time, we're in no rush. :)

**Comment by asbjornu** [comment]
Ping @fourpastmidnight?
