### ISSUE TITLE
GitVersion doesn't work on Pull-Request

### ISSUE THREAD

**Issue by fedebn** [GitTools/GitVersion#2115]
Hi guys!

I'm using a MultiBranch Pipeline jenkins project to build every pull-request on my c# project located in a bitbucket server, gitVersionTask can't build the PR.

In my Pipeline i have used the following command to perform the check-out
git scm
git branch: "${env.BRANCH_NAME}"

```
gitversiontask\5.1.3\build\GitVersionTask.targets(10,9): error : InvalidOperationException: Could not find a 'develop' or 'master' branch, neither locally nor remotely. 
gitversiontask\5.1.3\build\GitVersionTask.targets(10,9): error :    at GitVersion.Configuration.BranchConfigurationCalculator.InheritBranchConfiguration(Branch targetBranch, BranchConfig branchConfiguration, IList`1 excludedInheritBranches)
gitversiontask\5.1.3\build\GitVersionTask.targets(10,9): error :    at GitVersion.Configuration.BranchConfigurationCalculator.GetBranchConfiguration(Branch targetBranch, IList`1 excludedInheritBranches)
```

**Comment by asbjornu** [comment]
I'm guessing Jenkins has done a shallow clone or that the repository is otherwise incomplete. Ensure that you have a full clone and that the `develop` and `master` branches exist locally (tracking `origin/develop` and `origin/master`).

**Comment by fedebn** [comment]
I'm uising this option for checkout:
git branch: "${env.BRANCH_NAME}", credentialsId: '.....', url: 'http://...'

**Comment by asbjornu** [comment]
Sorry, but that doesn't say me much. I don't use Jenkins myself and can only speak in general terms from the perspective of what GitVersion expects in order to work correctly. You will have to figure out how Jenkins can be adjusted in order to comply with these expectations.

**Comment by ermshiperete** [comment]
I have a similar problem, also with a multibranch Jenkins pipeline job. GitVersionTask crashes when building a PR. This is not a shallow clone.

I can reproduce it on the command line by setting the `JENKINS_URL` environment variable. The output I get from running `dotnet gitversion`:

```
INFO [04/15/20 8:06:40:15] Applicable build agent found: 'Jenkins'.
INFO [04/15/20 8:06:40:15] Working directory: /home/jenkins/workspace/SIL.BuildTasks_PR-27.test
INFO [04/15/20 8:06:40:23] Applicable build agent found: 'Jenkins'.
INFO [04/15/20 8:06:40:23] Branch from build environment: 
INFO [04/15/20 8:06:40:23] Begin: Normalizing git directory for branch ''
  INFO [04/15/20 8:06:40:33] One remote found (origin -> 'https://github.com/sillsdev/SIL.BuildTasks.git').
  INFO [04/15/20 8:06:40:34] Skipping fetching, if GitVersion does not calculate your version as expected you might need to allow fetching or use dynamic repositories
  INFO [04/15/20 8:06:40:35] Skipping update of 'refs/remotes/origin/feat/testOrigin' as it already matches the remote ref.
  INFO [04/15/20 8:06:40:36] Creating local branch from remote tracking 'refs/remotes/origin/feature/NormalizeLocalesTask'.
  INFO [04/15/20 8:06:40:43] End: Normalizing git directory for branch '' (Took: 195.66ms)
  ERROR [04/15/20 8:06:40:45] An unexpected error occurred:
LibGit2Sharp.LibGit2SharpException: ref 'refs/remotes/origin/feature/NormalizeLocalesTask' doesn't match the destination
   at LibGit2Sharp.Core.Ensure.HandleError(Int32 result)
   at LibGit2Sharp.Core.Proxy.git_refspec_rtransform(IntPtr refSpecPtr, String name)
   at LibGit2Sharp.Remote.FetchSpecTransformToSource(String reference)
   at LibGit2Sharp.BranchUpdater.GetUpstreamInformation(String canonicalName, String& remoteName, String& mergeBranchName)
   at LibGit2Sharp.BranchUpdater.SetUpstream(String upstreamBranchName)
   at LibGit2Sharp.BranchCollection.Update(Branch branch, Action`1[] actions)
   at GitVersion.Helpers.GitRepositoryHelper.CreateOrUpdateLocalBranchesFromRemoteTrackingOnes(ILog log, IRepository repo, String remoteName) in D:\a\GitVersion\GitVersion\src\GitVersionCore\Helpers\GitRepositoryHelper.cs:line 298
   at GitVersion.Helpers.GitRepositoryHelper.NormalizeGitDirectory(ILog log, IEnvironment environment, String gitDirectory, AuthenticationInfo authentication, Boolean noFetch, String currentBranch, Boolean isDynamicRepository) in D:\a\GitVersion\GitVersion\src\GitVersionCore\Helpers\GitRepositoryHelper.cs:line 41
   at GitVersion.GitPreparer.NormalizeGitDirectory(AuthenticationInfo auth, String targetBranch, String gitDirectory, Boolean isDynamicRepository) in D:\a\GitVersion\GitVersion\src\GitVersionCore\GitPreparer.cs:line 181
   at GitVersion.GitPreparer.Prepare() in D:\a\GitVersion\GitVersion\src\GitVersionCore\GitPreparer.cs:line 42
   at GitVersion.GitVersionExecutor.VerifyArgumentsAndRun(Arguments arguments) in D:\a\GitVersion\GitVersion\src\GitVersionExe\GitVersionExecutor.cs:line 61
  INFO [04/15/20 8:06:40:45] Attempting to show the current git graph (please include in issue): 
  INFO [04/15/20 8:06:40:45] Showing max of 100 commits
...
```

Interestingly, things work when I run `dotnet gitversion` a second time on the command line (but not when I trigger the build the second time).

**Comment by ermshiperete** [comment]
This is caused by a libgit2sharp bug: https://github.com/libgit2/libgit2sharp/issues/1782

This bug shows up when the remote has multiple fetch refspecs, as is the case when the repo gets cloned by a multibranch Jenkins pipeline job.

**Comment by jpc-ava** [comment]
Is there any other solution instead of @ermshiperete's workaround ? 
Such a pity to not be able to use it properly on Jenkins.

**Comment by asbjornu** [comment]
If there's anything we can do to massage the branches in GitVersion before we invoke the buggy code in libgit2sharp, that may be a venue worth investigating. If you figure out how to circumvent this in GitVersion, we will happily accept a pull request.

**Comment by jpc-ava** [comment]
I "fixed" the issue by reconfiguring the SCM to allow local branches to be available : 
> `checkout([
>     $class: 'GitSCM',
>     branches: scm.branches,
>     extensions: scm.extensions + [[$class: 'LocalBranch'], [$class: 'WipeWorkspace']],
>     userRemoteConfigs: [[credentialsId: '<credID>', url: '<GitHubUrl>']],
>     doGenerateSubmoduleConfigurations: false
> ])`
GitVersion is now working as expected and generates properly the gitversion.properties file in the Jenkins context in a Jenkins multi-branch pipeline. 

The documentation for Jenkins integration shall be updated in that way to explicitely state that multi branch pipeline won't work without that specific configuration.

**Comment by arturcic** [comment]
@jpc-ava if you don't mind can you send us a PR with the proposed changes?
