### ISSUE TITLE
Publish Windows version as zip file

### ISSUE THREAD

**Issue by TheBoneJarmer** [GitTools/GitVersion#2121]
Hi

It is just a small favor to ask, but can you publish the Windows binaries as zip files instead of tar.gz? I had to install WinRar to just extract an archive that may as well could have been a zip. I find that to be a bit ridiculous. Or publish both a zip and tar.gz for those who have some automation in place.

With kind regards,
TheBoneJarmer

**Comment by asbjornu** [comment]
All Windows installations are incomplete without the free and open source [7-zip](https://www.7-zip.org/). Closing as **WONTFIX**.

**Comment by TheBoneJarmer** [comment]
Well thanks for nothing than I guess.. A bit rude reply don't you think? I can also say the same to you: "Windows comes with a free and pre-installed zip system. Use it." If this is how you decide to respond to issues than I won't bother to open up one anymore even if it could help you out.

**Comment by asbjornu** [comment]
Sorry, I didn't mean to be rude. I just find it ridiculous that Windows is incapable of opening `.tar.gz` files after TAR and Gzip being patent unencumbered, open source and freely available archiving and compression mechanism for 41 and 27 years respectively. If you submit a pull request that adds the functionality to publish ZIP files, we'll, of course, accept it.
