### ISSUE TITLE
Incorrect statement regarding version increment with regard to SemVer.

### ISSUE THREAD

**Issue by jwdonahue** [GitTools/GitVersion#2132]
The [doc on Version Incrementing, first paragraph under Approach reads](https://gitversion.net/docs/more-info/version-increments):

> Bumping one of the version components by more than 1 in a single release means you will have gaps in your version number, which defeats the purpose of SemVer.

This is not a true a statement.  Nothing in the [SemVer spec](https://semver.org) says that version numbers should be linear or monotonic.   Any particular repository of versioned packages may in fact have gaps due to deletions, or due to skipped or dropped versions that were never published.   Skipping N versions per release is a common enough practice that all tooling should expect or support it.

The SemVer spec is agnostic regarding workflows.  The spec says exactly what it must say, to define/convey the meaning/intent of semantic versioning, and nothing more.  The following version history is perfectly acceptable:

0.1.0
1.0.0
1.2.0
1.2.5
1.2.1

While you might think that last one was pointless, the available information, beyond the release history found in the package feed, cannot convey sufficient information to make that determination, nor are pointless releases banned by the spec.  

If GitVersion is limited to increment by one, it is an arbitrary feature of your tool that has nothing to do with the purpose of SemVer.

**Comment by asbjornu** [comment]
I agree this particular sentence is a bit too opinionated. I can see why some developers would like version numbers without gaps, but demanding that all version numbers are gapless and that SemVer somehow demands this, might be going a bit too far. If you'd like to submit a PR correcting this language, I wouldn't mind merging it. Do you have suggestions for how it could be worded differently?

**Comment by jwdonahue** [comment]
I think it can be safely deleted.  At some point, if this tool provides support to bump by N, then a good bit of the page will require rework.

**Comment by jwdonahue** [comment]
PR #2133 simply removes the sentence.
