### ISSUE TITLE
How to configure GitVersion to meet this branch strategy ?

### ISSUE THREAD

**Issue by actionthomas** [GitTools/GitVersion#2145]
Hello

I'm struggling to make GitVersion work with our branching strategy (in azure devops pipelines)
Here is a diagram I hope is clear enough :
![image](https://user-images.githubusercontent.com/1763624/75550605-87b6f300-5a32-11ea-82b1-9009e644b4c5.png)

I played with the config file, but I have not been able to "force push" the version number from a release branch to master.

Does anyone have an idea on how to achieve this ?

Thomas

**Comment by asbjornu** [comment]
I think your diagram looks sensible. In what way does GitVersion deviate from your expectations?

**Comment by actionthomas** [comment]
Right now, on a commit on the release branch, gitversion doesn't automatically increment the patch version. I'm sure the problem is that I can't figure out how to set parameters right...

**Comment by asbjornu** [comment]
You may try to set `mode: ContinuousDeployment` on the `release` branch:

```yaml
branches:
  release:
    mode: ContinuousDeployment
```

[Read more about Continuous Deployment](https://gitversion.net/docs/reference/versioning-modes/continuous-deployment).

**Comment by actionthomas** [comment]
I tried to set the mode. After a commit on the release branch, the patch number is not incremented :
```json
{
  "Major":1,
  "Minor":2,
  "Patch":0,
  "PreReleaseTag":"ci.6",
  "PreReleaseTagWithDash":"-ci.6",
  "PreReleaseLabel":"ci",
  "PreReleaseNumber":6,
  "WeightedPreReleaseNumber":30006,
  "BuildMetaData":"",
  "BuildMetaDataPadded":"",
  "FullBuildMetaData":"Branch.release-1.2.Sha.06357e9826431cf8ddab9d36ba5eba4084b3daf1",
  "MajorMinorPatch":"1.2.0",
  "SemVer":"1.2.0-ci.6",
  "LegacySemVer":"1.2.0-ci6",
  "LegacySemVerPadded":"1.2.0-ci0006",
  "AssemblySemVer":"1.2.0.0",
  "AssemblySemFileVer":"1.2.0.0",
  "FullSemVer":"1.2.0-ci.6",
  "InformationalVersion":"1.2.0-ci.6+Branch.release-1.2.Sha.06357e9826431cf8ddab9d36ba5eba4084b3daf1",
  "BranchName":"release/1.2",
  "EscapedBranchName":"release-1-2",
  "Sha":"06357e9826431cf8ddab9d36ba5eba4084b3daf1",
  "ShortSha":"06357e9",
  "NuGetVersionV2":"1.2.0-ci0006",
  "NuGetVersion":"1.2.0-ci0006",
  "NuGetPreReleaseTagV2":"ci0006",
  "NuGetPreReleaseTag":"ci0006",
  "VersionSourceSha":"516bf2c79e30f1e22681c015a313cabee6053216",
  "CommitsSinceVersionSource":6,
  "CommitsSinceVersionSourcePadded":"0006",
  "CommitDate":"2020-03-09"
}
```
I messed with the options in the yml file, I haven't been able to make it change the patch number automatically.
