### ISSUE TITLE
Release: gitversion-linux-5.1.3.tar.gz is not in gzip format 

### ISSUE THREAD

**Issue by paul-michalik** [GitTools/GitVersion#2147]
The attempt to unzip [GitVersion/releases/download/5.1.3/gitversion-linux-5.1.3.tar.gz](https://github.com/GitTools/GitVersion/releases/download/5.1.3/gitversion-linux-5.1.3.tar.gz) on Ubuntu 18.04 yields: `gzip: stdin: not in gzip format`

**Comment by arturcic** [comment]
weird, were using https://cakebuild.net/api/Cake.Compression/CompressionAliases/A5D7C664 for creating the `tar.gz`

**Comment by arturcic** [comment]
I'll check it on Monday

**Comment by paul-michalik** [comment]
Please close it, my bad. If you download the file via 
```
curl https://github.com/GitTools/GitVersion/releases/download/5.1.3/gitversion-linux-5.1.3.tar.gz
``` 
then a http redirection happens and you get the redirection message as response instead of the real archive. You need to use 
```
curl https://github.com/GitTools/GitVersion/releases/download/5.1.3/gitversion-linux-5.1.3.tar.gz --location
``` 
in order to redirect to real address. I apologize for the noise!

**Comment by paul-michalik** [comment]
Closed, since not a real issue.
