### ISSUE TITLE
Different behavior between build sources vs nupkgs

### ISSUE THREAD

**Issue by migheorghe** [GitTools/GitVersion#2152]
There is a different behavior for GitVersion nupkg vs local build. 
1. using local build files I get the version as beeing latest tag + number of commits
2.  using nupks (v5.1.3, 5.1.4-beta) the version is getting reset at the latest tag and it's set as beeing the number of commits:

It's the same Gitversion.yml and I can reproduce it on my local and AzureDevOps environment.

e.g. 
My latest tag is -alpha.213 and I have 103 commits extra
1. in the first case, using local build file I get version 316 = 213+103 which is exactly what I want

> INFO [03/02/20 13:14:12:72] Base version used: Git tag 'v20.3.0-alpha.213': 20.3.0-alpha.213 with commit count source 7f90f5dc1b53bd26bb (Incremented: 20.3.0-alpha.214)
>   INFO [03/02/20 13:14:12:72] End: Calculating base versions (Took: 1,048.33ms)
>   INFO [03/02/20 13:14:12:72] 103 commits found between f90f5dc1b53bd26bb and 11e5204e7b2e29ddd452
> [....]
> Update build number to 20.3.0-alpha.316 for build 790332

2. Using nupkgs version is 103 completely ignoring my tag. In this case the log files are like bellow:

>  INFO [03/02/20 8:26:47:94] Base version used: Git tag 'v20.3.0-alpha.213': 20.3.0-alpha.213 with commit count source dc1b53bd26bb (Incremented: 20.3.0-alpha.214)
>   INFO [03/02/20 8:26:47:94] End: Calculating base versions (Took: 3,822.91ms)
>   INFO [03/02/20 8:26:47:94] 100 commits found between dc1b53bd26bb and a2d4646013f3a451a107
> [.....]
> Update build number to 20.3.0-alpha.100 for build 789876

**Comment by asbjornu** [comment]
Which `nupkg` are you using? Can you point to precisely which NuGet package you are using, including version?

**Comment by migheorghe** [comment]
Today I have been trying with this version 5.1.3+Branch.master.Sha.bef8ebc0b62b3ddd0cdafe09b66d68bbfcaf90d5
Download from nuget, extract and run locally. Bellow are the exact command line and changes in GlobalAssemblyInfo.cs

& [PATH]\GitVersion.exe /output buildserver /nocache /nofetch /updateAssemblyInfo GlobalAssemblyInfo.cs
[assembly: AssemblyVersion("20.3.0.103")]

& [SRC_PATH]\bin\Release\net472\GitVersion.exe /output buildserver /nocache /nofetch /updateAssemblyInfo GlobalAssemblyInfo.cs
[assembly: AssemblyVersion("20.3.0.316")]

**Comment by migheorghe** [comment]
Any news on this?

**Comment by asbjornu** [comment]
Can you please test with `5.1.4-beta1.220` and see whether the problem still exists?
