### ISSUE TITLE
Consuming GitVersionTask in your project with various target frameworks

### ISSUE THREAD

**Issue by dazinator** [GitTools/GitVersion#2158]
I have a project `dotnet.glob` on github that has been using GitVersionTask for a long time.
It supports a wide array of target frameworks.

Here is the proj file:

```
<PropertyGroup>
    <TargetFrameworks>netstandard1.1;netstandard2.1;netcoreapp2.1;net45;net46;net4</TargetFrameworks>
    <AssemblyName>DotNet.Glob</AssemblyName>
    <OutputType>Library</OutputType>
    <PackageId>DotNet.Glob</PackageId>
    <PackageProjectUrl>https://github.com/dazinator/DotNet.Glob</PackageProjectUrl>
    <Description>A fast globbing library for .NET applications, including .net core. Doesn't use Regex.</Description>
    <Authors>Darrell Tunnell &lt;darrell.tunnell@googlemail.com&gt;</Authors>
    <PackageLicenseUrl>https://github.com/dazinator/DotNet.Glob/blob/master/LICENSE</PackageLicenseUrl>
    <PackageTags>glob;globbing;dotnet;pattern;match</PackageTags>
    <PackageReleaseNotes>New features and fixes. See README in Github Repo.</PackageReleaseNotes>
    <RootNamespace>DotNet.Glob</RootNamespace>
  </PropertyGroup>

  <PropertyGroup Condition="  '$(TargetFramework)' == 'net4' ">
    <DefineConstants>NET40</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition="  '$(TargetFramework)' == 'netstandard2.1' OR '$(TargetFramework)' == 'netcoreapp2.1' ">
    <DefineConstants>SPAN;NEWGITVERSION</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition="  '$(Configuration)' == 'Release' ">
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>..\..\Dotnet.Glob.snk</AssemblyOriginatorKeyFile>
  </PropertyGroup>

  <ItemGroup Condition="$(DefineConstants.Contains(NEWGITVERSION))">
    <PackageReference Include="GitVersionTask" Version="5.1.4-beta1.220">
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup Condition="!$(DefineConstants.Contains(NEWGITVERSION))">
    <PackageReference Include="GitVersionTask" Version="4.0.1-beta1-65">
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

</Project>
```

It was using purely `4.0.1-beta.65` of GitVersionTask for a long time, until recently the AppVeyor builds started to break. I tried upgrading to the latest 5.1.x version of GitVersion and GitVersionTask - but that caused build errors too: https://ci.appveyor.com/project/dazinator/dotnet-glob/builds/31272810

The only solution I have found so far is demonstrated above - which is to use a combination of both the new and the old depending upon the target framework being built.

This has me wondering, with the new `checks` in place during our CI builds, it might be good to extend the coverage so we build a test csproj that targets a wider array of target frameworks.

Also I can't remember if perhaps we intentionally dropped support for projects targeting older frameworks - but I can't see why we would do that, given that this is a build time tool, the frameworks that the target project is targeting shouldn't matter..?

I am hoping by extending the checks to excercise GitVersionTask against a wider array of target frmaeworks, it might repro this issue: https://ci.appveyor.com/project/dazinator/dotnet-glob/builds/31272810

**Comment by bording** [comment]
Given that the latest packages have no dependencies, it should not matter at all what the target frameworks of the consuming projects are.

Have you tried 5.2.4 yet?

**Comment by dazinator** [comment]
Nope only 5.1, I'll give 5.2.4 a try and report back.
