### ISSUE TITLE
GitVersionApp should set exit code

### ISSUE THREAD

**Issue by gitfool** [GitTools/GitVersion#2160]
Since switching GitVersion to use generic hosting (https://github.com/GitTools/GitVersion/commit/17bfb2ec8c0816da9f5d447fe59b4818ed65e5c1), GitVersion stopped returning an exit code. This leads to [ugliness](https://github.com/GitTools/GitVersion/issues/2138#issuecomment-591237874) with tools like Cake that try to parse the non-existent json output.

**Comment by arturcic** [comment]
@gitfool do you have a fix for this?

**Comment by gitfool** [comment]
@arturcic I think so. Not completely sure, but then I can't see any other way to set the exit code.
