### ISSUE TITLE
Build fails since GitVersionTask 5.1.3

### ISSUE THREAD

**Issue by dittodhole** [GitTools/GitVersion#2163]
```txt
1>Build started 2020-03-09 10:39:58.
1>Target Clean:
1>  Target CoreClean:
1>    Deleting file ...
1>  Target ResolvePackageAssets:
1>    Target CoreClean:
1>      Deleting file ...
1>  Target _SplitProjectReferencesByFileExistence:
1>    Target GetVersion:
1>      2020-03-09 10:39:59		INFO [03/09/20 10:39:59:08] IsDynamicGitRepository: False
1>    Target GetVersion:
1>      ...\.nuget\packages\gitversiontask\5.1.3\build\GitVersionTask.targets(68,21): error MSB4064: The "NoNormalize" parameter is not supported by the "GetVersion" task. Verify the parameter exists on the task, and it is a settable public instance property.
1>      ...\.nuget\packages\gitversiontask\5.1.3\build\GitVersionTask.targets(65,9): error MSB4063: The "GetVersion" task could not be initialized with its input parameters.
1>    Done building target "GetVersion" in project ... -- FAILED.
1>
1>    Done building project ... -- FAILED.
1>    ...
1>
1>Build FAILED.
1>
1>...\.nuget\packages\gitversiontask\5.1.3\build\GitVersionTask.targets(68,21): error MSB4064: The "NoNormalize" parameter is not supported by the "GetVersion" task. Verify the parameter exists on the task, and it is a settable public instance property.
1>...\.nuget\packages\gitversiontask\5.1.3\build\GitVersionTask.targets(65,9): error MSB4063: The "GetVersion" task could not be initialized with its input parameters. 
1>    0 Warning(s)
1>    2 Error(s)
1>
1>Time Elapsed 00:00:00.18
========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========
```

The project I am building is a "Microsoft.NET.Sdk" project with net40 and net46. GitVersionTask [5.1.2](https://www.nuget.org/packages/GitVersionTask/5.1.2) runs without any issues, whereas [5.2.0](https://www.nuget.org/packages/GitVersionTask/5.2.0) still throws the same error.

**Comment by arturcic** [comment]
Can you try version 5.2.0?

**Comment by dittodhole** [comment]
@arturcic Forgot to inlcude this very detail: Still same error :(

**Comment by arturcic** [comment]
That is weird, we have integration tests that check the GitVersionTask, and they are not failing

**Comment by arturcic** [comment]
As for the version you're targeting I don't think we cover them, we target 472 and netstandard

**Comment by dittodhole** [comment]
I am a bit baffled: Why should the target matter here? GitVersionTask is running the same framework as MSBuild (hosted in VisualStudio), so there should not be any interference (I am runnig Visual Studio 2019).

**Comment by arturcic** [comment]
I'll try building using you scenario, but have little to no time to investigate at the moment

**Comment by dittodhole** [comment]
fyi

I author some task nugets myself, where I use following switch for the hosting framework (eg https://github.com/dittodhole/dotnet-SemVer.Stamp):

.targets-file of the package (located in `.nupkg/build/***.targets`)

```xml
<?xml version="1.0" encoding="utf-8"?>
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <Task_Assembly Condition="'$(MSBuildRuntimeType)' == 'Full'">$(MSBuildThisFileDirectory)..\tasks\net46\***.dll</Task_Assembly>
    <Task_Assembly Condition="'$(MSBuildRuntimeType)' == 'Core'">$(MSBuildThisFileDirectory)..\tasks\netstandard2.0\***.dll</Task_Assembly>
  </PropertyGroup>
</Project>
```

**Comment by dittodhole** [comment]
> I'll try building using you scenario, but have little to no time to investigate at the moment

Thanks for your time, appreciate it!
Anyway, workaround: keep GitVersionTask at [5.1.2](https://www.nuget.org/packages/GitVersionTask/5.1.2)

**Comment by tpaxatb** [comment]
I noticed this occuring, and it tends to happen if you have both 5.1.3 and 5.1.2 references in different projects in your solution. The issue seems to be that the msbuild driver doesn't necessarily reload the task dll on each build, so if you get a project that builds with 5.1.2 first, then one that references the 5.1.3 targets (with the new properties), the project with the 5.1.2 task dll loaded borks.

The way I found to unbork this was to ensure that all references to < 5.1.3 were removed and updated completely.

**Comment by dittodhole** [comment]
@tpaxatb Thanks for your input!

fyi - I did not have any mixed references (see downgrade commit https://github.com/dittodhole/dotnet-Caliburn.Micro.Contrib.Controller/commit/46cffaab8c108b18011caf7f2524b9796bba9b95 for verification) in my scenario.

**Comment by arthurliang** [comment]
I have suffered the issue for long time. Recently, I occasionally found workaround which you can try:

1. Remove .vs folder;
2. Remove all bin/obj folders in your project's folder;
3. Modify all your csproj file to use version 5.2.0;

Have a good luck.

**Comment by arturcic** [comment]
> I have suffered the issue for long time. Recently, I occasionally found workaround which you can try:
> 
> 1. Remove .vs folder;
> 2. Remove all bin/obj folders in your project's folder;
> 3. Modify all your csproj file to use version 5.2.0;
> 
> Have a good luck.

Taking this as solution, closing

**Comment by tpaxatb** [comment]
> > I have suffered the issue for long time. Recently, I occasionally found workaround which you can try:
> > 
> > 1. Remove .vs folder;
> > 2. Remove all bin/obj folders in your project's folder;
> > 3. Modify all your csproj file to use version 5.2.0;
> > 
> > Have a good luck.
> 
> Taking this as solution, closing

One final thing is to ensure that only the version desired exists in the local user .nuget folder (e.g C:\Users\username\.nuget on windows)
