### ISSUE TITLE
Meta: How do you tell what commit is the latest commit for a GitVersion Version number

### ISSUE THREAD

**Issue by KiLLeRRaT** [GitTools/GitVersion#2164]
Hi All,

I have a silly issue.  Hopefully it's just me missing something simple.

When I look at a version string for GitVersion e.g. `5.1.4-beta1.229`, how can I easily see what commit the last commit was for that version? **On the  GITHUB page**.

I also want to say look at commits between versions, e.g. what commits were made between `5.1.4-beta1.229` and `5.1.4-beta1.234`.

Cheers,

**Comment by asbjornu** [comment]
What do you mean with "On the GitHub page"? Can you provide a URL to what exactly it is you're thinking of?

GitVersion only cares about the current commit for which it is going to create a semantic version. To figure out changes between ranges of commits, you need to use something like [GitReleaseManager](https://github.com/GitTools/GitReleaseManager) or similar.

**Comment by KiLLeRRaT** [comment]
In Visual Studio (Or nuget.org) you see a list of Gitversion package versions:
 - 5.1.4-beta1.239
 - 5.1.4-beta1.237
 - 5.1.4-beta1.235
 - ...
 - 5.1.4-beta1.217

These are not showing as releases on the GitHub page for GitVersion anywhere as releases.  I **do** understant that they are beta packages.

How can I tell what has changed between these beta versions? Is there a screen that shows the commits between two of these versions? I don't want a nicely written release history, just the commits between the two packages is fine.

There are no tags either.  I can only see tags on full releases.

**Reasoning behind this**
Because the full releases are not very frequent, it'd be great to tell that between `5.1.4-beta1.237` and `5.1.4-beta1.239` you have upgraded _xyz library_, or changed _vuw_.  That way if anything goes astray, I can tell exactly what was changed, and revert to a previous beta version that worked.

I'm pretty sure people would benefit in this.

Possible solutions:
 - Tagging the commit with a beta tag? (Looks like it used to be done this way in the past)
 - Can we add information in the GitHub `Actions/Build` with information about the version? That way we can use the actions page and see.  Perhaps if the title had the beta tag in it


Thanks

**Comment by asbjornu** [comment]
Ah, I see.

We only tag and describe stable releases because it involves quite a bit of manual labour. Beta releases are provided as a convenience, particularly to developers who have submitted a PR that fixes a problem they've faced and need a build of GitVersion available after that PR has been merged.

If we were to require manual labour to publish beta releases, I'm sorry to say that we would simply have to stop publishing beta releases altogether.

Perhaps we can investigate the possibility of creating automatic pre-releases on GitHub, but I don't know whether we can get to a satisfactory level of quality without any manual labor for that to work. Thoughts, @arturcic?

**Comment by KiLLeRRaT** [comment]
People, I think I actually found what I was hunting for! I didn't realise that this information was inside the NuGet package.  That's great, and all I was looking for.  This way I can see what was included and what wasn't in the package :)

It MAY be worth it just having a line somewhere saying: _If you want to check which commits are included in a beta release, please check the metadata in the nuget package for the commit SHA_

![image](https://user-images.githubusercontent.com/7088084/76456643-292f4300-643c-11ea-849b-4fabe14fa67c.png)


Thanks guys!

**Comment by arturcic** [comment]
@KiLLeRRaT that's true, but only recent versions have this included since 98be0054184c9dca6444b384bd0fbc17d91305fa

**Comment by KiLLeRRaT** [comment]
That's fine by me, as long as it stays there going forward! 😄
