### ISSUE TITLE
Worktrees incorrectly calculated

### ISSUE THREAD

**Issue by tpaxatb** [GitTools/GitVersion#2165]
When running gitversion within a worktree, the version that is calculated is against the HEAD of the main repository rather than the HEAD of the worktree itself.  This is caused by the fact that the Repository object that is created is using the return from the main git directory rather than the worktree path.

I don't know how to fix this, because if I change it to either GetWorkingDirectory or GetProjectDirectory (either will work), the tests:
GitVersionCore.Tests.DynamicRepositoryTests.FindsVersionInDynamicRepo
DynamicRepositoriesShouldNotErrorWithFailedToFindGitDirectory
fail.

Obviously, the GetDotGitDirectory needs to return the actual directory so that caching works, however when in a worktree, the repository object that is created needs to be based on the worktree.

See also #1063

**Comment by asbjornu** [comment]
The current architecture has created a conflict between all features supported by GtiVersion that add flexibility around which folder and repository to consider for the version calculation, including worktrees, dynamic repositories, `GitVersion.yml` placement, etc.

Every time we make an adjustment to one of these features, one or more of the others stop working in one way or another. It's whack-a-mole. I have no idea what the solution to this is, but it's apparent that the current architecture isn't supporting how GitVersion is being used, or at least can't support all of the features simultaneously in a satisfactory manner.

I think a major refactoring is required, but I can't currently provide any assistance in how such a refactoring is supposed to be conducted or how the target architecture should look like. If you want to start a draft PR, I would be happy to assist you in your refactoring journey there, though.

**Comment by tpaxatb** [comment]
Honestly, I don't think the architecture is the problem necessarily; it is more of a lack of documentation as to what should happen when which conditions are met. A well defined and documented conditional for the DotGitDir, ProjectDir, and WorkingDir needs to be made that addresses these.  I have no idea WHAT these three directories are supposed to be. What seems to have happened is that this hasn't been really addressed.
1) What is dynamic repo, and in what conditions is it used?
2) The differences between a bare repository and a working folder with respect to the three directory types.

The libgit libraries (at least on windows and linux) is able to differentiate between working tree structure and works well.  There really is no reason why a refactoring would be required, as all of the code necessary for figuring all of this out is in the GitPreparer object already.  It just seems that the logic isn't quite right (like, why is the project directory currently returning the working folder if we are using a dynamic repository?)

**Comment by asbjornu** [comment]
Good point. The source of my lack of understanding regarding all of this could indeed have been remedied by much clearer documentation. Some of these features have been added without foreseeing exactly how they will interact with each other and how they are intended to work is largely undefined. What do you get when you combine several undefined features with each other? C++. 😆 

Jokes aside, if you have ideas on how to clarify this in both code and documentation, we would welcome one or more PRs tackling that warmly. 🙏
