### ISSUE TITLE
Commit count resetting after merge develop to release

### ISSUE THREAD

**Issue by Dobriy33** [GitTools/GitVersion#2170]
When use GitVersion with default settings I have a problem with resetting commits count source.
Sometimes we need to merge develop into release to avoid conflicts on merging release to develop. And it causes resetting of alpha tag version.
I prepared scenario to describe what's happend.
```
        using var fixture = new EmptyRepositoryFixture();
        fixture.Repository.MakeACommit();
        fixture.BranchTo("develop");
        fixture.Repository.MakeCommits(3);
        fixture.AssertFullSemver("0.1.0-alpha.3");
        fixture.BranchTo("release/0.2.0");
        fixture.Repository.MakeACommit();
        fixture.Checkout("develop");
        fixture.Repository.MakeCommits(3);
        fixture.AssertFullSemver("0.3.0-alpha.3");

        // Merge to master
        fixture.Checkout("master");
        fixture.Repository.MergeNoFF("release/0.2.0");

        // Merge to develop
        //first need to sync release with dev to avoid conflict in PR
        fixture.Checkout("release/0.2.0");
        fixture.Repository.MergeNoFF("develop");
        //than merge release to dev
        fixture.Checkout("develop");
        fixture.Repository.MergeNoFF("release/0.2.0");
        fixture.AssertFullSemver("0.3.0-alpha.5");  //but we get 0.3.0-alpha.3

        fixture.Repository.MakeACommit();

        fixture.AssertFullSemver("0.3.0-alpha.6");
```
Can it be fixed via custom config?

**Comment by asbjornu** [comment]
My expectation here is that when you merge `release/0.2.0` to `master`, it sets the version number to `0.2.0` and resets the commit count to 0. The subsequent merge to `develop` shouldn't affect the version number, afaik. This is the intended behaviour.

**Comment by Dobriy33** [comment]
> My expectation here is that when you merge `release/0.2.0` to `master`, it sets the version number to `0.2.0` and resets the commit count to 0. The subsequent merge to `develop` shouldn't affect the version number, afaik. This is the intended behaviour.

For master - yes. But develop should be versioned other way. Before creating `release/0.2.0` version in `develop` is `0.1.0-alpha.8` and after creating release next commit to develop should produce `0.2.0-alpha.1`. And while new `release/0.3.0` isn't created in develop `-alpha` tag should count each commit from `develop` for `0.2.0`.
As shown for minor release [here](https://gitversion.net/docs/git-branching-strategies/gitflow-examples)
