### ISSUE TITLE
[Bug] Parse Bitbucket 7 pull request merge message 

### ISSUE THREAD

**Issue by 7evenk** [GitTools/GitVersion#2175]
**Describe the bug**
Pull request commit message changed in Bitbucket 7. The new merge message format is not recognized.

## Expected Behavior
Bitbucket 7 merge message format should be recognized.

## Actual Behavior
Bitbucket 7 merge message format is not recognized.

## Possible Fix
Add Bitbucket 7 merge message format to the default formats.

## Steps to Reproduce
Try this commit message:

Pull request #68: Release/2.2

Merge in aaa/777 from release/2.2 to master

* commit '750aa37753dec1a85b22cc16db851187649d9e97':

## Context
I merged release/2.2 to master. Normally the the master version should be increased to 2.2 but it is still 2.1.

## Your Environment
Win 10 and Bitbucket 7.
GitVersion 5.2.2

**Comment by jogibear9988** [comment]
Same Problem on mine
