### ISSUE TITLE
[Docs] No documentation available for `/proj` and `/projArgs`

### ISSUE THREAD

**Issue by fourpastmidnight** [GitTools/GitVersion#2188]
Other than what is output by running `GitVersion /help`, there is no official documentation on the usage of the `/proj` and `/projargs` switches.

**Comment by fourpastmidnight** [comment]
I mis-read the `GitVersion /help` output. It is now clear to me what `/proj` is doing.

**Comment by arturcic** [comment]
I'd suggest to not use them as they are obsolete and will be removed in the upcoming release
