### ISSUE TITLE
[Docs] Incrementing per commit

### ISSUE THREAD

**Issue by Sebazzz** [GitTools/GitVersion#2191]
The docs on [incrementing per commit](https://gitversion.net/docs/more-info/incrementing-per-commit) point in the text to a commit graph that isn't shown on the page:

> When using the continuous deployment mode (which will increment the SemVer every commit) all builds must have a pre-release tag, except for builds which are explicitly tagged as stable.
> 
> Then the build metadata (which is the commit count) is promoted to the pre-release tag. Applying those rules *the above commit graph* would produce:

There is no commit graph 😃

**Comment by asbjornu** [comment]
Seems like [that file](https://github.com/GitTools/GitVersion/blob/master/docs/input/docs/more-info/incrementing-per-commit.md)'s history has been lost during the migration to Wyam, so I'm not sure what that diagram looked like when it was present (if it ever was). However, if you can think of how such a diagram can look like, we warmly welcome a PR. 😃

**Comment by Sebazzz** [comment]
That is exactly the problem, I don't know GitVersion well enough so I was searching some examples how it'd work. 😄

**Comment by asbjornu** [comment]
Ok, then we need to do a bit of digging to see what that diagram might have been. Thanks for pointing it out! 😃

**Comment by gep13** [comment]
@asbjornu the original file is here:

https://github.com/gep13/GitVersion/blob/f844e701d32ef002ba1bdf80288a85c0ffd5b9f6/docs/more-info/incrementing-per-commit.md

But I don't see any thing in there about a commit graph.

**Comment by asbjornu** [comment]
@gep13, thanks for the digging. Correct, there's no history for that file showing any graph either. Perhaps "incrementing per commit" is split out from another page that did contain a graph?

**Comment by gep13** [comment]
>@asbjornu said...
Perhaps "incrementing per commit" is split out from another page that did contain a graph?

On that, I am not sure.

**Comment by Leosori** [comment]
Looks like the graph on the examples page matches the description. 
https://gitversion.net/docs/examples
