### ISSUE TITLE
[Feature] Support injecting assembly information in precompiled website binary

### ISSUE THREAD

**Issue by Sebazzz** [GitTools/GitVersion#2192]
This is for `GitVersion.Task`.

**Is your feature request related to a problem? Please describe.**
For System.Web projects, during publish, it is possible to precompile the files. Usually the build process generates a temporary assembly info file, however, it does not when GitVersion is used.

## Detailed Description
Generate the proper temporary assembly info file so it will be incorporated in the generated precompiled DLL.

## Context
Currently *no* version information is stored at all in the precompiled DLL, so you can't tell from which commit, or codebase it has been compiled.

## Possible Implementation
Hook onto the correct MSBuild target, but I will need to investigate.

---

I'm happy to provide a pull request, if you give me a few pointers how you would like to integrate it in your codebase.

**Comment by arturcic** [comment]
When you have the solution please create a PR for this

**Comment by Sebazzz** [comment]
Thank you. Provided pull request #2195.
