### ISSUE TITLE
Clean the obj directory from .g.cs-files not needed anymore

### ISSUE THREAD

**Issue by sxleixer** [GitTools/GitVersion#2196]
**Is your improvement request related to a problem? Please describe.**
GitVersioonTask generates a new `GitVersionInformation_*.g.cs` and `AssemblyInfo_*.g.cs` file on every build. Ultimately bloating the whole obj-folder.

## Context
It is good practice to clean up the files not needed anymore. The more, one should be taking care of the resources of others responsibly. When searching files of other tasks, it is very hard to find them by eye.

## Possible Implementation
Create a new task which runs right before the generation tasks, removing all files which are not needed anymore. Maybe you may pick the names of the files to be AssemblyInfo.g.cs or GitVersionInformation.g.cs or porvide at least a switch to name them like this.

**Comment by asbjornu** [comment]
I agree that this would be a good addition. Are you up for fixing it in a PR?

**Comment by sxleixer** [comment]
> I agree that this would be a good addition. Are you up for fixing it in a PR?

I am up for fixing it in a PR. Is there any obstruction in the way for naming the files according to my suggestion? I will name them AssemblyInfo_GitVersionTask.g.cs and GitVersionInformation_GitVersionTask.g.cs if that is okay. Or should I simplyremove the old files?

**Comment by sxleixer** [comment]
Okay, that issue got a whole lot more puzzling. The described improvement is already in the code - somehow. Look at this snippet:
```c#
public static FileWriteInfo GetFileWriteInfo(this string intermediateOutputPath, string language, string projectFile, string outputFileName)
{
    var fileExtension = GetFileExtension(language);
    string workingDirectory, fileName;

    if (intermediateOutputPath == null)
    {
        fileName = $"{outputFileName}_{Path.GetFileNameWithoutExtension(projectFile)}_{Path.GetRandomFileName()}.g.{fileExtension}";
        workingDirectory = TempPath;
    }
    else
    {
        fileName = $"{outputFileName}.g.{fileExtension}";
        workingDirectory = intermediateOutputPath;
    }
    return new FileWriteInfo(workingDirectory, fileName, fileExtension);
}
```
In my project, which is using Core SDK, I get the result of the first branch, however, the working directory is the IntermediateOutputPath. So I get `AssemblyInfo_<MyProjectName>_<RandomString>.g.cs` inside my `obj\<Configuration>\` directory. I am using version 5.1.2 of GitVersionTask.

In GitVersionTask 5.2.4 on another project I get the wished result. Long story short. I am not fixing this issue, since I cannot reproduce it.
