### ISSUE TITLE
[Bug] Mainline doesn't support pre-release tags on master error when releasing as pre-release to GitHub

### ISSUE THREAD

**Issue by ptr727** [GitTools/GitVersion#2211]
**Describe the bug**
I am using mainline mode with a master and develop branch.
I do dev on develop and merge to master.
I have github branch rules to require the master build to succeed before allowing a merge.
I build in Azure DevOps.
I publish to github releases only for master and develop branches, I do not publish pull requests.
If the branch is develop, I set the pre-release tag for the github release.
As soon as any release includes 'alpha', subsequent runs of gitversion will fail with the error `Mainline development mode doesn't yet support pre-release tags on master`
If I go to github and delete the alpha release and the associated alpha tag, gitversion works again.

## Expected Behavior
I want to use mainline mode, tag all develop builds as pre-release, and have gitversion keep on working for all builds, even if there are alpha builds released.

## Actual Behavior
As soon as there is an alpha release gitversion fails with `Mainline development mode doesn't yet support pre-release tags on master`

## Possible Fix
Maybe treat github releases tagged as pre-release as not a pre-release on master?

## Steps to Reproduce
Delete all alpha tags and releases from github releases, build develop, succeed.
Build develop again, build fails.

## Context
Trying to mainline mode releases.

## Your Environment
DotNet Core 3.1 console app.
Code in GitHub, building in Azure DevOps.

- Version Used: GitVersion Task 5.0.1
- Operating System and version: Windows Server 2019 (Azure DevOps build host)

Project is here: https://github.com/ptr727/PlexCleaner
Yaml is here: https://raw.githubusercontent.com/ptr727/PlexCleaner/master/azure-pipelines.yml

[GitVersion.log](https://github.com/GitTools/GitVersion/files/4410545/GitVersion.log)

**Comment by pianomanjh** [comment]
duplicates #1809

**Comment by asbjornu** [comment]
Closing in favor of #1809.
