### ISSUE TITLE
[Feature] Possible to configure task to use NuGetVersion instead of full semver

### ISSUE THREAD

**Issue by lisamariet** [GitTools/GitVersion#2218]
We have nuget packages in our code, and I would like the buil,d, release, nugets etc to all follow the same naming. Since nuget does not suppoert the full semver (AFAIK) and also because I think the NuGetVersion is easier to read it would be great if it was possible to configure the task which property to use from GitVersion. 

This taks automatically updates BuildNumber to be full semver. I would like to configure the task to use NuGetVersion.

I have solved it with a inline powershell script after this task which will rename the build again to NuGetVersion, but would be nice not to have to do this.

**Comment by asbjornu** [comment]
Which task are you referring to? We have the MSBuild task, Azure DevOps task, GitHub Actions task, etc.
