### ISSUE TITLE
Ignore all incoming branches [Improvement]

### ISSUE THREAD

**Issue by tbergstedt** [GitTools/GitVersion#2219]
For our project, we want to have full control over the version numbering, i.e. it is set through GitVersion.yml and git Tags on release branches. It is the project board that controls what numbers to use in our first three digits. We are totally ignorant of any Pull Request, patch or feature branch that has been merged to the build branch.

I haven't myself managed to configure GitVersion to ignore all incoming branches, so for our project it would be a great enhancement to this system. Why? Because as it is now, the GitVersion task in our builds can take roughly 20% of the total build time - sometimes more, just for parsing all branches and deeming them to be ignored. For each branch in our repository, we get:
```
  INFO [04/02/20 13:01:14:46] Skipping update of 'refs/remotes/origin/user-branch-name' as it already matches the remote ref.
```
And while this simply is information that these branches are ignored, the process of traversing each branch can take several minutes.

So for us, it would be a great enhancement to just look at the current branch (# of commits since base and tags). Apologize if that already is possible through settings, but I have yet not found out how.

**Comment by asbjornu** [comment]
Isn't it the build system's job to ignore specific tasks or steps in the build pipeline given certain environmental differences in each build? In GitHub Actions, it's easy to disable GitVersion for all pull requests with `if: startsWith(github.ref, 'refs/pull') != true`, for example.

**Comment by tbergstedt** [comment]
Yes we could disable the task In our build system (we use Azure DevOps Server). The thing is, we don't want to disable GitVersion completely; we need the versioning functionality, and just want it to work more efficiently for us.

I totally understand that automatically calculating exact version number from incoming patches/PRs can be very useful, it's just not soemthing for us.

**Comment by asbjornu** [comment]
How do you suggest such a feature would be configured and work?

**Comment by tbergstedt** [comment]
Configuration-wise, I figure you could either add some kind of branch filter under the `ignore` section in the configuration. I say this without knowing anything about how commits are selected now, or the viability/feasibility in how to implement.

We will experiment using the `commits-before` functionality for the `ignore` section, but that might a bit too "blunt" for us, and might be possible to use only on certain branches.

**Comment by asbjornu** [comment]
If you figure out a way to configure this, please propose a syntax and perhaps even an implementation of it in a pull request. I'm not saying we definitely will merge it, but I'm also not saying we won't.

**Comment by tbergstedt** [comment]
Kind of the answer I was afraid of :). But it's only fair, so I'll try to take a look at it.
