### ISSUE TITLE
[Bug]Duplicate 'System.Reflection.Assembly...." attribute

### ISSUE THREAD

**Issue by fedebn** [GitTools/GitVersion#2226]
**Describe the bug**
After pull of repository where another user have been updated gitVersion task from version 5.1.3 to 5.2.4 is not possible to compile the solution.

## Expected Behavior
Correct compiling

## Actual Behavior
Duplicate 'System.Reflection.Assembly.XXX" attribute
![70374DEE](https://user-images.githubusercontent.com/58945352/78651038-0cadeb80-78c0-11ea-852f-4d8be94233d1.PNG)

## Your Environment
Vs2017
All project are for .net45 in sdk style

GitVersionTask 5.2.4

**Comment by asbjornu** [comment]
Can you please read through the discussion in #2163 and see whether it contains any information that may be helpful to you?

**Comment by fedebn** [comment]
I have read the issue, and me and my colleagues can't exit from this problem.
we have try all this things:
Remove .vs folder;
Remove all bin/obj folders in your project's folder;
Modify all your csproj file to use version 5.2.0;
Delete C:\Users\username.nuget on windows

**Comment by fedebn** [comment]
To resolve the problem, my colleagues have uninstalled and reinstalled visual studio. 

Now after updating a project to 5.3.X the problem is coming back.

**Comment by arturcic** [comment]
Please use the GitVersion.MsBuild. Closing
