### ISSUE TITLE
Publish gem on release

### ISSUE THREAD

**Issue by JakeGinnivan** [GitTools/GitVersion#223]
@johnsimons looks like the only way to make this work is to have an API key in a file, would you be able to set this up?

http://guides.rubygems.org/command-reference/#gem-push

**Comment by gep13** [comment]
@JakeGinnivan did we get anywhere with this one?  I have never played with gem's, so don't know where to start, but was thinking couldn't we add the build step to take the encrypted variable from TeamCity, write it to a file in the right place, and then tidy up afterwards?  A bit of a cludge, but just a thought.

**Comment by JakeGinnivan** [comment]
Owners are particular and @danielmarbach - so yeah, they need to get an API key and put in as a password parameter in teamcity. Then we can just `gem push`. Instructions at http://guides.rubygems.org/publishing/#publishing-to-rubygemsorg

**Comment by JakeGinnivan** [comment]
Bump, can someone make this happen?
