### ISSUE TITLE
[Feature] Build project if no Git history is available (instead of failing)

### ISSUE THREAD

**Issue by bkragl** [GitTools/GitVersion#2234]
It would be great to be able to compile a project even if no Git history (i.e., `.git` directory) is available. It seems unsatisfactory that the Git history is mandatory, and that the source code alone is not enough to successfully compile.

## Detailed Description

We are using GitVersionTask for the releases of the [Boogie](https://github.com/boogie-org/boogie) project. If I delete the `.git` directory from my local clone, I get the following build error

```
~/.nuget/packages/gitversiontask/5.1.2/build/GitVersionTask.targets(10,9): error : DirectoryNotFoundException: Can't find the .git directory in  [...]
```

## Context

It seems desirable to be able to compile the source code of a project without necessarily having the Git history available.

Concretely, when archiving a source code snapshot (e.g., on https://zenodo.org/) it does not feel right to include the `.git` directory.

## Possible Implementation

If no `.git` directory is found, still compile the project. Perhaps with some default version number (like `0.0.0`) and a warning. But don't fail the whole build.

**Comment by asbjornu** [comment]
Sounds like something that could be configured in `GitVersion.yml`. Pull requests are welcome!

**Comment by bkragl** [comment]
> Sounds like something that could be configured in `GitVersion.yml`. Pull requests are welcome!

Do you meant that it should already be possible to configure this, or that support for this in the configuration file has to be implemented?

**Comment by asbjornu** [comment]
Sorry for the lack of response, @bkragl. I meant that if GitVersion should support this scenario, some sort of configuration needs to be added. Since this only really applies to GitVersionTask, I suggest a pull request adding an MSBuild property to enable this behaviour would be a good solution.

**Comment by fowl2** [comment]
I think this is still a valid request

**Comment by asbjornu** [comment]
@fowl2, sure. But this still applies:

>I suggest a pull request adding an MSBuild property to enable this behaviour would be a good solution.

**Comment by oliverw** [comment]
So is there a workaround for this?

**Comment by asbjornu** [comment]
Currently no, @oliverw. But pull requests are welcome.
