### ISSUE TITLE
[Feature] Azure Devops - Add BuildId to InformationalVersion

### ISSUE THREAD

**Issue by buckleyGI** [GitTools/GitVersion#2246]
**Is your feature request related to a problem? Please describe.**

Is there a way to get more information passed to the InformationalVersion?

## Detailed Description

Currently it is 
`1.0.0+6.Branch.master.Sha.664fa830ed99f72dbcee3d3230fd1ba1d2357db6`

But we would like to add the BuildId of Azure DevOps so the assemblies are stamped as
`1.0.0+6.Branch.master.Sha.664fa830ed99f72dbcee3d3230fd1ba1d2357db6-BuildId=123`

The Azure Devops GitVersion task is updating the AssemblyInfo.cs and we are looking for a way to instruct it to add some information to the variable

Can this be done through configuration? I looked at the existing option "Additional GitVersion.exe arguments" but to somehow influence it.

## Context

Correlating a assemblies to their build id is useful as multiple builds (with different tests being executed for example) can produce the same InformationalVersion

**Comment by asbjornu** [comment]
Yes, [`assembly-informational-format`](https://gitversion.net/docs/configuration#assembly-file-versioning-format) and the other `-format` configurations can contain `env:` variables so you can include pretty much whatever you want in them.

**Comment by buckleyGI** [comment]
Thanks @asbjornu !

**Comment by asbjornu** [comment]
If this answers your question, can the issue be closed, @buckleyGI?

**Comment by buckleyGI** [comment]
Almost there thanks to your pointer. In the GitVersion.yml I specify
`assembly-informational-format: '{InformationalVersion}-BuildId.{env:BUILD_BUILDID ?? 0}`

And get back 
`'InformationalVersion' is not a member of type 'GitVersion.SemanticVersionFormatValues'`

So basically I just want to append some more buildmetadata to the good default that GitVersion is already providing (and keeping it semver compliant).

Going trough to code I hoped finding how {InformationalVersion} got constructed given the existing variables so I could reproduce it in the yml to no avail.

(I read the isue that this is expected and InformationalVersion is not available in this context. https://github.com/GitTools/GitVersion/issues/2103)

Other than that GitVersion seems to be working out of the box almost like we want 👍

**Comment by asbjornu** [comment]
Try replacing `{InformationalVersion}` with `{DefaultInformationalVersion}`. #2051 should correct that, but I don't think it's in a stable release yet.

**Comment by buckleyGI** [comment]
Thank.. again @asbjornu 

The snippet below will add some more useful metadata for Azure DevOps.

Its almost totally driven from config. For the current date some extra scripting is required.
Would a variable named {CurrentDate}  (in accordance to the existing  {CommitDate}) be a good addition to GitVersion? If so I'll create some time for a PR.

GitVersion.yml
```
assembly-informational-format: '{DefaultInformationalVersion}-BuildId.{env:BUILD_BUILDID ?? 0}-BuildDateUtc.{env:BuildDateUtc ?? 0}-CommitDateUtc.{CommitDate}'
commit-date-format: yyyyMMddTHHmmssK
```

Yaml to create the supporting env variable
```
  - powershell: |
      # The $BuildDateUtc variable is used in the GitVersion.yml file
      # The K in the below format stands for the UTC offset eg. +02:00 for CEST      
      $BuildDateUtc=Get-Date ([datetime]::UtcNow) -Format yyyyMMddTHHmmssK
      Write-Host "##vso[task.setvariable variable=BuildDateUtc]$BuildDateUtc"
      echo $BuildDateUtc

```
