### ISSUE TITLE
[Bug] Chocolatey: executable missing in GitVersion.Portable 5.3.0

### ISSUE THREAD

**Issue by akamyshanov** [GitTools/GitVersion#2252]
Chocolatey [GitVersion.Portable 5.3.0](https://chocolatey.org/packages/GitVersion.Portable/5.3.0#files) package lacks the main executable that should be at `tools/gitversion.exe`.

**5.3.0:**
<img width="1117" alt="Image 2020-05-04 at 6 07 53 PM png" src="https://user-images.githubusercontent.com/1358330/80981284-70312780-8e32-11ea-9a53-a8e0e382b7f8.png">

**5.2.4:**
<img width="1117" alt="image" src="https://user-images.githubusercontent.com/1358330/80981446-a5d61080-8e32-11ea-8a6a-dd161fcda3ad.png">

**Comment by arturcic** [comment]
Good catch, I'll check it

**Comment by jrlilly** [comment]
Same issue in Gitversion.Commandline, need another bug?

**Comment by arturcic** [comment]
Will fix them together
