### ISSUE TITLE
[Improvement] Validate GitVersion.Commandline and GitVersion.Portable artifacts

### ISSUE THREAD

**Issue by arturcic** [GitTools/GitVersion#2255]
Validate GitVersion.Commandline and GitVersion.Portable artifacts during Artifacts test stage to avoid having empty packages

**Comment by gep13** [comment]
@arturcic I am curious as to what the plan is here.  Is this something that you are planning on adding to the Cake script?

**Comment by arturcic** [comment]
Currently we have a 'test artifacts' stage where we test the msbuild task (on Windows with msbuild, in Linux with dotnet build). We also test the dotnet global tool, and the native executables. We need to test the remaining 2 artifacts - command line and chocolatey. The way I see it is to run 2 additional jobs in this stage on Windows and execute the newly built artifacts

**Comment by arturcic** [comment]
This will require both cake and yaml file to be adjusted

**Comment by gep13** [comment]
@arturcic thanks for that.  Will keep an eye on this, as I am curious to see how this will be done 😄
