### ISSUE TITLE
[Bug] GitVersion tool doesn't generate any output

### ISSUE THREAD

**Issue by nZeus** [GitTools/GitVersion#2260]
**Describe the bug**
`dotnet tool run dotnet-gitversion /verbosity Diagnostic` command doesn't produce _any_ output.

## Expected Behavior
It should produce a json output

## Actual Behavior
Does nothing. No errors, no output

## Steps to Reproduce
You can reproduce it here:
https://labs.play-with-docker.com/p/bqq0t0qosm4g0090ih90#bqq0t0qo_bqq0t2iosm4g0090iha0

```shell
docker pull mcr.microsoft.com/dotnet/core/sdk:3.1
docker run -i -t mcr.microsoft.com/dotnet/core/sdk:3.1

mkdir x
cd x

dotnet new tool-manifest
dotnet tool install --local GitVersion.Tool --version 5.3.2

git init
git config --global user.email "you@example.com"
git config --global user.name "Your Name"
git add .config/dotnet-tools.json
git commit -m "First"

dotnet tool run dotnet-gitversion /verbosity Diagnostic
```

## Your Environment
Docker image `dotnet/core/sdk:3.1`

- Version Used:
- Operating System and version: Debian 10

**Comment by asbjornu** [comment]
I'm unable to reproduce on macOS, so this may be a Debian-related issue. I believe Debian isn't fully supported, due to LibGit2Sharp not fully supporting it. Are you up to date on the details there, @arturcic?

**Comment by arturcic** [comment]
https://github.com/libgit2/libgit2sharp/issues/1725 - the Debian 10 is not supported by LibGit2Sharp,

**Comment by nZeus** [comment]
Indeed, I tried `mcr.microsoft.com/dotnet/core/sdk:3.1-alpine` and it works.

Is it possible to throw an exception (e.g. `System not supported`, or a libgit2sharp exception)?
So that users aware of why the output is empty?

**Comment by asbjornu** [comment]
It would be great to do something like that, @nZeus. But it sounds like a PITA to maintain a list of supported operating systems for **another** software project. If LibGit2Sharp had a list we could use, this would be no problem. But unfortunately they don't afaik.

**Comment by mabead** [comment]
@asbjornu I understand that it would be a PITA to maintain a **perfect** list but maintaining a list that contains the OS that you **know** will fail could save a lot of times to others. 

As said in https://github.com/GitTools/GitVersion/issues/2308, we spend about two days (total) trying to find out what was going wrong. We were migrating all our code and build to .net core 3.1 when we had this problem. Narrowing down the error took us a lot of time.

**Comment by asbjornu** [comment]
Sure, I wouldn't mind having a blacklist of known unsupported operating systems. If anyone submits a pull request implementing it, I would merge it.

**Comment by DarwinJS** [comment]
It is also happening in the container - /verbosity is ignored.

**Comment by Alex2357** [comment]
Same with me `/verbosity Diagnostic` doesn't work and this is critical to figure out how things do work. Please fix this asap to avoid raising new issues.

**Comment by nbarnwell** [comment]
I thought it was just me. The only affect `/verbosity diagnostic` has for me is to _prevent_ the `/diag` switch having any effect.

**Comment by phitattoo** [comment]
•	ดูและแก้ไขเอกสารนี้ได้ในโปรแกรม Word ในคอมพิวเตอร์ แท็บเล็ต หรือโทรศัพท์ของคุณ
•	คุณสามารถแก้ไขข้อความโดยแทรกเนื้อหา เช่น รูปภาพ รูปร่าง และตารางได้อย่างง่ายดาย แล้วบันทึกเอกสารไว้ใน Cloud ได้อย่างราบรื่นจากโปรแกรม Word บนอุปกรณ์ที่ใช้ระบบปฏิบัติการ Windows, Mac, Android หรือ iOS ของคุณ

**Comment by phitattoo** [comment]
•	ดูและแก้ไขเอกสารนี้ได้ในโปรแกรม Word ในคอมพิวเตอร์ แท็บเล็ต หรือโทรศัพท์ของคุณ
•	คุณสามารถแก้ไขข้อความโดยแทรกเนื้อหา เช่น รูปภาพ รูปร่าง และตารางได้อย่างง่ายดาย แล้วบันทึกเอกสารไว้ใน Cloud ได้อย่างราบรื่นจากโปรแกรม Word บนอุปกรณ์ที่ใช้ระบบปฏิบัติการ Windows, Mac, Android หรือ iOS ของคุณ

**Comment by phitattoo** [comment]
> I thought it was just me. The only affect `/verbosity diagnostic` has for me is to _prevent_ the `/diag` switch having any effect. This is on Windows using `dotnet-gitversion` so perhaps it's unrelated?
