### ISSUE TITLE
[Bug] Incorrect version calculation for non-master mainline

### ISSUE THREAD

**Issue by Kirill-Maurin** [GitTools/GitVersion#2268]
For a non-"master" mainline branch a version increments twice

## Expected Behavior
A version is calculated identical for any mainline branch
Test commit: https://github.com/Kirill-Maurin/GitVersion/commit/27a2220a3ad678c848582ed12c10dbdb9a58e176
1. Branch "mainline": 6.0.0
2. Branch "master": 6.0.0

## Actual Behavior
1. Branch "mainline": 7.0.0
2. Branch "master": 6.0.0

## Possible Fix
Use ```!context.CurrentBranch.IsSameBranch(mainline)``` instead hardcode ```context.CurrentBranch.FriendlyName != "master"```
https://github.com/GitTools/GitVersion/blob/ba7992f2a0c536157f1ea6c3aed19a042575c932/src/GitVersionCore/VersionCalculation/MainlineVersionCalculator.cs#L72

## Steps to Reproduce
1. Checkout test branch: https://github.com/Kirill-Maurin/GitVersion/tree/test/mainline
GitVersion: 7.0.0
2. Reset master to commit: https://github.com/Kirill-Maurin/GitVersion/commit/27a2220a3ad678c848582ed12c10dbdb9a58e176
3. Checkout master
GitVersion: 6.0.0

**Comment by JustinGrote** [comment]
I believe I am seeing behavior related to this issue, @Kirill-Maurin can you confirm or should I open a new issue?

## Steps to Reproduce

1. Have non-master mainline (production in my case)
1. Tag it as v0.8.0
1. Master is the "develop" branch for this scenario. Add a commit with +semver:minor

## Expected Result
Master gitversion is 0.9.0-beta1

## Actual Result

Master gitversion is 0.8.0-beta1. /diag logs say the base Increment was supposed to be 0.9.0. Changing mode to "continuousDeployment" produces the expected result for `master (develop)` branch, but not for `production` obviously anymore.

### Gitversion.yml
```yaml
mode: Mainline
branches:
  master:
    regex: ^prod(uction)?$
  develop:
    tag: beta
    regex: ^master$
    increment: Patch
  release:
    tag: rc
```

### Gitversion /Diag
```
INFO [05/11/20 12:19:32:63] Dumping commit graph: 
INFO [05/11/20 12:19:32:83] * 03ccc17 20 seconds ago  (HEAD -> master)
* 7880e5a 7 minutes ago
* 3b46d9c 7 minutes ago
* 2198a43 8 minutes ago  (tag: v0.8.0, production)
  INFO [05/11/20 12:19:33:22] Base version used: Git tag 'v0.8.0': 0.8.0 with commit count source 2198a43bd465bd07fcbc128abd16e85f29e12e41 (Incremented: 0.9.0)
  INFO [05/11/20 12:19:33:23] End: Calculating base versions (Took: 150.40ms)
  INFO [05/11/20 12:19:33:24] Begin: Using mainline development mode to calculate current version
    INFO [05/11/20 12:19:33:25] Found possible mainline branches: production
    INFO [05/11/20 12:19:33:26] Mainline for current branch is production
    INFO [05/11/20 12:19:33:28] Current branch (master) was branch from 2198a43bd465bd07fcbc128abd16e85f29e12e41
    INFO [05/11/20 12:19:33:29] 3 commits found between 2198a43bd465bd07fcbc128abd16e85f29e12e41 and 03ccc172d53e7ed92828ef2c8618507b49636942
  INFO [05/11/20 12:19:33:31] End: Using mainline development mode to calculate current version (Took: 67.19ms)
  INFO [05/11/20 12:19:33:31] Begin: Getting version tags from branch 'refs/heads/master'.
  INFO [05/11/20 12:19:33:33] End: Getting version tags from branch 'refs/heads/master'. (Took: 19.77ms)
  INFO [05/11/20 12:19:33:34] Running on Windows.
{
  "Major":0,
  "Minor":8,
  "Patch":0,
  "PreReleaseTag":"beta.3",
  "PreReleaseTagWithDash":"-beta.3",
  "PreReleaseLabel":"beta",
  "PreReleaseNumber":3,
  "WeightedPreReleaseNumber":3,
  "BuildMetaData":"",
  "BuildMetaDataPadded":"",
  "FullBuildMetaData":"Branch.master.Sha.03ccc172d53e7ed92828ef2c8618507b49636942",
  "MajorMinorPatch":"0.8.0",
  "SemVer":"0.8.0-beta.3",
  "LegacySemVer":"0.8.0-beta3",
  "LegacySemVerPadded":"0.8.0-beta0003",
  "AssemblySemVer":"0.8.0.0",
  "AssemblySemFileVer":"0.8.0.0",
  "FullSemVer":"0.8.0-beta.3",
  "InformationalVersion":"0.8.0-beta.3+Branch.master.Sha.03ccc172d53e7ed92828ef2c8618507b49636942",
  "BranchName":"master",
  "EscapedBranchName":"master",
  "Sha":"03ccc172d53e7ed92828ef2c8618507b49636942",
  "ShortSha":"03ccc17",
  "NuGetVersionV2":"0.8.0-beta0003",
  "NuGetVersion":"0.8.0-beta0003",
  "NuGetPreReleaseTagV2":"beta0003",
  "NuGetPreReleaseTag":"beta0003",
  "VersionSourceSha":"2198a43bd465bd07fcbc128abd16e85f29e12e41",
  "CommitsSinceVersionSource":3,
  "CommitsSinceVersionSourcePadded":"0003",
  "CommitDate":"2020-05-11"
}
```

**Comment by asbjornu** [comment]
I see you've done some work on this, @Kirill-Maurin. Would you mind submitting a pull request with your suggested fix? Preferably with a `RepositoryFixture` test that provokes the problem and verifies the fix, if possible.

**Comment by Kirill-Maurin** [comment]
> Would you mind submitting a pull request with your suggested fix?
Done

**Comment by Kirill-Maurin** [comment]
> I believe I am seeing behavior related to this issue, @Kirill-Maurin can you confirm or should I open a new issue?

No, in your case this behavior is correct for mainline mode (IMHO)
