### ISSUE TITLE
[Bug] /updateassemblyinfo filename does not work anymore

### ISSUE THREAD

**Issue by nix63** [GitTools/GitVersion#2270]
In a MSVS 2019 project I've configured a prebuild step execution with this command
gitversion /updateassemblyinfo $(SolutionDir)GlobalAssemblyInfo.cs /ensureassemblyinfo

This worked well with previous versions of GitVersion and the GlobalAssemblyInfo.cs file  was generated with the info expected

With version 5.3.2, the GlobalAssemblyInfo.cs file specified in the command line is not created and the AssemblyInfo.cs files in the solution are updated.

Is this the expected behavior?

**Comment by arturcic** [comment]
well the path of the assemblyInfo you want to update should be relative to the root folder that contains the `.git`, or relative to the directory the gitversion is run from. So in your case change the 
$(SolutionDir)GlobalAssemblyInfo.cs with the appropriate value, or

you can use the Glob pattern (also relative to the directory the tool runs)
similar to **/GlobalAssemblyInfo.cs
you can find other examples here https://github.com/GitTools/GitVersion/blob/master/src/GitVersionExe.Tests/ArgumentParserTests.cs#L307-L384

**Comment by nix63** [comment]
Sorry, the $(SolutionDir) is a Visual studio variable which is replaced at build time with the complete solution path.
But if I open a command prompt, move to the path containing .git directory and run the command 
`gitversion /updateassemblyinfo GlobalAssemblyInfo.cs /ensureassemblyinfo`
the GlobalAssemblyInfo.cs file is not created with version 5.3.2. 
In version 5.2.4 the file was created.

**Comment by arturcic** [comment]
Fixed by e92db5e

**Comment by hana26** [comment]
@arturcic I'm still facing this issue. I'm doing /updateassemblyinfo CommonAssemblyInfo.cs. However, this seems to be updating all the AssemblyInfo.cs files in my repository which is not what I want. I need to update only CommonAssemblyInfo.cs in one of the projects from the entire repository. How do I provide the path to that? 

When I did /updateassemblyinfo /<projectname>/CommonAssemblyInfo.cs, it gave me this error: "Unhandled exception. GitVersion.WarningException: Could not parse command line parameter '/<projectname>/CommonAssemblyInfo.cs'"

**Comment by hana26** [comment]
^nvm, I was able to solve it by doing /updateassemblyinfo \projectname\CommonAssemblyInfo.cs

Turns out it was updating all the AssemblyInfo.cs files if it couldn't find the file you specified or something wrong with the path.
