### ISSUE TITLE
[Bug] Latest GitVersion breaks Cake build on Bitrise

### ISSUE THREAD

**Issue by gitfool** [GitTools/GitVersion#2279]
See https://github.com/cake-build/cake/pull/2771 where I bumped `GitVersion.Tool` from `5.1.2` to `5.3.3`.

The Bitrise Ubuntu PR build [failed](https://app.bitrise.io/build/7ada89b80a1c6a61#?tab=log) with warning:
```
It looks like the branch being examined is a detached Head pointing to commit 'ff1812c'. Without a proper branch name GitVersion cannot determine the build version.
```
For comparison, another recent Bitrise Ubuntu PR build [succeeded](https://app.bitrise.io/build/18d950458009d232#?tab=log) with GitVersion `5.1.2`.

Note: the output is different between the two versions, so GitVersion behavior has changed.

**Comment by gitfool** [comment]
For the failed PR, after reverting `GitVersion.Tool` to `5.1.2`, the Bitrise Ubuntu PR build [succeeded](https://app.bitrise.io/build/2753d91ea616854d#?tab=log).

**Comment by gep13** [comment]
@gitfool this seems like the same/similar error that is being shown here:

https://github.com/GitTools/GitVersion/issues/2301#issuecomment-717766298

**Comment by devlead** [comment]
Failing logs with `5.5.0`
https://app.bitrise.io/build/4e9669a5d1464547#?tab=log
https://app.bitrise.io/build/51d261147af75205#?tab=log

Successful logs after reverting back to `5.1.2`
https://app.bitrise.io/build/04fef81325df1112#?tab=log
https://app.bitrise.io/build/9f29dd67b97eb6ad#?tab=log

**Comment by asbjornu** [comment]
Ugh. 😬 Seems like our attempt at fixing tag builds actually has made things worse. 😑

**Comment by asbjornu** [comment]
I've reopened #2301 where I've shared my findings so far. Please weigh in there if you have any discoveries or information to share.
