### ISSUE TITLE
[Bug] Maybe it is feature.

### ISSUE THREAD

**Issue by riksking** [GitTools/GitVersion#2288]
**Describe the bug**
Hi.
I noticed one trouble in version 5.3.4.
I have some c# projects on .net Core and .net Standard in one solution.
And I have “Directory.Build.props” in core directory of solution
with content
<Project> <PropertyGroup> <GenerateAssemblyInfo>false</GenerateAssemblyInfo> <UpdateAssemblyInfo>true</UpdateAssemblyInfo> <GenerateDocumentationFile>true</GenerateDocumentationFile> <NoWarn>$(NoWarn);1591</NoWarn> </PropertyGroup> </Project>

But when I build this project, I get this message
Target "UpdateAssemblyInfo" skipped, due to false condition; ($(UpdateAssemblyInfo) == 'true') was evaluated as (false == 'true').
And this
Property reassignment: $(UpdateAssemblyInfo)="false" (previous value: "true") at \.nuget\packages\gitversiontask\5.3.4\build\GitVersionTask.props (22,9)
and the version is "0.0.0.0"

In version 5.0.1 it works fine and write current version of file.

Also, if I insert “<UpdateAssemblyInfo>true</UpdateAssemblyInfo>” into the project itself, version calculation and writing is successful.

## Expected Behavior
I expect that config in “Directory.Build.props” read currectly, like in version 5.0.1
And version write currectly.

## Actual Behavior
Wrong version of file after build.

## Possible Fix
I have no suggesions. (:

## Steps to Reproduce
Create solution with two C# projects. One on .net Core, and another on .Net Standart.
Create additional folders for these projects and put them there.
Create file "Directory.Build.props" with content

```
<Project> 
  <PropertyGroup> 
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo> 
    <UpdateAssemblyInfo>true</UpdateAssemblyInfo> 
    <GenerateDocumentationFile>true</GenerateDocumentationFile> 
    <NoWarn>$(NoWarn);1591</NoWarn> 
    </PropertyGroup> 
</Project>
````

and put it in core directory of solution.

Try to build it and check version of the files.

## Context
I update GitversionTask from 5.0.1 to 5.3.4 and expected that everything will be fine.
But I received a large number of files with version "0.0.0.0"

## Your Environment
Windows 10

**Comment by asbjornu** [comment]
Can this be related to #2280?

**Comment by riksking** [comment]
I think not.
In my case, it's about applying global settings to projects on .Net Core and .Net Standart

It's about this.
https://docs.microsoft.com/ru-ru/visualstudio/msbuild/customize-your-build?view=vs-2019

**Comment by asbjornu** [comment]
Ok, so this is about supporting the global `Directory.Build.props` file in GitVersion? I'm a bit puzzled that GitVersion should even know about its existence and that this isn't just solved transparently by MSBuild. It is also strange that this worked in 5.0.1 but not in 5.3.4.

**Comment by riksking** [comment]
Perhaps, earlier the GitVersion was built in later than the global settings were tightened and received the correct value of this parameter.
