### ISSUE TITLE
Gitversion crashes on Gitlab when there is no local for submodule

### ISSUE THREAD

**Issue by madhusameena** [GitTools/GitVersion#2321]
I see some information from https://github.com/GitTools/GitVersion/issues/1967
But I have a submodule which need to build with CI. I tried to set Git_Branch as master for testing. But it still fails.   
As submodule does not have any branch.  

Any work around ?

**Comment by asbjornu** [comment]
Git submodules aren't supported, I'm afraid. GitVersion needs to know which branch it's building as well as the full history of that branch and its relation to `master` up until the latest tag. I think that's going to be very hard getting to work with Git submodules, unfortunately.
