### ISSUE TITLE
[Bug] TC build number not updated automatically

### ISSUE THREAD

**Issue by mrt181** [GitTools/GitVersion#2322]
**Describe the bug**
The TC build number is not updated to the GitVersion number

## Expected Behavior
TC build number updated to the GitVersion number automatically

## Actual Behavior
The TC build number is set to the TC build counter

## Steps to Reproduce
This is my csproj file (abbreviated):
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <GenerateAssemblyTitleAttribute>true</GenerateAssemblyTitleAttribute>
    <GenerateAssemblyConfigurationAttribute>true</GenerateAssemblyConfigurationAttribute>
    <GenerateAssemblyCompanyAttribute>true</GenerateAssemblyCompanyAttribute>
    <GenerateAssemblyProductAttribute>true</GenerateAssemblyProductAttribute>
    <GenerateAssemblyCopyrightAttribute>true</GenerateAssemblyCopyrightAttribute>
    <GenerateAssemblyVersionAttribute>true</GenerateAssemblyVersionAttribute>
    <GenerateAssemblyFileVersionAttribute>true</GenerateAssemblyFileVersionAttribute>
    <GenerateAssemblyInformationalVersionAttribute>true</GenerateAssemblyInformationalVersionAttribute>
    <UpdateAssemblyInfo>false</UpdateAssemblyInfo>
    <WriteVersionInfoToBuildLog>true</WriteVersionInfoToBuildLog>

    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
   
    <TargetFrameworks>netstandard2.0;netcoreapp2.1</TargetFrameworks>

    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <VersionSuffix>$(VersionSuffix)</VersionSuffix>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <WarningsAsErrors />
  </PropertyGroup>

  <PropertyGroup>
    <Protobuf_TouchMissingExpected>true</Protobuf_TouchMissingExpected>
    <Protobuf_NoWarnMissingExpected>true</Protobuf_NoWarnMissingExpected>

  </PropertyGroup>

  <ItemGroup>

    <PackageReference Include="GitVersionTask" Version="5.3.5">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="System.ValueTuple" Version="4.5.0" />
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="../../proto/api/**/*.proto" ProtoRoot="../../proto" OutputDir="api-csharp/%(RelativeDir)" CompileOutputs="true" GrpcServices="Client" />

    <PackageReference Include="Google.Api.Gax.Grpc" Version="3.0.0" />
    <PackageReference Include="Google.Protobuf" Version="3.11.4" />
    <PackageReference Include="Grpc" Version="2.27.0" />
    <PackageReference Include="Grpc.Tools" Version="2.27.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>

   </ItemGroup>
</Project>
```

These are my CI build parameters and build steps:
```xml
    <parameters>
      <param name="GitVersion.NuGetVersion" value="%build.number%" />
      <param name="env.Git_Branch" value="%teamcity.build.vcs.branch.RootMainPublishPackage%" />
      <param name="teamcity.git.fetchAllHeads" value="true" />
      <param name="teamcity.vcsTrigger.runBuildInNewEmptyBranch" value="true" />
    </parameters>
    <build-runners order="RUNNER_3287, RUNNER_3313, RUNNER_2662, RUNNER_1463">
      <runner id="RUNNER_3313" name="Clean Restore" type="simpleRunner">
        <parameters>
          <param name="script.content"><![CDATA[dotnet clean
dotnet restore --source http://depot.my.com:8080/nexus/service/local/nuget/nuget-my/]]></param>
          <param name="teamcity.build.workingDir" value="api-csharp/My.Api.Trading" />
          <param name="teamcity.step.mode" value="default" />
          <param name="use.custom.script" value="true" />
        </parameters>
      </runner>
      <runner id="RUNNER_2662" name="Build" type="simpleRunner">
        <parameters>
          <param name="script.content"><![CDATA[dotnet build --configuration Release
dotnet pack --configuration Release -p:PackageVersion=%GitVersion.NuGetVersion%]]></param>
          <param name="teamcity.build.workingDir" value="api-csharp/My.Api.Trading" />
          <param name="teamcity.step.mode" value="default" />
          <param name="use.custom.script" value="true" />
        </parameters>
      </runner>
    </build-runners>
````

## Context
Show the GitVersion number as TC's build number.
GitTaskVersion creates the correct version but does not show it:

```
Successfully created package 'D:\TeamCity\BuildAgent.0\work\trading-api\api-csharp\My.Api.Trading\bin\Release\My.Api.Trading.0.9.2-ci.6.nupkg'.
```

## Your Environment

* Version Used: 
  * TC: `2017.2.2 (build 50909)`
  * GitVersionTask:  `5.3.5`
  * Operating System and version: `Windows Server 2012`

**Comment by mrt181** [comment]
Hi, that's strange because I have another build job in TC which uses `msbuild` instead of `dotnet` and in this build job the correct version is shown in the TC UI.

**Comment by asbjornu** [comment]
You may be right. I don't use GitVersionTask much myself, but given that it shares a bit of the code with the command line executable, it may detect that it's running on a build server and expose the variables regardless. I can't tell you why `msbuild` and `dotnet` is acting differently, though. @arturcic, do you have any ideas?

I would recommend that you run GitVersion in executable form (not GitVersionTask) one way or another with `/output buildserver` regardless, just to contain that part of the puzzle to a separate step. This compartementalization is something we're going to do much more of in version 6, to avoid surprises and inconsistencies like the one you're experiencing here, @mrt181. See #2275 for details.

**Comment by mrt181** [comment]
How would I run `gitversion.exe /output buildserver`, that is does using the GitVersionTask automatically make `gitversion.exe` available to be picked up by the build job? does it work with linux agents running the dotnet commands?

**Comment by asbjornu** [comment]
You need to run it explicitly using one of the many available methods. You can use [the `dotnet` global tool](https://www.nuget.org/packages/GitVersion.Tool), [`gitversion.exe`](https://www.nuget.org/packages/GitVersion.CommandLine), [the AzDO Task](https://marketplace.visualstudio.com/items?itemName=gittools.gittools) or [the GitHub Action](https://github.com/marketplace/actions/use-actions).

**Comment by mrt181** [comment]
Ok, I did install the global tool, that works.
```bash
$ ~/.dotnet/tools/dotnet-gitversion
{
  "Major":1,
  "Minor":9,
  "Patch":2,
  ...
}
```
```cmd
C:\myrepo\..\.dotnet\tools\dotnet-gitversion.exe
{
  "Major":1,
  "Minor":9,
  "Patch":2,
  ...
}
```

But the prefered CommandLine version does not work with WSL1 (can't try WSL2), I assume it won't work on a linux build agent too.
```bash
$ dotnet gitversion
Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET Core program, but dotnet-gitversion does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.
```
but it does with cmd
```cmd
C:\myrepo>dotnet gitversion
{
  "Major":1,
  "Minor":9,
  "Patch":2,
  ...
}
```
This returns the same empty output on cmd and wsl: 
```bash
>dotnet tool list
Package Id      Version      Commands      Manifest
---------------------------------------------------
```

**Comment by asbjornu** [comment]
Just use one that works.

**Comment by RobSmyth** [comment]
I also have this issue, TeamCity's build number is not updated when using GitVersion.MsBuild 5.6.10. But does work when using GitVersionTask 5.5.1.

If it helps ...

In the logs, for the build using GitVersion.MsBuild 5.6.10, I see:

`\packages\GitVersion.MsBuild.5.6.10\tools\net48/gitversion.exe" "C:\BuildAgent\work\4f49d8a097124216\Versioning01" -output file -outputfile gitversion.json
`

I guess the "-ouput file" option is the problem.

I do not see any call to gitversion.exe in the 5.5.1 logs.

Both builds are on the same TeamCity server.

So GitVersionTask 5.5.1 works, but GetVersion.MsBuild 5.6.10 does not.
