### ISSUE TITLE
[Bug] Unexpected increment of patch version in release branch after new commit in master

### ISSUE THREAD

**Issue by saciervo** [GitTools/GitVersion#2323]
**Describe the bug**
In Mainline mode. Every commit automatically creates a deliverable a build server for us with the GitVersion determined `SemVer` output assigned as version number.

![image](https://user-images.githubusercontent.com/707898/84377405-d142dc80-abe2-11ea-9745-b0128845a65b.png)

**Green (left)** are the version numbers that we would expect to be assigned to our deliverables.
**Red (right)** are the version numbers that actually were assigned to our deliverables.

You can see the problem on the latest commit `Improve new feature` we didn't expect GitVersion to increment the patch level number, since it's a straight line inside the **release/2.4** branch.

After some try and error, it seems that the `Bugfix #2` commit on **master** is responsible for that behavior. Imho it should not interfere with the versioning in the other branch.

## Expected Behavior
The `Improve new feature` commit should be version "2.4.0-beta.2".

## Actual Behavior
The `Improve new feature` commit actually gets assigned version "2.4.1-beta.2". Just because of a commit to **master** which is even on a different minor version number.

To make matters worse: If you checkout the `New Feature` commit on the **release/2.4** branch now (with the `Bugfix #2` commit on **master**) the version is now suddenly "2.4.1-beta.1". So GitVersion now assigns a different version number then it had in the past. **For the same commit**.

## Context
We did not notice the difference, until we merged the **release/2.4** branch into **master** for the release (Which is correctly assigned with 2.4.0 by GitVersion) and then browsed the SemVer-sorted deliverables download list which looks like this.

- 2.4.1-beta.2
- 2.4.0
- 2.4.0-beta.1
- 2.3.2
- 2.3.1
- 2.3.0

So the 2.4.1-beta.2 (apart from having a wrong version number) appears for the customer as the higher (even if tagged as beta) version than the stable release, which is wrong. 

## Your Environment
- Version Used: 5.1.3+Branch.master.Sha.bef8ebc0b62b3ddd0cdafe09b66d68bbfcaf90d5
- Operating System: Windows 10

**Comment by asbjornu** [comment]
Are you able to reproduce this behavior inside a `RepositoryFixture` and submit it as a pull request?

**Comment by saciervo** [comment]
Hi @asbjornu 
I finally had some time to do this. Please check PR #2403

**Comment by saciervo** [comment]
Hi @asbjornu 

I played around a bit with the tests. And found that I probably could just configure master to be in CD mode while generally having mainline development. So far it works for me:

``` yml
mode: Mainline
branches:
  master:
    mode: ContinuousDeployment
ignore:
  sha: []
merge-message-formats: {}
```

I'll close the issue ☺️
