### ISSUE TITLE
[Bug] GitVersion is not using the correct GitVersion.yml file

### ISSUE THREAD

**Issue by DerGary** [GitTools/GitVersion#2331]
**Describe the bug**
When gitversion is executed against a remote repository with /url and /b parameters it does not use the GitVersion.yml that is in this repository in this branch. 

## Expected Behavior
When gitversion is executed for a remote repository it should ignore the gitversion that is inside the folder that gitversion is executed from and it should instead look inside the remote repository for a GitVersion.yml and use the next verion of that GitVersion.yml

## Actual Behavior
If you execute gitversion from a folder with no GitVersion.yml it just starts with 0.1.0 instead of the nextversion inside the GitVersion.yml that is part of the remote repository. If you execute gitversion from a folder with a GitVersion.yml then it uses the next version of this GitVersion.yml (that is a completely different one than the remote one) as base version.

## Steps to Reproduce
- create a GitVersion.yml with a content like this: (or just use my test repo https://github.com/DerGary/GitVersionTest)
````
next-version: 1.1.5
branches: {}
ignore:
  sha: []
merge-message-formats: {}
````
- commit it to a remote repository with commit message: +semver: minor
- open command prompt (folder that has no git repo in it)
- execute gitversion /url /b and calculate the version of the remote repository (in my case it returned 0.2.0)

###Problem inside folder with GitVersion.yml
- open command prompt (folder that has a git repo in it with a GitVersion.yml for example:)
````
next-version: 2.0.0
branches: {}
ignore:
  sha: []
merge-message-formats: {}
````
- execute gitversion /url /b and calculate the version of the remote repository (in my case it returned 2.1.0, so it used the GitVersion.yml of the current folder instead of the remote repository)
 
## Context
I try to calculate if the version of my development branch changed in regarding to the test or master branch. We want to accomplish that we check on a pull request build if the version has changed, and if not then the pull request should not be allowed to be completed.

- Version Used: 5.3.6+Branch.master.Sha.c73300b5aa053e9a086a5972e875890ecd7e13dc
- Operating System: Windows 10 Enterprise
- Test Repo: https://github.com/DerGary/GitVersionTest

**Comment by DerGary** [comment]
I just realized that +semver:minor commit messages from a remote branch seem to be also not used is this all intended behaviour maybe?

**Comment by asbjornu** [comment]
So given a dynamic repository, the remote repository should take precedence over **everything** of the local repository? This seems to be asking for quite a breaking change. I'm not sure everyone using dynamic repositories would agree with you in this being the default behavior.

Also worth mentioning is that we're debating removing dynamic repositories from GitVersion in version 6 altogether, as the entire feature can be implemented in no more than one line of shell scripting.

**Comment by DerGary** [comment]
> So given a dynamic repository, the remote repository should take precedence over everything of the local repository

That is exactly what I thought the feature would do. At least there is no hint that it does not do exactly that in the documentation: https://gitversion.net/docs/more-info/dynamic-repositories
The Documentation reads like as if gitversion would download the remote repository and calculate the version against that repository.

**Comment by asbjornu** [comment]
I agree that the dynamic repository feature may give the appearance that it will override everything else from the local repository, but I don't believe that's how it's implemented. I still think most things file-related such as the file system cache, loading `GitVersion.yml`, etc., is operating on the local repository.

That's most likely not a mindful design choice, it's just how these features have been implemented probably because almost no one uses dynamic repositories. I wish I had a better answer for you, but that's how it is.

Hopefully, we are able to clean this up in the future. Do you see any big, compelling reasons to keep the dynamic repository feature in GitVersion at all, as we are discussing its removal in version 6?

**Comment by DerGary** [comment]
As I don't understand what dynamic repository does, as it does not do what I thought it does, I don't see a compelling reason to keep the feature.

Is there a way to achieve what I am looking for? 
I want to check what the version of another branch is so I can compare it with the version that my current branch has.

**Comment by asbjornu** [comment]
What you want to do should be possible by just doing something like this:

```bash
git checkout branch1
branch1_version=$(gitversion -showvariable FullSemVer)
git checkout branch2
branch2_version=$(gitversion -showvariable FullSemVer)
```

**Comment by DerGary** [comment]
Well it wasn't that easy because I need to do this on my CI Pipeline which is Azure Pipelines and I can't rely on GitVersion being installed on the build machine. Also on Pull Request builds there are additional commits created that are not part of normal branches. But I got it solved in the end.
