### ISSUE TITLE
[Docs] How to start using GitVersion in a new project?

### ISSUE THREAD

**Issue by FISHMANPET** [GitTools/GitVersion#2335]
I'm trying to use GitVersion in a brand new project of mine, using GitHub Flow and mainline mode, and I'm having trouble configuring it to behave the way I'd like/am expecting to.

I've been able to use GitVersion in an existing project of mine, where I'm able to tag the most recent release.  For example if I've released 1.2.3, I can tag that in Git.  On changes in a new branch, GitVersion will generate 1.2.4-branch0001 versions, which is what I'm expecting and what I want.

But I can't seem to figure out how to replicate this same behavior before I have any kind of release.  What I would imagine I do is set the next-version in my config to 1.0.0, then versions will be generated like 1.0.0-branch0001, 1.0.0-branch0002, etc, until I merge into master, gitversion generates 1.0.0, and Git is tagged with that version.  At that point I can remove next-version and rely on GitVersion seeing the Git tags to determine the next version.  However when I set next-version to 1.0.0, GitVersion generates 1.0.1-branch0001 versions.  I experimented a bit, and if I run it in master with next-version set to 1.0.0 and mode:MainLine, it will generate 1.0.0.  However my build processes deploys the pre-release versions to a test environment, and I need them to be a semantically lower version than the 1.0.0 that will eventually be released.

Is this a bug in gitversion?  Is there an additional configuration setting I'm missing?  Some misunderstanding I have with how the tool operates?

**Comment by asbjornu** [comment]
This is strange. Can you try to delete your `GitVersion.yml` file and see if that helps? The following test shows that your use-case is working just as you describe:

https://github.com/GitTools/GitVersion/blob/5330bbb2b93571c2e6ea8b91e2758798b28e52e4/src/GitVersionCore.Tests/VersionCalculation/NextVersionCalculatorTests.cs#L91-L118

**Comment by FISHMANPET** [comment]
If I delete gitversion.yml it works like I expect, except it's defaulting to version 0.1.0 so my versions in the branch are 0.1.0-branch0001.

I just tried it in a brand new repository, here are the exact steps I took:
Create new repository
Create new branch (bajurny) in repository based off master
Commit gitversion.yml (because I need some commit in the branch) that looks like this:
```yaml
mode: Mainline
next-version: 1.0.0
```

And at that point, I run gitversion and the generated version is `1.0.1-bajurny0001` rather than the expected `1.0.0-bajurny0001`

And I merged bajurny into master (whose only changes are the gitversion.yml) and then gitversion returns `1.0.1` as the version.

**Comment by asbjornu** [comment]
What version number do you get if you remove `mode: Mainline` and the only thing in your `GitVersion.yml` is `next-version 1.0.0`?

**Comment by FISHMANPET** [comment]
Getting a chance to play around with this again.

If I remove mode: Mainline then GitVersion properly returns a 1.0.0 prerelease number, if I add mode: Mainline back in it creates a 1.0.1 prerelease.

So it looks like that test case tests the case with no mode specified, but not with Mainline, and it also sounds like this is a bug rather than a documentation issue.

**Comment by FISHMANPET** [comment]
I wrote two failing tests, it looks like mainline mode isn't properly using next-version, perhaps treating the next-version as the already deployed version, rather than truly the next version.

The first test is when inside a branch, setting next-version to 1.0.0, and gitversion returns 1.0.1-foo.1 instead of 1.0.0-foo.1.
The second test is when a branch is merged into the mainline (master) with next-version, it should produce 1.0.0 but it produces 1.0.1.

I tried to poke around at the source code to try and find where this might be happening but I'm not very fluent in C# so I wasn't able to immediately figure out where it might be happening.
I never shared this, this is the result of `gitversion /diag` where I would expect `1.0.0-brach1.4` but instead get `1.0.1-brach1.4`
```
PS C:\Users\bajurny\Desktop\gitversion\gv1> gitversion /diag
INFO [07/13/20 13:25:55:16] Dumping commit graph:
INFO [07/13/20 13:25:55:21] * c32bdd4 34 minutes ago  (HEAD -> branch1)
* fc3a097 38 minutes ago
* 50aa2f3 48 minutes ago
* 5598a81 49 minutes ago
* 8adf1a4 55 minutes ago  (master)

INFO [07/13/20 13:25:55:22] Working directory: C:\Users\bajurny\Desktop\gitversion\gv1
INFO [07/13/20 13:25:55:24] Project root is: C:\Users\bajurny\Desktop\gitversion\gv1\
INFO [07/13/20 13:25:55:24] DotGit directory is: C:\Users\bajurny\Desktop\gitversion\gv1\.git
INFO [07/13/20 13:25:55:34] Using latest commit on specified branch
INFO [07/13/20 13:25:55:34] No branch configuration found for branch branch1, falling back to default configuration
INFO [07/13/20 13:25:55:35] Begin: Attempting to inherit branch configuration from parent branch
  INFO [07/13/20 13:25:55:35] Begin: Finding branch source of 'branch1'
    INFO [07/13/20 13:25:55:36] Begin: Finding merge base between 'branch1' and 'master'.
      INFO [07/13/20 13:25:55:37] Found merge base of 8adf1a4025ff4e2b13501e00018b5edc1c9219e5
      INFO [07/13/20 13:25:55:37] Merge base of branch1' and 'master is 8adf1a4025ff4e2b13501e00018b5edc1c9219e5
    INFO [07/13/20 13:25:55:37] End: Finding merge base between 'branch1' and 'master'. (Took: 10.89ms)
  INFO [07/13/20 13:25:55:38] End: Finding branch source of 'branch1' (Took: 22.31ms)
  INFO [07/13/20 13:25:55:38] Begin: Getting branches containing the commit '8adf1a4025ff4e2b13501e00018b5edc1c9219e5'.
    INFO [07/13/20 13:25:55:38] Trying to find direct branches.
    INFO [07/13/20 13:25:55:38] No direct branches found, searching through all branches.
    INFO [07/13/20 13:25:55:38] Searching for commits reachable from 'master'.
    INFO [07/13/20 13:25:55:39] The branch 'master' has a matching commit.
  INFO [07/13/20 13:25:55:39] End: Getting branches containing the commit '8adf1a4025ff4e2b13501e00018b5edc1c9219e5'. (Took: 8.49ms)
  INFO [07/13/20 13:25:55:39] Found possible parent branches: master
  INFO [07/13/20 13:25:55:39] End: Attempting to inherit branch configuration from parent branch (Took: 43.38ms)
  INFO [07/13/20 13:25:55:39] Running against branch: branch1 (c32bdd47c6a714120341b6175bec80742b12ef87)
  INFO [07/13/20 13:25:55:39] Begin: Calculating base versions
    INFO [07/13/20 13:25:55:41] NextVersion in GitVersion configuration file: 1.0.0 with commit count source External Source
    INFO [07/13/20 13:25:55:43] Base version used: NextVersion in GitVersion configuration file: 1.0.0 with commit count source 8adf1a4025ff4e2b13501e00018b5edc1c9219e5
  INFO [07/13/20 13:25:55:43] End: Calculating base versions (Took: 39.62ms)
  INFO [07/13/20 13:25:55:44] Begin: Using mainline development mode to calculate current version
    INFO [07/13/20 13:25:55:44] Found possible mainline branches: master
    INFO [07/13/20 13:25:55:45] Mainline for current branch is master
    INFO [07/13/20 13:25:55:45] Current branch (branch1) was branch from 8adf1a4025ff4e2b13501e00018b5edc1c9219e5
    INFO [07/13/20 13:25:55:45] 4 commits found between 8adf1a4025ff4e2b13501e00018b5edc1c9219e5 and c32bdd47c6a714120341b6175bec80742b12ef87
    INFO [07/13/20 13:25:55:45] Performing Patch increment for current branch
  INFO [07/13/20 13:25:55:45] End: Using mainline development mode to calculate current version (Took: 16.54ms)
  INFO [07/13/20 13:25:55:46] Using branch name to calculate version tag
  INFO [07/13/20 13:25:55:46] Begin: Getting version tags from branch 'refs/heads/branch1'.
  INFO [07/13/20 13:25:55:46] End: Getting version tags from branch 'refs/heads/branch1'. (Took: 2.88ms)
{
  "Major":1,
  "Minor":0,
  "Patch":1,
  "PreReleaseTag":"branch1.4",
  "PreReleaseTagWithDash":"-branch1.4",
  "PreReleaseLabel":"branch1",
  "PreReleaseNumber":4,
  "WeightedPreReleaseNumber":4,
  "BuildMetaData":"",
  "BuildMetaDataPadded":"",
  "FullBuildMetaData":"Branch.branch1.Sha.c32bdd47c6a714120341b6175bec80742b12ef87",
  "MajorMinorPatch":"1.0.1",
  "SemVer":"1.0.1-branch1.4",
  "LegacySemVer":"1.0.1-branch1-4",
  "LegacySemVerPadded":"1.0.1-branch1-0004",
  "AssemblySemVer":"1.0.1.0",
  "AssemblySemFileVer":"1.0.1.0",
  "FullSemVer":"1.0.1-branch1.4",
  "InformationalVersion":"1.0.1-branch1.4+Branch.branch1.Sha.c32bdd47c6a714120341b6175bec80742b12ef87",
  "BranchName":"branch1",
  "EscapedBranchName":"branch1",
  "Sha":"c32bdd47c6a714120341b6175bec80742b12ef87",
  "ShortSha":"c32bdd4",
  "NuGetVersionV2":"1.0.1-branch1-0004",
  "NuGetVersion":"1.0.1-branch1-0004",
  "NuGetPreReleaseTagV2":"branch1-0004",
  "NuGetPreReleaseTag":"branch1-0004",
  "VersionSourceSha":"8adf1a4025ff4e2b13501e00018b5edc1c9219e5",
  "CommitsSinceVersionSource":4,
  "CommitsSinceVersionSourcePadded":"0004",
  "CommitDate":"2020-07-13"
}
  INFO [07/13/20 13:25:55:48] Done writing
```
From what I can tell it's properly finding the next-version, but then I suspect the mainline code isn't using it properly, but I haven't found where those parts are glued together yet to try and get a better idea of the logic.

**Comment by asbjornu** [comment]
Please take a look at the mainline mode tests we have and whether they are covering your scenario at all. If not, we would welcome a PR with more tests and a fix that hopefully doesn't break a bunch of the existing tests.

https://github.com/GitTools/GitVersion/blob/e705d3798b438e48481300dd3c61bec57685080e/src/GitVersionCore.Tests/IntegrationTests/MainlineDevelopmentMode.cs#L16-L546

**Comment by FISHMANPET** [comment]
None of the Mainline tests include Next-Version, which seems to be the source of the problem.  I've written failing tests and opened a PR, and I'll keep looking over the code to see if I can find out what's happening.

**Comment by FISHMANPET** [comment]
A small thing, but I never updated the title of this to reflect that it was actually a bug rather than a documentation issue, I've updated the title to more accurately describe the actual bug found.  If you want to move this under "Bug" rather than "Documentation" in the release notes, that would be more accurate, but it's a small thing and I don't mind either way

**Comment by arturcic** [comment]
I think we keep it like this

**Comment by asbjornu** [comment]
Those particularly interested can always click from the release notes to the particular issue and get the right title, so I agree with @arturcic that this is fine as is.
