### ISSUE TITLE
[Bug] Manual incrementing version by commit message is only applied once

### ISSUE THREAD

**Issue by DerGary** [GitTools/GitVersion#2345]
**Describe the bug**
When the branch contains 2 or more commits with +semver: minor (or other possible increments, specifically when it is 2 or more times the same version part that should be incremented), gitversion just increments the version by 1 instead of the count.

## Expected Behavior
I have a branch that contains 3 commits incrementing the minor version. 
![image](https://user-images.githubusercontent.com/4302467/86247569-ef31aa80-bbac-11ea-906c-9738b9d8b735.png)

My GitVersion.yml starts with a next-version of 1.1.5.
![image](https://user-images.githubusercontent.com/4302467/86246855-f86e4780-bbab-11ea-8cfa-1d838fd97dd4.png)
I would expect the version gitversion would return to be 1.5.0 but instead it returns 1.2.0
![image](https://user-images.githubusercontent.com/4302467/86246931-1471e900-bbac-11ea-85db-3396bbd936a0.png)

## Steps to Reproduce
- Clone this repository https://github.com/DerGary/GitVersionTest
- run gitversion against it.

## Context

We use a branching and merging strategy that does not comply with the default ones that gitversion supports. I thought manually incrementing would be a nice feature because we would not need to manually incrementing the version in several files and just specify in the commit message which part we want to increment, which would save us significant time in merging and incrementing versions before we complete PRs.

## Your Environment

- Version Used: 5.3.6+Branch.master.Sha.c73300b5aa053e9a086a5972e875890ecd7e13dc
- Operating System and version (Windows 10, Ubuntu 18.04): Windows 10
- Link to your project: https://github.com/DerGary/GitVersionTest

**Comment by asbjornu** [comment]
Which `mode` are you using? If not `Mainline`, please test it.

**Comment by DerGary** [comment]
@asbjornu I just tried Mainline mode, it behaves differently to the default mode but it still does not completely behave as I would expect it to. When on the master branch and I create 2 commits both with "+semver: minor" it increments the minor version by 2. When I try the same on any other branch it just increments the minor version by 1.

**Comment by asbjornu** [comment]
Yes, that's because the only "versioned" branch in Mainline is the main branch.
