### ISSUE TITLE
[Improvement] Documentation about Azure DevOps tasks

### ISSUE THREAD

**Issue by Ozzian** [GitTools/GitVersion#2350]
In the documentation ( https://gitversion.net/docs/build-server-support/build-server/azure-devops ) the link to the extension directs to page which has deprecated warning. But the one with the warning has the latest updates compared the one that "should be the new one".

## Detailed Description
* Link in the documentation directs to deprecated extension.
* Is the extension actually deprecated?
* Which one we should actually use?

## Context
People are (atleast I am) confused on what version to use. Could you be more clear on this?

**Comment by asbjornu** [comment]
Our documentation around package availability is not entirely up to date. See #2326 for an up to date list. If you feel inspired, we warmly welcome pull requests to our documentation. 🙏
