### ISSUE TITLE
[Bug] WPF Resource Dictionary triggers 'File contains ... obj\Debug\AssemblyInfo.g.cs'

### ISSUE THREAD

**Issue by aubiyko** [GitTools/GitVersion#2352]
**Describe the bug**
Rebuilding the WPF App project with Resource Dictionary gets 'File contains assembly version attributes which conflict with the attributes generated by GitVersion obj\Debug\AssemblyInfo.g.cs' warning.

This may be related to #2228.

## Expected Behavior
No errors/warnings.

## Actual Behavior
...\packages\GitVersionTask.5.3.7\build\GitVersionTask.targets(19,9): warning : File contains assembly version attributes which conflict with the attributes generated by GitVersion obj\Debug\AssemblyInfo.g.cs

obj/Debug/AssemblyInfo.g.cs does indeed exist, but contains version information generated by GitVersion.

```
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by GitVersion.
//
// You can modify this code as we will not overwrite it when re-executing GitVersion
// </auto-generated>
//------------------------------------------------------------------------------

using System.Reflection;

[assembly: AssemblyFileVersion("1.2.4.0")]
[assembly: AssemblyVersion("1.2.4.0")]
[assembly: AssemblyInformationalVersion("1.2.4+1.Branch.master.Sha.0978c44bbeaf25fb56562fdc6d04f6da9e976245")]
```

## Steps to Reproduce
1.  Create WPF App (.NET Framework 4.8);
2. Delete AssemblyInfo.cs;
2. Add Resource Dictionary (WPF);
3. Install GitVersionTask NuGet;
4. Just in case, reload soulion; 
5. Rebuild.

## Your Environment
- Version Used: 5.3.7
- Operating System and version (Windows 10, Ubuntu 18.04): Microsoft Windows 10 1909
- IDE: Microsoft Visual Studio Community 2019 16.6.3
- Microsoft .NET Framework 4.8.03752

**Comment by asbjornu** [comment]
Did #2280 not fix this?
