### ISSUE TITLE
Clearify PreRelease-Handling, separation of PreReleaseLabel and PreReleaseNumber

### ISSUE THREAD

**Issue by pniederlag** [GitTools/GitVersion#2353]
We have been using gitversion for a while now and I understand it's really powerfull and flexibel. On the opposite side there is a hugh complexity involved in getting it to work in a way that one might like.

The thing that troubles me most is that it seems hard(impossible?) to use a PreReleaseLabel without a PreReleaseNumber. The PreReleaseLabel can be configured in a really powerful way by the `branches.xyz.tag` configuration. But it will always come with an additional postfix of a PreReleaseNumber, that seems to be out of control.

In my use-case I would really love to use just the fixed string 'SNAPSHOT' as a prelease-label (combined with {BranchName}), but i do *not* want this prerelease to get a PreReleaseNumber Postfix.

Another *imho* valid use case is just about the opposite, use a PreReleaseNumber, but *dont't* add a PreReleaseLabel, check this issue for the details: https://github.com/GitTools/GitVersion/issues/2347

So, do we have any chance to use PreReleaseLabel and PreReleaseNumber indepently of each other? In effect we'd like to have more control over the resulting PreReleaseTag.

The rationale/logic behind the current behaviour is explained briefly here:
https://github.com/GitTools/GitVersion/issues/1646

### actual result

```
GitVersion_PreReleaseTag=SNAPSHOT.1
GitVersion_PreReleaseTagWithDash=-SNAPSHOT.1
GitVersion_PreReleaseLabel=SNAPSHOT
GitVersion_PreReleaseNumber=1
```

### desired result
```
GitVersion_PreReleaseTag=SNAPSHOT
GitVersion_PreReleaseTagWithDash=-SNAPSHOT
GitVersion_PreReleaseLabel=SNAPSHOT
GitVersion_PreReleaseNumber=
```

**Comment by asbjornu** [comment]
By the looks of it, this sounds related to what's being discussed in #2065. Could you please read through that discussion and comment on whether it could be adjusted to also support your use-case? The discussion in #2199 may also prove relevant, although from a different perspective.
