### ISSUE TITLE
[Improvement] Extend the /updateprojectfiles parameter to update the 'Version' element

### ISSUE THREAD

**Issue by akordowski** [GitTools/GitVersion#2359]
**Is your improvement request related to a problem? Please describe.**
I use GitVersion in a DevOps Pipeline. After using the `dotnet pack` command the Nuget Package still had the default 1.0.0 version number. I also used the `/verbosity Diagnostic` to check if the `.csproj` files are updated, but got no diagnostic info.

## Detailed Description

1. I propose to extend the `ProjectFileUpdater` class to update the `<Version>` element in the `.csproj` file aswell.
2. I propose to add diagnostic log outputs to the `ProjectFileUpdater` class, to have a better overview which classes are updated.

## Context
Using GitVersion in a DevOps scenario I was expecting that the `<Version>` element is changed.

**Comment by akordowski** [comment]
I would like to contribute the changes, if I got the OK.

**Comment by asbjornu** [comment]
I think this sounds like a welcome contribution. A PR would be appreciated. 🙏

**Comment by akordowski** [comment]
Ok, than I will provide a PR in the next days. Thanks!
