### ISSUE TITLE
Create or Update Directory.Build.props File

### ISSUE THREAD

**Issue by balbarak** [GitTools/GitVersion#2364]
## Detailed Description

Add the ability to update or add `Directory.Build.props` file

## Context
Visual Studio Build System for .NET Core

## Possible Implementation
Create XML file called `Directory.Build.props` at root folder with the followings 
```
<Project>
  <PropertyGroup>
    <VersionPrefix>3.2.5</VersionPrefix>
    <VersionSuffix>dev.3</VersionSuffix>
  </PropertyGroup>
</Project>
```

by doing that the build system will take that information and apply it on all `csproj` files

**Comment by SamuelJohnsonMedia** [comment]
Yes please, this would be quite necessary for our .net core apps

**Comment by asbjornu** [comment]
Pull requests are welcome! :)
