### ISSUE TITLE
[Improvement] Add "main" to master branch regex

### ISSUE THREAD

**Issue by TheTimBecker** [GitTools/GitVersion#2366]
As many more organizations (including [GitHub](https://twitter.com/natfriedman/status/1271253144442253312)) and repositories are moving towards naming their default branch `main` instead of `master`, it would be useful to include this naming in the default configuration.

## Detailed Description
This can easily be implemented in a completely backwards compatible way; repositories that use `master` will still recognize that as the master branch. The `develop` branch regex already has alternate naming conventions (`^dev(elop)?(ment)?$`), so there is precedence within GitVersion for this.

_Side note: that regex qualifies `devment` as a valid develop branch name 😁_

## Context
Our organization is making this change and many of our repos use GitVersion. We could make custom configurations for all these repositories, but that is yet another configuration file to maintain and distribute. As this is a movement that is gaining popularity across the board, it would be useful to have this baked into GitVersion and not require a custom configuration.

`main` seems to be the general consensus from the community as the preferred alternative to `master`. It also seems to be the preferred name of the [developer who chose the original names](https://twitter.com/xpasky/status/1271477451756056577).

## Possible Implementation
https://github.com/TheTimBecker/GitVersion/commit/05377a423a62981c902788ed3a498587692b9ae0

Change the default regex for `master` branches from `^master$` to `^master|main$`. This would be done by updating `MasterBranchRegex` in [src/GitVersionCore/Model/Configuration/Config.cs](https://github.com/GitTools/GitVersion/blob/master/src/GitVersionCore/Model/Configuration/Config.cs), as well as updating the documentation and tests.

**Comment by asbjornu** [comment]
Since this is both a welcome change as well as a backwards compatible one, I think we can safely add this to GitVersion 5. Would you be so kind as to submit a PR from https://github.com/TheTimBecker/GitVersion/commit/05377a423a62981c902788ed3a498587692b9ae0?
