### ISSUE TITLE
Support WindowsDesktop project files.

### ISSUE THREAD

**Issue by olivegamestudio** [GitTools/GitVersion#2369]
Using GITVersion on a WindowsDesktop project file causes the following to be displayed:

`WARN [07/29/20 10:29:33:69] Specified project file Sdk (Microsoft.NET.Sdk.WindowsDesktop) is not supported, please ensure the project sdk is of the following: Microsoft.NET.Sdk|Microsoft.NET.Sdk.Web.`

An example WindowsDesktop project file:

`<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <TargetFramework>net461</TargetFramework>
    <UseWPF>true</UseWPF>
  </PropertyGroup>
</Project>`

**Comment by olivegamestudio** [comment]
Created pull request #2370 for this support.

**Comment by asbjornu** [comment]
Fixed in #2370.
