### ISSUE TITLE
[Improvement] Update Homebrew package

### ISSUE THREAD

**Issue by asbjornu** [GitTools/GitVersion#2374]
GitVersion on Homebrew is out of date and we should implement a process to ensure that it's kept up to date. 

## Detailed Description
The current version of GitVersion on Homebrew requires Mono, since .NET Core is not yet available in Homebrew. .NET Core  was unsuccessfully attempted to be added in Homebrew/homebrew-core#3691. As a self-contained executable is not permitted (see Homebrew/homebrew-core#53092), someone (most likely one of us) needs to submit a .NET Core formula first and then submit a new version of GitVersion dependent on the .NET Core formula. See dotnet/sdk#4600 for more information.

## Context
Having an up to date GitVersion formula in Homebrew will make it easier to use GitVersion on (most importantly) macOS and Linux.

## Possible Implementation
1. We should take a look at the rejected formula in Homebrew/homebrew-core#3691 and tweak it to match the latest version of .NET Core.
2. Once the .NET Core formula is accepted, we should submit an upgraded GitVersion formula dependent on the .NET Core formula.
3. Every time we create a release in GitVersion, we can bump the version and SHA in the GitVersion formula and submit it as a pull request towards the `homebrew-core` repository with the [create-pull-request action](https://github.com/marketplace/actions/create-pull-request). This will ensure that the GitVersion formula in Homebrew is kept up to date.

**Comment by asbjornu** [comment]
The current status is that .NET Core is impossible to build from source unless you have access to Microsoft's internal NuGet feeds. So in practice, you need to be hired by Microsoft in order to build .NET Core. 🤦  See dotnet/sdk#11795 for details.

**Comment by arturcic** [comment]
@asbjornu great job on that PR. I followed the progress there, that was an amazing work

**Comment by arturcic** [comment]
If I can help with anything let me know

**Comment by arturcic** [comment]
Do you think we can automate the homebrew PR creation as part of the release flow? ( Maybe using the github cmdline tool **gh** )

**Comment by MikeMcQuaid** [comment]
@arturcic Yup! Check out `brew bump-formula-pr`, https://github.com/dawidd6/action-homebrew-bump-formula and https://github.com/mislav/bump-homebrew-formula-action.

**Comment by arturcic** [comment]
> @arturcic Yup! Check out `brew bump-formula-pr`, https://github.com/dawidd6/action-homebrew-bump-formula and https://github.com/mislav/bump-homebrew-formula-action.

Thank you, then I think we can automate that

**Comment by asbjornu** [comment]
Here it is: Homebrew/homebrew-core#62817.

**Comment by asbjornu** [comment]
And now Homebrew/homebrew-core#62817 is merged, so I'm closing this. The `brew bump-formula-pr` automation can be tracked in another issue, I think.

**Comment by arturcic** [comment]
> The `brew bump-formula-pr` automation can be tracked in another issue, I think.

Agree.
