### ISSUE TITLE
[Bug] Cloning develop throws InvalidOperationException: Sequence contains no matching element

### ISSUE THREAD

**Issue by kcaswick** [GitTools/GitVersion#2378]
**Describe the bug**
Using develop as our default branch led to GitVersion failing locally with an incomprehensible error.

## Expected Behavior
* Version should be the same as if both master and develop have been checked out locally. 
* Not having master branch should lead to a clear warning message something like "Could not find a 'master' branch, neither locally nor remotely."

## Actual Behavior
```
  System.InvalidOperationException : Sequence contains no matching element
  Stack Trace: 
    Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
    MainlineVersionCalculator.GetMainline(Commit baseVersionSource) line 133
    MainlineVersionCalculator.FindMainlineModeVersion(BaseVersion baseVersion) line 44
    NextVersionCalculator.FindVersion() line 59
```

## Possible Fix
Add origin/master to regex for master.

## Steps to Reproduce
See PR #2379 test GivenARemoteGitRepositoryWithCommitsThenClonedLocalDevelopShouldMatchRemoteVersion

## Your Environment

- Version Used: 5.3.7
- Windows 10
- Internal Azure DevOps repo

**Comment by asbjornu** [comment]
Using `develop` as the main branch without any configuration won't work. GitVersion has intrinsic knowledge and logic built around `develop` that requires `master` to exist. If you aren't going to have a `master` branch, why not just call it `main` as supported through #2367 (unreleased, but will still be easier and safer to configure)?

**Comment by kcaswick** [comment]
Master is our main branch. We have a master branch on the **server**, but when a developer is working **locally** it only exists as `origin/master`. 

Why should a developer be required to checkout `master` locally to prevent GitVersion from reporting an error on build? They will never update master directly, that always happens by accepting a pull request in ADO.

In version used, I should have also specified that we are using GitVersionTask.

**Comment by asbjornu** [comment]
Although it's not a big job normalizing the repository so a local `master` is available, I agree it shouldn't be necessary. For some reason, it has become required. I'm not sure why or when, but I'll agree that it can be considered a bug.

**Comment by bert2** [comment]
I just stumbled upon the same problem, and I agree with OP that a dedicated error message would be very helpful.

**Comment by asbjornu** [comment]
A pull request that manages to pinpoint where and when this exception occurs and write a custom error message instead would be merged instantaneously.

**Comment by asbjornu** [comment]
Possibly related to #1671.
