### ISSUE TITLE
Unable to use GitVersion in AWS CodeBuild

### ISSUE THREAD

**Issue by ExcaliburVT** [GitTools/GitVersion#2382]
My team has been successfully using GitVersion on Azure DevOps for more than a year now but we are having to move to AWS CodeCommit/CodeBuild.  Gitversion does not appear to be able to determine where it is, and I'm not sure how to fix it.

Additional Info:
1. Ensured that the AWS Source settings are returning the entire Git repo, so i don't think this is not an issue with a shallow copy
2. I have found info that indicates that AWS CodeBuild operates in a detached git branch rather than working off the "actual" branch that you are building from, but this PR #1841 seems to have included logic to find the current branch.  The PR doesn't seem to indicate if anything additional is required to make GitVersion work however.

## Expected Behavior
Running GitVersion with the existing configuration results in semantic version

## Actual Behavior
`   
GitVersion.Portable v5.3.7 [Approved]
gitversion.portable package files install completed. Performing other installation steps.
Added C:\ProgramData\chocolatey\bin\gv.exe shim pointed to '..\lib\gitversion.portable\tools\gitversion.exe'.
 ShimGen has successfully created a shim for gitversion.exe
 The install of gitversion.portable was successful.
  Software install location not explicitly set, could be in package or
  default install location if installer.

Chocolatey installed 1/1 packages. 
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

[Container] 2020/08/06 18:35:24 Running command 

[Container] 2020/08/06 18:35:25 Phase complete: INSTALL State: SUCCEEDED
[Container] 2020/08/06 18:35:25 Phase context status code:  Message: 
[Container] 2020/08/06 18:35:25 Entering phase PRE_BUILD
[Container] 2020/08/06 18:35:25 Phase complete: PRE_BUILD State: SUCCEEDED
[Container] 2020/08/06 18:35:25 Phase context status code:  Message: 
[Container] 2020/08/06 18:35:25 Entering phase BUILD
[Container] 2020/08/06 18:35:25 Running command & GitVersion.exe $env:CODEBUILD_SRC_DIR /output buildserver /nofetch /config (Join-Path $env:CODEBUILD_SRC_DIR GitVersion.yml) /updateAssemblyInfo true
INFO [08/06/20 18:35:29:05] Working directory: C:\codebuild\tmp\output\src178324475\src\git-codecommit.us-east-2.amazonaws.com\v1\repos\XXXX
INFO [08/06/20 18:35:29:09] Project root is: C:\codebuild\tmp\output\src178324475\src\git-codecommit.us-east-2.amazonaws.com\v1\repos\XXXX\
INFO [08/06/20 18:35:29:09] DotGit directory is: C:\codebuild\tmp\output\src178324475\src\git-codecommit.us-east-2.amazonaws.com\v1\repos\XXXX\.git
INFO [08/06/20 18:35:29:18] Begin: Loading version variables from disk cache
  INFO [08/06/20 18:35:29:18] Cache file C:\codebuild\tmp\output\src178324475\src\git-codecommit.us-east-2.amazonaws.com\v1\repos\XXXX\.git\gitversion_cache\0FEFD83F68A789CE5A4E930E71AC6962D2C06C76.yml not found.
  INFO [08/06/20 18:35:29:18] End: Loading version variables from disk cache (Took: 3.27ms)
  INFO [08/06/20 18:35:29:32] Using latest commit on specified branch
  INFO [08/06/20 18:35:29:36] Begin: Getting branches containing the commit 'b29af23204cabe6bacb4948e9410f620b087988a'.
    INFO [08/06/20 18:35:29:36] Trying to find direct branches.
    INFO [08/06/20 18:35:29:36] No direct branches found, searching through all branches.
    INFO [08/06/20 18:35:29:36] Searching for commits reachable from 'develop'.
    INFO [08/06/20 18:35:29:41] The branch 'develop' has a matching commit.
    INFO [08/06/20 18:35:29:41] Searching for commits reachable from 'origin/develop'.
    INFO [08/06/20 18:35:29:42] The branch 'origin/develop' has a matching commit.
  INFO [08/06/20 18:35:29:42] End: Getting branches containing the commit 'b29af23204cabe6bacb4948e9410f620b087988a'. (Took: 65.49ms)
  INFO [08/06/20 18:35:29:43] No branch configuration found for branch (no branch), falling back to default configuration
..........
 WARN [08/06/20 18:35:35:73] Failed to inherit Increment branch configuration, no branches found.
Falling back to develop branch config
  INFO [08/06/20 18:35:35:73] End: Attempting to inherit branch configuration from parent branch (Took: 6,297.85ms)
  INFO [08/06/20 18:35:35:82] Running against branch: (no branch) (b29af23204cabe6bacb4948e9410f620b087988a)
  WARN [08/06/20 18:35:35:82] An error occurred:
It looks like the branch being examined is a detached Head pointing to commit 'b29af23'. Without a proper branch name GitVersion cannot determine the build version.
  INFO [08/06/20 18:35:35:84] Done writing 

[Container] 2020/08/06 18:35:36 Command did not exit successfully & GitVersion.exe $env:CODEBUILD_SRC_DIR /output buildserver /nofetch /config (Join-Path $env:CODEBUILD_SRC_DIR GitVersion.yml) /updateAssemblyInfo true exit status 1
[Container] 2020/08/06 18:35:36 Phase complete: BUILD State: FAILED
[Container] 2020/08/06 18:35:36 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: & GitVersion.exe $env:CODEBUILD_SRC_DIR /output buildserver /nofetch /config (Join-Path $env:CODEBUILD_SRC_DIR GitVersion.yml) /updateAssemblyInfo true. Reason: exit status 1
`

**Comment by ExcaliburVT** [comment]
Additional information: Codebuild doesn't give you the .git folder AT ALL which means that GitVersion as its written is useless.
https://itnext.io/how-to-access-git-metadata-in-codebuild-when-using-codepipeline-codecommit-ceacf2c5c1dc

So this is unfortunately not a bug, but a result of the design decisions of AWS CodeBuild.

Bottom line, there isn't any EASY way to make it work that I can find.  I'm going to close this and hopefully it will save someone a lot of time in the future.

**Comment by tkrafael** [comment]
At this moment, in codepipeline you can choose to use git clone or zip file. Have you tried?
I'm having an issue regarding detached head

**Comment by tkrafael** [comment]
After some time I was able to get it running on amazon codebuild, however it refuses to run when doing manual retry.
My aws codebuild is:
- connection: bitbucket (it uses internally codestar)
- git clone depth: 0 (full)
- git submodule init : true

When doing through webhook from bitbucket, it works correctly.

**Comment by hsip24** [comment]
I am getting this error when using CodeCommit. I have already selected 'Full clone' in Edit action screen. Can you please let me know how to fix this in CodeBuild when using CodeCommit.
