### ISSUE TITLE
[Feature] Support for making all version numbers lowercase

### ISSUE THREAD

**Issue by dnperfors** [GitTools/GitVersion#2387]
**Is your feature request related to a problem? Please describe.**
In our pipeline we use GitVersion to specify the version of our docker images. In our pipeline some tasks will automatically convert the version to lowercase, but other tasks will use the version as is. So when we have a branch like `feature/My-Special-Feature` the semVer version created by GitVersion will be `1.0-My-Special-Feature`, but the task to build a docker image will create the tag `1.0-my-special-feature`.
Of course as  a work around we can focus on how we create branches or by modifying the version to be lowercase, but that will not make version numbers consistent.

## Detailed Description
It would be great if there would be configuration option to specify what the casing strategy for version numbers is.

## Context
With this change we have more control over how the version is generated.

## Possible Implementation
Configuration to specify the version strategy, either globally or on branch level.

**Comment by asbjornu** [comment]
This feels very relevant to what's being discussed in #2199 and #2065. Please have a look at them and see whether you can fit a solution to your problem into the design of either of those.

**Comment by dnperfors** [comment]
Hi @asbjornu, yes I believe this would fit rather well in the scheme design of #2065, a docker specific scheme could for example solve my issue. Please keep in mind that docker is used mostly in combination with other technologies. In my case I want to have the same casing for both the version generated by a docker scheme and the version generated by my .NET scheme.

**Comment by asbjornu** [comment]
@dnperfors, please follow and add to the discussion in #2065.
