### ISSUE TITLE
Add optional namespace around GitVersionInformation.

### ISSUE THREAD

**Issue by sxleixer** [GitTools/GitVersion#2392]
I use GitVersionTask in multiple projects on a single solution. When I add a reference to a project also using the task and make them fried assemblies I get the following warning.

```
The type 'GitVersionInformation' in '<ProjectA>\obj\Debug\GitVersionInformation.g.cs' conflicts 
with the imported type 'GitVersionInformation' in '<ProjectB>'. 
Using the type defined in '<ProjectB>\obj\Debug\GitVersionInformation.g.cs'.
```

## Detailed Description
I would suggest to create an optional custom namespace around the specified GitVersionInformation classes. Such that one may cherry-pick the namespace of the GitVersionInformation to use.

## Context
This will give me the possibility to get rid of the warning and not to have any conflicting information in my project.

## Possible Implementation
Add a new property which can be set in the project e.g. GitVersionInfoNamespace. When it is not set, there will be no namespace around the GitVersionInformation. When set the namespace will be generated. Changing it this way should be backwards compatible.

**Comment by asbjornu** [comment]
Seems related to #2228 which was fixed by #2280. Could you please have a look at them and see whether there's something that can be adjusted to also fix your issue? I would like to not add configuration if we can avoid it.

**Comment by sxleixer** [comment]
The issues aren't related at all.

My problem is, that when I make internal classes visible to another project, the GitVersionInformation gets also visible to that project. But hence there is no possibility to choose which of the two colliding classes one should use - because of the missing namespace around the class - I cannot get rid of the warning, which is annoying. So please add a namespace around the generated class.

**Comment by asbjornu** [comment]
I see. We can probably do this for v6 as it's a breaking change. A PR would be welcome.

**Comment by sxleixer** [comment]
I think, I can do it without incurring a breaking change. At least I will try. PR on the way.
