### ISSUE TITLE
[Feature] use conventionalcommits.org message information by default

### ISSUE THREAD

**Issue by PixnBits** [GitTools/GitVersion#2395]
**Is your feature request related to a problem? Please describe.**
Simplify configuration set up by asking if conventional commits are used. Perhaps this could even be auto-detected.

## Detailed Description
https://www.conventionalcommits.org/en/v1.0.0/ describes structured commit messages, which can provide information on how to increment versions. This could be manually configured via [`minor-version-bump-message`](https://gitversion.net/docs/configuration#minor-version-bump-message) et. al. but their default values could be changed. Before a breaking version of GitVersion, this could be a question in the configuration setup.

## Context
Conventional commit messages have become more common, culminating in [a specific format](https://www.conventionalcommits.org/en/v1.0.0/). By detecting or defaulting to this syntax GitVersion can work "out of the box" with projects following this trend.

## Possible Implementation
Full disclosure I haven't written C# in years, but [conventional-commits-parser](https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-commits-parser) has a JavaScript implementation of parsing commits that might be useful for the auto-detection.

**Comment by asbjornu** [comment]
I agree that Conventional Commits has become so common that it would be good for GitVersion to support them out of the box. I don't use Conventional Commits myself, though, so I don't have much incentive to add this to GitVersion myself. If someone provides a PR with tests for this, I would be happy to merge, though.

**Comment by asbjornu** [comment]
Implemented in #2553.
