### ISSUE TITLE
How to customize the name of the resulting package?

### ISSUE THREAD

**Issue by awdm** [GitTools/GitVersion#2401]
I'm using Gitversion with .Net Core and would like to have the resulting NuGet Package to be named `[ProjectName].Major.Minor.Patch` for the master branch (this already works) and `[ProjectName].Major.Minor.Patch-BranchName` for every other branch. At the moment it puts another number behind `BranchName , that increments with every commit, and when I build it on Jenkins it even puts a `-origin` before `BranchName`. Is there any way to get rid of this?

**Comment by awdm** [comment]
This is supposed to have the "Question"-Label, but I can't figure out how to change. Sorry, I'm new here.

**Comment by asbjornu** [comment]
You can compose your own version number by using the different [variables](https://gitversion.net/docs/more-info/variables) available.
