### ISSUE TITLE
[Improvement] Add docker image with git included

### ISSUE THREAD

**Issue by elferherrera** [GitTools/GitVersion#2414]
I've been working with your GitTools/Gitversion in gitlab in order to get a semantic version of the created packages. So far it has been great and thanks for your project. 

In order to improve its usage, I was wondering if it is possible for you to add git to one of your docker images or to create a tag that includes git. This is because with some projects gitlab does a shallow clone of the repo and gitversion fails to find the correct id. This is solved by using git to fetch the repo and change the branch. I know I can create a custom image based on yours but I think it would be great if you include to option to have git in the image.

**Comment by arturcic** [comment]
You can have a look here https://github.com/GitTools/build-images

**Comment by arturcic** [comment]
And you can send us a PR to that repo

**Comment by elferherrera** [comment]
Excuse my ignorance, but how do you find the images you have in that repo in docker?

**Comment by arturcic** [comment]
This is the Dockerfile for alpine for example https://github.com/GitTools/build-images/blob/master/src/linux/alpine.3.10-x64/Dockerfile

**Comment by elferherrera** [comment]
Yes, I understand that that is the image and if I were to create a PR I may create another folder with the new dockerfile including git's installation. What I was wondering is how I find these images in docker in order to download a specific version?

**Comment by arturcic** [comment]
well I don't think it hurts if we add the git client to these dockerfiles

**Comment by elferherrera** [comment]
so, if I were to add to the debian file the instruction "apt install -y git" would that mean that git is going to be available on the gittools/gitversion image in docker?

Would you like to add git to all the files?

**Comment by arturcic** [comment]
to be honest I do not have the time, but a PR from you would be very welcomed

**Comment by elferherrera** [comment]
sure... I'll work on it

**Comment by arturcic** [comment]
Closing as [this](https://github.com/GitTools/build-images/pull/1) one was merged
