### ISSUE TITLE
[Feature] Github action for gitversion

### ISSUE THREAD

**Issue by MindaugasLaganeckas** [GitTools/GitVersion#2417]
**Is your feature request related to a problem? Please describe.**
I would like to use gitversion in my builds here on github. Now I am using a docker image with gitversion. I think it would be more user friendly to use github action.

## Detailed Description
I propose action.yml file as described here https://docs.github.com/en/free-pro-team@latest/actions/creating-actions/metadata-syntax-for-github-actions. I propose to use the existing docker image from github as a driver for the action. E.g.
```
runs: 
  using: 'docker'
  image: 'gittools/gitversion:5.3.5-linux-alpine.3.10-x64-netcoreapp3.1'
```

## Context

People will be able to integrate GitVersion in to their build pipelines in Github.
I am using it for the Mermaid CLI project myself.  

## Possible Implementation

In the action.yml
```
runs: 
  using: 'docker'
  image: 'gittools/gitversion:5.3.5-linux-alpine.3.10-x64-netcoreapp3.1'
```

**Comment by arturcic** [comment]
@MindaugasLaganeckas can you check this one? https://github.com/GitTools/actions

**Comment by MindaugasLaganeckas** [comment]
@arturcic : I am so sorry for wasting your time! Have a really nice day! :smile:
