### ISSUE TITLE
[Docs Not Secured] Mixed Content error on gitversion.net (at least)

### ISSUE THREAD

**Issue by tebeco** [GitTools/GitVersion#2418]
**Describe the bug**
The browser is not happy because some images are pointing to `http` only website while `gitversion.net` is `https

## Expected Behavior
Use `https` everywhere

## Actual Behavior
loading https://gitversion.net/docs/more-info/how-it-works will load an image that is here:
(I won't complain about that URL length ...)
http://www.plantuml.com/plantuml/png/fLCxJyCm4DxzAsuib4P914i69De1CS38Vd6kYIN7ZcodK8aVp-KX6Y2fKCbY9NV-7lVb2WoOeoVOMRDNfH0lz1vUoNbbpGwrR3K6ws1p3rlk-bN8u972f2AC3GHEbLN8m1D1Jjg-mPuXAZvx9kL1ZW1KY5dOZczMI0Pf54VnHtf7jpaAWJg0sW-uXw4PK3Eb1sMaevfCW6i1_0m6po1l7HfPJUxvu5XYUOHLWq5MLptCudmMK9--u5glJ0dIEaVo1Dw3JgVM6Km4cM9mzyrQXHuQHnj7chhl0JcnIrHjno1wiWtgfi8eWVK_7OQAmBHrJWvORFVM2PmrE7AcWZGh-Lj0FvptVvLiUPnCdG_XhNhOov9wQ1fzv7nw5S5EwSvw6CDQNfnMwUAP0XQyQpj70nkx3Nn3p5NFY9IshbNWepKi8ublWFiSPkC0ee8El75Dv5aOxqZQBScbWpWn0Pe2wb6aM1p4Eea_0G00

Even the github md use external repository, which might be subject to change, and then ... 404 in the docs
especially when it's already using 307 redirect on possible "Saved docs on a third part designer" :)
![image](https://user-images.githubusercontent.com/2266487/95265113-d599a200-0830-11eb-9efc-7cd876efb7f4.png)

## Possible Fix
These images are also present in the repo, which is version, and the RAW url from github for the github docs would make a better candidate:
we can see it here: 
https://github.com/GitTools/GitVersion/blob/master/docs/input/docs/more-info/how-it-works.md
https://camo.githubusercontent.com/939d04e389925b3368e60e0da6fb78ee44fd6f47/687474703a2f2f7777772e706c616e74756d6c2e636f6d3a38302f706c616e74756d6c2f706e672f664c43784a79436d3444787a41737569623450393134693639446531435333385664366b59494e375a636f644b386156702d4b58365932664b436259394e562d376c566232576f4f656f564f4d52444e6648306c7a3176556f4e62627047777252334b367773317033726c6b2d624e38753937326632414333474845624c4e386d3144314a6a672d6d507558415a7678396b4c315a57314b5935644f5a637a4d493050663534566e487466376a706141574a673073572d75587734504b33456231734d6165766643573669315f306d36706f316c374866504a55787675355859554f484c5771354d4c70744375646d4d4b392d2d7535676c4a3064494561566f314477334a67564d364b6d34634d396d7a79725158487551486e6a376368686c304a636e4972486a6e6f3177695774676669386557564b5f374f51416d4248724a57764f5246564d32506d7245374163575a47682d4c6a304676707456764c6955506e4364475f58684e684f6f7639775131667a76376e773553354577537677364344514e666e4d775541503058517951706a37306e6b78334e6e3370354e465939497368624e5765704b693875626c57466953506b4330656538456c3735447635614f78715a51425363625770576e30506532776236614d3170344565615f30473030

Maybe moving images from "outside" to the repo + link to the reference / original site would fix
* the `http` issue
* the possible 404
* the URI format

## Steps to Reproduce
Open https://gitversion.net/docs/more-info/how-it-works
your browser will be angry
![image](https://user-images.githubusercontent.com/2266487/95264987-923f3380-0830-11eb-84c3-3f55e48f8582.png)

## Context
Reading the docs

## Your Environment
Canary MsEdge

**Comment by asbjornu** [comment]
Thanks for noticing this. I'm not sure why we use PlantUML to host this image for us. A pull request moving the image (preferably [the SVG version](https://www.plantuml.com/plantuml/svg/fLCxJyCm4DxzAsuib4P914i69De1CS38Vd6kYIN7ZcodK8aVp-KX6Y2fKCbY9NV-7lVb2WoOeoVOMRDNfH0lz1vUoNbbpGwrR3K6ws1p3rlk-bN8u972f2AC3GHEbLN8m1D1Jjg-mPuXAZvx9kL1ZW1KY5dOZczMI0Pf54VnHtf7jpaAWJg0sW-uXw4PK3Eb1sMaevfCW6i1_0m6po1l7HfPJUxvu5XYUOHLWq5MLptCudmMK9--u5glJ0dIEaVo1Dw3JgVM6Km4cM9mzyrQXHuQHnj7chhl0JcnIrHjno1wiWtgfi8eWVK_7OQAmBHrJWvORFVM2PmrE7AcWZGh-Lj0FvptVvLiUPnCdG_XhNhOov9wQ1fzv7nw5S5EwSvw6CDQNfnMwUAP0XQyQpj70nkx3Nn3p5NFY9IshbNWepKi8ublWFiSPkC0ee8El75Dv5aOxqZQBScbWpWn0Pe2wb6aM1p4Eea_0G00)) into this repository would be accepted.
