### ISSUE TITLE
[Feature]Prerelease tag identifies if build on the build system.

### ISSUE THREAD

**Issue by RobSmyth** [GitTools/GitVersion#2428]
## Detailed Description

Provide ability, when using Continuous Delivery mode, for the prerelease tag "beta" to be dependent on if building from a build server of orr a developer box. This provides detection of uncontrolled builds.

The prerelease tag would be:

- **Alpha** - for any build on a developer's box regardless of the branch.
- **Beta** - for any build, on the build system, that is not on a release branch.
- **<empty>** - for any release branch build on the build system.

## Context

This import in environments were developer's frequently build and copy code to test systems/machines /devices. It allows for:

* Positive identific of build box builds. (Useful for testers, and release management).
* Easy identification of unofficial code being used on equipment and/or customer installs.
* Enables use of different metadata in developer box builds for superior traceability (e.g: Who). That is, if developer's code is found on a machine it is easy to determine which developer and check purpose before removing.

## Possible Implementation

(sorry ... I do not know)

**Comment by asbjornu** [comment]
This would probably not be very hard to implement, but as I have no need for such a feature, I'm not going to spend time doing it, sorry. Pull requests are welcome.
