### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by jhulbertpmn** [GitTools/GitVersion#2431]
**Describe the bug**
The Azure DevOps pipeline task - when executing GitVersion - does not appear to detect .net 5 rc2 as a valid sdk

## Actual Behavior
Command: dotnet-gitversion /__w/1/s /output json /output buildserver
/__t/GitVersion.Tool/5.3.7/x64/dotnet-gitversion /__w/1/s /output json /output buildserver
It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '3.1.0' was not found.
  - The following frameworks were found:
      5.0.0-rc.2.20475.5 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]

You can resolve the problem by installing the specified framework and/or SDK.

## Steps to Reproduce
-Create a .net 5 app - simple console app or class library
-Setup an Azure DevOps pipeline for the project
-Setup the pipeline to build in a container: container: mcr.microsoft.com/dotnet/sdk:5.0
-Install gitversion 5.x
-Run gitversion/execute@0

## Context
Setting up a new project, using .net5rc2 now that it is supported for production. Had to remove the gitversion tasks for now.

## Your Environment
Azure DevOps build pipeline
Running in container mcr.microsoft.com/dotnet/sdk:5.0
Using vmImage 'ubuntu-latest'

**Comment by nloum** [comment]
I don't know anything about the Azure DevOps task you're using, but I suspect at least part of the change is to add `.net5.0` to this line: https://github.com/GitTools/GitVersion/blob/master/src/GitVersionExe/GitVersionExe.csproj#L7

**Comment by asbjornu** [comment]
A pull request adding support for .NET 5 would be welcome, provided that all tests execute successfully.

**Comment by vip32** [comment]
https://github.com/GitTools/GitVersion/pull/2452

**Comment by atrauzzi** [comment]
Noticing this on github actions as well, can't build my 5.x projects.

**Comment by Kralizek** [comment]
any ETA for this issue?

I'm not able to run builds on CircleCI when using the .NET 5.0 docker images

**Comment by arturcic** [comment]
Should be fixed by https://github.com/GitTools/GitVersion/pull/2486 in v5.6.0
