### ISSUE TITLE
[Bug] Support for Github 'main' branch

### ISSUE THREAD

**Issue by chr15murray** [GitTools/GitVersion#2433]
**Describe the bug**
A newly created github repo now uses 'main' instead of 'master' as the default branch. Attempting to run gitversion against this results in. 
`System.InvalidOperationException: Could not find a 'develop' or 'master' branch, neither locally nor remotely.`
I believe the default behavior should be extedned to include 'main' also.

Other command such as /init also fail

## Expected Behavior

A 'main' branch should be treated the same as a 'master' branch with default configuration.

## Actual Behavior

There is no default handling for a main branch and the lack of master or develop causes an error to be returned.

## Steps to Reproduce

- Create a new repo (default branch will be set to 'main'
- clone repo
- run gitversion and expect the error

## Context

I expect I will need to create a GitVersion.yml and setup main branch handling until this is supported. Alternatively I could rename my branch to master.

## Your Environment

- Version Used: 5.3.7
- Operating System and version (Windows 10, Ubuntu 18.04): OSX
- Link to your project: N/A
- Link to your CI build (if appropriate): N/A

**Comment by asbjornu** [comment]
#2367 added support for `main`, but it has unfortunately not been released yet. We'll be sure to get a release out the door soon.

**Comment by jeanfrancoislarente** [comment]
@chr15murray - would be useful if you could edit the title of the issue.

**Comment by atrauzzi** [comment]
Any possible workarounds while we wait for the release?

**Comment by gep13** [comment]
@atrauzzi you should be able to setup the configuration file similar to the following:

https://github.com/Jericho/ZoomNet/blob/develop/GitVersion.yml

Where that repository has already made the switch to using `main`

**Comment by asbjornu** [comment]
@atrauzzi, #2367 should have been included in the 5.5.0 release that went out the door 16 days ago. Does it now work?

**Comment by jeanfrancoislarente** [comment]
@asbjornu - Don't want to hijack this thread, but I'm trying to take advantage of the latest version to resolve the issue in this thread but I'm using Azure pipeline task `GitVersion@5` and it seems like it's always only installing 5.0.1? 

Are there steps to get 5.5.0 supported in Azure Pipelines so that I can take advantage of the latest version changes? 

```
steps:
- task: GitVersion@5
  inputs:
    runtime: 'core'
    configFilePath: 'GitVersion.yml'
    updateAssemblyInfo: true
```

Output in pipeline:
```
Task         : GitVersion Task
Description  : Easy Semantic Versioning (http://semver.org) for projects using Git
Version      : 5.0.1
Author       : GitVersion Contributors
```

**Comment by arturcic** [comment]
@jeanfrancoislarente `GitVersion` task is obsolete, please consider moving to https://marketplace.visualstudio.com/items?itemName=gittools.gittools. Here is a sample on 
 how to use it https://github.com/GitTools/actions/blob/master/docs/examples/azure/gitversion/index.md

**Comment by jeanfrancoislarente** [comment]
Thanks for the prompt response @arturcic  - moved over now. Issue with updateAssemblyFileInfo but I'll dig into that and/or create a separate issue once I'm done testing the switch to main branch!

**Comment by atrauzzi** [comment]
I think the GitHub action for gitversion might need to be updated.

**Comment by fowl2** [comment]
I'm still receiving this error in version 5.5.1.

(also, seems like the [error message](https://github.com/GitTools/GitVersion/blob/07ddcefd18404839f6165085bc57f8e5790304d1/src/GitVersionCore/Configuration/BranchConfigurationCalculator.cs#L134) will need to be updated too)

**Comment by asbjornu** [comment]
> (also, seems like the [error message](https://github.com/GitTools/GitVersion/blob/07ddcefd18404839f6165085bc57f8e5790304d1/src/GitVersionCore/Configuration/BranchConfigurationCalculator.cs#L134) will need to be updated too)

Indeed. Pull requests are welcome! 🙏

**Comment by asbjornu** [comment]
I'm fairly confident this is properly implemented and supported now. Closing.
