### ISSUE TITLE
[Feature] Net5.0 support for GitVersion.Tool (And probably the others as well).

### ISSUE THREAD

**Issue by SeppPenner** [GitTools/GitVersion#2466]
This feature request is related to my issue under https://github.com/GitTools/GitVersion/issues/2465.

## Detailed Description
We have a build image in Docker running `mcr.microsoft.com/dotnet/sdk:5.0-buster-slim` (For more details, see issue linked above) and try to run GitVersion.Tool from the command line with Net5.0 which is not possible right now.

## Context
Net5.0 is the newest framework, so it should be supported when possible.

## Possible Implementation
None.

**Comment by asbjornu** [comment]
This is being worked on in #2452. Contributions are welcome.

**Comment by SeppPenner** [comment]
Seems like you are mainly waiting for a new nunit release there. I will see if I can help here.

**Comment by arturcic** [comment]
Fixed by https://github.com/GitTools/GitVersion/pull/2486 in v5.6.0
