### ISSUE TITLE
[Bug] GitVersion fails on Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by cobrafast** [GitTools/GitVersion#2471]
**Describe the bug**
GitVersion seems to be unable to locate libssl1.0.0 which is needed by libgit2 shipped via nuget.

I have installed libssl1.0.0 but it doesn't like it or something:

```
/home/anse/.nuget/packages/gitversiontask/5.3.7/build/GitVersionTask.targets(71,9): error : TypeInitializationException: The type initializer for 'LibGit2Sharp.Core.NativeMethods' threw an exception.
/home/anse/.nuget/packages/gitversiontask/5.3.7/build/GitVersionTask.targets(71,9): error : DllNotFoundException: Unable to load shared library '/home/anse/.nuget/packages/gitversiontask/5.3.7/tools/netstandard2.0/runtimes/linux-x64/native/libgit2-ef5a385.so' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libssl.so.1.0.0: cannot open shared object file: No such file or directory
```

```
ldd /home/anse/.nuget/packages/gitversiontask/5.3.7/tools/netstandard2.0/runtimes/linux-x64/native/libgit2-ef5a385.so
        linux-vdso.so.1 (0x00007ffe57791000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f670298c000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f6702969000)
        libssl.so.1.0.0 => /lib/x86_64-linux-gnu/libssl.so.1.0.0 (0x00007f6702701000)
        libcrypto.so.1.0.0 => /lib/x86_64-linux-gnu/libcrypto.so.1.0.0 (0x00007f67022bc000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f67020ca000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f6702cf2000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f67020c2000)
```

```
libssl1.0.0:
  Installed: 1.0.2g-1ubuntu4.17
  Candidate: 1.0.2g-1ubuntu4.17
  Version table:
 *** 1.0.2g-1ubuntu4.17 500
        500 http://security.ubuntu.com/ubuntu xenial-security/main amd64 Packages
        100 /var/lib/dpkg/status
```

May be related to #1901.

## Expected Behavior
Everything just works.

## Actual Behavior
Nothing works.

## Possible Fix
\-

## Context
This bug prevents me from building/running dotnet projects on Linux.

## Your Environment

- Version Used: 5.3.7 apparently
- Operating System and version (Windows 10, Ubuntu 18.04): Ubuntu 20.04 LTS
- Link to your project:
- Link to your CI build (if appropriate):

**Comment by arturcic** [comment]
>> May be related to #1901.

Well it is and the issue is the library we rely on Libgit2sharp

**Comment by cobrafast** [comment]
Apparently running `dotnet build -r ubuntu.18.04-x64` works around the problem even though it fails (I suspect it has something to do with the implicit restore run by it). A subsequent `dotnet build` will then run fine. Peculiar.

**Comment by perosb** [comment]
This will also affect everyone using gitversion on azure devops ubuntu-latest which soon switches to 20.04
https://github.com/actions/virtual-environments/issues/1816

**Comment by arturcic** [comment]
[Fixed](https://github.com/GitTools/GitVersion/pull/2486) in v5.6.0
