### ISSUE TITLE
[Bug] Cannot use output parameter due to it being hardcoded by task

### ISSUE THREAD

**Issue by quasarea** [GitTools/GitVersion#2473]
**Describe the bug**
Running gitversion with /output file parameter gets overwritten. Actually it gets overwritten twice with two different parameters - json and buildserver.

```
C:\hostedtoolcache\windows\GitVersion.Tool\5.5.1\x64\dotnet-gitversion.exe D:/a/1/s /output json /output buildserver /config /output file
```

## Expected Behavior
Being able to specify intended output, perhaps as parameter

## Actual Behavior
buildserver output type gets precedence over both json and file outputs

## Possible Fix
Expose output as parameter

## Steps to Reproduce
Create task that will save GitVersion.json file using /output file parameter

## Context
I'm not able to create json artifact to reuse it in other jobs

**Comment by asbjornu** [comment]
Can you perhaps create this issue in the [actions](https://github.com/GitTools/actions) repository as this is not related to GitVersion itself?

**Comment by quasarea** [comment]
Sure, done, thanks https://github.com/GitTools/actions/issues/282
