### ISSUE TITLE
Support 'assembly-versioning-format' option as a part of '/overrideconfig' command line parameter

### ISSUE THREAD

**Issue by nenadvicentic** [GitTools/GitVersion#2485]
It would be very useful to support syntax overriding **'assembly-versioning-format'** as a part of command-line arguments for `/overrideconfig`. At the moment of writing this, only `tag-prefix` option is supported.

**Reason for request:**

Currently, only way to override **'assembly-versioning-format'** option is via configuration files. For example `GitVersion.yml` file in the root of repository. This means that to use custom version format on the company level, one has to commit new file in each repository. It's not possible to control formatting this via CI build-configuration alone.

Example syntax:
```
> gitversion /overrideconfig assembly-versioning-format='{Major}.{Minor}.{Patch}.{env:CI_JOB_ID ?? 0}'
```

Or perhaps double-quotes would be more consistent for the value-part?
`"{Major}.{Minor}.{Patch}.{env:CI_JOB_ID ?? 0}"`

**Comment by asbjornu** [comment]
Extending `/overrideconfig` to support every property supported in `GitVersion.yml` is something I support. I'm kind of surprised only `tag-prefix` is the only supported property. Pull requests are welcome.

**Comment by nenadvicentic** [comment]
After checking the code, I see multiple problems related to full `GitVersion.yml` implementation:

- Some of the properties of `GitVersion.yml` are complex types. For example `Branches` are dictionary of `BranchConfigs, `MergeMessageFormats` or `Ignore`, having multiple properties of their own. 
- Different parsing implementations. `GitVersion.yml` relies on `YamlDotNet` and it's attributes to parse `GitVersion.yml` file and deserialize it in `GitVersion.Model.Configuration.Config` class. Separate implementation would be required for line arguments parsing.
- Keeping all properties of `Config` class in sync with command line arguments would require maintenance two separate lists of properties. Second option would be `Reflection` on `YamlMemberAttribute`s of `Config` class, but that would create other issues.

I would suggest to start smaller: implement only a few properties that make sense to be used from command line and are usually not project specific.

For example: `assembly-informational-format`, `assembly-versioning-format` and `assembly-file-versioning-format`, as versioning schema makes a lot of sense to be applied globally, across all company's projects.

**Comment by asbjornu** [comment]
Thanks for diving into it, @nenadvicentic. That sounds reasonable. Perhaps it makes sense to only allow simple typed properties that can be represented by strings on the command line?

**Comment by phitattoo** [comment]
ผมก็แค่ว่างจัดครับ😂😂😂
