### ISSUE TITLE
[Bug] MsBuildTask does not set GitVersionInformation.UncommittedChanges

### ISSUE THREAD

**Issue by NeilMacMullen** [GitTools/GitVersion#2496]
**Describe the bug**
I have added the GitVersionTask (5.5.1) nuget package to a C# command line application.  Within that application I test the **UncommitedChanges** variable to see if the code was built from "dirty" source (i.e. code with changes that were not committed first).
 
` var dirtyBuild =  GitVersionInformation.UncommittedChanges != "0";`

I am *expecting* this variable to hold some measure of the extent of locally modified files (# diff lines, # modified files etc) but it seems to return **"0"** regardless of whether I have made local changes to the source prior to the build.  For example here is the output of git diff prior to build...

```
16:03>git diff --stat
 Test/Test.cs | 4 +++-
 1 file changed, 3 insertions(+), 1 deletion(-)
```
After building this source,  `Console.WriteLine(GitVersionInformation.UncommittedChanges);` displays "0";

Note that other **GitVersionInformation** fields such as **ShortSha**, **CommitDate** etc are populated as expected so the task is running correctly.

## Steps to Reproduce
- Create a new C# Console Application in Visual Studio
- Add the GitVersionTask nuget package to the application
- Ensure the project is added to source control
- Add   `Console.WriteLine(GitVersionInformation.UncommittedChanges); ` to the main method
- Build and run the application

## Your Environment
Visual Studio Preview 16.9.0 pv2
Windows 10

**Comment by asbjornu** [comment]
There's probably a mapping missing when producing the MSBuild properties or something. If you're able to figure out the missing piece, we'd love a pull request.

**Comment by bddckr** [comment]
I've opened #2497 which should resolve this.

Assuming my PR helps (and gets merged) you'll need to switch from GitVersionTask to [GitVersion.MsBuild](https://www.nuget.org/packages/GitVersion.MsBuild) as [that is the replacement for the former since 5.6.0](https://github.com/GitTools/GitVersion/commit/6af3b9cd1cad912877daa30ae671ccb72145b94f).

**Comment by NeilMacMullen** [comment]
Super job - thanks @bddckr  !
