### ISSUE TITLE
[Bug] GitVersion.MsBuild removing assembly attributes defined in csproj

### ISSUE THREAD

**Issue by impsnldavid** [GitTools/GitVersion#2501]
In my .csproj file, I have the following declaration to make internals visible to the unit test assembly:

```xml
<ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
        <_Parameter1>$(MSBuildProjectName).Test</_Parameter1>
    </AssemblyAttribute>
</ItemGroup>
```

When compiling with GitVersion.MsBuild 5.6.1 (via NuGet) this assembly attribute is not being applied. If the NuGet package is uninstalled, the attribute is applied again.

Project is a net5.0 library, building with VS2019 16.8.3.

**Comment by hlaebe** [comment]
I can second this. These two attributes
- AssemblyCompanyAttribute
- AssemblyTitleAttribute
applied by vs2019 by default, are missing when using GitVersion.MsBuild 5.6.1. As @impsnldavid reported, running without package works as expected.

Project is net4.8, building with vs2019 16.8.3

**Comment by ThomasBarnekow** [comment]
I can confirm @hlaebe's comment. I have code that displays this information to the user in an About dialog. This behavior obviously breaks my code.

**Comment by asbjornu** [comment]
Pull requests are welcome! 🙏🏼

**Comment by hlaebe** [comment]
> Pull requests are welcome! 🙏🏼

Would you mind to give a hint on which part of the code I should look into ? I'm not used to the source code nor the structure.

🤷‍♂️
