### ISSUE TITLE
[Docs] Update the docs to reflect the current state of the code base

### ISSUE THREAD

**Issue by arturcic** [GitTools/GitVersion#2503]

**Comment by asbjornu** [comment]
It would be great if #2326 was taken into account at the same time.

**Comment by arturcic** [comment]
@asbjornu if you could reference all docs issues to point to this one so that we can later update them all

**Comment by asbjornu** [comment]
Sure. Currently we have #2409, #2365, #2194 and #1381 in addition to the one already mentioned.
