### ISSUE TITLE
[Docs]  Documentation references Deprecated version of GitVersionTask

### ISSUE THREAD

**Issue by vllama** [GitTools/GitVersion#2504]
Page at https://gitversion.net/docs/build-server-support/build-server/azure-devops references installing the Deprecated GitVersionTask task here : [https://www.nuget.org/packages/GitVersionTask/ ](https://www.nuget.org/packages/GitVersionTask/ )
as well as a deprecated GitVersion Extension here:
[https://marketplace.visualstudio.com/items?itemName=gittools.usegitversion](https://marketplace.visualstudio.com/items?itemName=gittools.usegitversion)

The new versions of the tools don't seem to work the same when following the  existing documentation.

**Comment by arturcic** [comment]
I will close this one in favor of https://github.com/GitTools/GitVersion/issues/2503 as it covers all the docs
