### ISSUE TITLE
[Improvement] Make the Nuget package icon in a solid bright color with borders so it can be seen in Visual Studio's dark UI.

### ISSUE THREAD

**Issue by LazaroOnline** [GitTools/GitVersion#2508]
Make the Nuget package icon in a solid bright color so it can be seen in Visual Studio's dark UI for easier identification and to improve quality perception upon users.

This is how it is seen currently from Visual Studio using the Dark UI:
![GitVersion-Icon-VisualStudioDarkUI](https://user-images.githubusercontent.com/13026853/103577630-76056e00-4ed5-11eb-9d8c-c7d1599a9331.jpg)

as an example from Microsoft, they use a bright color with a border around it so that it always has contrast regardless of the background color.
![Microsoft-icon-examples](https://user-images.githubusercontent.com/13026853/103577790-b8c74600-4ed5-11eb-8b04-b00ad68538f5.jpg)

**Comment by arturcic** [comment]
We have a repo for the graphics - https://github.com/GitTools/graphics You can check it out

**Comment by LazaroOnline** [comment]
Here are some proposals in transparent high-res png:
![GitVersionIcon-Circle](https://user-images.githubusercontent.com/13026853/103580223-165d9180-4eda-11eb-9a1e-52f370ef1e1e.png)
![GitVersionIcon-Square](https://user-images.githubusercontent.com/13026853/103580225-16f62800-4eda-11eb-84c0-45b172e4519b.png)
![GitVersionIcon-Stroke](https://user-images.githubusercontent.com/13026853/103580226-16f62800-4eda-11eb-83ab-736dda603ddb.png)

**Comment by arturcic** [comment]
I prefer the last one, @GitTools/developers what do you think?

**Comment by arturcic** [comment]
Also we need the GitTools logo to update in case the GitVersion gets updated

**Comment by gep13** [comment]
Yes, I like the last one as well!

**Comment by arturcic** [comment]
@gep13 what about GRM? Should we update it as well?

**Comment by LazaroOnline** [comment]
Here are some versions for GitTool also:
![GitTool-Square](https://user-images.githubusercontent.com/13026853/103586298-16af5a00-4ee5-11eb-85f5-0dad26bfcdb8.png)
![GitTool-Stroke](https://user-images.githubusercontent.com/13026853/103586299-1747f080-4ee5-11eb-9909-a7490cd035df.png)

**Comment by arturcic** [comment]
Last one looks better for me and in the same theme as GitVersion

**Comment by LazaroOnline** [comment]
Now that GitHub has a dark mode, the documentation will also improve readability by updating the repos to the new icon version.

Here is a list of docs to be updated and its location:

https://github.com/GitTools/actions#gittools-actions
https://github.com/GitTools/actions/blob/master/docs/icon.png
https://github.com/GitTools/GitVersion#--------gitversion
https://github.com/GitTools/GitTools.Core#------gittoolscore

This link cannot be seen in GitHub dark mode:
https://github.com/GitTools/GitLink#gitlink

In this one you could use the icon with the color background:
https://github.com/GitTools/GitReleaseManager#gitreleasemanager  
https://github.com/GitTools/graphics/blob/master/GitReleaseManager/icon_128x128.png

The icon link in these repos are broken, I'm not sure what was the icon used before: 
https://github.com/GitTools/GitTools.Testing#gittoolstesting
https://github.com/GitTools/GitTools.IssueTrackers

**Comment by LazaroOnline** [comment]
For GitLink, if someone is interested, here is a version following the same scheme:

SVG:
[GitLink-svg.zip](https://github.com/GitTools/GitVersion/files/5770960/GitLink.zip)

128 png:
![logo_128](https://user-images.githubusercontent.com/13026853/103663062-f9c06880-4f70-11eb-93b2-b679de67096b.png)

**Comment by arturcic** [comment]
> https://github.com/GitTools/GitTools.Testing#gittoolstesting

This one was archived, now the source code is back into GitVersion

**Comment by arturcic** [comment]
@LazaroOnline thank you for taking the time, I have updated dockerhub, GitHub organization, updated the gittools/actions Azure and GitHub Action tasks, the nuget packages will get updated on next release

**Comment by gep13** [comment]
@arturcic for GRM, we already went a slightly different path, so I don't think an update is required there:

https://github.com/GitTools/graphics/blob/master/GitReleaseManager/icon_100x100.png

**Comment by LazaroOnline** [comment]
We forgot to update the icon in one more location:

https://github.com/GitTools/GitVersion/blob/master/docs/input/docs/img/package_icon.png

It should get replaced by this one:
![package_icon](https://user-images.githubusercontent.com/13026853/103691829-225b5900-4f97-11eb-9f83-a5e168f37efe.png)

Can someone with repo access update the image?
for binary files GitHub doesn't have a quick edit-and-PR functionality.

**Comment by asbjornu** [comment]
Awesome, @LazaroOnline! Can you please provide the icons in SVG format as well?

**Comment by LazaroOnline** [comment]
SVG versions are available here if required:
https://github.com/GitTools/graphics/blob/master/GitVersion/Color/icon.svg
https://github.com/GitTools/graphics/blob/master/GitTools/Color/icon.svg
