### ISSUE TITLE
[Bug] Specifying preferBundledVersion to false in task gittools.gitversion.gitversion-task.GitVersion@5 does not use gitversion installed on the build server

### ISSUE THREAD

**Issue by tristanbarcelon** [GitTools/GitVersion#2513]
**Describe the bug**
Based on how I interpreted the gitversion task documentation, specifying preferBundledVersion to false would cause the task to utilize gitversion that is available on the build server. During build, task seems to only use version 5.0.1, at least from what I could tell in the log. Perhaps the version logged is the task version and not the gitversion used. Looking at the pipeline logs, it shows that it is still using the bundled gitversion.dll even though preferBundledVersion is set to false in the task.

## Expected Behavior
It should use gitversion.exe or gitversion that is found in the path rather than the bundled dll when preferBundledVersion is false.

## Actual Behavior
Browsing through the Azure Devops build log, I can see that it is using the bundled dll.

```text
Starting: GitVersion
==============================================================================
Task         : GitVersion Task
Description  : Easy Semantic Versioning (http://semver.org) for projects using Git
Version      : 5.0.1
Author       : GitVersion Contributors
Help         : See the [documentation](http://gitversion.readthedocs.org/en/latest/) for help
==============================================================================
"C:\Program Files\dotnet\dotnet.exe" d:\agentwork\a1\_tasks\GitVersion_e5983830-3f75-11e5-82ed-81492570a08e\5.0.1\core\GitVersion.dll d:\agentwork\a1\67\s /output buildserver /nofetch /config d:\agentwork\a1\67\s\gitversion.yml /updateassemblyinfo true
```

Should I be specifying the **gitVersionPath** input parameter as well? If so, should it be the full path to gitversion.dll or just the folder containing gitversion.dll? Runtime it set to dotnet core. The linux release archive contains 2 executable files: gitversion and libgit2-6777db8.so. What should the gitVersionPath input parameter be for ubuntu 18.04? Should it be set to /usr/local/bin/gitversion or /usr/local/bin?

**Comment by arturcic** [comment]
Unfortunately we do not support this extension any more. Please use the new bundle https://marketplace.visualstudio.com/items?itemName=gittools.gittools with examples on usage: https://github.com/GitTools/actions/blob/master/docs/examples/azure/gitversion/index.md
