### ISSUE TITLE
[Bug] GitVersion.MSBuild fails when running "dotnet.exe pack"

### ISSUE THREAD

**Issue by dieterv** [GitTools/GitVersion#2523]
**Describe the bug**
Running "dotnet.exe pack" fails with  `error MSB4044: The "GenerateGitVersionInformation" task was not given a value for the required parameter "Language"`.

## Expected Behavior
"dotnet.exe pack" running to completion.

## Actual Behavior
Now that #2502, #2518 and #2519 have been fixed in 5.6.2 my "dotnet.exe build" and "dotnet.exe test" jobs are passing.
Running "dotnet.exe pack" and "dotnet.exe pack --no-build" however both fail with `error MSB4044: The "GenerateGitVersionInformation" task was not given a value for the required parameter "Language"`.

## Context
It is no longer possible to build a NuGet package using "dotnet.exe pack".

## Your Environment

- GitVersion.MsBuild 5.6.2
- Windows 10

**Comment by arturcic** [comment]
@dieterv could you create a sample project with the repro so I can check it

**Comment by dieterv** [comment]
@arturcic sure, see https://github.com/dieterv/GitVersion-issues-2523
This is what I get when running  `powershell -File build.ps1`:
```
<snip>
========================================
Package
========================================
Executing task: Package
<snip>
C:\Program Files\dotnet\sdk\5.0.101\MSBuild.dll -maxcpucount -property:NoBuild=true -property:IncludeSymbols=true -property:Configuration=Release -target:pack -verbosity:m /bl:C:/Development/github.com/GitTools/GitVersion-issues-2523/build/artifacts/dotnet_pack.binlog C:/Development/github.com/GitTools/GitVersion-issues-2523/Reproducer.sln
C:\Users\dieter\.nuget\packages\gitversion.msbuild\5.6.3\tools\GitVersion.MsBuild.targets(110,9): error MSB4044: The "GenerateGitVersionInformation" task was not given a value for the required parameter "Language". [C:\Development\github.com\GitTools\GitVersion-issues-2523\source\Reproducer\Reproducer.csproj]
An error occurred when executing task 'Package'.
<snip>
```

**Comment by arturcic** [comment]
I will check it

**Comment by Thanos06660** [comment]
Same problem here on a build pipeline after upgrading to gitversion.msbuild 5.6.3

**Comment by Thanos06660** [comment]
The Problem seems to apply cause the $(Language)-variable for the compile language seems to be empty. 

This is strange because it should be defined in Microsoft.CSharp.CurrentVersion.Targets ?!
 
```
<GenerateGitVersionInformation SolutionDirectory="$(GitVersionPath)" VersionFile="$(GitVersionOutputFile)"
                                       ProjectFile="$(MSBuildProjectFullPath)"
                                       IntermediateOutputPath="$(IntermediateOutputPath)"
                                       Language="$(Language)">
```

**Comment by dieterv** [comment]
@arturcic I've prepared a patch that skips all GitVersion MSBuild tasks entirely when the Language property is not set, as is the case when running the "pack" target. I'm not entirely sure if this is too big a hammer to fix this problem though? Read below for a slightly smaller hammer.
![image](https://user-images.githubusercontent.com/220082/104179658-81dcbd00-540c-11eb-97fa-7d0c767880a4.png)

In my first attempt I only skipped the GenerateGitVersionInformation and UpdateAssemblyInfo MSBuild tasks but then I was wondering why we would even want to run the RunGitVersion, WriteVersionInfoToBuildLog and GetVersion tasks during the "pack" target. And maybe even other non build related targets? Seemed like a waste of CPU cycles to me, so I moved the condition up a level to the RunGitVersion task. Works for me (tm) with the reproducer project but see my question above...
![image](https://user-images.githubusercontent.com/220082/104168235-083dd280-53fe-11eb-9b31-45224dd7f1a6.png)

The reproducer project from above succeeds with both approaches but I'd like your thoughts before finishing this into a PR :-)
Both approaches available in my [feature/issues-2523 branch](https://github.com/dieterv/GitVersion/commits/feature/issues-2523)

**Comment by Thanos06660** [comment]
We use the "pack" target in an TFS Build step. Will the generated nuget-package get the right naming after your "patch"?

**Comment by arturcic** [comment]
> We use the "pack" target in an TFS Build step. Will the generated nuget-package get the right naming after your "patch"?

I doubt that

@dieterv an easier solution would be to have a fallback for Language like
`<Language Condition=" '$(Language)' == '' ">C#</Language>` in the GitVersion.MsBuild.props

**Comment by dieterv** [comment]
> > We use the "pack" target in an TFS Build step. Will the generated nuget-package get the right naming after your "patch"?

Ah, of course. Scrap both of my proposals, they indeed end up with wrong NuGet package names.

**Comment by Thanos06660** [comment]
is there a way to implement this fallback manually only in my solution/project?

**Comment by dieterv** [comment]
@arturcic thank you :smile:

**Comment by Thanos06660** [comment]
Super!
