### ISSUE TITLE
[Bug]Build error due to malformed file path `obj\/gitversion.json`

### ISSUE THREAD

**Issue by NameOfTheDragon** [GitTools/GitVersion#2534]
**Describe the bug**
GitVersion.MSBuild nuget package v5.6.3 uses a badly formed path that causes a build error.
The build log makes this clear:
<pre>
C:\Users\Tim\.nuget\packages\gitversion.msbuild\5.6.3\tools\GitVersion.MsBuild.targets: The command "C:\Users\Tim\.nuget\packages\gitversion.msbuild\5.6.3\tools\net48/gitversion.exe C:\Users\Tim\AppData\Local\NCrunch\12004\2\TA.Ascom.ReactiveCommunications -output file -outputfile obj\/gitversion.json" exited with code 1.
</pre>

## Expected Behavior
Obviously, there should not be a build error

## Steps to Reproduce

1. Add NuGet packae GitVersion.MSBuild-5.3.6 to a NETStandard 2.1 class library project.
2. Build the project
3. Observe the build error.

## Context
Showstopper! I can no longer build my code.

## Your Environment
Windows 10
VS2019 Enterprise
.NETStandard 2.1 class library project
GitVersion.MSBuild nuget package v5.6.3

Here is a link to the minimal solution required to reproduce the issue (it is really just File/New Project)
https://github.com/NameOfTheDragon/TA.GitVersionIssue

**Comment by NameOfTheDragon** [comment]
Sorry guys, false alarm. Something else must've been going on as I can't reproduce it now. You still might want to look at that mangled path though ;-)

**Comment by asbjornu** [comment]
There may be hard coded instances of `\` or `/` in our codebase which should be replaced with calls to `Path.Combine()`. Pull requests are welcome! 😃 🙏🏼

**Comment by arturcic** [comment]
@asbjornu this one is done in msbuild props https://github.com/GitTools/GitVersion/blob/782e420dba9991ad95e4bc464ef017a3bc5ca628/src/GitVersion.MsBuild/msbuild/tools/GitVersion.MsBuild.props#L5

**Comment by arturcic** [comment]
maybe we do not need the /gitversion.json, as the BaseIntermediateOutputPath has already the correct `\` or `/`

**Comment by asbjornu** [comment]
Ah, we should replace that with `$([System.IO.Path]::Combine($(Path1),$(Path2)))` if possible.

**Comment by asbjornu** [comment]
> maybe we need to remove the`/`, as the BaseIntermediateOutputPath has already the correct `\` or `/`

That's a good point and may highlight why Microsoft designed all paths to deliberately end with slashes in MSBuild. I've always despised that decision, but alleviating the need to do `Path.Combine` is a neat feature I haven't realized before.

**Comment by bddckr** [comment]
I believe just dropping the slash is exactly what the MSBuild convention is, considering this property is documented to end with the slash [here](https://docs.microsoft.com/visualstudio/msbuild/common-msbuild-project-properties).

If you want to guard against users who override this property but forget to add the slash at the end I suggest `$([MSBuild]::EnsureTrailingSlash($(BaseIntermediateOutputPath))`, which uses one of the [property functions](https://docs.microsoft.com/visualstudio/msbuild/property-functions). I've personally ran into a bunch of other targets that don't handle missing slashes for properties that represent directory paths, so I still prefer just requiring users to get it right.

**Comment by arturcic** [comment]
@bddckr do you mind sending a PR?

**Comment by bddckr** [comment]
👍 However, I'll check out the provided repro later today or tomorrow first - I've not been able to reproduce in my own projects at all 🤔 (I already had the slash at the end for this property, but even removing it doesn't change anything - it keeps working for me no matter what.)

**Comment by julianbartel** [comment]
Hi all,
I ran into the same issue, but for me, it was not the malformed `GitVersionOutputFile` property but the `GitVersionFileExe` property. 
https://github.com/GitTools/GitVersion/blob/9eab74ae93b0d1f5575745087055c5ef4afb8400/src/GitVersion.MsBuild/msbuild/tools/GitVersion.MsBuild.props#L26
The path should be quoted, otherwise the call fails when the package is cached in a path containing whitespaces (on Windows, this is usually %userprofile%\.nuget\packages - I my case, having a space in my user name).

**Comment by SeppPenner** [comment]
I have this issue as well. My project under https://github.com/SeppPenner/SerilogSinkForPostgreSQL (With multiple target frameworks) throws the error: `Der Befehl "C:\Users\User\.nuget\packages\gitversion.msbuild\5.6.3\tools\net48/gitversion.exe C:\Users\User\Github\C# und VB\SerilogSinkForPostgreSQL\src\SerilogSinksPostgreSQL -output file -outputfile obj\/gitversion.json" wurde mit dem Code 1 beendet.`

@arturcic I will try your change from https://github.com/arturcic/GitVersion/commit/353837a5a55c6e64c1f0d99bb322778a3eb4e99b and see if this works for me.

**Comment by SeppPenner** [comment]
Ok, the workaround doesn't solve my issue.

**Comment by thoemmi** [comment]
Is there any known workaround? I've tried adding `<GitVersionOutputFile>$(BaseIntermediateOutputPath)gitversion.json</GitVersionOutputFile>` in my _Directory.Build.props_, but it didn't help.

**Comment by asbjornu** [comment]
The best "workaround" is to provide a pull request that fixes this in GitVersion.

**Comment by SeppPenner** [comment]
> The best "workaround" is to provide a pull request that fixes this in GitVersion.

If I knew where the problem was, there would have been one from my side :D
