### ISSUE TITLE
Clarification on generated Mainline version

### ISSUE THREAD

**Issue by kieronlanning** [GitTools/GitVersion#2536]
I'll start off by saying this might be confusion on my part...!

I'm using the Mainline mode with the following branch strategy and configuration, as generated by the CLI wizard:

```
main
   |- dev
```

```
assembly-versioning-scheme: MajorMinorPatch
mode: Mainline
branches: {}
ignore:
  sha: []
merge-message-formats: {}
```

Here the work is done in `dev` and then when a release is ready to go, we merge from `dev` to `main`.

During my local testing I seem to have an inconsistency in the way the version number is generated:

> main -> git tag 1.0.0 (for initial version)
> gitversion generated 1.0.0
> checkout dev, do a commit
> gitversion generated 1.1.0-alpha.1
> checkout main, merge dev
> gitversion generated 1.0.1

I'd have expected `main` to now be at 1.1.0 as that's what `dev` was generating in alpha form?

Lastly, as this is for nuget packages, is there a way to change the `alpha` tag to a `prerelease` tag and then if I need to build from either `dev` or a feature branch I can generate the correct version with prerelease versioning?

**Comment by asbjornu** [comment]
When you merged `dev` into `main`, did you write `+semver: minor` in the commit message? Read more on [Mainline mode](https://gitversion.net/docs/reference/versioning-modes/mainline-development).

**Comment by kieronlanning** [comment]
@asbjornu No, I didn't...

**Comment by kieronlanning** [comment]
@asbjornu Are you saying I _should_ have set a commit message to `+semver: minor` in order to bump `main` to 1.1.0 like the `dev` branch was?

**Comment by asbjornu** [comment]
Yes.

**Comment by kieronlanning** [comment]
@asbjornu Gotcha. Is there any way to automate that through detection of the branch change?

**Comment by asbjornu** [comment]
Not with GitVersion, no. But with GitHub Actions, anything is possible.

**Comment by kieronlanning** [comment]
@asbjornu is there a mode that you'd recommend that replicates that simplified process?

**Comment by asbjornu** [comment]
If you always want to increment minor, you can set [`increment`](https://gitversion.net/docs/configuration#increment) to `minor` in `GitVersion.yml`.
