### ISSUE TITLE
[Improvement]

### ISSUE THREAD

**Issue by curicm** [GitTools/GitVersion#2537]
**Is your improvement request related to a problem? Please describe.**
Need GitVersionTask5.6.3 because of issue #2470 but the latest version on nuget.org is 5.5.1

## Detailed Description
Cannot get latest releases via nuget.org

## Context
On GitLab CI/CD the GitVersionTask is breaking the publish installer pipeline due to issue #2471

## Possible Implementation
Make latest releases available on nuget.org

**Comment by arturcic** [comment]
GitVersionTask is obsolete, please switch to GitVersion.MsBuild
