### ISSUE TITLE
[Bug] "UpdateAssemblyInfo" task was not given a value for the required parameter "Language"

### ISSUE THREAD

**Issue by curicm** [GitTools/GitVersion#2539]
**Describe the bug**
After switching from GitVersionTask to GitVersion.MSbuild, error occurs in UpdateAssemblyInfo.

## Expected Behavior
Build should succeed as is did using GitVersionTask on the same project. Nothing was changed on the project file.

## Actual Behavior
msbuild igm.Installer.wixproj /p:configuration=release
Microsoft (R) Build Engine version 16.8.3+39993bd9d for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 14/01/2021 07:42:18.
Project "igm.Installer.wixproj" on node 1 (default targets).
RunGitVersion:
  C:\dev\AutoStore\asigm\asigm\packages\GitVersion.MsBuild.5.6.3\tools\net48/gitversion.exe igm.Installer -outp
  ut file -outputfile /gitversion.json
C:\dev\AutoStore\asigm\asigm\packages\GitVersion.MsBuild.5.6.3\tools\GitVersion.MsBuild.targets(134,9): error MSB4044: The "UpdateAssemb
lyInfo" task was not given a value for the required parameter "Language". [C:\dev\igm\igm.Installer\igm.Installer.wixpro
j]
Done Building Project "C:\dev\igm\igm.Installer.wixproj" (default targets) -- FAILED.
Build Failed

## Steps to Reproduce

clone https://github.com/curicm/GitVersionWixIssue
run:
msbuild WixInstallerTest.wixproj
error as described above occurs
exclude GitVersion.MSBuild and run msbuild WixInstallerTest.wixproj
error does not occur

## Context
msbuild fails building a Wix installer project

## Your Environment
Microsoft (R) Build Engine version 16.8.3+39993bd9d for .NET Framework

- Version Used:
- Operating System: Windows 10

**Comment by arturcic** [comment]
It was fixed in #2529
