### ISSUE TITLE
[Bug] GitVersion.MSBuild fails when project path contains spaces

### ISSUE THREAD

**Issue by AkisKK** [GitTools/GitVersion#2540]
When GitVersion.MSBuild is installed in a project path which contains spaces, it fails with an error message:

```
C:\.nuget\packages\gitversion.msbuild\5.6.3\tools\net48/gitversion.exe C:\Program Files (x86)\Jenkins\workspace\satellite-communication-endpoint\argoswindows\ProjectVeil\Veil.Comms -output file -outputfile obj\/gitversion.json
  Cannot find the .git directory
C:\.nuget\packages\gitversion.msbuild\5.6.3\tools\GitVersion.MsBuild.targets(9,9): error MSB3073: The command "C:\.nuget\packages\gitversion.msbuild\5.6.3\tools\net48/gitversion.exe C:\Program Files (x86)\Jenkins\workspace\satellite-communication-endpoint\argoswindows\ProjectVeil\Veil.Comms -output file -outputfile obj\/gitversion.json" exited with code 1. [C:\Program Files (x86)\Jenkins\workspace\satellite-communication-endpoint\argoswindows\ProjectVeil\Veil.Comms\Veil.Comms.csproj]
```
Could also be related to #2534.

## Expected Behavior
It shouldn't fail.

## Actual Behavior
The build fails when the *RunGitVersion* task runs.

## Possible Fix
Path references inside the `GitVersion.MsBuild.targets` file should be enclosed in `&quot;`.

## Steps to Reproduce
Use GitVersion.MSBuild in a project under a path whihch contains spaces and attempt to build.

## Context
Build projects on a default Windows installation of Jenkins CI. (under C:\Program Files (x86)\Jenkins)

## Your Environment
- Version Used: GitVersion.MSBuild 5.6.3
- Operating System and version (Windows 10, Ubuntu 18.04): Windows 10
- Link to your project:
- Link to your CI build (if appropriate):

**Comment by lennoncork** [comment]
I came across this with "5.6.11". Removing the space from the path worked. I generally also move the output location using "Directory.Build.props" like this. 

```
<PropertyGroup>
    <SolutionOutputPath>$(MSBuildThisFileDirectory).output</SolutionOutputPath>
    <ProjectOutputPath>$(SolutionOutputPath)\$(MSBuildProjectName)</ProjectOutputPath>
    <BaseOutputPath>$(ProjectOutputPath)\bin</BaseOutputPath>
    <BaseIntermediateOutputPath>$(ProjectOutputPath)\obj</BaseIntermediateOutputPath>
</PropertyGroup>
```
