### ISSUE TITLE
[Bug] Msbuild generates dependencies even if I had specified PrivateAssets

### ISSUE THREAD

**Issue by Cyl18** [GitTools/GitVersion#2549]
**Describe the bug**
![image](https://user-images.githubusercontent.com/14993992/104819192-e5c91080-5866-11eb-8007-05c5cb92aea8.png)

First, I build my solution with: `dotnet publish WFBot -c "Release" -o Publish`  
Then, I execute with `dotnet Publish/WFBot.dll`  
It shows this error: 
![image](https://user-images.githubusercontent.com/14993992/104819257-45bfb700-5867-11eb-8b91-467ea91c2aa6.png)

deps.json:
![image](https://user-images.githubusercontent.com/14993992/104819303-8b7c7f80-5867-11eb-80bd-068103d82509.png)

you can reproduce it by using this project: 
https://github.com/TRKS-Team/WFBot/tree/gitversion-bug-report

## My Environment

- Version Used: GitVersion.MsBuild 5.6.3
- Operating System and version (Windows 10, Ubuntu 18.04): Windows 10
- Link to your project: https://github.com/TRKS-Team/WFBot/tree/gitversion-bug-report
- Link to your CI build (if appropriate):

**Comment by thoemmi** [comment]
I experience a similar issue with GitVersion.MsBuild, 5.6.4. In my case, dotnet complains about missing _System.Text.Encoding.CodePages_:

> Error:
>  An assembly specified in the application dependencies manifest (***redacted***.deps.json) was not found:
>    package: 'System.Text.Encoding.CodePages', version: '4.0.1'
>    path: 'runtimes/win/lib/netstandard1.3/System.Text.Encoding.CodePages.dll'

**Comment by thoemmi** [comment]
Follow-up: After I removed GitVersion.MsBuild and all its dependencies from the .deps.json file, my application was able to start again.

**Comment by acgritt** [comment]
I am running into an issue that I think is caused/related to this as well. We are using the WebApplicationFactory to do testing against our API project and after upgrading from GitVersionTask to GitVersion.MsBuild I am not getting errors when running the tests because it can't find the deps.json file for the API project.

**Comment by bddckr** [comment]
This works for me:
```xml
<PackageReference Install="GitVersion.MsBuild" Version="5.6.4">
  <PrivateAssets>all</PrivateAssets>
  <IncludeAssets>build; native; contentfiles; analyzers</IncludeAssets>
</PackageReference>
```

You might be able to add `buildtransitive` to `IncludeAssets`, too, but I didn't test that. See #2576.

**Comment by Cyl18** [comment]
> This works for me:
> 
> ```
> <PackageReference Install="GitVersion.MsBuild" Version="5.6.4">
>   <PrivateAssets>all</PrivateAssets>
>   <IncludeAssets>build; native; contentfiles; analyzers</IncludeAssets>
> </PackageReference>
> ```
> 
> You might be able to add `buildtransitive` to `IncludeAssets`, too, but I didn't test that. See #2576.

@bddckr thanks!
