### ISSUE TITLE
GitFlow merge release back to develop (and not master) > where to put tags?

### ISSUE THREAD

**Issue by NickSevens** [GitTools/GitVersion#2556]
The GitFlow method specifies that after a release, I should merge the `release` branch back into `develop` (and not `master` > `develop`).

However, since the tag (e.g. `1.1.0`) is on the `master` branch, the `develop` branch does not recognize this tag as a "previous version".

How do I configure so that this scenario _is_ supported?

**Comment by asbjornu** [comment]
I think the following test proves that the tag `1.2.0` on `master` indeed applies to `develop`.

https://github.com/GitTools/GitVersion/blob/519916b13047f32e6b336da644a6e6ec1659ee97/src/GitVersionCore.Tests/IntegrationTests/DevelopScenarios.cs#L200-L237

**Comment by NickSevens** [comment]
Thanks for the info @asbjornu 

I think it indeed _should_ work as expected, but the fact that I'm using PRs in Azure DevOps to merge Release > Master seems to complicate things ... :/

Any recommendation towards that?

**Comment by asbjornu** [comment]
Are you doing fast-forward merge or merge-commit?

**Comment by NickSevens** [comment]
I'm merging with no ff, and yes, release gets deleted afterwards.
The CI is triggered on commit as well, so I can't really tag manually in between either (I think)

**Comment by asbjornu** [comment]
The tag needs to be applied and pushed before the build is performed, or else GitVersion won't have the tag to perform its calculations from.

**Comment by NickSevens** [comment]
So what's the recommended flow for this process then?
Tag the latest commit in the release branch, before completing the CR?

Thanks for the help btw, @asbjornu

**Comment by asbjornu** [comment]
No, tag the merge-commit, push the tag, then push the commit itself.

**Comment by NickSevens** [comment]
But, since the merge happens on the Azure DevOps side, and master is protected with a CI policy, you can't manually push (the merge-commit) to the remote - which means I can't tag the merge before running the CI job?

Sorry if I'm asking stupid questions ... I'm not _that_ experienced with all of this yet

**Comment by asbjornu** [comment]
Is it possible for you to set up AzDO such that only tagged builds on `master` are built?

**Comment by NickSevens** [comment]
@asbjornu I can indeed check on the Build source if it's coming from a tag. That does help, thanks!

**Comment by asbjornu** [comment]
Excellent! 👍🏼

**Comment by NickSevens** [comment]
@asbjornu followup question, if I may:
when I complete the PR, and _dont_ delete the `release/v1.2.0` branch, and then add a tag `v1.2.0`, the version is resolved to `1.3.0`.
Probably because it finds a release branch with an existing v1.2.0, which causes the build to increment, regardless of the tag specified?

**Comment by asbjornu** [comment]
Depending on which branch you're on, the existence of a release branch may bump the version, yes.
