### ISSUE TITLE
[Bug] Version number is incremented when you create new branch - Mainline mode

### ISSUE THREAD

**Issue by leonids2005** [GitTools/GitVersion#2562]
**Describe the bug**
I am not sure this is a bug and maybe the wrong configuration on my side.

I am trying to use Gitversion in mainline mode and getversion increment a patch number when I create a new branch. So let's say my current master version is 1.0.1 so when I create a new branch from the master - the version in this new branch is 1.0.2. Technically this is the same version really - even the commit is the same.

## Expected Behavior

Mainline mode

master branch version - 1.0.1
created a new branch from master - version should still be 1.0.1 because it is technically the same version - even commit is the same.

## Actual Behavior

master branch version - 1.0.1
created a new branch from master - version 1.0.2

## Your Environment

- Version Used:
- Operating System and version (Windows 10, Ubuntu 18.04):
- Link to your project:
- Link to your CI build (if appropriate):

**Comment by FISHMANPET** [comment]
I believe this is the expected design.  The idea behind mainline mode is that you only merge into main what you're releasing, and the first step to changing your code is to create a new branch which will eventually be merged into main and increment the release.  So that new branch becomes a pre-release of the next version.

**Comment by asbjornu** [comment]
Indeed, @FISHMANPET.

**Comment by leonids2005** [comment]
I understand but I am not sure I agree here. when you create a pre-release version and then do not change anything in the code why do you need to increment the version number?  it is technically the same version - referring to the same commit.  
to illustrate an example - in master we have 1.0.1, created pre-release branch - it is now 1.0.2.  Did verification, everything works fine, no code changes required - so we deploy it to production as 1.0.2. nothing is changed in master at that stage (so nothing to merge back to the master) so we really now need to "artificially" bump the master version to 1.0.2 without any code changes.

if you change anything during your pre-release process  (in a  new branch) then yes, you will get a new version number. So for me, this is a flaw here. Anyway, my question is - is anything could be done here to change the behavior.

**Comment by asbjornu** [comment]
The existence of the branch is enough to have GitVersion increment the version number. That's what GitVersion does. If that doesn't suit your needs, I don't think GitVersion is what you want.

**Comment by leonids2005** [comment]
GitVersion does a good job for us - this is just an issue we faced and I am just raising. for me this is like a feature request. I will try using  increment: none

**Comment by leonids2005** [comment]
It turns out that I am using  'increment: None'  already.  So am I right that in this case version number should not be incremented?

**Comment by asbjornu** [comment]
How does your `GitVersion.yml` look like, @leonids2005?
