### ISSUE TITLE
[Bug] GitVersion.MsBuild produces extra files

### ISSUE THREAD

**Issue by kroppt** [GitTools/GitVersion#2565]
**Describe the bug**
GitVersion.MsBuild produces files called `gitversion.json` in each project directory. Thus, a .gitignore entry is in order for those using this, which is a little annoying. GitVersionTask did not have this issue.

For context, I am using Paket, so I do a `paket restore` before building with `msbuild`.

## Expected Behavior
Run a build and have no unexpected side-effects.

## Actual Behavior
Ran a build and got several files showing up as changes in git.

## Context

I am wanting to upgrade from the deprecated `GitVersionTask` to the more up-to-date `GitVersion.MsBuild` so that the version of it can keep up with the executable distribution, to help isolate build issues.

## Your Environment

OS: Windows 10
Project Target: net462
Visual Studio Version: 2019 16.8.4
Paket Version: 5.257.0
GitVersion.MsBuild Version: 5.6.4

**Comment by bddckr** [comment]
Starting in 5.6.2 the file has been moved to the intermediate output folder. That output folder is used by projects for intermediate build artifacts and as such should always be ignored in your VCS.
https://github.com/GitTools/GitVersion/blob/72ee9eaaac5b30a3bef36f82444696fdc80a88c1/src/GitVersion.MsBuild/msbuild/tools/GitVersion.MsBuild.props#L5

Are you sure you're running 5.6.4? Alternatively perhaps you've previously ran a version <= 5.6.2 and thus all you're seeing are the files left over from those older versions? Try deleting the files in your project folder, restart VS and do a new rebuild. 🤞

**Comment by kroppt** [comment]
I created a new project and it is replicable. Attached:
[TestGitVersionBug.zip](https://github.com/GitTools/GitVersion/files/5880697/TestGitVersionBug.zip)

**Comment by chrbkr** [comment]
Same here: gitversion.json is produced in the project directory.
I'm using GitVersion.MsBuild 5.6.4, and I never had an older version installed, since I just switched over from GitVersionTask.

Maybe it's this line?

https://github.com/GitTools/GitVersion/blob/8937c25e2a9c880193264b4627813f465abc4c65/src/GitVersion.MsBuild/msbuild/tools/GitVersion.MsBuild.targets#L9

**Comment by arturcic** [comment]
It's not a bug, it's by design and it should go to the `obj` folder

**Comment by kroppt** [comment]
The bug is that it's not going to the `obj` folder.

**Comment by kroppt** [comment]
The package works fine if you use PackageReference. But using Paket and packages.config, the issue appears.

**Comment by chrbkr** [comment]
@arturcic Can you please reopen this issue? It IS a bug, as the json file does not go to the obj folder, but to the project folder.

**Comment by arturcic** [comment]
where is your `BaseIntermediateOutputPath` point to?

**Comment by chrbkr** [comment]
`BaseIntermediateOutputPath` is pointing to /obj. But what about the line I posted? `GitVersion_ToolArgments` is `-output file -outputfile gitversion.json`, putting gitversion.json in the current working directory, which apparently is the project folder.

**Comment by arturcic** [comment]
actually that is https://github.com/GitTools/GitVersion/blob/72ee9eaaac5b30a3bef36f82444696fdc80a88c1/src/GitVersion.MsBuild/msbuild/tools/GitVersion.MsBuild.props#L15 which in turn is https://github.com/GitTools/GitVersion/blob/72ee9eaaac5b30a3bef36f82444696fdc80a88c1/src/GitVersion.MsBuild/msbuild/tools/GitVersion.MsBuild.props#L5

**Comment by chrbkr** [comment]
This is weird. Apparently, at the moment GitVersionOutputFile is defined, BaseIntermediateOutputPath is empty. Is it possible that this is handled differently in PackageReference and package.config?

**Comment by arturcic** [comment]
Good question, but unfortunately I do not have time to check that.

**Comment by GillesBrice** [comment]
I had the same problem, I change the order of the GitVersion.MsBuild.props's import in my csproj.

So I put the line :
`<Import Project="packages\GitVersion.MsBuild.5.6.6\build\GitVersion.MsBuild.props" Condition="Exists('packages\GitVersion.MsBuild.5.6.6\build\GitVersion.MsBuild.props')" />`
After the line :
`<Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" />`

Now, the gitversion.json is produced in the obj folder for my project.

**Comment by chrbkr** [comment]
> I had the same problem, I change the order of the GitVersion.MsBuild.props's import in my csproj.

Doesn't work for me :/ I already had the import for GitVersion.MsBuild.targets as the last entry. The import for GitVersion.MsBuild.props is missing entirely (I guess it is imported automatically as a dependency, as its presence is checked in PrepareForBuild). Adding it manually doesn't fix the problem either.

**Comment by arturcic** [comment]
But how can we control the position where nuget will include the import statement when restoring the package

**Comment by chrbkr** [comment]
No idea... There must be a difference between how the props and the targets file is imported.

**Comment by chrbkr** [comment]
So apparently it is the default behavior to put props at the top and targets at the bottom: https://docs.microsoft.com/en-us/visualstudio/msbuild/how-to-use-project-sdk?view=vs-2019

I guess the correct way to do this is to just put these properties in the targets file, as described here: https://docs.microsoft.com/en-us/visualstudio/msbuild/customize-your-build?view=vs-2019#choose-between-adding-properties-to-a-props-or-targets-file

**Comment by arturcic** [comment]
@chrbkr can you test this locally and see if that works? If so, can you also send a PR?

**Comment by chrbkr** [comment]
I can try.
