### ISSUE TITLE
Bug in AssemblyInfo FileUpdate

### ISSUE THREAD

**Issue by HenningBredenkoetter** [GitTools/GitVersion#257]
Patching of AssemblyInformationalVersion works just once, because 
 `"InformationalVersion":"1.2.3-unstable.4+5.Branch.feature1.Sha.commitSha"`
does not match Regex 
 `\d+.\d+.\d+(.\d+|\*)?`

Why not just Match 
 `.RegexReplace(@"AssemblyInformationalVersion\(.*\)"`

Would be nice if you could fix this?

> File: AssemblyInfoFileUpdate.cs, Line 39
> `.RegexReplace(@"AssemblyInformationalVersion\(""\d+.\d+.\d+(.\d+|\*)?""\)", string.Format("AssemblyInformationalVersion(\"{0}\")", assemblyInfoVersion))`

**Comment by JakeGinnivan** [comment]
Did you want to submit a pull request to the 3.0 branch so this can be fixed in the 3.0 release?

**Comment by JakeGinnivan** [comment]
This looks like it has been fixed at some point. Closing issue out
