### ISSUE TITLE
[Bug] Exception references to documentation URL resolves to 404 page when copied exactly

### ISSUE THREAD

**Issue by davislabs** [GitTools/GitVersion#2571]
**Describe the bug**
When provided an error message with a link, the link as provided returns a 404 page.  The problem is that the extra "/" prevents the page from loading in current Chrome browser.

GitVersion.Configuration.ConfigurationException: Branch configuration 'dev(elop)?(ment)?$' is missing required configuration 'regex'
See https://gitversion.net/docs/configuration/ for more info

## Expected Behavior
The link would open the page as described

## Actual Behavior
Receive a 404 page and had to spend a minute or two guessing at why there was a 404 page.

## Possible Fix
Drop the "/" from the URL link.

## Context
I was just wanting to review the reference material.

## Your Environment
Running on Windows, local repository.

- Version Used: 5.6.4+Branch.master.Sha.519916b13047f32e6b336da644a6e6ec1659ee97
- Operating System and version (Windows 10, Ubuntu 18.04): Windows 10

**Comment by asbjornu** [comment]
Thanks for the bug report. A PR fixing the problem is welcome. 🙏🏼
