### ISSUE TITLE
[Bug] GitVersion.MsBuild should not have 'runtime' listed in the IncludeAssets property

### ISSUE THREAD

**Issue by odalet** [GitTools/GitVersion#2576]
**Describe the bug**
When adding a nuget reference to GitVersion.MsBuild from Visual Studio in a Sdk-style project, we end up with this declaration:

```xml
<PackageReference Include="GitVersion.MsBuild" Version="5.6.4">
  <PrivateAssets>all</PrivateAssets>
  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
</PackageReference>
```

## Expected Behavior

The package should be restored like below (and maybe other assets need not be included...):

```xml
<PackageReference Include="GitVersion.MsBuild" Version="5.6.4">
  <PrivateAssets>all</PrivateAssets>
  <IncludeAssets>build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
</PackageReference>
```

## Actual Behavior

Having 'runtime' part of the included assets has some implications:
* trough its dependency tree, GitVersion.MsBuild depends on `System.Drawing.Common`:
![image](https://user-images.githubusercontent.com/79333/106462213-11b6d980-6496-11eb-92e3-ad995b6a290f.png)

* This dependency (and others) end up in the build output **and** are listed in the `deps.json` file.
* This is already not that clean, but then I have other issues when trying to run the application in docker:
* I publish the application as framework-dependent and multi-platform  and then build my Docker image
* The application inside the Docker does not work and tells me it can't find `System.Drawing.Common`:
```sh
Step 12/14 : RUN ./GitVersionSysDrawingIssue
 ---> Running in 1f86a3a65590
Error:
  An assembly specified in the application dependencies manifest (GitVersionSysDrawingIssue.deps.json) was not found:
    package: 'System.Drawing.Common', version: '4.7.0'
    path: 'runtimes/unix/lib/netcoreapp3.0/System.Drawing.Common.dll'
The command '/bin/sh -c ./GitVersionSysDrawingIssue' returned a non-zero code: 140
```

If the package were to be restored like above (without the 'runtime' in the included assets), then this issue disappears (as there is not any more a dependency on `System.Drawing.Common.dll`)

## Steps to Reproduce

This behavior can be reproduced with this repository: <https://github.com/odalet/GitVersionSysDrawingIssue>
* Clone it on a Linux (or WSL) machine:
```sh
git clone https://github.com/odalet/GitVersionSysDrawingIssue.git
cd GitVersionSysDrawingIssue
```
* Build/publish: 
```sh
dotnet publish GitVersionSysDrawingIssue/GitVersionSysDrawingIssue.csproj --configuration Release -o out/
```
* Build the docker image
```sh
docker build .
```
The build shoudl fail at step 12 when attempting to run the app in the container.

Then,

* Edit `GitVersionSysDrawingIssue.csproj` and remove 'runtime' from `<IncludeAssets>` and repeat publish then docker build.

## Context

Trying to run an app that uses GitVersion.MsBuild in a linux Docker.

## Your Environment

* .NET Core 3.1 app
* Visual Studio 2019 v16.8.3
* Windows 10 20H2, Debian 10 WSL (to build the docker image), Docker image: mcr.microsoft.com/dotnet/runtime:3.1
* Repro Repository:< https://github.com/odalet/GitVersionSysDrawingIssue>

**Comment by arturcic** [comment]
@odalet if you find a solution a PR is welcomed

**Comment by odalet** [comment]
Hehe! Unfortunately I don't have a solution. For now, I remove 'runtime' by hand in my csproj... I may ask if this is even possible on nuget repository.

Btw, I conducted other experiments and:
* Although, the clean way would be not to have these dependencies,
* I managed to have my docker images build by tweaking a bit my publish command:

```sh
dotnet publish GitVersionSysDrawingIssue/GitVersionSysDrawingIssue.csproj --configuration Release -r linux-x64 -o out/
```

This works, but pollutes my docker with a whole lot of System.* and Microsoft.* DLLs because the app is not considered any more framework-dependent.

Better:

```sh
dotnet publish GitVersionSysDrawingIssue/GitVersionSysDrawingIssue.csproj --configuration Release -r linux-x64 --self-contained false -o out/
```

This one does work too *and* is still considered framework-dependent (no more useless dependencies, not even System.Drawing.Common...). I suppose this is the correct incantation.

But these are only workarounds.
works as well

**Comment by odalet** [comment]
Here is my message in a bottle: <https://github.com/NuGet/Home/issues/10512>

**Comment by odalet** [comment]
Hi, although this is not solved per se, fixing #2642 had the positive effect of thread not being an issue anymore. By reflecting on this. I think that what I described here was in fact a work around for #2642 (removing `runtime` prevented the `Microsoft.Build.Utilities.Core` to be deployed. But now that this dependency is private upstream, having `runtime` in the included assets is not an issue any more.

So I suppose this can be closed now!

**Comment by arturcic** [comment]
@odalet thanks for the information, closing

**Comment by odalet** [comment]
Btw, concerning what I asked in [NuGet/Home#10512](https://github.com/NuGet/Home/issues/10512), it's just not supported.
