### ISSUE TITLE
[Bug] Typo in GitVersion.MsBuild.targets

### ISSUE THREAD

**Issue by MarkusHorstmann** [GitTools/GitVersion#2582]
`
<DefineConstants Condition=" '$(GitVersion_PreReleaseLabelWithDash)' != '' ">GitVersion_PreReleaseLabelWithDash=$(GitVersion_PreReleaseLabeWithDashl);$(DefineConstants)</DefineConstants>
`
should likely be 
`
<DefineConstants Condition=" '$(GitVersion_PreReleaseLabelWithDash)' != '' ">GitVersion_PreReleaseLabelWithDash=$(GitVersion_PreReleaseLabelWithDash);$(DefineConstants)</DefineConstants>
`

Noticed doing other changes, but don't have a way to test this.

## Expected Behavior
Unknown

## Actual Behavior
Unknown

## Possible Fix
See above.
## Steps to Reproduce
Unknown

## Context
Code inspection

**Comment by asbjornu** [comment]
`GitVersion_PreReleaseLabeWithDashl` does not look right indeed. Could you please submit a PR that fixes this? 🙏🏼

**Comment by MarkusHorstmann** [comment]
Happy to include it in my current PR, or do you prefer separate PRs for different fixes?

**Comment by asbjornu** [comment]
Since your #2581 does not deal with the MSBuild task directly, fixing the typo in a separate PR would be preferable. 🙏🏼

**Comment by MarkusHorstmann** [comment]
Ok, I'll revert it there and kick off a separate PR.
