### ISSUE TITLE
[Feature] GitVersion.Tool installation not documented

### ISSUE THREAD

**Issue by mpoettgen** [GitTools/GitVersion#2584]
## Detailed Description

The documentation at https://gitversion.net/docs/usage/command-line doesn't mention the option to install GitVersion via:

```
dotnet tool install -g GitVersion.Tool
```

## Context

Even though GitVersion.Tool is mentioned in the README.md it is not listed as an install option on the page referenced above. This is confusing as it seams to be the easiest method to install GitVersion as it doesn't require Chocolatey, Homebrew or any other package manager for installation. At least for .NET (5+) and .NET Core projects the `dotnet` CLI is already present.

## Possible Implementation

Mention how to install GitVersion as a global tool.

**Comment by arturcic** [comment]
@mpoettgen would you mind to send us a PR to fix this?

**Comment by mpoettgen** [comment]
Can do.

**Comment by mpoettgen** [comment]
@arturcic like that? Let me know, if you want more or less.
