### ISSUE TITLE
[Bug] GitVersion.MSBuild `dotnet pack` fails under Linux

### ISSUE THREAD

**Issue by NameOfTheDragon** [GitTools/GitVersion#2591]
**Describe the bug**
My solution builds correctly and sets the TeamCity build number with the correct SemVer. It runs and passes all the unit tests.
Then it fails when running `dotnet pack` with the following build log output:

```lang=log
13:53:16]	     1>/root/.nuget/packages/gitversion.msbuild/5.6.6/tools/GitVersion.MsBuild.targets(110,9): error : ArgumentException: Unknown language detected: 'en_US:en'
[13:53:16]	/root/.nuget/packages/gitversion.msbuild/5.6.6/tools/GitVersion.MsBuild.targets(110,9): error :    at GitVersion.MsBuild.FileHelper.GetFileExtension(String language) in D:\a\GitVersion\GitVersion\src\GitVersion.MsBuild\Helpers\FileHelper.cs:line 56
[13:53:16]	/root/.nuget/packages/gitversion.msbuild/5.6.6/tools/GitVersion.MsBuild.targets(110,9): error :    at GitVersion.MsBuild.FileHelper.GetFileWriteInfo(String intermediateOutputPath, String language, String projectFile, String outputFileName) in D:\a\GitVersion\GitVersion\src\GitVersion.MsBuild\Helpers\FileHelper.cs:line 143
[13:53:16]	/root/.nuget/packages/gitversion.msbuild/5.6.6/tools/GitVersion.MsBuild.targets(110,9): error :    at GitVersion.MsBuild.GitVersionTaskExecutor.GenerateGitVersionInformation(GenerateGitVersionInformation task) in D:\a\GitVersion\GitVersion\src\GitVersion.MsBuild\GitVersionTaskExecutor.cs:line 57
[13:53:16]	/root/.nuget/packages/gitversion.msbuild/5.6.6/tools/GitVersion.MsBuild.targets(110,9): error :    at GitVersion.MsBuild.GitVersionTasks.<>c__DisplayClass2_0.<GenerateGitVersionInformation>b__0(IGitVersionTaskExecutor executor) in D:\a\GitVersion\GitVersion\src\GitVersion.MsBuild\GitVersionTasks.cs:line 17
[13:53:16]	/root/.nuget/packages/gitversion.msbuild/5.6.6/tools/GitVersion.MsBuild.targets(110,9): error :    at GitVersion.MsBuild.GitVersionTasks.ExecuteGitVersionTask[T](T task, Action`1 action) in D:\a\GitVersion\GitVersion\src\GitVersion.MsBuild\GitVersionTasks.cs:line 30
[13:53:16]	/root/.nuget/packages/gitversion.msbuild/5.6.6/tools/GitVersion.MsBuild.targets(110,9): error :
[13:53:16]	     1>Done Building Project "/opt/buildagent/work/8f12cde64aeec7e3/TA.Ascom.ReactiveCommunications/TA.Ascom.ReactiveCommunications.csproj" (pack target(s)) -- FAILED.
[13:53:16]
```

(full build log at http://teamcity.tigra-astronomy.com:8111/viewLog.html?buildId=9842&buildTypeId=TigraOss_TaReactiveCommunications&tab=buildLog&branch_TigraOss=hotfix%2F1.3.2)

## Expected Behavior
I would expect this step to have succeeded since the build step worked successfully and produced the correct SemVer.
I do not understand how I get different results for `dotnet build` and `dotnet pack`.

## Actual Behavior
Some crazy error about an "unknown language". Why does it even require a language?

## Steps to Reproduce

Unfortunately I'm not able to provide a test solution as I don't really understand the failure mechanism.

## Context

It's a showstopper, I'm unable to complete my build. I don't believe there's anything wrong with my solution or build configuration. I'm not aware that GitVersion provides any way for me to pass in a `Language` parameter so this appears to be purely an internal error.

## Your Environment

TeamCity build server
Linux (Ubuntu 20.04) build agent (in a docker container) with GitVersion installed on the agent image.
The solution being built is https://github.com/Tigra-Astronomy/TA.ReactiveCommunications/tree/hotfix/1.3.2
The TeamCity build is http://teamcity.tigra-astronomy.com:8111/viewType.html?buildTypeId=TigraOss_TaReactiveCommunications&branch_TigraOss=hotfix%2F1.3.2&tab=buildTypeStatusDiv

**Comment by arturcic** [comment]
There is a property that sets the `Language` to C#, https://github.com/GitTools/GitVersion/blob/0cfa014e955a2fae864040cf23cdfba9302d77b4/src/GitVersion.MsBuild/msbuild/tools/GitVersion.MsBuild.props#L7, but I assume you have in your project this property set to "en_US:en" that's why it fails.

**Comment by NameOfTheDragon** [comment]
> There is a property that sets the `Language` to C#,
> 
> https://github.com/GitTools/GitVersion/blob/0cfa014e955a2fae864040cf23cdfba9302d77b4/src/GitVersion.MsBuild/msbuild/tools/GitVersion.MsBuild.props#L7
> 
> , but I assume you have in your project this property set to "en_US:en" that's why it fails.

No, I'm not setting it _at all_. I'm using the vanilla 'pack' target. What it looks like to me is that the `en-US:en` value is somehow being picked up from an environment variable when run under Linux. If I open my build agent container with an interactive shell, and look at the environment variables, there's your language value right there:
![image](https://user-images.githubusercontent.com/1268490/107399260-68588f00-6af8-11eb-94ec-14ee95beac81.png)

**Comment by arturcic** [comment]
You have 2 options, either remove/update that environment variable (but that might break something), or you can set the Language as a msbuild property (either in the csproj directly or via commandline)

**Comment by NameOfTheDragon** [comment]
> You have 2 options, either remove/update that environment variable (but that might break something), or you can set the Language as a msbuild property (either in the csproj directly or via commandline)

Those are good suggestions and I'll certainly try them as a workaround and report back. However, please note:

1. This is the `jetbrains/teamcity-agent` image with GitVersion installed on it, so this might be a wider issue than just me. That environment variable seems to be pretty standard under Linux. Perhaps a better name could be used in GitVersion? Something like `ProgrammingLanguage` or something?
2. Why isn't the `dotnet build` command affected? What's different with `dotnet pack`?

**Comment by arturcic** [comment]
> 1. Something like `ProgrammingLanguage` or something

Actually that is not what GitVersion sets. That's the msbuild Property that msbuild sets

**Comment by NameOfTheDragon** [comment]
> You have 2 options, either remove/update that environment variable (but that might break something), or you can set the Language as a msbuild property (either in the csproj directly or via commandline)

Those are good suggestions and I'll certainly try them as a workaround and report back. However, please note:

1. This is the `jetbrains/teamcity-agent` image with GitVersion installed on it, so this might be a wider issue than just me. That environment variable seems to be pretty standard under Linux. Perhaps a better name could be used in GitVersion? Something like `CompilerLanguage` or something?
2. Why isn't the `dotnet build` command affected? What's different with `dotnet pack`?

**Comment by NameOfTheDragon** [comment]
Ok so we have a workaround (and the problem is confirmed). In my TeamCity build step, I added:

![image](https://user-images.githubusercontent.com/1268490/107411929-06535600-6b07-11eb-9df1-8cf2dd088c5d.png)

...and the result...

![image](https://user-images.githubusercontent.com/1268490/107411809-e0c64c80-6b06-11eb-85aa-83159a470053.png)

**Comment by NameOfTheDragon** [comment]
> > 1. Something like `ProgrammingLanguage` or something
> 
> Actually that is not what GitVersion sets. That's the msbuild Property that msbuild sets

I believe that MSBuild promotes environment variables to build properties. So this `LANGUAGE` environment variable (which doesn't usually exist under Windows but does under Linux) will become a build property under Linux. I would imagine that the normal semantics are then applied, i.e. default values are set only if the property doesn't already have a value. So the `en_US:en` value, I think, is getting carried through into the build of the `pack` target. So you have a name collision under Linux between an environment variable and a build property.

I don't understand why the `pack` target is affected differently than the `build` target. Perhaps it's because during a compile operation, the `LANGUAGE` is set explicitly and not during `pack`. The innards of MSBuild and dotnet.exe are a bit beyond what I can afford to delve into, unfortunately. But I think you have here a 'smoking gun' that points to a cross-platform issue.

**Comment by NameOfTheDragon** [comment]
In issue #2595 I have made some suggestions for handling the Language setting differently. The current approach is clearly flawed and in my humble opinion something needs to change. In my opinion, things should work for any valid MSBuild project on any platform/OS and not just for C#, F# and VB projects under Windows.

**Comment by ermshiperete** [comment]
This is a very annoying issue. The `LANGUAGE` environment variables is used by [GNU gettext](https://www.gnu.org/software/gettext/manual/html_node/The-LANGUAGE-variable.html), so it will be set on most Linux systems.

**Comment by ermshiperete** [comment]
MSBuild's `LANGUAGE` gets set in `/usr/share/dotnet/sdk/5.0.103/Microsoft.CSharp.CurrentVersion.targets` (and `Microsoft.VisualBasic.CurrentVersion.targets`). When running the `pack` target, these `*.targets` files don't get imported.

When looking at those files, I notice that in addition to `Language` the property `DefaultLanguageSourceExtension` gets set. So a possible fix would be to include that property in the condition:

```
<Language Condition=" '$(Language)' == '' Or '$(DefaultLanguageSourceExtension)' == ''">C#</Language>
```

**Comment by arturcic** [comment]
@ermshiperete thanks for taking the time to dig in. Can you try locally on your machine this potential fix? If it works can you fill in a PR?

**Comment by ermshiperete** [comment]
> Can you try locally on your machine this potential fix? If it works can you fill in a PR?

Yes, I tried it locally and it works.

**Comment by arturcic** [comment]
Great, then, could you please send us a PR with the fix?

**Comment by ermshiperete** [comment]
> Great, then, could you please send us a PR with the fix?

You're too fast :smile:
