### ISSUE TITLE
[Bug] dotnet tool unable to run in alpine 3.13 container

### ISSUE THREAD

**Issue by Kralizek** [GitTools/GitVersion#2594]
**Describe the bug**
When executing `dotnet gitversion` in a .NET SDK container built using the 5.0-alpine or 5.0-alpine3.13 image, no output is returned. Everything is normal when using the 5.0-alpine3.12 and 5.0.103-alpine3.12 images.

## Expected Behavior
Be able to use gitversion.tool with latest .NET SDK Docker images.

## Actual Behavior
No content is returned

## Possible Fix
Use images based on alpine 3.12.

## Steps to Reproduce
```
> docker run --rm -it mcr.microsoft.com/dotnet/sdk:5.0-alpine3.13
> mkdir project
> cd project
> git clone <repo> .
> dotnet tool install -g gitversion.tool
> dotnet gitversion
> _
```
No output

## Context
I noticed the issue because the builds were failing in CircleCI.

## Your Environment

- Version Used: gitversion.tool (version '5.6.4')
- Operating System and version (Windows 10, Ubuntu 18.04):

```
# cat /etc/os-release
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.13.1
PRETTY_NAME="Alpine Linux v3.13"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://bugs.alpinelinux.org/"
```

- Link to your project: n/a
- Link to your CI build (if appropriate): n/a

**Comment by asbjornu** [comment]
Why can't you use [`gittools/gitversion:5.6.6-alpine.3.12-x64-3.1`](https://hub.docker.com/layers/gittools/gitversion/5.6.6-alpine.3.12-x64-3.1/images/sha256-8bb2d351dcecdf00a5594c3070ed257c91f7968db4357b7a9d54dffdaa7ee631?context=repo) or [`gittools/gitversion:5.6.6-alpine.3.12-x64-5.0`](https://hub.docker.com/layers/gittools/gitversion/5.6.6-alpine.3.12-x64-5.0/images/sha256-e8316198bbb70c1dce671ec6c62e2c6e37762ab6c108d54dc313a91071e3c300?context=repo)?

**Comment by Kralizek** [comment]
Honestly, I didn't try it.

In this step of the CI process I'm computing the version and packing the library. And I got it to work using the image I mentioned above (5.0-alpine3.12).

This issue was opened to make sure you were aware that your tool isn't compatible with 3.13.

**Comment by vadym** [comment]
I have the same issue.

Tried to use gittools/gitversion:5.6.7-alpine.3.12-x64-5.0 but got the error: "Cannot find the .git directory" (GitLab-CI)
and even if I use mcr.microsoft.com/dotnet/sdk:5.0 (which works correctly) dotnet build commands executed in alpine fails with the same reason:

Segmentation fault (core dumped)

/home/build/.nuget/packages/gitversion.msbuild/5.6.6/tools/GitVersion.MsBuild.targets(9,9): error MSB3073: The command "dotnet --roll-forward Major "/home/build/.nuget/packages/gitversion.msbuild/5.6.6/tools/netcoreapp3.1/gitversion.dll" "/builds/ ... SOURCE_PATH" -output file -outputfile obj/gitversion.json" exited with code 139.

Project has been configured to use dotnet 5.0.

**Comment by asbjornu** [comment]
Can you please paste the entire `docker` command you're trying to execute, @vadym?

**Comment by vadym** [comment]
@asbjornu - 1) I do not call docker command directly. 2) GitLab-CI use 'docker-machine' executor and it uses custom 'alpine' docker image to provision build environment. 3) CI call the command 'dotnet build ${NUGET_SOLUTION_NAME} -c Release --no-restore' and app code uses inside of it gitversion.

**Comment by asbjornu** [comment]
How does the "app code" use GitVersion, @vadym? Through the MSBuild Task or otherwise?

**Comment by vadym** [comment]
1) I'm not a developer on this project. 2) I see that reference to GitVersion was 2.1) added into the project .csproj file and 2.2) used on *.cshtml pages.

**Comment by KiLLeRRaT** [comment]
GitVersion.MsBuild is a NuGet reference in one of my projects (PackageReference in csproj).  When I run an image using `FROM mcr.microsoft.com/dotnet/sdk:5.0-alpine3.13 AS build` I also run into trouble.  This is what I get back:

```
#16 3.838 /root/.nuget/packages/gitversion.msbuild/5.6.11/tools/GitVersion.MsBuild.targets(9,9): error MSB3073: The command "dotnet --roll-forward Major "/root/.nuget/packages/gitversion.msbuild/5.6.11/tools/netcoreapp3.1/gitversion.dll" "/src/MyProject" -output file -outputfile obj/gitversion.json" exited with code 139. [/src/MyProject/MyProject.csproj]
```

Any further ideas on this?

**Comment by arturcic** [comment]
I tested with mcr.microsoft.com/dotnet/sdk:7.0-alpine and `dotnet tool install -g gitversion.tool --version 6.0.0-beta.2` and it works,

Closing

**Comment by barrett777** [comment]
I also get this issue when trying to `dotnet build` after upgrading GitVersion.MsBuild from 5.12.0 to 6.0.2

`.nuget\packages\gitversion.msbuild\6.0.2\tools\GitVersion.MsBuild.targets(22,9): error MSB3073: The command "dotnet --roll-forward Major "C:\Users\benb\.nuget\packages\gitversion.msbuild\6.0.2\tools\net8.0-windows\gitversion.dll" "C:\Source\....."  -output file -outputfile "obj\gitversion.json"" exited with code 1. [C:\Source\......csproj]`

Building in Visual Studio 2022 on my local PC works fine

If I go to the Visual Studio Package Manager Console on my local PC and run `dotnet build`, I get the error above

This command works fine with GitVersion.MsBuild 5.12.0

I get the same error when attempting to use `dotnet build` in Azure Devops using their latest Windows 2022 VM:
https://github.com/actions/runner-images/blob/main/images/windows/Windows2022-Readme.md

https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/dotnet-core-cli-v2?view=azure-pipelines#build-a-project

**Comment by tincann** [comment]
> I also get this issue when trying to `dotnet build` after upgrading GitVersion.MsBuild from 5.12.0 to 6.0.2
> 
> `.nuget\packages\gitversion.msbuild\6.0.2\tools\GitVersion.MsBuild.targets(22,9): error MSB3073: The command "dotnet --roll-forward Major "C:\Users\benb\.nuget\packages\gitversion.msbuild\6.0.2\tools\net8.0-windows\gitversion.dll" "C:\Source\....." -output file -outputfile "obj\gitversion.json"" exited with code 1. [C:\Source\......csproj]`
> 
> ```
> Possible reasons for this include:
>   * You misspelled a built-in dotnet command.
>   * You intended to execute a .NET program, but dotnet---roll-forward does not exist.
> Could not execute because the specified command or file was not found.
>   * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.
> ```
> 
> Building in Visual Studio 2022 on my local PC works fine
> 
> If I go to the Visual Studio Package Manager Console on my local PC and run `dotnet build`, I get the error above
> 
> This command works fine with GitVersion.MsBuild 5.12.0
> 
> I get the same error when attempting to use `dotnet build` in Azure Devops using their latest Windows 2022 VM: [actions/runner-images@`main`/images/windows/Windows2022-Readme.md](https://github.com/actions/runner-images/blob/main/images/windows/Windows2022-Readme.md?rgh-link-date=2024-08-16T15%3A33%3A26Z)
> 
> [learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/dotnet-core-cli-v2?view=azure-pipelines#build-a-project](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/dotnet-core-cli-v2?view=azure-pipelines#build-a-project)

We have the exact same issue when trying to upgrade to 6.0.2. We're using .NET 8.0.204 SDK.
