### ISSUE TITLE
[Bug] The 'Documentation', 'Failing test', and 'Improvement request' issue templates lack proper descriptions.

### ISSUE THREAD

**Issue by jwdonahue** [GitTools/GitVersion#2606]
**Describe the bug**
At `Project=>Issues=>New Issue`: https://github.com/GitTools/GitVersion/issues/new/choose
The `Documentation`, `Failing test` and `Improvement request` issue templates lack proper descriptions. They both have the default template descriptions "Describe this issue template's purpose here."

## Expected Behavior
They should each provide sufficient descriptions of their purpose, such that a person attempting to file an issue can determine which template to use.

## Actual Behavior
Useless default description: "Describe this issue template's purpose here."

## Steps to Reproduce

1. Navigate to [https://github.com/GitTools/GitVersion](https://github.com/GitTools/GitVersion)
2. Click on Issues tab.
3. Click on New Issues button.
4. Read issue template descriptions.

## Context

It slowed me down. I had two issues to report regarding the readme.md file, and wound up having to file this report first.

## Your Environment

Chrome browser.

- Version Used:
- Operating System and version (Windows 10, Ubuntu 18.04):
- Link to your project:
- Link to your CI build (if appropriate):
Not relevant.

**Comment by arturcic** [comment]
Fixed in https://github.com/GitTools/GitVersion/pull/3457
