### ISSUE TITLE
[Docs] Quick Links in readme file don't all point to valid pages.

### ISSUE THREAD

**Issue by jwdonahue** [GitTools/GitVersion#2608]
The readme.md file displayed at https://github.com/GitTools/GitVersion has some broken links:

The following list entries return [Page not found](https://gitversion.net/docs/why):

- Why GitVersion
- Usage
- FAQ
- Who is using GitVersion

**Comment by asbjornu** [comment]
Thanks for reporting. #2609 should fix this.
