### ISSUE TITLE
[Bug] Wrong version on Mainline with tag

### ISSUE THREAD

**Issue by Gaurav-Puri101187** [GitTools/GitVersion#2610]
**Describe the bug**
I Was testing GitVersion for the Mainline Mode.
I tagged my latest commit to 0.1.0 
After tagging i used command **gitversion /config** on my main branch.
The next calculated version i get was 0.1.4(based upon my prev commits)

## Expected Behavior
Expected behavior is that next calculated version should have been 0.1.0 as i have explicityly tagged
Another interesting behavior was when i tagged as 0.1.1 then next calculated version was 0.1.1 

## Actual Behavior
Calculate Version becomes 0.1.4
## Your Environment

- Version Used:
- Operating System and version (Windows 10, Ubuntu 18.04):
- Link to your project:
- Link to your CI build (if appropriate):

**Comment by asbjornu** [comment]
If you tag `1.0.0` instead, do you see the same behavior? I know GitVersion has had problems in scenarios where tags are lower than `1.0.0`.

**Comment by Gaurav-Puri101187** [comment]
No,, when i  Tagged as 1.0.0.. the next calculated version is 1.0.0.
Similarly behavior seems to be fine when i tagged 0.1.1 the next version calculated was 0.1.1 which is correct

**Comment by DmytroSokhach** [comment]
Facing the same issue. "next-version" got broken.

How do I install older version of gitversion? 
My collegue has 5.0.1+Branch.master.Sha.c71b8fc9f6d7b6adffe82fef588e717beb864e91 and it works fine for him.

**Comment by asbjornu** [comment]
I don't think this bug is related to `next-version`, @DmytroSokhach as @Gaurav-Puri101187 is using `git tag`. Sounds like you're experiencing #2441 instead, which is remedied by removing `next-version` and adding a `git tag` instead.

**Comment by DmytroSokhach** [comment]
@asbjornu thank you for fast reply! Indeed was using Mainline and next-version, after updating to 5+ didn't notice the moment when it stopped working.
Adding tag to particular commit in master did it's job.
