### ISSUE TITLE
[Bug] GitVersionTask: Rebuild of solution shows warning "File contains assembly version attributes which conflict with the attributes generated by GitVersion"

### ISSUE THREAD

**Issue by mzanin** [GitTools/GitVersion#2613]
**Describe the bug**

Upgraded NuGet package on all of our 16 projects from GitVersionTask 5.0.1 to GitVersionTask 5.5.1 with no other changes and suddenly getting this build warning whenever I rebuild the solution: "File contains assembly version attributes which conflict with the attributes generated by GitVersion [output_path]\AssemblyInfo.g.cs".
We do not have version information in any of our AssemblyInfo.cs files. 
Building once after the rebuild removes the warning. 

So I went through every minor release of GitVersionTask from 5.1 to 5.5 and found that:
* 5.1 - rebuilds successfully
* 5.2 - fails to compile with "GitVersionInformation.g.cs" was specified more than once in the "Sources" parameter..."
* 5.3 - fails to compile with "GitVersionInformation.g.cs" was specified more than once in the "Sources" parameter..."
* 5.4 - no version... ok?!
* 5.5 - rebuilds but with the warning "File contains assembly version attributes which conflict with the attributes..."

**Update (and rant)**
So I noticed another NuGet package named GitVersion.MsBuild which seems to be new and most likely a replacement for GitVersionTask (no mention of this in the documentation which still refers to GitVersionTask...)? 
Upgrading to version 5.6.6 and rebuilding still gives me the same warnings!

I also noticed that this latest version of GitVersion.MsBuild adds a ton of dependencies. Now all of my 16 projects will have to reference these packages which is ridiculous imo. Some of the devs on our team are not even using VS and would now have to reference Microsoft.VisualStudio.Setup.Configuration.Interop which seems to be used to give information about the instance of the VS product? Why is this even needed for GitVersioning? 

```
  <package id="Microsoft.Build.Framework" version="16.8.0" targetFramework="net472" />
  <package id="Microsoft.Build.Utilities.Core" version="16.8.0" targetFramework="net472" />
  <package id="Microsoft.NETFramework.ReferenceAssemblies" version="1.0.0" targetFramework="net472" developmentDependency="true" />
  <package id="Microsoft.NETFramework.ReferenceAssemblies.net472" version="1.0.0" targetFramework="net472" developmentDependency="true" />
  <package id="Microsoft.VisualStudio.Setup.Configuration.Interop" version="1.16.30" targetFramework="net472" developmentDependency="true" />
  <package id="System.Collections.Immutable" version="1.5.0" targetFramework="net472" />
```

## Expected Behavior
Should behave the same as GitVersionTask 5.0.1 - should rebuild without warnings. 

## Actual Behavior
Rebuilds with warning "File contains assembly version attributes which conflict with the attributes generated by GitVersion [output_path]\AssemblyInfo.g.cs" always on the same 3 (out of many) of our projects

## Your Environment
C# with .Net Framework 4.7.2
Windows 10
GitVersionTask 5.5.1
GitVersion.MsBuild 5.6.6
Rider IDE
VS 2019

Edit 1: May be related to https://github.com/GitTools/GitVersion/issues/2352
Edit 2: I created a small repository that reproduces the issue: https://github.com/mzanin/GitVersionBug
Edit 3: I debugged the task with GitVersion and found that UpdateAssemblyInfo is called multiple times and on the second time CheckForInvalidFiles is called with the generated assembly infos (no idea what creates that temp csproj and why): 

![image](https://user-images.githubusercontent.com/1013551/109842928-da7d4900-7c4a-11eb-8f86-2f4202955985.png)

**Comment by BinToss** [comment]
In short, because the conflicting assemblyinfo file is generated by a previous GitVersion MSBuild task, the resulting warning is safe to ignore unless the file's header does not indicate that it was generated by GitVersion.
In DotNet SDK projects, AssemblyInfo.g.cs generated by default during builds.
That behavior can be disabled with the following properties:
```xml
    <!-- GitVersion DotNet SDK Compatibility -->
    <GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
    <GenerateAssemblyFileVersionAttribute>false</GenerateAssemblyFileVersionAttribute>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
```

**EDIT (2026-07-08):**
This was resolved by [326d487](https://github.com/GitTools/GitVersion/commit/326d4872c12f686d32ab4e8117e8cd75b78703bd#diff-fd220849a8350039b5f8daaee5d4199c6b29cb3bf905f9fe5f70ae25e074e5cbL40) in https://github.com/GitTools/GitVersion/pull/2579 which was merged and released in [v5.6.5](https://github.com/GitTools/GitVersion/releases/5.6.5) .
