### ISSUE TITLE
[Improvement] Make github action actually useful

### ISSUE THREAD

**Issue by chadgrant** [GitTools/GitVersion#2621]
The github action doesn't actually update/tag/persist the version in the repo so not sure what the advantage is over just using a tag and do a quick shell parse to use the tag? It seems to be pretty useless

**Comment by asbjornu** [comment]
GitVersion produces a version number based on Git tags and other Git metadata, not the other way around. This is not exclusive to the GitHub Action, but to GitVersion in general. You can read more about how GitVersion works in our [documentation](https://gitversion.net/docs/).

The "advantage" of using GitVersion is that given a Git tag, you are able to deduce a stable version number of a commit in various other branches adhering to Git Flow, GitHub Flow or Mainline development, to help in CI/CD scenarios and similar. If that's of no use to you, then GitVersion is of no use to you and you should look for another tool.
