### ISSUE TITLE
Exec format error on Gitlab CICD with cake build script

### ISSUE THREAD

**Issue by nagtilaklaxman** [GitTools/GitVersion#2626]
**Describe the bug**
When Gitversion is used with the cake build script, it is failing with Exec format error on the GitLab CICD server

## Expected Behavior
It should work and provide the version of the current branch

## Actual Behavior
It is failing with the Exec format error 

## Steps to Reproduce
Below is the live sample application
https://gitlab.com/myself56/cicddemo/-/tree/development

## Context
unable to make the NuGet package with correct version information

- Version Used:
- GitVersion.CommandLine(5.6.6)
- https://gitlab.com/myself56/cicddemo/-/tree/development
- https://gitlab.com/myself56/cicddemo/-/jobs/1089667704

**Comment by asbjornu** [comment]
@gep13, since this is Cake related, do you have any input? 🙏🏼

**Comment by gep13** [comment]
@nagtilaklaxman I don't seem to be able to access any of the links that you have provided.

**Comment by nagtilaklaxman** [comment]
@gep13 
Sorry for the inconvenience.
I have updated the links can you check now

**Comment by nagtilaklaxman** [comment]
@gep13  : Any update on this
