### ISSUE TITLE
[Bug] NugetPreReleaseTag does not respect padding setting

### ISSUE THREAD

**Issue by JustinGrote** [GitTools/GitVersion#2632]
## Description
With padding set, the `nugetprereleasetag` does not match the `nugetversionv2`

```
legacy-semver-padding: 3
build-metadata-padding: 3
commits-since-version-source-padding: 3
```

## Expected Behavior

```json

  "NuGetVersionV2": "0.1.1-ci011",
  "NuGetVersion": "0.1.1-ci011",
  "NuGetPreReleaseTagV2": "ci011",
  "NuGetPreReleaseTag": "ci011",
```

## Actual Behavior
```json
  "NuGetVersionV2": "0.1.1-ci011",
  "NuGetVersion": "0.1.1-ci011",
  "NuGetPreReleaseTagV2": "ci0011",
  "NuGetPreReleaseTag": "ci0011",
```

## Steps to Reproduce
Relevant config: 
```
legacy-semver-padding: 3
build-metadata-padding: 3
commits-since-version-source-padding: 3
```

## Environment
`5.6.6+Branch.main.Sha.80adc3f3b8919b655adca7b796b273fb10478c3f`

**Comment by bitbonk** [comment]
Just came across the same problem. If I wanted to totally disable padding for all of nuget (`NuGetVersionV2`, `NuGetVersion`, `NuGetPreReleaseTagV2`, `NuGetPreReleaseTag`), because (if I am not mistaken) padding is not required at all anymore if you are only targeting .NET Core (or newer).

**Comment by asbjornu** [comment]
@bitbonk, yes we are planning to remove most of the legacy version variables and associated configuration properties in v6.

**Comment by bitbonk** [comment]
@asbjornu If I want to have unpadded nuget prerelease version numbers that respect the way nuget treats version ordering (which is SemVer 2 I suppose), is it safe to set `legacy-semver-padding: 0` ?

Also does it matter whether I use `NuGetVersionV2` or `NuGetVersion` ? Which one is the preferred?

**Comment by asbjornu** [comment]
If you don't want padding, can't you use `SemVer` or `FullSemVer`?

**Comment by bitbonk** [comment]
> If you don't want padding, can't you use `SemVer` or `FullSemVer`?

Right, I probably can. Do you happen to know why `SemVer` has a dot before the prerelease number (`3.22.11-beta.99`) where as `NuGetVersion` just like `LegacySemVer` has not (`3.22.11-beta99`)?

Will NuGet handle versions with that additional dot correctly?

**Comment by asbjornu** [comment]
`SemVer` and `FullSemVer` follows the [SemVer specification](https://semver.org/), while the various `NuGet…` variables are permutations of `FullSemVer` to fit into old versioning schemes that weren't SemVer compatible. The `.99` syntax is specificed in [specification item 9](https://semver.org/#spec-item-9):

>A pre-release version MAY be denoted by appending a hyphen and a series of dot separated identifiers immediately following the patch version. Identifiers MUST comprise only ASCII alphanumerics and hyphens [0-9A-Za-z-]. Identifiers MUST NOT be empty. Numeric identifiers MUST NOT include leading zeroes. Pre-release versions have a lower precedence than the associated normal version. A pre-release version indicates that the version is unstable and might not satisfy the intended compatibility requirements as denoted by its associated normal version. Examples: 1.0.0-alpha, 1.0.0-alpha.1, 1.0.0-0.3.7, 1.0.0-x.7.z.92, 1.0.0-x-y-z.–.

**Comment by asbjornu** [comment]
> So I think, if you want to use `NuGetVersionV2` or `NuGetVersion`, make sure you have enough padding active. And if you don't want to have padding, use `SemVer` or `FullSemVer` (wich both contain the dot).

Sound advice for sure. 👍🏼
