### ISSUE TITLE
[Bug] GitVersion crashes Docker build

### ISSUE THREAD

**Issue by Caleb9** [GitTools/GitVersion#2633]
**Describe the bug**

Running `dotnet-gitversion` during `docker build .` crashes with `LibGit2Sharp.RepositoryNotFoundException`.

To demonstrate this I created a repository containing only a Dockerfile with following content:

```
FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build

WORKDIR /source

RUN dotnet tool install --global --version 5.6.7 GitVersion.Tool && \
    touch GitVersion.yml

COPY ["./.git", "./"] 

RUN export PATH="$PATH:/root/.dotnet/tools" && \
    dotnet-gitversion
```

This is intentionally simplistic only to demonstrate the issue. There's only one commit in the repository (adding the Dockerfile above), so running `dotnet-gitversion` directly in the repository calculates SemVer correctly to 0.1.0. When running `docker build .` it crashes and an image does not get built.

I understand it is necessary to have `.git` directory in the build directory so GitVersion can calculate the version, so that's the only thing I'm copying into the Docker build context.

## Expected Behavior

`docker build .` should simply create a docker image.

## Actual Behavior

`docker build .` crashes with `LibGit2Sharp.RepositoryNotFoundException`:

```
[+] Building 1.0s (9/9) FINISHED                                                                                   
 => [internal] load build definition from Dockerfile                                                          0.0s
 => => transferring dockerfile: 38B                                                                           0.0s
 => [internal] load .dockerignore                                                                             0.1s
 => => transferring context: 2B                                                                               0.0s
 => [internal] load metadata for mcr.microsoft.com/dotnet/sdk:5.0                                             0.1s
 => [1/5] FROM mcr.microsoft.com/dotnet/sdk:5.0@sha256:248d3d37927ca6aa606b41e2f94a17d90e0d3d9079573586b1896  0.0s
 => [internal] load build context                                                                             0.1s
 => => transferring context: 4.01kB                                                                           0.0s
 => CACHED [2/5] WORKDIR /source                                                                              0.0s
 => CACHED [3/5] RUN dotnet tool install --global --version 5.6.7 GitVersion.Tool &&     touch GitVersion.ym  0.0s
 => CACHED [4/5] COPY [./.git, ./]                                                                            0.0s
 => ERROR [5/5] RUN export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/root/.dotnet/  0.7s
------
 > [5/5] RUN export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/root/.dotnet/tools" &&     dotnet-gitversion:
#9 0.641 INFO [03/28/21 11:02:39:62] Working directory: /source
#9 0.641 INFO [03/28/21 11:02:39:63] Project root is: /
#9 0.641 INFO [03/28/21 11:02:39:63] DotGit directory is: /source
#9 0.641 ERROR [03/28/21 11:02:39:65] An unexpected error occurred:
#9 0.641 LibGit2Sharp.RepositoryNotFoundException: Path '/' doesn't point at a valid Git repository or workdir.
#9 0.641    at LibGit2Sharp.Core.Proxy.git_repository_open(String path)
#9 0.641    at LibGit2Sharp.Repository..ctor(String path, RepositoryOptions options, RepositoryRequiredParameter requiredParameter)
#9 0.641    at LibGit2Sharp.Repository..ctor(String path)
#9 0.641    at GitVersion.GitRepository.<>c__DisplayClass7_0.<.ctor>b__0() in D:\a\GitVersion\GitVersion\src\GitVersion.LibGit2Sharp\Git\GitRepository.cs:line 36
#9 0.641    at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
#9 0.641    at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
#9 0.641    at System.Lazy`1.CreateValue()
#9 0.641    at System.Lazy`1.get_Value()
#9 0.641    at GitVersion.GitRepository.get_repositoryInstance() in D:\a\GitVersion\GitVersion\src\GitVersion.LibGit2Sharp\Git\GitRepository.cs:line 15
#9 0.641    at GitVersion.GitRepository.get_Head() in D:\a\GitVersion\GitVersion\src\GitVersion.LibGit2Sharp\Git\GitRepository.cs:line 48
#9 0.641    at GitVersion.VersionCalculation.Cache.GitVersionCacheKeyFactory.GetRepositorySnapshotHash() in D:\a\GitVersion\GitVersion\src\GitVersion.Core\VersionCalculation\Cache\GitVersionCacheKeyFactory.cs:line 149
#9 0.641    at GitVersion.VersionCalculation.Cache.GitVersionCacheKeyFactory.Create(Config overrideConfig) in D:\a\GitVersion\GitVersion\src\GitVersion.Core\VersionCalculation\Cache\GitVersionCacheKeyFactory.cs:line 40
#9 0.641    at GitVersion.GitVersionCalculateTool.CalculateVersionVariables() in D:\a\GitVersion\GitVersion\src\GitVersion.Core\Core\GitVersionCalculateTool.cs:line 47
#9 0.641    at GitVersion.GitVersionExecutor.RunGitVersionTool(GitVersionOptions gitVersionOptions) in D:\a\GitVersion\GitVersion\src\GitVersion.App\GitVersionExecutor.cs:line 61
#9 0.641 INFO [03/28/21 11:02:39:65] Attempting to show the current git graph (please include in issue): 
#9 0.641 INFO [03/28/21 11:02:39:65] Showing max of 100 commits
#9 0.641 INFO [03/28/21 11:02:39:66] * d82d6e6 13 minutes ago  (HEAD -> master, origin/master)
#9 0.641 
------
executor failed running [/bin/sh -c export PATH="$PATH:/root/.dotnet/tools" &&     dotnet-gitversion]: exit code: 1
```

## Steps to Reproduce

1. Clone [https://github.com/Caleb9/gitversion-docker-bug.git](https://github.com/Caleb9/gitversion-docker-bug.git)
2. Run `docker build .` in the repository folder

or to do it "manually":

1. Create a new repository: `git init .`
2. Add the `Dockerfile` above to the repository and create a commit.
3. Try `dotnet-giversion` (assuming `GitVersion.Tool` is installed locally) to see that SemVer 0.1.0 is calculated correctly.
4. Try `docker build .` to see that an image cannot be built.

## Context

I am trying to build a Docker image containing a .NET Core console application which accepts `--version` option to print its version number. Version is normally set on the assembly from `.csproj` file that gets patched using GitVersion.

Outside of Docker, on a CI server where I build the binaries this works fine (e.g. in my [camera-utility](https://github.com/Caleb9/camera-utility) project). But I can't patch the `.csproj` files when building a Docker image for the reasons mentioned above. Normally to achieve this I would of course need some more options passed to `dotnet-gitversion` command, but even just running it without any of them throws an exception.

It's possible that I'm doing something wrong but then maybe you could provide some guidance please?

Please note that there are some other workarounds I had to apply, i.e. when running in Docker build, it seems necessary to have some (even an empty one) `GitVersion.yml` file - otherwise GitVersion bails out. This is different behaviour than observed when running it directly in a terminal, where this file does not need to exist - not sure if this is intended behaviour or another bug, but that's why I used `RUN touch GitVersion.yml` in the Dockerfile. I also needed to fix the PATH variable to make `dotnet-gitversion` accessible.

## Your Environment

- Version Used: 5.6.7
- Operating System and version (Windows 10, Ubuntu 18.04): Docker
- Link to your project: https://github.com/Caleb9/gitversion-docker-bug.git
- Link to your CI build (if appropriate):

**Comment by asbjornu** [comment]
This line seems to be at fault and doesn't make much sense to me:

```
#9 0.641 INFO [03/28/21 11:02:39:63] Project root is: /
```

Since `WORKDIR` is set to `/source`, I don't understand why GitVersion is attempting to traverse the directory tree upwards. 🤔

**Comment by asbjornu** [comment]
Also `touch GitVersion.yml` shouldn't be required (reported in #2634).

**Comment by arturcic** [comment]
The issue with this one is the line 

```dockerfile
COPY ["./.git", "./"] 
```

It should be 
```dockerfile
COPY ["./.git", "./.git"] 
```

Here is an example that works:

```dockerfile
FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build

WORKDIR /source

RUN dotnet tool install --global --version 5.12.0 GitVersion.Tool

COPY ["./.git", "./.git"]

RUN export PATH="$PATH:/root/.dotnet/tools" && \
    dotnet-gitversion

```
