### ISSUE TITLE
[Bug] GitVersion.MsBuild v5.6.7 seems to require the presence of GitVersion.yml now

### ISSUE THREAD

**Issue by odalet** [GitTools/GitVersion#2634]
**Describe the bug**

Build failing when upgrading from v5.6.6 to v5.6.7 because `GitVersion.yml` cannot be found

## Expected Behavior

Although this project does not define any `GitVersion.yml`, everything should work smoothly as with the previous version.

## Actual Behavior

`GitVersion.MsBuild` complains saying: `The configuration file was not found at '/home/runner/work/Delta.Units/Delta.Units/src/Delta.Units/GitVersion.yml' or '/home/runner/work/Delta.Units/Delta.Units/GitVersion.yml'`

## Possible Fix

In the meantime, adding a `GitVersion.yml` at the root of the repository fixes the build. But that's a workaround, I think `GitVersion.yml` should not become mandatory from one minor version to another.

## Steps to Reproduce

Create a project that uses GitVersion.MsBuild, but *do not* provide a `GitVersion.yml` file.

## Context

Raised by dependabot automatic PR

## Your Environment

- Version Used: v5.6.7
- Operating System and version: Linux (GitHub standard ubuntu-latest image, but also true of another project that builds on Windows)
- Link to your project: <https://github.com/odalet/Delta.Units>
- Link to your CI build (if appropriate): <https://github.com/odalet/Delta.Units/pull/29/checks?check_run_id=2215578075>

**Comment by emech-en** [comment]
I have same issue.

Version 5.6.6 works fine, but version 5.6.7 is broken

**Comment by asbjornu** [comment]
This is indeed a bug and I'm quite surprised this doesn't break 99% of our tests.
