### ISSUE TITLE
[Question] Support for Mono

### ISSUE THREAD

**Issue by gep13** [GitTools/GitVersion#264]
Does GitVersion support running under Mono?

If not, are there any plans to support?

**Comment by JakeGinnivan** [comment]
It would be great to have mono support and make GitVersion cross platform. It needs a champion to make this feature happen, if anyone wants to take it on feel free!

**Comment by nulltoken** [comment]
Quick heads up. Check @bording's https://github.com/libgit2/libgit2sharp/pull/984. It should help running LibGit2Sharp on non-Windows platform by embedding the Win/Mac OS X/Linux compiled binaries in a separate NuGet package.

**Comment by JakeGinnivan** [comment]
That is awesome news @nulltoken. When this drops it would be good to try and get GitVersion running on mac/linux :D

**Comment by nulltoken** [comment]
@Jake That was the plan :wink: I'll keep you updated when it's ready for battlefield testing

**Comment by nulltoken** [comment]
@JakeGinnivan Latest prerelease package (`0.22.0-pre20150529055949`) is waiting for you, Sir!

**Comment by therosco** [comment]
Any progress?

**Comment by JakeGinnivan** [comment]
Nope, still up for grabs if anyone wants to have a crack at it

**Comment by onovotny** [comment]
:+1: would love to see this happen, esp to get Xamarin builds on OSX for iOS working the same as the Windows agents

**Comment by BeeWarloc** [comment]
I have made an attempt to upgrade to the latest prerelease of LibGit2Sharp to fix this for GitVersionTask, as it broke the build of one of my projects on mono.

https://github.com/GitTools/GitVersion/pull/638

Due to a problem with how mono searches for dlls, I had to place them in libNativeBinaries instead of NativeBinaries. There is a discussion about this here: https://github.com/libgit2/libgit2sharp/issues/1170

This has received limited testing, but it works for compiling a medium sized project with mono 4.0.3 on Ubuntu 15.04.

**Comment by BeeWarloc** [comment]
https://github.com/GitTools/GitVersion/pull/638

**Comment by hazzik** [comment]
:+1:

**Comment by hazzik** [comment]
What about switching to ngit? As it is fully managed library?

**Comment by Therzok** [comment]
@hazzik NGit is unmaintained, and we switched away from it in MonoDevelop because of various issues that arose when using it. Updating it is not an easy task either.

**Comment by ghuntley** [comment]
It seems mono for x86/amd64 on Linux was fixed by #638

Mono on OSX remains unresolved.

https://gist.github.com/ghuntley/f7f9a120ab40a69f56e9

using

    <title>GitVersion.CommandLine</title>
    <version>3.4.1</version>

    $ mono --version
    Mono JIT compiler version 4.2.2 (explicit/996df3c Wed Jan 20 00:19:48 EST 2016)
    Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           normal
	SIGSEGV:       altstack
	Notification:  kqueue
	Architecture:  x86
	Disabled:      none
	Misc:          softdebug
	LLVM:          yes(3.6.0svn-mono-(detached/a173357)
	GC:            sgen
