### ISSUE TITLE
[Bug]  DisableGitVersionTask ineffective

### ISSUE THREAD

**Issue by NeilMacMullen** [GitTools/GitVersion#2640]
**Describe the bug**
The *DisableGitVersionTask* property was used on the old *GitVersionTask* package to allow continuous test runners such as Ncrunch to operate without access to the git repository.  It appears that no longer works with the new GitVersion.MsBuild package.  Instead, *gitversion.exe* is run and then fails (due to not being able to find '.git').  

## Expected Behavior
No gitversion tasks should be run if DisableGitVersionTask is set to true

## Actual Behavior
Errors such as this occur (from NCrunch Trace Output)

```
NCrunch: This project was built on server '(local)'
C:\Users\neilm\.nuget\packages\gitversion.msbuild\5.6.7\tools\GitVersion.MsBuild.targets: The command ""C:\Users\neilm\.nuget\packages\gitversion.msbuild\5.6.7\tools\net48/gitversion.exe" "C:\Users\neilm\AppData\Local\NCrunch\20620\27\Textrude" -output file -outputfile obj\gitversion.json" exited with code 
```

[This post](https://forum.ncrunch.net/yaf_postsm15241_GitVersion-MSBuild-error.aspx#post15241)  describes the same issue (from another user).

## Possible Fix

Presumably something in the twisty maze of conditional properties in GitVersion.MsBuild.props is going awry.

## Context
Show stopper since unable to run tests

## Your Environment

- Version Used: 5.6.7 but it seems to have been broken at least as far back as 5.6.0
- Operating System and version: Windows 10
- Link to your project:  [Branch exhibiting issue](https://github.com/NeilMacMullen/Textrude/tree/gitversion-upgrade)
- Link to your CI build (if appropriate): N/A - checkout and run locally with Ncrunch enabled

**Comment by NeilMacMullen** [comment]
Quite possible I'm misunderstanding the dependency chain but shouldn't the "GetVersion" target  in GitVersion.MsBuild.targets have a condition attached?


Ie 

`<Target Name="GetVersion" DependsOnTargets="RunGitVersion" BeforeTargets="$(GitVersionTargetsBefore)">`

should probably be 


`<Target Name="GetVersion" DependsOnTargets="RunGitVersion" BeforeTargets="$(GitVersionTargetsBefore)" Condition="$(GetVersion) == 'true'>`

**Comment by Leszek-Kowalski** [comment]
DisableGitVersionTask is ineffective when running plain build via MSBuild or VS as well.

**Comment by NeilMacMullen** [comment]
@Leszek-Kowalski   good point  - have renamed the issue to make this more obvious!

**Comment by Leszek-Kowalski** [comment]
Hi,
Would it be possible to release 5.6.9 ?
This issue has been bugging our team for a bit too long.
Thanks :)

**Comment by xerootg** [comment]
I just spent the last 6 hours beating my head against what seems like this issue, can I bribe the gitversion team to release this or something? I'd really like to use all this goodness.
