### ISSUE TITLE
[Bug] Microsoft.Build.Utilities.Core should be a private dependency for GitVersion.MsBuild 

### ISSUE THREAD

**Issue by bording** [GitTools/GitVersion#2642]
The GitVersion.MsBuild package currently has a package dependency on Microsoft.Build.Utilities.Core. This is an internal dependency of the package and should not be public. By having this as a public dependency, all consumers of GitVersion.MsBuild get an unneeded transitive reference to Microsoft.Build.Utilities.Core.

## Possible Fix
Make the [Microsoft.Build.Utilities.Core package reference](https://github.com/GitTools/GitVersion/blob/main/src/GitVersion.MsBuild/GitVersion.MsBuild.csproj#L16) be `PrivateAssets="All"`.

**Comment by bording** [comment]
I've opened #2643 to fix this.

**Comment by bording** [comment]
@arturcic Is there any time frame for when 5.6.8 will be released? The current packages having this dependency is a blocker for us to adopt the new GitVersion.Msbuild package.

**Comment by arturcic** [comment]
Well there is no time frame, but I think we can release today, I will have a look
