### ISSUE TITLE
[Improvement] Customize branch build tags (more)

### ISSUE THREAD

**Issue by krishanj20** [GitTools/GitVersion#2654]
**Is your improvement request related to a problem? Please describe.**
Hi, Im trying to use GitVersion to create release candidates for custom python libraries. The issue is that conda doesn't like it, throwing the error
`Error: bad character '-' in package/version: 0.6.0-airflow2.1`
 - in the tags when I build from branch. After taking a look at the documentation there is no way to change that dash to a dot or something similar. I am wondering if this feature could be added?

## Detailed Description

Add the ability in the yaml to set the style of the resulting tag.e.g.
`{tag}.{branchName}.{branchversion}`
## Context

SO this would be especially useful for conda builds as this is my use case, but more customization is always good!

**Comment by asbjornu** [comment]
Sounds like a duplicate of #2065?
