### ISSUE TITLE
Unshallow Error with GIT_DEPTH: "1000" 

### ISSUE THREAD

**Issue by axle07** [GitTools/GitVersion#2655]
**Describe the bug**
We've been getting intermittent failures in our pipeline with the following error message:

```
Fetching changes with git depth set to 1000...
Reinitialized existing Git repository in /builds/core/
fatal: error in object: unshallow 050112029e77de15d7accb5ea870d14462cea532
Cleaning up file based variables 00:02
ERROR: Job failed: exit code 1
```

## Expected Behavior
CI runs without error

## Actual Behavior
~30% of the time we receive the "unshallow" error listed above

## Steps to Reproduce
Push to gitlab (triggering a new job).
Steps to reproduce are tricky, because the error is intermittent.

## Your Environment
About 19,000 files in repo
.gitlab-ci.yml includes:
```
variables:
  GIT_DEPTH: "1000"
```

Ubuntu 20.04

**Comment by asbjornu** [comment]
Does `GIT_DEPTH: 0` work, to fully clone the repository and not just perform a shallow clone?

**Comment by axle07** [comment]
Same result

**Comment by asbjornu** [comment]
Are you able to do `git fetch --unshallow` before executing GitVersion? [GitVersion's requirements for successful execution are documented](https://gitversion.net/docs/reference/requirements).
