### ISSUE TITLE
Command to create a tag?

### ISSUE THREAD

**Issue by rcdailey** [GitTools/GitVersion#2663]
First of all, I realize a link to Gitter was provided for questions, but there is nothing but questions in the channel from the past couple of weeks and I do not see anyone answering those questions. So I will provide my question here, instead.

I have read the docs and searched previous issues. I am not seeing a way to create a git tag locally from the calculated version. NerdBank.GitVersioning, for example, has a command to do this with `nbgv tag`. I was planning on using Github Flow + Continuous Delivery. My goal is to push a tag to my repo when it is time to build a release. My Github Action workflow performs deployment steps in addition to a build if a tag is pushed.

I don't see how people are expected to create tags manually, especially if they are using continuous deployment. Version numbers can become very non-deterministic without parsing through commits.

I'm still new to this and am in the research phase, so I apologize if I missed something obvious. I did my best to research this before posting.

**Comment by asbjornu** [comment]
As I wrote in https://github.com/GitTools/GitVersion/issues/2621#issuecomment-794646195:

>GitVersion produces a version number based on Git tags and other Git metadata, not the other way around. This is not exclusive to the GitHub Action, but how GitVersion works in general. You can read more about how GitVersion works in our [documentation](https://gitversion.net/docs/).

**Comment by rcdailey** [comment]
I disagree with your reasoning. I think especially in a continuous deployment situation, where version numbers can be wildly nondeterministic (from a user's perspective), there's a lot of value in facilitating a way to create tags. Especially since GitVersion is the authority on version numbers here.

Just leaving my opinion here "for the record". I'm not expecting any changes, as I've seen the same response in similar topics about GitVersion. I'll close this one out.
