### ISSUE TITLE
[Docs] missing redirects

### ISSUE THREAD

**Issue by matkoch** [GitTools/GitVersion#2664]
<img width="906" alt="image" src="https://user-images.githubusercontent.com/5005566/115116982-b4163180-9f9c-11eb-8534-ef86538e771f.png">

**Comment by asbjornu** [comment]
I'm not sure this particular issue still exists, but it is a huge problem that we still have a lot of duplicated information on ReadTheDocs. I would like to take it all down and just redirect everything to [gitversion.net](https://gitversion.net/). I'm not sure how to go about doing that, though. A pull request would be highly appreciated. 🙏🏼

**Comment by gep13** [comment]
I have this on my list of things that I would like to get to, but that list keeps getting longer and priorities on it change ☹️

**Comment by gep13** [comment]
From the screenshot above, one of the affected URL's is:

https://gitversion.net/docs/more-info/incrementing-per-commit

If everything has worked, this link should now redirect to correct location.

**Comment by gep13** [comment]
@matkoch I am going to go ahead and close this out as most of the internal redirects within the site have now been taken care of.

Given the changes that have happened to the docs, and the different technologies that we have used over the years, there is a good chance that we have missed something, but these can be tackled under a different issue if any other broken links are found.

Thanks for reporting this!
