### ISSUE TITLE
[Feature] Gitversion support for apple silicon

### ISSUE THREAD

**Issue by iamNoah1** [GitTools/GitVersion#2668]
I would like to use gitversion on my apple silicon. 

Installing using brew gives me: `Error: dotnet: no bottle available!`

Try to use the docker image gives me:
```
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
Failed to create CoreCLR, HRESULT: 0x8007FF06
```

**Comment by arturcic** [comment]
Unfortunately we currently do not support the new silicon. Even though there is some level of support for ARM provided by Libgit2sharp, but we do not support it official

**Comment by iamNoah1** [comment]
Any plans on supporting it in the future?

**Comment by arturcic** [comment]
I think we should support it in long term, the issue is we are not able to build it in GitHubAction or AzurePipelines at the moment. When that is available we could add support for the M1

**Comment by jshinevar** [comment]
I have not tried this yet, but here is the full error I see from homebrew:

`Error: gitversion: no bottle available!
You can try to install from source with:
  brew install --build-from-source gitversion
Please note building from source is unsupported. You will encounter build
failures with some formulae. If you experience any issues please create pull
requests instead of asking for help on Homebrew's GitHub, Twitter or any other
official channels.`

Has anyone tried using the --build-from-source?  Were you successful?

**Comment by asbjornu** [comment]
[Support for M1 in .NET is underway](https://github.com/orgs/dotnet/projects/18), but still far from completed. Until both .NET and LibGit2Sharp has full support for M1, GitVersion won't be able to provide full support for M1.

**Comment by andymac4182** [comment]
For me I need to run the arm64 version with docker which is supported in dotnet as far as I am aware. 

It would be great if there could be a arm64 docker image. https://docs.docker.com/desktop/multi-arch/

**Comment by MuhKuh7** [comment]
any updates on this one?

**Comment by arturcic** [comment]
@MuhKuh7 actually it should already support osx-arm64 starting with 5.8.1 https://github.com/GitTools/GitVersion/releases/tag/5.8.1

**Comment by MuhKuh7** [comment]
@arturcic thx, will 5.8.1 be available on homebrew (https://formulae.brew.sh/formula/gitversion) soon?

**Comment by arturcic** [comment]
unfortunately for the homebrew we ned to have the dotnet formula for version 6.0, that's something @asbjornu was working on. So for now no, you can only use the tar.gz version for now
