### ISSUE TITLE
[Bug] CommitDate using UTC

### ISSUE THREAD

**Issue by davi1td** [GitTools/GitVersion#2671]
Using latest version 5.6.8 
CommitDate returns a date without time but appears its coming  from a UTC date/time.
I don't think that makes since since we're only using a date here.
Git GUI shows the correct date/time ...
If its going to be using UTC I think it should be called that and then return the full UTC date/time so it can be converted.
Regards

**Comment by asbjornu** [comment]
The default date format is `yyyy-MM-dd`, but the [`commit-date-format` can be configured](https://gitversion.net/docs/reference/configuration#commit-date-format) to whatever you want. It's not possible to change from UTC, though.

https://github.com/GitTools/GitVersion/blob/92f3d5b64229395a71d3c0307ea51e03b316b486/src/GitVersion.Core/VersionCalculation/SemanticVersioning/SemanticVersionFormatValues.cs#L65

**Comment by davi1td** [comment]
Thought it was simple thanks!
for Ref:
in GitVersion.yml :
commit-date-format: 'yyyy-MM-ddTHH:mm:ss'
in Program :
DateTime.Parse(GitVersionInformation.CommitDate).ToLocalTime()
