### ISSUE TITLE
GitVersion automatically increases the minor version regardless of the branch configuration

### ISSUE THREAD

**Issue by syamrag** [GitTools/GitVersion#2678]
I am using gitversion 5.6.9 and I am on Ubuntu 16.04.1. I am following gitflow work flow and I have created a hotfix branch from master branch. I set the increment for hotfix branch to "Patch" and mode to  "ContinuousDelivery". When ever I make any commits on hotfix branch the gitversion automatically increases the minor version regardless of the branch configuration I given.  

Master - 1.0.0

hotfix - 1.0.0

Once I make any commit on hotfix the gitversion becomes 1.1.0 instead of 1.0.1.

**Comment by syamrag** [comment]
``mode: ContinuousDeployment
continuous-delivery-fallback-tag: ''
major-version-bump-message: '\+semver:\s?(breaking|major)'
minor-version-bump-message: '\+semver:\s?(feature|minor)'
patch-version-bump-message: '\+semver:\s?(fix|patch)'
legacy-semver-padding: 4
build-metadata-padding: 4
commit-message-incrementing: Enabled
tag-prefix: '[vV]'


branches:
feature:
tag: 'a'
mode: ContinuousDelivery
regex: features?[/-]
increment: Inherit
prevent-increment-of-merged-branch-version: false
is-release-branch: false
track-merge-target: false
tracks-release-branches: false
source-branches: ['develop', 'hotfix']

develop:
tag: 'b'
mode: ContinuousDeployment
increment: Minor
prevent-increment-of-merged-branch-version: false
is-release-branch: false
track-merge-target: true
tracks-release-branches: true

release:
tag: 'rc'
mode: ContinuousDelivery
regex: releases?[/-]
increment: Inherit
prevent-increment-of-merged-branch-version: true
is-release-branch: true
track-merge-target: false
tracks-release-branches: false

master:
tag: ''
mode: ContinuousDelivery
regex: ^master$|^main$
increment: Patch
prevent-increment-of-merged-branch-version: true
is-release-branch: false
track-merge-target: false
tracks-release-branches: false

pull-request:
tag: 'pr'
mode: ContinuousDelivery
regex: (pull|pull\-requests|pr)[/-]
increment: Inherit
prevent-increment-of-merged-branch-version: false
tag-number-pattern: '[/-](?<number>\d+)[-/]'
is-release-branch: false
track-merge-target: false
tracks-release-branches: false

hotfix:
tag: 'post'
mode: ContinuousDelivery
regex: hotfix(es)?[/-]
increment: Patch
prevent-increment-of-merged-branch-version: false
is-release-branch: false
track-merge-target: false
tracks-release-branches: false

**Comment by asbjornu** [comment]
This seems to completely contradict #2454?

**Comment by syamrag** [comment]
Yes, I think so. I also tried to set the increment to "Major" and "None" and regardless of the configuration gitversion still increment the minor portion.

**Comment by asbjornu** [comment]
Can you please just try to delete `GitVersion.yml` and tell me how it behaves then?

**Comment by syamrag** [comment]
Quick update on this. I was able to solve the problem. When I changed the hot fix branch form "hotfix" to "hotfix/fix" it works as expected. So, I think the problem is with regular expression pattern I used to match the hotfix branch. You can close this issue and Thanks for your help.
