### ISSUE TITLE
Azure devops pipeline unable to access GitVersion variables

### ISSUE THREAD

**Issue by aurimasroxit97** [GitTools/GitVersion#2682]
**Describe the bug**
On Azure Devops build pipeline, I am setting build number format to `$(GitVersion.MajorMinorPatch)`. This sets the build number format as text `$(GitVersion.MajorMinorPatch)` and not to an actual MajorMinorPatch number.

## Expected Behavior
Build number format should be set to GitVersion.MajorMinorPatch variable, not text.

Default GitVersion (version 5) configuration is being used. On "Execute GitVersion" task, I've added _/output buildserver_ to additional GitVersion arguments, but this did not solve the issue. 

I can also see that Execute GitVersion task runs successfully, and does print out all the GitVersion variables as expected.

**Comment by asbjornu** [comment]
Can you please paste your `GitVersion.yaml` configuration?

**Comment by aurimasroxit97** [comment]
@asbjornu There is no GitVersion.yml, using completely default configs.

**Comment by aurimasroxit97** [comment]
@asbjornu As a last resort, I tried switching the build agent from Linux machine to Windows and suddenly build number format was transformed to an actual MajorMinorPatch number. If using $(GitVersion.MajorMinorPatch) for build number format works when using Windows agent, what should be used when using Linux?

**Comment by asbjornu** [comment]
> There is no GitVersion.yml, using completely default configs.

So you're configuring the build number format in the pipeline configuration? How does that look like, then?

> As a last resort, I tried switching the build agent from Linux machine to Windows and suddenly build number format was transformed to an actual MajorMinorPatch number. If using $(GitVersion.MajorMinorPatch) for build number format works when using Windows agent, what should be used when using Linux?

It shouldn't differ. If your experience is reproducible, this is surely a bug.

**Comment by asbjornu** [comment]
I don't use AzDO, so I have no idea what's possible there, but GitVersion does expose every [version variable](https://gitversion.net/docs/reference/variables) it creates as environment variables that you should be able to use after GitVersion has executed.

**Comment by phatcher** [comment]
@aurimasroxit97 Here's the yaml fragment I use to update the build number - the build id is added so that the builds are uniquely named if you are doing non-semantic changes

```
# Update the build version to our SemVer
- script: echo %Action%%BuildVersion%
  displayName: 'Set build version'
  env:
    Action: '##vso[build.updatebuildnumber]'
    BuildVersion: '$(Version.GitVersion.NugetVersionV2)-$(Build.BuildId)'
```
