### ISSUE TITLE
[Bug] VersionInBranchNameVersionStrategy only considers the release branch

### ISSUE THREAD

**Issue by ruhullahshah** [GitTools/GitVersion#2693]
**Description**

In order to calculate the next version, GitVersion evaluates the version numbers produced by various [candidates](https://github.com/GitTools/GitVersion/tree/main/src/GitVersion.Core/VersionCalculation/BaseVersionCalculators) and selects the one that yields the highest version number on a give branch. [VersionInBranchNameVersionStrategy](https://github.com/GitTools/GitVersion/blob/main/src/GitVersion.Core/VersionCalculation/BaseVersionCalculators/VersionInBranchNameVersionStrategy.cs) is one of the candidates and from the name of it, should only look at the current branch. For instance, `hotfix/17.1.0`. However, this strategy seems to be [biased](https://github.com/GitTools/GitVersion/blob/main/src/GitVersion.Core/VersionCalculation/BaseVersionCalculators/VersionInBranchNameVersionStrategy.cs#L32) and only considers release branches. This approach probably violates the single responsibility principle and can be a source of bugs.

Additionally, another [strategy](https://github.com/GitTools/GitVersion/blob/main/src/GitVersion.Core/VersionCalculation/BaseVersionCalculators/TrackReleaseBranchesVersionStrategy.cs#L37) uses it and the version detection in the branch name could probably be parameterized.

## Expected Behavior
The strategy should consider the version in the current branch, e.g. `hotfix/17.1.0`

## Actual Behavior
The version in the hotfix branch name has no chance to make it to the [list](https://github.com/GitTools/GitVersion/blob/main/src/GitVersion.Core/VersionCalculation/BaseVersionCalculator.cs#L37) of possible candidates.

## Possible Fix
Make strategy branch agnostic.

## Context
1.We created a hotfix branch (`hotfix/1.0.1`) from the tag `v1.0.0`
2. However, the calculated version number was still `1.0.0-something` because we had set `prevent-increment-of-merged-branch-version` to `true`.
3. In this situation, we would have expected the version number from the hotfix branch name to make it to the list of candidates as well.

## Workaround
Set the  `prevent-increment-of-merged-branch-version` to `false`

## Environment
OS: Windows
GitVersion version: Latest

**Comment by asbjornu** [comment]
> Make strategy branch agnostic.

As long as we don't have any regressions, that sounds like a fine improvement to me. 👍🏼 Do you have a solution in mind that you can submit a PR for? 🙏🏼

**Comment by ruhullahshah** [comment]
@asbjornu Yes, I do have a solution and as a first step, I have added a unit test that better illustrates this problem in PR #2696.
