### ISSUE TITLE
[Bug] Build fail when building a detached head

### ISSUE THREAD

**Issue by Evangelink** [GitTools/GitVersion#2697]
**Describe the bug**

I have setup my projects to use GitVersions and as soon as I try to build a commit from history (detached head), build fails with

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB3073	The command ""C:\Users\XXX\.nuget\packages\gitversion.msbuild\5.6.9\tools\net48/gitversion.exe" "C:\Src\YYY" -output file -outputfile obj\gitversion.json" exited with code 1.	YYY	C:\Users\XXX\.nuget\packages\gitversion.msbuild\5.6.9\tools\GitVersion.MsBuild.targets	9	
```

## Expected Behavior

I should be able to get back to any commit and simply build my solution.

## Actual Behavior

Build fails, I have to comment the nuget from all my projects and rebuild.

## Steps to Reproduce

1. Create a simple project
2. Add `GitVersion.MsBuild`
3. Commit some code
4. Commit something else
5. Get back to previous commit
6. Build the solution, the solution fails

My `GitVersion.yml`:
```
assembly-versioning-scheme: MajorMinorPatch
mode: ContinuousDelivery
next-version: 1.0.0
branches: {}
ignore:
  sha: []
merge-message-formats: {}
```

## Context

I am trying to see on which commit a bug was introduced.

## Your Environment

- Version Used: 5.6.9
- Operating System and version (Windows 10, Ubuntu 18.04): Windows 10

**Comment by asbjornu** [comment]
[Detached head is not supported](https://gitversion.net/docs/reference/requirements).

**Comment by Evangelink** [comment]
Hi @asbjornu,

Thanks for the link!

I understand that a detached head makes it impossible to determine correctly a version but having build failures when you looking at the history is pretty annoying. Would it be possible to consider avoiding a hard-failure or introducing some option to only warn and continue with a fallback version? I can understand the failure might be interesting for some contexts but I fail to see it useful when recompiling past versions of the code.

I am willing to help if you think that's something that could be useful.

**Comment by asbjornu** [comment]
I would accept a pull request that changed the current behavior as long as it doesn't break any other tests.
