### ISSUE TITLE
[Bug] - Cannot find the .git folder 

### ISSUE THREAD

**Issue by tomdewilde** [GitTools/GitVersion#2701]
**Describe the bug**
gitversion cannot find the .git folder although it is clearly present in the current folder

## Expected Behavior
normal run

## Actual Behavior
gitversion cannot find the .git folder

## Steps to Reproduce
it happens in any of my repo folders

## Your Environment
- Version Used: 5.6.6
- Operating System and version: Windows 10 x64

![image](https://user-images.githubusercontent.com/17985681/119035444-df32dd00-b9af-11eb-96b5-c88ebbc742d9.png)

**Comment by asbjornu** [comment]
Does this happen in the latest version of GitVersion as well?

**Comment by tomdewilde** [comment]
yes just installed the latest version, same issue.
Tried /verbose Diagnostic argument, but I don't get any more information.
Very strange. I've been using GitVersion for some time now without any
problems, but now suddenly I get this on all my repos ...

**Comment by tomdewilde** [comment]
Problem solved. My mistake ... I accidantally deleted some mandatory folder from the .git folder.
