### ISSUE TITLE
[Bug] Azure DevOps - PR merge to main from release results in patch, not minor 

### ISSUE THREAD

**Issue by spr0ut** [GitTools/GitVersion#2704]
**Describe the bug**
Starting with a tag `0.1.0` on main. a merge from `release/0.2.0` results in a calculated version `0.1.x`, when it should produce a version of `0.2.0`.

## Expected Behavior
Correct version is calculated, so it can be used to tag the main branch.

## Actual Behavior
Version is calculated as `0.1.x` (x depending on how many times I've run this test scenario!)

## Steps to Reproduce
According to this fixture test. the merge should result in the version `0.2.0` - this passes.
```
        [Test]
        public void ReleaseFromMasterShouldNotBeBetaTag()
        {
            using var fixture = new EmptyRepositoryFixture();
            fixture.Repository.MakeATaggedCommit("0.1.0");
            //dev
            fixture.BranchTo("develop");
            //feature
            fixture.BranchTo("feature/new-thing");
            fixture.Repository.MakeCommits(5);
            fixture.AssertFullSemver("0.2.0-new-thing.1+5");
            //back to dev
            fixture.Checkout("develop");
            fixture.MergeNoFF("feature/new-thing");
            fixture.AssertFullSemver("0.2.0-alpha.6");//5 commits from feature PLUS the merge
            //release
            fixture.BranchTo("release/0.2.0");
            fixture.AssertFullSemver("0.2.0-beta.1+0");
            ///main
            fixture.Checkout(MainBranch);
            fixture.MergeNoFF("release/0.2.0");
            fixture.AssertFullSemver("0.2.0+0");
        }
```

However, performing these steps on a repo in Azure Devops, the final being create and complete the PR, results in the build producing the incorrect version. I'd understand this behaviour if the above test case failed, but the result of the MergeNoFF suggests this should work. What am I missing?

Link to GitVersion config https://gist.github.com/spr0ut/294ab16c7ee8cd5b55f9af14a5117742
Should be pretty much stock, but included anyway.

**Comment by asbjornu** [comment]
A branch name is only able to affect its own version, not the version of the merge target. That's why the merge-commit needs to be tagged. When the branch `release/0.2.` is deleted, GitVersion won't have any idea where the merge-commit came from (other than possibly being mentioned in the commit message).

**Comment by spr0ut** [comment]
In my test, I didn't actually delete the release branch, but if GitVersion doesn't look at it regardless, then this makes sense as there is no tag. Why does `MergeNoFF` pass in the test case, is it creating a commit message?
Getting Azure DevOps to tag on the merge commit after the PR completes is a different problem,,,

**Comment by asbjornu** [comment]
GitVersion can't operate under the assumption that branches other than `master` / `main` (and, in Git Flow, `develop`) are permanent. Why your test with `MergeNoFF` succeeds I can't explain without investigating, but a predictable merge message might be it.

**Comment by spr0ut** [comment]
For reference, configuring the merge message in the PR title results in the expected behaviour. Could be better documented as it's a bit cumbersome to understand, as evidenced by the above.

**Comment by asbjornu** [comment]
A pull request to clarify this in [the documentation](https://gitversion.net/) would be highly appreciated, @spr0ut. 🙏🏼
