### ISSUE TITLE
Build system build number (version) customisation

### ISSUE THREAD

**Issue by RobSmyth** [GitTools/GitVersion#2719]
Allow the customisation build system build number update to include the build system's actual/original build number to uniquely identify a build.

## Detailed Description

Currently, for a non-release build, GitVersion will update our build system (TeamCity) with prerelease metadata that includes a commit count:

`<major>.<minor>.<patch>-Beta.<commit count>`

As noted in the documentation, this does not give a unique SemVer. What is important to me is traceability to a build system build, even if the same commit is rebuilt multiple times. The need is to have a concise SemVer shown on the build system that is easily mapped to a products SemVer to identify the exact build. Build numbers are good as they are sequential.

**Note:**
* If building on a dev box we set the build number to U to mark it as uncontrolled. Useful to detect dev builds that gone free range.
* For me, being able to add the build system build number to the general metadata is another useful feature for same reasons. 

We currently add code to do this, but what would be better is to be able to define the build number prerelease as something like:

`Beta.{BuildNumber}`

## Context

This is important to provide simple traceability of a build, that may discovered on a machine, to the actual build on the build system. This then gives us the git commit info, changes, and importantly which build agents, which tools used, etc.

In many situations a release candidate must be (or it would be nice to be) a release just waiting testing. That is, no rebuild. So this feature (if the build number is in the SemVer metadata) means that we can internally identify RCs from the final promoted release.

Very important for medical software and those needing complete reproducibility. Besides it just makes it easier.

## Possible Implementation

Sorry, we needed to add MsBuild tasks to read the generated info, construct the version and then pass it to the build system. This is an FYI for potential improvements.

**Comment by asbjornu** [comment]
In #2720 you mention `{env:BUILD_NUMBER}` yourself, why can't you use that?

**Comment by RobSmyth** [comment]
I tried that on a branch spec:

  `tag: beta.{env:BUILD_NUMBER ?? U}`

This gives `beta.U` on a dev box (GOOD) but then gives `beta.{env:BUILD_NUMBER ?? U}.1` on TeamCity. Note that the `.1` is not wanted.

I'm missing something obvious?

**Comment by asbjornu** [comment]
Configuring the `tag` will only change the pre-release label, which will be appended to as you've discovered. If you're able to use something like `assembly-file-versioning-format`, you'll have full control over the end result. Please investigate the [different configuration properties](https://gitversion.net/docs/reference/configuration) that are available and whether some of them would be a better fit.

**Comment by RobSmyth** [comment]
Thanks,

`assembly-file-versioning-format` is a bit problematic as that version is a Microsoft version <major>.<minor>.<build>.<patch>, so our implementation is:

> ` assembly-file-versioning-format: '{Major}.{Minor}.{{env:BUILD_NUMBER ?? 0}}.{Patch}'`

Same of course for the assembly version.

Using the info version format is also a problem as we use that to provide full metadata (short sha1). The build system's number needs to be short and the sha1 is not useful as it has that anyway. So I cannot use the info version format.

**Alternative**

So ... thinking of another solution to display the info required ... can we drop the `<commit count>` for the pre-release metadata?

Thing is we are release focused with a release always being off a build system. We need to know which build. The same code can be recompiled with multiple builds ... which one did we ship?

That is:

> For a non-release branch build:
> 
>     `'{Major}.{Minor}.{Patch}'-Beta+{env:BUILD_NUMBER ?? U}'`
> 
> For a release branch build:
> 
>     `'{Major}.{Minor}.{Patch}+{env:BUILD_NUMBER ?? U}'`
>
> Examples:
>
>     1.2.3-Beta+2345
>     1.2.3+2345

But ... how can I make "-Beta" (without a commit count) only visible on a non-release branch build?

**Comment by asbjornu** [comment]
If you want different values for different branches, you can use the [branch configuratio](https://gitversion.net/docs/reference/configuration#branch-configuration), no?
