### ISSUE TITLE
Treat all builds on developer boxes as prerelease

### ISSUE THREAD

**Issue by RobSmyth** [GitTools/GitVersion#2720]
I require, for traceability and reproducibility, that all release builds come from the build system. It would be good to be able to override **PreReleaseTag** when no build system is detected.

## Detailed Description

I have a need to clearly identify if a product or assembly was built on a developer's box. The tools used in the build are not known. Hence the build may not realistically be reproducible and therefor not supportable.

Current GitVersion allows defining SemVer prerelease metadata using **PreReleaseTag** and branch **is-release-branch**. Good. This feature is to allow this to be overridden, for all branches, if the build is not a build system.

Not part of the request, but to explain usage, my SemVer release/prerelease definition is:

Release - Built on the build system AND on a release branch.
Beta  - Built on the build system AND not on a release branch.
Alpha - Not built on the build system (uncontrolled).

**Note:** I currently do use the syntax in the documentation of `{env:BUILD_NUMBER ?? U}`. Useful but not as implicit as making it prerelease and something like "ALPHA".

## Context

I have a need to clearly identify if a product or assembly was built on a developer's box. Such a build should not be sent to a customer. Critically important for software that must have strong traceability such as medical software.

Would be highly valued by others who want to ensure that only builds off a build system are in circulation.

## Possible Implementation

Sorry retrospective suggestion. I have implemented by nasty MsBuild tasks and turning build number update off.

**Comment by asbjornu** [comment]
Could you please try to devise a possible implementation so I can better understand what it is you want here?
