### ISSUE TITLE
Save variables as environment variables

### ISSUE THREAD

**Issue by RobSmyth** [GitTools/GitVersion#2721]
When writing scripts to customise version formatting to our needs, it has been difficult to access GitVersion variables. It would be easier if GitVersion variable(s) could optionally be exposed as environment variables.

## Detailed Description

When using a batch file (say) or an MsBuild task (target file) to customise version formatting to our needs we need to read the GitVersion variable from a file (this may be mutually exclusive to using command line `output` option of `buildsystem`).

If we could, by configuration, nominate all or some variables to be made available as system variables (current session only) then we could access those in many languages including even (shock) a batch file.

## Context

Reduce dev time to use the tool.

## Possible Implementation

Another retrospective solution. Done by awful means.

**Comment by asbjornu** [comment]
It's not well documented, but GitVersion already exposes all version variables as environment variables in the form `GitVersion_<variable_name>` such as `GitVersion_FullSemVer`.

**Comment by RobSmyth** [comment]
Thank you, I must be missing something as I tried that without success. I call version.exe as a Visual Studio prebuild event and then call `set` to list all variables. I do not see any `GitVersion_...` variables. Same on my box and the build box (TeamCity).

I've not been able to access the variable as %GitVersion_FullSemVer%.

**Comment by asbjornu** [comment]
I see. `gitversion.exe` should set environment variables if it detects that it's running within a [supported build server](https://gitversion.net/docs/reference/build-servers/). 


itself, that's done by the different build tasks (as how environment variables are set differs from build server to build server). You can see how it's done in AzDO here:

https://github.com/GitTools/GitVersion/blob/dca800837bb34e3cda8be4fb28b0bc72964e656f/src/GitVersion.Core/BuildAgents/AzurePipelines.cs#L20-L27

#2722 seeks to improve the documentation in this area.

**Comment by RobSmyth** [comment]
Well I was actually thinking of the host OS environment variables. That looks like a build system's variables/parameters.

**Comment by asbjornu** [comment]
GitVersion does write OS environment variables, but I don't know AzDO well enough to say for certain that's what the linked code does. I **can**, however, say for certain that the GitHub Actions integration does it as per the following lines of code:

https://github.com/GitTools/GitVersion/blob/dca800837bb34e3cda8be4fb28b0bc72964e656f/src/GitVersion.Core/BuildAgents/GitHubActions.cs#L16
https://github.com/GitTools/GitVersion/blob/dca800837bb34e3cda8be4fb28b0bc72964e656f/src/GitVersion.Core/BuildAgents/GitHubActions.cs#L47
https://github.com/GitTools/GitVersion/blob/dca800837bb34e3cda8be4fb28b0bc72964e656f/src/GitVersion.Core/BuildAgents/GitHubActions.cs#L51-L59
