### ISSUE TITLE
[Feature] Use GitVersion on submodules

### ISSUE THREAD

**Issue by Dirk-Kuypers** [GitTools/GitVersion#2725]
I (as a config manager) have a user project which is using GitVersion and submodules. The project states they used GitVersion for the submodules since years and it always worked. When I google for submodule support and GitVersion it seems to me that this is not a supported feature of GitVersion like stated in [Issue 2321](https://github.com/GitTools/GitVersion/issues/2321) for instance.

Building the application with the submodule on Jenkins leads to the following warning (referencing the develop branch of the submodule):
GitVersionTask.targets(10,9): warning : It looks like the branch being examined is a detached Head pointing to commit 'd615ea8'. Without a proper branch name GitVersion cannot determine the build version.

Building the application on a release branch with the submodule pointing at the submodule's release branch we get a version number:
Getting branches containing the commit '44ebad314dc691bcfd96c51229cd56287b9e9fc2'. (Took: 195.94ms)
15:27:07.866    
15:27:07.866    2021-06-10 15:27:08		  INFO [06/10/21 15:27:08:21] Running against branch: origin/release/18.1.2 (44ebad314dc691bcfd96c51229cd56287b9e9fc2)

The version of GitVersion  used is 5.3.4 if that matters. 

So I am a bit puzzled. 

- Should this work and it is a bug? 
- Or is it coincidence if I get a version number on a release branch? 
- Or is it just some kind of misconfiguration on our side?

Thanks for a hint
Dirk

**Comment by asbjornu** [comment]
See https://github.com/GitTools/GitVersion/issues/2321#issuecomment-641879784

**Comment by Dirk-Kuypers** [comment]
Thanks for the answer, I already found the issue. But I was unsure, if this is a real general statement that GitVersion is not suited for submodules because obviously it seems that it works at least sometimes. 

So to sum it up: There is no support in GitVersion for submodules and implementation is very difficult or even not possible.

**Comment by asbjornu** [comment]
The support GitVersion has for submodules is accidental and not explicit. We do not have any test coverage for submodules so we have no means to assert that the accidental submodule support doesn't regress over time. If someone invested the time to add proper submodule support and (most importantly) added a heap of tests for it, we would applaud such an effort and gladly merge it in.
