### ISSUE TITLE
[Improvement] Automatically update Docker Hub README with released version

### ISSUE THREAD

**Issue by asbjornu** [GitTools/GitVersion#2742]
As noted in GitTools/build-images#3, the tag of the Docker image provided in the README on Docker Hub should preferably be equivalent to our latest released, stable, version. Keeping the README up to date manually is not a viable solution. The optimal thing would be to have a GitHub Action running `on: release` that [updated the README on Docker Hub automatically](https://gist.github.com/chrodriguez/f4f4fb9c42d429e3b9a22151cecd178a).

**Comment by arturcic** [comment]
I think we ccan use this one instead https://github.com/peter-evans/dockerhub-description
