### ISSUE TITLE
Linux Arm64 Support

### ISSUE THREAD

**Issue by jonstelly** [GitTools/GitVersion#2747]
I have a need to run gitversion on linux/arm64.

## Detailed Description
It looks like there was some discussion of this before in #1998.  I've got the building of the linux/arm64 binary working, PR to be submitted shortly.

## Context
I use gitversion and my build process runs on x64 and arm64 hardware.  Being able to run gitversion directly on the arm64 hardware would simplify the kludgy way I have to run gitversion from x64 and then kick off the arm64 part of the build with those values passed as arguments.

## Possible Implementation
See PR linking to this one in a minute.  I don't need arm64 docker images but I'm happy to add those to the PR with some guidance from a maintainer.

**Comment by asbjornu** [comment]
I believe this was implemented in #2863. If not, please reopen and explain why.
