### ISSUE TITLE
[Bug] /updateassemblyinfofilename switch doesn't work

### ISSUE THREAD

**Issue by pgrawehr** [GitTools/GitVersion#2749]
**Describe the bug**
The switch `/updateassemblyinfofilename` can, according to the help screen, be used to specify a particular AssemblyInfo.cs file to update (instead of recursively updating all of them). Since I have a `GlobalVersionInfo.cs` file in my project which is included from all projects in the solution, that's very handy - if it would work. 

## Actual Behavior
The command 
```
dotnet-gitversion /updateassemblyinfo /updateassemblyinfofilename GlobalAssemblyInfo.cs
```
throws an exception, saying that the switch `/updateassemblyinfofilename` is not recognized. Looking at the code, the parser nowhere identifies this string. 

The suggested shorthand
```
dotnet-gitversion /updateassemblyinfo GlobalAssemblyInfo.cs
```
silently ignores the argument if the file cannot be found (and then behaves as if `/updateassemblyinfo` was used without file name, updating all AssemblyInfo.cs files instead). If the target file exists, this shorthand seems to work (but only with a simple file, if a path is given, it again doesn't work)

Additionaly, there's no way to use this syntax with the Nuke extension. `GitVersionSettings` has no overload to `SetUpdateAssembly` that takes a string as argument. Using `SetUpdateAssemblyFileNames` again causes the exception above. 

## Expected Behavior

1) `/updateassemblyinfofilename <filename>` is recognized
2) `/updateassemblyinfo <SomeNonExistingFile>` throws an exception

## Possible Fix

See above

## Steps to Reproduce

See above. Run the command
```
dotnet-gitversion /updateassemblyinfo /updateassemblyinfofilename GlobalAssemblyInfo.cs
```
within a git repo with an existing file `GlobalAssemblyInfo.cs`

## Your Environment

- Version Used: GitVersion 5.6.10+Branch.main.Sha.e9013533474e8e46b6a0ca60d20d02f3680b5980
- Windows 10, dotnet 5.0
- Attempting to set up a Nuke build with the latest Nuke version

**Comment by pgrawehr** [comment]
Hi Bot! This issue is not stale just because nobody seems to care about it.

**Comment by pgrawehr** [comment]
I'm currently using this workaround in my Nuke script:

```csharp
                        var globalAsmInfoTmpl = SourceDirectory / "GlobalAssemblyInfo.cs.tmpl";
			var globalAsmInfo = globalAsmInfoTmpl.ToString().Replace(".tmpl", "", StringComparison.InvariantCultureIgnoreCase);

			CopyFile(globalAsmInfoTmpl, globalAsmInfo, FileExistsPolicy.Overwrite);

			GitVersionTasks.GitVersion(c =>
				c.SetProcessWorkingDirectory(SourceDirectory)
				.SetFramework("net6.0")
				.SetProcessArgumentConfigurator(a => a.Add("/updateassemblyinfo GlobalAssemblyInfo.cs"))
			);
```
When the file exists already _and_ the code is executed with the working directory set, the problem does not happen.

**Comment by Jaschan** [comment]
Thanks for the answer! at the end I went with my own workaround, I will leave it here since it could help other people.

I renamed my `GlobalAssemblyInfo.cs` to `AssemblyInfo.g.cs`.
And the ones that I didn't wanted to be modified by GitVersion now are called `ProjectAssemblyInfo.cs` instead of `AssemblyInfo.cs`.

I took inspiration from the testing on the source code xD

![image](https://user-images.githubusercontent.com/4916750/231794535-6de1ccdb-8951-441c-ba69-bbfb46eb3f47.png)

**Comment by Jaschan** [comment]
I was doing more testing and this works:
- `dotnet-gitversion /ensureassemblyinfo /updateAssemblyInfo GlobalAssemblyInfo.cs` (this one actually address the issue from OP)
- `dotnet-gitversion /updateAssemblyInfo GlobalAssemblyInfo.cs` (In case you don't want GitVersion to generate the file)

but the option  `/updateassemblyinfofilename GlobalAssemblyInfo.cs` don't work. This one will throw an exception.

Tested on version 5.12.0
