### ISSUE TITLE
[Bug] Task fails if path is too long

### ISSUE THREAD

**Issue by asclearuc** [GitTools/GitVersion#2751]
**Describe the bug**
Task fails if path is too long

## Expected Behavior
Do not fail on long paths

## Actual Behavior
The task fails where there  is a long path inside it.
The error is:
```
2>    ERROR [07/15/21 13:59:39:01] An unexpected error occurred:
2>  LibGit2Sharp.LibGit2SharpException: invalid path '\\?\D:\development\_etc\c#\GitLongPath\aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb\cccccccccccccccccccccccc\ddddddddddddddddddddddd\eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee\ffffffffffffffffffffffffffffffffffffffff\gggggggggggggggggggggggggggggggggggggggg' (path too long)
2>     at LibGit2Sharp.Core.Ensure.HandleError(Int32 result)
```

Full path contains 295 characters in my case

As a result - task fails:
```
2>D:\development\_etc\c#\GitLongPath\packages\GitVersion.MsBuild.5.6.10\tools\GitVersion.MsBuild.targets(9,9): error MSB3073: The command ""D:\development\_etc\c#\GitLongPath\packages\GitVersion.MsBuild.5.6.10\tools\net48/gitversion.exe" "D:\development\_etc\c#\GitLongPath\GitLongPath2" -output file -outputfile gitversion.json" exited with code 1.
```

## Possible Fix
Either:
- **process it correctly (correct way)**
- ignore long path (as a workaround, may be with additional option)

## Steps to Reproduce
Clone the repo [GitVersionLongPath](https://github.com/asclearuc/GitVersionLongPath) and compile it

## Context
Upgrading from 5.3.6 to 5.6.* (cause versions up to 5.6.* are not supported already)
Actually latest non-supported version (5.5.1) already fails with my repo
Upgrading from .NET framework 4.6 to 4.8

## Your Environment

- Version Used: 5.6.10
- Operating System and version: Windows 10 / Visual Studio 2019
- Link to your project: https://github.com/asclearuc/GitVersionLongPath (as a demo)
- Link to your CI build (if appropriate): Locally, using Visual Studio 2019

**Comment by asbjornu** [comment]
Isn't this a Win32 error? I'm pretty sure this error is impossible to reproduce on other operating systems than Windows. I think catering for deficiencies in Windows is out of scope for GitVersion.

**Comment by asclearuc** [comment]
> Isn't this a Win32 error? I'm pretty sure this error is impossible to reproduce on other operating systems than Windows. I think catering for deficiencies in Windows is out of scope for GitVersion.

With GitVersionTask version 5.3.6 everything is working
With newer versions (GitVersionTask 5.5.1 && GitVersion.MSBuild 5.6.10) - is not

**Comment by asbjornu** [comment]
Hm, that's weird. If you're able to figure out what changed since 5.3.6 that may have affected this, a pull request reverting the behaviour (and adding a test to avoid regressions) would be warmly welcomed. 🙏🏼

**Comment by hanamantsm** [comment]
I have the same issue in Windows 2012 R2 build server. The GitVersion tool (v5.7.0) is failing due to file length exceeding 260 characters. The issue remains the same even when I use the latest version of the GitVersion tool.

Initially, the long path file caused the issue in checking out into the build server, which I fixed by enabling a registry key called LongPathsEnabled.

Now, when the GitVersion tool is trying to determine the version we are getting the below error from the LibGit2Sharp library of the GitVersion tool.
ERROR [01/27/22 4:31:06:49] An unexpected error occurred:
LibGit2Sharp.LibGit2SharpException: invalid path '<filePath>' (path too long).

We found that the path to long issue is resolved in the below issue
https://github.com/libgit2/libgit2sharp/issues/1805 

Please provide new release with this issue resolved.

**Comment by asbjornu** [comment]
@hanamantsm, no release of LibGit2Sharp has been made since December 11, 2019. It needs to be updated and we have no sensible way of doing it without them publishing a new version of it. Taking on a fork of LibGit2Sharp as a source dependency is not an option.

**Comment by arturcic** [comment]
This should already be fixed as the latest version of GitVersion is already using a version of LibGit2Sharp that includes the fix

**Comment by SaurabhRaoot** [comment]
Fond solution here https://forum.uipath.com/t/error-libgit2sharp-libgit2sharpexception-path-too-long/462510/3
