### ISSUE TITLE
Un-needed versionVariables field

### ISSUE THREAD

**Issue by Evangelink** [GitTools/GitVersion#2752]
The field `versionVariables` in https://github.com/GitTools/GitVersion/blob/main/src/GitVersion.MsBuild/GitVersionTaskExecutor.cs#L16 is actually never used (always written before being read) and could be refactored as local variable in the various methods.

Happy to provide a fixing PR if you approve the change.

**Comment by asbjornu** [comment]
PR welcome! 🙏🏼
