### ISSUE TITLE
[Improvement] Throw in yield function could result in unexpected behavior

### ISSUE THREAD

**Issue by Evangelink** [GitTools/GitVersion#2755]
I would like to suggest a small change in the [GetBranchesContainingCommit](https://github.com/GitTools/GitVersion/blob/main/src/GitVersion.Core/Core/RepositoryStore.cs#L240) yielding function. Its current form makes it fully "asynchronous" causing the exception to be thrown only when the collection will be iterated. That's currently not a problem in the codebase because all call sites are doing direct iteration but this could cause some issue in the future if new call sites are added without respecting this condition.

## Detailed Description

Please use the following [Sharplab repro](https://sharplab.io/#v2:C4LgTgrgdgNAJiA1AHwAICYAMBYAUBgRj1UwAJUCAWAbjwEgGHiBmc9cggdjwG96N09PrgYUAnAAoARAAkApgBsFAe1IB1ZWAVwpASlq5SR40ahyA7h04TdAOgDic4ADFlyiVAhL9pAPS/SADlVOQAPAGM5AAdgAEtlKFJoOIVSWOA5MABDDLg8ExMzSwprO0cXN3QPLwUff1IAUQjouITSYAALMGVzRLhYsDlw4AUAT3oAX3p+VgpmAB5YqGAAPlJy13dlACMAKyHgUmVdIXo6WIAzUglVAF5b0k9vM7pO7ssi0gBBMABzCAAtnJloEak1IjF4lAPFkgcoLjddPozmcKARyJxSJgDKICOjUJiCDipoZjPljKhZgQFktVusnJsqjt9sMjicRMIGJdrncHk9ai83j1HhZvn9AcDgKClOCWlCYXCEcdkSI6OSChjSABJAFRBQ2AwaozqgpzRbLNY6vU2E0mTl0ExozXYs6OvGaom24wkugkiZAA===) to see the problem live.

## Context

As said in the description, there is no direct problem but this is an issue to become if people are unaware of this behavior and so do not respect the condition use.

## Possible Implementation

The sharplab link contains a suggestion of implementation (with a local function), the name has to be defined. I usually go for `Iterator`, `Impl` or function name + suffix (e.g. `XXXIterator` or `XXXImpl`). It's also probably worth adding a comment to explain the reasoning of the split.

**Comment by asbjornu** [comment]
Thanks for pointing it out. A PR with your possible implementation would be welcome. 🙏🏼
