### ISSUE TITLE
[Improvement] Add static code analyzers

### ISSUE THREAD

**Issue by Evangelink** [GitTools/GitVersion#2760]
I would like to suggest to install [Microsoft.CodeAnalysis.NetAnalyzers](https://github.com/dotnet/roslyn-analyzers) to enhance code quality and also [Microsoft.CodeAnalysis.CSharp.CodeStyle](https://docs.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/) for styling/formatting rules.

This would help this project to increase the overall quality but also help to enforce certain code style you would like to see.

## Context

The first package would help to prevent certain code smells and future bugs to sneak into the codebase. The second helps to have a defined code style and could help contributors to "code" the way you prefer.

## Possible Implementation

There are a lot of alternative code analyzers but these two are Microsoft actively contributed and are becoming a defacto standard in .NET5+ (can be opt-in/opt-out).

**Comment by arturcic** [comment]
Do you mind making a PR? Adding the packages and fixing the code?

**Comment by Evangelink** [comment]
That's absolutely fine. I will go with the default set of rules and let you decide if there are specific you would like to enable (or disable).

**Comment by asbjornu** [comment]
This would be great. I've started https://github.com/asbjornu/GitVersion/pull/25 which I'm struggling to get past the tests, but please have a look at the code style I'm aiming for there so we can get compatibility between ReSharper (`.DotSettings`)  and `Microsoft.CodeAnalysis.CSharp.CodeStyle` (if possible).
