### ISSUE TITLE
[Improvement] Add Microsoft public API analyzer

### ISSUE THREAD

**Issue by Evangelink** [GitTools/GitVersion#2762]
Add the public [API analyzer](https://github.com/dotnet/roslyn-analyzers#microsoftcodeanalysispublicapianalyzers). This analyzer helps you define what's part of the public API and what's not. If there are changes made to the public API you will get notification and so you can easily decide whether or not to incorporate them AND also have an easy way to track breaking changes.

**Comment by asbjornu** [comment]
A PR that implements this is very welcome.
