### ISSUE TITLE
[Improvement] CA1018 ReflectionIgnoreAttribute is missing AttributeUsage info

### ISSUE THREAD

**Issue by Evangelink** [GitTools/GitVersion#2777]
See https://docs.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1018

## Possible Implementation

1. Define what should be the usage kind.
2. Update attribute to specify the info.
3. Change rule level from message to warning to prevent further issues.

**Comment by Evangelink** [comment]
@asbjornu I will let you get back to me with the info and then I will provide the PR.

**Comment by asbjornu** [comment]
Adding `AttributeUsage` only makes sense. I can't think of a reason not to do it.

**Comment by Evangelink** [comment]
Could you let me know where this attribute is supposed to be allowed or disallowed? I will then submit a PR.

**Comment by asbjornu** [comment]
I can only find `ReflectionIgnoreAttribute` in the codebase and I can't see that it's in use anywhere except for the reflection code that looks for its usage. Better to delete it than decorate it, imho.

**Comment by Evangelink** [comment]
Fixed by #3032
