### ISSUE TITLE
[Bug] Self assignment in SemanticVersion.cs

### ISSUE THREAD

**Issue by Evangelink** [GitTools/GitVersion#2782]
**Describe the bug**
In https://github.com/GitTools/GitVersion/blob/main/src/GitVersion.Core/VersionCalculation/SemanticVersioning/SemanticVersion.cs#L308 there is a self-assignment (i.e. property = property). The code was introduced with the bug in 2015.

## Possible Fix

I would recommend to simply remove the line of code as it is useless and doesn't result from a change.

**Comment by asbjornu** [comment]
> I would recommend to simply remove the line of code as it is useless and doesn't result from a change.

Agreed. PR welcome. 🙏🏼
