### ISSUE TITLE
[Bug] Mainline mode breaks hotfix version when commit is tagged

### ISSUE THREAD

**Issue by koershov** [GitTools/GitVersion#2786]
**Describe the bug**
When I use mainline mode with master and hotfix branch it works fine unless I start tagging every commit.
Imagine a hotfix branch is branched out from the mainline at version 1.2.0. From that point, every commit on that branch should increment only the patch version. But if one of the commits on hotfix was tagged with current version the next version calculation will be broken (the minor version will be affected by an unrelated commit on mainline)
Here's an example how the git structure for that case looks like

```
* 45d2cdf 44 minutes ago  (HEAD -> hotfix/may)
* a756535 46 minutes ago  (tag: 1.2.2)
* 104d39d 48 minutes ago 
| * b6e989c 50 minutes ago  (main)
|/  
* 1a4437e 52 minutes ago 
* 6ef88f0 54 minutes ago  (tag: 1.1.0)
* 0ad3ed8 56 minutes ago  (tag: 1.0.0)
* eb7857c 58 minutes ago 
```

The same thing happens when the commit where the hotfix branch was branched of is tagged

```
* 5b74598 50 minutes ago  (HEAD -> hotfix/may)
| * 5a68be2 52 minutes ago  (main)
|/  
* d44f7f1 54 minutes ago  (tag: 1.1.0)
* 7784f67 56 minutes ago  (tag: 1.0.0)
* 6d36b75 58 minutes ago 

```

## Expected Behavior
First example, the version should be "1.2.3"
Second example, the version should be "1.1.1"

## Actual Behavior
First example, the version should is "1.3.1"
Second example, the version should be "1.2.1"

## Possible Fix
It feels like mainlineCommitLog should include also the commit where the current branch was branched off. In FindMergeBaseBeforeForwardMerge method

## Steps to Reproduce
Tests are here #2787

## Context
Our strategy is very simple. Each commit on main should increment minor. Each commit on hotfix should increment patch.

**Comment by asbjornu** [comment]
While this does sound like a bug, I wonder why you would tag the `hotfix` branch?

**Comment by koershov** [comment]
We just tag every commit on which we run the build. But even if we don't, there's still gonna be an issue when parent commit of the hotfix branch is tagged (example 2)

**Comment by asbjornu** [comment]
Are you able to submit this as a (failing) test in a PR?

**Comment by koershov** [comment]
I've already provided 2 tests here https://github.com/GitTools/GitVersion/pull/2787/files

**Comment by asbjornu** [comment]
Ah, sorry. I haven't had time to investigate.

**Comment by Bazaleev** [comment]
Hi @asbjornu, any update on this one? It does look like a bug and quite unpleasant one.

**Comment by HHobeck** [comment]
The `hotfix` branch inherits from the `main` branch and gets the `IncrementStrategy.Minor`. Why would you expect that the patch number increases!? And I don't understand why you would create a tag (an exception might be a pre-release tag) on the `hotfix` branch. Your scenario seems to me not following the git hub workflow. Please see this documentation https://gitversion.net/docs/learn/branching-strategies/gitflow/examples#hotfix-branches.

The following configuration is something which might be suit better for your use case:

```csharp
[Test]
public void HotfixScenarioWithVersioningModeMainline()
{
    var configuration = GitFlowConfigurationBuilder.New
        .WithVersioningMode(VersioningMode.Mainline)
        .WithBranch("main", _ => _.WithIncrement(IncrementStrategy.Minor))
        .WithBranch("hotfix", _ => _.WithIncrement(IncrementStrategy.Patch))
        .Build();

    using var fixture = new EmptyRepositoryFixture("main");

    fixture.MakeATaggedCommit("1.0.0");

    // ✅ succeeds as expected
    fixture.AssertFullSemver("1.0.0", configuration);

    fixture.MakeACommit();

    // ✅ succeeds as expected
    fixture.AssertFullSemver("1.1.0", configuration);

    fixture.MakeACommit();

    // ✅ succeeds as expected
    fixture.AssertFullSemver("1.2.0", configuration);

    fixture.ApplyTag("1.2.0");

    // ✅ succeeds as expected
    fixture.AssertFullSemver("1.2.0", configuration);

    fixture.BranchTo("hotfix/1.2.1");
    fixture.MakeACommit();

    // ✅ succeeds as expected
    fixture.AssertFullSemver("1.2.1-beta.1+1", configuration);

    fixture.MakeACommit();

    // ✅ succeeds as expected
    fixture.AssertFullSemver("1.2.1-beta.1+2", configuration);

    fixture.ApplyTag("1.2.1-beta.1");

    // ✅ succeeds as expected
    fixture.AssertFullSemver("1.2.1-beta.1", configuration);

    fixture.MakeACommit();

    // ✅ succeeds as expected
    fixture.AssertFullSemver("1.2.1-beta.2+1", configuration);

    fixture.Checkout("main");
    fixture.MergeNoFF("hotfix/1.2.1");

    // ✅ succeeds as expected
    fixture.AssertFullSemver("1.2.1", configuration);

    fixture.ApplyTag("1.2.1");

    // ✅ succeeds as expected
    fixture.AssertFullSemver("1.2.1", configuration);

    fixture.MakeACommit();

    // ✅ succeeds as expected
    fixture.AssertFullSemver("1.3.0", configuration);
}
```
