### ISSUE TITLE
[Bug] Inconsistency between GitVersion.MsBuild and GitVersion.Tool

### ISSUE THREAD

**Issue by vhatsura** [GitTools/GitVersion#2813]
**Describe the bug**
GitVersion.Tool sets [`NuGetVersionV2` as `Version`](https://github.com/GitTools/GitVersion/blob/686e17d4533ff1637bfc8bac70085ced90c2ded3/src/GitVersion.Core/VersionConverters/AssemblyInfo/ProjectFileUpdater.cs#L45) attribute in project file, however, [`GitVersion.MsBuild` uses `FullSemVer`](https://github.com/GitTools/GitVersion/blob/686e17d4533ff1637bfc8bac70085ced90c2ded3/src/GitVersion.MsBuild/msbuild/tools/GitVersion.MsBuild.targets#L55).

## Expected Behavior
 `GitVersion.MsBuild` should use `NuGetVersionV2` as `Version` attribute in project file.

## Actual Behavior
`FullSemVer` is used as the value for the `Version` attribute in the project file.

## Possible Fix
Change a value in targets to `$(GitVersion_NuGetVersionV2)`

## Context

It prevents from setting proper version for NuGet package with padded prerelease tag. As a workaround, it's possible to disable `UseFullSemVerForNuGet`.

## Your Environment

- Version Used: 5.6.11

**Comment by asbjornu** [comment]
I agree it should be consistent, but I'm not sure whether `GitVersion.Tool` should start using `FullSemVer` or `GitVersion.MsBuild` should start using `NuGetVersionV2`. But one of them should probably change to the other. Thoughts, @arturcic?

**Comment by arturcic** [comment]
I agree that we need to make it consistent, but I would go for $(GitVersion_NuGetVersion) for both cases.
@vhatsura are you in a position to make this change and submit a PR?

**Comment by vhatsura** [comment]
> I agree that we need to make it consistent, but I would go for $(GitVersion_NuGetVersion) for both cases.
> 
> @vhatsura are you in a position to make this change and submit a PR?

Yeap, I’m open to implement such changes, but before, it would be nice to align on the implementation details. Firstly, do I need to change GitVersion.Tool as well? Then, should UseFullSemVer property be deprecated as it will
