### ISSUE TITLE
Allow project defined GitVersionOutputFile.

### ISSUE THREAD

**Issue by hubuk** [GitTools/GitVersion#2844]
I would like to make GitVersion create `gitversion.json` file in different location that the default one `$([MSBuild]::EnsureTrailingSlash($(BaseIntermediateOutputPath)))gitversion.json`. 
One of the simplest ways of doing this is by defining value for this property in Directory.Build.props file.
The problem is that GitVersion.MsBuild.props does not allow default value.

## Detailed Description
A value for GitVersionOutputFile property in GitVersion.MsBuild.props should be set only if the property does not have a value assigned already.

## Context
I would like to use gitversion.json file in FrontEnd project which due to some external requirements expects source file to be located in particular location. I would like to change the default location.

## Possible Implementation
```JSON
<GitVersionOutputFile Condition="'$(GitVersionOutputFile)' == ''">$([MSBuild]::EnsureTrailingSlash($(BaseIntermediateOutputPath)))gitversion.json</GitVersionOutputFile>
```
`Condition` attribute defined as above should be sufficient. I can prepare a PR if the requested improvement is acceptable by maintainers 😊

**Comment by arturcic** [comment]
Honestly I'm not against, it might provide more flexibility. Go for it
