### ISSUE TITLE
Correct version in TeamCity agent (checkout on agent) when no tags available.

### ISSUE THREAD

**Issue by hmemcpy** [GitTools/GitVersion#285]
Unless I'm doing something wrong, here's the problem I have:

When running in TeamCity (VCS mode changed to "checkout on agent", to have the `.git` directory present), TeamCity uses `git fetch` to get the latest changes onto the agent. By default, `git fetch` does not fetch the tags (you need to use `git fetch --tags` to have git fetch the changes *and* tags, or `git fetch origin refs/tags/*:refs/tags/*` to fetch the tags only).
Since after a clean fetch no tags are present, and there is no `NextVersion.txt` file present, GitVersion will display an incorrect version number (e.g. 0.2.xxx)

To "workaround" this, I've added a build step that fetches tags before calling GitVersion.

So, is there something wrong with my setup?
Would it make sense to add this flow to GitVersion, to have it always fetch the tags automatically (in TeamCity mode)?

**Comment by JakeGinnivan** [comment]
@hmemcpy is this still an issue?

**Comment by gsuttie** [comment]
im tagging a release 1.10.2 but when I build on TeamCity Enterprise 9.0.4 (build 32407) - Gitversion is showing 1.9.2 ;(

**Comment by gep13** [comment]
@gsuttie just want to check...

Can you confirm the exact command that you are using to run GitVersion on TeamCity?

**Comment by JakeGinnivan** [comment]
Reopen if still an issue in v3

**Comment by sstorie** [comment]
I'm new to using gitflow, and especially in setting TeamCity up to use it effectively, but I'm running into this situation myself. Right now I had some release builds that were properly updating when I tag'd commits, but at some point stopped. Now the tags aren't being updated on the agent's checkout working directory even though the latest revision is pulled down. I just see a collection of tags that worked before, and nothing new is added.

I was able to manually pull them down to the working copy using `git fetch --tags`, but something happened to break the regular functionality.

I'll keep digging and report back anything I can figure out.

*This is using TeamCity 9.0.4*

**Comment by brianlocke** [comment]
Using this workaround fixed this issue for us: https://youtrack.jetbrains.com/issue/TW-24878
