### ISSUE TITLE
Getting type of update (major/minor/patch) or previous version 

### ISSUE THREAD

**Issue by user4426** [GitTools/GitVersion#2860]
I am using GitVersion in a pipeline that builds and versions a python library. This library should only be uploaded if the version changes and I would therefore like to have a way to check for version changes. I assumed that `CommitsSinceVersionSource` would be zero whenever the version changed but it seems that the number corresponds to the state before (e.g., version changed from `1.0.39` with `CommitsSinceVersionSource` is 24 to `1.1.0` but `CommitsSinceVersionSource` is 25). Do I have to parse the commit message and search for `semver` or is there a straightforward way to achieve this?

**Comment by asbjornu** [comment]
Can't you just extract the last `git tag` and compare that to the version number GitVersion produces?
