### ISSUE TITLE
[Feature Request] Add JSON schema to help configure 'GitVersion.yml'

### ISSUE THREAD

**Issue by BinToss** [GitTools/GitVersion#2874]
## Detailed Description
GitVersion only has a JSON schema for the *output* JSON, but it lacks one for the *input* YAML/JSON config.

## Context
I've found that going back and forth between the documentation and the config file I'm editing takes up more time than it could if my editor was able to detect a schema and use that to suggest properties and values. It wouldn't be perfect, but nothing is.

**Comment by BinToss** [comment]
So long as the user has the RedHat YAML language server installed and
enabled, as well as the appropriate IntelliSense settings, I believe so.

Visual Studio IDE's IntelliSense should work the same depending on the IDE
versions' support for YAML and JSON.

**Comment by BinToss** [comment]
I can't recommend using one schema file for...two schemas.
Ham-fisting a mix of incompatible values into a schema would confuse code
editors that support JSON Schema matching.

GitVersion expects 'gitversion.yml' and 'gitversion.json' to have different
contents, but a JSON schema expects the yml and json extensions to be
interchangeable.
This means that one or the other must have its filename changed to prevent
collisions.

Hopefully, this change will be as simple as "Replace 'gitversion.yml' with
'gitversion.cfg.yml' in all files" so we can have non-colliding schemas.

**Comment by asbjornu** [comment]
I have no idea how this works, but your suggested solution sounds good @BinToss. I suppose that's up to @SchemaStore, though?

**Comment by BinToss** [comment]
I recently learned that one can specify a JSON schema via a "$schema" property in the JSON/YAML file. This property allows both URLs and local file paths. The schema filename can be different than the current file's name.

https://developer.microsoft.com/json-schemas/sp/site-design-script-actions.schema.json

Consequently, we now have three more solutions for GitVersion.json and GitVersion.yml:
- host both files' schemas in a GitVersion-owned repo or branch and access them remotely.
- package both schemas with GitVersion, copy them to be alongside their respective json/yml, and write the relative path to those files.
- Generate the schemas during runtime based on what's available in the currently executing GitVersion assembly.

GitVersion CLI is already capable of generating and configuring a config file. Depending on how that's implemented, also generating a schema should be relatively easy.

**Comment by asbjornu** [comment]
> host both files' schemas in a GitVersion-owned repo or branch and access them remotely.

I like this option and think we should expose them through the website on [gitversion.net](https://gitversion.net/). A PR adding `GitVersion.json` and `GitVersion.yml` to the website would be appreciated.
