### ISSUE TITLE
[Bug] GitVersion is extremely slow (25 minutes)

### ISSUE THREAD

**Issue by samhocevar** [GitTools/GitVersion#2881]
**Describe the bug**
Running `gitversion` to generate the JSON for a project is very slow; about 25 minutes.

## Expected Behavior
It should not take more than a few seconds.

## Steps to Reproduce
This is a private project I cannot share, unfortunately, but I can run additional tests if necessary.

Attached is a log with `/diag`: [gitversion-log.txt](https://github.com/GitTools/GitVersion/files/7351835/gitversion-log.txt)

## Your Environment

- Version Used: 5.7.0+Branch.main.Sha.8d177c6d666c8eeb1c6a6a2c71fd4b78741137d2
- Operating System and version (Windows 10, Ubuntu 18.04): Windows 10
- git version 2.33.1.windows.1
- The repository has about 12,000 commits in total and 11,000 tags.

**Comment by asbjornu** [comment]
May this be related to #2864, perhaps?

**Comment by asbjornu** [comment]
If an upgrade of LibGit2Sharp may help alleviate this problem, #2916 should provide useful.
