### ISSUE TITLE
Improve GitVersion performance

### ISSUE THREAD

**Issue by candritzky** [GitTools/GitVersion#2885]
GitVersion unnecessarily slows down the build process on solutions with many projects.

## Detailed Description
GitVersion.exe has a performance problem when used in large solutions with several hundred projects.
Even though it takes less than a second for each project, this sums up to a couple of avoidable minutes for each (re-)build.
This is not so much of a problem on a build agent, but it is annoying during local development when the Git history hasn't changed but larger parts of the application need to be built due to my code changes.

Significant overhead is caused by the YamlDotNet library which is used for gitversion_cache and config file parsing.
The deserialization code is pretty slow on the first call ("cold start") for each deserialized type (here: Dictionary<string,string>, see VersionVariables.FromFileInternal and Config, see ConfigSerializer.Read). (Obviously it needs some internal "warmup" and caches the generated deserializers.)

Here's a performance trace (taken with JetBrains dotTrace) that shows how slow e. g. the gitversion_cache file parsing currently is:

![image](https://user-images.githubusercontent.com/3244395/138491274-1fd19ead-30e9-49ad-9d52-a2b522173bc1.png)

And here's how fast it could be with some very simple/naive, hand-crafted parsing logic (that currently works only for the simply structured gitversion_cache file):

![image](https://user-images.githubusercontent.com/3244395/138491316-9b461731-6aad-48cb-8ff5-625e7bba59c3.png)

A similar performance hit (> 100 ms) can be seen when parsing the GitVersion Config file.

An additional performance gain seems to be achievable by streamlining the startup procedure (CreateHostBuilder and friends).

## Context
Performance improvements are important because I'm slowed by down GitVersion by additional build times during development.
gitversion.exe is executed thousands of times per day and should be strongly optimized performance.

## Possible Implementation
Replace YamlDotNet with a faster YAML parser, or find a way to somehow pre-compile the internal setup of its deserializers (optimized for the required data types).

**Comment by candritzky** [comment]
Comment just to keep the issue open.

**Comment by ChristoWolf** [comment]
Bump.

Is there an option that I am missing which would compzte a single version for the whole solution which would then get injected into each project?
For now I am manually doing this using the GitVersion CLI in my pipelines.
But it would also be nice to achieve this with the package.

**Comment by asbjornu** [comment]
@ChristoWolf, no such option exists. Running GitVersion once on the CLI for an entire repository is the recommended workaround.
