### ISSUE TITLE
Run docker image on read-only root filesystem [Improvement]

### ISSUE THREAD

**Issue by taylorjonl** [GitTools/GitVersion#2899]
I am trying to use this project in a Tekton pipeline to calculate the version number of our builds but my company requires all docker images to be ran as non-root(easy to solve here) and with the '--read-only' flag making the root filesystem read-only.  The current docker image does not support this and throws an exception.  You can test this with this command:
```
docker run --read-only -e COMPlus_EnableDiagnostics="0" -v "%CD%:/repo" gittools/gitversion:5.7.1-alpine.3.14-5.0 /repo
```
You will receive this error:
```
The system cannot open the device or file specified. : 'Global\gitversionrepo.git'
```

## Detailed Description
Simple request, make changes to support running the docker image with the '--read-only' flag.

**Comment by arturcic** [comment]
If you know how to do that please check this Dockerfile https://github.com/GitTools/GitVersion/blob/main/src/Docker/Dockerfile and you can submit a PR

**Comment by taylorjonl** [comment]
I forked the project and may dive in deeper in the future, for the moment I am just deleting the Mutex code to see if it runs correctly, since I am up against a deadline.

**Comment by taylorjonl** [comment]
It appears it is just the Mutex that was stopping it, at least for my use case.  This commit made it possible, the Mutex shouldn't be needed for my use case:
https://github.com/taylorjonl/GitVersion/commit/e3a96c48a90db7970764eb3bc7a566d19940bd45
When I find some spare time I will see if there is a more elegant solution, unless someone else has the desire or any inputs on a solution.
