### ISSUE TITLE
[Feature] Build with RollForward

### ISSUE THREAD

**Issue by matkoch** [GitTools/GitVersion#2907]
## Detailed Description

Building with `<RollForward>LatestMajor</RollForward>` would allow dropping all TFMs except the most minimum. Smaller file, no future updates required for the sole purpose of SDK support.

## Context

https://twitter.com/JonathanPeppers/status/1454141297544081409
https://twitter.com/RobertMircea/status/1457780352911507465

## Possible Implementation

Set the property.

**Comment by arturcic** [comment]
That is something to consider indeed. I will have a look.

**Comment by arturcic** [comment]
It was added long time ago
