### ISSUE TITLE
Crash when running inside Github Action

### ISSUE THREAD

**Issue by oliverw** [GitTools/GitVersion#2918]
**Describe the bug**

Github Action crashes during Build phase.

**Details**: https://github.com/coinfoundry/miningcore/runs/4203661713?check_suite_focus=true

## Expected Behavior

Build should succeed.

## Actual Behavior

Github Action crashes during Build phase with a `NullReferenceException: Object reference not set to an instance of an object.`

## Your Environment

Github Action with .NET 6 project.

- Version Used: 5.8
- Operating System and version (Windows 10, Ubuntu 18.04): Unknown
- Link to your project: https://github.com/coinfoundry/miningcore
- Link to your CI build (if appropriate): https://github.com/coinfoundry/miningcore/runs/4203661713?check_suite_focus=true

**Comment by arturcic** [comment]
I think you need to add include the git history for the tool to work correctly
See an example here https://github.com/GitTools/GitVersion/blob/1b52a39530df22946a187417b10f351d838cc112/.github/workflows/ci.yml#L72

**Comment by oliverw** [comment]
> I think you need to add include the git history for the tool to work correctly See an example here
> 
> https://github.com/GitTools/GitVersion/blob/1b52a39530df22946a187417b10f351d838cc112/.github/workflows/ci.yml#L72-L75

Correct. Thanks for pointing this out. Closing.
