### ISSUE TITLE
[Bug]Failed to try and guess branch to use. Move one of the branches along a commit to remove warning

### ISSUE THREAD

**Issue by jhy871167495** [GitTools/GitVersion#2927]
**Describe the bug**
when build a tag commit on a jenkins agent, it failed and report 
"[2021-11-29 16:47:39]     WARN [11/29/21 16:47:39:51] An error occurred:
[2021-11-29 16:47:39]   Failed to try and guess branch to use. Move one of the branches along a commit to remove warning"

## Expected Behavior
build success

## Actual Behavior
build failed

## Possible Fix
if current commit tagged, not throw a excpetion. 
https://github.com/GitTools/GitVersion/blob/b6d803b9979c913209ebdaf57dcd225e887cb95c/src/GitVersion.Core/Core/GitPreparer.cs#L250

## Steps to Reproduce
1. add a  Environment Variable in Windows "JENKINS_URL"  in Windows, act as a jenkins agent
2. open a powershell and execute:
`mkdir gitversionErrorTest
cd gitversionErrorTest
git init
git.exe config remote.origin.url https://github.com/jhy871167495/GitVersionBuildFail.git # timeout=10
git.exe fetch --tags --force --progress -- https://github.com/jhy871167495/GitVersionBuildFail.git +refs/heads/*:refs/remotes/origin/* +refs/merge/*:refs/remotes/origin/merge/*
git.exe rev-parse "b309af2d6845182e643eb60ee06ebe9aecf8425e^{commit}" # timeout=10
git.exe config core.sparsecheckout # timeout=10
git.exe checkout -f b309af2d6845182e643eb60ee06ebe9aecf8425e
dotnet-gitversion ".\src\TcWinApp" -output file -outputfile src\TcWinApp\obj\gitversion.json`

## Context
CI failed after tag

## Your Environment
![企业微信截图_16382739727145](https://user-images.githubusercontent.com/3050754/144044688-0b8bf656-0476-4ff6-9218-577ef07e1e34.png)

- Version Used:
- GitVersion Version 5.7.0

**Comment by asbjornu** [comment]
[GitVersion's requirements state](https://gitversion.net/docs/reference/requirements):

> The repository should be switched to a named, existing branch pointing to the commit being built (i.e. no detached HEAD).

**Comment by jhy871167495** [comment]
> [GitVersion's requirements state](https://gitversion.net/docs/reference/requirements):
> 
> > The repository should be switched to a named, existing branch pointing to the commit being built (i.e. no detached HEAD).

I know the requirements. But it isn't always fail when in detached HEAD. In some detached condition, GitVersion will help switch to the right branch. It switches to main branch (if the main branch's HEAD equals the commit) or proper branch (if found only one  branch which name without separator). 
The problem occurs when 
when 1.  **Build on Jenkins agent**
and 2.  Detached HEAD
and 3.  Have more than one branch with the HEAD equals the building commit
and 4.  Have no branch without separator('/', '-')

**If I don't build on a Jenkins agent, git version will run success.** So I think It is an accidental bug. It often interrupts our CI workflow. 

In my situation, The commit is tagged, I think the semanticVersion is definite. Throwing exception is pointless
Switching to any proper branch or staying detached HEAD is acceptable.

**Comment by asbjornu** [comment]
I don't use Jenkins myself and have no use for building detached HEADs, but if you figure out a way to solve this (with tests), I'd be happy to merge a PR.

**Comment by jhy871167495** [comment]
> I don't use Jenkins myself and have no use for building detached HEADs, but if you figure out a way to solve this (with tests), I'd be happy to merge a PR.

@asbjornu Please review #2933.
