### ISSUE TITLE
Improve Documentation

### ISSUE THREAD

**Issue by gep13** [GitTools/GitVersion#293]
Yes, I know that no-one likes doing it, but I think we all agree that it needs doing.

I have been giving some thought to how I am going to be doing the documentation for ChocolateyGUI, and I am thinking that I am going to use this: https://readthedocs.org/

I first saw it being used on this project: https://github.com/cake-build/cake and you can see what it looks like here:  http://cake.readthedocs.org/en/latest/

Things I like about it:

* ties into existing documentation that we already have
* is fully searchable
* you can tag a "version" of the documentation that matches to a release of the product

Thoughts?  Could we use this for GitVersion as well?

**Comment by JakeGinnivan** [comment]
I have started using readme.io for this.

See shouldlys docs at http://docs.shouldly-lib.net/

**Comment by JakeGinnivan** [comment]
I have started this at #502

Interestingly enough, cake has moved to this approach. And must build their gh-pages docs from that folder. https://github.com/cake-build/website/blob/develop/src/Cake.Web/App_Data/docs/fundamentals/tasks.md

**Comment by JakeGinnivan** [comment]
Actually, cake doesn't have a different website. But I think we could build that

**Comment by JakeGinnivan** [comment]
Closing this, have new tasks and have made a decent start on this
