### ISSUE TITLE
[Improvement] Configuration Options for Nuget Version schema

### ISSUE THREAD

**Issue by PeterESoft** [GitTools/GitVersion#2931]
I am very happy with the options to configure the File/Assembly versions with GitVersion. But I have found no options to configure the NuGet Version. 

## Detailed Description
I'm using MSBuild 16.0 and NuGet.Build.Tasks.Pack 5.11. Variables "AssemblySemVer" and "AssemblySemFileVer" are as expected but variable "NuGetVersion" is either 3 parts or is a pre-release.

My usecase is that the NuGet Version shall be the same as the file version, which has 4 parts in my case (assembly-file-versioning-scheme: MajorMinorPatchTag). But I was not able to get a 4 part version for the NuGetVersion without having a prerelease tag. But I want to have a unique NuGet Version that is not a prerelease version.

## Context
My Company uses NuGet packages for internal exchange and the version schema is always 4 parts. So its maybe not the standard way of handling versioning including prerelease packages. For us it would make things much easier when the NuGet version can be configurable like the FileVersions.

## Possible Implementation
Have the same options for NuGet Version like for Assembly File (e.g. "assembly-file-versioning-scheme", "assembly-informational-format") or be able to specify which variable shall be used for NuGet Package Version.

**Comment by asbjornu** [comment]
`AssemblySemVer`, `AssemblySemFileVer` and `InformationalVersion` on one hand and `NuGetVersion` on the other has very different uses. The former comply with Microsoft's [`System.Version` class](https://docs.microsoft.com/en-us/dotnet/api/system.version), which "Represents the version number of an assembly, operating system, or the common language runtime" while the latter is complies with the versioning scheme of [NuGet](https://www.nuget.org/), which is [Semantic Versioning 2.0](https://semver.org/).

These versioning schemes are not interchangeable and serve different purposes. However, if you want to create your own version number you can combine any of the available [version variables](https://gitversion.net/docs/reference/variables)  to create a new, four-part version number as an environment variable in your build pipeline.

**Comment by PeterESoft** [comment]
I tried to override "PackageVersion" variable, but always the GitVersion NuGetVersion is taken.
msbuild.exe /t:pack /p:PackageVersion="1.2.3.4" $(solution)

I was not able to find another property/variable that can be set that overwrites the GitVersion NuGetVersion or that the Build-Task "pack" uses my self-defined variable.

**Comment by asbjornu** [comment]
Great! If you'd like to write up your solution, it would be a good addition to our documentation. So a PR would be appreciated. 🙏🏼

**Comment by PeterESoft** [comment]
I do not have a Solution. I am not even sure if it is more an issue of GiVersion or the NuGet.Build.Tasks.Pack.

**Comment by asbjornu** [comment]
Sorry, I did not read the "not" in "I was not able to find another property/variable" and thought you had found a solution.

**Comment by fowl2** [comment]
Just ran into this problem today - I would also be interested in a solution, either/both:

1. Allow overriding the `<PackageVersion>` in the project file.
1. Allow overriding the `NuGetVersion` in the configuration, eg. adding `nuget-versioning-scheme`/`nuget-assembly-versioning-scheme`/`nuget-versioning format`.

**Comment by PeterESoft** [comment]
@fowl2 My current solution is to adapt the MSBuild Variable during the build with a target:
```
<Target Name="AdaptNugetVersion" AfterTargets="GetVersion">
  <PropertyGroup>
    <PackageVersion>$(GitVersion_AssemblySemVer)+$(GitVersion_EscapedBranchName)-$(GitVersion_ShortSha)</PackageVersion>
  </PropertyGroup>
</Target>
```
