### ISSUE TITLE
Gitversion task in Azure DevOps warning about the Node6 deprecation. 

### ISSUE THREAD

**Issue by syamrag** [GitTools/GitVersion#2932]
I am using gitversoin task in azure pipeline and I am started getting warning about Node6 deprecation.

I am using the following gitversion task

- task: UseGitVersion@5
  displayName: gitversion
  inputs:
    versionSpec: ${{parameters.gitVersionVersion}}
    configFilePath: ${{parameters.gitVersionConfigFilePath}} 

The below is the warning I am getting.

`
**##[warning]This task uses Node 6 execution handler, which will be removed March 31st 2022. If you are the developer of the task - please consider the migration guideline to Node 10 handler - https://aka.ms/migrateTaskNode10 (check this page also if you would like to disable Node 6 deprecation warnings). If you are the user - feel free to reach out to the owners of this task to proceed on migration.*`*

I am very much concerned about this because Azure will stop supporting Node6 after March 31st 2022 and lot of my projects are depends on the gitversion task. Do you have any plan to update the Gitversion task from Node 6 to Node 10 before 31st march 2022?

**Comment by arturcic** [comment]
@syamrag UseGitVersion was deprecated please use https://marketplace.visualstudio.com/items?itemName=gittools.gittools instead as it's the only one supported
