### ISSUE TITLE
[Docs] What does IGNORE_NORMALISATION_GIT_HEAD_MOVE do? Is it safe to always set it to 1?

### ISSUE THREAD

**Issue by CAP-3Shape** [GitTools/GitVersion#2934]
I have a C# code base that uses GitVersion.MsBuild. Sometimes my Jenkins build server gives me this error:

    GitVersion.BugException: GitVersion has a bug, your HEAD has moved after repo normalisation.
    To disable this error set an environmental variable called IGNORE_NORMALISATION_GIT_HEAD_MOVE to 1

This often happens when building a feature branch that is not based on the latest master (i.e., master has moved since the feature branch was made). 

The error message describes a suggested fix/workaround, but I am hesitant to do this because I don't know what environmental variable IGNORE_NORMALISATION_GIT_HEAD_MOVE _does_, and I cannot find a description of it anywhere. 

If I set IGNORE_NORMALISATION_GIT_HEAD_MOVE to 1, what side effects does this have? Does it do _anything_ other than suppress the above error/warning? Is it safe to always set it to 1?

Thanks in advance!

**Comment by asbjornu** [comment]
The environment variable `IGNORE_NORMALISATION_GIT_HEAD_MOVE` is only used as a flag to not throw the `BugException` you encountered, here:

https://github.com/GitTools/GitVersion/blob/661c8c8d33786e584c5399bf38ef423e5e6cb1a2/src/GitVersion.Core/Core/GitPreparer.cs#L267-L278

It would be great to have this and other environment variables GitVersion supports (both for configuration and as output) in [the documentation](https://gitversion.net/). I'm thinking a new page à la [version variables](https://gitversion.net/docs/reference/variables). What do you think? Would you be up for writing a PR for this?

**Comment by CAP-3Shape** [comment]
Thanks for the response.

> Would you be up for writing a PR for this?

I tried to write a first draft of such a document, but apparently I do not have permission to push feature branches.

**Comment by asbjornu** [comment]
@CAP-3Shape, you will have to [create a pull request from a fork](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork).
