### ISSUE TITLE
Gitversion tag issue

### ISSUE THREAD

**Issue by sdobhal369** [GitTools/GitVersion#2954]
Gitversion showing old tags which are in my Github repo. It is not able to show the latest tag from my github. I am using gitversion in my Ubuntu 20.10 terminal. I am using latest gitversion release 5.8.1.
![Screenshot from 2022-01-04 15-30-27](https://user-images.githubusercontent.com/89004127/148042416-1370f29d-d87c-4b31-afb4-806a325ded0f.png)
![Screenshot from 2022-01-04 15-31-00](https://user-images.githubusercontent.com/89004127/148042438-905ddda2-00d7-411c-98a0-71deb7778875.png)

**Comment by asbjornu** [comment]
The commit https://github.com/nxdevops/react-native-calendars/commit/7b3aa0a1c8638d1e1fc533a89067afa6876f17cd is tagged with `2.0.0` while the following commit https://github.com/nxdevops/react-native-calendars/commit/de0ddf688843bc5cc6bc2bb3659e6bab3e129ff2 has the commit message `+semver: major`. A major increment of `2.0.0` yields `3.0.0`. 

If you do `git reset --hard 7b3aa0a1c8638d1e1fc533a89067afa6876f17cd` and then execute `gitversion`, GitVersion will produce version `2.0.0` as expected.

**Comment by sdobhal369** [comment]
Thanks for the help mate! I will check it.
