### ISSUE TITLE
[Docs] Fix remark-lint warnings in .md files

### ISSUE THREAD

**Issue by arturcic** [GitTools/GitVersion#2964]
Check this https://github.com/GitTools/GitVersion/runs/4803368038?check_suite_focus=true  for the list of warnings

**Comment by arturcic** [comment]
Closed by #3246

**Comment by Osei-b4** [comment]
hello please i  am having a problem `
README.md:14:5 MD051/link-fragments Link fragments should be valid [Context: "[Developing Your Solutions](#developing-your-solution)"]
retrospective.md:47:81 MD013/line-length Line length [Expected: 80; Actual: 84]`
