### ISSUE TITLE
[Bug]  -output file -outputfile gitversion.json exited with code 1.

### ISSUE THREAD

**Issue by ucapbba** [GitTools/GitVersion#2993]
## Description of issue
I have added GitVersion.MsBuild.5.8.1to my GUI.csproj (contained in a Visual Studio 2017 solution with many projects).   My  .yml contains the line  run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}
which is run after push.  Having added GitVersion I see (full paths reduced):

       "D:\a\GUI\GUI.csproj" (default target) (2) ->
       (RunGitVersion target) -> 
         D:\a\packages\GitVersion.MsBuild.5.8.1\tools\GitVersion.MsBuild.targets(9,9): error MSB3073: The command ""D:\a\packages\GitVersion.MsBuild.5.8.1\tools\net48/gitversion.exe" "D:\a\GUI" -output file -outputfile gitversion.json" exited with code 1. [D:\a\GUI\GUI.csproj]

## Analysis
The line where error occurs in GitVersion.MsBuild.target is

Exec Command="$(GitVersionFileExe) &quot;$(MSBuildProjectDirectory)&quot; $(GitVersion_ToolArgments)" 

I add my gitversion.json which appeared in my project folder after local build (I also tried adding to source control but I guess not required) , and my msbuild.yml and GUI.csproj used here:

[gitversion - Copy.json.txt](https://github.com/GitTools/GitVersion/files/8053284/gitversion.-.Copy.json.txt)
[msbuild - Copy.yml.txt](https://github.com/GitTools/GitVersion/files/8053285/msbuild.-.Copy.yml.txt)
[GUI - Copy.csproj.txt](https://github.com/GitTools/GitVersion/files/8053293/GUI.-.Copy.csproj.txt)

## Context
This is the first time I have used GitVersion.  I installed using NuGet package and removed AssemblyInfo.cs from the .csproj.  The repository is private, if useful I can add a user to assist.  

I have been following here to try to understand the issue 
https://gitversion.net/docs/usage/msbuild

## Your Environment
VS 2017 / Net 4.8 / Windows 10 / GitVersion.MsBuild.5.8.1

Thankyou

**Comment by asbjornu** [comment]
Can you please try [the command line](https://gitversion.net/docs/usage/cli/) instead? If it too fails, it may be easier to figure out why.

**Comment by ucapbba** [comment]
running dotnet-gitversion from my .git location I get 
![image](https://user-images.githubusercontent.com/87702063/154730946-0f0ceb03-cce4-4b64-a37d-18c381928d51.png)
which looks reasonable

**Comment by asbjornu** [comment]
Yeah, looks like GitVersion itself is working fine. If there's something wrong with `msbuild.yml`, that's out of scope for GitVersion, sorry.

**Comment by ucapbba** [comment]
Perhaps it's related to this case :
https://github.com/GitTools/GitVersion/issues/2534

the slash seems to be the wrong way before gitversion.exe \net48/gitversion.exe so perhaps the error is due to not being able to find GitVersion.exe in the GitAction

**Comment by ucapbba** [comment]
I have replicated the case with a simple test project 
https://github.com/ucapbba/CodeSamples/tree/main/GitAction
It uses the default MSBuild git action - you can see exactly what has been done and replicate the error with a push

**Comment by asbjornu** [comment]
@ucapbba, for GitVersion to execute successfully, it needs the full repository history. By default, `actions/checkout` does a shallow clone. Add the following to the workflow and it should at least be able to execute:

```yaml
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
```

[This requirement is documented](https://github.com/GitTools/actions/blob/main/docs/examples/github/gitversion/execute/usage-examples.md).
