### ISSUE TITLE
[BREAKING CHANGE] Sunset support for .NET Framework 4.8

### ISSUE THREAD

**Issue by arturcic** [GitTools/GitVersion#2997]
As agreed with the team support for .NET Framework 4.8 will be removed as part of the version 6.x meaning the latest version to support .net48 will be 5.x versions.

**Comment by fowl2** [comment]
> 🎉 This issue has been resolved in version 6.0.0 🎉 The release is available on:

I don't think this is true. Also I'd like to confirm this doesn't remove support for using the MSBuild tasks in modern projects that multitarget .NET Framework, because if it does drop support for these, it should really be called out in the release notes :)
