### ISSUE TITLE
[Bug] Detached head in Docker Container

### ISSUE THREAD

**Issue by MeikelLP** [GitTools/GitVersion#3004]
**Describe the bug**
When I try to build my app into a (windows) container via Dockerfile I get the following error from Gitversion.MsBuild:

```
It looks like the branch being examined is a detached Head pointing to commit '5d0a036'. Without a proper branch name GitVersion cannot determine the build version.
```

I tried to set the `Git_Branch`, `GIT_BRANCH` and `BUILD_SOURCEBRANCH` environment variable but nothing helps. I'm using Azure Devops. All commits in my docker pipeline fail while all commits in my non-docker pipeline succeed. The build (should be/) is identical as the both just call `dotnet build` but somehow in the Docker container it says it's a detached head but the "native" build works fine.

## Expected Behavior
Dockerfile build should work the same as a native build.

## Actual Behavior
`dotnet build` with `GitVersion.MsBuild` in  a Dockerfile fails

## Context
This prevents us from packing our app into a docker image.

## Your Environment
- Version Used: 5.8.2
- Operating System and version (Windows 10, Ubuntu 18.04): Windows 10
- Link to your project:
- Link to your CI build (if appropriate):

**Comment by asbjornu** [comment]
If you're using AzDO, can't you use the official [AzDO GitTools Task](https://marketplace.visualstudio.com/items?itemName=gittools.gittools)?

**Comment by MeikelLP** [comment]
Yes that did resolve my problem because it runs on the agent/host and not in the container.
