### ISSUE TITLE
SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by niko124a** [GitTools/GitVersion#3007]
I have been trying to setup GitTools in my azure devops pipeline, but I keep getting this syntax error.

The error occurs the **gitversion/execute@0** task.

This is my pipeline tasks: 
- task: gitversion/setup@0
  displayName: 'Install GitVersion'
  inputs:
    versionSpec: '5.x'
- task: gitversion/execute@0
  displayName: 'Determine Version'
  inputs:
    useConfigFile: true
    configFilePath: 'GitVersion.yml'

And this is my config file:

branches:
feature:
    regex: features?[/-]
    mode: ContinuousDelivery
    tag: alpha.{BranchName}
  develop:
    regex: dev(elop)?(ment)?$
    mode: ContinuousDelivery
    tag: alpha
  release:
    regex: releases?[/-]
    mode: ContinuousDelivery
    tag: beta
  hotfix:
    regex: hotfix(es)?[/-]
    mode: ContinuousDelivery
    tag: beta
  master:
    mode: ContinuousDeployment

**Comment by redtaped** [comment]
Can you share what the cause/solution was?

**Comment by KungFuCookie** [comment]
same issue appearing suddenly for me today

**Comment by arturcic** [comment]
I would recommend to pin the version number always to avoid this type of 'surprises'. So for now I would recommend to pin to version 5.9.0 and when we find some time/will have more details, we will fix this issue.

**Comment by KungFuCookie** [comment]
done, and thanks for speedy response
