### ISSUE TITLE
[Bug] GitVersion.Portable chocolatey 5.8.2 dll missing

### ISSUE THREAD

**Issue by Dunge** [GitTools/GitVersion#3017]
Updated from 5.7.0 to 5.8.2 using chocolatey and now I receive the error message

> The program can't start because api-ms-win-core-winrt-l1-1-0.dll is missing from your computer. Try reinstalling the program to fix this problem.

I know this dll is part of the .NET runtimes, but I already have 3.1.3, 5.0.0 and 6.0.2 installed. Anyone know which one it was built with?
Also quite strange because that's not usually the message that is shown when the runtime is not installed.

**Comment by arturcic** [comment]
Please use version 5.12.0
