### ISSUE TITLE
[Bug] Azure Pipelines stop working with GitVersion

### ISSUE THREAD

**Issue by sparkitny** [GitTools/GitVersion#3019]
**Describe the bug**
Starting from 27.02.2022 the GitVersion task in the pipelines produces the following error

'Microsoft.NETCore.App', version '2.1.0' was not found.

 The following frameworks were found:
      3.1.4 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      3.1.6 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      3.1.20 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      3.1.22 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      5.0.4 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      5.0.9 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      5.0.14 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

You can resolve the problem by installing the specified framework and/or SDK.

The specified framework can be found at:
  - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=2.1.0&arch=x64&rid=win10-x64
##[error]Error: The process 'C:\Program Files\dotnet\dotnet.exe' failed with exit code 2147516566

**Comment by arturcic** [comment]
Please use https://marketplace.visualstudio.com/items?itemName=gittools.gittools instead. The one you're using is deprecated.
Docs: https://github.com/GitTools/actions/blob/main/docs/examples/azure/gitversion/index.md

**Comment by sparkitny** [comment]
Hi arturcic,

thx for the hint. Didn't know that.
