### ISSUE TITLE
[Feature] Set fallback version

### ISSUE THREAD

**Issue by Michenux** [GitTools/GitVersion#3065]
I would like to be able to configure the fallback version (0.1.0) in the GitVersion.yml 
to specify the first version when there is no tag on the git repository. 
In my use case, i want the first version to be 1.0.0.

**Comment by HHobeck** [comment]
The only reason why you have the fallback version in the code is that at least one version will be returned. Of course it is quite unintentionally that this version is 0.1.0. It should be 0.0.0 with should increment true IMO. If you want the first version number in your project 1.0.0 then you should define this as next-version. Exactly for that purpose the next version configuration is there.
