### ISSUE TITLE
New tag is ignored if the older +semver: suggests higher version

### ISSUE THREAD

**Issue by patrikbeno** [GitTools/GitVersion#3071]
**Describe the bug**
Series of `+semver:` commit messages bumps version up to next major, e.g. `2.0.0`.
Explicit tag says `1.1.0`.
Next commit still suggests `2.0.0`

![image](https://user-images.githubusercontent.com/2464234/162560958-ff4c63a5-3223-4c32-8503-5578eff1474f.png)

## Expected Behavior
Explicit tag should take priority over the messages in commit history.
Tag should reset the calculation of the version from message history before the tag.
Latest tag should be considered new baseline, and only messages in commit history following the tag should be considered.

## Actual Behavior
Tag is ignored completely, and `+semver:` commit history wins.

## Possible Fix
Ignore commit history before the tag.

## Steps to Reproduce
```
$ git log --oneline
9514c9e (HEAD -> main)  #(2.0.0+7)
d749b10 +semver: none #(2.0.0+6)
6d6eace (tag: 1.1.0) +semver: fix #(2.0.0+5)
a0b2e0e +semver: feature #(2.0.0+4)
77f5a4a +semver: major #(2.0.0+3)
842d1ce +semver: feature #(1.1.0+2)
8ca3e12 +semver: fix #(1.0.1+1)
9f90368 (tag: 1.0.0) initial
```

## Context
Message in commit history suggested bumping the major version.
This is later considered as mistake.
History is written, and its rewrite is not possible.
Explicit tag is used to reset/baseline the automated version calculation.

## Your Environment
Windows 10
GitVersion 5.9.0

**Comment by patrikbeno** [comment]
Another view:
```
[main (root-commit) f0e3c9b] initial
tagging: 1.0.0
[main bb045e8] +semver: fix
1.0.1+1
[main 1a1d875] +semver: feature
1.1.0+2
[main 261a0c0] +semver: major
2.0.0+3
[main 99523f7] +semver: feature
2.0.0+4
[main 68077bf] +semver: fix
2.0.0+5
tagging: 1.1.0
[main b65ddac] +semver: none
2.0.0+6
[main ea21499] 
2.0.0+7
DONE
```

**Comment by asbjornu** [comment]
It is by design that the highest possible version number will be used, not the latest.

**Comment by patrikbeno** [comment]
> It is by design that the highest possible version number will be used, not the latest.

Yes, but this applies to conflict resolution, when there are mutliple possible version candidates.

However, if there is one single specific `1.1.0` tag on a current commit, it used despite the fact that commit history suggests `2.0.0` version. That's because there is no conflict.

Now, adding a simple `+semver: none` commit bumps version to `2.0.0`. 

Why? This behavior is not only inconsistent, it also does not make any sense.

**Comment by asbjornu** [comment]
I agree this doesn't make much sense. Since the change in behavior around this can be seen as a breaking change, we may want to change this in `main` rather than in `support/5.x`. It can also be seen as a bugfix that can be applied directly to `support/5.x`. Thoughts? Also, would you be up for providing a PR that changes this behavior?

**Comment by rcdailey** [comment]
I'm using v5.10.3 and I do not believe this is fixed. I'll explain my use case here to first make sure I am facing the same problem.

Here is my `GitVersion.yml`:

```yml
mode: MainLine
major-version-bump-message: "^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test)(\\([\\w\\s-]*\\))?(!:|:.*\\n\\n((.+\\n)+\\n)?BREAKING CHANGE:\\s.+)"
minor-version-bump-message: "^(feat)(\\([\\w\\s-]*\\))?:"
patch-version-bump-message: "^(build|chore|ci|docs|fix|perf|refactor|revert|style|test)(\\([\\w\\s-]*\\))?:"
```

And the git log:

![image](https://user-images.githubusercontent.com/1768054/200068324-21441e96-d34a-4102-a4d1-025acf3dd9fc.png)

When I run `gitversion` I expect version `0.1.1`, but instead I get `1.0.3`. It appears that it continues to count commits *before* the tagged commit, which I wasn't expecting (or wanting) it to do.

Here are the logs of `gitversion /diag`:

```txt
INFO [11/04/22 14:51:00:18] Working directory: C:\code\Monitor.Deployment\src\Monitor.Deployment.Client
INFO [11/04/22 14:51:00:20] Project root is: C:\code\Monitor.Deployment\
INFO [11/04/22 14:51:00:20] DotGit directory is: C:\code\Monitor.Deployment\.git
INFO [11/04/22 14:51:00:20] Branch from build environment:
INFO [11/04/22 14:51:00:23] Using latest commit on specified branch
INFO [11/04/22 14:51:00:36] Running against branch: master (e17b7c2 Merged PR 7712: GitVersion support)
INFO [11/04/22 14:51:00:36] Begin: Calculating base versions
  INFO [11/04/22 14:51:00:38] Fallback base version: 0.1.0 with commit count source 087d75f8e55d5fdea1f0e20d9c8151da447729a6
  INFO [11/04/22 14:51:00:44] Git tag 'v0.1.0': 0.1.0 with commit count source 97d8e2916675f062b56e586a9139f957156d9cc4
  INFO [11/04/22 14:51:00:49] Found multiple base versions which will produce the same SemVer (0.1.1), taking oldest source for commit counting (Fallback base version)
  INFO [11/04/22 14:51:00:49] Base version used: Fallback base version: 0.1.0 with commit count source 087d75f8e55d5fdea1f0e20d9c8151da447729a6
  INFO [11/04/22 14:51:00:49] End: Calculating base versions (Took: 128.55ms)
  INFO [11/04/22 14:51:00:50] 38 commits found between 087d75f chore: gitattributes and gitignore and e17b7c2 Merged PR 7712: GitVersion support
  INFO [11/04/22 14:51:00:50] Begin: Using mainline development mode to calculate current version
    INFO [11/04/22 14:51:00:51] '^master$|^main$' does not match 'dev/rcd/api-key-auth'.
    INFO [11/04/22 14:51:00:51] '^support[/-]' does not match 'dev/rcd/api-key-auth'.
    INFO [11/04/22 14:51:00:51] '^master$|^main$' does not match 'dev/rcd/client-library'.
    INFO [11/04/22 14:51:00:51] '^support[/-]' does not match 'dev/rcd/client-library'.
    INFO [11/04/22 14:51:00:51] '^master$|^main$' matches 'master'.
    INFO [11/04/22 14:51:00:52] Found merge base e17b7c29f297ada956dfedd9d2cde2c2c03b07a4 for 'master'.
    INFO [11/04/22 14:51:00:52] '^master$|^main$' does not match 'HEAD'.
    INFO [11/04/22 14:51:00:53] '^support[/-]' does not match 'HEAD'.
    INFO [11/04/22 14:51:00:53] '^master$|^main$' matches 'master'.
    INFO [11/04/22 14:51:00:53] Found merge base e17b7c29f297ada956dfedd9d2cde2c2c03b07a4 for 'origin/master'.
    INFO [11/04/22 14:51:00:53] Found possible mainline branches: master, origin/master
    INFO [11/04/22 14:51:00:54] Choosing master as mainline because it is the current branch
    INFO [11/04/22 14:51:00:55] Direct commit on main 7d411e5 refactor: Initial Web API project incremented base versions Patch, now 0.1.1
    INFO [11/04/22 14:51:00:55] Merge commit 0474f35 Merged PR 7610: Some fixups to the initial project incremented base versions Patch, now 0.1.2
    INFO [11/04/22 14:51:00:55] Merge commit f7ce387 Merged PR 7621: refactor: Move service registration into CompositionRoot class incremented base versions Patch, now 0.1.3
    INFO [11/04/22 14:51:00:55] Merge commit 551c6c4 Merged PR 7627: build: Actually enable central package management incremented base versions Patch, now 0.1.4
    INFO [11/04/22 14:51:00:55] Merge commit 0daf62d Merged PR 7630: Repo checklist items incremented base versions Patch, now 0.1.5
    INFO [11/04/22 14:51:00:56] Merge commit 90d529e Merged PR 7632: Pipeline + skeleton for unit tests incremented base versions Patch, now 0.1.6
    INFO [11/04/22 14:51:00:56] Merge commit 65a483b Merged PR 7641: Code style change, UTF-8 adjustments, URL format change incremented base versions Major, now 1.0.0
    INFO [11/04/22 14:51:00:56] Merge commit 1769ba1 Merged PR 7674: Docker support incremented base versions Patch, now 1.0.1
    INFO [11/04/22 14:51:00:56] Merge commit 97d8e29 Merged PR 7694: ci: Fix inconsistent architecture for docker build incremented base versions Patch, now 1.0.2
    INFO [11/04/22 14:51:00:56] Merge commit e17b7c2 Merged PR 7712: GitVersion support incremented base versions Patch, now 1.0.3
    INFO [11/04/22 14:51:00:57] 38 commits found between 087d75f chore: gitattributes and gitignore and e17b7c2 Merged PR 7712: GitVersion support
  INFO [11/04/22 14:51:00:57] End: Using mainline development mode to calculate current version (Took: 70.11ms)
```

Of particular interest is this bit:

```txt
Fallback base version: 0.1.0 with commit count source 087d75f8e55d5fdea1f0e20d9c8151da447729a6
Git tag 'v0.1.0': 0.1.0 with commit count source 97d8e2916675f062b56e586a9139f957156d9cc4
Found multiple base versions which will produce the same SemVer (0.1.1), taking oldest source for commit counting (Fallback base version)
```

Isn't the fix here supposed to prevent it from choosing the root commit on the branch as a search target? Shouldn't it only consider the tag which is `v0.1.0`?

**Comment by gbtb** [comment]
> I agree this doesn't make much sense. Since the change in behavior around this can be seen as a breaking change, we may want to change this in `main` rather than in `support/5.x`. It can also be seen as a bugfix that can be applied directly to `support/5.x`. Thoughts? Also, would you be up for providing a PR that changes this behavior?

That was indeed a breaking change for us :smiling_face_with_tear:  Upgraded from 5.9 to 5.12 and suddenly version calculation skyrocketed from 2 seconds to 39. I've bisected it to 5.10.1 - 5.10.2 update, and thankfully diff was small. 
`commit-message-incrementing: Disabled` fixed the problem. I guess it happened because we haven't use commit message incrementing at all, and because of that it started to scan whole repo history.

**Comment by asbjornu** [comment]
@gbtb, I'm glad you figured out a fix and thankful that you reported it back here. 🙏🏼

**Comment by luka-grabarevic** [comment]
You guys sure this behavior is as intended? I've pinned down our sudden versioning issues to this PR #3078.

We have a tag v4.11.0 which was our last release.
We have a tag v4.12.0-beta.1 which is our new beta release.

Previously to this change our builds on master/main produced this output:

```
INFO [10/16/23 13:04:26:59] Found multiple base versions which will produce the same SemVer (4.12.0), taking oldest source for commit counting (Git tag 'v4.11.0')
INFO [10/16/23 13:04:26:59] Base version used: Git tag 'v4.11.0': 4.11.0 with commit count source 824f70807c7f3711b99aa6e8a80416155f3260ac
```

now this comes out:

```
INFO [10/16/23 13:03:26:98] Found multiple base versions which will produce the same SemVer (4.12.0-beta.2), taking oldest source for commit counting (Git tag 'v4.12.0-beta.1')
INFO [10/16/23 13:03:26:98] Base version used: Git tag 'v4.12.0-beta.1': 4.12.0-beta.1 with commit count source c986cb959b7df6606a59c4c62eea993ac270cdaa
```

For the release/4.12.0 branch the second behavior is correct, but not for a master/main build.
