### ISSUE TITLE
[Bug] "It was not possible to find any compatible framework version" on Azure pipeline (.net core 6)

### ISSUE THREAD

**Issue by arp-mbender** [GitTools/GitVersion#3072]
**Describe the bug**
Adding GitVersion task to a simple Azure Pipeline for a .NET core 6.0 project produces the error "It was not possible to find any compatible framework version"

## Expected Behavior
GitVersion should work fine?

## Actual Behavior
Output from Azure pipeline:
```
It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '2.1.0' (x64) was not found.
  - The following frameworks were found:
      3.1.4 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      3.1.6 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      3.1.20 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      3.1.22 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      3.1.23 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      5.0.4 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      5.0.9 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      5.0.14 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      5.0.15 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      6.0.3 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
```

## Steps to Reproduce
Create a simple .net core 6 project; create an Azure pipeline which will build said project, and start the pipeline with
```
- task: GitVersion@5
  displayName: 'GitVersion'
  inputs:
    updateAssemblyInfo: true
    preferBundledVersion: false
```

## Context
Can't use the GitVersion pipeline task for new projects.

## Your Environment
Azure Devops Services

- Version Used:
Using a `windows-latest` vmImage in the pipeline, and the `@5` version of the GitVersion task.

**Comment by arturcic** [comment]
@arp-mbender, you are using a deprecated extension, please see the [Announcement](https://github.com/GitTools/GitVersion/discussions/3073)
