### ISSUE TITLE
[Bug] Gitversion fails in a submodule of a worktree

### ISSUE THREAD

**Issue by raphael-grimm** [GitTools/GitVersion#3076]
**Describe the bug**
Gitversion fails if invoked in a submodule of a worktree

## Expected Behavior
It should use the correct path from the submodules `.git` file

## Actual Behavior
It uses some other incorrect path (no idea where that one comes from).

## Possible Fix
Just use the path from the `.git` file.

## Steps to Reproduce
See https://github.com/raphael-grimm/mwe-gitversion-bug

## Context
How has this bug affected you? What were you trying to accomplish? Well, I tried to get a Version of a submodule...

## Your Environment

- Versions Used: 
   `GitVersion 5.7.0+Branch.main.Sha.8d177c6d666c8eeb1c6a6a2c71fd4b78741137d2` (dotnet-gitversion.exe)
  `GitVersion 5.8.1+Branch.main.Sha.5c21ee61e344c142c7d18342d0a8ac4422636569` (gitversion.exe)
- Operating System and version: Windows 10

**Comment by asbjornu** [comment]
Please see #2725. Git submodules aren't supported in GitVersion.
