### ISSUE TITLE
Change GitVersionInformation C# template ('const string' instead of 'static string')

### ISSUE THREAD

**Issue by kvasnevskiy** [GitTools/GitVersion#3095]
Similar request was already open #1376 and then closed. But I see that it's still `static string`. Can template be changed to `const string`? Because I want to use GitVersionInformation in attributes and value there should be constant,

**Comment by arturcic** [comment]
@kvasnevskiy  do you mind creating a PR for this? 
As a starting point here https://github.com/GitTools/GitVersion/blob/support/5.x/src/GitVersion.Core/VersionConverters/GitVersionInfo/AddFormats/GitVersionInformation.cs, You might need to update some of the tests as well

**Comment by kvasnevskiy** [comment]
@arturcic ok, I will create a PR for this.

**Comment by asbjornu** [comment]
As mentioned by @jbaehr in https://github.com/GitTools/GitVersion/issues/1376#issuecomment-412799435, the change from `static` to `const` is a breaking change. For more insight into the reflection side of things, please see https://github.com/GitTools/GitVersion/issues/895#issuecomment-226118785, the linked issues and the surrounding discussion.

**Comment by arturcic** [comment]
Closed by #3113
