### ISSUE TITLE
[Bug] Failing to detect branch when GitHub action is triggered from a comment on the pull request

### ISSUE THREAD

**Issue by abd3lraouf** [GitTools/GitVersion#3153]
**Describe the bug**
Failing to detect branch when GitHub action is triggered from a comment on the pull request

## Expected Behavior

It should detect the branch name of the pull request.

## Actual Behavior

it always says it's **develop** (the pr is from a feature branch into develop)

## Context
I tried to get the branch name manually, so if there is a way I can provide the correct branch name to gitversion.

## Your Environment

- Operating System and version (Windows 10, Ubuntu 18.04): ubuntu-latest
```yml
  - name: Determine Version
    uses: gittools/actions/gitversion/execute@v0.9.7
````

**Comment by asbjornu** [comment]
Have you tried providing the environment variable `Git_Branch`?

**Comment by abd3lraouf** [comment]
Unfortunately, this is not our case, we use it to trigger the workflow on the PR branch,

**Comment by asbjornu** [comment]
Ah, I see you're using GitHub Actions. I don't think `Git_Branch` should do anything to or from then. @arturcic, do you remember how `gitversion/execute` determines the branch name?

**Comment by arturcic** [comment]
The GitHub action as well as Azure DevOps task is just a wrapper for the global tool.

**Comment by asbjornu** [comment]
So the action does nothing to convey the information about which branch is being built to the global tool? If not, we should probably do that, somehow. 🤔

**Comment by asbjornu** [comment]
#3020 seems to contradict this, somehow?
