### ISSUE TITLE
[Bug] Inconsistency in specifying updateassemblyinfo and updateprojectfiles

### ISSUE THREAD

**Issue by christophwille** [GitTools/GitVersion#3155]
Version: GitVersion 5.10.3+Branch.support-5.x.Sha.bc9c9d003e655385e3dd1ba3bd013e04062d2f9b

```
dotnet-gitversion . /output buildserver /nofetch /updateassemblyinfo false /updateprojectfiles true
dotnet-gitversion . /output buildserver /nofetch /updateassemblyinfo true /updateprojectfiles false
```

First command runs and updates the project files, second command fails with "Cannot specify both updateassemblyinfo and updateprojectfiles in the same run. Please rerun GitVersion with only one parameter". I started with the first one (parameterized the booleans in the build script), and then stumbled onto the second one when I changed the boolean params around.

**Comment by asbjornu** [comment]
Is the bug here that GitVersion fails even though `false` is passed to one of the `/update…` parameters?

**Comment by asbjornu** [comment]
I'm not asking about the message, I'm wondering why you're considering it a bug.

**Comment by christophwille** [comment]
I pointed out that one combination fails, the other works. I would have expected both to fail.

**Comment by asbjornu** [comment]
Acknowledged! I agree that both should fail.
