### ISSUE TITLE
[Bug] The Target RunGitVersion does not exist in the project

### ISSUE THREAD

**Issue by cjmurph** [GitTools/GitVersion#3162]
**Describe the bug**
After installing GitVersion.MsBuild into a project, the project will no longer build, throwing the error:
The Target "RunGitVersion" does not exist in the project

The error is quite accurate, there is no target with that name in the project file.

## Expected Behavior
The documentation says install the library and it will start versioning my project...

## Actual Behavior
I can't build my project

## Possible Fix
Who knows

## Steps to Reproduce
Create a project, add the GitVersion.MsBuild library from nuget, try and build it

## Context
I can't build my project. I wanted it versioned by this library.

## Your Environment
VS2022, C# .net 6.0-windows project

- Version Used: 5.10.3
- Operating System and version (Windows 10, Ubuntu 18.04): Windows 11
- Link to your project: local

I'm aware this shouldn't be a bug report, I'm clearly doing something wrong, however I can't seem to find this error in any other reported issues. 
If I just add a target node named RunGitVersion to the project it complains about a missing gitversion.json, I never expected that to solve the issue obviously as I have no idea what that target node should contain. 
I honestly have no idea what is going on. I first saw this when I cloned a repo that included this library. 
Subsequently I tried to replicate the issue with other projects to see if it was something with the project I cloned (missing configuration file etc).
Any help pointing me at the obvious would be much appreciated.

**Comment by asbjornu** [comment]
> Subsequently I tried to replicate the issue with other projects to see if it was something with the project I cloned (missing configuration file etc).

Were you able to replicate the issue?

**Comment by cjmurph** [comment]
> > Subsequently I tried to replicate the issue with other projects to see if it was something with the project I cloned (missing configuration file etc).
> 
> Were you able to replicate the issue?

sorry, I didn't articulate that very well in my original post.

I get this error with every project I add the library to. I've tried making new projects of different types and it always gives me this error.

Yesterday I reinstalled VS2022, that didn't help. 

I haven't checked another dev machine, I will try that at a later stage. It won't answer my question though, as if theres somthing broken on this machine, I would like to fix it.

Does everyone with this library in their project have a task called RunGitVersion in their project file?

**Comment by asbjornu** [comment]
I don't use `GitVersion.MSBuild` anymore, so I'm not sure how it's supposed to work. It would be useful to know if you are able to reproduce this on another machine.

**Comment by cjmurph** [comment]
Ok, I found the problem. something was missing or corrupt in my package cache. I removed everything from the nuget package cache and restored, now it works. I was chasing the wrong thing as the error was telling me my project was missing some configuration.

**Comment by asbjornu** [comment]
I'm glad you figured it out @cjmurph!
