### ISSUE TITLE
[Bug] /updateprojectfiles and /output file command line arguments require specific order 

### ISSUE THREAD

**Issue by Rahkola** [GitTools/GitVersion#3185]
**Describe the bug**
When executing GitVersion from command line and speficying both /outputfile and /updateprojectfiles, the tool requires the command line arguments to be in specific order for the tool to work properly. Obviously the /output file argument is used here together with the /outputfile as instructed by documentation.

This command both produces the output file and updates project files:
`dotnet gitversion /output file /outputfile version.json /updateprojectfiles`

This command only updates project files:
`dotnet gitversion /updateprojectfiles /output file /outputfile version.json`

## Expected Behavior
Processing of the command line arguments is order/position agnostic and arguments can be used in any given order. Or alternatively if a specific order is required, this must be documented in the official documentation page at https://gitversion.net/docs/usage/cli/arguments.

## Actual Behavior
version.json output file is not created when executing command `dotnet gitversion /updateprojectfiles /output file /outputfile version.json` which per current documentation is completely valid .

## Proposed Fix
Cmd argument parsing is made order agnostic, or documenation is updated. 

## Your Environment

- Version Used:
- Win 11, Gitversion 5.10.3+Branch.support-5.x.Sha.bc9c9d003e655385e3dd1ba3bd013e04062d2f9b

**Comment by asbjornu** [comment]
We are aware of the fact that our command line parser has … room for improvement. 😅 See #2275.
