### ISSUE TITLE
[Bug] brew install gitversion; gitversion /version -> 1.0.0

### ISSUE THREAD

**Issue by Ashtonian** [GitTools/GitVersion#3201]
**Describe the bug**
I've installed gitversion on two instances of macos (Monterey, Big Sur) via `brew install gitversion`. Home brew reports its pouring cask `5.x` as expected, but when I run the `gitversion /version` it returns `1.0.0`. Using the binary from the github release section `gitversion /version` returns `5.x.x`. 

## Expected Behavior
The latest version of gitversion to be installed via homebrew and `gitversion /version` to be consistent and return the latest release. 

## Actual Behavior
Its installing version 1.0.0?

## Steps to Reproduce
```sh
# be on a mac
# have homebrew installed
brew install gitversion 
gitversion /version
```

## Context
I'm trying to debug and issue that I think is caused by an outdated version. 

## Your Environment
Intel MacOs (Monterey, Big Sur)

**Comment by asbjornu** [comment]
Thank you for reporting this. It is a known issue, but we just haven't gotten around to debug it yet. We would be very happy to receive a PR that fixes this. 🙏🏼

**Comment by arturcic** [comment]
there is a fix of the homebrew formulae https://github.com/Homebrew/homebrew-core/pull/113622

**Comment by asbjornu** [comment]
@arturcic, so the `Version` argument was never passed to the compiler. That explains it! :)

**Comment by arturcic** [comment]
yes, tested in linux homebrew

**Comment by arturcic** [comment]
That PR got merged, closing this issue
