### ISSUE TITLE
[Improvement] Don't consider `tag-prefix` as optional

### ISSUE THREAD

**Issue by AlexPykavy** [GitTools/GitVersion#3216]
## Detailed Description

Currently `tag-prefix` is always considered as optional which makes calculation of the next version incorrect. It mixes prefixed and unprefixed versions and takes the largest of both.

## Context

To correctly calculate the next version with the prefix. For example, we develop the main product and some its plugin in the same repository and have the following git tags list:
- 0.1.0
- 0.1.1
- 0.2.0
- 0.2.1
- plugin_0.1.0
- plugin_0.1.1
The expected next plugin version is 0.1.2 not 0.2.2 (plugin_ prefix will be prepended before setting the tag).

**Comment by arturcic** [comment]
Fixed by https://github.com/GitTools/GitVersion/pull/3208

**Comment by asbjornu** [comment]
This will be a part of our next release of v5, @andyfurniss4. We haven't planned one yet, but we do them fairly regularly.

**Comment by andyfurniss4** [comment]
Thanks @asbjornu
