### ISSUE TITLE
[Bug] MsBuild fails when not in a git repo (GitHub ZIP download)

### ISSUE THREAD

**Issue by 0blu** [GitTools/GitVersion#3242]
When downloading a repository as a ZIP from GitHub the build process fails, because there is no repository (`.git` folder) in the zip. 

![image](https://user-images.githubusercontent.com/7039020/196601683-46c3ecd3-29f2-4270-9817-efa4e236a1d5.png)

I read something about a fallback strategy in [the unreleased `breaking_changes.md`](https://github.com/GitTools/GitVersion/blob/a5ef03efa2dde4972f1032d6a1b442275533333d/BREAKING_CHANGES.md?plain=1#L4).
Will this fix the issue?

## Expected Behavior
There should be an option to default the version to `0.0.0` when no repository is found.

## Steps to Reproduce
This bug was tested with [HermesProxy](https://github.com/WowLegacyCore/HermesProxy) but applies to all other projects too.
1. Use GitHub to download the project as a zip
2. Try to compile the solution

## Your Environment
- GitVersion.MsBuild: 5.10.3
- Windows 10

**Comment by asbjornu** [comment]
This was fixed in #3190 which will be a part of v6 once it's released.
