### ISSUE TITLE
[Bug] Error with .NET 7: You must install .NET to run this application

### ISSUE THREAD

**Issue by diegosasw** [GitTools/GitVersion#3287]
I have installed .NET 7 and I don't have .NET 6 anymore. When installing the latest GitVersion and trying to run it with `dotnet gitversion` I get the following error
```
You must install .NET to run this application.

App: /home/diegosasw/.dotnet/tools/dotnet-gitversion
Architecture: x64
App host version: 7.0.0
.NET location: Not found

Learn about runtime installation:
https://aka.ms/dotnet/app-launch-failed

Download the .NET runtime:
https://aka.ms/dotnet-core-applaunch?missing_runtime=true&arch=x64&rid=ubuntu.22.04-x64&apphost_version=7.0.0

```

## Expected Behavior
It should display the gitversion output

## Actual Behavior
It's displaying the error stating that .NET location is Not found

## Steps to Reproduce
Install .NET 7
```
sudo apt install curl
curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | sudo dd of=/usr/share/keyrings/microsoft.gpg
```
For 22.04
```
echo 'deb [arch=amd64 signed-by=/usr/share/keyrings/microsoft.gpg] https://packages.microsoft.com/ubuntu/22.04/prod jammy main' | sudo tee /etc/apt/sources.list.d/microsoft.list >/dev/null
```
Install SDK and runtimes for .NET 7
```
sudo apt update
sudo apt install dotnet-sdk-7.0
sudo apt install dotnet-runtime-7.0 
sudo apt install aspnetcore-runtime-7.0
```

Validate dotnet is there
```
dotnet --version
7.0.100
```

Install GitVersion
```
dotnet tool install --global GitVersion.tool --version 5.11.1
Tool 'gitversion.tool' is already installed.
```

Now try to use it
```
dotnet gitversion
You must install .NET to run this application.

App: /home/diegosasw/.dotnet/tools/dotnet-gitversion
Architecture: x64
App host version: 7.0.0
.NET location: Not found

Learn about runtime installation:
https://aka.ms/dotnet/app-launch-failed

Download the .NET runtime:
https://aka.ms/dotnet-core-applaunch?missing_runtime=true&arch=x64&rid=ubuntu.22.04-x64&apphost_version=7.0.0

```

## Your Environment
- Version Used: 5.11.1
- Operating System and version (Windows 10, Ubuntu 18.04): Ubuntu 22.04

**Comment by diegosasw** [comment]
I suspect it's not yet supported, but using an environment variable 
```
DOTNET_ROLL_FORWARD=Major
```
doesn't make any difference. No other versions installed.

**Comment by gep13** [comment]
The PR that you linked to (https://github.com/GitTools/GitVersion/pull/3243) is associated with this issue (https://github.com/GitTools/GitVersion/issues/3169) which you will see is tagged on the 6.x milestone, which hasn't shipped yet.

**Comment by diegosasw** [comment]
Oh I see, sorry and thank you.
