### ISSUE TITLE
LibGit2Sharp.LibGit2SharpException: Too many redirects or authentication replays with GitVersion.CommandLine 2.0.0

### ISSUE THREAD

**Issue by pvandervelde** [GitTools/GitVersion#330]
I've just updated from 1.3.3 to 2.0.0 and now the build isn't working on my build server anymore (can reproduce on my local if I provide the same user and password).

I'm using this command line

    GitVersion.exe /u MyADUser /p abcdef123 /url "http://tfs:8080/tfs/myproject/_git/myrepo"

Which leads to the following response

    Setting up credentials using name 'MyADUser'
    Retrieving git info from url 'http://tfs:8080/tfs/myproject/_git/myrepo'
    An unexpected error occurred:
    LibGit2Sharp.LibGit2SharpException: Too many redirects or authentication replays
       at LibGit2Sharp.Core.Ensure.HandleError(Int32 result)
       at LibGit2Sharp.Core.Proxy.git_clone(String url, String workdir, GitCloneOptions& opts)
       at LibGit2Sharp.Repository.Clone(String sourceUrl, String workdirPath, CloneOptions options)
       at GitVersion.GitPreparer.GetGitInfoFromUrl() in c:\BuildAgent\work\68ea6bfb44e5afb\GitVersionExe\GitPreparer.cs:line 62
       at GitVersion.GitPreparer.Prepare() in c:\BuildAgent\work\68ea6bfb44e5afb\GitVersionExe\GitPreparer.cs:line 28
       at GitVersion.Program.Run() in c:\BuildAgent\work\68ea6bfb44e5afb\GitVersionExe\Program.cs:line 66

It does work if I don't specify a user / password in which case I assume it will use my AD credentials or possibly nothing?

Any suggestions if there is a fix for this?

**Comment by kvarv** [comment]
I'm experiencing the same error... Any help would be greatly appreciated!

**Comment by JakeGinnivan** [comment]
@nulltoken any ideas? :)

**Comment by nulltoken** [comment]
>GitVersion.exe /u MyADUser /p abcdef123 /url "http://tfs:8080/tfs/myproject/_git/myrepo"

@ethomson When talking to tfs through Windows authentication, shouldn't we rather rely on using `DefaultCredentials` rather than `UsernamePasswordCredentials`?

**Comment by ethomson** [comment]
> @ethomson When talking to tfs through Windows authentication, shouldn't we rather rely on using DefaultCredentials rather than UsernamePasswordCredentials?

You can do that, to log in as the current user.  But you should also be able to specify `UsernamePasswordCredentials`.

Troubleshooting authentication failures can be tricky.  @kvarv do you have permissions to the repository?  Can you clone from the command-line using Git for Windows?  Are you specifying your domain with your username?  If not, why not?  If so, are you using `DOMAIN\username` or `username@DOMAIN`?  What's in the server log?

Ultimately this is most likely to be a configuration issue.  I would recommend that you contact your server administrator and / or support to help troubleshoot.

**Comment by kvarv** [comment]
@ethomson Yes, I have permissions and can clone the repository. My problems are related to TeamCity and I'm pretty much in the same boat as this guy: http://stackoverflow.com/questions/27144453/connection-error-with-private-repository-using-gitversion-as-a-build-step-in-tea

On my dev machine I get the "Too many redirects or authentication replays" when supplying username and password along with an url. 

Anyway, I'm suspecting that basic authentication is not enabled in our TFS server so I will contact the administrators and check.

Thanks!

**Comment by thisispaulsmith** [comment]
@kvarv did you resolve your issue?
I seem to having the same problem at the moment
