### ISSUE TITLE
[Improvement] Move serialization and deserialization process of configuration out of the scope of core domain

### ISSUE THREAD

**Issue by HHobeck** [GitTools/GitVersion#3306]
**Is your improvement request related to a problem? Please describe.**
In the discussion of pull-request https://github.com/GitTools/GitVersion/pull/3235 (Create new fallback and unknown section in GitVersionConfiguration) we came to the conclusion that it might be a good idea to move the serialization and deserialization process out of the scope of the core domain (see https://github.com/GitTools/GitVersion/pull/3235#discussion_r1030138326).

## Detailed Description
The core domain should have only the business logic without the dependency to the Yaml library.

## Possible Implementation
Move the logic in GitVersionContextFactory from core to another place and only provide the final GitVersionConfiguration instance to the core domain. The idea is to either make the GitVersionConfiguration immutable or provide the entity via interface or abstract class.

**Comment by arturcic** [comment]
I was thinking we need to move `Configuration` related code into a separate module similarly I did for BuildAgents and Output, I just wonder what should we keep in your opinion in the `GitVersion.Core`?

The idea is to keep in the `GitVersion.Core`  mainly the interfaces, and the classes related to version calculation.

What do you think?

**Comment by HHobeck** [comment]
I'm not sure what exactly the target architecture might be: Maybe onion architecture or 3-layer architecture with dedicated business entities. Nevermind independent of that the plan is to have some where a place (GitVersion.Core?) with business logic of GitVersion with no dependencies to other services or infrastructure like de-/serialization components. Thus this classes and intefaces which giving the additional value to GitVersion (without dependencies) needs to be present in GitVersion.Core.

**Comment by HHobeck** [comment]
Maybe we need to create a concept and write a component diagram to illustrate the dependencies first? @asbjornu: What do you think?

**Comment by arturcic** [comment]
@HHobeck @asbjornu - please check this one https://github.com/GitTools/GitVersion/discussions/3407
