### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by Sardardot2** [GitTools/GitVersion#3321]
**Describe the bug**
This is more of a breaking change, however, with the latest release of 6.0.0-alpha.1. When pulling in the image from docker hub inside a GitLab pipeline, an issue occurs when running the "dotnet-gitversion" executable with no real discernible error output.

After debugging a little further, I was able to shed a little light and found that the 'continuous-delivery-fallback-tag' was not found for the type 'GitVersion.Configuration.GitVersionConfiguration' and the log reported it as an unexpected error.

The output is displayed below:

INFO [12/22/22 21:48:20:74] End: Loading version variables from disk cache (Took: 0.25ms)
  INFO [12/22/22 21:48:20:74] Using latest commit on specified branch
  ERROR [12/22/22 21:48:20:82] An unexpected error occurred:
(Line: 3, Col: 1, Idx: 31) - (Line: 3, Col: 33, Idx: 63): Property 'continuous-delivery-fallback-tag' not found on type 'GitVersion.Configuration.GitVersionConfiguration'.

## Expected Behavior
When pulling down the latest gitversion image from docker hub inside a GitLab pipeline, running the dotnet-gitversion command should generate a valid semantic version.

## Actual Behavior
The actual behavior is that it appears the above tag either is not configured or is missing, and it is causing a nondescript error without much information.

## Steps to Reproduce
**Done inside of a gitlab pipeline in yaml syntax and using EKS
1. Specify an image with either the latest tag or with the 6.0.0-alpha.1 tag
2. Create a GitVersion.yml file with the mode set as 'ContinuousDeployment' and the 'continuous-delivery-fallback-tag' tag set to  main
3. run 'dotnet-gitversion' with /showvariable SemVer

## Context
This bug is impactful as it was preventing a valid semantic version from being included as part of the image name when undergoing the build process.

- Version Used: 6.0.0-alpha.1
- Operating System and version (Windows 10, Ubuntu 18.04): Ubuntu 16.04

**Comment by arturcic** [comment]
That is actually a breaking change, please check the document https://github.com/GitTools/GitVersion/blob/main/BREAKING_CHANGES.md#unreleased. That was part of a planned change https://github.com/GitTools/GitVersion/issues/1054
