### ISSUE TITLE
[Docs] Publish docs from stable tags

### ISSUE THREAD

**Issue by asbjornu** [GitTools/GitVersion#3325]
As reported in #3324, our docs are published from `main` which now is primed for v6. This makes the docs out of sync with our latest stable release, v5. We should probably publish the docs from the `support/5.x` branch at least until v6 is done.

What we should have done before was to only publish docs on stable tags. That way, `docs` could be published from any branch as long as it had a stable tag. Perhaps we can do that now and get a new stable v5 out the door so the docs are brought back in time to v5?

**Comment by arturcic** [comment]
Ok I will have a look and disable the  publishing from `main` and re-publish v5.0

**Comment by asbjornu** [comment]
@arturcic, we may have a more future-proof system in place if we only publish on stable tags (regardless of branch), perhaps?

**Comment by arturcic** [comment]
> @arturcic, we may have a more future-proof system in place if we only publish docs on stable tags (regardless of branch), perhaps?

That will be the next step, first we need to re-publish v5

**Comment by arturcic** [comment]
I have published from v5 for now. So next I will work on the publishing from the stable tags when I find some time

**Comment by arturcic** [comment]
This was implemented for v6 beta 1, but it will be working on v6 stable release
