### ISSUE TITLE
[Bug] `increment` setting not respected

### ISSUE THREAD

**Issue by ckoehler** [GitTools/GitVersion#3339]
**Describe the bug**

I have set `increment: Minor` in my GitVersion.yml, everything else is default. I am on `main`, where the last tag (a few commits ago) was `1.1.30`. I run `gitversion`

## Expected Behavior

The new version should be `1.2.0` (like in the `SemVer` field of the output).

## Actual Behavior

The new version is `1.1.31`.

## Steps to Reproduce

See description above.

## Context

See above.

## Your Environment

- Version Used: 5.11.0 and 5.11.1
- Operating System and version (Windows 10, Ubuntu 18.04): OSX
- Link to your project: <private>
- Link to your CI build (if appropriate): <private>

**Comment by ckoehler** [comment]
Oh, looks like a duplicate of #2870

**Comment by HHobeck** [comment]
Please see this comment: https://github.com/GitTools/GitVersion/issues/2870#issuecomment-1476857171
