### ISSUE TITLE
[Bug]: GitVersion.BugException: GitVersion has a bug, your HEAD has moved after repo normalisation.

### ISSUE THREAD

**Issue by kabilanmani93** [GitTools/GitVersion#3342]
**Describe the bug**
Need to calculate the semversion after doing a hard reset to a specific commit [Using Gitlab pipelines]

## Expected Behavior
To calculate the gitversion after the hard-reset

## Actual Behavior
GitVersion.BugException: GitVersion has a bug, your HEAD has moved after repo normalisation.

## Steps to Reproduce

**scenario 1:** Running the gitversion using docker image ( docker  file give below) locally using 
docker run -it -v "$(pwd):/repo" --entrypoint sh gitversion:1.0 
cd /repo
git reset --hard <COMMIT>
/tools/dotnet-gitversion
--- > Works fine as expected the gitversion is calculated till the commit given in hard reset

**scenario 2:** Running the gitversion on Gitlab pipeline job(job yaml added below) using the same docker image ( docker file given below) 
after performing the git hard reset, the head changes
but then running the /tools/dotnet-gitversion getting an error "GitVersion has a bug, your HEAD has moved after repo normalisation."

Then we exported an environment variable export IGNORE_NORMALISATION_GIT_HEAD_MOVE=1
now executing the /tools/dotnet-gitversion the Semversion is the latest one , and head is also changed
  **Expected**: Semversion to be till the hard reset commit

## Context
We have stg and prd pipeline triggered , once the release branch is triggered
Both are executed manually
Once the stg pipeline  is executed and deployed ( assume the sem version is 0.8.10)
we have further feature commits to master (but we dont wanna release it)---> (0.9.0)
now trigger the prd pipeline , the semversion that we expect to be calculated is 0.8.10, but the semversion shown is 0.9.0

## Your Environment
Gitlab , 
Gitlab runners on EKS

**Docker file**
```
FROM gittools/gitversion:5.10.3-alpine.3.14-6.0
WORKDIR /tools
ADD GitVersion.yml .
ENTRYPOINT ["/tools/dotnet-gitversion"]
```

**Gitlab Pipeline Job**
``
```
.semantic-versioning:
  stage: sem-version
  image: 
  variables:
    GIT_STRATEGY: fetch
    GIT_DEPTH: 0
    GIT_FETCH_EXTRA_FLAGS: --no-tags
  script:
    - |
      if [[ "$ENVIRONMENT" == "prd" ]]; then 
         echo "Debugging enabled"
         set -xv

         echo "------HARDRESET TO LAST RELEASE HAVING TAG------------------------"
         git reset --hard $(git log --show-linear-break --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit | grep release/ | grep -E 'tag:\s[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,4}' | awk '{print $1}'| head -n1)
      fi

      VERBOSITYSETTING='/verbosity Diagnostic'
	  
      /tools/dotnet-gitversion /output buildserver $VERBOSITYSETTING && TAG_VER=$(grep 'GitVersion_SemVer=' gitversion.properties | awk -F= '{print $2}') 
      if [ "$TAG_VER" == "" ]; then
        echo "GitVersion failed"
        exit 1
      fi 
      echo "BUILD_VERSION=${TAG_VER}" >> build.env
    - echo $TAG_VER
  artifacts:
    reports:
      dotenv: build.env

```

**Comment by kabilanmani93** [comment]
could someone help us here ?

**Comment by asbjornu** [comment]
Looks like a duplicate of #3161.

**Comment by kabilanmani93** [comment]
Do we have any possible temp fix for this ?

**Comment by asbjornu** [comment]
@kabilanmani93 have you tried https://github.com/GitTools/GitVersion/issues/3161#issuecomment-1245042873?

**Comment by kabilanmani93** [comment]
Mine is of a different scenario,

Assume below stages in pipeline

- Gitverison-1 ( Pull code from master and calculate gitversion--> works fine) 
- sleep 3min  ( in 3 min sleep time, there is a new commit on master)
- Gitversion-2 ( **calculating  the gitversion fails here with below error**)

GitVersion.BugException: GitVersion has a bug, your HEAD has moved after repo normalisation

**Comment by kabilanmani93** [comment]
Even after switching checkout  to a different branch, the normalization happens on main branch.
Secondly passing the /c argument , till where the gitversion to be calculated, seems that is also not considered

**Switched to branch 'b7b294e4125a696afdbfedd1c87ec0413f2e1971'**
/tools/dotnet-gitversion /output buildserver **/c $CI_COMMIT_SHA** $VERBOSITYSETTING && TAG_VER=$(grep 'GitVersion_SemVer=' gitversion.properties | awk -F= '{print $2}') 
++ /tools/dotnet-gitversion /output buildserver /c b7b294e4125a696afdbfedd1c87ec0413f2e1971
INFO [03/01/23 18:27:36:30] Working directory: /builds/core/gitversion
INFO [03/01/23 18:27:36:32] Project root is: /builds/core/gitversion/
INFO [03/01/23 18:27:36:32] DotGit directory is: /builds/core/gitversion/.git
INFO [03/01/23 18:27:36:32] Branch from build environment: main
INFO [03/01/23 18:27:36:32] **Begin: Normalizing git directory for branch 'main'**

**Comment by asbjornu** [comment]
Have you tried running with the `/nonormalize` argument?

**Comment by kabilanmani93** [comment]
@asbjornu How important is normalization in gitversion, having nonormalize argument would not calculate  an incorrect semversion?

**Comment by asbjornu** [comment]
If GitVersion is unable to create a version, it will fail. Normalization is only built to attempt to fix an unorderly repository. If you can fix the repository yourself before running GitVersion, it will run just fine.

**Comment by kabilanmani93** [comment]
@asbjornu Okay thanks for the info. 

and adding the below code worked for my scenario. Thanks for the help.

git fetch origin $CI_COMMIT_SHA:master
git checkout master
/tools/dotnet-gitversion /output buildserver /c $CI_COMMIT_SHA /nonormalize
