### ISSUE TITLE
[Improvement] Allow us to override buildserver type

### ISSUE THREAD

**Issue by N0K0** [GitTools/GitVersion#3350]
**Is your improvement request related to a problem? Please describe.**

Hi! Been over medium confused today why i did not get any output from 
`/tools/dotnet-gitversion /output buildserver /targetpath /repo/` when running it locally, but in Gitlab, with its image it worked without any issue.

Now in retrospect its clear that this line refers to output format:
> Executing GenerateSetVersionMessage for 'LocalBuild'.
Which is this on Gitlab:
> Executing GenerateBuildLogOutput for 'GitLabCi'.

Would it make more sense to either 
1) Output into a standard .env format?
2) Give us a clear override switch for setting version. I've resolved the issue for me now by using `GITLAB_CI=1`, which i found via perusing the source code.

## Context

As of right now, it's not clear why/that `/output buildserver` will not work locally.
If anything, this is just to remove some surprise from users that also reads the /help
But not the docs good enough https://gitversion.net/docs/usage/cli/output

## Possible Implementation

* Make Localbuild output something more useful than nothing.
* Add a flag to override the output formatter, so that you may match your buildserver for example

**Comment by asbjornu** [comment]
How about documenting the environment variables used to detect build servers better?

**Comment by asbjornu** [comment]
I think the page for each individual [build server](https://gitversion.net/docs/reference/build-servers/) makes most sense?

**Comment by arturcic** [comment]
@N0K0 I wonder why would you want to run gitversion with the `/output buildserver` when running locally? The intent of that option is to write some agent specific command messages that will set some variables as well as update the build number for the build agents that do support that. I don't see why would you want to have this option used locally. I'd suggest to close this one if there is no good reason to run gitversion locally with that option

**Comment by N0K0** [comment]
@arturcic my issue at the time was that GitVersion acted differently between local runs and on the buildserver without it being all that clear why. By being able to override/document how the GitVersion output format is selected, we can ensure parity between tooling run locally and run on the build server :smile: 

It's an edge case, so updating the documentation regarding how  output format is selected might be enough for most.

**Comment by arturcic** [comment]
then I would say we need to change the Issue title and just update the docs adding some details on which environment variables are used to determine which build agent it runs on and other details specific to a build agent. Can you update the title please?
