### ISSUE TITLE
[Bug] Publish fails for WPF .NET 6 project

### ISSUE THREAD

**Issue by githubjanson** [GitTools/GitVersion#3366]
**Describe the bug**
Not sure if this is a bug or an error in documentation. When using GitVersion.MSBuild in a WPF .NET 6 project, Publish to folder fails. 

## Expected Behavior
This should work for SDK style WPF .NET 6 projects, the workarounds described in documentation is for earlier versions.

## Actual Behavior
Publishing fails with the following output:

`3>Duplicate 'System.Reflection.AssemblyFileVersionAttribute' attribute
3>Duplicate 'System.Reflection.AssemblyInformationalVersionAttribute' attribute
3>Duplicate 'System.Reflection.AssemblyVersionAttribute' attribute`

## Possible Fix
It works with the workaround described for versions < v5.0.200, turning off automatic generation of the different versioning attributes.

## Steps to Reproduce
Project: WPF project targeting .NET 6, with NuGet GitVersion.MSBuild 5.12.0
Action: Select Publish to folder, with the following profile settings:
- Configuration: Release | Any CPU
- Target framework: net6.0-windows
- Deployment mode: Self-contained
- Target runtime: win-x64
- File publish options: Produce single file, Enable ReadyToRun compilation

## Your Environment
Visual Studio 2022 Version 17.1.3
Windows 11

**Comment by arturcic** [comment]
If you have [assembly: AssemblyVersion("")] and [assembly: AssemblyInformationalVersionAttribute("")] and [assembly: AssemblyInformationalVersionAttribute("")] in your AssemblyInfo.cs file, please remove them, in order for GitVersion.MsBuild to generate the appropriate attributes.

I've tried with a new wpf project created from scratch targeting .net sdk 6.0 and in the default AssemblyInfo there were no above attributes. I used both version 5.12.0 and 6.0.0-beta.1

**Comment by githubjanson** [comment]
Correct, there are no such attributes in AssemblyInfo. But it still fails for me.

**Comment by arturcic** [comment]
Can you post your csproj here?

**Comment by githubjanson** [comment]
Sure! Somewhat anonymized, but still.
[noname.csproj.txt](https://github.com/GitTools/GitVersion/files/10909483/noname.csproj.txt)
