### ISSUE TITLE
[Improvement] Deprecate GitVersion.Commandline nuget package

### ISSUE THREAD

**Issue by arturcic** [GitTools/GitVersion#3375]
Starting with version v6.0 we will deprecate the [`GitVersion.Commandline`](https://www.nuget.org/packages/GitVersion.CommandLine/) nuget package and the reasons are:

- There are 2 alternatives that can be used:
  - the dotnet global tool [`GitVersion.Tool`](https://www.nuget.org/packages/GitVersion.Tool) if you have the dotnet sdk installed
  - use the `zip` files depending on the architecture you run on (you can find the `zip`  files as artifacts of every release)
- The usage on nuget.org is really low and with every version lower.

**Comment by hotchkj** [comment]
I understand that this is the direction GitVersion is going, but this is a disappointing change. Previously, I could use NuGet to properly download and cache tooling reliably. It meant that any given build is not immediately subject to the whims of Internet package availability unless the package had actually changed.

Now I have to either re-invent that caching myself or build my own NuGet package. The current alternatives all appear to be global tools, which are not suitable for CI environments, which in turn means a complicated dance of installing these onto something like Docker images. Was this really such a saving that the package had to be removed?

**Comment by hotchkj** [comment]
It's possible I'm unaware of some aspect of global tools. With a NuGet package, I can control where the packages go with environment variables, and have multiple versions co-exist and be requested by version by tooling. With a global tool, I'm not sure how to achieve that; when last I tried, dotnet only worked properly when one version of a tool is present, which doesn't scale across hundreds of repos using different editions of toolings.

**Comment by arturcic** [comment]
Check this one https://learn.microsoft.com/en-us/dotnet/core/tools/global-tools-how-to-use#use-the-tool-as-a-global-tool-installed-in-a-custom-location
