### ISSUE TITLE
[Bug] Normalization takes a very long time

### ISSUE THREAD

**Issue by NorbertNemec** [GitTools/GitVersion#3397]
This is reopening #1266 because the time for normalization really is a serious issue in our case, using GitVersion 5.12.0 on Azure Pipelines.

I'm attempting to introduce GitVersion to an existing large project with ~100 developers and ~1000 personal branches. I'm in no position to sort that out, but due to that, running gitversion/execute@0 in our Azure Pipeline takes ~1.5 min spewing out log messages ("Creating local branch from remote tracking...") for each of those personal branches.

Adding >1min to each of our pipeline builds just for introducing GitVersion will be seriously hard sell. Is there any means to avoid that normalization or filter the branches that need to be added locally for the version calculation?

**Comment by NorbertNemec** [comment]
Yes, ADO is doing a full clone, including all branches. I just edited my description to remove my hypothesis about an incomplete initial clone, which was clearly wrong and misleading.

I have no idea what kind of "normalization" GitVersion needs to do after that clone and why "creating local branches" takes ~50ms per branch.

**Comment by asbjornu** [comment]
Are you able to run GitVersion with the `/nonormalize` argument?

**Comment by NorbertNemec** [comment]
Hmm - interesting that I missed that option. It might have fixed the issue. Anyway - by now I have built a simple alternative solution that does not depend on GitVersion. Pity...
