### ISSUE TITLE
[Bug] wrong patch count after merging Release branch

### ISSUE THREAD

**Issue by tomtom1976** [GitTools/GitVersion#3422]
**Describe the bug**
After merging a feature branch to the main and merge back the main to development
![image](https://user-images.githubusercontent.com/10657125/222966426-e7725a42-d2d7-4e89-9b25-4051b4642248.png)

the version number is build correct to 1.1.0 but the patches not.
GitVersion counts all commits after branching the develoment from the main

![image](https://user-images.githubusercontent.com/10657125/222966625-1b045f87-932b-4ee4-a241-c91885ff3119.png)

## Expected Behavior
A Version number like 1.1.0-alpha.1 or like that

## Actual Behavior
1.1.0-alpha.6 <- all commit after branching from master

**Comment by HHobeck** [comment]
Hi @tomtom1976 .

Thank's for your input. What version you are using? May I ask you to create a integration test for your scenario? It helps us alot.  Please use the latest main branch which targeting the next release version 6.x.

```csharp
    [Test]
    public void Just_A_Test()
    {
        // * 2373a87 58 minutes ago  (HEAD -> main)

        var configuration = GitFlowConfigurationBuilder.New
            .WithVersioningMode(VersioningMode.ContinuousDeployment)
            .WithBranch("main", builder => builder
                .WithLabel("ci")
                .WithVersioningMode(VersioningMode.ContinuousDeployment)
            )
            .Build();

        using var fixture = new EmptyRepositoryFixture();

        fixture.MakeACommit();

        // ✅ succeeds as expected
        fixture.AssertFullSemver("0.0.1-ci.1", configuration);

        // or

        // ❌ expected: 0.0.1-ci.5"
        fixture.AssertFullSemver("0.0.1-ci.1", configuration);

        fixture.Repository.DumpGraph();
    } 
```

**Comment by HHobeck** [comment]
I think it will be solved with https://github.com/GitTools/GitVersion/issues/3438. @tomtom1976 please confirm
