### ISSUE TITLE
[Bug] Failure to load SSL libraries in Ubuntu 22

### ISSUE THREAD

**Issue by charryson** [GitTools/GitVersion#3460]
**Describe the bug**
We are seeing failures load SSL libraries when running in an Ubuntu 22 docker container. 

It looks like this might actually be fixed in the beta release, however, I was not able to prove that - the current beta itself failed for a different reason - with no changes to our GitVersion.yml file:
Could not build the configuration instance because following exception occurred: 'Property 'tag' not found on type 'GitVersion.Configuration.BranchConfiguration'

## Expected Behavior
Should generate a version number

## Actual Behavior
Failure to run

## Possible Fix
Possibly already fixed in 6.0.0 beta, I hit a different problem trying to use that version.

## Steps to Reproduce
Taking a best guess at this since I'm running this inside a docker container:

- Start with an Unbuntu 22.04 image
- dotnet tool install -g GitVersion.Tool
- run dotnet-gitversion on the container

## Context
We are using it to auto version + tag branches in our CI pipelines.

## Your Environment
gitlab
docker

- Version Used: 5.12.0, 5.8.1

**Comment by arturcic** [comment]
> Property 'tag' not found on type

It was changed to 'label'

**Comment by charryson** [comment]
thanks, that fixed the secondary failure - seems like there was quite a few breaking configuration changes from the version we have been using. 

After some updating, led me to confirm that the underlying issue is fixed in the beta version

**Comment by arturcic** [comment]
Thank you for confirmation, closing
