### ISSUE TITLE
[Bug] ref '.....' doesn't match the destination

### ISSUE THREAD

**Issue by DanieleSky** [GitTools/GitVersion#3465]
**Describe the bug**
Hi, I'm using GitVersion 6.0.0-beta2 with Jenkins with Multibranch pipeline.
I'm using the standard configuration (I haven't GitVersion.yaml)
When I tag a commit and build it, GitVersion throw an error like this:
```
INFO [04/07/23 13:04:13:94] Applicable build agent found: 'Jenkins'.
INFO [04/07/23 13:04:14:09] Working directory: /var/lib/jenkins/workspace/4Retail_Dinamo.Extensions_v1.7.1
INFO [04/07/23 13:04:14:09] Project root is: /var/lib/jenkins/workspace/4Retail_Dinamo.Extensions_v1.7.1/
INFO [04/07/23 13:04:14:09] DotGit directory is: /var/lib/jenkins/workspace/4Retail_Dinamo.Extensions_v1.7.1/.git
INFO [04/07/23 13:04:14:10] Branch from build environment: v1.7.1
INFO [04/07/23 13:04:14:11] Begin: Normalizing git directory for branch 'v1.7.1'
  INFO [04/07/23 13:04:14:16] One remote found (origin -> 'http://gitea.dinamoretail.lan/Var4Retail/Dinamo.Extensions.git').
  INFO [04/07/23 13:04:14:16] Skipping fetching, if GitVersion does not calculate your version as expected you might need to allow fetching or use dynamic repositories
  INFO [04/07/23 13:04:14:17] Updating local branch v1.7.1 to match ref v1.7.1
  INFO [04/07/23 13:04:14:22] Skipping update of 'refs/remotes/origin/HashRefactorECrypting' as it already matches the remote ref.
  INFO [04/07/23 13:04:14:22] Skipping update of 'refs/remotes/origin/main' as it already matches the remote ref.
  INFO [04/07/23 13:04:14:22] Creating local branch from remote tracking 'refs/remotes/origin/staging'.
  INFO [04/07/23 13:04:14:24] End: Normalizing git directory for branch 'v1.7.1' (Took: 130.16ms)
  ERROR [04/07/23 13:04:14:26] An unexpected error occurred:
**LibGit2Sharp.LibGit2SharpException: ref 'refs/remotes/origin/staging' doesn't match the destination**
```
If I rerun the build the error change based of the name of all branch I have in the repository.
Like this:
**LibGit2Sharp.LibGit2SharpException: ref 'refs/remotes/origin/main' doesn't match the destination**
**LibGit2Sharp.LibGit2SharpException: ref 'refs/remotes/origin/staging' doesn't match the destination**
**LibGit2Sharp.LibGit2SharpException: ref 'refs/remotes/origin/features-1' doesn't match the destination**

After last branch the build works as expected:
```
+ dotnet-gitversion /updateprojectfiles buildserver
{
  "AssemblySemFileVer": "1.7.1.0",
  "AssemblySemVer": "1.7.1.0",
  "BranchName": "v1.7.1",
  "BuildMetaData": null,
  "CommitDate": "2023-04-07",
  "CommitsSinceVersionSource": 0,
  "EscapedBranchName": "v1-7-1",
  "FullBuildMetaData": "Branch.v1.7.1.Sha.434206b3d7989e7106c234e1a5b06a611c078296",
  "FullSemVer": "1.7.1",
  "InformationalVersion": "1.7.1+Branch.v1.7.1.Sha.434206b3d7989e7106c234e1a5b06a611c078296",
  "Major": 1,
  "MajorMinorPatch": "1.7.1",
  "Minor": 7,
  "Patch": 1,
  "PreReleaseLabel": "",
  "PreReleaseLabelWithDash": "",
  "PreReleaseNumber": null,
  "PreReleaseTag": "",
  "PreReleaseTagWithDash": "",
  "SemVer": "1.7.1",
  "Sha": "434206b3d7989e7106c234e1a5b06a611c078296",
  "ShortSha": "434206b",
  "UncommittedChanges": 0,
  "VersionSourceSha": "434206b3d7989e7106c234e1a5b06a611c078296",
  "WeightedPreReleaseNumber": 60000
}
```

Attach the configuration of Jenkins
![image](https://user-images.githubusercontent.com/11925650/230599921-9bc19b63-7112-407f-bbe4-c2c1184e56ce.png)

Why the software have this behaviour?
There are some configurations that is wrong?

**Comment by HHobeck** [comment]
> Why the software have this behaviour?

I think you have found a bug. For me it's not clear why this error occures and also I cannot try/reproduce it because I'm not using Jenkins. Thus I need your help finding the root cause. Could please give me the hole exception stack trace please? Maybe this change is a candidate: https://github.com/GitTools/GitVersion/pull/3459

**Comment by DanieleSky** [comment]
Hi HHobek,
I started with the version 5.12 and then I upgraded to 6.0.0-beta2 to try to resolve..
With the version 5.12 there was the same issue.
I have jenkins installed in a linux machine, I could try to install the same enviroment on a shared machine.
Daniele

**Comment by DanieleSky** [comment]
Hi @HHobeck 
I send you an email. Let me know if is ok.
Thank you
Daniele

**Comment by DanieleSky** [comment]
Hi @HHobeck 
Have you try to reproduce the issue on test environment that I shared with you?
If not do you know when you can or if someone else can?

**Comment by HHobeck** [comment]
First of all thank you for creating the test environment. Actually I'm quite busy at this moment and have no time to take a look into your issue. It's also related to infrastrucutre which I'm not fimiliar with. @arturcic Do you have time to take a look?

**Comment by arturcic** [comment]
I don't think the following month i will be able to spend time on this

**Comment by DanieleSky** [comment]
Ok, don't worry. I'm going to shutdown the test enviroment due the costs of infrastructure. When you able to check this issue, if you need the enviroment let me know, so I can restart it again.
Thanks

**Comment by DanieleSky** [comment]
Hi, any news about this issue?

**Comment by mwijns** [comment]
I'm having the same problem, tested on 5.10.0, 5.11.0. and 5.12.0. As described above every build the problem from the previous build is resolved and the error is on the next update, e.g.

12:30:16  WARNING:   INFO [06/27/23 12:30:14:97] Updating local branch release/2.4.2 to match ref release/2.4.2
12:30:16  WARNING:   INFO [06/27/23 12:30:15:42] Creating local branch from remote tracking 'refs/remotes/origin/develop'.
12:30:16  WARNING:   INFO [06/27/23 12:30:15:43] End: Normalizing git directory for branch 'release/2.4.2' (Took: 682.58ms)
12:30:16  WARNING:   ERROR [06/27/23 12:30:15:46] An unexpected error occurred:
12:30:16  WARNING: LibGit2Sharp.LibGit2SharpException: ref 'refs/remotes/origin/develop' doesn't match the destination

16:33:39  WARNING:   INFO [06/27/23 16:33:38:12] Updating local branch release/2.4.2 to match ref release/2.4.2
16:33:39  WARNING:   INFO [06/27/23 16:33:38:56] Skipping update of 'refs/remotes/origin/develop' as it already matches the remote ref.
16:33:39  WARNING:   INFO [06/27/23 16:33:38:57] Creating local branch from remote tracking 'refs/remotes/origin/feature/specific_feature_branch'.
16:33:39  WARNING:   INFO [06/27/23 16:33:38:58] End: Normalizing git directory for branch 'release/2.4.2' (Took: 733.13ms)
16:33:39  WARNING:   ERROR [06/27/23 16:33:38:61] An unexpected error occurred:
16:33:39  WARNING: LibGit2Sharp.LibGit2SharpException: ref 'refs/remotes/origin/feature/specific_feature_branch' doesn't match the destination

16:46:55  WARNING:   INFO [06/27/23 16:46:53:80] Updating local branch release/2.4.2 to match ref release/2.4.2
16:46:55  WARNING:   INFO [06/27/23 16:46:54:42] Skipping update of 'refs/remotes/origin/develop' as it already matches the remote ref.
16:46:55  WARNING:   INFO [06/27/23 16:46:54:43] Skipping update of 'refs/remotes/origin/feature/specific_feature_branch' as it already matches the remote ref.
16:46:55  WARNING:   INFO [06/27/23 16:46:54:43] Creating local branch from remote tracking 'refs/remotes/origin/feature/another_feature_branch'.
16:46:55  WARNING:   INFO [06/27/23 16:46:54:44] End: Normalizing git directory for branch 'release/2.4.2' (Took: 933.50ms)
16:46:55  WARNING:   ERROR [06/27/23 16:46:54:47] An unexpected error occurred:
16:46:55  WARNING: LibGit2Sharp.LibGit2SharpException: ref 'refs/remotes/origin/feature/another_feature_branch' doesn't match the destination


full stack trace of the first instance (this was running 5.10.0):
12:30:16  WARNING:   ERROR [06/27/23 12:30:15:46] An unexpected error occurred:
12:30:16  WARNING: LibGit2Sharp.LibGit2SharpException: ref 'refs/remotes/origin/develop' doesn't match the destination
12:30:16  WARNING:    at LibGit2Sharp.Core.Ensure.HandleError(Int32 result) in /_/LibGit2Sharp/Core/Ensure.cs:line 154
12:30:16  WARNING:    at LibGit2Sharp.Core.Ensure.ZeroResult(Int32 result) in /_/LibGit2Sharp/Core/Ensure.cs:line 172
12:30:16  WARNING:    at LibGit2Sharp.Core.Proxy.git_refspec_rtransform(IntPtr refSpecPtr, String name) in /_/LibGit2Sharp/Core/Proxy.cs:line 2088
12:30:16  WARNING:    at LibGit2Sharp.Remote.FetchSpecTransformToSource(String reference) in /_/LibGit2Sharp/Remote.cs:line 138
12:30:16  WARNING:    at LibGit2Sharp.BranchUpdater.GetUpstreamInformation(String canonicalName, String& remoteName, String& mergeBranchName) in /_/LibGit2Sharp/BranchUpdater.cs:line 188
12:30:16  WARNING:    at LibGit2Sharp.BranchUpdater.SetUpstream(String upstreamBranchName) in /_/LibGit2Sharp/BranchUpdater.cs:line 116
12:30:16  WARNING:    at LibGit2Sharp.BranchUpdater.set_TrackedBranch(String value) in /_/LibGit2Sharp/BranchUpdater.cs:line 53
12:30:16  WARNING:    at GitVersion.BranchCollection.<>c__DisplayClass7_0.<UpdateTrackedBranch>g__Updater|0(BranchUpdater branchUpdater) in D:\a\GitVersion\GitVersion\src\GitVersion.LibGit2Sharp\Git\BranchCollection.cs:line 43
12:30:16  WARNING:    at LibGit2Sharp.BranchCollection.Update(Branch branch, Action`1[] actions) in /_/LibGit2Sharp/BranchCollection.cs:line 290
12:30:16  WARNING:    at GitVersion.BranchCollection.UpdateTrackedBranch(IBranch branch, String remoteTrackingReferenceName) in D:\a\GitVersion\GitVersion\src\GitVersion.LibGit2Sharp\Git\BranchCollection.cs:line 45
12:30:16  WARNING:    at GitVersion.GitPreparer.CreateOrUpdateLocalBranchesFromRemoteTrackingOnes(String remoteName) in D:\a\GitVersion\GitVersion\src\GitVersion.Core\Core\GitPreparer.cs:line 352
12:30:16  WARNING:    at GitVersion.GitPreparer.NormalizeGitDirectory(Boolean noFetch, String currentBranchName, Boolean isDynamicRepository) in D:\a\GitVersion\GitVersion\src\GitVersion.Core\Core\GitPreparer.cs:line 165
12:30:16  WARNING:    at GitVersion.GitPreparer.NormalizeGitDirectory(String targetBranch, Boolean isDynamicRepository) in D:\a\GitVersion\GitVersion\src\GitVersion.Core\Core\GitPreparer.cs:line 134
12:30:16  WARNING:    at GitVersion.GitPreparer.PrepareInternal(GitVersionOptions gitVersionOptions) in D:\a\GitVersion\GitVersion\src\GitVersion.Core\Core\GitPreparer.cs:line 69
12:30:16  WARNING:    at GitVersion.GitPreparer.Prepare() in D:\a\GitVersion\GitVersion\src\GitVersion.Core\Core\GitPreparer.cs:line 48
12:30:16  WARNING:    at GitVersion.GitVersionCalculateTool.CalculateVersionVariables() in D:\a\GitVersion\GitVersion\src\GitVersion.Core\Core\GitVersionCalculateTool.cs:line 43
12:30:16  WARNING:    at GitVersion.GitVersionExecutor.RunGitVersionTool(GitVersionOptions gitVersionOptions) in D:\a\GitVersion\GitVersion\src\GitVersion.App\GitVersionExecutor.cs:line 66

**Comment by DanieleSky** [comment]
Sad to see that this issue is still open :(
How I can to help you?

**Comment by asbjornu** [comment]
> I'm having the same problem, tested on 5.10.0, 5.11.0. and 5.12.0. 

@mwijns, can you please test with the latest v6 beta?

> Sad to see that this issue is still open :( How I can to help you?

@DanieleSky, we need a way to reproduce this. Did you manage to create a stable reproduction of the problem that we can have a look at?

**Comment by DanieleSky** [comment]
@asbjornu as I wrote above, I shared with @HHobeck an environment with Jenkins installed where you can try and see the issue.
Do you need somethings else?

**Comment by asbjornu** [comment]
> @asbjornu as I wrote above, I shared with @HHobeck an environment with Jenkins installed where you can try and see the issue. Do you need somethings else?

Are you able to share it publicly, or with me at asbjorn@ulsberg.no?

**Comment by DanieleSky** [comment]
@asbjornu I send you an email!
Thanks for you support

**Comment by JohnyBro** [comment]
Hi, do we have any information on this issue?

**Comment by DanieleSky** [comment]
No new information..
I'm going to shutdown the test enviroment due the costs of infrastructure. @asbjornu, when you able to check this issue, if you need the enviroment let me know, so I can restart it again.
Thanks

**Comment by JohnyBro** [comment]
@DanieleSky Did you find a workaround ?

**Comment by DanieleSky** [comment]
@JohnyBro no.. today I tried to debug the issue but without success.
It's an annoying problem, open from mote than six months. I'm thinking to switch to another tool.

**Comment by asbjornu** [comment]
Sorry for not finding time to debug this issue. All work on GitVersion is voluntary and unpaid, so we do it all on our free time. Finding the time and energy to debug a problem like this is therefore difficult. If anyone were able to reproduce the bug in an integration test, it would make the bug incredibly much simpler to fix.

**Comment by DanieleSky** [comment]
At the end I switched from Jenkins to GitLab (on prem) and all is working more or less as expected!

**Comment by pniederlag** [comment]
I can verify the problem 

`LibGit2Sharp.LibGit2SharpException: ref 'refs/remotes/origin/feature/STALE-FEATURE-BRANCH' doesn't match the destination
`

running gitversion on jenkins

- default gitlab config 5.12.0
- Gitlab-Style branch name for MergeRequest ("MR-48")
- no develop branch

'git show-ref' yields this (SHAS REDUCTED):

```
a242e87c refs/heads/MR-48
5d11a8fb refs/heads/feature/STALE-FEATURE-BRANCH
a242e87c refs/remotes/origin/MR-48
5d11a8fb refs/remotes/origin/feature/STALE-FEATURE-BRANCH
7bb0af5b refs/remotes/origin/master
b0cecc29 refs/tags/1.4.0
```

'.git/config' contains:

```
[remote "origin"]
	fetch = +refs/merge-requests/48/head:refs/remotes/origin/MR-48
	fetch = +refs/tags/*:refs/tags/*
	fetch = +refs/heads/*:refs/remotes/origin/*
```

there is an upstream bug-report in libgit2shar with multiple, overlapping ref-specs https://github.com/libgit2/libgit2sharp/issues/1782

**Comment by pniederlag** [comment]
I could solve the problem by adapting the refspec (one can configure the details on how git checkout is processed and what fetch refspecs are added into git/config) from "origin" (or ${REMOTE}) to "upstream".

Broken (effectivly "origin)):  ```+refs/heads/*:refs/remotes/${REMOTE}/*```
Working:  ```+refs/heads/*:refs/remotes/upstream/*```
