### ISSUE TITLE
[Feature] Create Changelog file

### ISSUE THREAD

**Issue by dhilgarth** [GitTools/GitVersion#3500]
**Is your feature request related to a problem? Please describe.**
Create changelog file

## Detailed Description
Other Semantic versioning tools create changelog files. Which makes sense because the git history is being parsed anyway, so this info could be re-used to automatically create a changelog file.
This needs to be optional and configurable, based on branch and / or mode

I might be able to provide a PR, but I first would like to understand if you actually see it as a good feature for GitVersion

**Comment by HHobeck** [comment]
How would the change log looks like!? Could you give an example?
