### ISSUE TITLE
[Bug] Git Tag version not respect

### ISSUE THREAD

**Issue by DanieleSky** [GitTools/GitVersion#3504]
Hi,
I'm using the version [6.0.0-beta.2](https://github.com/GitTools/GitVersion/releases/tag/6.0.0-beta.2).
I'm using the Tagging commit version increments.
With the same Jenkins pipeline command I have received two different results.
The first that is correct:
![image](https://github.com/GitTools/GitVersion/assets/11925650/bb6ec14a-fbfa-4ce1-acc4-04c4b56ab248)

And the second that have the wrong Major and Minor numbers:
![image](https://github.com/GitTools/GitVersion/assets/11925650/e4c4157b-5059-433a-b14a-752831446fbe)

I cannot understand why the major number was incremented.

**Comment by asbjornu** [comment]
To me, `Major` seems to be `0` in both examples? How does your configuration look like? Why are there 7 tags in the first example and 27 in the second? The two examples are from two different commits, why do you expect the version number to be in each of them? The same?

**Comment by HHobeck** [comment]
@DanieleSky May I kindly ask you: Is this a question or a bug report? In any cases it is mandatory to provide steps to reproduce. If you like please use the latest main branch which targeting the next release version 6.x and create a integration test which reflects your scenario like:

```csharp
    [Test]
    public void Just_A_Test()
    {
        // * 2373a87 58 minutes ago  (HEAD -> main)

        var configuration = GitFlowConfigurationBuilder.New
            .WithVersioningMode(VersioningMode.ContinuousDeployment)
            .WithBranch("main", builder => builder
                .WithLabel("ci")
                .WithVersioningMode(VersioningMode.ContinuousDeployment)
            )
            .Build();

        using var fixture = new EmptyRepositoryFixture();

        fixture.MakeACommit();

        // ✅ succeeds as expected
        fixture.AssertFullSemver("0.0.1-ci.1", configuration);

        // or

        // ❌ expected: 0.0.1-ci.5"
        fixture.AssertFullSemver("0.0.1-ci.1", configuration);

        fixture.Repository.DumpGraph();
    } 
```

Thank you very much.

**Comment by DanieleSky** [comment]
> To me, `Major` seems to be `0` in both examples? How does your configuration look like? Why are there 7 tags in the first example and 27 in the second? The two examples are from two different commits, why do you expect the version number to be in each of them? The same?

I'm sorry but I realized I wrote it wrong!
I meant that in first case the number of the version wrote in the tag is respected, in the second not.
The repository are different, but the tags are done in the same way.
I expect that in the second example the version calculated from git version is Major = 0, Minor = 19, Patch = 1.

@HHobeck I try to reproduce with unit test, I return to you when I have done.
