### ISSUE TITLE
[Improvement] Use arm64/amd64 or x86_64/aarch_64 in the pre-built binary packages

### ISSUE THREAD

**Issue by damphyr** [GitTools/GitVersion#3583]
Use of just 'x64' for the pre built binaries of x86_64 CPUs makes it hard to incorporate gitversion in things like docker multi-platform images because 'x64` does not match any of the strings emitted by compilers, os tools etc.

It would make determining the download URL in the context of a docker multi-platform build much easier if the naming of the release packages matched the architecture emitted by e.g. `uname -m`.
Since arm64 is already used instead of aarch_64, using amd64 instead of x86_64 would look more consistent.

**Comment by asbjornu** [comment]
I suppose we welcome a pull request changing this. What do you say @arturcic?

**Comment by arturcic** [comment]
I'm not against that, but I think that is something the dotnet publish is using (RID) https://learn.microsoft.com/en-us/dotnet/core/rid-catalog so we used the Microsoft conventions

**Comment by damphyr** [comment]
I don't know if you have any storage restrictions, but adding a copy of the x64 package with the changed name would be a simple way to transition without breaking people who depend on the x64 naming
