### ISSUE TITLE
.deps.json not added to PublishItemsOutputGroup if GitVersion is used

### ISSUE THREAD

**Issue by martinmueller4voice** [GitTools/GitVersion#3597]
I have a .NET 7 ASP.NET project with a web UI for configuration of an application.

Since I want the configuration to be hosted in a Windows service, I include a reference to Microsoft.Extensions.Hosting.WindowsService.

For easy deployment, I need a Windows Installer package and this is created via a VS Setup Project.
The Setup Project packs the PublishItemsOutputGroup from my project into an msi file.
During deployment, the msi gets installed, the service registered and started  and everything worked until recently.

After I started using GitVersion, my service could no longer be started.

After deployment, I always got a `System.PlatformNotSupportedException: ServiceController enables manipulating and accessing Windows services and it is not applicable for other operating systems.`
in the `Microsoft.Extensions.Hosting.WindowsServices.WindowsServiceLifetime` c'tor.

I was able to find out that this is due to the fact that MyProject.deps.json is no longer being included in the msi file because - somehow - this file is no longer listed in the PublishItemsOutputGroup outputs.

When I build my project (not the installer), MyProjects.deps.json is created in the output folder.
When I publish my project to a folder, MyProjects.deps.json is published as well.

When I build the installer, there's a direct correlation between having a GitVersion reference and MyProject.deps.json missing from the output group.

Please help.

- Version Used: GitVersion 5.12.0
- Operating System and version (Windows 10)

**Comment by asbjornu** [comment]
Can you please try version 6 just to see whether the same problem is still there? If so, are you able to reproduce the problem in a test somehow?

**Comment by martinmueller4voice** [comment]
Hi Asbjørn and thanks for picking up the issue!
I've created a test repository at https://github.com/4voiceAG/GitVersionTest where you can reproduce the effect.

Unfortunately, I don't know how to try version 6 since 5.12.0 is the newest version I can see in VS.

Could you please give me some short feedback if you can reproduce the effect?

TIA
