### ISSUE TITLE
[Bug] CS0436 may be present with InternalsVisibleTo

### ISSUE THREAD

**Issue by Applesauce314** [GitTools/GitVersion#3606]
**Describe the bug**
When `GitVersionTask `was replace with `GitVersion.MSBuild` in 5.6.0 the issue described in #448 has reemerged.
## Expected Behavior
Not sure, GitVersionTask -> GitVersion.MsBuild is obviously a breaking version change, but the inconsistent behavior does not appear to be documented. was this change in behavior intentional or an accidental regression between versions.
## Actual Behavior
CS0436 is present if you try to use the `GitVersionInformation` when it is also present in a referenced project which exposes its internals to the current assembly with `InternalsVisibleTo`

**Comment by arturcic** [comment]
@Applesauce314 can you please create a test solution that reproduces the issue, and then we can decide if/when to fix it. If we decide to do it, then it will be implemented in v6 release cycle.

**Comment by Applesauce314** [comment]
[repro repository](https://github.com/Applesauce314/GitVersion_3606)

Apparently the change made for #448 only existed in version 3.2.1, version 4.0.0 was what actually returned to the original behavior.

my thoughts on "fixing" it would be to add a configuration option, that way it would not be a breaking change.
```xml
<GenerateGitVersionInformationInUniqueNamespace>true</GenerateGitVersionInformationInUniqueNamespace>
```

I have a fork I can turn into a pull request with the above suggestion included

**Comment by Applesauce314** [comment]
pull request is #3619 

I am not very happy with the way I handled the template for C♯, its kind of clunky,
