### ISSUE TITLE
Support Regex for label property

### ISSUE THREAD

**Issue by CasperWSchmidt** [GitTools/GitVersion#3661]
## Detailed Description
We're using Shortcut to manage stories and bugs. Shortcut can automatically generate branches based on features and chores in the format _feature/sc-xxxx/description_. Using the default regex ^features?[/-] to recognize branches, `useBranchName` (or `{branchName}`) we'll get tags with _sc-xxxx-description_ but we'd like to only have the story id (_sc-xxxx_) as the tag.

I'll be happy to make a PR once this feature has been discussed.

## Context
I'm unsure of the actual syntax, but perhaps something like `label: regex sc-\d+` so that the code can recognize the _regex_ prefix. This regex will then be executed against the branch name to retrieve the part of the branch name that is returned as the label

**Comment by HHobeck** [comment]
I like the idea. I would recomment to reuse the label and regex property in the branch related property section like:

```
  feature:
    label: '{BranchName}'
    regex: ^features?[\/-](?<BranchName>.+)
```

The important thing to notice here is that the user can use zero, one or more generic named capture groups in the regex of an branch which can be used in the label property per placeholder convention like `{BranchName}` or `<BranchName>`.

@asbjornu what do you think?

**Comment by asbjornu** [comment]
I agree to remove the `useBranchName` token and instead allow string interpolation of any variable GitVersion exposes.

**Comment by CasperWSchmidt** [comment]
That sounds awesome! Any ETA on a final release for 6.0.0?

**Comment by HHobeck** [comment]
> That sounds awesome! Any ETA on a final release for 6.0.0?

Of course when the tickets are done for milestone 6!? 😅

**Comment by CasperWSchmidt** [comment]
> > That sounds awesome! Any ETA on a final release for 6.0.0?
> 
> Of course when the tickets are done for milestone 6!? 😅

I can see that the milestone is 5% done, so I guess it will be a while :)

With a little guidance as to where and how you see this change made, I might be able to do this PR myself. Just let me know.

**Comment by HHobeck** [comment]
> I can see that the milestone is 5% done, so I guess it will be a while :)

On the first glance the progress for 6.x seems to be not so advanced but some alpha and beta versions have been released already with alot of changes ;)

![image](https://github.com/GitTools/GitVersion/assets/56404113/fa48354d-c062-4119-9df1-21d1a45e9601)

I would appreciate your help very much. Any features or bugs which can be finished will help to speed up the release.

> With a little guidance as to where and how you see this change made, I might be able to do this PR myself. Just let me know.

Of course I can guide you to the right location. For the beginning I would say let's start with this feature. :)
