### ISSUE TITLE
Dynamic repo should require a branch specified

### ISSUE THREAD

**Issue by JakeGinnivan** [GitTools/GitVersion#367]
See https://github.com/ParticularLabs/GitVersion/issues/351#issuecomment-70459600

When using the https://github.com/ParticularLabs/GitVersion/wiki/Feature:-Dynamically-Obtained-Repository feature (`/url`) we should throw if the `/b` argument is not used. The exception should contain information from that wiki page to make it easy for people to know what is going wrong.

**Comment by RaphHaddad** [comment]
I will pick this up and send a PR soon.

Ideally I would like a discussion around the PR before it's merged. I will put my concerns on the PR.

**Comment by JakeGinnivan** [comment]
Oops :P didn't read before I merged

**Comment by JakeGinnivan** [comment]
What were the concerns? Or ended up being ok?

**Comment by RaphHaddad** [comment]
They were more around the fact that we're throwing the base class
'Exception' everywhere. Is there any plan to have our own derived
Exceptions?

**Comment by JakeGinnivan** [comment]
The exception handling isn't great. No plan, but no objections to fix it up

**Comment by RaphHaddad** [comment]
Excellent. I will create an issue for this so that I don't forget. I will
get on this in the next few days.
