### ISSUE TITLE
[Improvement] Upgrade GitVersion to a newer version of .net

### ISSUE THREAD

**Issue by DuelMonster** [GitTools/GitVersion#3685]
## Detailed Description
The company I work for recently underwent a software security audit and in order to pass we were required to remove .net 5 from our infrastructure. This left us without a build server until the audit was complete due to GitVersion still being .net 5.

We have had to reinstall .net 5 on our build server in order to continue to support our clients and build our software.  This is far from ideal and will need to be removed again before our next security audit, which is an annual occurrence.

## Context
.net 5 became unsupported on May 10th 2022 and therefore is now a **security risk**.

## Implementation
Upgrade GitVersion to a newer version of .net. (_.net 6 for example is supported until Nov 12th 2024_)

I would also suggest that .net 8 is considered.  .net 8 gets released this November and it will be supported until Nov 2026.

**Comment by arturcic** [comment]
Do you mind telling which version of GitVersion you're using? The latest stable version which is 5.12.0 is actually supporting .net 6.0 https://www.nuget.org/packages/GitVersion.Tool/5.12.0#supportedframeworks-body-tab.

We are definitely considering .net8 as in our support policy it's to support latest Lts version and the previous Sts version as long as they are supported

**Comment by DuelMonster** [comment]
Well I thought we were running the latest, however I have just found 1 azure agent (_out of 8_) that was still running 5.11.0.
I've updated it and uninstalled .net 5 again.

I shall be sure to force all to update to the next version once it's release.

Thank you and sorry to bother you 😉
Closing issue

**Comment by DuelMonster** [comment]
Well I thought we were running the latest, however I have just found 1 azure agent (out of 8) that was still running 5.11.0.
I've updated it and uninstalled .net 5 again.

I shall be sure to force all to update to the next version once it's release.

Thank you and sorry to bother you 😉
Closing issue
