### ISSUE TITLE
[Bug] Invalid path passed to /config via cmd line is ignored without error

### ISSUE THREAD

**Issue by jwittner** [GitTools/GitVersion#3688]
**Describe the bug**
Run the command line tool and pass /config with a path to a non-existent file. Observe that version json results are produced and no error is reported.

```
dotnet tool run dotnet-gitversion /config .\GitVersion-ACS.yaml 
```

## Expected Behavior
No results and an invalid path should result in an error in the tool indicating that the config cannot be used.

## Actual Behavior

Version json results are produced and no error is reported.

## Possible Fix

The path must be getting validated - this should cause an error to manifest.

## Steps to Reproduce

See above commands

## Context
I thought the tooling was setup and working, but it had the wrong version path. Had to spend time debugging instead of have a clear indicator on what I did wrong.

## Your Environment

- Version Used: 5.12.0
- Operating System and version (Windows 10, Ubuntu 18.04): 
  - Windows 11
  - PowerShell 7.x
  - DotNet 6

**Comment by HHobeck** [comment]
Pull requests are welcome!!

**Comment by JonAnders** [comment]
Looks like this might have been fixed in https://github.com/GitTools/GitVersion/commit/e0c882d6919033a7cda57ce0272e3ed8afd5f0ab, currently included in the v6 betas.

**Comment by asbjornu** [comment]
Thanks, @JonAnders – it looks like you're right! Closing.
