### ISSUE TITLE
[Improvement] Publish testing framework

### ISSUE THREAD

**Issue by Sopor10** [GitTools/GitVersion#3691]
**Is your improvement request related to a problem? Please describe.**

I would like to document our gitversion configuration with tests. 

Therefor I looked at your awesome integration tests and wanted to write specific ones for my use case.
They work fine inside the GitVersion repository but at the moment I need to copy a bunch of source code (e.g. LibGit2Sharp) into my repository, as it is not published inside a nuget package.

## Detailed Description

I want to use the tests as a living documentation and safty net for the versioning of that repository.
It would be really nice to be able to have some sort of framework for that.

## Possible Implementation

It would be really nice, if you would publish all packages to create integration tests for custom gitversion configurations.

**Comment by HHobeck** [comment]
To understand your request: Do you think a change of the existing code is necessary as well (change classes from internal to public) or is it just to publish the existing test framework via nuget?

**Comment by Sopor10** [comment]
Sorry for the late reply.
I did not use internal classes, that would need to be made public.
