### ISSUE TITLE
[Bug] Error when trying to set "Branch Increment mode"

### ISSUE THREAD

**Issue by pampua84** [GitTools/GitVersion#3716]
Hi,
after running the dotnet-gitversion init command from the command line, I try to set " Branch Increment mode" by pressing 5 button, but the following error message appears:

> A suitable constructor for type 'GitVersion.Configuration.Init.SetConfig.GlobalModeSetting' could not be located. Ensure the type is concrete and services are registered for all parameters of a public constructor.

Environment
- Windows 11
- GitVersion 5.12.0+Branch.support-5.x.Sha.3f75764963eb3d7956dcd5a40488c074dd9faf9e

**Comment by pampua84** [comment]
Going through the code and doing a more in-depth search, I saw that the constructor on the branch main has gone back to being protected. Related issue #1942

This is the exception:

> A suitable constructor for type 'GitVersion.Configuration.Init.SetConfig.GlobalModeSetting' could not be located. Ensure the type is concrete and services are registered for all parameters of a public constructor.

**Comment by arturcic** [comment]
Thanks for the time spent on debugging. I will merge the change

**Comment by pampua84** [comment]
I apologize, it seems like a test fails. Tomorrow I will try to understand why and I will try to solve it

Inviato da Outlook per iOS<https://aka.ms/o0ukef>
________________________________
Da: Artur ***@***.***>
Inviato: Monday, October 9, 2023 11:38:28 PM
A: GitTools/GitVersion ***@***.***>
Cc: pampua84 ***@***.***>; Author ***@***.***>
Oggetto: Re: [GitTools/GitVersion] [Bug] Error when trying to set "Branch Increment mode" (Issue #3716)


Thanks for the time spent on debugging. I will merge the change

**Comment by arturcic** [comment]
for some reason not related to your PR the tests on macos sometimes does not work as expected. That seems to be something with the macos agents. I need to find some time to find the root cause, but that won't happen soon
