### ISSUE TITLE
NuGet versioning and the `unstable` and `beta` post-fixes

### ISSUE THREAD

**Issue by dennisdoomen** [GitTools/GitVersion#372]
What is the philosophy behind the `unstable` and `beta` post-fixes that are added to the NuGet versions in GitVersion? Because I just realized that pushing NuGet packages from both `develop` branch as well as any `release-` branches to the same MyGet feed is not giving me the desired behavior. The cause of this is that `unstable` is 'higher' than `beta` with respect to the versioning semantics of NuGet. Should I use separate feeds? Or is there some way of changing the `unstable` post-fix into something like `alpha`?

**Comment by orjan** [comment]
It's possible to set pre-release tag per branch! Run gitversion.exe /showconfig

**Comment by dennisdoomen** [comment]
Version 2.0.1 doesn't seam to have that option. Is it v3?

**Comment by gep13** [comment]
@dennisdoomen V3 hasn't been released yet, but over the last few days, @JakeGinnivan has been going a bit nuts, throwing loads of new features in, including the ability to configure just about everything.  If you are willing, I would suggest that you take a look at the latest source, and compile your own local version, and use that.  It should definitely include what you are asking for.

**Comment by dennisdoomen** [comment]
Cool!

**Comment by JakeGinnivan** [comment]
And for the philosophy.

If you are using GitFlow then likely you want to consume packages from your CI feed which must be higher than release packages to make that possible. Generally the recommended approach is CI packages are exposed via one feed, then deploy release packages to the official feeds to consume them.

But as @orjan and @gep13 said, v3.0 will be out soon and you can configure most things

**Comment by dennisdoomen** [comment]
@JakeGinnivan Thanks, but do you mean that 'beta' packages should also go to the official feed?

**Comment by JakeGinnivan** [comment]
Depends on your scenario, but yeah probably

**Comment by JakeGinnivan** [comment]
Hey @dennisdoomen can this issue be closed? Not sure what needs to be done or if it is sorted by v3?

**Comment by dennisdoomen** [comment]
Yes, I've adopted the two-feed approach. Thanks for the explanation.
