### ISSUE TITLE
[Feature] Use GitHub PR merge commit message for incrementing mainline version after release branch merge

### ISSUE THREAD

**Issue by AlexPykavy** [GitTools/GitVersion#3720]
**Is your feature request related to a problem? Please describe.**

I want to merge release branches to main via GitHub Pull Requests and not edit the default merge commit message in order to tell GitVersion to increment the version in the mainline. As far as I understand, now the merge commit message should contain the ["Merge branch" and "release" strings](https://github.com/GitTools/GitVersion/blob/ea00a28c284a2839851f74b4ad9c5634188b55e1/src/GitVersion.Core/VersionCalculation/BaseVersionCalculators/MergeMessageVersionStrategy.cs#L47C34-L47C34).

## Possible Implementation

The default GitHub PR merge commit message is "Merge pull request #<PR_NUMBER> from <REPOSITORY_NAME>/release/1.0.0". Maybe we can just update the if statement to also check for the phrase "Merge pull request".

**Comment by HHobeck** [comment]
Actually have you seen this configuration already? Does the regular expression not match?

![image](https://github.com/GitTools/GitVersion/assets/56404113/bf67f291-b80e-4465-8e64-b35bda233765)


https://github.com/GitTools/GitVersion/blob/main/src/GitVersion.Core/MergeMessage.cs

**Comment by AlexPykavy** [comment]
Thank you @HHobeck , I'll give it a try.

**Comment by HHobeck** [comment]
Okay pleases reopen this issue or give me a feedback if it's not working.

**Comment by AlexPykavy** [comment]
Eventually I found time to troubleshoot this behavior a bit and found the reason why it didn't work in my case. I used 5.x version of  the tool.
