### ISSUE TITLE
[Feature] Derive main branch version from release branch name

### ISSUE THREAD

**Issue by user1584** [GitTools/GitVersion#3721]
According to the [documentation](https://gitversion.net/docs/learn/branching-strategies/gitflow/examples), the Gitflow workflow requires tagging the main branch explicitly after merging a release branch. This seems unnecessary if the release branch naming conforms to the usual format (e.g. "release/1.3.0"). I expected the main version to be derived automatically from the merged release branch.

With default GitVersion-configuration, merging a relase branch named "release/1.3.0" to main with pre-merge-version "1.2.0" results in post-merge-version "1.2.1" instead of "1,3.0". 

I do not really understand the [source code](https://github.com/GitTools/GitVersion/blob/ea00a28c284a2839851f74b4ad9c5634188b55e1/src/GitVersion.Core/VersionCalculation/BaseVersionCalculators/MergeMessageVersionStrategy.cs#L49), but it seems that the release branch name is getting parsed already. From what I understood, the merge message is supposed to contain "Merge branch" and "release". Therefore, I tried the message "Merge branch release", but to no avail. 

The question is therefore: Is it possible to derive the version of the main branch from the merged release branch?

**Comment by asbjornu** [comment]
Branches are deleted, so nothing can be based on a branch name except to version itself during its lifetime. What's possible, though, is to use the merge message (where the branch name may or may not appear; it is not guaranteed) to derive a version number. But it's a flaky basis, so that's why tagging is (highly) recommended.

**Comment by user1584** [comment]
Thanks for pointing that out! I just didn't think about the branches being deleted. So, my version-from-branch-approach then obviously won't work. But the version-from-merge-message-approach seems worth a second thought. If running in a CI/CD pipeline, the tagging could even be automated based on the derived version. 
In another, related [thread](https://github.com/GitTools/GitVersion/issues/3720#issuecomment-1754430621), @HHobeck linked to a list of regular expressions. Are these commit message formats already expected to be supported by Gitversion 5.12.0 to derive the version? If not, is there a supported format?

**Comment by asbjornu** [comment]
Yes, we have some regular expressions that are able to catch the most common merge messages. It's possible to extend with your own if the default ones aren't sufficient.

**Comment by user1584** [comment]
Thanks! I have no idea why I struggled with this for so long, but while creating a debug script, I finally got the expected results! 
Thus, just for those who struggle as well, here is my debug script:
``` shell 
#!/bin/bash
set -e
git config --global init.defaultBranch main
git config --global user.email "you@example.com"
git config --global user.name "Your Name"

rm -rf /test_repo
git init --quiet /test_repo
cd /test_repo

# Make sure we are on 'main'. 
echo "# Status:"
git status

# Shortcut to return the "FullSemVer".
function FullSemVer () {
    echo "$(/tools/dotnet-gitversion /test_repo /showvariable FullSemVer )"
}

git commit --allow-empty -m "Initial commit on main."
echo "# FullSemVer of main after initial commit:"
echo $(FullSemVer)

# Creating develop and switching to it.
echo "# Switching to develop."
git switch -c develop
git commit --allow-empty -m "Initial commit on develop."

# Creating feature branch and switching to it.
echo "# Switching to feature branch."
git switch -c feature/new_feature

# Creating a file that can be committed.
echo "first commit" > test.txt
# Committing the file
git add test.txt
git commit --quiet -m "Initial commit on feature branch."
echo "# FullSemVer after first commit on feature branch:"
echo $(FullSemVer)

# Merging to develop
git checkout develop
git merge --quiet --no-ff -m "Merge of feature branch to develop." feature/new_feature
echo "# FullSemVer after feature branch merge to develop:"
echo $(FullSemVer)

# Creating release branch
git switch -c release/1.0.0
echo "# FullSemVer on release branch:"
echo $(FullSemVer)

# Merging to main
git checkout main
git merge --quiet --no-ff -m "Merge branch 'release/1.0.0' into main" release/1.0.0
echo "# FullSemVer on main after release branch merge:"
echo $(FullSemVer)
```

I mounted it into a [docker container with gitversion v6](gittools/gitversion:6.0.0-beta.3-debian.11-6.0). The output is:
```
# Status:
On branch main

No commits yet

nothing to commit (create/copy files and use "git add" to track)
[main (root-commit) 1f09fb8] Initial commit on main.
# FullSemVer of main after initial commit:
0.0.1-1
# Switching to develop.
Switched to a new branch 'develop'
[develop 0b6740d] Initial commit on develop.
# Switching to feature branch.
Switched to a new branch 'feature/new_feature'
# FullSemVer after first commit on feature branch:
0.1.0-new-feature.1+3
Switched to branch 'develop'
# FullSemVer after feature branch merge to develop:
0.1.0-alpha.4
Switched to a new branch 'release/1.0.0'
# FullSemVer on release branch:
1.0.0-beta.1+0
Switched to branch 'main'
# FullSemVer on main after release branch merge:
1.0.0-0
```

In the script, I used the default format `@"^Merge (branch|tag) '(?<SourceBranch>[^']*)'(?: into (?<TargetBranch>[^\s]*))*"` from [MergeMessage.cs](https://github.com/GitTools/GitVersion/blob/main/src/GitVersion.Core/MergeMessage.cs#L11). 
This makes me very happy!
