### ISSUE TITLE
[Docs] Git push does not transfer tags

### ISSUE THREAD

**Issue by SRNissen** [GitTools/GitVersion#3740]
NB: This is not a problem with gitversion-the-software, but it sure did take me long to find out why gitversion wasn't updating.

Starting this off: Gitversion gave different numbers locally and in my github job.

Reading the FAQ:

---

![image](https://github.com/GitTools/GitVersion/assets/4851097/b19d3251-0b1d-495e-8f2d-580c4b5b3081)

---

Well, then I clicked the link and on that page I saw:

---

![image](https://github.com/GitTools/GitVersion/assets/4851097/0161317f-658a-4930-beec-0e3a6ede19d4)

---

And I knew that I had God damn well tagged my commits.

So I went to the issue tracker and, yeah, there were issues about tags not being tracked - *closed* issues, by people who had resolved their problems, so ... probably not an issue with gitversion-the-software?

And then I read up on git tags (which I have never used before getting into gitversion) and found out that git push does not transfer tags, which explains the whole thing.

But it would have been nice to read that in the FAQ on gitversion. It happened to me - it could happen to others.

**Comment by asbjornu** [comment]
Good idea. A pull request documenting this would be merged for sure! 👍🏼

**Comment by SRNissen** [comment]
Sure, I've got a PR ready.

Do I fork the repo or do you grant access to creating branches in this repo or how is the preferred contribution style here? (...which I might as well add to CONTRIBUTING.md while I'm at it)

**Comment by arturcic** [comment]
Please create a fork and create the PR

**Comment by SRNissen** [comment]
Well the PR doesn't build

I can confirm, independently of the testing workflow, that the link causing the build failure does not work.

It is a link in a different part of the documentation, located at:

https://gitversion.net/docs/learn/branching-strategies/githubflow/

that has nothing to do with this change.

Still, it might be better to do something about the issue. Are there any policies on removing links?
