### ISSUE TITLE
[Bug] WeightedPreReleaseNumber is calculated incorrectly

### ISSUE THREAD

**Issue by bb185239** [GitTools/GitVersion#3791]
**Describe the bug**
We use the version format as - '{Major}.{Minor}.{Patch}.{WeightedPreReleaseNumber ?? 0} 
Suppose, the current main build is at 21.20.0.301, 
When I raise PR and merge the changes from branch1 to main, the build number incremented to be - 21.20.0.305
Later, when I raise PR and merge the changes of another branch- branch2 to main (merging without updating from the main branch so the branch2 doesn't have changes of branch1), the build number is observed to be - 21.20.0.302 (a decremented build number).

## Expected Behavior
The build to be incremented with no dependency on 'update from main branch'

## Actual Behavior
The build is decremented. 
The branch2 state without the commits of branch1 is used for calculating the build number.

## Possible Fix
Making sure that we update from main branch before merging the changes.

## Steps to Reproduce
We use the version format as - '{Major}.{Minor}.{Patch}.{WeightedPreReleaseNumber ?? 0} 
Suppose, the current main build is at 21.20.0.301, 
When I raise PR and merge the changes from branch1 to main, the build number incremented to be - 21.20.0.305
Later, when I raise PR and merge the changes of another branch- branch2 to main (merging without updating from the main branch so the branch2 doesn't have changes of branch1), the build number is observed to be - 21.20.0.302 (a decremented build number).

## Your Environment
Using gitversion: 5.5.1

- Version Used: 5.5.1
- Operating System and version - Windows Server 2016 DataCenter (OS Build- 14393.5582)

**Comment by HHobeck** [comment]
Hi there.

Please provide steps to reproduce by creating an integration test. This would help us to understand your scenario. In advance the main branch reflects the latest development initiatives which is 6.0.0-beta.3.

Thanks!

```csharp
[Test]
public void Just_A_Test()
{
    var configuration = GitFlowConfigurationBuilder.New.Build();

    using EmptyRepositoryFixture fixture = new("main");

    fixture.MakeACommit();

    // ✅ succeeds as expected
    fixture.AssertFullSemver("0.0.1", configuration);

or

    // ❌ expected: 0.1.0
    fixture.AssertFullSemver("0.0.1", configuration);
}
```

**Comment by HHobeck** [comment]
Suppose I have understood you right I don't see any misbehavior. The pre-release number increases in your scenario for each commit. If branch1 has more commits compared to branch2 then the calculated pre-release number of branch2 is of course lower. Could you please elaborate why do you think it is not correct?
