### ISSUE TITLE
Expose version bump type

### ISSUE THREAD

**Issue by RazaGR** [GitTools/GitVersion#3812]
as discussed here https://github.com/GitTools/GitVersion/discussions/3809 It would be great to have this feature in output to display details of what type of version bump it is. for example 

```js
isMajorUpdate: true,
isMinorUpdate: false,
isPatchUpdate: false
```

**Comment by HHobeck** [comment]
May I ask you to give us some information about the motivation of this feature? In which scenario you would like to use the information and for what? Please describe your workflow.

Thank you very much.

**Comment by HHobeck** [comment]
> May I ask you to give us some information about the motivation of this feature? In which scenario you would like to use the information which increment strategy has been performed and for what reason? Please describe your workflow.
> 
> Thank you very much.

@RazaGR
