### ISSUE TITLE
[Bug] v6.0.0-beta3 - GitVersion.yml custom master ignored when command line flags passed

### ISSUE THREAD

**Issue by Zordrak** [GitTools/GitVersion#3813]
**Describe the bug**

Config seems ignored when passing `-diag`.
With a master branch called `custom-master`, `gitversion` shows SemVer "1.8.0". `gitversion -diag` shows SemVer "1.8.0-custom-master.1"

## Expected Behavior

"SemVer": "1.8.0"

## Actual Behavior

"SemVer": "1.8.0-custom-master.1"

## Context

I'm struggling to reliably reproduce it. I was trying to diagnose why I was getting a different result in a custom shell script in GitHub Actions than I was locally, as the github action being invoked with `./gitversion -output file -outputfile gitversion.json -l gitversion.log -nocache;` was producing the wrong output, treating the custom-master branch like it was a feature branch. So I tried doing some local diagnostics, and discovered that with -diag mode on, I get the same aberrant behaviour. I can only assume this is something basic to do with passing arguments causing the GitVersion.yml to not be loaded properly?

## Your Environment

v6.0.0-beta.3
GNU Linux, Bash 5
x64 binary from GitHub Releases

GitVersion.yml:

```yml
---
mode: ContinuousDelivery
branches:  
   master:  
      regex: ^custom-master$
ignore:
  sha: []
merge-message-formats: {}
next-version: '1.0.0'
```

```bash
$ gitversion -output file -outputfile gitversion.json -l gitversion.log -nocache;  grep '"SemVer"' gitversion.json 
  "SemVer": "1.8.0-custom-master.1"
```

```bash
$ gitversion -diag |  grep '"SemVer"'
  "SemVer": "1.8.0-custom-master.1"
```

```bash
$ gitversion | grep '"SemVer"'
  "SemVer": "1.8.0"
```

This is not the same behaviour as v5.12.0 which acts appropriately, giving 1.8.0 in all cases.

**Comment by HHobeck** [comment]
Hi @Zordrak.

I'm actually not sure what exactly your scenario is. In beta.3 you have two features:

- unknown branches which can be configured in JSON branches -> unknown
- and fallback branch configuration which can be found on the root configuration level

Please notice that you have specified master branch name not main. Thus GitVersion uses label {BranchName} instead of empty label.

Please take a look to the following default base configuration (GitFlow/v1): https://github.com/GitTools/GitVersion/blob/main/src/GitVersion.Configuration/SupportedWorkflows/GitFlow/v1.yml

**Comment by Zordrak** [comment]
I think you may have missed the point of the bug.

The behaviour is changed by the passing of command line flags.

`gitversion` and `gitversion -diag` and `gitversion -output file -outputfile gitversion.json` should produce the same SemVer regardless of the configuration.

**Comment by HHobeck** [comment]
Hi. I have taken your example and have verified it that it is working and not reproducable. Can you please provide steps to reproduce?

Thank you

**Comment by HHobeck** [comment]
> This is not the same behaviour as v5.12.0 which acts appropriately, giving 1.8.0 in all cases.

Giving the result of `1.8.0-custom-master.1` back is fully correct why do you expecting 1.8.0?

**Comment by HHobeck** [comment]
![image](https://github.com/GitTools/GitVersion/assets/56404113/bcf8a33e-b65f-4733-92bf-cbce6e5c4de8)

![image](https://github.com/GitTools/GitVersion/assets/56404113/6fffff61-b4a7-40c2-a292-4f6280efea88)

**Comment by Zordrak** [comment]
I am doing what I can to create completely generic reproduction steps, but it's difficult to know exactly where it's happening in the release repo I'm currently working on.

I thought that it was just an artifact of the change from acknowledging master to not acknowledging master, and maybe some code was still accounting for master by mistake.. but with GitVersion now pointing `main` at the custom branch I'm still getting a difference in 6b3 that isnt in 5.12.

GitVersion.yml
```
---
mode: ContinuousDelivery
branches:
  main:        
    regex: ^custom-master$
  develop:  
    regex: ^custom-develop$
ignore:
  sha: []
merge-message-formats: {}
next-version: '1.0.0'
```

On branch `custom-master` with HEAD~1 tagged with both v1.9.0-beta.1 & tag: v1.9.0-alpha.1

*6b3 with -diag flag*: `1.9.0-1`
```
$ ../gitversion-6.0.0-beta.3 -diag | grep \"SemVer\"
  "SemVer": "1.9.0-1",
```

*6b3 without flags*: `1.9.0`
```
$ ../gitversion-6.0.0-beta.3 | grep \"SemVer\"
  "SemVer": "1.9.0",
```

*5.12 with -diag flag*: `1.9.0`
```
$ ../gitversion-5.12.0 -diag | grep \"SemVer\"
  "SemVer": "1.9.0",
```

*5.12 without flags*: `1.9.0`
```
$ ../gitversion-5.12.0 | grep \"SemVer\"
  "SemVer": "1.9.0",
```

I will let you know when I get a generic reproducable, which might have to wait until I'm done with the feature I'm delivering, but there's *definitely* something shonky going on when 6.0.0-beta.3 is passed command line arguments.
