### ISSUE TITLE
[Bug] 6.0 Beta 4 gitversion.msbuild with dotnet build

### ISSUE THREAD

**Issue by christophwille** [GitTools/GitVersion#3832]
When I add 6.0-b4 msbuild nuget, it works fine in VS. When executing `dotnet build` on the command line it fails when executing

`dotnet --roll-forward Major "C:\Users\chwille\.nuget\packages\gitversion.msbuild\6.0.0-beta.4\tools\/gitversion.dll" "C:\Workspace\src\myProject"  -output file -outputfile obj\gitversion.json`

(exit code 1)

When I run this separately (in the same directory as dotnet build) I get

```
Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET program, but dotnet---roll-forward does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.
```

**Comment by arturcic** [comment]
Can you run in a cmd this piece directly?
`dotnet --roll-forward Major "C:\Users\chwille\.nuget\packages\gitversion.msbuild\6.0.0-beta.4\tools\/gitversion.dll" "C:\Workspace\src\myProject"  -output file -outputfile obj\gitversion.json`

**Comment by christophwille** [comment]
As I pointed out I did.

**Comment by christophwille** [comment]
@arturcic is it possible to get a new beta package on nuget.org?

**Comment by arturcic** [comment]
@christophwille at this moment I cannot give an estimation when we get this released.

There is PR that needs to be reviewed, and as far as I understand there will be a couple more related to the trunk based implementation.

Let me check with @HHobeck if we can have a beta5 before he finishes his work.

**Comment by HHobeck** [comment]
Until now there is only one PR merged to master which includes only preparation changes for the actual refactoring task. It is up to you:
- review the changes and go forward
- create a package for one bugfix ;)

**Comment by arturcic** [comment]
@christophwille may you give a try to the new beta?

**Comment by christophwille** [comment]
I just did - works fine (the last stumbling block was Azure DevOps doing shallow checkouts these days by default).
