### ISSUE TITLE
[Bug] LibGit2Sharp.InvalidSpecificationException: the given reference name is not valid

### ISSUE THREAD

**Issue by darwin-cjessen** [GitTools/GitVersion#3856]
**Describe the bug**
When running an AWS CodePipeline, the `gitversion /updateassemblyinfo /config GitVersion.yml` command is failing.  It appears to be related to the naming of the git branch when it is executed thru the pipeline as everything works as expected when executing the CodeBuild manually.

When running the AWS Pipeline, it runs the source code thru an AWS service called Codestar instead of the source repository.  Because of this, the naming scheme for the references has changed.  In the error below the referenced name is completely different than what is actually used in my git repository.  I believe something in the reference name is not compatible with GitVersion or perhaps more accurately LibGit2Sharp.

Here is the name reference that is erroring:
`refs/heads/origin/arn:aws:s3:::codepipeline-us-east-1-000000000000/stagetest/SourceArti/SXgcZ6P`

## Steps to Reproduce
1. In the AWS Pipeline, set the source as Full Clone.  Screenshot Attached.
![2024-01-04_15-06-28](https://github.com/GitTools/GitVersion/assets/39840655/9f131413-cc3b-4cf3-8e56-7c9871c27913)

2. In the AWS CodeBuild project add the following line to the pre_build->command entry in the yaml file
- dotnet gitversion /updateassemblyinfo /config GitVersion.yml

3. Run the AWS Pipeline.

## Actual Behavior
[Container] 2023/12/29 16:54:27.443319 Running command dotnet gitversion /updateassemblyinfo /config GitVersion.yml
INFO [12/29/23 16:54:27:69] Applicable build agent found: 'CodeBuild'.
INFO [12/29/23 16:54:27:75] Working directory: /codebuild/output/src2910330725/src/codestar-connections.us-east-1.amazonaws.com/git-http/000000000000/us-east-1/e7c2b99b-f81d-4fe3-8d41-60b8e05002a3/darwintt/darwin
INFO [12/29/23 16:54:27:76] Project root is: /codebuild/output/src2910330725/src/codestar-connections.us-east-1.amazonaws.com/git-http/000000000000/us-east-1/e7c2b99b-f81d-4fe3-8d41-60b8e05002a3/darwintt/darwin/
INFO [12/29/23 16:54:27:76] DotGit directory is: /codebuild/output/src2910330725/src/codestar-connections.us-east-1.amazonaws.com/git-http/000000000000/us-east-1/e7c2b99b-f81d-4fe3-8d41-60b8e05002a3/darwintt/darwin/.git
INFO [12/29/23 16:54:27:76] Branch from build environment: arn:aws:s3:::codepipeline-us-east-1-000000000000/stagetest/SourceArti/SXgcZ6P
INFO [12/29/23 16:54:27:76] -< Begin: Normalizing git directory for branch 'arn:aws:s3:::codepipeline-us-east-1-000000000000/stagetest/SourceArti/SXgcZ6P' >-
  INFO [12/29/23 16:54:27:78] One remote found (origin -> 'https://codestar-connections.us-east-1.amazonaws.com/git-http/000000000000/us-east-1/e7c2b99b-f81d-4fe3-8d41-60b8e05002a3/darwintt/darwin.git').
  INFO [12/29/23 16:54:27:78] Skipping fetching, if GitVersion does not calculate your version as expected you might need to allow fetching or use dynamic repositories
**INFO [12/29/23 16:54:27:79] -< End: Normalizing git directory for branch 'arn:aws:s3:::codepipeline-us-east-1-000000000000/stagetest/SourceArti/SXgcZ6P' (Took: 29.99ms) >-
ERROR [12/29/23 16:54:27:82] An unexpected error occurred:
LibGit2Sharp.InvalidSpecificationException: the given reference name 'refs/heads/origin/arn:aws:s3:::codepipeline-us-east-1-000000000000/stagetest/SourceArti/SXgcZ6P' is not valid**
   at LibGit2Sharp.Core.Ensure.HandleError(Int32 result) in /_/LibGit2Sharp/Core/Ensure.cs:line 154
   at LibGit2Sharp.Core.Ensure.ZeroResult(Int32 result) in /_/LibGit2Sharp/Core/Ensure.cs:line 172
   at LibGit2Sharp.Core.Proxy.git_reference_lookup(RepositoryHandle repo, String name, Boolean shouldThrowIfNotFound) in /_/LibGit2Sharp/Core/Proxy.cs:line 1953
   at LibGit2Sharp.ReferenceCollection.RetrieveReferencePtr(String referenceName, Boolean shouldThrowIfNotFound) in /_/LibGit2Sharp/ReferenceCollection.cs:line 676
   at LibGit2Sharp.ReferenceCollection.Resolve[T](String name) in /_/LibGit2Sharp/ReferenceCollection.cs:line 441
   at LibGit2Sharp.BranchCollection.BuildFromReferenceName(String canonicalName) in /_/LibGit2Sharp/BranchCollection.cs:line 82
   at LibGit2Sharp.BranchCollection.get_Item(String name) in /_/LibGit2Sharp/BranchCollection.cs:line 49
   at GitVersion.BranchCollection.get_Item(String name) in /_/src/GitVersion.LibGit2Sharp/Git/BranchCollection.cs:line 23
   at GitVersion.GitPreparer.EnsureLocalBranchExistsForCurrentBranch(IRemote remote, String currentBranch) in /_/src/GitVersion.Core/Core/GitPreparer.cs:line 382
   at GitVersion.GitPreparer.NormalizeGitDirectory(Boolean noFetch, String currentBranchName, Boolean isDynamicRepository) in /_/src/GitVersion.Core/Core/GitPreparer.cs:line 163
   at GitVersion.GitPreparer.NormalizeGitDirectory(String targetBranch, Boolean isDynamicRepository) in /_/src/GitVersion.Core/Core/GitPreparer.cs:line 134
   at GitVersion.GitPreparer.PrepareInternal(GitVersionOptions gitVersionOptions) in /_/src/GitVersion.Core/Core/GitPreparer.cs:line 69
   at GitVersion.GitPreparer.Prepare() in /_/src/GitVersion.Core/Core/GitPreparer.cs:line 48
   at GitVersion.GitVersionCalculateTool.CalculateVersionVariables() in /_/src/GitVersion.Core/Core/GitVersionCalculateTool.cs:line 44
   at GitVersion.GitVersionExecutor.RunGitVersionTool(GitVersionOptions gitVersionOptions) in /_/src/GitVersion.App/GitVersionExecutor.cs:line 66
INFO [12/29/23 16:54:27:82] Attempting to show the current git graph (please include in issue): 
INFO [12/29/23 16:54:27:82] Showing max of 100 commits
INFO [12/29/23 16:54:27:89] * 92978420b 19 hours ago  (HEAD -> develop, origin/develop)
* 014352ffc 19 hours ago 
* aaf9b626a 20 hours ago 
* 1ecadbd89 22 hours ago 
* c6abe6109 24 hours ago 
* b950db8c1 24 hours ago 
* 9e8577d52 2 days ago 
* 55492ea1e 9 days ago 
* ab6a6ea8a 9 days ago 
* 7692be524 10 days ago  (tag: 3.10, origin/release/v3.10, origin/master, release/v3.10, master)
* fc68e8db3 10 days ago 
* 13a7406e0 10 days ago 
* a9993c23a 11 days ago 
* 798f437be 11 days ago 
* 722e024b1 11 days ago 
* 367d77af2 11 days ago 
* 69571ec05 2 weeks ago 
* 692f0feb1 2 weeks ago 
* 230052cc3 2 weeks ago 
* 5049fde40 2 weeks ago 
* 2d10159d5 2 weeks ago 
* 203fba8d5 2 weeks ago 
* 6767b2c19 2 weeks ago 
* 2a06f39e9 2 weeks ago 
* 2fe28726e 2 weeks ago 
* e50610b40 3 weeks ago 
* 79a7f9486 3 weeks ago 
* 4a1e9cda4 3 weeks ago 
* 9617e0aff 3 weeks ago 
* cc74516f3 3 weeks ago 
* 98cf1a0a1 3 weeks ago 
* cc686163e 3 weeks ago 
* ea4f5547b 3 weeks ago 
* 380ca8dd2 3 weeks ago  (origin/release/v3.09, release/v3.09)
* d7cf99dee 3 weeks ago 
* e2fb64574 4 weeks ago 
* 6a781edf7 4 weeks ago 
* 302766a6c 4 weeks ago 
* 8e0b82196 4 weeks ago 
* 677b5b153 4 weeks ago 
* 6c0d596b2 4 weeks ago 
* 34631b167 4 weeks ago 
* f9e41b3fc 4 weeks ago 
* 2ba5fc154 4 weeks ago 
* 828788976 4 weeks ago 
* cf69b9ed2 4 weeks ago 
* 56c6d0e6e 4 weeks ago 
* 3c4bd53aa 4 weeks ago  (origin/hotfix/v3.08.02, hotfix/v3.08.02)
* cf83399a5 4 weeks ago  (origin/hotfix/v3.08.01, hotfix/v3.08.01)
* d392ade55 4 weeks ago 
* 00a4dceb6 5 weeks ago 
* e2fec580d 5 weeks ago 
* 4e4db9365 5 weeks ago 
* fb2a39c84 5 weeks ago 
* ac12903b2 6 weeks ago 
* 08d55ca34 6 weeks ago 
* 4233262c8 6 weeks ago 
* f9b7251ce 6 weeks ago 
* e6e897b45 6 weeks ago 
* 649cfe9f3 6 weeks ago 
* 7d454cc85 6 weeks ago  (origin/release/v3.08, release/v3.08)
* 4fddaeb59 7 weeks ago 
* aa849a25a 7 weeks ago 
* 3399d08d7 7 weeks ago 
* c43d76d35 7 weeks ago 
* 90eacbc26 7 weeks ago 
* 6e09a6191 7 weeks ago 
* 89002b1b7 7 weeks ago 
* ed3f72adc 7 weeks ago 
* c3b662ced 7 weeks ago 
* a3effe472 7 weeks ago 
* 796a11284 7 weeks ago 
* dfcd08832 7 weeks ago 
* 3156eaf7d 7 weeks ago 
* 148b9b4a2 7 weeks ago 
* 6652eb78b 7 weeks ago 
* 98f897876 7 weeks ago 
* 6311aa5e3 7 weeks ago 
* 5920fa52e 7 weeks ago 
* 2530af3ce 7 weeks ago 
* e2ee658ed 8 weeks ago 
* 4f01cf3be 8 weeks ago 
* a0dae842e 8 weeks ago  (origin/release/v3.07, release/v3.07)
* 630760636 8 weeks ago 
* df356ed7d 9 weeks ago 
* 5e43a6a7f 9 weeks ago 
* be93f23b1 9 weeks ago 
* 712036863 9 weeks ago 
* ddbd1fea0 9 weeks ago 
* 28eff6255 9 weeks ago 
* 99ec508d7 9 weeks ago 
* e86efd020 9 weeks ago 
* abaa82375 9 weeks ago 
*   3d62813d9 9 weeks ago 
|\  
| * 3f7f5fce2 9 weeks ago  (origin/hotfix/v3.06.02, hotfix/v3.06.02)
* | 321223d3a 9 weeks ago 
* | c6785242e 9 weeks ago 
* | 531383243 9 weeks ago 
* | 7e84be988 9 weeks ago 
|\| 
| * 7994ebdc7 9 weeks ago  (origin/hotfix/v3.06.01, hotfix/v3.06.01)

**Comment by HHobeck** [comment]
Please provide steps to reproduce and give more information about the context. Thank you.

**Comment by darwin-cjessen** [comment]
Steps added.  Also added more context on what I believe is happening in the bug description.

**Comment by HHobeck** [comment]
I think you need to investigate this problem in more detail and find the root cause. Why do you think it is a problem in GitVersion? Obviously in the repository a branch with the name `arn:aws:s3:::codepipeline-us-east-1-000000000000/stagetest/SourceArti/SXgcZ6P` existing which is not a valid name for a branch.

If I try to setup a git-repository with this name I'm getting the following error:
```
$ git switch -c arn:aws:s3:::codepipeline-us-east-1-000000000000/stagetest/SourceArti/SXgcZ6P
fatal: 'arn:aws:s3:::codepipeline-us-east-1-000000000000/stagetest/SourceArti/SXgcZ6P' is not a valid branch name
```

- Maybe it's an idea to ask the AWS support team what the specification is and why the branch name is so cryptic.
- Save the workspace of the pipeline locally and try to reproduce it or take a look if you see the cryptic branch name.
- If you see the cryptic branch name in the git repository how would AWS create it? Is the repository maybe corrupted?

**Comment by darwin-cjessen** [comment]
Thanks to the help of AWS Support, we were able to resolve this issue.  As indicated above, AWS Packages up the source code in their Codestar product and the referenced branches do not meet naming standards in Git.  However, in CodeBuild script you can add the following line in the yaml file before the call to GitVersion:

- CODEBUILD_SOURCE_VERSION=develop

This will change the branch to the correct name and the script will continue to process successfully.
