### ISSUE TITLE
[Improvement] Need `/updateprojectfiles Directory.Build.props`

### ISSUE THREAD

**Issue by frg2089** [GitTools/GitVersion#3886]
**Is your improvement request related to a problem? Please describe.**
I'm using `Directory.Build.props` to manage projects, is there a command like this?
```shell
dotnet gitversion /updateprojectfiles Directory.Build.props
```

**Comment by asbjornu** [comment]
All [command line arguments are documented](https://gitversion.net/docs/usage/cli/arguments) and no such argument exists. But I see how something like that would be useful and would welcome a pull request adding it.

**Comment by jamiebarrow** [comment]
This would be a great feature. I'd rather update one `Directory.Build.props` file than have the tool find all `.csproj` files and update them all.
