### ISSUE TITLE
[ISSUE]: Patch version get bumped up on every commit without redefined `+semver: ` message

### ISSUE THREAD

**Issue by juicybaba** [GitTools/GitVersion#3941]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched [issues](https://github.com/GitTools/GitVersion/issues) to ensure it has not already been reported

### GitVersion package

AzureDevops task

### GitVersion version

5.12

### Operating system

Linux

### What are you seeing?

Creating a dedicated issue for Q3 in #3939 

Patch version get bumped up on every commit without redefined `+semver: ` message. I am using default config.
e.g. a commit message like `this is a dummy commit`

```
steps:
  - checkout: self
    fetchDepth: 0
    persistCredentials: true
  - task: gitversion/setup@0
    inputs:
      versionSpec: '5.x'
  - task: gitversion/execute@0
    name: version
  - script: |
      echo "Major: $(version.major)"
      echo "Minor: $(version.minor)"
      echo "Patch: $(version.patch)"
      echo "PreReleaseTag: $(version.preReleaseTag)"
      echo "PreReleaseTagWithDash: $(version.preReleaseTagWithDash)"
      echo "PreReleaseLabel: $(version.preReleaseLabel)"
      echo "PreReleaseNumber: $(version.preReleaseNumber)"
      echo "WeightedPreReleaseNumber: $(version.weightedPreReleaseNumber)"
      echo "BuildMetaData: $(version.buildMetaData)"
      echo "BuildMetaDataPadded: $(version.buildMetaDataPadded)"
      echo "FullBuildMetaData: $(version.fullBuildMetaData)"
      echo "MajorMinorPatch: $(version.majorMinorPatch)"
      echo "SemVer: $(version.semVer)"
      echo "LegacySemVer: $(version.legacySemVer)"
      echo "LegacySemVerPadded: $(version.legacySemVerPadded)"
      echo "AssemblySemVer: $(version.assemblySemVer)"
      echo "AssemblySemFileVer: $(version.assemblySemFileVer)"
      echo "FullSemVer: $(version.fullSemVer)"
      echo "InformationalVersion: $(version.informationalVersion)"
      echo "BranchName: $(version.branchName)"
      echo "EscapedBranchName: $(version.escapedBranchName)"
      echo "Sha: $(version.sha)"
      echo "ShortSha: $(version.shortSha)"
      echo "NuGetVersionV2: $(version.nuGetVersionV2)"
      echo "NuGetVersion: $(version.nuGetVersion)"
      echo "NuGetPreReleaseTagV2: $(version.nuGetPreReleaseTagV2)"
      echo "NuGetPreReleaseTag: $(version.nuGetPreReleaseTag)"
      echo "VersionSourceSha: $(version.versionSourceSha)"
      echo "CommitsSinceVersionSource: $(version.commitsSinceVersionSource)"
      echo "CommitsSinceVersionSourcePadded: $(version.commitsSinceVersionSourcePadded)"
      echo "UncommittedChanges: $(version.uncommittedChanges)"
      echo "CommitDate: $(version.commitDate)"
  - script: |
      git tag v$(version.MajorMinorPatch)
      git push origin v$(version.MajorMinorPatch)
      git tag -f v$(version.Major)
      git push origin -f v$(version.Major)
```

### What is expected?

no tag should be created.

### Steps to Reproduce

setup gitversion in azure devops task without customized config and add random value in commit message

**Comment by HHobeck** [comment]
@juicybaba: Please provide the console output as well. Does this problem occuring in the preview version of gitversion as well?

```yaml
  - task: gitversion/setup@0
    inputs:
      versionSpec: '6.x'
      includePrerelease: true
```

**Comment by HHobeck** [comment]
What do you mean with on every commit it is incremented? Please provide steps to reproduce. It is not clear documented in this issue what the history of you repository is and what the checkout branch is. In advanced please notice: The main branch for gitflow has per default a patch increment. Why do you think it is a bug?

**Comment by juicybaba** [comment]
> What do you mean with on every commit it is incremented? Please provide steps to reproduce. It is not clear documented in this issue what the history of you repository is and what the checkout branch is. In advance please notice: The main branch for gitflow workflows has per default a patch increment. Why do you think it is a bug?
> 
> Edit: If you don't like the behavior you can change the configuration and set the patch increment to none. Please let me know if this solves your problem.

Hi @HHobeck, thanks for your advice, the pipeline behave the same with `6.x`. 

To be clear, my following comments are based on commit against default branch and no local configuration file in place. 

Correct me if I am wrong, based on the attached screenshot, no tag increment unless the commit message contains `+semver:  <key word>` by default. 

I am ok if random commit message create a patch increment, although it is kinda against the purpose of patch-version-bump-message.

This is where I got the 
![image](https://github.com/GitTools/GitVersion/assets/79539850/eb346599-427b-4ab6-b391-7bbb5d2bbe7c)

**Comment by HHobeck** [comment]
> To be clear, my following comments are based on commit against default branch(`main`) and no local configuration file in place.
> 
> Correct me if I am wrong, based on the attached screenshot, no tag increment unless the commit message contains `+semver: <key word>` by default.
> 
> I am ok if random commit message create a patch increment, although it is kinda against the purpose of patch-version-bump-message.

Yes that is the behavior of GitVersion. If you define an increment on the main branch to patch, then the next version will be incremented independent of whether you have defined a bumb message or not.

Please the the documentation [here](https://gitversion.net/docs/learn/branching-strategies/gitflow/examples)

I'm closing this issue. Happy Branching.
