### ISSUE TITLE
When using workflow TrunkBased/v1 after version 0.1.9.0 comes  0.1.0.0

### ISSUE THREAD

**Issue by mdmoura** [GitTools/GitVersion#3989]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched [issues](https://github.com/GitTools/GitVersion/issues) to ensure it has not already been reported

### GitVersion package

gittools/actions

### GitVersion version

6.0.0-beta.7

### Operating system

N/A

### What are you seeing?

Using GitVersion on a GitHub action with workflow `TrunkBased/v1` the version after 0.1.9.0 is 0.1.0.0  

### What is expected?

I am expecting the version after `0.1.9.0` would be `0.1.10.0`

### Steps to Reproduce

I am using GitVersion on a GitHub action as follows:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
 
      - name: GitVersion
        uses: gittools/actions/gitversion/setup@v1
        with:
          versionSpec: 6.x
          includePrerelease: true

      - name: Versioning
        uses: gittools/actions/gitversion/execute@v1
        id: versioning
        with:
          useConfigFile: true
          configFilePath: gitversion.yml

And the `gitversion.yml` is simply:

    workflow: TrunkBased/v1

I created the tag `v0.1.0` and pushed a few commits.

The version was incremented as follows:

    0.1.0.0, 0.1.1.0, 0.1.2.0, ...

But when it reaches `0.1.9.0` the next commit gets the version `0.1.0.0`.

**Comment by HHobeck** [comment]
Hi Miguel.

I have tried to reproduce this issue in azure devops without success. The following integration test proofs your scenario and has been executed with the code base of 6.0.0-beta.7 without any problems:

```csharp
[Test]
public void JustATest()
{
	var configuration = TrunkBasedConfigurationBuilder.New.Build();

	using var fixture = new EmptyRepositoryFixture("main");

	fixture.MakeACommit("A");

	// ✅ succeeds as expected
	fixture.AssertFullSemver("0.0.1", configuration);

	fixture.ApplyTag("0.1.0");

	for (int i = 0; i < 10; i++) fixture.MakeACommit();

	// ✅ succeeds as expected
	fixture.AssertFullSemver("0.1.10", configuration);
}
```

Could you please provide a repository or analyze your scenario in more detail?
