### ISSUE TITLE
[ISSUE]: v6 Beta 7 Msbuild Task failing again

### ISSUE THREAD

**Issue by christophwille** [GitTools/GitVersion#3999]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched [issues](https://github.com/GitTools/GitVersion/issues) to ensure it has not already been reported

### GitVersion package

GitVersion.MsBuild

### GitVersion version

6.0.0-beta.7

### Operating system

Linux, Windows

### What are you seeing?

#3832 that was fixed and working a-ok for months now (we were using Beta 5). Today I tried upgrading, and I seem to be back at square one again.

```
C:\Users\myusername\.nuget\packages\gitversion.msbuild\6.0.0-beta.7\tools\GitVersion.MsBuild.targets(21,9): error MSB3073:
 The command "dotnet --roll-forward Major "C:\Users\myusername\.nuget\packages\gitversion.msbuild\6.0.0-beta.7\tools\net8.
0/gitversion.dll" "C:\Workspace\myProject"  -output file -outputfile "obj\gi
tversion.json"" exited with code 1. [C:\Workspace\myProject\myProject.csproj]
```

### What is expected?

n/a

### Steps to Reproduce

Visual Studio is again not balking (building a-ok), only `dotnet build` on the command line - as stated, locally on Windows as well as on Linux on the build server.

**Comment by christophwille** [comment]
I ran the command manually (omitted the cache infos):

```
WARN [04/11/24 9:45:49:31] An error occurred:
Could not build the configuration instance because following exception occurred: 'Requested value 'Mainline' was not found.' Please ensure that the /overrideconfig parameters are correct and the configuration file is in the correct format.
```

Did something in the config files change from b5 to b7 that I missed in the release notes?

**Comment by christophwille** [comment]
My gitversion.yml (I think created back in the day using gitversion init, not modified):

```
merge-message-formats: {}
update-build-number: true
semantic-version-format: Strict
branches: {}
ignore:
  sha: []
mode: Mainline
increment: None
source-branches: []
is-source-branch-for: []
```

**Comment by asbjornu** [comment]
`mode: Mainline` is temporarily gone in beta 7. We might bring it back in beta 8, right @HHobeck?

**Comment by HHobeck** [comment]
The mainline mode has been deprecated and will be not available anymore. The mode has been renamed from versioning mode to deployment mode and can be seen just as a option to specify how the semantic version will be printed. Thus the deployment mode option has no influence how the version will be determined in general. Therefor the version strategy implementation are there.

This question has been answered in following discussion already:
https://github.com/GitTools/GitVersion/discussions/3949#discussioncomment-8730542
