### ISSUE TITLE
No command line setting to Include untracked branches when calculating versions

### ISSUE THREAD

**Issue by anobleperson** [GitTools/GitVersion#400]
TFS build for Git checks out the remote branch, which means there are no local branches, hence for GitVersion to work it needs to use untracked branches. There is no command line option for that.

**Comment by JakeGinnivan** [comment]
I want to understand this a little better.

How does TFS actually check it out? 

I think we need a `TeamBuildServer` which inherits from `BuildServerBase`. The other build servers use this helper: `GitHelper.NormalizeGitDirectory(gitDirectory, authentication);` which will turn remote tracking branches into local branches so GitVersion can work effectively. If this approach works for TFS too then we don't need a new command line argument

**Comment by anobleperson** [comment]
Thanks, that does help my understanding of what the Normalize does. I started down that path, but I must admit I couldn't see how it worked or would work for me. We run this as either local or build machine builds, so the same command is run for both environments.  I'm happy to have another crack at it. I still need it to output the same JSON or set the environment variables so the script can pick it up and update the build info.

Whilst I can't see exactly what TFS is doing, it appears to just fetch-all and then checkout the remote branch. So we end up with a local master, and remote branch.

**Comment by JakeGinnivan** [comment]
The build server stuff looks for environmental variables which are set by each build server.

TeamCity also just checks out the remote branch, we match the HEAD to the remote branch and it should work ok

**Comment by JakeGinnivan** [comment]
Created #518 to investigate and document usage with TFS Team Build
