### ISSUE TITLE
[ISSUE]: Regex Capture Groups don't work correctly on release branch.

### ISSUE THREAD

**Issue by BenB196** [GitTools/GitVersion#4019]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched [issues](https://github.com/GitTools/GitVersion/issues) to ensure it has not already been reported

### GitVersion package

GitVersion.Tool

### GitVersion version

6.0.0-beta.7-alpine.3.18-7.0

### Operating system

Linux

### What are you seeing?

I am seeing GitVersion not properly do regex capture grouping and returning invalid versions/labels.

Example:

```
GitVersion_SemVer=0.2.0-beta{SubBranchName}.1
GitVersion_FullSemVer=0.2.0-beta{SubBranchName}.1+0
```

### What is expected?

I would expect `{SubBranchName}` to be a proper value:

Example:

```
GitVersion_SemVer=0.2.0-beta-bravo.1
GitVersion_FullSemVer=0.2.0-beta-bravo.1+0
```

### Steps to Reproduce

1. Use a default GitVersion.yml set to `mode: ContinuousDelivery`
2. Update the `release` branch configuration to look like:
```yaml
release:
  regex: ^releases?[/-]\d+(?:.\d+)?(?:.\d+)(?<SubBranchName>.*)
  label: 'beta{SubBranchName}'
```
3. Run GitVersion against a branch named `release/0.2.0`
Observe the correct output:
```
GitVersion_SemVer=0.2.0-beta.1
```
4. Run GitVersion against a branch named `release/0.2.0-bravo`
Observe the incorrect output:
```
GitVersion_SemVer=0.2.0-beta{SubBranchName}.1
```

**Comment by HHobeck** [comment]
The functionality to "Support Regex for label property" was implemented in this PR:
- https://github.com/GitTools/GitVersion/pull/3687

I agree that the behavior you are describing here is not intuitive. If you like please fix this and create a pull request for it:

- Change the relase and hotfix regex in GitFlowConfigurationBuilder and GitHubFlowConfigurationBuilder to support branch name override natively (label: {SubBranchName} ?? beta)
- Change the workflow resources in src\GitVersion.Configuration\Workflows
- Remove branchNameOverride parameter in ConfigurationExtensions::GetBranchSpecificLabel
- Change the logic in GetBranchSpecificLabel and use dynamic string interpolation
- Create integration tests

![image](https://github.com/GitTools/GitVersion/assets/56404113/84c558ee-85bd-44ef-9820-5dd675f0a62f)

**Comment by HHobeck** [comment]
@asbjornu please confirm

**Comment by asbjornu** [comment]
Sounds reasonable. As long as no existing tests fail, I'm positive. :)
