### ISSUE TITLE
It would be nice to redirect the json output to a file rather than console

### ISSUE THREAD

**Issue by anobleperson** [GitTools/GitVersion#404]
Some script languages make it hard to extract information sent to the console (looking at you Powershell!) so it would be nice to send the output to a file instead.

**Comment by gep13** [comment]
@anobleperson I am just curious, what exactly is hard about doing this in PowerShell?  I do this internally at work, and I don't have an issue doing it.  I am not back in the office until Tuesday, but I can certainly dig out the code when I get back if it would help.  Also, assuming you are running on a build server, why not simply read the generated version number information from Environment Variables?

**Comment by SimonCropp** [comment]
Isnt it a case of using outfile? http://www.computerperformance.co.uk/powershell/powershell_file_outfile.htm#Example_1_-_Starting_with_Out-File

**Comment by anobleperson** [comment]
@SimonCropp  Unfortunately it's not that simple. We run it as a separate process ($process = [Diagnostics.Process]::Start($startInfo)), so then we need to capture the output, which means either hooking the async screen updates, or waiting until the process completes and capturing the output. If there is an error then something goes weird in the output stream and it waits for a timeout (30mins) before continuing.

@gep13 I'd be interested in how you execute the commands.

**Comment by gep13** [comment]
@andreasohlund I checked in-house, and we are using the approach documented here: http://jake.ginnivan.net/blog/2014/05/25/simple-versioning-and-release-notes/ by @JakeGinnivan without any problems.

**Comment by JakeGinnivan** [comment]
Whats the status of this? Can we close it or create a `up-for-grabs` issue with a clear plan?

**Comment by gep13** [comment]
For my point of view, and my understanding of how GitVersion, GitReleaseNotes, and GitReleaseManager will interact, I think it would still be a nice to have.

**Comment by JakeGinnivan** [comment]
@gep13 yeah, I agree. Could you create an up-for-grabs issue with well laid out requirements?

**Comment by gep13** [comment]
Yip, let me try to do that tonight.

**Comment by JakeGinnivan** [comment]
Bump, just putting together release notes. Also related discussion in #534
