### ISSUE TITLE
gitversion from container image default behaviour differs from other installation methods

### ISSUE THREAD

**Issue by f2calv** [GitTools/GitVersion#4042]
Hi,

Firstly, love GitVersion, thanks to all contributors :)

Secondly, I've been experimenting with different methods of installing GitVersion in my GitHub workflows and believe I've found an anomaly in the containerised version... or at least something I can't explain, so I hope someone can shed some light here...

I one workflow am runinng 3 parallel jobs, each installing and executing GitVersion via 3 different mechanisms;
- offical gittools actions
- dotnet tool
- container image

Here is the workflow I am executing;
https://github.com/f2calv/playground-gitversion/blob/f2calv/2024-05-checkout-testing/.github/workflows/test.yml

On a simple push trigger everything works as expected, actions/checkout checks out the HEAD;
- https://github.com/f2calv/playground-gitversion/actions/runs/9249843512
![image](https://github.com/GitTools/build-images/assets/16097639/9143d9fe-f41f-4250-aa4f-5eecf89ce9e8)

On a Pull Request trigger the containerised version of GitVersion fails, actions/checkout checks out a MERGE commit;
- https://github.com/f2calv/playground-gitversion/actions/runs/9249843653
![image](https://github.com/GitTools/build-images/assets/16097639/bc547831-1dbb-4025-8a83-fcf540e07f7d)

The initial error is [ERROR: fatal: detected dubious ownership in repository at '/repo'](https://github.com/f2calv/playground-gitversion/actions/runs/9249843653/job/25442316315#step:4:51). If I then attempt to override the entrypoint in the container by setting safe.directory then GitVersion executes a little further but ultimately fails with [Gitversion could not determine which branch to treat as the development branch](https://github.com/f2calv/playground-gitversion/actions/runs/9249843653/job/25442316637#step:3:76), I got the safe-directory idea from another issue https://github.com/GitTools/build-images/issues/34.

I would expect all three installation mechanisms of GitVersion to act the same.

Note: If I override the actions/checkout ref with github.event.pull_request.head.sha [the containerised version works as expected](https://github.com/f2calv/playground-gitversion/actions/runs/9249843653/job/25442316748).

**Comment by arturcic** [comment]
@f2calv do you mind to test with the `rc.1` variants of the docker images? The `latest` tag is using an older version of the image and tool. https://hub.docker.com/r/gittools/gitversion/tags?page=&page_size=&ordering=&name=rc.1.

The `latest` will be moved to the 6.0 release soon and then the  https://github.com/GitTools/build-images/issues/34 will be included

**Comment by arturcic** [comment]
Additionally on GitHub Actions you need to specify these env vars https://github.com/GitTools/GitVersion/blob/main/build/common/Utilities/DockerContextExtensions.cs#L263-L270

**Comment by f2calv** [comment]
Thanks @arturcic for the pointers, sorry for delay, I have experimented with;
- **ENV vars** OR **no ENV vars**
- tag **latest** or **6-rc1**
- using my (default) GitVersion.yml config file OR no config file

Note: AFAIK this is just a default MainLine configuration file, I use the file mainly as an 'identifier' to let me/others know the repository versioning is managed by GitVersion;

```yaml
mode: Mainline
branches: {}
ignore:
  sha: []
merge-message-formats: {}
```

Push request build;
- https://github.com/f2calv/playground-gitversion/actions/runs/9621842304
  - the v6-rc1 job fails _with a config file_ error is 'Mainline' not found, I presume this is a breaking change in v6?

Pull request build;
- https://github.com/f2calv/playground-gitversion/actions/runs/9621842426
  - as above the v6-rc1 job fails _with a config file_ error is 'Mainline' not found, I presume this is a breaking change in v6?
  - latest tag always fails when used without ENV vars
  - strangely the dotnet version fails now, when it worked a some weeks ago?

Conclusions;
- ENV vars are most definitely needed to get success in a PR build (I didn't know this before)
- Config file format is important
- v6 has breaking changes in the config file

Did I miss anything?

**Comment by arturcic** [comment]
> Push request build;
> 
> * https://github.com/f2calv/playground-gitversion/actions/runs/9621842304
>   
>   * the v6-rc1 job fails _with a config file_ error is 'Mainline' not found, I presume this is a breaking change in v6?

Yes, please check https://github.com/GitTools/GitVersion/blob/main/BREAKING_CHANGES.md#configuration-changes



> * strangely the dotnet version fails now, when it worked a some weeks ago?

I check the log, I suspect you should re-run the job as it seems an GH Actions issue


> Conclusions;
> 
> * ENV vars are most definitely needed to get success in a PR build (I didn't know this before)
> * Config file format is important
> * v6 has breaking changes in the config file

Yes, you got it right, I think we need to update the docs on DockerHub and specify the usage when running in a CI environment
