### ISSUE TITLE
[ISSUE]: GitVersion AzDo task appears to be stuck at version 5.0.1

### ISSUE THREAD

**Issue by ericnewton76** [GitTools/GitVersion#4054]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched [issues](https://github.com/GitTools/GitVersion/issues) to ensure it has not already been reported

### GitVersion package

AzureDevops task

### GitVersion version

5.0.1

### Operating system

Windows

### What are you seeing?

The Gitversion azdo task (using 5.*) isnt pulling newest release of Gitversion, its using 5.0.1

### What is expected?

The task probably needs a versionSpec in the task UI (using Classic AZDO pipeline definition for the moment)

Guessing the yaml version pulls the correct version?

### Steps to Reproduce

Gitversion azdo task, classic pipeline

Observe gitversion being pulled:
![image](https://github.com/GitTools/GitVersion/assets/2211788/e76f057f-df8b-44fd-b2b4-137e122c35a7)

Also, the Gitversion info log should first emit its version number in very beginning.  I could only figure out the version number by going onto a local hosted agent, navigating into the task directory and running `Gitversion /version` to see 5.0.1

NOTE, the root cause is GitVersion 5.0.1 calculating the Nuget version incorrectly as 3.6.0-beta0001 when it should be 3.6.0-beta0022 since its 22 commits since last

### Output log or link to your CI build (if appropriate).

```
   see attached
[rawlog.txt](https://github.com/user-attachments/files/15741871/rawlog.txt)


```

**Comment by arturcic** [comment]
@ericnewton76 you're using an old unsupported task, please use this instead https://marketplace.visualstudio.com/items?itemName=gittools.gittools
