### ISSUE TITLE
[ISSUE]: `init` command still shown in the help output

### ISSUE THREAD

**Issue by CJCombrink** [GitTools/GitVersion#4060]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched [issues](https://github.com/GitTools/GitVersion/issues) to ensure it has not already been reported

### GitVersion package

GitVersion.Tool

### GitVersion version

6.0.0-rc.1+Branch.main.Sha.0452c2e74f50ec6c68abafcd589690394a383153

### Operating system

N/A

### What are you seeing?

When running `giversion /?` the init command is still shown as an option

### What is expected?

Since the `init` command was removed, I would not expect the command to still be shown when asking for help
Related #3900 and https://github.com/GitTools/GitVersion/discussions/4001#discussioncomment-9092014

### Steps to Reproduce

```
gitversion /?
```

**Comment by arturcic** [comment]
@CJCombrink good catch!!
