### ISSUE TITLE
[ISSUE]: GitVersion.Model.Exceptions.InfiniteLoopProtectionException: Inherited branch configuration caused 50 recursions. Aborting!

### ISSUE THREAD

**Issue by FeynmanFan** [GitTools/GitVersion#4105]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched [issues](https://github.com/GitTools/GitVersion/issues) to ensure it has not already been reported

### GitVersion package

AzureDevops task

### GitVersion version

5.12.0

### Operating system

macOS

### What are you seeing?

When executing a build on our _develop_ branch, either in a merge attempt or directly, we receive the following error in our build logs:

```
ERROR [07/18/24 14:09:19:18] An unexpected error occurred:
GitVersion.Model.Exceptions.InfiniteLoopProtectionException: Inherited branch configuration caused 50 recursions. Aborting!
```

That is followed by thousands of lines of branches (this is a pretty old repo with many stale branches), and this message:

`Falling back to develop branch config`
Many more lines of a Git tree, and then finally this error message:

`##[error]TypeError: Cannot read property 'message' of undefined`

The last message is clearly that it's unable to read from a null commit. I have a general Git sense here that we're dealing with an orphaned commit - is that correct? I pulled the code locally, built it, and ran it with the same args against a local copy of _develop_, and it worked fine.

I would appreciate a fix, or at least some more information on what is going wrong here and how it could fixed.

### What is expected?

Either a direct fix with a release, or a workaround. There may be a git operation that could clear the problem - I just need to know what that is.

### Steps to Reproduce

I'm unable to reproduce this even with the same git repo, so it seems like a deep understanding of the code and the exception is the only way to fix.

**Comment by HHobeck** [comment]
Hi there.

Thank you very much for reporting this issue. If you not mind, please migrate to the new version [6.0.0](https://github.com/GitTools/GitVersion/releases/tag/6.0.0). If this problem remains please report it again.

Thank you.
