### ISSUE TITLE
[ISSUE]: Errors with NugetVersionV2 variable and FullSemVer

### ISSUE THREAD

**Issue by brianpendell** [GitTools/GitVersion#4120]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched [issues](https://github.com/GitTools/GitVersion/issues) to ensure it has not already been reported

### GitVersion package

GitVersion.Tool, GitVersion.MsBuild

### GitVersion version

6.0.0

### Operating system

Centos7

### What are you seeing?

Attempt the command 

dotnet-gitversion /nofetch /showvariable NuGetVersionV2 /updateassemblyinfo

Receive error 
Unhandled exception. GitVersion.WarningException: /showvariable requires a valid version variable. Available variables are:
'Major', 'Minor', 'Patch', 'BuildMetaData', 'FullBuildMetaData', 'BranchName', 'EscapedBranchName', 'Sha', 'ShortSha', 'MajorMinorPatch', 'SemVer', 'FullSemVer', 'AssemblySemVer', 'AssemblySemFileVer', 'PreReleaseTag', 'PreReleaseTagWithDash', 'PreReleaseLabel', 'PreReleaseLabelWithDash', 'PreReleaseNumber', 'WeightedPreReleaseNumber', 'InformationalVersion', 'CommitDate', 'VersionSourceSha', 'CommitsSinceVersionSource', 'UncommittedChanges'

This worked in 5.2.0

Switching to FullSemVer variable, we attempt

dotnet-gitversion /showvariable FullSemVer /nofetch
And receive error 

Unhandled exception. System.TypeInitializationException: The type initializer for 'LibGit2Sharp.Core.NativeMethods' threw an exception.
 ---> System.DllNotFoundException: Unable to load shared library 'git2-a418d9d' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libgit2-a418d9d: cannot open shared object file: No such file or directory

### What is expected?

We should be able to retrieve the variable values without error. 

### Steps to Reproduce

We saw this as part of a Jenkins build running on CentOS 7. Hopefully, this can be reproduced directly from the console by simply executing 
dotnet-gitversion /nofetch /showvariable NuGetVersionV2 /updateassemblyinfo
or 
dotnet-gitversion /nofetch /showvariable FullSemVer  /updateassemblyinfo

**Comment by arturcic** [comment]
Please see https://github.com/GitTools/GitVersion/issues/2325

**Comment by rose-a** [comment]
@arturcic could you please add the list of removed variables to the breaking changes document?
