### ISSUE TITLE
[ISSUE]: Normalizing git directory fails with LibGit2Sharp.CheckoutConflictException

### ISSUE THREAD

**Issue by chufgard** [GitTools/GitVersion#4141]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched [issues](https://github.com/GitTools/GitVersion/issues) to ensure it has not already been reported

### GitVersion package

GitVersion.Tool

### GitVersion version

6.0.1+Branch.main.Sha.0fd23d1af997a7b7c6f22f27310443270a91fb18

### Operating system

N/A

### What are you seeing?

We are using gitversion dockerized with gittools/gitversion@sha256:7da8a14e5b04a7a1bbcae458914158cbc23b053e661b7901b21994c4f5ea6f46 in a gitlab pipeline. gitversion fails with a LibGit2Sharp.CheckoutConflictException during repo normalization. 

The problem does not occur when we use gittools/gitversion@sha256:9c64982ce2030f8c45a6d1331e2bfcf55c57780bd641f81fe0fbf837e9993f6a instead.

### What is expected?

gitversion runs without an exception

### Steps to Reproduce

I was not able to reproduce the problem outside of our pipeline yet.

**Comment by arturcic** [comment]
The fixes we did in 6.0.1 are not related to version calculation so I think that's an intermittent issue

**Comment by chufgard** [comment]
> The fixes we did in 6.0.1 are not related to version calculation so I think that's an intermittent issue

Our builds fail reproducible with the latest version and work with the previous one. Our workaround is to pin to the previous version. Maybe a dependency was updated in the lastest build and that one breaks it?

**Comment by monofone** [comment]
We encounter the same issue with 6.0.2 (Docker image) in the gitlab pipeline.

@chufgard do you mind sharing you call to git version in the pipeline run ?

**Comment by monofone** [comment]
Hi @arturcic,

I was able to reproduce it with different respositories in our setup.

1. clone repository with: git clone --filter=blob:none --no-checkout $CI_REPOSITORY_URL $CI_PROJECT_DIR
2. cd to $CI_PROJECT_DIR
3. docker run --rm -e GITLAB_CI=true -v `pwd`:/repo gittools/gitversion:6.0.2 /repo /b $CI_COMMIT_REF_NAME  /c $CI_COMMIT_SHA1

This yields the error in our case, also locally reproducable.

**Comment by monofone** [comment]
Uh, need to revoke my last comments, we have a different exception.

LibGit2Sharp.NotFoundException: object not found - no match for id

Will create a new issue, sorry for the noise.

**Comment by arturcic** [comment]
>  Our workaround is to pin to the previous version. Maybe a dependency was updated in the lastest build and that one breaks it?
 
Well actually that's the best practice to pin to a specific version any dependency, and test the next or other version before using it.

@chufgard, in order to understand your issue we need to have much more details then the docker sha you used
