### ISSUE TITLE
[ISSUE]: There's no NuGetVersionV2 anymore, and no zero-padded PreReleaseNumber

### ISSUE THREAD

**Issue by Jaykul** [GitTools/GitVersion#4153]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched [issues](https://github.com/GitTools/GitVersion/issues) to ensure it has not already been reported

### GitVersion package

GitVersion.Tool

### GitVersion version

6.0.1

### Operating system

N/A

### What are you seeing?

I was porting settings from a PowerShell module, and I get this error:

Unable to format AssemblyInformationalVersion.  Check your format string: 'NuGetVersionV2' is not a member of type 'GitVersion.SemanticVersionFormatValues' (Parameter 'propertyOrFieldName')

### What is expected?

I expected to be able to build a version like "1.2.3-beta0002" so I can upload packages to [the PowerShell gallery](https://powershellgallery.com). chocolatey, and other old nuget-based servers.

Note that the FAQ still refers to a NuGetVersionV2

### Steps to Reproduce

Try using this in your GitVersion.yml
```
assembly-informational-format: '{NuGetVersionV2}'
```

The FAQ still refers to a NuGetVersionV2

**Comment by arturcic** [comment]
Please see https://github.com/GitTools/GitVersion/blob/main/BREAKING_CHANGES.md#legacy-output-variables

**Comment by Jaykul** [comment]
So we need to stay on 5.x in order to version packages for anything that's not SemVer 2 -- like the official PowerShell gallery.

**Comment by asbjornu** [comment]
> So we need to stay on 5.x in order to version packages for anything that's not SemVer 2 -- like the official PowerShell gallery.

Unfortunately, yes. But as a fix to this issue and probably a few other issues as well, would be for GitVersion to support arbitrary C# format strings, so you could create your own padded version number as such:

```yaml
assembly-informational-format: '{Major}.{Minor}.{Patch}-{CommitsSinceVersionSource:0000}'
```

Something like that would be very powerful and definitely something I'd welcome pull requests for.

**Comment by HHobeck** [comment]
> > So we need to stay on 5.x in order to version packages for anything that's not SemVer 2 -- like the official PowerShell gallery.
> 
> Unfortunately, yes. But as a fix to this issue and probably a few other issues as well, would be for GitVersion to support arbitrary C# format strings, so you could create your own padded version number as such:
> 
> ```yaml
> assembly-informational-format: '{Major}.{Minor}.{Patch}-{CommitsSinceVersionSource:0000}'
> ```
> 
> Something like that would be very powerful and definitely something I'd welcome pull requests for.

Do you know if already a feature ticket has been raised for this?

**Comment by ericnewton76** [comment]
I'm actually baffled as to why NuGetVersion2 was removed... in favor of something more complicated like adding parsing of format strings into a config variable... ???

if NuGetVersionV2 was complicated to calculate then I can understand... theres a lot of people, inclding myself using GitVersion to properly calculate a usable NuGet version...

**Comment by 9swampy** [comment]
https://github.com/GitTools/GitVersion/pull/4605 pull request for review. HIH.
