### ISSUE TITLE
[ISSUE]: The version returned is NULL

### ISSUE THREAD

**Issue by MoeHamdan** [GitTools/GitVersion#4155]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched [issues](https://github.com/GitTools/GitVersion/issues) to ensure it has not already been reported

### GitVersion package

GitVersion.Tool

### GitVersion version

6.0.1

### Operating system

Linux

### What are you seeing?

GitVersion = {
   FullSemVer: 1.6.1-1250
   LegacySemVer: [NULL]
   MajorMinorPatch: 1.6.1
   InformationalVersion: 1.6.1-1250+Branch.master.Sha.9f0b84fc6cb09b9b026fd12402dd889306f0d8d5
   Nuget v2 version: [NULL]
}
Version to use: [NULL]

### What is expected?

Expected to get version value instead of [NULL}

GitVersion = {
   FullSemVer: 1.6.1+1250
   LegacySemVer: 1.6.1
   MajorMinorPatch: 1.6.1
   InformationalVersion: 1.6.1+1250.Branch.master.Sha.9f0b84fc6cb09b9b026fd12402dd889306f0d8d5
   Nuget v2 version: 1.6.1
}
Version to use: 1.6.1.1250

### Steps to Reproduce

Try get value for LegacySemVer or NuGetVersionV2

**Comment by arturcic** [comment]
We deprecated those values, see https://github.com/GitTools/GitVersion/issues/4153
