### ISSUE TITLE
[ISSUE]:  Wrong minor version

### ISSUE THREAD

**Issue by MoeHamdan** [GitTools/GitVersion#4162]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched [issues](https://github.com/GitTools/GitVersion/issues) to ensure it has not already been reported

### GitVersion package

GitVersion.Tool

### GitVersion version

6.0.2

### Operating system

Linux

### What are you seeing?

 MajorMinorPatch: 0.0.1

### What is expected?

 MajorMinorPatch: 0.1.0

### Steps to Reproduce

just get the  MajorMinorPatch: 0.1.0

**Comment by arturcic** [comment]
That was a breaking change in 6.x we introduced, @HHobeck can you elaborate on this one?

**Comment by HHobeck** [comment]
Sorry I don't understand this issue. Please express your scenario in a understandable and meaningful way. Just saying to expect a number instead of another number is not constructive.

Thank you.

**Comment by HHobeck** [comment]
> Hello @HHobeck When I use version 5.x and get the value of "MajorMinorPatch" I usually get the value 0.1.0, now when using the version 6.x, the value I get is 0.0.1.

Yes that is correct. In the breaking change doucment you will find the following:

> The fallback version strategy now returns 0.0.0 and is flagged with ShouldIncrement equal to true. This yields the version 0.1.0 on the develop branch (IncrementStrategy.Minor by default) and 0.0.1 on the main branch (IncremetnStrategy.Patch by default).

**Comment by MoeHamdan** [comment]
Thanks, last question, how would I make sure it is 0.1.0 on my feature branches?

**Comment by HHobeck** [comment]
```yaml
workflow: GitFlow/v1
branches:
  feature:
    increment: minor
```
