### ISSUE TITLE
[ISSUE]: Azure Devops GitVersion task upgrade internal gitversion.exe to 5.12.0

### ISSUE THREAD

**Issue by ericnewton76** [GitTools/GitVersion#4171]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched [issues](https://github.com/GitTools/GitVersion/issues) to ensure it has not already been reported

### GitVersion package

AzureDevops task

### GitVersion version

5.12.0

### Operating system

Windows

### What are you seeing?

Please do a final upgrade of the gitversion.exe contained within AzureDevopsTask of GitVersion to version 5.12.0

I have a bunch of "Classic Pipelines" that cant apparently utilize the newer "Azure GitTools Extensions" within Classic Pipelines (the non-yml pipelines)

### What is expected?

AzureDevopsTask internal gitversion.exe upgraded to 5.12.0

### Steps to Reproduce

Start a Classic pipeline, 
add a "GitVersion" task from marketplace
add /version to the commandline ran
run the pipeline
observe GitVersion 5.0.1 reported.

**Comment by ericnewton76** [comment]
Not having the internal gitversion.exe at version 5.12.0 causes me to have to run a hosted agent with gitversion.exe 5.12.0 available in the filesystem instead of being able to use a generic Azure VM hosted agent.

**Comment by arturcic** [comment]
Please use this extension instead https://marketplace.visualstudio.com/items?itemName=gittools.gittools, as this is the only one we support. And here are the docs https://github.com/GitTools/actions/blob/main/docs/examples/azure/gitversion/index.md

**Comment by ericnewton76** [comment]
Strangely enough, yesterday I looked again at the task list filtered on "gitversion" and the newer extension based tasks showed up.  Trying to get them integrated into the build now.

Can probably close this issue
