### ISSUE TITLE
GitVersion /debug switch

### ISSUE THREAD

**Issue by JakeGinnivan** [GitTools/GitVersion#421]
When stuff goes wrong it is hard to figure out why. The debug switch should automatically create a debug file which can be pasted into a gist or a github issue.

Things to include:
 - Sha of head
 - Current branch
 - The effective config
 - Maybe we should just dump the current context to a Json object which would include the previous 3?
 - Calculated version (full semver)
 - Version calculated by each of the base version providers
 - Last 30 commits on the commit log (that should be enough?) - maybe add `/commits` to specify more commits

**Comment by orjan** [comment]
+1

**Comment by asbjornu** [comment]
It would be great to have a method and recipe on how to force this switch on builds within Visual Studio with GitVersionTask. If dropping down to command line and running `MSBuild.exe` is the solution; fine, as long as it's documented along with the `debug` switch. :)

**Comment by JakeGinnivan** [comment]
To be honest this isn't really needed anymore. The log is enough.

**Comment by Shereef** [comment]
Where do I access such log if I am using msbuild ?
