### ISSUE TITLE
[ISSUE]: init cannot find the .git directory

### ISSUE THREAD

**Issue by GuidDotEmpty** [GitTools/GitVersion#4221]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched [issues](https://github.com/GitTools/GitVersion/issues) to ensure it has not already been reported

### GitVersion package

GitVersion.Tool

### GitVersion version

6.0.2 6.0.2+Branch.main.Sha.30211316bc16e481dc440baae39ff904c4fa4966

### Operating system

Windows

### What are you seeing?

When running the command `gitversion init` in a repo i get the text
`Cannot find the .git directory`

### What is expected?

I would expect to see output where i can setup my gitversion config

### Steps to Reproduce

1. Create an empty folder and open it
2.  Start a new command promt in the newly created folder
3. Run `git init`
4. Run `gitversion init`

### Output log or link to your CI build (if appropriate).

```shell
PS C:\Temp\sdsd> git init
Initialized empty Git repository in C:/Temp/sdsd/.git/
PS C:\Temp\sdsd> gitversion init
Cannot find the .git directory
PS C:\Temp\sdsd> gitversion /version
```

**Comment by arturcic** [comment]
`gitversion init` was removed in version 6 https://github.com/GitTools/GitVersion/pull/3899

**Comment by SamyakManandhar** [comment]
Hi @arturcic ,
Thank you for pointing that out, following the threads, as you have shared; https://github.com/GitTools/GitVersion/blob/main/docs/input/docs/reference/configuration.md#:~:text=GitVersion%20ships%20with,when%20using%20GitFlow.

**Confirming:** I DO NOT initialize GitVersion in my project, or populate my project with the GitVersion.yml file or any NuGet packages, instead, I would just use the GitTools task in my Azure DevOps CI/CD (Deployment) pipeline, and it would calculate use the default configuration to implement SemVer?

**Context:**
I am working an Asp.Net Blazor application hosted in Azure and Deployed via ADO, using pipeline artifacts,
GitVersion version: 6.3.0
.NET version: 9.0

Thank you in Advance.

**Comment by lloydjatkinson** [comment]
> `gitversion init` was removed in version 6 [#3899](https://github.com/GitTools/GitVersion/pull/3899)

Why do the docs still instruct users to use it?
