### ISSUE TITLE
[ISSUE]: dotnet tool install docs should not use an explicit --version arg

### ISSUE THREAD

**Issue by fourpastmidnight** [GitTools/GitVersion#4244]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have searched [issues](https://github.com/GitTools/GitVersion/issues) to ensure it has not already been reported

### GitVersion package

GitVersion.Tool

### GitVersion version

6.x

### Operating system

Windows

### What are you seeing?

I recently installed the dotnet tool for this project <ins>following the instructions on the documentation site: `dotnet tool install --global GitVersion.Tool --version 5.*`. ~: `dotnet tool -g gitversion`. Upon installation, running `dotnet gitversion /version` yields `5.12.0...`.~

I initially forgot I had supplied a `--version` parameter when installing, hence the genesis of this issue.

### What is expected?

~I was expecting v6.x which is the currently released version.~ I expect that the documentation would be updated to not include a `--version` flag in the example. Perhaps a notice sidebar could be added to the docs to point people to the `--version` flag if they need to install an older version of the GitVersion.Tools package, such as:

> [!NOTE]
> To install an older version of GitVersion.Tools, use the `--version` flag of `dotnet tool install`, e.g. `dotnet tool install GitVersion.Tool --global --version 5.*`

### Steps to Reproduce

In the Visual Studio Terminal:

```powershell
PS C:> dotnet tool -g install gitversion --version 5.*
PS C:> dotnet tool gitversion /version
5.12.0+Branch.support-5.x.Sha.3f75764963eb3d7956dcd5a40488c074dd9faf9e
```

**Comment by fourpastmidnight** [comment]
No, it's a documentation issue thing. Wish you wouldn't close an issue for errant docs 😒

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by asbjornu** [comment]
I agree that we should update [the installation instructions](https://gitversion.net/docs/usage/cli/installation) and either remove `--version` altogether or at least set it to version `6` and not `5` as it is now.

**Comment by fourpastmidnight** [comment]
I'd rather remove it altogether, but if deemed helpful, add a note as I demonstrated in the original issue. Thanks for reopening.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
