### ISSUE TITLE
[ISSUE]: <title>I'm getting this error in Azure devops Unhandled exception. GitVersion.WarningException: Could not parse Verbosity value 'Debug'  C:/ProgramData/Chocolatey/bin/GitVersion.exe" -output json -updateassemblyinfo -verbosity Debug

### ISSUE THREAD

**Issue by PraveenRsys** [GitTools/GitVersion#4255]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have searched [issues](https://github.com/GitTools/GitVersion/issues) to ensure it has not already been reported

### GitVersion package

GitVersion.Tool

### GitVersion version

5.12.0

### Operating system

Windows

### What are you seeing?

I'm getting Following error in Azure devops build Pipeline
Error: [37mExecuting: [0m[37;1m"C:/ProgramData/Chocolatey/bin/GitVersion.exe" -output json -updateassemblyinfo -verbosity Debug[0m
2024-10-07T10:20:39.2081116Z Unhandled exception. GitVersion.WarningException: Could not parse Verbosity value 'Debug'

1mSystem.AggregateException: One or more errors occurred. (GitVersion: Process returned an error (exit code -532462766).)
2024-10-07T10:20:52.4398525Z  ---> Cake.Core.CakeException: GitVersion: Process returned an error (exit code -532462766)

Here's my Build pipeline:
trigger:
- master
- develop

pool:
  vmImage: 'windows-2019'

variables:
  SYSTEM_ACCESSTOKEN: $(System.AccessToken)

steps:
- powershell: .\build.ps1 --Target=VSTS --Solution=USMED.Cake.Core.sln
  displayName: Cake Build
  env:
    SYSTEM_ACCESSTOKEN: $(System.AccessToken)
 
Following is my Gitversion.cake for your Reference

//#tool "nuget:https://www.nuget.org/api/v2?package=GitVersion.CommandLine&version=5.3.7"

Task("Version")
	.Does(() =>
	{
		string version = null;
		string semVersion = null;
		string milestone = null;
		string informationalVersion = null;
		string nugetVersion = null;
		string assemblySemVer = null;
		string fullSemVer = null;
		string major = "";
		string minor = "";
		string patch = "";
		string buildMetaData = "";

		Debug("Version Started");

		// if(AppVeyor.IsRunningOnAppVeyor)
		// {
		// 	GitVersion(new GitVersionSettings
		// 	{
		// 		UpdateAssemblyInfoFilePath = "../SolutionInfo.cs",
		// 		UpdateAssemblyInfo = true,
		// 		OutputType = GitVersionOutput.BuildServer
		// 	});

		// 	version = EnvironmentVariable("GitVersion_MajorMinorPatch");
		// 	semVersion = EnvironmentVariable("GitVersion_LegacySemVerPadded");
		// 	informationalVersion = EnvironmentVariable("GitVersion_InformationalVersion");
		// 	milestone = string.Concat(version);
		// 	nugetVersion = EnvironmentVariable("GitVersion_NuGetVersion");
		// }

		GitVersion assertedVersions = GitVersion(new GitVersionSettings
		{
			UpdateAssemblyInfo = true,
			OutputType = GitVersionOutput.Json,
		});

		version = assertedVersions.MajorMinorPatch;
		semVersion = assertedVersions.LegacySemVerPadded;
		informationalVersion = assertedVersions.InformationalVersion;
		milestone = string.Concat(version);
		nugetVersion = assertedVersions.NuGetVersion;
		assemblySemVer = assertedVersions.AssemblySemVer;
		fullSemVer = assertedVersions.FullSemVer;
		major = assertedVersions.Major.ToString();
		minor = assertedVersions.Minor.ToString();
		patch = assertedVersions.Patch.ToString();
		buildMetaData = assertedVersions.BuildMetaData;

		Verbose("Version: {0}", version);
		Verbose("Semantic Version: {0}", semVersion);
		Verbose("Informational Version: {0}", informationalVersion);
		Verbose("NuGet Version: {0}", nugetVersion);
		Verbose("Assembly Semantic Version: {0}", assemblySemVer);
		Verbose("Full Semantic Version: {0}", fullSemVer);
		Verbose($"New Main version: {assertedVersions.Major}.{assertedVersions.Minor}.{assertedVersions.BuildMetaData}");

		BuildVersion.SetVersion(
		  version, 
		  semVersion, 
		  milestone, 
		  informationalVersion, 
		  nugetVersion, 
		  assemblySemVer, 
		  fullSemVer,
		  major,
		  minor,
		  patch,
		  buildMetaData
		  );

		Debug("Version Completed");
	});

public static class BuildVersion
{
	public static string Version { get; private set; }
	public static string SemVersion { get; private set; }
	public static string Milestone { get; private set; }
	public static string InformationalVersion { get; private set; }
	public static string NuGetVersion { get; private set; }
	public static string AssemblySemVer { get; private set; }
	public static string FullSemVer { get; private set; }
	public static string CustomVersion => $"{Major}.{Minor}.{BuildMetaData}";
	public static string Major { get; private set; }
	public static string Minor { get; private set; }
	public static string Patch { get; private set; }
	public static string BuildMetaData {get; private set; }

	public static void SetVersion(
		string version,
		string semVersion, 
		string milestone, 
		string informationalVersion,
		string nugetVersion,
		string assemblySemVer,
		string fullSemVer,
		string major,
		string minor,
		string patch,
		string buildMetaData)
		{
			Version = version;
			SemVersion = semVersion;
			Milestone = milestone;
			InformationalVersion = informationalVersion;
			NuGetVersion = nugetVersion;
			AssemblySemVer = assemblySemVer;
			FullSemVer = fullSemVer;
			Major = major;
			Minor = minor;
			Patch = patch;
			BuildMetaData = buildMetaData;
		}
}

Following is my Gitversion.yml

next-version: 0.1.0
assembly-versioning-scheme: MajorMinorPatch
mode: mainline
increment: Inherit
commit-message-incrementing: Enabled
commit-date-format: 'yyyy-MM-dd'
branches:
  master:
    mode: ContinuousDelivery
    tag: '' 
    increment: Minor
    prevent-increment-of-merged-branch-version: true
    track-merge-target: false
  develop:
    regex: dev(elop)?(ment)?$
    mode: ContinuousDelivery
    tag: beta
    increment: Patch
    prevent-increment-of-merged-branch-version: true
    tracks-release-branches: false
    is-release-branch: true
ignore:
  sha: []
Following is my addins.cake
// Install modules

#addin "nuget:https://api.nuget.org/v3/index.json?package=Cake.Incubator&version=6.0.0"
#addin "nuget:https://api.nuget.org/v3/index.json?package=Cake.Npm&version=1.0.0"
#addin "nuget:https://pkgs.dev.azure.com/usmedequip/_packaging/smarts/nuget/v3/index.json?package=Cake.DotNetCoreEFAzure"
#addin "nuget:https://api.nuget.org/v3/index.json?package=Cake.Plist&version=0.7.0"
#addin "nuget:https://api.nuget.org/v3/index.json?package=Cake.FileHelpers&version=4.0.1" //&version=3.3.0"
#addin "nuget:https://api.nuget.org/v3/index.json?package=Cake.AppCenter&version=1.3.1"
#addin "nuget:https://api.nuget.org/v3/index.json?package=Cake.DoInDirectory&version=4.0.2" //&version=3.3.0"
#addin "nuget:https://api.nuget.org/v3/index.json?package=Cake.AzureCli&version=1.2.1"
#addin "nuget:https://api.nuget.org/v3/index.json?package=Cake.PathTildeHelper&version=3.0.1"

#addin "nuget:https://api.nuget.org/v3/index.json?package=Cake.Issues&version=2.0.0"
#addin "nuget:https://api.nuget.org/v3/index.json?package=Cake.Issues.MsBuild&version=2.0.0"
#addin "nuget:https://api.nuget.org/v3/index.json?package=Cake.Issues.Reporting&version=2.0.0"
#addin "nuget:https://api.nuget.org/v3/index.json?package=Cake.Issues.Reporting.Sarif&version=2.0.0"

#addin nuget:?package=Cake.Git&version=1.1.0

#module nuget:?package=Cake.DotNetTool.Module&version=0.4.0
#tool dotnet:?package=GitVersion.Tool&version=5.12.0

#tool "nuget:?package=MSBuild.Extension.Pack"

### What is expected?

I want to fix this error to run the successful build

### Steps to Reproduce

This same build was working fine when we checked couple of months back but suddenly we are getting this error in build pipeline.

**Comment by arturcic** [comment]
https://gitversion.net/5.12.0/api/GitVersion.Logging/Verbosity/
