### ISSUE TITLE
[ISSUE]: Azure pipelines task fails when using versionSpec 6.x since the release of 6.1.0

### ISSUE THREAD

**Issue by fbus** [GitTools/GitVersion#4344]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have searched [issues](https://github.com/GitTools/GitVersion/issues) to ensure it has not already been reported

### GitVersion package

AzureDevops task

### GitVersion version

6.1.0

### Operating system

Linux

### What are you seeing?

![Image](https://github.com/user-attachments/assets/cd5c68a0-3091-4e6c-bf78-b96fbf202c02)

Since the release of gitversion 6.1.0, using versionSpec: 6.x will fail with the error above.
the version.
Replacing versionSpec 6.x with **6.0.5** is enough to avoid the problem.

### What is expected?

this should use version 6.1.0

### Steps to Reproduce

create an azure pipeline containing:

- task: gittools.gittools.setup-gitversion-task.gitversion/setup@3
  displayName: gitversion/setup
  inputs:
    versionSpec: 6.x

### Output log or link to your CI build (if appropriate).

```shell

```

**Comment by arturcic** [comment]
There is no v4 version of the actions so for now use 6.0.x
