### ISSUE TITLE
Generated classes create conflicts with InternalsVisibleTo

### ISSUE THREAD

**Issue by onovotny** [GitTools/GitVersion#448]
Using the 3.0 b2 msbuild tasks, I see this:
```
C:\Users\Oren\Source\Git\MetroLog\MetroLog.WP8\obj\Release\GitVersionTaskAssemblyInfo.g.cs(8,12,8,23): warning CS0436: The type 'ReleaseDateAttribute' in 'C:\Users\Oren\Source\Git\MetroLog\MetroLog.WP8\obj\Release\GitVersionTaskAssemblyInfo.g.cs' conflicts with the imported type 'ReleaseDateAttribute' in 'MetroLog, Version=0.8.8.0, Culture=neutral, PublicKeyToken=ba4ace74c3b410f3'. Using the type defined in 'C:\Users\Oren\Source\Git\MetroLog\MetroLog.WP8\obj\Release\GitVersionTaskAssemblyInfo.g.cs'.
```
Problem is that the ReleaseDateAttribute and GitVersionInformation classes are created in the root namespace, so they'll conflict with friend access.

Proposal:
Put the attribute in a namespace underneath the assembly name.

I.e., for an assemlby Foobar.Frob:

namespace Foobar.Frob {
...
}

**Comment by JakeGinnivan** [comment]
@SimonCropp, thoughts?

**Comment by SimonCropp** [comment]
Dont object. But how bigger "greaking" change is this?

**Comment by onovotny** [comment]
As these classes are generated at compile-time and included, how many people have references to those types?

I'd think it'd be more of a breaking change if it was generated on included somehow in VS so developers could use those types in their code directly?

**Comment by SimonCropp** [comment]
well either way we r in v3beta so i say lets do it. @onovotny want to do a PR?

**Comment by onovotny** [comment]
Wish I could, I just don't have the bandwidth right now :/

**Comment by distantcam** [comment]
Should we also add a CompilerGeneratedAttribute too?
