### ISSUE TITLE
AssemblyInfo files not compatible using both CommandLine and Task

### ISSUE THREAD

**Issue by Sacrelicious** [GitTools/GitVersion#473]
Using the GitVersionTask requires that there not be any conflicting attributes in the appropriate AssemblyInfo.cs in order to correctly update the assembly's version info, however, when using the command line tool, the AssemblyInfo.cs files won't get updated unless those attributes exists (b/c it uses a regex to find that attribute). This means that you cannot use both the Task and command line on the same projects, for instance, we would like to use the Task when building projects on dev machines, but use the command line when running on a build server.

Pull request for this issue coming shortly.

**Comment by asbjornu** [comment]
@Sacrelicious just out of curiosity, why do you want or need to use the command line tool on build servers? We use GitVersionTask with TeamCity and it works just fine.
