### ISSUE TITLE
Warning should be info: No specific commit specified or found, falling back to latest commit on specified branch

### ISSUE THREAD

**Issue by onovotny** [GitTools/GitVersion#485]
When using the GitVersionTask v3.0.0-beta004, I see the following in my build output:

WARN [07/07/15 15:55:05:16] No specific commit specified or found, falling back to latest commit on specified branch

Is that a "real" warning? Isn't that doing what it should do; use the latest commit on a branch? If that's normal, then it shouldn't be a warning; it's preventing a totally "Green" build :)

At the very least, it should be a property I can set in my csproj to turn it to an info -- or default to info and an option to make it a warning.

**Comment by asbjornu** [comment]
I agree that this shouldn't be a warning. But as mentioned in #437, this exact message caused considerable slowdowns in large repositories, so I understand why it could be considered a warning "back then". The performance issues should be fixed, though, so the situation isn't much to warn about anymore, imo. :smile:

**Comment by JakeGinnivan** [comment]
Yeah, it shouldn't have been a warning. Nice change
