### ISSUE TITLE
Version number for nuget in hotfix branches

### ISSUE THREAD

**Issue by alkampfergit** [GitTools/GitVersion#487]
I do not know if this is a desired feature, I've created an hotifix branch, after 5 commit in that hotfix branch here are properties generated by the tool

     GitVersion.ClassicVersionWithTag 1.0.1.5-beta.1
     GitVersion.NuGetVersionV2 1.0.1-beta0001

Classic version with tag correctly reports 1.0.1.5 and I'm expecting NuGetVersionV2 to be 1.0.1-beta0005, not 1.0.1-beta0001

With develop branch everything works as expected, after 6 commit in develop branch I have

       GitVersion.ClassicVersionWithTag 1.1.0.6-unstable.6
       GitVersion.NuGetVersionV2 1.1.0-unstable0006

Am I missing some configuration for Hotfix branches? 

Thanks.

**Comment by asbjornu** [comment]
@alkampfergit, which version of GitVersion are you using? Version 2 or 3? GitVersion command line or GitVersionTask?

**Comment by alkampfergit** [comment]
We installed in TeamCity with metarunner (https://github.com/JetBrains/meta-runner-power-pack/tree/master/gitversion) 

The exact metarunner text that is active in our teamcity can be found here https://gist.github.com/alkampfergit/5d7448fb7b65e70f83bd

Thanks.

**Comment by asbjornu** [comment]
Why would you use that meta-runner when you already have GitVersionTask installed in the solution? I don't see what benefit it gives.

**Comment by alkampfergit** [comment]
We are just started with GitVersion, and using TeamCity integration seemed the easiest way to go, it is easy to use and does not require people to modify solution to include GitVersionTask, just configure a build and you are ready to go.

Do you think that the cause of the bug is due to meta-runner for TeamCity and using directly GitVersionTask could solve the problem?

**Comment by JakeGinnivan** [comment]
It will be v2.

The meta runner should be updated for v3. Until v3 is released this line will need to be changed to have `-pre` as well - https://github.com/JetBrains/meta-runner-power-pack/blob/master/gitversion/MR_GitVersion.xml#L137

**Comment by alkampfergit** [comment]
Thanks a lot, I'll try as soon as possible.

**Comment by JakeGinnivan** [comment]
That said, I think you will still face the issue.

develop has a different increment strategy than other branches. Have a read of https://github.com/GitTools/GitVersion/blob/master/Docs/versionIncrements.md

Good news is with v3 you can change this behavior

**Comment by alkampfergit** [comment]
Many thanks, I think that now I have all needed information to accomplish what I need.

**Comment by asbjornu** [comment]
Since you asked; yea, I do think it is better to install GitVersionTask and have the same solution yield the same version number on the same commit being built regardless of who, what or where it is being built. No matter how you use GitVersion, though, I would recommend choosing one strategy and tool and not mix them around. And among the available tools and options I think GitVersionTask is the best available.

**Comment by gep13** [comment]
@JakeGinnivan there is an outstanding PR for GitVersion V3 support here in the meta runners project:

https://github.com/JetBrains/meta-runner-power-pack/pull/47
