### ISSUE TITLE
Version number is not cached between projects in a solution

### ISSUE THREAD

**Issue by asbjornu** [GitTools/GitVersion#488]
As mentioned in #437, when GitVersionTask (version 3 beta 4) is installed in a solution, I get the following informational message when building every project in the solution.
```
INFO [07/08/15 14:57:03:21] Version not in cache. Calculating version.
```
It would speed the build up noticeably if the version number was successfully cached between projects.

**Comment by GeertvanHorrik** [comment]
I think that it is possible that multiple instances of msbuild are running for the same sln. This means that caching must be done based on the sln name + last modification date of the .git folder. Not sure if we can do this in a short time period (still working very hard to create GitTools.Core to create a shared logic for all applications).

**Comment by asbjornu** [comment]
I see. Will it be possible to get this fixed within the timeframe of 3.0, or will this have to be postponed to a minor v3 increment some time in the future?

**Comment by JakeGinnivan** [comment]
If someone submits a PR which fixes before I get a chance to finalise, it will be in. Otherwise it wont :P

**Comment by GeertvanHorrik** [comment]
We are already trying to release 3.0 for months. Let's finish it and stop expanding its scope.

**Comment by GeertvanHorrik** [comment]
@JakeGinnivan even with a PR, let's leave it out and plan for 3.1 (if anyone wants to take it). I prefer monthly releases over yearly releases anyway ;-))

**Comment by JakeGinnivan** [comment]
Moving countries has really taken a toll on my spare time. Next week I will be releasing v3

**Comment by asbjornu** [comment]
@JakeGinnivan, @GeertvanHorrik sounds good.

**Comment by asbjornu** [comment]
@JakeGinnivan I really hope #594 fixes the problem! Since it's already merged, is there any chance of a new minor release any time soon so I can verify the fix?

**Comment by JakeGinnivan** [comment]
Yep, minor release hopefully this weekend. Want to get the bump via commit message stuff in for the 3.1 release :)

**Comment by asbjornu** [comment]
@JakeGinnivan Great. I'll try to get the `ConcurrentDictionary` PR in before the next minor too. I'll hopefully have time to work on that monday. Does that sound OK?
