### ISSUE TITLE
Bamboo checks out repository with a detached head - causes errors

### ISSUE THREAD

**Issue by Tungsten78** [GitTools/GitVersion#499]
We encountered an issue where source checkouts are headless when Bamboo is triggered by Stash commits.  Forcing a build plan manually does not have this problem.

There is a precondition that protects against headless checkouts (I presume because GitVersion requires knowledge of the current branch for its rules) and this causes premature exit.

I have read up on dynamic repositories, which I probably could use, but I was wondering what we thought about maybe using the /b switch to specify the branch in this scenario.  In the absence of the other /url, /u, /p switches we could wire this into the branch detection logic.

Thoughts?

**Comment by Tungsten78** [comment]
Upon further investigation it seems GitVersion does a bit of handling to deal with detached heads. My server is doing something funky with the fetch and ending up with an odd checkout. 

Closing.

**Comment by JakeGinnivan** [comment]
Actually we have a special mode GitVersion runs in when it detects it's on the build server. We actually fetch and fix the branches automatically (assuming the server has actually checked out a proper git repo). Dynamic repositories is only for say TeamCity checkout on agent where it doesn't actually clone the git repo, it just transfers the contents of that commit to the agent.

I think we need to add Bamboo support as a proper build server. See https://github.com/GitTools/GitVersion/blob/master/GitVersionCore/BuildServers/TeamCity.cs for the TeamCity implementation. If you added one of these for Bamboo things should work as you expect

**Comment by MattDavies** [comment]
@tungsten78 you aren't going crazy, Bamboo does some particularly strange (and sometimes inconsistent) things with the Git checkout.

We worked around with dynamic repositories pretty much as you described, happy to help out with a proper fix if you need a hand based on what behaviour I've seen.

**Comment by JakeGinnivan** [comment]
@MattDavies I can't see anywhere that Bamboo has a way to write variables/overwrite build number from a build? If so we could just throw with a helpful error message pointing at the dynamic repo switches

**Comment by Tungsten78** [comment]
@JakeGinnivan As far as I know variable overwriting requires a custom plugin. Coincidentally someone created one based on your project (I assume you are aware) : http://carolynvanslyck.com/blog/2015/03/gitversion-for-bamboo/
I haven't tried it out since our instance is locked down and this requires admin privileges. 

What I am doing is invoking gitversion from an nant script. I let gitversion take care of my assembly info files but have the script output a file based on the json variables that an out of the box plugin can use to inject variables. The variables I use for artifact naming and future deployment stages.

**Comment by Tungsten78** [comment]
Thanks guys. I will look at the build server modes and see if a bamboo server implementation might help.

**Comment by JakeGinnivan** [comment]
Did not know about GitVersion for Bamboo. Awesome. When I do the docs I will link it.

**Comment by MattDavies** [comment]
Neither did I, that plugin looks awesome!

You can write variables from a build but I haven't ever found a way to override the actual build number. :(

**Comment by JakeGinnivan** [comment]
Where are the docs on writing out variables?

**Comment by Tungsten78** [comment]
@JakeGinnivan You're not asking via the plug-in route are you?  As far as I'm aware this is the only way.   I'm guessing your motivation is to create the Bamboo IBuildServer instance?

[Tasks API](https://developer.atlassian.com/display/BAMBOODEV/Tasks+Overview)  **Java only**

The metadata is exposed to the plan via customBuildData - see below (this is precisely what the GitVersion plugin task is doing).  This doesn't override but provides new metadata. At the deployment stage, Bamboo has you specify the release version by way of variable references (ie: ${bamboo.GitVersion.SemVer} where GitVersion.SemVer is a property the GitVersion task publishes).

Map<String, String> metadata = buildContext.getBuildResult().getCustomBuildData();
metadata.put("key", "value");

**Comment by JakeGinnivan** [comment]
Fair enough. 

I think we need to have a flag which can force initialisation of the repo. This normalises all the remote branches as local refs so GitVersion can effectively calculate the version. The bamboo plugin could then call GitVersion with that flag. That should make it all work nicely. Otherwise we can force use of dynamic repos with that plugin. I think the normalise route is better though

**Comment by JakeGinnivan** [comment]
@Tungsten78 see https://github.com/GitTools/GitVersion/issues/507

**Comment by Tungsten78** [comment]
@JakeGinnivan I found this:  [Bamboo REST API](https://docs.atlassian.com/bamboo/REST/5.0-SNAPSHOT/)

It can be used to [alter variables](https://confluence.atlassian.com/display/BAMKB/Resetting+Variables+via+a+REST+API+call+and+Dynamic+Release+versioning).  While I didn't test it, it will require authentication.
