### ISSUE TITLE
Fix Gem deployment

### ISSUE THREAD

**Issue by JakeGinnivan** [GitTools/GitVersion#501]
We either need to retire the Gem, or set the release up again. This needs to be done soon after the v3 release

**Comment by gep13** [comment]
I wasn't ever involved in doing anything with this.

Was it a complicated thing to do?  Can we get AppVeyor to do it for us?

**Comment by JakeGinnivan** [comment]
Yeah, shouldn't be too hard. Just something I have to do, didn't want to forget

**Comment by gep13** [comment]
:+1:

**Comment by JakeGinnivan** [comment]
Gem is uploaded as an artifact, need to push manually after deployment. Am getting access to do that now, have added badge as a reminder
