### ISSUE TITLE
GitVersion.Portable uses deprecated Write-ChocolateySuccess

### ISSUE THREAD

**Issue by asbjornu** [GitTools/GitVersion#515]
When installing version 3 beta 4 of [GitVersion.Portable](https://chocolatey.org/packages/GitVersion.Portable), I got a warning saying `Write-ChocolateySuccess is deprecated. If you are the maintainer, please remove it from your package file.`. Full command line output:
```
C:\...> choco install gitversion.portable -pre
Chocolatey v0.9.9.8
Installing the following packages:
gitversion.portable
By installing you accept licenses for the packages.

GitVersion.Portable v3.0.0-beta0004
The package GitVersion.Portable wants to run 'chocolateyInstall.ps1'.
Note: If you don't run this script, the installation will fail.
Note: To confirm automatically next time, use '-y' or consider setting 'allowGlobalConfirmation'. Run 'choco feature -h' for more details.
Do you want to run the script?
 1) yes
 2) no
 3) print
1
 Added C:\ProgramData\chocolatey\bin\gfv.exe shim pointed to '..\lib\gitversion.portable\tools\gitversion.exe'.
 WARNING: Write-ChocolateySuccess is deprecated. If you are the maintainer, please remove it from your package file.
 ShimGen has successfully created a shim for GitVersion.exe
 The install of gitversion.portable was successful.

Chocolatey installed 1/1 package(s). 0 package(s) failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
```

**Comment by gep13** [comment]
Yip, this is a known issue.

I know for a fact that it isn't getting removed from Chocolatey for quite a while yet, so we are ok, but it is something that we need to tidy up.

Thanks for reporting it :+1:

**Comment by urig** [comment]
Would love to pick this up - If only I knew where the Chocolatey package sources are...? :)

**Comment by asbjornu** [comment]
@urig Excellent! The source file you're after is [this](https://github.com/GitTools/GitVersion/blob/master/src/GitVersionExe/NugetAssets/chocolateyInstall.ps1), I believe. :smiley:

**Comment by gep13** [comment]
@asbjornu @urig yes, that is the one.  Simply remove the call to Write-ChocolateySuccess.

**Comment by gep13** [comment]
@asbjornu @urig same in the uninstallChocolatey.ps1 file.

**Comment by urig** [comment]
Did it. I'm a click away from submitting the PR but I don't know how to test myself... Halp? :)

**Comment by asbjornu** [comment]
@urig You can test locally with an NUnit test runner in ReSharper or Visual Studio, use the GUI application or on the console. Lots of options! Or, you could just submit the PR and it will be tested by AppVeyor and Travis.
