### ISSUE TITLE
Documentation Feedback

### ISSUE THREAD

**Issue by JakeGinnivan** [GitTools/GitVersion#517]
So I have moved to using the `docs` folder to hold doco. I will release v3 once I finish the doco updates

I think I am going to settle on http://gitversion.readthedocs.org/en/latest for the live documentation. It is generated automatically from the `docs` folder in the repo. What I like about this is that you can use GitHub to browse the docs (see https://github.com/GitTools/GitVersion/tree/master/Docs) and read the docs provides a nice view of the latest version, as well as the docs for previous versions (if we used this approach earlier).

Looking for some feedback on the direction. Some other options are and some of my pros/cons

1. GitHub wiki
  - No PR support :-1: 
  - Not that nice to navigate :-1: 
2. readme.io
  - Looks nice :+1: 
  - Separate to GitHub, so can't update docs in a PR :-1: 
3. Custom jekyll page
  - Work to implement :-1: 
  - Can make it work just like we want :+1: 

Other suggestions welcome. // @GeertvanHorrik @gep13 @robdmoore

**Comment by robdmoore** [comment]
Cool! I like you can host it somewhere that looks nice, but keep the source of truth with the code. Very cool

**Comment by gep13** [comment]
>@JakeGinnivan said...
No PR support :-1:

While this is technically true, there is a bit of a workaround that we use over at Chocolatey.  You basically take the wiki, and push it to a new repo.  PR's can then be submitted to that repo, and if/when they are accepted, changes are then pushed to the upstream remote, which is the actual wiki.  It is a little bit cumbersome, but it works.

With readthedocs, are different versions of the docs based on a tag in the repo?  Or how do you indicate that it is a different version?

I really like this suggestion.  It gives the best of both worlds.

**Comment by JakeGinnivan** [comment]
> With readthedocs, are different versions of the docs based on a tag in the repo? Or how do you indicate that it is a different version?

Yep, when you tag it builds a version of the docs using the content of the `docs` folder. Pretty neat

**Comment by gep13** [comment]
very cool, that definitely sounds like the ideal solution! :+1:

**Comment by distantcam** [comment]
:+1: Looks nice! Might have to use that on some of my other projects.

**Comment by pascalberger** [comment]
Since readthedocs is now in use I'm closing this issue
