### ISSUE TITLE
When version attributes missing when using exe?

### ISSUE THREAD

**Issue by JakeGinnivan** [GitTools/GitVersion#529]
**Update:**
We have decided on option 1, when the version attributes cannot be found to update in GitVersion.exe, we should raise an error.

---

Original:
The Task requires version attributes to _not_ be present (because they are inserted into the MSBuild pipeline) and the exe is updating assembly info files so the attributes are required to be there.

This can cause issues migrating between the two (especially from task to exe). I see two ways to resolve this:
1. Throw error when attributes cannot be found in the exe
   - This could also highlight errors when version info is in a commonassemblyinfo.cs, prompting the user to specify the filename which should be updated
2. If the attributes cannot be found, insert them rather than replace.
   - Currently we just replace the ones that can be found, so if you want the Info attribute with everything, just put it into your assembly info files and it will be updated
   - Will mean duplicates if using the commonassemblyinfo.cs approach

I think **1** is the way to go, but want feedback.

// @gep13 @asbjornu @distantcam

**Comment by distantcam** [comment]
I'm :+1: for the first option.

- It's the easier one to back out of if the user made a mistake. Option 2 has changed files that need to be reverted.
- It's less "magically just works" which means less code and less likely to just "magically fail".

**Comment by asbjornu** [comment]
I think throwing an exception with detailed description and friendly guidance on how to fix it is the best way to go. Just throw in as much information about why it occurred and how it can be remedied and it will yield a good development experience. :smile:

**Comment by asbjornu** [comment]
I believe this was fixed in #1249.
