### ISSUE TITLE
Gfv* variables

### ISSUE THREAD

**Issue by JakeGinnivan** [GitTools/GitVersion#530]
I have only spotted this after reading http://www.neovolve.com/2015/04/04/bridging-gitversion-and-octopack

We have not fixed the task variable names to be in line with all the other conventions. These are not documented anywhere and I think we should change before the final v3 release?

Also the variables do not line up properly with the changed variables we have in v3.

Thoughts @SimonCropp @distantcam 

// cc @roryprimrose

**Comment by SimonCropp** [comment]
@JakeGinnivan i am happy to make a breaking change to the variable names since it is a major release. 

where is the doco for the current command line ones? then i will do a PR to bring the task ones into line

**Comment by JakeGinnivan** [comment]
https://github.com/GitTools/GitVersion/blob/master/docs/more-info/variables.md

But the best source is https://github.com/GitTools/GitVersion/blob/master/src/GitVersionCore/OutputVariables/VersionVariables.cs

There are also tests which make sure the tasks actually line up with that class at https://github.com/GitTools/GitVersion/blob/master/src/GitVersionTask.Tests/GetVersionTaskTests.cs - not sure if we could do same thing for the targets file. Or dynamically generate it

**Comment by JakeGinnivan** [comment]
Could make the targets file a .tt file which generates on build?

**Comment by JakeGinnivan** [comment]
Should also update https://github.com/GitTools/GitVersion/blob/master/docs/usage.md to give info about the variables in the targets file

**Comment by SimonCropp** [comment]
isnt .tt overkill? how often are we going to be changing variable names? Also eventually will we  want to be documenting version X and X-1 ?

**Comment by JakeGinnivan** [comment]
True, readthedocs actually already supports versioned docs. So yeah, just do it :)

**Comment by JakeGinnivan** [comment]
@SimonCropp when are you planning to submit this? :)

**Comment by SimonCropp** [comment]
this weekend

**Comment by johnkattenhorn** [comment]
I used the articule you mentioned at the top to great effect but 3.0.1 seems to have broken it for me. I changed the variable name to $(GitVersion_NuGetVersion) but it doesn't seem to get set. 

Here is a snippet of the bottom of my project file

    <PropertyGroup>
        <BuildDependsOn>
          $(BuildDependsOn);
          SetOctoPackVersion
        </BuildDependsOn>
      </PropertyGroup>
      
      <Target Name="SetOctoPackVersion">
        <PropertyGroup>
          <OctoPackPackageVersion>$(GitVersion_NuGetVersion)</OctoPackPackageVersion>
        </PropertyGroup>
      </Target>
      <Import Project="$(SolutionDir)\.nuget\NuGet.targets" Condition="Exists('$(SolutionDir)\.nuget\NuGet.targets')" />
      <Target Name="EnsureNuGetPackageBuildImports" BeforeTargets="PrepareForBuild">
        <PropertyGroup>
          <ErrorText>This project references NuGet package(s) that are missing on this computer. Enable NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is {0}.</ErrorText>
        </PropertyGroup>
        <Error Condition="!Exists('..\packages\GitVersionTask.3.0.1\Build\GitVersionTask.targets')" Text="$([System.String]::Format('$(ErrorText)', '..\packages\GitVersionTask.3.0.1\Build\GitVersionTask.targets'))" />
  </Target>
      <Import Project="..\packages\AutoMapper.3.3.1\tools\AutoMapper.targets" Condition="Exists('..\packages\AutoMapper.3.3.1\tools\AutoMapper.targets')" />
      <Import Project="..\packages\OctoPack.3.0.42\tools\OctoPack.targets" Condition="Exists('..\packages\OctoPack.3.0.42\tools\OctoPack.targets')" />
      <Target Name="EnsureOctoPackImported" BeforeTargets="BeforeBuild" Condition="'$(OctoPackImported)' == ''">
        <Error Condition="!Exists('..\packages\OctoPack.3.0.42\tools\OctoPack.targets') And ('$(RunOctoPack)' != '' And $(RunOctoPack))" Text="You are trying to build with OctoPack, but the NuGet targets file that OctoPack depends on is not available on this computer. This is probably because the OctoPack package has not been committed to source control, or NuGet Package Restore is not enabled. Please enable NuGet Package Restore to download them. For more information, see http://go.microsoft.com/fwlink/?LinkID=317567." HelpKeyword="BCLBUILD2001" />
        <Error Condition="Exists('..\packages\OctoPack.3.0.42\tools\OctoPack.targets') And ('$(RunOctoPack)' != '' And $(RunOctoPack))" Text="OctoPack cannot be run because NuGet packages were restored prior to the build running, and the targets file was unavailable when the build started. Please build the project again to include these packages in the build. You may also need to make sure that your build server does not delete packages prior to each build. For more information, see http://go.microsoft.com/fwlink/?LinkID=317568." HelpKeyword="BCLBUILD2002" />
  </Target>
      <Import Project="..\packages\GitVersionTask.3.0.1\Build\GitVersionTask.targets" Condition="Exists('..\packages\GitVersionTask.3.0.1\Build\GitVersionTask.targets')" />
      <!-- To modify your build process, add your task inside one of the targets below and uncomment it. 
       Other similar extension points exist, see Microsoft.Common.targets.
      <Target Name="BeforeBuild">
      </Target>
      <Target Name="AfterBuild">
      </Target>

**Comment by roryprimrose** [comment]
This worked fine for me.

```

  <!-- Hook into the AfterBuild activity -->
  <PropertyGroup>
    <BuildDependsOn>
      $(BuildDependsOn);
      SetOctoPackVersion
    </BuildDependsOn>
  </PropertyGroup>
  <!-- 
  Create Octopus Deploy package
  -->
  <Target Name="SetOctoPackVersion">
    <PropertyGroup>
      <OctoPackPackageVersion>$(GitVersion_NuGetVersion)</OctoPackPackageVersion>
    </PropertyGroup>
  </Target>
```

**Comment by roryprimrose** [comment]
I tested it locally by adding <RunOctoPack>True</RunOctoPack> into the proj

**Comment by johnkattenhorn** [comment]
Hey @roryprimrose, thanks for the great article!

See the other issue I logged, it seems only to affect the build process when using the new TFS Build vNext service.

**Comment by roryprimrose** [comment]
Hmm, that's what I tested this morning and it worked fine. Perhaps put some message tasks in your proj and share the relevant build log entries.






On Wed, Jul 29, 2015 at 1:39 AM -0700, "John Kattenhorn" <notifications@github.com> wrote:
Hey @roryprimrose, thanks for the great article!

See the other issue I logged, it seems only to affect the build process when using the new TFS Build vNext service.

---

**Comment by johnkattenhorn** [comment]
Ah ok, let me check it out and come back to you.

Do you know if the order of the imports affect anything ?

Does the bottom of my project file look ok to you ?

**Comment by roryprimrose** [comment]
Should be ok. I've got mine at the bottom of the proj and it worked fine in a vNext VSO build.

Here is what I built this morning.

```

  <!-- Hook into the AfterBuild activity -->
  <PropertyGroup>
    <BuildDependsOn>
      $(BuildDependsOn);
      SetOctoPackVersion
    </BuildDependsOn>
  </PropertyGroup>
  <!-- 
  Create Octopus Deploy package
  -->
  <Target Name="SetOctoPackVersion">
    <PropertyGroup>
      <OctoPackPackageVersion>$(GitVersion_NuGetVersion)</OctoPackPackageVersion>
    </PropertyGroup>
  </Target>
  <Import Project="..\packages\OctoPack.3.0.42\tools\OctoPack.targets" Condition="Exists('..\packages\OctoPack.3.0.42\tools\OctoPack.targets')" />
  <Target Name="EnsureOctoPackImported" BeforeTargets="BeforeBuild" Condition="'$(OctoPackImported)' == ''">
    <Error Condition="!Exists('..\packages\OctoPack.3.0.42\tools\OctoPack.targets') And ('$(RunOctoPack)' != '' And $(RunOctoPack))" Text="You are trying to build with OctoPack, but the NuGet targets file that OctoPack depends on is not available on this computer. This is probably because the OctoPack package has not been committed to source control, or NuGet Package Restore is not enabled. Please enable NuGet Package Restore to download them. For more information, see http://go.microsoft.com/fwlink/?LinkID=317567." HelpKeyword="BCLBUILD2001" />
    <Error Condition="Exists('..\packages\OctoPack.3.0.42\tools\OctoPack.targets') And ('$(RunOctoPack)' != '' And $(RunOctoPack))" Text="OctoPack cannot be run because NuGet packages were restored prior to the build running, and the targets file was unavailable when the build started. Please build the project again to include these packages in the build. You may also need to make sure that your build server does not delete packages prior to each build. For more information, see http://go.microsoft.com/fwlink/?LinkID=317568." HelpKeyword="BCLBUILD2002" />
  </Target>
  <Import Project="..\packages\GitVersionTask.3.0.1\Build\GitVersionTask.targets" Condition="Exists('..\packages\GitVersionTask.3.0.1\Build\GitVersionTask.targets')" />
  <Target Name="EnsureNuGetPackageBuildImports" BeforeTargets="PrepareForBuild">
    <PropertyGroup>
      <ErrorText>This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is {0}.</ErrorText>
    </PropertyGroup>
    <Error Condition="!Exists('..\packages\GitVersionTask.3.0.1\Build\GitVersionTask.targets')" Text="$([System.String]::Format('$(ErrorText)', '..\packages\GitVersionTask.3.0.1\Build\GitVersionTask.targets'))" />
  </Target>
  <!-- To modify your build process, add your task inside one of the targets below and uncomment it. 
       Other similar extension points exist, see Microsoft.Common.targets.
  <Target Name="BeforeBuild">
  </Target>
  <Target Name="AfterBuild">
  </Target>
  -->
</Project>
```

**Comment by johnkattenhorn** [comment]
Cheers Rory, I’ll check it out.

I’m looking forward to the Octopus Build Step so we can separate the packaging and push from the build.

Seems wrong to push the build into Octopus before the tests have run ☺, at the moment I just don’t allow the automatic release to happen in that case.
