### ISSUE TITLE
GitFlow not accurate

### ISSUE THREAD

**Issue by igloo15** [GitTools/GitVersion#533]
The problem I am having is that I have a master branch tagged at version 1.4, my develop branch is now moving on to version 2.0. My team is building features for 2.0 and branching off develop. There is no release branch for 2.0 yet because we aren't ready. Yet my develop branch is reporting back that we are working on version 1.5 and not 2.0. I understand that its looking at the 1.4 and incrementing to 1.5 but there must be some way to tell it that we are now working on a new major version with creating a release branch. Since according to GitFlow release branches are only created after development is done on the release. 

The examples on http://gitversion.readthedocs.org/en/latest/git-branching-strategies/gitflow-examples/ seem to imply there is no way to increment major release for develop until you are already working on the next minor version. What I mean is that develop could never be version 2.0, 3.0, 4.0, etc. It would always only be the next version 2.1, 3.1, 4.1.

**Comment by JakeGinnivan** [comment]
You can just set `next-version: 3.0.0` or whatever in `GitVersionConfig.yaml` to increment to the next major

**Comment by JakeGinnivan** [comment]
Do you think I should add a link to http://gitversion.readthedocs.org/en/latest/more-info/version-increments/#manually-incrementing-the-version from the examples? Would that make it more discoverable?

**Comment by igloo15** [comment]
Where does the GitVersionConfig.yaml file have to be placed. Can a GitVersionConfig.yaml be specified as a executable option? I saw that in the manually increment section but I figured it was a global property and I have several projects that use GitVersion and they all have different versions.

**Comment by JakeGinnivan** [comment]
The GitVersionConfig.yaml file sits in the root of your git repository.

GitVersion is tied to your VCS, so a commit in a repository translates to a version. We can't support multiple projects with different versions in the same repo. 

Is that what you meant?

**Comment by igloo15** [comment]
Ok so I did do that but it had no effect on the GitVersion. I have a GitVersionConfig.yaml file at the root and I uncommented the next-version: line and set it 2.0.0 but when I run GitVersion from there I still get 1.5 version. I am on the develop branch.

**Comment by igloo15** [comment]
This is the content of my GitVersionConfig.yaml which is right next to my .git folder

 # assembly-versioning-scheme: MajorMinorPatchMetadata | MajorMinorPatch | MajorMinor | Major
 # develop-branch-tag: alpha
 # release-branch-tag: rc
 # tag-prefix: '[vV|version-] # regex to match git tag prefix
 next-version: 2.0.0

**Comment by igloo15** [comment]
Update to beta version 3.0 of GitVersion and now it appears to work.

**Comment by JakeGinnivan** [comment]
Ah yeah, all this only works with 3. I should have asked that first! :)

The aim is to release v3 stable this weekend

**Comment by JakeGinnivan** [comment]
So, all sorted?

**Comment by igloo15** [comment]
Yup all sorted thanks for the help
