### ISSUE TITLE
Don't reset beta when merging hotfix branches

### ISSUE THREAD

**Issue by GeertvanHorrik** [GitTools/GitVersion#539]
We currently have this situation:

1. Create release branch
2. Do several commits (beta count increases to 1.2.0-beta4)
3. Do hotfix on release branch (which shouldn't actually happen, I know)
4. Beta count resets to 1.2.0-beta0 again

Is this something we should fix or do we call this user error?

**Comment by JakeGinnivan** [comment]
I actually broke tests and commit counting late in the release so we had green tests when they should have been failing! Fixed in #541

**Comment by JakeGinnivan** [comment]
3.0.1 released with the fix
