### ISSUE TITLE
$(GitVersion_NuGetVersion) does seem to get set when Solution is built using TFS Build vNext

### ISSUE THREAD

**Issue by johnkattenhorn** [GitTools/GitVersion#546]
I've already put a comment in the closed issue #530.

I used the article you mentioned in #530 to great effect but 3.0.1 seems to have broken it for me. I changed the variable name to $(GitVersion_NuGetVersion) but it doesn't seem to get set. 

Here is a snippet of the bottom of my project file

    <PropertyGroup>
        <BuildDependsOn>
          $(BuildDependsOn);
          SetOctoPackVersion
        </BuildDependsOn>
      </PropertyGroup>
      
      <Target Name="SetOctoPackVersion">
        <PropertyGroup>
          <OctoPackPackageVersion>$(GitVersion_NuGetVersion)</OctoPackPackageVersion>
        </PropertyGroup>
      </Target>
      <Import Project="$(SolutionDir)\.nuget\NuGet.targets" Condition="Exists('$(SolutionDir)\.nuget\NuGet.targets')" />
      <Target Name="EnsureNuGetPackageBuildImports" BeforeTargets="PrepareForBuild">
        <PropertyGroup>
          <ErrorText>This project references NuGet package(s) that are missing on this computer. Enable NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is {0}.</ErrorText>
        </PropertyGroup>
        <Error Condition="!Exists('..\packages\GitVersionTask.3.0.1\Build\GitVersionTask.targets')" Text="$([System.String]::Format('$(ErrorText)', '..\packages\GitVersionTask.3.0.1\Build\GitVersionTask.targets'))" />
  </Target>
      <Import Project="..\packages\AutoMapper.3.3.1\tools\AutoMapper.targets" Condition="Exists('..\packages\AutoMapper.3.3.1\tools\AutoMapper.targets')" />
      <Import Project="..\packages\OctoPack.3.0.42\tools\OctoPack.targets" Condition="Exists('..\packages\OctoPack.3.0.42\tools\OctoPack.targets')" />
      <Target Name="EnsureOctoPackImported" BeforeTargets="BeforeBuild" Condition="'$(OctoPackImported)' == ''">
        <Error Condition="!Exists('..\packages\OctoPack.3.0.42\tools\OctoPack.targets') And ('$(RunOctoPack)' != '' And $(RunOctoPack))" Text="You are trying to build with OctoPack, but the NuGet targets file that OctoPack depends on is not available on this computer. This is probably because the OctoPack package has not been committed to source control, or NuGet Package Restore is not enabled. Please enable NuGet Package Restore to download them. For more information, see http://go.microsoft.com/fwlink/?LinkID=317567." HelpKeyword="BCLBUILD2001" />
        <Error Condition="Exists('..\packages\OctoPack.3.0.42\tools\OctoPack.targets') And ('$(RunOctoPack)' != '' And $(RunOctoPack))" Text="OctoPack cannot be run because NuGet packages were restored prior to the build running, and the targets file was unavailable when the build started. Please build the project again to include these packages in the build. You may also need to make sure that your build server does not delete packages prior to each build. For more information, see http://go.microsoft.com/fwlink/?LinkID=317568." HelpKeyword="BCLBUILD2002" />
  </Target>
      <Import Project="..\packages\GitVersionTask.3.0.1\Build\GitVersionTask.targets" Condition="Exists('..\packages\GitVersionTask.3.0.1\Build\GitVersionTask.targets')" />
         <!-- To modify your build process, add your task inside one of the targets below and uncomment it. 
       Other similar extension points exist, see Microsoft.Common.targets.
         <Target Name="BeforeBuild">
         </Target>
         <Target Name="AfterBuild">
         </Target>

**Comment by JakeGinnivan** [comment]
// @SimonCropp

**Comment by johnkattenhorn** [comment]
Interesting ... It's actually still working if I issue the MSBUILD command from my machine but it not working using TFS Build vNext (Visual Studio Online). Previous version was definitely ok.

**Comment by SimonCropp** [comment]
and from VS?

**Comment by johnkattenhorn** [comment]
Oh your both still up :-) I'll check now.

**Comment by johnkattenhorn** [comment]
From VS it is calculated correctly too.

**Comment by johnkattenhorn** [comment]
Was definitely working at the previous release, seems like when run in TFS vNext doesn't pick up previous commits or something from the repository.

**Comment by JakeGinnivan** [comment]
When we get this figured and working, would you be able to throw a bit of a how to into https://github.com/GitTools/GitVersion/blob/master/docs/more-info/build-server-setup/tfs-build-vnext.md

TFS Build vNext actually supports service messages, so we should add first class support so you can just run GitVersion and the service messages are written in the build output, making the variables available in TFS Build. I just haven't got to it or added the issue with all the required info, need to do reading and have a play first

**Comment by johnkattenhorn** [comment]
Sounds good, I'm pretty new to it myself and still leaning on MSBuild within vNext. 

But I'd love to contrib, I know the guys over at Octopus are working on a vNext build step so it would be good to make sure we can still bring the GitVersion.NuGet version over to the package. 

I wonder if the variables created by GitVersion are available in the build steps after the build one ?

**Comment by JakeGinnivan** [comment]
If we use service messages, then yeah they are. It is the setup I use on appveyor and teamcity. I run the exe, then the next steps are my build and all the variables exist and are passed as properties to MSBuild/NuGet etc

**Comment by johnkattenhorn** [comment]
Just to confirm, I've rolled back to 2.0.1 and it works fine. I'll setup a foo project in GitHub tomorrow we can use as a test to see if we can figure what the issue is.

@JakeGinnivan - Had a quick google for Service Messages and didn't turn up much for vNext, if you have any links let me know and I'd be happy to see if I could PR in an implementation, as vNext is a massive step forward and I won't be going back ;-)

**Comment by JakeGinnivan** [comment]
@johnkattenhorn service message docs at https://github.com/Microsoft/vso-agent-tasks/blob/master/docs/authoring/commands.md

**Comment by pascalberger** [comment]
@johnkattenhorn Were you successful yet in getting GitVersion running in TFS Build vNext?

**Comment by pascalberger** [comment]
I tried to pass the version determined by GitVersion to TFS Build vNext using the service message to set a variable. But it seems like this variable can for example later not be used as build number format. See Microsoft/vso-agent-tasks#380

**Comment by onovotny** [comment]
While the VSO team works on letting a MSBuild variable for the display name, it seems like there rest of the functionality can be implemented.

Is someone already working on this? I could submit a PR today if not.

**Comment by pascalberger** [comment]
A PR would be great. I'm currently not working on this.

**Comment by onovotny** [comment]
Fixed in PR #562
