### ISSUE TITLE
NuGet 3.1, GitVersion and Universal Windows Platform(UWP)

### ISSUE THREAD

**Issue by veccie** [GitTools/GitVersion#550]
Soo, I just tried adding GitVersionTask to an UWP project, and at first I couldn't believe what was going on. I mean nothing really happened except GitVersionTask was added as an actual reference in the project. The same happened with GitVersionExe.

Did some searching and found this: http://blog.nuget.org/20150729/Introducing-nuget-uwp.html

The packages.config file is now a project.json file and the package itself is now only stored in a global storage folder .nuget under %userprofile%. Apparently you can't execute install scripts either.

I don't really know much about NuGet and how packages are made, etc, but does this mean manual installation from now on when working on UWP projects?

**Comment by veccie** [comment]
While we're on the subject of UWP projects here's an idea for a future release:

Update version in AppxManifest with AssemblyVersion when the project is for UWP.

The building process is a bit different though, so it could be tricky to figure out exactly when the file can be updated, without being overwritten by another process.

**Comment by gep13** [comment]
@SimonCropp is this related to this:

https://twitter.com/GeertvanHorrik/status/626675872020369409

Thanks!

**Comment by SimonCropp** [comment]
i am testing a fix for this on Fody. if it works i will perform the same fix here

**Comment by SimonCropp** [comment]
@JakeGinnivan what do u want the milestone to be?

**Comment by JakeGinnivan** [comment]
Don't mind, as things get fixed will just push releases. I don't tend to plan what will go into each release

**Comment by onovotny** [comment]
I fixed this in #563

**Comment by SimonCropp** [comment]
closing since #563 is merged
