### ISSUE TITLE
GitVersion not workig for detached head - TFS Build vNext

### ISSUE THREAD

**Issue by onovotny** [GitTools/GitVersion#553]
Some of the time my TFS vNext builds are failing due to blank version numbers being returned from GitVersion (yes, I could check for that, but I want the version!)

```
WARN [08/03/15 8:17:59:29] Could not determine assembly version: It looks like the branch being examined is a detached Head pointing to commit 'c28dce0'. Without a proper branch name GitVersion cannot determine the build version.
```
Seems like the build agents are checking out specific commits in a way that's confusing GitVersion? I do have a GitVersinConfig.yaml with the following:
```
assembly-versioning-scheme: MajorMinorPatch
next-version: 3.0.0
```

**Comment by onovotny** [comment]
So I'm not sure why VSO is in a detached head state, maybe it's doing a checkout of a remote repo?

One workaround for that was to do the following in my VSO build script:
```xml     
<!-- ensure branch is checked out -->
<Exec Command="git checkout -b $(BUILD_SOURCEBRANCHNAME) $(BUILD_SOURCEVERSION)" />
```
VSO does know the branch and commit id, so I just manually call checkout again before the GitVersionTask runs.

**Comment by onovotny** [comment]
So not sure if anything can ultimately be done in GitVersion to work with a detached head, but perhaps the workaround can be added to the docs on using GitVersion with VSO.

**Comment by pascalberger** [comment]
Maybe you can raise an issue over at the https://github.com/Microsoft/vso-agent repo. I assume it's where the git checkout happens.

**Comment by JakeGinnivan** [comment]
Checking out a detached head is very common, we have explicit support for build servers and when GitVersion detects it is running on a build server it normalises the git directory to checkout a branch and also turn remote branches into local ones.

https://github.com/GitTools/GitVersion/blob/master/src/GitVersionCore/ExecuteCore.cs#L13 calls https://github.com/GitTools/GitVersion/blob/master/src/GitVersionCore/GitPreparer.cs#L34 which controls this.

We need to add Team Build vNext to https://github.com/GitTools/GitVersion/tree/master/src/GitVersionCore/BuildServers - another discussion is happening at https://github.com/GitTools/GitVersion/issues/546 about this.

**Comment by onovotny** [comment]
So given the fixups needed for VSO, I think the agent task is really the best way: https://github.com/GitTools/GitVersion/pull/562.

There was a bunch of PowerShell voodoo to normalize stuff as I couldn't use any fetching.
