### ISSUE TITLE
Pulling version from IP in remote url

### ISSUE THREAD

**Issue by igloo15** [GitTools/GitVersion#557]
I have a problem where GitVersion is pulling a version number from an ip in the url of the remote. This happens when GitVersion analyzes merge messages.

Here is a paste bin : http://pastebin.com/NFnFDk5i

I should be on version 2.0 but since the merge message is:
Merge branch 'DEMO' of http://10.10.10.121/gitlab/mtolland/orcid into DEMO

It grabs the IP and makes my version 10.11

**Comment by JakeGinnivan** [comment]
We have an open task at #538 which will allow issues like this to be fixed. We could also try and fix the regexes so ip addresses do not get recognised.

**Comment by igloo15** [comment]
While I think that task #538 will allow me to work around this issue I think that updating regexes to not consider IP addresses is better solution for this particular issue. I don't have alot of experience with Regexes but I will play around with it to see if I can find a regex that will not grab IP addresses.

**Comment by gep13** [comment]
While an addition to the regex to cover this case of an IP Address may address your issue, there are probably yet more edge cases like this that would need to be supported.  A more general approach like ignoring commits before this date, or point in history, means that those edge cases don't need to be addressed.

**Comment by igloo15** [comment]
Yes I agree but maybe the regex could configurable at least because every merge request in this repo is going to have the ip address in the default merge message.

**Comment by gep13** [comment]
@JakeGinnivan I know we have some regex configurations available, but I don't think we have one to cover this situation, right?

**Comment by JakeGinnivan** [comment]
This is something I don't think should be configurable, it could cause issues which are difficult to debug.

I still think the `ignore:` configuration option is fine, we can just have `contains: <ipaddress>` which will automatically filter the merge commits with that ip address in it.

**Comment by igloo15** [comment]
I did not realize there would be an contains option on #538 I thought I was going to have to add an ignore sha to every commit that had an ip. If I can just ignore some text that would be just as good if not better.

**Comment by JakeGinnivan** [comment]
There wasn't :) But no reason not to have multiple ways to exclude things. I will start on #538 tomorrow if noone picks it up first

**Comment by mkoertgen** [comment]
I modified the involved regexp to filter out versions prefixed with '://', cf. #659.

**Comment by mkoertgen** [comment]
I added green testcases for https://github.com/GitTools/GitVersion/issues/557#issue-99349268
and https://github.com/GitTools/GitVersion/issues/557#issuecomment-130436901

**Comment by mkoertgen** [comment]
This should be fixed with #661

**Comment by mkoertgen** [comment]
Can we close this issue, then?
