### ISSUE TITLE
Build Metadata for branch includes invalid characters from branch name

### ISSUE THREAD

**Issue by o-o00o-o** [GitTools/GitVersion#569]
When bringing in the "InformationalVersion" number into a class that performs validation on the semver as per semver.org rules, it fails if we have a branch that has anything other than [a-zA-Z0-9\.\-]. 

Often branches are of the form feature/a feature/b where the forward slash is used as a folder indicator. There could be other invalid characters in git branch names.

Can I suggest that the BranchName property should be left untouched but the InformationalVersion number should be cleaned so we can use it directly. All non alphanumeric chars should be changed to be -'s and then it will always be a valid full semver.

Currently I apply this workaround in Msbuild but better if it did this in the tool directly I think?

**Comment by JakeGinnivan** [comment]
Yeah, it should be done directly in GitVersion.

**Comment by JakeGinnivan** [comment]
Have marked this as up for grabs, feel free to submit a pull request
