### ISSUE TITLE
Support GitVersion.yml config file

### ISSUE THREAD

**Issue by JakeGinnivan** [GitTools/GitVersion#575]
Because `GitVersionConfig.yaml` has the wrong extension and Config is redundant.

**Comment by orjan** [comment]
I think this should be the default behavior in v4 but with a read fallback on the old file with a warning?

**Comment by asbjornu** [comment]
Fallback with warning sounds like a good plan. We don't even need to wait for v4 if we have backwards compatibility, imho.

**Comment by JakeGinnivan** [comment]
Just support both, shouldn't be too hard

**Comment by qetza** [comment]
Hi, i'll do it:
- read GitVersion.yml if present
- if not read GitVersionConfig.yaml and log a warning for deprecated file name.

**Comment by qetza** [comment]
Done in PR #790

**Comment by raybooysen** [comment]
Possible to close this?
