### ISSUE TITLE
Documented commandlineswitch /updateassemblyinfofilename not implemented?

### ISSUE THREAD

**Issue by vegar** [GitTools/GitVersion#584]
I'm trying to specify the name of my assemblyinfo. The commandline help states that

> **AssemblyInfo updating**
>    `/updateassemblyinfo`
>                    Will recursively search for all 'AssemblyInfo.cs' files in the git repo and update them
>    `/updateassemblyinfofilename`
>                    Specify name of AssemblyInfo file. Can also /updateAssemblyInfo GlobalAssemblyInfo.cs as a shorthand

So basically, I should be able to do one of the following:

`>GitVersion.exe /updateassemblyinfo true /updateassemblyinfofilename SharedAssemblyInfo.cs`
`>GitVersion.exe /updateassemblyinfo /updateassemblyinfofilename SharedAssemblyInfo.cs`
`>GitVersion.exe /updateassemblyinfo SharedAssemblyInfo.cs`

But whenever I try to include the `/updateassemblyinfofilename` parameter, I get an error: 

> Failed to parse arguments: /updateassemblyinfofilename ....

Looking into the [code for the argument parser](https://github.com/GitTools/GitVersion/blob/7e94062b0b1fce8e19bebdb6b1e3e9670bf85bd5/src/GitVersionExe/ArgumentParser.cs#L154-L174), I can't see that the `updateassemblyinforfilename`-parameter is implemented at all.

That wouldn't be a large problem, except that the VsoTask is implemented in a way that it's impossible to use this form, since it uses a checkbox for specifying the `updateassemblyinfo`-parameter. If I try to override this by not checking the 'Update AssemblyInfo's'-checkbox and then specify `/updateassemblyinfo nameofassemblyinfo.cs` as an extra argument, the task fails since the argument is added twice:

> 2015-08-18T11:42:34.3961389Z Failed to parse arguments: C:\a\4386bae5\Finale /output buildserver /updateAssemblyInfo false /nofetch /updateAssemblyInfo SharedAssemblyInfo.cs
> 2015-08-18T11:42:34.3961389Z Could not parse command line parameter 'SharedAssemblyInfo.cs'.
 

So there are multiple possible bugs/shortages/inconsistencies here, depending how it *should* work:

**For the commandline tool:**
- [ ] `updateassemblyinforfilename`-argument not implemented in ArgumentParser.cs, or
- [ ] non-existing `updateassemblyinforfilename`-argumente documented in HelpWriter.cs

**And for the VsoTask:**
- [ ] don't output `updateassemblyinfo` argument if false, to allow for override in 'additional arguments', or
- [ ] don't output `updateassemblyinfo`argument if it's given in 'additional arguments'
- [ ] [don't use apostrophe](http://theoatmeal.com/comics/apostrophe) in 'Update AssemblyInfo's' label... :wink:

**Comment by pascalberger** [comment]
I think the VSO task should only add the updateassemblyinfo parameter if the checkbox is set (and don't add any updateassemblyinfo parameter if it is not checked). This might require to use a Powershell script, but this won't be a big issue. I can provide a PR for this, if this is the consensus.

**Comment by vegar** [comment]
I think that sounds like the simplest/best/most clear solution. 

I see there is a spike regarding argument parsing (#572). Maybe the `updateassemblyinfofilename`-argument will just die as part of that PR? Or would it be best to fix this right away?

**Comment by JakeGinnivan** [comment]
The spike for the command line parsing probably won't land for a while.

I think introduce /updateassemblyinfofilename, that will be the quickest way and then we don't need to introduce a powershell script (which means gitversion will work on non-windows build agents when we get mono support working)

**Comment by pascalberger** [comment]
Instead of Powershell we also could use a node script to define the command line arguments, which should work cross plattform.

**Comment by pascalberger** [comment]
Since [Version 3.4.0](https://github.com/GitTools/GitVersion/releases/tag/v3.4.0) a `Update Assembly File` option is available in the VSTS/TFS task.
