### ISSUE TITLE
GitVersionTask 3.0.2, build failure due to invalid namespace

### ISSUE THREAD

**Issue by mauroservienti** [GitTools/GitVersion#602]
Just updated a project to `GitVersionTask` v3.0.2, build *randomly* fails due to `GitVersionInformation` class included in an invalid namespace:

![image](https://cloud.githubusercontent.com/assets/1325611/9422975/5dcc2e10-48ae-11e5-9550-9520448febbb.png)

**Comment by JakeGinnivan** [comment]
3.1 will be released later today and fixes this. Sorry about that!

**Comment by JakeGinnivan** [comment]
I am working on the release as we speak :)

**Comment by JakeGinnivan** [comment]
Ok, have pushed 3.1. Try upgrading now and it should all be fixed

**Comment by mauroservienti** [comment]
works as expected now, many thanks.
