### ISSUE TITLE
Error with 3.1.0 on Jenkins server using SSH

### ISSUE THREAD

**Issue by KenHundley** [GitTools/GitVersion#603]
Hi, I have been using GitVersion 3.0.2 on our jenkins server by parsing the output of "gitversion /output json" with powershell into a properties file and importing into environment variables. These builds are using SSH. I attempted to update to 3.1.0, but I get an error message that it found it's running in a jenkins environment and attempts to communicate with the ssh url, which fails.  

Here is the build output.
INFO [08/24/15 18:33:52:31] Working directory: C:\ws\redacted\work 
INFO [08/24/15 18:33:52:32] Applicable build agent found: 'Jenkins'. 
INFO [08/24/15 18:33:52:43] One remote found (origin -> 'ssh://git@redacted.com:7999/redacted.git'). 
INFO [08/24/15 18:33:52:43] Fetching from remote 'origin' using the following refspecs: +refs/heads/*:refs/remotes/origin/*. 
ERROR [08/24/15 18:33:52:48] An unexpected error occurred: LibGit2Sharp.LibGit2SharpException: Unsupported URL protocol

Is there any way to suppress it attempting to communicate with origin server when it detects it's running on a build server?

**Comment by JakeGinnivan** [comment]
Yeah, use the `/nofetch` switch. We now actually support Jenkins officially and can write out the properties file for you (save you the parsing). See http://gitversion.readthedocs.org/en/latest/more-info/build-server-setup/jenkins

**Comment by JakeGinnivan** [comment]
Have created an up-for-grabs issue which will make it easier to get started on build servers which do a proper clone

**Comment by KenHundley** [comment]
That worked perfectly. Ty for the help
As soon as I get a chance I'll test out the new jenkins output. That'll be a nice imporvement

**Comment by KenHundley** [comment]
One more small thing. I did check the application arguments with a /? but /nofetch wasn't listed.  That should probably be added at some point.

Thanks again for the help
