### ISSUE TITLE
Build server can suggest if fetch is needed

### ISSUE THREAD

**Issue by JakeGinnivan** [GitTools/GitVersion#604]
See #603

Jenkins and VSO both do a proper clone so there is no need to fetch. The buildserver info should be able to tell GitVersion if a fetch is needed so you don't need to use the `/nofetch` switch

**Comment by arthurzaczek** [comment]
The same issue leads to Version = 0.0.0.0 by the MSBuild Task if you build a Project on Jenkins:

MSBUILD : warning : WARN [09/01/15 9:22:35:71] Could not determine assembly version: Unsupported URL protocol [c:\jenkins-node\workspace\*****\***.Core.csproj]

**Comment by JakeGinnivan** [comment]
@arthurzaczek does Jenkins provide an environmental variable with the current branch name?

**Comment by arthurzaczek** [comment]
@JakeGinnivan: Yes

    GIT_BRANCH=origin/master

https://wiki.jenkins-ci.org/display/JENKINS/Git+Plugin

**Comment by JakeGinnivan** [comment]
@arthurzaczek thanks, ended up finding that. Am using that to prevent fetching. If you want to give master a spin and verify it's fixed that would be super handy, otherwise I think it should be fixed next release for you

**Comment by arthurzaczek** [comment]
Hmmmm. I'm trying to reproduce the problem, but it looks like Version 3.3 don't have this problem anymore. 

    Installing 'GitVersionTask 3.3.0'.
    ...
    INFO [01/26/16 12:44:47:13] Applicable build agent found: 'Jenkins'.
    INFO [01/26/16 12:44:47:13] Branch from build environment: 
    INFO [01/26/16 12:44:47:13] One remote found (origin -> '...').
    INFO [01/26/16 12:44:47:13] Skipping fetching, if GitVersion does not calculate your version as expected you might need to allow fetching or use dynamic repositories

**Comment by arthurzaczek** [comment]
YES! It works :-)

    Installing 'GitVersionTask 3.3.1'.
    Finished: SUCCESS

BTW: Thank you very, very much for *build.cmd* - it's easy to build and publish to a (private) NuGet Gallery :-)
