### ISSUE TITLE
v3.1.0 (& 3.0.2) Generating improper NuGetVersion strings

### ISSUE THREAD

**Issue by KenHundley** [GitTools/GitVersion#608]
Hi,
I've noticed an issue where the generated NuGetVersion and NuGetVersionV2 strings are invalid.  
We have some branches that were created like "feature/123-SomeFeature".  When we run GitVersion on this branch the NuGetVersion and NuGetVersionV2 appear like "2.1.0-123-somefeature0010".  This is actually an invalid version string. Nuget does not allow the pre-release to start with a number

Nuget pack output: `'2.1.0-123-somefeature0010' is not a valid version string.
Parameter name: version`

I'm not sure what the best fix for this is. Currently I'm manually generating the Nuget version and appending an arbitrary "b" before the number like: `2.1.0-b123-somefeature0010`
Another suggestion may be to remove any non-alpha characters from the start of the branch name.

**Comment by vegar** [comment]
I second this. We use the backlog id first in our branch name, and it would be nice to keep that as part of the pre-release tag. 

Currently, I have managed to solve this by adding the following to the gitversion-config:

>  pbi[/-]:
>    mode: ContinuousDeployment
>    tag: pbi

which gives me nugetversion like `1.0.0-pbi0010`, where `0010` is the commit-count, but I would rather have something unique for the branch, like `1.0.0-pbi123-0010`.

**Comment by onovotny** [comment]
Related to this, I also see some invalid strings if I have a branch `features/foo` with the default configuration. The pre-release tag shows up as `-features/foo`

**Comment by mkoertgen** [comment]
This is also typical for me when working on feature branches prefixed with issue number (e.g. JIRA). And in fact, this is due to an unfixed bug in NuGet, cf.: [NuGet #1743](https://github.com/NuGet/Home/issues/1743)

**Comment by asbjornu** [comment]
As @nshenoy points out in https://github.com/GitTools/GitVersion/issues/1067#issuecomment-258104776, NuGet 3.5 is RTM and solves this problem. Doesn't that mean this issue can be closed?

**Comment by mkoertgen** [comment]
I just updated using `nuget update -self` to `3.4.4-rtm-final`. Right now, the `recommended-latest`-link on http://dist.nuget.org/index.html still points to 3.4.4-rtm-final. Let's wait until this maps to 3.5.0.

**Comment by asbjornu** [comment]
[NuGet Server got SemVer 2.0 support in v2.14.0](https://twitter.com/nuget/status/905884837776465921) and [NuGet.exe got SemVer 2.0 support in v4.3](https://docs.microsoft.com/en-us/nuget/create-packages/prerelease-packages#semantic-versioning), so this shouldn't be a problem anymore. For those who need less syntactically rich version numbers, the variable `NuGetVersion` might be a better fit than `FullSemVer`.
