### ISSUE TITLE
GitFlow Feature Branches not incrementing

### ISSUE THREAD

**Issue by RDalziel** [GitTools/GitVersion#614]
Is there any extra configuration required to have Feature branches increment?

This is a fairly new repository with no Release Branches or master tags yet, it seems that Feature Branches are staying on 001.

Note: There doesn't appear to be any issue with incrementing the develop versions.

**Comment by RDalziel** [comment]
See below: FullSemVer shows the AnotherFeatureBranch as 1+5 (I'm assuming this is commits)?

![screenshot 152](https://cloud.githubusercontent.com/assets/3485935/9562423/14815dc8-4e64-11e5-9b41-37e549875b1e.jpg)

Shouldn't the NuGetVersion be "1.1.0-anotherfeature0005"?

**Comment by orjan** [comment]
Have you set the mode to continiousdeploy? Run "gitversion init" to setup your config. Run "gitversion /showconfig" to view the effective configuration beeing used

/Örjan

**Comment by RDalziel** [comment]
Ah! Switching from Continuous Delivery to Continuous Deployment seems to resolve the issue. 

Is there a recommended way of doing this when using as part of a build process? Specifically the VSO Build Process?
