### ISSUE TITLE
BuildMetaData need a padded version

### ISSUE THREAD

**Issue by onovotny** [GitTools/GitVersion#617]
BuildMetaData currently is an unpadded-only value. If we want to use it for a NuGet CI build for packages, a padded version is more useful.

If you know you won't have more than 10 of a beta/RC, then it's nicer to just use 

$(GitVersion.LegacySemVer)-build$(GitVersion.BuildMetaData) as the NuGet version. But for NuGet's alphabetical sort, that last bit should be padded.

**Comment by JakeGinnivan** [comment]
You want to switch GitVersion into continuous deployment mode. http://gitversion.readthedocs.org/en/latest/reference/continuous-deployment/

Sent from my Windows Phone
________________________________

**Comment by onovotny** [comment]
Not sure that's really what I want. I want to have x builds of an RC3. I don't want it incrementing RC3, RC3, RC...N. I'm creating -rc3-build<blah> that goes to MyGet. One of them will be RC3, in which case I'll publish from MyGet and drop the -build tag.

**Comment by JakeGinnivan** [comment]
How do you drop the build tag? Do you repackage the NuGet package? 

In this case maybe MyGet is not the right store, I keep my artifacts on my build then publish them from there. The other thing is maybe we need to talk to the MyGet team and support feeds with build metadata, they should be super limited though so they are not accidentally used as a real NuGet feed. I think Octopus will be going down this road to have feeds with multiple packages of the same version.

These feeds should also support proper semver so we do not need to pad the build metadata. What do you think?
