### ISSUE TITLE
New version mode for doing incremental builds of a prerelease

### ISSUE THREAD

**Issue by onovotny** [GitTools/GitVersion#621]
This follows up from a discussion in Gitter.

For xUnit, we publish NuGet's to MyGet for every build that we then consume in our integration projects. We will tag something as a -beta or -rc at some point and then do CI builds on those.

So for example, we have -rc3-build1083, -rc3-build1084, etc. 

Essentially we need a way to "fix" a pre-release tag and then have GitVersion increment another element of that. At some point we can either declare a "stable" -rc3 build and run a build on that. Maybe via something in the branch tag or next-version?

We can also sometimes use MyGet's publish feature to have it alter the package version when it pushes to NuGet, though that only works for some projects that have less complicated internal package dependencies.

**Comment by onovotny** [comment]
The build portion of this can be dealt with by using my changes in #701 as a starting place

**Comment by pascalberger** [comment]
@onovotny Is this still an issue or already fixed with #701?

**Comment by JakeGinnivan** [comment]
I know this is a super old issue, but the v4 mainline mode should solve this nicely. Going to close
