### ISSUE TITLE
Mixed up branches when running in TeamCity

### ISSUE THREAD

**Issue by orjan** [GitTools/GitVersion#624]
Running GV 3.1.1 on TC I'm having a issue with GV using the branch from the previous build see attached image. I've also seen this we're "develop" got the version from a feature-branch pointing at the same commit. I've tried to reproduce this with a failing integration test but have failed and even locally against the same repository but have failed. @JakeGinnivan do you have a clue what could be wrong or how to mimic the TC behavior so I can reproduce the issue locally and provide a fix?

![image](https://cloud.githubusercontent.com/assets/124032/9614778/28a83c08-50f4-11e5-8336-90a17df66c81.png)

<img width="1105" alt="2015-08-28 23_02_25-brikks __ development __ build release _ overview teamcity" src="https://cloud.githubusercontent.com/assets/124032/9614992/a69a5cbc-50f5-11e5-9dd6-870e7fec148b.png">

On hint could be, `HEAD points at branch 'refs/heads/feature/BRIKKS-4446` from the gist below:
https://gist.github.com/orjan/40c8fc5ac36e10e381c8

**Comment by orjan** [comment]
Another side effect of this issue is that TC will build the wrong branch e.g. the semver is working but the wrong branch is built.

**Comment by orjan** [comment]
@JakeGinnivan is it possible to get a release of 3.1.2 during the weekend?

**Comment by JakeGinnivan** [comment]
Yeah will do

**Comment by orjan** [comment]
Awesome, thanks a lot!

**Comment by asbjornu** [comment]
We experienced this problem just now. @JakeGinnivan It would be great with a 3.1.2 release as soon as possible! :)

**Comment by JakeGinnivan** [comment]
Released!

**Comment by asbjornu** [comment]
@JakeGinnivan :+1: :smile:
