### ISSUE TITLE
[Feature Request] Allow creation of source file containing assembly version information

### ISSUE THREAD

**Issue by Philo** [GitTools/GitVersion#630]
Using /updateassemblyinfo true|<file> will update the existing version information stored within either **/AssemblyInfo.cs or <file>, however I think it would be useful to provide an option to actually create <file> and populate it with assembly version information if the file does not exist.

```
GitVersion.exe /updateassemblyinfo VersionAssemblyInfo.cs
```

will:

* check for the existence of VersionAssemblyInfo.cs, if found will update existing version attributes
* if VersionAssemblyInfo.cs does not exist, create the file and add the version attributes to it
 - Inspect the filename extension to .cs or .vb to determine whether the generated file should contain VB and C# code

In general a common/global assembly info file would not be committed to source control, and for large projects managing individual AssemblyInfo.* files would be a pain.

Thoughts?

**Comment by robdmoore** [comment]
If GitVersion is creating the file then wouldn't that mean it probably hasn't been referenced in the .csproj? Hence the file won't be used if it's created.

The only time this wouldn't be the case is if it's in the gitignore, but then you would break the local clone and build (without gitversion) scenario.

**Comment by Philo** [comment]
In our workflow we have build tasks that would be executed locally against a freshly cloned repository, if a new developer was starting on a code base.  They would be running this initial script (usually the same script executed on our build server) before beginning work, this would create the ```CommonAssemblyInfo.cs``` file along with any other setup required.

We never commit the "CommonAssemblyInfo.cs" file for our projects, it is always generated via a script or build server workflow task.

In this scenario I have to add a build workflow step to create the file prior to executing GitVersion, my preferred solution would be that we remove the version attributes from our "CommonAssemblyInfo.cs" and add a new "VersionAssemblyInfo.cs" file that is generated by GitVersion.

__**/Properties/AssemblyInfo.cs__ (within each project)
```c#
using System.Reflection;

[assembly: AssemblyTitle("Product.Stuff")]
```

__CommonAssemblyInfo.cs__
```c#
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyDescription("My product rocks")]
[assembly: AssemblyCompany("Best Company Ever")]
[assembly: AssemblyProduct("My Super Product")]
[assembly: AssemblyCopyright("Copyright 2015")]
[assembly: ComVisibleAttribute(false)]
```

__VersionAssemblyInfo.cs__
```c#
//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by GitVersion.
// 
// You can modify this code as we will not overwrite it
// </auto-generated> 
//------------------------------------------------------------------------------
using System.Reflection;

[assembly: AssemblyFileVersion("0.1.0.0")]
[assembly: AssemblyVersion("0.1.0.0")]
[assembly: AssemblyInformationalVersion("0.1.0.0+1.Branch.master.Sha.<something>")]
```

Then the ```VersionAssemblyInfo.cs``` file can be added to ```.gitignore``` and generated on build.

We could add an argument to specify whether this behaviour should be applied:

```GitVersion.exe /updateassemblyinfo VersionAssemblyInfo.cs /ensureassemblyinfo```

I will submit a pull request with my implementation for review

**Comment by JakeGinnivan** [comment]
See discussion in #631 for more history on this issue

**Comment by JakeGinnivan** [comment]
We need to also add a test which makes sure you can use full paths in that switch. i.e. `/updateAssemblyInfo src/Properties/AssemblyInfo.cs`

**Comment by JakeGinnivan** [comment]
We should also probably allow the switch to be specified multiple times

**Comment by JakeGinnivan** [comment]
@Philo this is fixed, right?

**Comment by Philo** [comment]
@JakeGinnivan 

afaik, the ability to create assembly info files outside of my pull request is not available?

I have updated my branch to include options to specify multiple files for update.

See commit message for info: 8c189ca70c0efa7242cdc1a49bd500fabae10e55

**Comment by JakeGinnivan** [comment]
Did you want to get this into a PR and update the docs? :) Would love to close this out

**Comment by Philo** [comment]
created pull request #760

**Comment by JakeGinnivan** [comment]
Opening #871 with a small issue.
