### ISSUE TITLE
Visual Basic My Project\AssemblyInfo.vb supported?

### ISSUE THREAD

**Issue by Pitterling** [GitTools/GitVersion#633]
The documentation just talkes about the C# AssemblyInfo file - Properties\AssemblyInfo.cs
http://gitversion.readthedocs.org/en/latest/usage/#msbuild-task

VisualBasic has this information here - My Project\AssemblyInfo.vb

**Comment by JakeGinnivan** [comment]
We actually do support AssemblyInfo.vb in the .exe, but not the Task it seems. Happy to receive a PR

**Comment by Pitterling** [comment]
It also works for the VB AssemblyInfo file.

**Comment by pascalberger** [comment]
This seems like a duplicate of #138. I propose to close this issue and continue discussion in #138.

**Comment by JakeGinnivan** [comment]
Agreed
