### ISSUE TITLE
Symbols package fails to publish when using GitVersionTask due to missing file

### ISSUE THREAD

**Issue by Philo** [GitTools/GitVersion#636]
Log from Appveyor:

_Publishing assembly.symbols.nupkg to https://nuget.symbolsource.org/MyGet/somefeed...Skipped (Package submission failed: Source file C:\projects\assembly\obj\Release\GitVersionTaskAssemblyInfo.g.cs not found in package. Source file is declared in assembly.pdb. . See http://www.symbolsource.org/Public/Home/Help for possible reasons. Fiddler may help diagnosing this error if your client discards attached detailed information.)_

**Comment by JakeGinnivan** [comment]
// @SimonCropp @distantcam

**Comment by distantcam** [comment]
@Philo How are you packaging up your symbol package? GitVersionTask generates a file at compile time that will need to be included as part of the source files.

**Comment by SimonCropp** [comment]
TBH i have seen many tools break symbolsource in this way. For example 

 * use of ILMerge
 * pre compilation injection
 * IL Manipulation

I have seen a non-trivial amount of time trying to solve this problem and in most cases the outcomes were either 

 * horrible hacks to include the cs files 
 * faking the files
 * giving up on symbolsource as not worth the effort

I have chosen the last one. I have no interest in jumping through hoops to work around that particular error. Having said that if someone else wants to solve it or document a workaround i am happy. But as it stands GitVersionTask and symbolsource should be considered incompatible.

FWIW I think the real fix is for symbolsource to support partial source maps ie with some files missing

**Comment by Philo** [comment]
@distantcam, the symbols package is being created via the standard nuget pack -symbols command line.

I was led to trying to GitVersionTask through my pull request #631.  Where the general opinion seems to be against having GitVersionExe allow the creation of VersionAssemblyInfo files.  Since using GitVersionTask will not allow me to create a complete symbols package (regardless of whether it is GitVersion or SymbolSource at fault), that leads me to push more for some way of auto-generating Version attributes like the implementation in #631

**Comment by JakeGinnivan** [comment]
Not sure how to action this issue. Going to close, if there is something that needs to be fixed in GitVersion let us know, but not sure this is a GitVersion issue?
