### ISSUE TITLE
Version 3.1.2 causing error on build : "BuildMetaDataPadded" parameter not supported

### ISSUE THREAD

**Issue by skipperTux** [GitTools/GitVersion#644]
Not sure if this is really an _issue_, but when updating the NuGet package of GitVersionTask from 3.1.1 to 3.1.2 I get the following error message on build.

> The "BuildMetaDataPadded" parameter is not supported by the "GetVersion" task. Verify the 
> parameter exists on the task, and it is a gettable public instance property.

I did a build clean before, and checked for the same version of GitVersion.portable installed via chocolatey. When in the project directory running GitVersion the "missing" parameter is empty (""), but existing.
When reverting the GitVersionTask package to Version 3.1.1 everything is working again, build succeeds.

**Comment by pascalberger** [comment]
`BuildMetaDataPadded` was added with #623.

But NuGet Task should be already updated with the new parameter: https://github.com/GitTools/GitVersion/blob/master/src/GitVersionTask/NugetAssets/GitVersionTask.targets#L45

**Comment by skipperTux** [comment]
As supposed it was not an issue. I had some cross reference to another project in the csproj file, and that project was still on GitVersionTask 3.1.1. Removed the reference and build succeeds with version 3.1.2 also.
Case closed.
