### ISSUE TITLE
Expose the prelease part of SemVerPadded

### ISSUE THREAD

**Issue by sunsided** [GitTools/GitVersion#651]
For `dnx`/`dnu`-based builds (#647), I'm required to set the `DNX_BUILD_VERSION` environment, which will replace the placeholder asterisk in `project.json`. An `DNX_BUILD_VERSION=unstable1234` with a `1.0.0-*` setting would result in a `1.0.0-unstable1234` build and NuGet package.

In order to circle around incompatibilites with `dnx`-based, GitVersion and v2-based NuGet feeds, the prerelease and padded prerelease part (e.g. `unstableXXXX` of `LegacySemVerPadded`) is required as a separate export. 

Alternatively a `GitVersion.DnxBuildVersion` could be exposed.

**Comment by sunsided** [comment]
For the record, I worked around this at the moment using a powershell script in TeamCity to split the version number and then pad it manually. The script can be found [in this gist](https://gist.github.com/sunsided/c647bcee55afa892344d).

**Comment by JakeGinnivan** [comment]
I am struggling to find where `DNX_BUILD_VERSION` and such is documented. Does it automatically remove the `-` for you if no build version is specified?

**Comment by asbjornu** [comment]
Woudn't `GitVersion.DnxBuildVersion` be the cleanest and most consistent way to expose this?

**Comment by sunsided** [comment]
@JakeGinnivan there's probabl no point searching for any documentation at the moment, it's still in the process of being written for very large parts. But yes, indeed, it's as you suspect. Have a look at my comments on #647.
@asbjornu I personalyl dislike this option as it implies the usage and that might underly some constraints the user's not aware o if he requires the same information elsewhere. If the tag part of the nuget version is all he needs, why not use that. That said, I'm fine with either option.

**Comment by JakeGinnivan** [comment]
I am leaning towards @sunsided's idea, I wasn't a massive fan of NuGetVersion because GitVersion was supposed to be agnostic but it did make it more discoverable. For DNX I'm not so sure as it is far more lightweight and hopefully doesn't have all the issues NuGet has.

We should just expose `BuildNumber` which is normally commit count, and also expose `BuildNumberPadded`. I also think we should have `PreReleaseDash` or something for doing manual concatenation rather than `PreReleaseTagWithDash`

**Comment by asbjornu** [comment]
@JakeGinnivan Sounds good! :+1:

**Comment by JakeGinnivan** [comment]
I think this is covered by existing variables plus #742

Am I missing anything?
