### ISSUE TITLE
Build Server Git Normalization leaves repo in wrong branch

### ISSUE THREAD

**Issue by dtabuenc** [GitTools/GitVersion#655]
When running on jenkins, during the git "normalization" process I see log messages about:

"Creating local branch from remote tracking "refs/remots/origin/feature/some-feature"

So while the build might have started on release/1.21 branch, When GitVersion runs it switches the current branch to feature/some-feature, producing an incorrect version number (1.22.0-some-feature.1) and leaving the repo in an incorrect state to continue bulding.

**Comment by KenHundley** [comment]
I've been experiencing the same issue on Jenkins as well. 

I just updated our version to 3.1.2 as it seemed similar to #624 reported on Teamcity. So far so good, but I'll report back if I continue to have issues after the update.

**Comment by gep13** [comment]
I was just about to ask...

@dtabuenc what version of GitVersion are you currently using?

**Comment by KenHundley** [comment]
I was experiencing the issue with 3.1.0 when running "/nofetch /output buildserver" on jenkins. Have not seen it yet since updating, but it's sort of random when it seems to happen

**Comment by JakeGinnivan** [comment]
This has been fixed in the latest versions. This is the PR which fixed it https://github.com/GitTools/GitVersion/pull/626
