### ISSUE TITLE
Documentation is wrong - 

### ISSUE THREAD

**Issue by Pitterling** [GitTools/GitVersion#662]
http://gitversion.readthedocs.org/en/latest/usage/#msbuild-task says

>Ensure you remove the Assembly*Version attributes from your Properties\AssemblyInfo.cs file so as to not get duplicate attribute warnings. Sample default:
```c#
[assembly: AssemblyVersion("1.0.0.0")]
[assembly: AssemblyFileVersion("1.0.0.0")]
[assembly: AssemblyInformationalVersion("1.1.0+Branch.master.Sha.722aad3217bd49a6576b6f82f60884e612f9ba58")]

In fact you need to have these attributes in the AssemblyInfo.cs file otherwise they will not be set. Data is just replaced by Regex and not created if it does not exist.

AssemblyInfoFileUpdate.cs --> public AssemblyInfoFileUpdate
```c#
var fileContents = fileSystem.ReadAllText(assemblyInfoFile)
                    .RegexReplace(@"AssemblyVersion\(""[^""]*""\)", string.Format("AssemblyVersion(\"{0}\")", assemblyVersion))
                    .RegexReplace(@"AssemblyInformationalVersion\(""[^""]*""\)", string.Format("AssemblyInformationalVersion(\"{0}\")", assemblyInfoVersion))
                    .RegexReplace(@"AssemblyFileVersion\(""[^""]*""\)", string.Format("AssemblyFileVersion(\"{0}\")", assemblyFileVersion));

**Comment by gep13** [comment]
This is true when you are using the GitVersion.exe, however, when you are using the GitVersionTask, which is what that page is referring to, I believe a temporary AssemblyInfo file is created, and that is why you have to remove the attributes from the main assemblyinfo file.

https://github.com/GitTools/GitVersion/blob/master/src/GitVersionTask/AssemblyInfoBuilder/UpdateAssemblyInfo.cs

Is that correct @SimonCropp

**Comment by asbjornu** [comment]
@gep13 Yes, that's correct. `GitVersion.exe` patches existing `Assembly*Version` attributes, while `GitVersionTask` adds them (thus; they can't already exist).

**Comment by Pitterling** [comment]
The thing is that the naming is somehow misleading, because the VSO Step is also called GitVersionTask
![capture](https://cloud.githubusercontent.com/assets/4181164/10302116/91f77662-6c09-11e5-847a-2b0f040b9538.PNG)

**Comment by gep13** [comment]
@Pitterling just so I am clear...

Are you saying that the documentation should refer to GitVersion Task, rather than MSBuild Task?

**Comment by Pitterling** [comment]
I'm just saying that the documentation is not always clear. VSO GitVersionTask is also called Task but it is using GitVersion.exe underneath, therefore i need the Assembly*Version attributes, while GitVersionTask in your answers always refers to MS Build Task and here i have to remove the Assembly*Version attributes.

**Comment by pascalberger** [comment]
@Pitterling I added a PR (#683) which adds documentation how the updating of AssemblyInfos behaves with the command line tool. Do you think this is clear now with this changes?

**Comment by Pitterling** [comment]
@pascalberger Thank you. Its much clearer now. Unfortunately when talking about AssemblyInfo only *.cs files are mentioned, but GitVersion.exe also works for *.vb files.
