### ISSUE TITLE
Allow {BranchName} in tag config

### ISSUE THREAD

**Issue by o-o00o-o** [GitTools/GitVersion#664]
As per #632 

Currently the prerelease tag configuration is fine except for feature branches where there can be many of them at the same time for the same version. The problem here is that with the current useBranchName config, feature branches starting with "a" are considered the lowest prerelease version and any feature branch starting with "z" will be the latest one. To solve this we should be able to prefix the feature braches "something." so they can be positioned in the desired order consistently no matter what the name of the feaure branch. 

E.g feature/AddForgottenPassword and feature/ZeroAllowedInAmount could be v1.0.0-alpha.AddForgottenPassword and v1.0.0-alpha.ZeroAllowedInAmount which would then both be seen as the same level compared with the other develop/release and master branches.

To achieve this @JakeGinnivan suggested using c# string interpolation so in config something like:

tag: alpha.{BranchName} 

For branch feature/FixLogin
Would produce a semver like 0.0.0-alpha.FixLogin

**Comment by gusztavvargadr** [comment]
I just wanted to double check if is #766 works like what you expect, but I see it just got merged, thanks @JakeGinnivan :)

**Comment by JakeGinnivan** [comment]
Yep, exactly what I was after.

I think in v4 this will become the default behaviour.

**Comment by mkoertgen** [comment]
Great feature! 

+1 for making `tag: alpha.{BranchName}` the new default for feature branches. 

BTW, this feature enables to workaround problems with `nuget pack` when feature branches begin with a number, cf. https://github.com/NuGet/Home/issues/1743, which seems to be common practice when working with issue trackers.

Very cool. Using it straight away!
