### ISSUE TITLE
Update http://particularlabs.github.io/GitVersion/

### ISSUE THREAD

**Issue by pascalberger** [GitTools/GitVersion#666]
The website at http://particularlabs.github.io/GitVersion/ seems to be quite outdated (all links ending on the root of this repo), but still linked in the description from this repo and from several other places in the web.

**Comment by gep13** [comment]
I was actually thinking about this the other day, as I stumbled across the site again.  If anything, I think that site should go, and simply use the main ReadTheDocs site.

Thoughts?

**Comment by gep13** [comment]
For now, I have changed the main WebSite link for this repo to point at http://gitversion.readthedocs.org/en/latest/ and we can decide how we want to proceed with the other site.

**Comment by pascalberger** [comment]
Completely replacing the site with the ReadTheDocs site sounds good to me

**Comment by JakeGinnivan** [comment]
This link is 404 now. Closing
