### ISSUE TITLE
GitVersionTask not updating assemblyinfo.cs

### ISSUE THREAD

**Issue by mrbelk** [GitTools/GitVersion#668]
I have installed the GitVersionTask via nuget (also installed GitVersion.Portable via chocolately. I think I've configured it to operate in ContinuousDeployment mode for feature and develop branches, but when I build my solution, it doesn't update the assemblyfile.cs files with the correct version nor does it tag the repository correctly (is it supposed to tag the repository automatically?).  I'm currently not using a build server and there are no messages in my local machine's build output window, but maybe there's not supposed to be.

Here is the results of "gitversion /showconfig"

assembly-versioning-scheme: MajorMinorPatch
mode: ContinuousDelivery
tag-prefix: '[vV]'
continuous-delivery-fallback-tag: ci
major-version-bump-message: '\+semver:\s?(breaking|major)'
minor-version-bump-message: '\+semver:\s?(feature|minor)'
patch-version-bump-message: '\+semver:\s?(fix|patch)'
legacy-semver-padding: 4
build-metadata-padding: 4
commit-message-incrementing: Enabled
branches:
  features?[/-]:
    mode: ContinuousDeployment
    tag: useBranchName
    increment: Inherit
    prevent-increment-of-merged-branch-version: false
    track-merge-target: false
  master:
    mode: ContinuousDelivery
    tag: 
    increment: Patch
    prevent-increment-of-merged-branch-version: true
    track-merge-target: false
  releases?[/-]:
    mode: ContinuousDelivery
    tag: beta
    increment: Patch
    prevent-increment-of-merged-branch-version: true
    track-merge-target: false
  (pull|pull\-requests|pr)[/-]:
    mode: ContinuousDelivery
    tag: PullRequest
    increment: Inherit
    prevent-increment-of-merged-branch-version: false
    tag-number-pattern: '[/-](?<number>\d+)[-/]'
    track-merge-target: false
  hotfix(es)?[/-]:
    mode: ContinuousDelivery
    tag: beta
    increment: Patch
    prevent-increment-of-merged-branch-version: false
    track-merge-target: false
  support[/-]:
    mode: ContinuousDelivery
    tag: 
    increment: Patch
    prevent-increment-of-merged-branch-version: true
    track-merge-target: false
  dev(elop)?(ment)?$:
    mode: ContinuousDeployment
    tag: unstable

thanks,
Matthew

**Comment by mrbelk** [comment]
OK, I see now that the version info is built into the assembly, but the actual assemblyinfo file is not modified.  Now, is there a way to automatically create the tags from the Semantic Version values? Do most people just execute a command line "git tag -a" command from the .csproj or MSBuild file?

**Comment by gep13** [comment]
>OK, I see now that the version info is built into the assembly, but the actual assemblyinfo file is not modified.

That is correct, a temporary assemblyinfo file is created when using the task, and this is compiled into the assembly.  You will actually need to remove the attributes from your current assemblyinfo file, as documented here:

http://gitversion.readthedocs.org/en/latest/usage/#msbuild-task

GitVersion isn't responsible for creating any tags in your repository, this is something that you would do outwith GitVersion.

**Comment by mrbelk** [comment]
yeah, I removed the Assembly*Version attributes already; I just thought that the file would be modified rather than a shadow file compiled and then removed.

**Comment by mrbelk** [comment]
so do people just manually add the tags based on what GitVersion reports? I tried to exec git tag -a $(GitVersion_SemVer) in the "AfterBuild" target of my project's .csproj file and it hangs.  I set the working directory to the "$(SolutionDir)" which is the top level of my git repository.

**Comment by JakeGinnivan** [comment]
The tag should be added by your build/release process ideally.

**Comment by JakeGinnivan** [comment]
There is a fair bit of info in the docs about version incrementing and how to use GitVersion. Also my podcast at https://www.dotnetrocks.com/default.aspx?showNum=1178 explains quite a bit of the broader topic

**Comment by mrbelk** [comment]
Everything works as expected except my attempt to auto-tag from the AfterBuild MSBuild target.

**Comment by gep13** [comment]
@mrbelk If you are interested, this is the process that I follow for the ChocolateyGUI project:

https://gitreleasemanager.readme.io/docs/example-workflow

**Comment by mrbelk** [comment]
@gep13 this looks great.  thanks for the link. I'll take a look

**Comment by JakeGinnivan** [comment]
As far as I can see, this issue can be closed. Let me know if that isn't the case or we need to do some follow up docs or something (also PRs are welcome which update docs based on your learnings).
