### ISSUE TITLE
Resetting commit count to 0 on new branches with ContinuousDeployment

### ISSUE THREAD

**Issue by KenHundley** [GitTools/GitVersion#681]
Hi,
I've been trying to figure out if it's possible to force gitversion to reset the commit count with each new feature / release / hotfix branch when using ContinuousDeployment.

Here is what I'm seeing:
develop version is say "1.1.0-unstable.4" (4 commits past 1.0.0 tag) which is what I expect, but if I branch a new feature (feature/f1) from develop I get "1.1.0-f1.4". I would rather have "1.1.0-f1.0" since there have been no commits on that branch. Although I know from looking at the git graph this may not be possible.

It's even more pronounced when we branch for a release. Usually when I branch it'll be something like
"1.1.0-beta0107" which is confusing to some people since they would expect it to start at 0. 

I've looked through the docs and prior posts, but I haven't found anything addressing this. So any advice would be appreciated.

I'm using version 3.1.2

**Comment by JakeGinnivan** [comment]
This sounds like the same issue as #700

If you can pull down master and verify this is fixed for you, if it isn't a test would be super helpful :)

**Comment by pkiers** [comment]
Hello,

I've recently found one curious case about the stuff we discussed last time, just take a look <http://desire.construction-consulting.com/e2awmpm>

Pardon my monkey thumbs, p.kiers@home.nl
