### ISSUE TITLE
Checking code with sonar

### ISSUE THREAD

**Issue by pascalberger** [GitTools/GitVersion#688]
It would be nice if the code could be check with [SonarQube](sonarqube.org). There exists a [nice plugin](http://www.sonarqube.org/github-pull-request-analysis-helps-fix-the-leak/) for automatically have Sonar commenting on PRs in GitHub. 
The catch is that it would need a Sonar instance running somewhere. There is [Nemo](http://nemo.sonarqube.org/), a public Sonar instance for OSS projects, but I don't know if it is possible to get listed there and use it with the GitHub pugin. Maybe there's another possibility to have a Sonar server runned somewhere.

**Comment by orjan** [comment]
@pascalberger would you mind giving an elevator pitch for SonarQube?

**Comment by pascalberger** [comment]
Sonar is a plattform for managing code quality and technical debt. Think about it as having code analysis or StyleCop run and reported back. It could also detect code duplicates, report about test coverage, etc

**Comment by JakeGinnivan** [comment]
SonarQube is something I want to play with and understand. Would you mind setting up an account @pascalberger and configuring it, then fire me through our login details (jake at ginnivan dot net) so I can check it out.

**Comment by pascalberger** [comment]
OK, I'll check if we can get an account on Nemo

**Comment by pascalberger** [comment]
@JakeGinnivan Here's their reply: 

> We're hoping to make it possible for you to set this sort of thing up yourself "soon", but in the meantime, we have to run the build and analysis for you. Unfortunately, I don't have any Windows slaves at my disposal, so while we'd welcome you on Nemo, I'm afraid it will have to be later, rather than sooner.

So I assume we have to wait until Version 4 and Mono support.

**Comment by pascalberger** [comment]
I now have an access to https://sonarqube.com (their Cloud Service) for GitVersion.

@asbjornu Do you think you can help me with integrating this into the travis build? There already other .NET projects using it (eg. https://github.com/OpenCover/opencover / https://sonarqube.com/overview?id=opencover) with AppVeyor

**Comment by gep13** [comment]
@pascalberger @asbjornu I will be watching this one with interest :-D

**Comment by pascalberger** [comment]
@asbjornu I don't know what our plans are regarding build server? Do we plan to completely switch to Travis or keep AppVeyor?

**Comment by gep13** [comment]
@pascalberger I think the plan would be to have both.  Travis for OSX and Linux, and AppVeyor for Windows.  Likely AppVeyor will be the "primary" CI server, and the one responsible for doing the deployments.

**Comment by asbjornu** [comment]
While I'd love SonarQube reporting for GitVersion, nothing seems to have happened since 2016 so I'll close this in await for a possible PR.
