### ISSUE TITLE
Cannot disable apply defaults

### ISSUE THREAD

**Issue by qetza** [GitTools/GitVersion#692]
I've updated my GetVersionConfig.yaml file so that the release branches do not generate a tag but i always get a tag of 'beta'.

It seems to come from the `ConfigurationProvider.Provide` method which is always called with `applyDefaults` to `true`. Since an empty Tags line is deserialized as a null value, my empty value is replaced by the default value 'beta' :(

It would be great to either be able to disable defaults value (through a command line switch or a parameter in the config file) or make sure that if a line is present in the file it's value is kept even if empty.

**Comment by JakeGinnivan** [comment]
Hey @qetza 

I just checked and confirmed with a test that if you put `""` into the value for the tag it will overwrite the default with an empty string.

i.e 

```
branches:
    releases?[/-]:
        tag: ""
```

I have also updated the docs. Hope that helps
