### ISSUE TITLE
Development branch version not updated after creating a release branch

### ISSUE THREAD

**Issue by qetza** [GitTools/GitVersion#693]
When i create a release branch from dev i would expect my dev branch to start it's version based on the release branch.

For example if my 'dev' has version '0.2.0-unstable' and i create a release branch 'release/0.2.0' i would expect my next commit on dev to become '0.3.0-unstable'. Creating a new release branch 'release/0.5.0' (0.4.0 has gone missing :) ) would make my next 'dev' version '0.6.0-unstable'.

**Comment by JakeGinnivan** [comment]
It will bump once the release branch is merged to master. Otherwise the version on develop would drop if you deleted the branch without merging.

**Comment by orjan** [comment]
@qetza is this issue the same as #695?

**Comment by qetza** [comment]
@orjan yes it's the same issue.

**Comment by orjan** [comment]
@qetza would you mind closing this issue and continue the discussion in #695?

**Comment by qetza** [comment]
Same as issue #695
