### ISSUE TITLE
Feature request: git-gitversion-tag command

### ISSUE THREAD

**Issue by pi3k14** [GitTools/GitVersion#705]
It would have been nice with a custom git command that did something like

version = gitversion /showvariable SemVer
git tag version
git push origin version

and then just run it with
git gitversion tag

**Comment by JakeGinnivan** [comment]
I don't think we should do this, gitversion is already pretty complex with a lot of features. This is starting to push the scope past what I think we should be doing. 

As convenient as it would be the workaround is not very complex and you could create a simple git alias `gitversiontag = "gitversion /showvariable SemVer | git tag; git push upstream --tags"` (assuming git tag supports piped input). Worth a shot :)

If you find an alias that works well, maybe submit a pull request into the FAQ of GitVersion?
