### ISSUE TITLE
Integration with TFS/Git...

### ISSUE THREAD

**Issue by thisispaulsmith** [GitTools/GitVersion#707]
I'm having trouble getting GitVersion working with TFS/Git (on premise) using TeamCity and the Meta-runner plugin. Though I don't believe that either the plugin or GitVersion is at fault.

Our build agent it setup with a domain account with permission to access the repo. However running the meta-runner in the build with default settings result in the error when fetch from remote. (I am checking out on the agent)

`LibGit2Sharp.LibGit2SharpException: Request failed with status code: 401`

I would assume that the agent credentials would have been used. However adding a domain account that has access to the runner modifies the error to 

``LibGit2Sharp.LibGit2SharpException: Too many redirects or authentication replays``

The log does display the current git graph. Fairly new to git so would appreciate any pointers?

**Comment by software-programmer** [comment]
If you are using the runner, just make sure you have filled in the following fields

![image](https://cloud.githubusercontent.com/assets/5966776/10813275/f97e1d68-7e15-11e5-92d3-1cfcc540e3be.png)

Your repository is more than likely to be private and this doesn't use the settings from the VCS Root

**Comment by thisispaulsmith** [comment]
Tried that. That just results in the second error.
I've turned he -NoFetch flag on for now which fixes the error. It appears it's to do with how TFS handles authentication but as I can run the commands manually I need to look at the source of LibGit2Sharp.

**Comment by JakeGinnivan** [comment]
Sorry, am traveling at the moment which is why I'm not responding to much. But the remote in vso cannot authenticate, the local repo on the build agent is a full one so the correct fix is -nofetch

You can also use the dynamic repositories feature to work around the situation where build servers do not clone a proper repo (like teamcity checkout on server).

Sent from my Windows Phone
________________________________

**Comment by thisispaulsmith** [comment]
Should the Repo be a full one?
We have a new build triggered from a dev branch. Using -nofetch result in the error..

`This repository doesn't contain a branch named 'master'. Please create one. Existing branches: 'refs/heads/develop', 'refs/remotes/origin/develop'`

TeamCity only clones the branch required for build it would seem.

**Comment by JakeGinnivan** [comment]
This issue title says its for tfs, which does a full clone.
Teamcity checkout on server doesn't work properly with GitVersion, you either need checkout on agent or use dynamic repositories. The docs should cover this I think, if not then we need to fix

Sent from my Windows Phone
________________________________

**Comment by thisispaulsmith** [comment]
It is for on-premise TFS and I am doing an agent checkout, the docs are correct.
However I'm not seeing a full clone by TeamCity, only the VCS branch which triggered the build is cloned.

So if master triggers the build it's fine, if develop triggers the build then it errors as it doesn't appear that master is cloned. It's fine in subsequent builds so I have to clean the working directory recreate a new build.

**Comment by JakeGinnivan** [comment]
Sorry for dropping this thread. It has been a pretty busy month!

If you specify the username/password on the command line it may help, this is an area I need to play around with different configurations, see the errors, then document.

**Comment by JakeGinnivan** [comment]
The requirement for having a master branch has been dropped.

Are you using build vNext or xaml builds? GitVersion only does branch normalisation for vNext TFS builds. Gonna close this one out for the moment, if you *are*using build vNext and having the issues.

Either way could you create a fresh issue detailing the issue and how you are running things. Not sure if you are using teamcity or TFS and have no idea what to fix

**Comment by thisispaulsmith** [comment]
Sorry for not updating this for a while. We did work around the issue with TeamCity anyway and are migrating to git anyway. Thanks for your help
