### ISSUE TITLE
Major version bump using commit message bumped minor

### ISSUE THREAD

**Issue by dazinator** [GitTools/GitVersion#708]
Using latest NuGet release of `GitVersion.CommandLine` - as [per the docs](http://gitversion.readthedocs.org/en/latest/more-info/version-increments/) I checked in a commit message containing `+semver: breaking` - but this resulted in the version number going from `0.1.11` to `0.2.0` - i,e it bumped the minor digit instead of the major.

I haven't tried to replicate this yet, but will look into it further once I have some time.

**Comment by gep13** [comment]
Hmmm, I have just done a very crude test here, and this worked as expected, for a already released public API, i.e. 1.0.0, went to 2.0.0.  This is what I did:

```
git init
notepad readme.md
<put some stuff in there>
git add .
git commit -m "Initial Commit"
git tag 1.0.0
gitversion
<output expected 1.0.0>
<change readme.md>
git add .
git commit -m "+semver: breaking"
gitversion
<output expected 2.0.0>
```

However, when I do the following:

```
git init
notepad readme.md
<put some stuff in there>
git add .
git commit -m "Initial Commit"
gitversion
<output expected 0.1.0>
<change readme.md>
git add .
git commit -m "+semver: breaking"
gitversion
<output perhaps the not expected 0.2.0>
```

I haven't looked at the code yet, but could this be because you weren't at a major release yet?

/cc @JakeGinnivan

**Comment by dazinator** [comment]
I just went through the code with a failing test case.. and I hit this comment in the code:

```
 // cap the commit message severity to minor for alpha versions
 if (baseVersion.SemanticVersion < new SemanticVersion(1) && commitMessageIncrement > VersionField.Minor)
            {
                commitMessageIncrement = VersionField.Minor;
            }
```

So its delibrately capped! Not sure why - but perhaps this needs to be in the docs!

**Comment by dazinator** [comment]
I am trying to thing why we delibrately cap a major bump for versions < 1.0.0 - I'd love to know the reason as I suspect I am very close to learning something..

**Comment by dazinator** [comment]
here is [a branch with a failing test case](https://github.com/dazinator/GitVersion/tree/bumpissue)) that looks like this:

```
  [Test]
    public void CanUseCommitMessagesToBumpVersion()
    {
        using (var fixture = new EmptyRepositoryFixture(new Config()))
        {
            fixture.Repository.MakeACommit();
            fixture.MakeATaggedCommit("1.0.0");
            fixture.Repository.MakeACommit("+semver:minor");

            fixture.AssertFullSemver("1.1.0+1");

            fixture.Repository.MakeACommit("+semver:major");

            fixture.AssertFullSemver("2.0.0+2");

            fixture.Repository.MakeACommit("+semver:breaking");
            fixture.AssertFullSemver("3.0.0+3");
        }

    }

```

Result:

```
Result Message:	Shouldly.ShouldAssertException : 
    variables.FullSemVer
        should be
    "3.0.0+3"
        but was
    "2.0.0+3"
```

**Comment by dazinator** [comment]
Ooh maybe the space between the colon and the word breaking is importants! Although  +semver:major works without the space! I will test that once im back from lunch!

**Comment by dazinator** [comment]
- nope, space made no difference.. Gonna try and debug later.

**Comment by dazinator** [comment]
Right so there seem to be two seperate issues here.

The first thing is we deliberately bump minor instead of major for versions less than 1.0.0. If there is a good reason for this it's just a case of updating the docs.

The second thing which I'm hesitant to say is a bug..or a feature..

Doing 2 major version bumps, doesn't bump the version twice - i.e this fails:

```
 [Test]
    public void CanUseCommitMessagesToBumpVersion()
    {
        using (var fixture = new EmptyRepositoryFixture(new Config()))
        {
            fixture.Repository.MakeACommit();
            fixture.MakeATaggedCommit("1.0.0");
            fixture.Repository.MakeACommit("+semver:minor");

            fixture.AssertFullSemver("1.1.0+1");

            fixture.Repository.MakeACommit("+semver:major");
            fixture.AssertFullSemver("2.0.0+2");

            fixture.Repository.MakeACommit("+semver:breaking");
            fixture.AssertFullSemver("3.0.0+3");
        }

    }

```

Is this because GitVersion is being clever and guessing you don't really need to increment major another time if there has been no release (tag) in the interim? Not sure..

I thought originally this was evidence that "+semver:breaking" was not working, but that's not the case because when I changed the test to this - it works:

 [Test]
    public void CanUseCommitMessagesToBumpVersion()
    {
        using (var fixture = new EmptyRepositoryFixture(new Config()))
        {
            fixture.Repository.MakeACommit();
            fixture.MakeATaggedCommit("1.0.0");
            fixture.Repository.MakeACommit("+semver:minor");

            fixture.AssertFullSemver("1.1.0+1");        

            fixture.Repository.MakeACommit("+semver:breaking");
            fixture.AssertFullSemver("2.0.0+2");
        }

    }

**Comment by aprooks** [comment]
```
Is this because GitVersion is being clever and guessing you don't really need to increment major another time if there has been no release (tag) in the interim? Not sure..
```
yes it does. It was pretty confusing for me as well.

A rule of a thumb - it bumps version on merge with master. And you'll have to make sure to tag this merge as well. 

Also, when there are 2 changes per release: for example, 2 pull requests are merged to `Dev` branch, and then dev merged to master (or release version), minor would be incremented by 1 (if no breaking changes marker of some kind added).

But if you use GitHubFlow by always merging with master, it will update version on every merge.

**Comment by JakeGinnivan** [comment]
Two things.

This feature is to allow indicating a commit has particular semver properties such as breaking or minor. If multiple PR's indicate this in a single release the declarations in the commits should be rolled out to make a single SemVer change.

Then the <1.0 case is that public API is considered unstable until v1. Breaking changes before v1 do not require a major version bump. We left it to tags/next-version/release branch to push up to 1.0.0

**Comment by dazinator** [comment]
Thanks both, you've put me back on the straight and narrow!

I'll update the docs page (about bumping versions) to make this clearer and I'll send a PR for that.

I get the feeling that GitVersion is being a little too clever for my liking - when I decide i want to go from 0.X.X to 1.0.0 because I decide that with my next commit I want the version to be considered stable - it says nah, what you really want is to increment the minor version number still.. Doh! So it wants me to create release branches to do that - and I don't use those for small projects - I just use master.

Perhaps I could introduce a YAML setting: "AllowDazinatorToOverrideVersionCleverness" ? haha.

**Comment by dazinator** [comment]
I'd be up for working on a PR to add in the ability to do this via a commit message also?

Perhaps something like `+semver:stable` which would only apply in this scenario of bumping from 0.X.X to 1.0.0 ?

**Comment by JakeGinnivan** [comment]
Maybe we have another command, +semver: Stable

Or we remove the smarts, don't mind.

Sent from my Windows Phone
________________________________

**Comment by dazinator** [comment]
Did you read my comment before posting that or is this a case of great minds think alike?

**Comment by JakeGinnivan** [comment]
Haha, didn't read your message. So the latter

Sent from my Windows Phone
________________________________

**Comment by gep13** [comment]
From my point of view, I like that OOTB GitVersion is following the Semantic guidelines, and not bumping major with a breaking change until the first public API is released.  Having said that, I can see why people would want to do this.  Therefore, I would suggest that the idea of using `+semver:stable` would be the best approach.

And yes, very spooky that you both came up with that independently! :-P

**Comment by JakeGinnivan** [comment]
Tracking in #740
