### ISSUE TITLE
VSO Task does'nt allow updated assembly info to be written to a specfic file

### ISSUE THREAD

**Issue by johnkattenhorn** [GitTools/GitVersion#718]
I needed to update a specific file using VSO and found I couldn't do it.

I tried setting the option Update AssemblyInfo files to false and adding the option via Additional GitVersion.exe arguments but could'nt because the /UpdateAssemblyInfo false confuses the parser.

I decided to update the VSO task to execute from a powershell script and added an additional parameter Update Assembly File.

Ticking the Update AssemblyInfo files to true should act just as it did before. I've added a PR #717 for the PowerShell change as I figure it might help give us some more flexibility in the future.

**Comment by JakeGinnivan** [comment]
Thanks for the PR, as I said we can convert to node down the track

**Comment by JakeGinnivan** [comment]
Or maybe even maintain 2 tasks, a node and a powershell. Which seems to be what most tasks do which want xplat
