### ISSUE TITLE
Nuget upgrade from 3.1 to 3.3 leaves 3.1 targets in csproj file

### ISSUE THREAD

**Issue by knightpfhor** [GitTools/GitVersion#725]
I've just upgraded from 3.1 to 3.3 via Nuget (VS2015, Nuget package manager 3.2) and the 3.1 imports in the csproj file were left behind there which caused the following build error:

    The "BuildMetaDataPadded" parameter is not supported by the "GetVersion" task. Verify the parameter exists on the task, and it is a gettable public instance property.

Removing the 3.1 references manually solved the problem.

This is what the csproj included before the upgrade:

    <Import Project="..\packages\GitVersionTask.3.1.0\Build\portable-net+sl+win+wpa+wp\GitVersionTask.targets" Condition="Exists('..\packages\GitVersionTask.3.1.0\Build\portable-net+sl+win+wpa+wp\GitVersionTask.targets')" />
    <Target Name="EnsureNuGetPackageBuildImports" BeforeTargets="PrepareForBuild">
        <PropertyGroup>
            <ErrorText>This project references NuGet package(s) that are missing on this computer. Enable NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is {0}.</ErrorText>
        </PropertyGroup>
        <Error Condition="!Exists('..\packages\GitVersionTask.3.1.0\Build\portable-net+sl+win+wpa+wp\GitVersionTask.targets')" Text="$([System.String]::Format('$(ErrorText)', '..\packages\GitVersionTask.3.1.0\Build\portable-net+sl+win+wpa+wp\GitVersionTask.targets'))" />
    </Target>

And after the upgrade:

    <Import Project="..\packages\GitVersionTask.3.1.0\Build\portable-net+sl+win+wpa+wp\GitVersionTask.targets" Condition="Exists('..\packages\GitVersionTask.3.1.0\Build\portable-net+sl+win+wpa+wp\GitVersionTask.targets')" />
    <Target Name="EnsureNuGetPackageBuildImports" BeforeTargets="PrepareForBuild">
        <PropertyGroup>
            <ErrorText>This project references NuGet package(s) that are missing on this computer. Enable NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is {0}.</ErrorText>
        </PropertyGroup>
        <Error Condition="!Exists('..\packages\GitVersionTask.3.1.0\Build\portable-net+sl+win+wpa+wp\GitVersionTask.targets')" Text="$([System.String]::Format('$(ErrorText)', '..\packages\GitVersionTask.3.1.0\Build\portable-net+sl+win+wpa+wp\GitVersionTask.targets'))" />
        <Error Condition="!Exists('..\packages\GitVersionTask.3.3.0\Build\dotnet\GitVersionTask.targets')" Text="$([System.String]::Format('$(ErrorText)', '..\packages\GitVersionTask.3.3.0\Build\dotnet\GitVersionTask.targets'))" />
    </Target>
    <Import Project="..\packages\GitVersionTask.3.3.0\Build\dotnet\GitVersionTask.targets" Condition="Exists('..\packages\GitVersionTask.3.3.0\Build\dotnet\GitVersionTask.targets')" />

And for completeness, this is what I changed it to:

    <Target Name="EnsureNuGetPackageBuildImports" BeforeTargets="PrepareForBuild">
        <PropertyGroup>
            <ErrorText>This project references NuGet package(s) that are missing on this computer. Enable NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is {0}.</ErrorText>
        </PropertyGroup>
        <Error Condition="!Exists('..\packages\GitVersionTask.3.3.0\Build\dotnet\GitVersionTask.targets')" Text="$([System.String]::Format('$(ErrorText)', '..\packages\GitVersionTask.3.3.0\Build\dotnet\GitVersionTask.targets'))" />
    </Target>
    <Import Project="..\packages\GitVersionTask.3.3.0\Build\dotnet\GitVersionTask.targets" Condition="Exists('..\packages\GitVersionTask.3.3.0\Build\dotnet\GitVersionTask.targets')" />

**Comment by JakeGinnivan** [comment]
@SimonCropp do you know how to sort this, I haven't done much with target files and NuGet.

**Comment by SimonCropp** [comment]
That is fully controlled by nuget. So u will have to raise a bug with them 

Sorry

**Comment by dazinator** [comment]
Just a guess in a vain attemp to be helpful, but perhaps NuGet didn't upgrade the targets file between gitversion 3.1.0 and 3.3.0 because the targets file seems to change its location in the nuget package.. in 3.1.0 its referenced from `portable-net+sl+win+wpa+wp\GitVersionTask.targets` and in 3.3.0 it's referenced from `dotnet\GitVersionTask.targets`.

Did you change your project type by any chance from a PCL or something? Im struggling to think why the targets file would change location - either the nuget packaging logic changed for gitversion, or your project type changed?

**Comment by JakeGinnivan** [comment]
@dazinator maybe.. 

Not sure how to action this issue. Closing :( Hopefully it doesn't happen again
