### ISSUE TITLE
GitVersion.CommandLine how to control assembly version format?

### ISSUE THREAD

**Issue by dazinator** [GitTools/GitVersion#726]
In prior versions of GitVersion command line, you could pass in a 'assemblyversionformat' argument.

This looks like it has now been dropped, requiring you to create a config yaml file instead.

Was this dropped intentionally? Previously I could get away without the step of adding a config yaml, and it's a shame now I can't due to this one config value! :)

**Comment by gep13** [comment]
Yes, I believe the decision was taken to move all configuration values to the yaml file, as per the comment here:

https://github.com/GitTools/GitVersion/blob/039a43b092134c6a42902fc162fcb4cbc1265c14/src/GitVersionExe/ArgumentParser.cs#L178

So unfortunately for you, a little bit of extra would will be required :-(

**Comment by dazinator** [comment]
Haha no worries. If that's the way things have to be I can get over losing 10 seconds to create a config file. /init is actually pretty nice to use. Closing.

**Comment by gep13** [comment]
:+1:
