### ISSUE TITLE
Need variable with just pre-release number

### ISSUE THREAD

**Issue by heaths** [GitTools/GitVersion#729]
In some places a dotted quad is necessary, such as 1.2.3.4. Since GitVersion only cares about 1.2.3, it would be great to have a variable that had all 4 numbers or even just (or both?) the incremental commit delta (i.e. 4 in this example) so we can generate dotted quads as needed.

**Comment by heaths** [comment]
To clarify, I know that `BuildMetaData` exists and does this depending on, it seems, one's `assembly-versioning-scheme` but having a variable that is just the numeric portion regardless of settings provides maximum flexibility.

**Comment by JakeGinnivan** [comment]
Did you want to submit a PR with this extra variable?

**Comment by JakeGinnivan** [comment]
Created a PR which combines this and another issue which was the other part of the pre-release tag. PR welcome :)
