### ISSUE TITLE
Make padding version smarter

### ISSUE THREAD

**Issue by JakeGinnivan** [GitTools/GitVersion#732]
We can actually make the padded version smarter. For instance

```
2.0.0-beta1
2.0.0-beta010
2.0.0-beta00100
```

This will sort numerically for > 10 or even >100 beta releases and makes it much nicer for the majority case which is <10 beta releases. We could also introduce a setting (which could be the default) which is 'smart'. i.e `legacy-semver-padding: smart`

Thoughts?

**Comment by asbjornu** [comment]
I don't quite understand. `beta1` will constrain it to 9 beta releases, as `beta10` will sort before `beta2`.

**Comment by JakeGinnivan** [comment]
What about padding with 9's :p

```
var arrr = new[] {
"2.0.0-beta1",
"2.0.0-beta2",
"2.0.0-beta9",
"2.0.0-beta91",
"2.0.0-beta92",
"2.0.0-beta99",
"2.0.0-beta991",
};

arrr.OrderBy(a => a).Dump();
```

Result:
```
2.0.0-beta1 
2.0.0-beta2 
2.0.0-beta9 
2.0.0-beta91 
2.0.0-beta92 
2.0.0-beta99 
2.0.0-beta991 
```

**Comment by robdmoore** [comment]
Is beta1 sorted before beta010? If so then that's very clever.

I'll assume padding with 9's is a joke :p

**Comment by JakeGinnivan** [comment]
Not really. My initial suggestion wont sort properly. And this change prioritises the majority case of betas only from 1-9. If you go over that we have a workaround in place which is to pad with 9s to get proper sorting :P

**Comment by dazinator** [comment]
How about..

```

2.0.0-beta1
2.0.0-beta9
2.0.0-beta9.1
2.0.0-beta9.9
2.0.0-beta9.9.1


```
Etc..

**Comment by dazinator** [comment]
Just adding another possibility to the table, cycle through letters of the alphabet! (Then numbers?) That way you get 36 releases before needing an extra "pad"

```
2.0.0-beta.a
2.0.0-beta.z
2.0.0-beta.0
2.0.0-beta.9
2.0.0-beta.9.a
2.0.0-beta.9.z
2.0.0-beta.9.a
2.0.0-beta.9.z
```
Etc

**Comment by JakeGinnivan** [comment]
NuGet doesn't support the .'s :(

**Comment by JakeGinnivan** [comment]
Gonna close this, don't care for the moment

**Comment by dazinator** [comment]
> NuGet doesn't support the .'s :(

Ah.. laaaame.. 
Perhaps dashes instead of dots then.

> Gonna close this, don't care for the moment

+1
