### ISSUE TITLE
Timestamp and/or filter on Personal Goals

### ISSUE THREAD

**Issue by johnfanguy** [GitTools/GitVersion#735]
When you create a new Personal Goal for someone, there's some level of delay before you see it and can select it.  If I set the start date of the new Personal Goal to yesterday, it's visible immediately. So I'm guessing either the filtering function in the drop down and/or the effective date/time being saved is the issue. Basically, I think the "start date" for a Personal Goal should default to the time of 12:00:01am.

**Comment by JakeGinnivan** [comment]
Wrong project?

**Comment by johnfanguy** [comment]
Sorry!


-John 

301-346-6749 cell

**Comment by gep13** [comment]
>@johnfanguy said...
Sorry!

Not a problem at all :+1:
