### ISSUE TITLE
Add support for updating version in VC++ resource file

### ISSUE THREAD

**Issue by Gambero81** [GitTools/GitVersion#736]
Hello, It would be nice to add support for updating visual c++ resource file with the calculated version by git version, as already done for c# assemblyinfo.cs
Thanks

**Comment by JakeGinnivan** [comment]
Are you using the .exe or the msbuild Task?

Does nuget and visual c++ projects support .targets files which we can hook the build pipeline or would this be the .exe only?

**Comment by JakeGinnivan** [comment]
Happy to receive a PR for this, but not going to mark as up for grabs as we have a heap of other up for grabs issues which I see as higher priority.

Going to close out this issue otherwise I think it will just sit here.
