### ISSUE TITLE
Commit message +semver:stable to bump to v1

### ISSUE THREAD

**Issue by JakeGinnivan** [GitTools/GitVersion#740]
See discussion in #708 for reasoning.

In short, if you are <1.0.0, `+semver: breaking` will only bump minor. This is intended behaviour as you have not declared your public API yet. Introduction of the `stable` keyboard will allow a v1 bump via commit messages.

**Comment by voslucas** [comment]
I have a simple project setup with Gitversion/Semver which i want to promote (being stable) to 1.0.0, but none of the +semver: commit messages seems to work (as described in 708). And as small project, no release branches. I see this is still an open request. What's the recommended workaround? Just make the tag by hand?

**Comment by asbjornu** [comment]
@voslucas, I'm not a user of the `+semver:` functionality myself, so I'm not sure how it's meant to be used, but as this issue is still open, I assume `git tag 1.0` will have to do for now.

**Comment by asbjornu** [comment]
As no one has provided a PR to fix this, I think we can conclude that `git tag 1.0` is a sufficient workaround. Closing.
