### ISSUE TITLE
Prerelease number is not scoped to prerelease label in continuous delivery

### ISSUE THREAD

**Issue by qetza** [GitTools/GitVersion#756]
Hi,

When i'm in continuous delivery mode and i have the following commit tree:

- commit 1
- commit 2 <- tag "0.1.0-test.1"
- commit 3 <- branch "feature/test" & "master"

With the tag configuration "useBranchName" for feature branches and "beta" for master i would expect that:

- calling GitVersion on "feature/test" would return "0.1.0-test.2" because there is a tag "0.1.0-test.1" in the parents
- calling GitVersion on "master" would return "0.1.0-beta.1" because it's the first version with the beta label.

Instead the call on "master" returns "0.1.0-beta.2" because the number computation takes into account all tags.

I'll push later today a pull request with a unit test for this scenario and a potential fix.

**Comment by qetza** [comment]
Test and code are in pull request #779

**Comment by JakeGinnivan** [comment]
Nice fix!

**Comment by asbjornu** [comment]
I assume this can be closed, then? :smile:

**Comment by qetza** [comment]
yes it can :smile:
