### ISSUE TITLE
How to use commits as Version numbers ?

### ISSUE THREAD

**Issue by oSilas** [GitTools/GitVersion#761]
like V5.16.2.5819

**Comment by oSilas** [comment]
5819  is commits number ! 
![Uploading 捕获.PNG…]()

**Comment by oSilas** [comment]
![default](https://cloud.githubusercontent.com/assets/3445167/12645225/801ba1ee-c603-11e5-97e7-608117e276f8.PNG)

**Comment by asbjornu** [comment]
@oSilas Just to be sure I've understood you correctly, what you're asking is how you can get the version number `1512` for a repository with 1.512 commits in it? From what I can read in [the documentation](http://gitversion.readthedocs.org/en/latest/), this is currently not a [variable](http://gitversion.readthedocs.org/en/latest/more-info/variables/) exposed by GitVersion. Should we consider this a feature request to have such a variable added?

**Comment by JakeGinnivan** [comment]
I don't think this idea fits GitVersion. We are trying to use git workflows to produce semver compatible version numbers.

This is also really easy to achieve outside of GitVersion, just run `git rev-list --count HEAD` to get the commit count of HEAD
