### ISSUE TITLE
Flakey data types of returned JSON data

### ISSUE THREAD

**Issue by dittert** [GitTools/GitVersion#762]
The data type in JSON seems to depend on it's value. Whenever a value is zero, it is returned as "0". Otherwise it is returned as number.

Example:
``` 
{
    "Major":"0",
    "Minor":1,
    "Patch":"0"
    ...
} 
```
This affects at least **Major**, **Minor**, **Patch**, **BuildMetaData**

This is inconvenient if you're using a JSON parser. My code (using simple-json) fails because ```"0"``` is considered to be a string and not a number. I can handle this in post processing but it would make things easier if the data type was consistent. 

This issue was reported for GitVersion 3.0.0.

**Comment by JakeGinnivan** [comment]
3.4 will be out shortly with a heap of fixes including this one. Thanks for reporting!
