### ISSUE TITLE
Allow relative path parameter

### ISSUE THREAD

**Issue by Gambero81** [GitTools/GitVersion#770]
Hi, it would be nice to allow gitversion.exe to get a relative path as input parameter for git repository 
( ex. gitversion.exe ..\ )

it's seem now is not possible.. or i make something wrong?
Thanks

**Comment by gep13** [comment]
@Gambero81 can you confirm what version of GitVersion you are using?

I just tested passing a relative path into GitVersion 3.4.0 and it worked as expected.

**Comment by asbjornu** [comment]
What path is it you want to be relative? If it's the log file, it was fixed in #678, which was included in [v3.3.0](../releases/tag/v3.3.0).

**Comment by pascalberger** [comment]
Closed since no response from OP for a while. If it still is an issue please reopen and add the requested information.
