### ISSUE TITLE
NuGet package GitVersion does not have dependencies, but it should

### ISSUE THREAD

**Issue by maximpashuk** [GitTools/GitVersion#772]
If you tak a look to
https://www.nuget.org/packages/GitVersion/3.4.0

you will see that "This package has no dependencies"

But actually it depends from LibGitSharp and YamlDotNet packages.
So you should explicitly add these packages at compatible versions.

Please check nuget package generating process.

In contrast, GitVersion.CommandLine package does not have any dependencies and this is cool.
But I think GitVersion package should reference to third-party dependencies.

**Comment by JakeGinnivan** [comment]
Agreed, the nuget package has not been a primary thing but it would be good to fix this issue.

**Comment by dazinator** [comment]
Closing this, its old, we manage nuspec dependencies better now and there are planned package id changes tracked by #1509
