### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by cloudcello** [GitTools/GitVersion#773]
GitVersion/docs/more-info/version-increments.md

> ### Version Incrementing
> Because GitVersion works with a number of workflows the way it does it's version incrementing may work perfectly for you, or it may cause you issues.

typo: "it's" --> replace with --> "its" (without quotes)

**Comment by gep13** [comment]
@cloudcello are you in a position to submit a pull request for this?  We would happily accept your contribution.

**Comment by pascalberger** [comment]
@gep13 Sorry, just saw your post now. Thought that I just might fix it directly :)

**Comment by cloudcello** [comment]
I thought that creating a fork for just one typo would be too much :)

**Comment by asbjornu** [comment]
@cloudcello It's actually really easy to fork and submit a PR when you edit files directly on GitHub. Just find [the file you want to fix](/GitTools/GitVersion/blob/master/docs/more-info/version-increments.md), click the edit pencil in the upper right corner and then GitHub will take you through the motions of forking and submitting a PR without writing a single git command. Easy peasy! :)

**Comment by cloudcello** [comment]
Ok asbjornu. Next time I'll fork it. I already a couple of repos where I did just that :) But I can always fit one more in my account.
