### ISSUE TITLE
GitVersion for Bamboo - Unable to parse multiple command-line arguments

### ISSUE THREAD

**Issue by TAGC** [GitTools/GitVersion#778]
This is an issue with your GitVersion for Bamboo plugin but I'm unable to sign up an account with your JIRA issue tracker (it keeps returning a 504 error) so I'm posting here instead.

I have a build where I include a GitVersion task:

![](http://i.imgur.com/HT7BRZP.png)

I consistently get the following error:

```
simple	05-Feb-2016 09:05:07	Executing C:\ProgramData\Chocolatey\Bin\GitVersion.exe /output buildserver /updateassemblyinfo
error	05-Feb-2016 09:05:08	Error executing GitVersion
Failed to parse arguments: /output buildserver /updateassemblyinfo

Could not parse command line parameter '/output buildserver /updateassemblyinfo'.
```

It doesn't seem to be splitting arguments by spaces.

If I run the GitVersion executable with these arguments directly as a Command task in Bamboo, it works fine. However, I don't know if this allows me to store the version information as Bamboo build variables and subsequently access them for my deployment release versioning. Is there a way I can work around this?

**Comment by JakeGinnivan** [comment]
@carolynvs any ideas?

**Comment by carolynvs** [comment]
Yeah, I'm not splitting the args by spaces. I'll fix that and reply back when an updated version to the marketplace is ready.

Thanks!

**Comment by carolynvs** [comment]
I've pushed GitVersion for Bamboo v1.2.2 to the Atlassian marketplace. This release fixes parsing of multiple arguments to gitversion.exe. 

I noticed from your example that you were passing `/output buildserver`, however the plugin relies on parsing json output, so using buildserver will cause the task to fail. To update your AssemblyInfo.cs files in addition to capturing the version in Bamboo, just pass `/updateassemblyinfo`.

If you run into any other troubles with the plugin, you can open an issue in the plugin's repository: https://bitbucket.org/carolynvs/gitversion-bamboo.

**Comment by TAGC** [comment]
Cheers.

> I noticed from your example that you were passing /output buildserver, however the plugin relies on parsing json output, so using buildserver will cause the task to fail. 

I was doing this originally (specifically, omitting the /output argument so it defaulted to JSON) and no versioning-related metadata was logged after my builds, so I thought I had to change it.

**Comment by carolynvs** [comment]
@TAGC If the Bamboo task isn't working for you, I'd appreciate a [bug report](https://bitbucket.org/carolynvs/gitversion-bamboo/issues?status=new&status=open) and any details you may have so I can reproduce. :smile:

**Comment by TAGC** [comment]
Sure. I'll see if I can submit a report tomorrow when I get into work.

**Comment by pascalberger** [comment]
@TAGC Has this issue been resolved and can be closed?

**Comment by TAGC** [comment]
Oh hey, sorry for not getting back. Yeah I'm not having any problems with the build now so this issue can be closed.
