### ISSUE TITLE
assembly-informational-format line in GitVersionConfig.yaml leads to crashes

### ISSUE THREAD

**Issue by The-E** [GitTools/GitVersion#780]
The following GitVersionConfig.yaml leads to a crash:

assembly-versioning-scheme: MajorMinorPatch
assembly-informational-format: {FullSemVer}
mode: ContinuousDelivery
next-version: 5.3.0
branches: {}

Stacktrace: 

ERROR [02/08/16 15:22:33:21] An unexpected error occurred:
YamlDotNet.Core.YamlException: (Line: 2, Col: 32, Idx: 76) - (Line: 2, Col: 32, Idx: 76): Exception during deserialization ---> System.InvalidOperationException: Failed to create an instance of type 'System.String'. ---> System.MissingMethodException: Für dieses Objekt wurde kein parameterloser Konstruktor definiert.
   bei System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   bei System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   bei System.Activator.CreateInstance(Type type, Boolean nonPublic)
   bei System.Activator.CreateInstance(Type type)
   bei YamlDotNet.Serialization.ObjectFactories.DefaultObjectFactory.Create(Type type) in c:\projects\yamldotnet\YamlDotNet\Serialization\ObjectFactories\DefaultObjectFactory.cs:Zeile 53.
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei YamlDotNet.Serialization.ObjectFactories.DefaultObjectFactory.Create(Type type) in c:\projects\yamldotnet\YamlDotNet\Serialization\ObjectFactories\DefaultObjectFactory.cs:Zeile 58.
   bei YamlDotNet.Serialization.NodeDeserializers.ObjectNodeDeserializer.YamlDotNet.Serialization.INodeDeserializer.Deserialize(EventReader reader, Type expectedType, Func`3 nestedObjectDeserializer, Object& value) in c:\projects\yamldotnet\YamlDotNet\Serialization\NodeDeserializers\ObjectNodeDeserializer.cs:Zeile 54.
   bei YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(EventReader reader, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer) in c:\projects\yamldotnet\YamlDotNet\Serialization\ValueDeserializers\NodeValueDeserializer.cs:Zeile 63.
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(EventReader reader, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer) in c:\projects\yamldotnet\YamlDotNet\Serialization\ValueDeserializers\NodeValueDeserializer.cs:Zeile 75.
   bei YamlDotNet.Serialization.ValueDeserializers.AliasValueDeserializer.DeserializeValue(EventReader reader, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer) in c:\projects\yamldotnet\YamlDotNet\Serialization\ValueDeserializers\AliasValueDeserializer.cs:Zeile 134.
   bei YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.<>c__DisplayClass2.<DeserializeValue>b__0(EventReader r, Type t) in c:\projects\yamldotnet\YamlDotNet\Serialization\ValueDeserializers\NodeValueDeserializer.cs:Zeile 63.
   bei YamlDotNet.Serialization.NodeDeserializers.ObjectNodeDeserializer.YamlDotNet.Serialization.INodeDeserializer.Deserialize(EventReader reader, Type expectedType, Func`3 nestedObjectDeserializer, Object& value) in c:\projects\yamldotnet\YamlDotNet\Serialization\NodeDeserializers\ObjectNodeDeserializer.cs:Zeile 65.
   bei YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(EventReader reader, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer) in c:\projects\yamldotnet\YamlDotNet\Serialization\ValueDeserializers\NodeValueDeserializer.cs:Zeile 71.
   bei YamlDotNet.Serialization.ValueDeserializers.AliasValueDeserializer.DeserializeValue(EventReader reader, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer) in c:\projects\yamldotnet\YamlDotNet\Serialization\ValueDeserializers\AliasValueDeserializer.cs:Zeile 134.
   bei YamlDotNet.Serialization.Deserializer.Deserialize(EventReader reader, Type type) in c:\projects\yamldotnet\YamlDotNet\Serialization\Deserializer.cs:Zeile 191.
   bei YamlDotNet.Serialization.Deserializer.Deserialize[T](TextReader input) in c:\projects\yamldotnet\YamlDotNet\Serialization\Deserializer.cs:Zeile 141.
   bei GitVersion.ConfigSerialiser.Read(TextReader reader) in C:\PrimeFact Dev\git\Source\Tools\GitVersion\src\GitVersionCore\Configuration\ConfigSerialiser.cs:Zeile 12.
   bei GitVersion.ConfigurationProvider.ReadConfig(String workingDirectory, IFileSystem fileSystem) in C:\PrimeFact Dev\git\Source\Tools\GitVersion\src\GitVersionCore\Configuration\ConfigurationProvider.cs:Zeile 129.
   bei GitVersion.ConfigurationProvider.Provide(String workingDirectory, IFileSystem fileSystem, Boolean applyDefaults) in C:\PrimeFact Dev\git\Source\Tools\GitVersion\src\GitVersionCore\Configuration\ConfigurationProvider.cs:Zeile 16.
   bei GitVersion.ConfigurationProvider.GetEffectiveConfigAsString(String gitDirectory, IFileSystem fileSystem) in C:\PrimeFact Dev\git\Source\Tools\GitVersion\src\GitVersionCore\Configuration\ConfigurationProvider.cs:Zeile 137.
   bei GitVersion.Program.VerifyArgumentsAndRun()

**Comment by asbjornu** [comment]
@The-E You're missing quotes (`'`) around `{FullSemVer}`. Your config should thus look like this:

```yaml
assembly-versioning-scheme: MajorMinorPatch
assembly-informational-format: '{FullSemVer}'
mode: ContinuousDelivery
next-version: 5.3.0
branches: {}
```

**Comment by The-E** [comment]
Thanks, that works.
