### ISSUE TITLE
NuGetVersionV2 doesn't generate valid version number

### ISSUE THREAD

**Issue by gep13** [GitTools/GitVersion#781]
...when using certain feature branch names.

I have created a sample repository to demonstrate this issue, you can find it here:

https://github.com/gep13/GitVersionTest

**Steps to reproduce**
1. Clone the repo
2. `cd` into repo
3. Run `.\build.ps1`
4. Verify that build works correctly
5. Do `git checkout feature/Gh-567` and run `.\build.ps1` and verify that build works correctly
6. Do `git checkout feature/567` and run `.\build.ps1` and verify that build does not work correctly

![image](https://cloud.githubusercontent.com/assets/1271146/12897877/f5a176cc-cea1-11e5-8e53-552707596f1c.png)

The difference between the two feature branches in this repo is that one has a prefix that contains letters, but the other doesn't.

If we are going to have a variable called NuGetVersionV2, then we are asserting that this will be a valid NuGet Version number of NuGet version 2.x.  If this is not the case, then we should not include a version number for this property.

**Comment by tertork** [comment]
Having the same problem:

'1.3.0-3cd5qnmw-server-0122' is not a valid version string.

Works ok for most branches, but when counter in metadata dont have letters in front of it (but -) it fails. I.e. 1.3.0-3cd5qnmw-server0122 works.

**Comment by pascalberger** [comment]
This issue was fixed in NuGet 3.5.0-rc1: https://github.com/NuGet/Home/issues/1743#issuecomment-241865097

But since the variable is explicitely for NuGet version 2.x use, IMHO we should still fix this in GitVersion.

**Comment by JakeGinnivan** [comment]
Completely agree, NuGetv2 should fix this absolutely

**Comment by asbjornu** [comment]
As @nshenoy points out in https://github.com/GitTools/GitVersion/issues/1067#issuecomment-258104776, NuGet 3.5 is RTM and solves this problem. Doesn't that mean this issue can be closed?

**Comment by pascalberger** [comment]
@asbjornu See discussion above. The consensus was to have this fixed in GitVersion since variable is explicitely for use with NuGet version 2.x.

**Comment by asbjornu** [comment]
@pascalberger: I see.

**Comment by nshenoy** [comment]
Also in #1067 @aarondandy pointed out the following rules for a proper NuGet 2.x prerelease tag:
