### ISSUE TITLE
Basic question on where Max/MinVer comes from

### ISSUE THREAD

**Issue by koraybalci** [GitTools/GitVersion#789]
I installed using nuget and when I build my project, my file version becomes: `0.1.0+261.Branch.master.Sha.0e4971d877b6f7blablabla`

My question is, where do I set the `0.1.0` part? Where is it retrieved from?

Should be a very simple answer, but I couldn't find it in any of the docs.. 

PS: I haven't touched GitVersionTask.targets file and not sure if I should..

**Comment by gep13** [comment]
`0.1.0` is the base version number that is used by GitVersion.  This is semantically, the first version number that you would be working towards.  After that, once you have tagged your repository with a released version number, GitVersion will start using the latest tag as the base version number, and continue calculating from there.

Sorry to hear that the documentation did provide you any guidance in this area, sounds like this is an area that we need to work on.  Can you point to a place in the documentation where you think it would be a good place to add this information?

**Comment by asbjornu** [comment]
@koraybalci You don't need to touch `GitVersionTask.targets`, but if you want to configure what version number the next build should have, or how the version number is minted, please have a look at [how to configure GitVersion](http://gitversion.readthedocs.org/en/latest/configuration/). If you have any questions to what's described there or think anything is missing, please let us know! :)

**Comment by koraybalci** [comment]
Thanks for the answers, it's all clear now. 

To be honest, after installing with nuget, it took me a while to realize it was actually already working. I was probably expecting to configure more. You might emphasize in the documentation, it is just so transparent! 

I was already reading about configuring (the link @asbjornu provided as well)  but I figured nuget version only comes with the dll, no command line. (I am using `GitVersionTask` by the way) 

So, briefly, I suppose some additional explanation at http://gitversion.readthedocs.org/en/latest/usage/msbuild-task/ or a general walkthrough somewhere would be beneficial. Especially for people who needs simple, basic use cases as just versioning the project dll to show users in test/prod etc.

Anyhow, thx for the great lib and friendly explanation. I will close the issue now.

**Comment by asbjornu** [comment]
@koraybalci Please have a look at #792. I hope it helps clarify things a bit. If not, I'd love input to how it can be improved further. Thanks!

**Comment by koraybalci** [comment]
looks great!
