### ISSUE TITLE
Change some output to Verbose

### ISSUE THREAD

**Issue by gep13** [GitTools/GitVersion#797]
I recently added GitVersion to the Cake build process, and it is working fine, however, the output is very "chatty".  It starts here:

https://ci.appveyor.com/project/cakebuild/cake/build/0.9.0-PullRequest.717+71.build.1562#L55

and ends here:

https://ci.appveyor.com/project/cakebuild/cake/build/0.9.0-PullRequest.717+71.build.1562#L729

Over 700 lines in the build log.  Should we move some of this out into verbose log instead of in the default?

**Comment by JakeGinnivan** [comment]
That would be handy, i've often thought the same thing.
