### ISSUE TITLE
GitVersion need ability to use default credentials (for TFS on-premise)

### ISSUE THREAD

**Issue by maximpashuk** [GitTools/GitVersion#799]
GitVersion 3.4 has only /u and /p options to set up username and password to fetch\push from remote.

These options maps to `GitVersion.Authentication` class, which later maps exactly to `LibGit2Sharp.UsernamePasswordCredentials` class.

But for TFS onpremise has only NTLM auth enabled by default, so `LibGit2Sharp.DefaultCredentials` should be used instead.

So set /u and /p is useless for TFS onpremise, since it not support basic auth by default.

Probably GitVersion need another switch option to use default credentials OR maybe default credentials should be used by default and userpasswordcredentials used if /u and /p are set.

**Comment by pascalberger** [comment]
I've marked this as up for grabs, feel free to submit a pull request
