### ISSUE TITLE
How to read this graph ?

### ISSUE THREAD

**Issue by dcorriveau-omniscient** [GitTools/GitVersion#804]
![gitflow](https://cloud.githubusercontent.com/assets/11891420/13496877/9d57f658-e120-11e5-9567-1b6e7419a4ae.png)
I was wondering what is the meaning of the arrows in the graph ? From what I've seen in other GitFlow graphs, the arrows usually point in the direction the project is going to (and left to right or top to bottom), not the other way around. So the graph and the actual result (text below) seemed to contradict each other in terms of order. Maybe I'm not understanding the meaning of the arrows ? Do they mean "it comes from there" ?

**Comment by asbjornu** [comment]
@dcorriveau-omniscient It's quite common in graph theory to have the arrow point in the direction of the reference, that is from the child to its parent. It's like this in class diagrams in UML as well. In Git, each commit has one or more parents and it is the child that references those parents, not the other way around.

**Comment by dcorriveau-omniscient** [comment]
I see, I thought it was more like a Flow Graph, but in the context of a UML graph it does make more sense. Thanks for the explanation.
