### ISSUE TITLE
GitVersion_NoFetchEnabled environment variable

### ISSUE THREAD

**Issue by gregbty** [GitTools/GitVersion#807]
I am using GitVersionTask for my projects and I am attempting to build on AppVeyor, however I see the following line:

`Could not determine assembly version: Unsupported URL protocol`

I read that the issue can be resolved  by using the nofetch option. I tried using the environment variable `GitVersion_NoFetchEnabled` but the MSBuild target does not seem to pick it up. Is there no way to specify this option globally via an environment variable, or am I force to do this at the project level?

**Comment by gep13** [comment]
@gregbty what Version Control system are you using?  Does it require authentication?

**Comment by gregbty** [comment]
I am using Git over SSH and yes it is a private repository. I do not think I have the ability to use HTTPS on the build server. Using ```gitversion /nofetch /output buildserver``` via the command line works.

**Comment by gep13** [comment]
Ah, you are using SSH...

I think that is why you are running into issues.  Please see this issue: https://github.com/GitTools/GitVersion/issues/436

**Comment by gregbty** [comment]
Well I saw that issue before. If I set the ```GitVersion_NoFetchEnabled``` property within the MS Build project itself, I do not run into this issue (even using SSH). However, if I set this via an environment variable ```set GitVersion_NoFetchEnabled```, GitVersionTask does not seem to pick it up. Is that the expected behavior? Is the only way to specify the flag is in the MS Build project?

**Comment by gep13** [comment]
Ah, I see what you are saying...

On that one I am not sure, as I don't use the GitVersionTask.

@JakeGinnivan @pascalberger @SimonCropp can any of you provide any input on this one?  Thanks!

**Comment by asbjornu** [comment]
`NoFetch` was added to GitVersionTask in #653. Closing, as that was merged ages ago.
