### ISSUE TITLE
Commit count resets to 0 when merge detected on branches (only the first merge)

### ISSUE THREAD

**Issue by taborda** [GitTools/GitVersion#814]
I'm still experiencing the problem explained in issue #700 

Commit count is reset to 0 when a merge is detected on a branch with ContinuousDeployment.
Apparently this problem only happens in the first merge. 

If it helps, here is the log:
[gitversion_branch_merge_resets_commit_count.txt](https://github.com/GitTools/GitVersion/files/174052/gitversion_branch_merge_resets_commit_count.txt)

In this example there was a merge in the release/1.4 branch with the message:
Merge branch 'release/1.4' of https://git-srv.local/taborda/test into release/1.4
The commit count was reset after this.
After that, it is not resetting the commit count on each merge. But still, it is counting from the last merge, that is when it was reset.

The branch release/1.4 is a branch from 9217f49575afd28dddd792137ad101f89166dd14
GitVersion selected a66691e3e173ae07a1cb086e37132cb1b9d2a0d5 as the source

**Comment by taborda** [comment]
I've created a pull request with the test provided by @msnelling on issue #700 

Just changed the expected FullSemver to be 2.0.0-beta.3 instead of 2.0.0-beta.2

**Comment by fokkoru** [comment]
I have the same issue, I have release and develop breach. When I merge release to develop it dropped count of commits, second merge did not change it.

**Comment by JakeGinnivan** [comment]
#832 fixes this. I will post in that PR if that will be released with the next release or it will be in 4.0.0-beta

**Comment by pkiers** [comment]
Hello,

I've got something exciting for you, you'll definitely love it, take a look <http://discover.sharetheroaddoc.com/e2ltx>

Yours truly, p.kiers@home.nl

**Comment by aryak93** [comment]
> #832 fixes this. I will post in that PR if that will be released with the next release or it will be in 4.0.0-beta

@JakeGinnivan Unfortunately, we're still facing this in https://github.com/GitTools/GitVersion/issues/1992 and we're using 4.0.1. Is there any other fix available for this in the subsequent releases?

**Comment by asbjornu** [comment]
@aryak93, can you please try with the latest release of version 5 of GitVersion?

**Comment by aryak93** [comment]
Thanks @asbjornu. I'll definitely give it a try. Can you please also take a look at #1992 ? It'd be of great help.
