### ISSUE TITLE
[Question] - Tmp directory for remote repo's - why?

### ISSUE THREAD

**Issue by dazinator** [GitTools/GitVersion#822]
I was just wondering what the reasons gitversion clones remote repositories to the %tmp% directory by default? Would it not be better to just default to using the working directory (which is a command line mandatory argument) - and then if the additional argument is provided to specify a directory to clone to, then use that argument to override the working dir?

The only reason I suggest this is because when using gitversion with a remote repo it's not immediately obvious where the repo has been put, and as the first arg is the working directory, I would have assumed it would end up there :)

**Comment by JakeGinnivan** [comment]
Say you have clean sources on your build server, we would re-clone each time because the clone would get deleted each checkout making things super slow.

We needed somewhere outside the working directory but still consistent to put the clone so it can be accessed across builds

**Comment by dazinator** [comment]
Ahh ok that makes sense. If this feature is purely for build servers that use clean sources, how about we still default to a location relative to the working directory, but an allow an argument to be passed in to specify the location where repos should be placed, and output a warning when in build server mode if that argument is not specified, saying that if using clean sources consider specifying a repo location so that a fresh clone isn't obtained each time.

Arguably, if you tick "clean sources" - it means you want to ensure you get a fresh copy of "everything" i.e you don't want any artifacts hanging around - so the usage of the temp dir in this scenario seems to be bypassing that intent under the guise of an optimisation?
