### ISSUE TITLE
Support builing tagged commits with deatched HEAD

### ISSUE THREAD

**Issue by ulrichb** [GitTools/GitVersion#825]
It would be nice if we could checkout a _tagged_ version, and get the same version numbers in GitVersion as I would get on the "master" branch (or some configured "fallback branch name for detached HEAD") + maybe a warning in the build log.

_Use case:_ A project library maintainer (or some developer which uses the library) wants to analyze an issue in a specific, earlier released version. Therefore she/he wants to checkout and build exactly the same (assembly) version (potentially with local modifications).

**Comment by JakeGinnivan** [comment]
If the commit is **tagged**, it should work. GitVersion should just pick up the tagged version and not do any version calculation.

For non-tagged detached head, this is not really possible as you say we don't know the branch config to use, and if we have a fallback then you will likely get a different version anyways.

**Comment by pkiers** [comment]
Hey,

Just take a look at these crazy stuff! It's something beyond my imagination, take a look here <http://develop.duyiwuer.com/e2srkd>

p.kiers@home.nl

**Comment by dennisdoomen** [comment]
Apparently this doesn't work as I expected. Just clone `https://github.com/dennisdoomen/fluentassertions`, then run `git checkout -f 4.6.3` and then `lib\Gitversion.exe`. It won't be able to calculate the version, even if you update GitVersion to 3.6. The same happens on our internal code-base (which I can't disclose obviously).

**Comment by asbjornu** [comment]
I'm pretty sure this works now and has been for a while. Can you please test and submit a PR with a failing test if this is still a problem?
