### ISSUE TITLE
Request: Optionally pass tag-prefix on command line

### ISSUE THREAD

**Issue by labmonkey42** [GitTools/GitVersion#826]
We have a number of repositories with multiple output projects in each repository.  Moving away from this repository structure would be a major effort, and tbh, there are senior (old school?) team members which I'm certain would vehemently resist this kind of repository restructuring.

In many cases we want a version history per-project, rather than that of the whole repo (e.g. Foo.Logging and Foo.Data are in the same repo but may not necessarily have the same version semantics per-build).  To that end, it seems to me that we could supply the project names as tag-prefixes.  However, unless I have misunderstood the documentation, tag-prefix has to be set in GitVersionConfig.yaml.

Therefore, I would like to request an implementation of one or both of the following:
1) (preferred) Support passing tag-prefix as a command line parameter, so that our CI builds can specifiy which project's version tree we're calculating. e.g. --tag-prefix "Foo.Logging-"
2) (less preferred) Some kind of GitVersionConfig.Foo.yaml override such that we can specify different config information per-project, but inherit from the primary GitVersionConfig.yaml, and pass as a command line parameter which project config to use.

**Comment by labmonkey42** [comment]
No sooner did I submit this request before it occurred to me that I could add a step to my CI build configuration which would modify GitVersionConfig.yaml to set tag-prefix before running the GitVersion step.

This seems like a hack, but if this feature request is rejected at least I have something to try.

**Comment by JakeGinnivan** [comment]
This is actually not a bad idea. It never occurred to me to approach the problem using tag prefixes. Happy to receive a PR.
