### ISSUE TITLE
Difference in determining the version between 2.0.1 and 3.4.1

### ISSUE THREAD

**Issue by danielmarbach** [GitTools/GitVersion#828]
We recently switched from 2.0.1 to 3.4.1. On the repo https://github.com/Particular/NServiceBus.SqlServer we got the following version: `3.0.0`. When we upgraded to 3.4.1 we got the following version `3.1.0`. The offending PR is the following:

https://github.com/Particular/NServiceBus.SqlServer/commit/c382841326b4f52aaf693b214f6427efe4394e6b

Any ideas how to resolve this without needing to rebase, reword and force push?

**Comment by asbjornu** [comment]
Sorry this was never answered. I hope you figured it out. Either way, we're on our way to release version 5 now, so whatever happened in version 2.0.1 isn't of much relevance anymore. Closing.
