### ISSUE TITLE
Version resets not supported

### ISSUE THREAD

**Issue by roji** [GitTools/GitVersion#830]
I've stumbled upon a scenario that doesn't seem to be supported with GitVersion.

In the course of a project's lifetime, it may be necessary to reset its version; this can happen if the project name is changed and the version is reset to 1.0.0. A concrete example would be Microsoft's Entity Framework 7 (still in development, never released yet) which has been renamed to Entity Framework Core, and whose version has been reset from 7.0.0-unstable* to 1.0.0-unstable*.

The problem is that GitVersion always looks for the highest version it can find (apart from tags), and if your commit history happens to have a "Merge branch 'release-3.0.0' into develop" it will pick that up. A possible fix for this would be to allow setting a minimum commit SHA1 beyond which GitVersion does not look, a sort of "reset point" for the git history as far as GitVersion is concerned.

**Comment by JakeGinnivan** [comment]
There is an up for grabs issue which would fix this at #538 

Would be nice to support scenarios like this

**Comment by roji** [comment]
Yep, looks like I created a dup.
