### ISSUE TITLE
Support for multiple projects in one git repo

### ISSUE THREAD

**Issue by twsouthwick** [GitTools/GitVersion#831]
It would be great if there was a way to manage multiple projects in one git repo that version separately from each other. Is there interest for this and would it even be possible?

**Comment by pascalberger** [comment]
GitVersion determines a version number based on the repository, which means that at any time there can only be one version number. IMHO way to go would be to have a separate repository per project (which also solves other problem like eg. triggering automatic builds)

**Comment by JakeGinnivan** [comment]
It would be cool to enable this scenario. I just think it will add too much complexity and introduce subtle bugs for people trying to achieve it.

**Comment by JakeGinnivan** [comment]
If someone writes up an RFC on how it would work talking about each of the versioning strategies that GitVersion has and the impact then we could make a call if it's worth it or not though

**Comment by twsouthwick** [comment]
I figured it might be difficult to reason about due to the versioning strategies GitVersion already does, but it would be cool. @pascalberger has a good point that ideally each project is in its own repo, but sometimes there are logistical, political, or some other reason why that's not possible. I'll have to research how the versioning strategies currently work, but will look into what generalizations could be made to accommodate this feature.

**Comment by asbjornu** [comment]
If a component needs its own version number, I see that as a crystal clear, non-negotiable proof that the component needs to reside in its own repository.

I'd say that if you have logistics, a process or politics that require you to jam several distinct components that need separate versioning strategies into one repository, then something about your logistics or process is broken or too weighed down by politics.

So I'm 👎  about having this feature in GitVersion at all.

**Comment by JakeGinnivan** [comment]
Going to close this one out. If someone opens an issue with a good investigation about how this is possible without making gitversion even more complicated than it already is then we can continue the discussion there.
As I said, it would be nice, but I don't think we can easily do this without really over complicating git version. 

The way I have solved this is simply with version.txt files or something similar in each of the projects folders.
