### ISSUE TITLE
Add NuGetPreReleaseTag

### ISSUE THREAD

**Issue by roji** [GitTools/GitVersion#834]
project.json builds allow you to leave the prerelease tag component of the version as a wildcard (`"version": "3.1.0-*"`) and then pass it in via a command-line parameter (`dotnet pack --version-suffix`).

Ironically with all the variables GitVersion generates, there doesn't seem to be a simple nuget-compatible prerelease tag (i.e. unstable0456 and not unstable.456). Maybe you guys would consider adding NuGetPreReleaseTag?

Related to #647

**Comment by JakeGinnivan** [comment]
Sounds fine to me.

**Comment by qetza** [comment]
Done in PR #1002
