### ISSUE TITLE
gitversion.yml @ TFS Build vNext (VSTS)

### ISSUE THREAD

**Issue by Pitterling** [GitTools/GitVersion#835]
Hi, how do i change the default pre release tag "unstable" for the develop branch while running on TFS Build vNext? 
I know how to change it within gitversion.yml, but how to edit this file when using the GitVersion.Extension? thx

**Comment by schenkjan** [comment]
Hi,
since you know how to change it using a gitversion.yml file, you could just put that file in the root directory of you git repo. At least that's what worked for me.

Best regards
Jan

**Comment by asbjornu** [comment]
@Pitterling As @schenkjan writes, adding `gitversion.yml` with the proper configuration to the repository root directory should work just fine, regardless of how the project is built.

**Comment by Pitterling** [comment]
@schenkjan @asbjornu I just tried it and it worked as pointed out by both of you. Thanks a lot. I was able to change the tag for the development branch.

**Comment by pkiers** [comment]
Hi,

Have you seen that place already? It's just spectaculous, you've got to look at it here <http://experience.robonbass.net/e2vpmd>

See you around, p.kiers@home.nl
