### ISSUE TITLE
Resetting BuildMetaData

### ISSUE THREAD

**Issue by anantkgoyal** [GitTools/GitVersion#836]
The semantic versioning I'm currently using is of the format 1.0.0.0. To use this I'm using major.minor.patch.buildMetaData. The buildMetaData increases on each commit, however occasionally I would like to increase the major, minor or patch number for a new release of software and accordingly reset the buildMetaData. How can I achieve this?

**Comment by asbjornu** [comment]
@anantkgoyal Just out of curiosity: What version strategy or git flow are you using? Either way, adding a tag should reset the build metadata.

**Comment by anantkgoyal** [comment]
We're developing completely off the master branch and each developer is creating a branch for his/her work and the merging into master when done. Please could you elaborate regarding adding the tag? I've tried to add the tag of the format release-2.0.0 to a commit but the next builds neither have the new version nor is the buildMetaData reset!

**Comment by asbjornu** [comment]
@anantkgoyal I don't think `release-2.0.0` is an expected tag format. Try with just `2.0.0` or `v2.0.0` and it should work. Alternatively, you can [configure](http://gitversion.readthedocs.org/en/latest/configuration/) what the tag format should be with `tag-prefix`.

**Comment by anantkgoyal** [comment]
@asbjornu That did not seem to work either. I have tried both of those tags. The tag-prefix currently is [vV]. Do I need to put the tag somewhere specifically?

**Comment by asbjornu** [comment]
You should tag the merge-commit on master.

**Comment by anantkgoyal** [comment]
@asbjornu I've tried that and it doesn't seem to be working either. I'm using pull requests on bitbucket and I'm adding in the tag right after merging.

**Comment by asbjornu** [comment]
The tag needs to be in place before the build. If you're doing the merge in the Bitbucket web interface, I suppose a build is set off on TeamCity or similar? If so, tagging that merge commit afterwards won't have any effect.

**Comment by anantkgoyal** [comment]
The build is happening on Bamboo. I even tried to add the tag to the last commit before asking for the pull request.

**Comment by asbjornu** [comment]
@anantkgoyal Hm, that's weird. Are you able to reproduce this in a repository you can make public on GitHub or (even better) as a repository fixture test in the GitVersion solution (as a pull request)?

**Comment by anantkgoyal** [comment]
@asbjornu If you don't mind please could you tell me exactly how and when am I supposed to pass in the tag?

**Comment by asbjornu** [comment]
@anantkgoyal, you simply do `git tag 2.0.0` on the merge commit on master. Building master after that has been done should set its version number to `2.0.0` and reset the build metadata.

**Comment by anantkgoyal** [comment]
Turns out that my server was not set up to pull, just checkout. Hence it was not getting the tags and because of this that tags were not being pulled in.

**Comment by asbjornu** [comment]
@anantkgoyal Makes sense! Glad you figured it out! 😄
