### ISSUE TITLE
Increasing Version with Commit Message

### ISSUE THREAD

**Issue by anantkgoyal** [GitTools/GitVersion#837]
Hi,
When I add in the string "+semver:major" or minor or patch with my commit message, the version does not seem to be increasing every time. Is there something that I am missing in this? Also can I reset the buildMetaData when I do this?
Thanks

**Comment by JakeGinnivan** [comment]
This feature respects SemVer, so it will use the biggest bump since the last tag. This is so if you bring in two breaking pull requests which both have `+semver: major` commits you only get a single major bump for that release.

**Comment by JakeGinnivan** [comment]
If you need further clarification just post a follow up question. Hope that answered your question.
