### ISSUE TITLE
Don't add extra debug info for /updateassemblyinfo

### ISSUE THREAD

**Issue by dcorriveau-omniscient** [GitTools/GitVersion#843]
Hi,

I'm using GitVersion from PS scripts (psake) for my build process. Before "MSBuilding", I call
 `gitversion /updateassemblyinfo true` to update all the AssemblyInfo files in the solution. I would have liked to be able to to that, get the result, parse the JSON and then get access to all the variables I need to use later on without having to call gitversion again. It would work perfectly fine if it wouldn't have been for the _Found 3 files_ debug line that is appended to the JSON result when running `updateassemblyinfo`. Looks like this:
```json
{
  "Major":1,                                                                                     
  "Minor":6,                                                                                     
  "Patch":17,                                                                                    
  ...
  "CommitsSinceVersionSourcePadded":"0006",                                                      
  "CommitDate":"2016-04-26"                                                                      
}                                                  
Found 3 files
```
So now I have to either remove that line before I can parse the JSON or call `/showvariable` as a following command to get the variables I want to use in the next steps.

1. Is there a /quiet switch or something I can do to prevent outputting those debug info ? (looking at `AssemblyInfoFileUpdate.cs` I don't think I could prevent this at the moment).
2. Are you doing some kind of optimization so that once gitversion has been run once and the repo hasn't changed, the various version info aren't recalculated every time we call gitversion ? (I could check the source code to find out but if you can answer this it would be great).

Thank you !

**Comment by JakeGinnivan** [comment]
1. We should always use the `Logger.Write*`. Any use of Console. is a bug, so this slipped through.
2. Yep, so if you use the show variable workaround the calls will be close to instant. We cache it in your .git folder somewhere (not sure off the top of my head).

**Comment by dcorriveau-omniscient** [comment]
Awesome, thanks for the quick response and fix.
I was wondering where you would have saved that cache, for some reason I didn't think of the .git folder but that sounds like a great idea.

**Comment by FunnyFry** [comment]
My bad for causing your issue @dcorriveau-omniscient 

Thanks @JakeGinnivan for fixing this!
Note taken to use Logger.Write* next time.

**Comment by gep13** [comment]
@dcorriveau-omniscient are you running on AppVeyor?

If so, as I do here:

https://github.com/chocolatey/ChocolateyGUI/blob/develop/BuildScripts/default.ps1#L440

You can make immediate use of the Environment variables that are created after the initial execution of GitVersion.  This will mean that you don't have to run it twice.

Hope that helps!

**Comment by dcorriveau-omniscient** [comment]
Thanks @gep13, I'm not running on AppVeyor. I'm calling from CruiseControl. I would `ConvertFrom-Json` the output and then set the variables I needed in env variables so that I could use them in functions I call later on. In any case, it's not a big deal as there are a few workarounds and none of them seem to be noticeably slow.
Thanks for sharing.

**Comment by gep13** [comment]
@dcorriveau-omniscient gotcha, no worries, just thought I would check just in case :smile_cat:
