### ISSUE TITLE
Version 3.5 crashes Visual Studio

### ISSUE THREAD

**Issue by mattGuima** [GitTools/GitVersion#844]
Installing the latest version, 3.5, on my web project in Visual Studio 2013 completely crashes it halfway through and corrupts the project file so it can't be opened without it crashing again unless you undo the changes.

**Comment by JakeGinnivan** [comment]
Seems there was a packaging error. Should have a release out shortly

**Comment by JakeGinnivan** [comment]
This should be fixed by 22d265db2299d406e643b219efdffc98bb8b2e0c, pushing a release now. 3.5.2 should update fine. I didn't check everything before this release as I wanted to push it a few days before heading on holiday. Sorry about that :)
