### ISSUE TITLE
Please remove /internalize flag from IlRepack task

### ISSUE THREAD

**Issue by maximpashuk** [GitTools/GitVersion#848]
GitVersion.CommandLine uses ilrepack command to embed all dependencies (yamldotnet, libgit2sharp, other girversion tools).

/internalize flag make all classes from these dependencies to be 'internal' instead of 'public'.

I just want to use gitversion.commandline, and also make some git stuff using libgit2sharp and powershell.
Now I should use separate libgit2sharp package, but I want to use classes from gitversion.commandline, all of them are synced by versions and tested together in gitversion.commandline.

I can't do it right now due to /internalize flag, all classes are internal, even if they were public in separate packages.

**Comment by asbjornu** [comment]
Which classes from `GitVersion.CommandLine` do you want to use? We should probably try to separate those out and move them into [GitTools.Core](/GitTools/GitTools.Core) instead of catering to edge-cases like yours within the `gitversion.exe` executable.

**Comment by maximpashuk** [comment]
Thanks @asbjornu, I understand that my method is not well enough.
GitVersion.Commandline should be called like .exe only, thats why it contains internal classes.

Now I am using GitVersion nuget packages and it is works fine, so I close my issue.

**Comment by asbjornu** [comment]
@maximpashuk I'm glad you resolved the issue! :+1:
