### ISSUE TITLE
NullReferenceException running GitVersion after branching off

### ISSUE THREAD

**Issue by roji** [GitTools/GitVersion#852]
So I was happily creating a new release/3.1.0 from develop, preparing a beta release, when currently gitversion suddenly started to bork. Running it on the same commit from develop works just fine. Any workaround proposal?

[Here are the logs](https://gist.github.com/roji/7900df20c057de5ad65a5990ec153658).

**Comment by asbjornu** [comment]
The problem happens within `LibGitExtensions.FindCommitBranchWasBranchedFrom()` somewhere. That is a rather complex and large method, so I think this might take a while to figure out. Any idea how to reproduce this, @roji, so we at least can get some `.pdb` files into a test scenario and get a line number?

**Comment by roji** [comment]
Hmph, I reinstalled my system in the meantime and can no longer reproduce the error, even when I execute GitVersion on exactly the same branch on the same commit as before...

Sorry about this, if I run into it again I'll report with better repro details.
