### ISSUE TITLE
BranchName set incorrectly

### ISSUE THREAD

**Issue by mdkf** [GitTools/GitVersion#857]
Calling gitversion /output buildserver on Jenkins sets GitVersion_BranchName=origin/develop instead of develop.

**Comment by gep13** [comment]
@JakeGinnivan @pascalberger either of you familiar with the innards of Jenkins?  Can you configure the branch name similar to what you can do in TeamCity?

**Comment by pascalberger** [comment]
Sorry, never have worked with Jenkins.

**Comment by mdkf** [comment]
Tried in my local repo, same result so I don't think it's Jenkins specific.

**Comment by mdkf** [comment]
Any ideas?
