### ISSUE TITLE
Update AssemblyInfo files checkbox does not work

### ISSUE THREAD

**Issue by MrHinsh** [GitTools/GitVersion#859]
Even with the Update AssemblyInfo files checkbox unchecked the task still tried to replace the version in the Assembly Info files.

![image](https://cloud.githubusercontent.com/assets/5205575/15188187/5d805fe0-179c-11e6-9965-83b180e886af.png)

Workaround: Disable the GitVersion task and build succeeds

This is related to #858 which is how it was found.

**Comment by pascalberger** [comment]
This was already fixed recently with #847 but not released yet.
