### ISSUE TITLE
Incorrect version calculation

### ISSUE THREAD

**Issue by lerthe61** [GitTools/GitVersion#862]
We have faced some strange behavior, when fork in repository is interpreted as merge:
![canvas](https://cloud.githubusercontent.com/assets/6067323/15296475/388c3a50-1b9e-11e6-8746-9fe4d525fc0c.png)

We also found workaround by changing _track-merge-target_ to false for _develop_ branch.
Original configuration is
[GitVersionConfig.zip](https://github.com/GitTools/GitVersion/files/266536/GitVersionConfig.zip)

We use version 3.4.1 (portable). But issue is still presented in latest codebase.

**Comment by lerthe61** [comment]
Prepare test repository for illustrating problem. For branch develop GitVersion calculate SemVer "1.0.1-feature.2"
[TestRepo.zip](https://github.com/GitTools/GitVersion/files/267466/TestRepo.zip)

**Comment by lerthe61** [comment]
Attach unit test for issue. It seems that problem in TrackMergeTargetBaseVersionStrategy.IsDirectMergeFromCommit method.

**Comment by pascalberger** [comment]
@lerthe61 Can you please test with latest [4.0.0-beta release](https://github.com/GitTools/GitVersion/releases/tag/v4.0.0-beta.1) as it changes some behavior how versioning on develop is handled.

**Comment by lerthe61** [comment]
@pascalberger Thanks! Everything look ok now. I will create pull request with my test to prevent regression in future
