### ISSUE TITLE
Changed tag-prefix doesn't apply till .git\gitversion_cache is cleaned up

### ISSUE THREAD

**Issue by sergiorykov** [GitTools/GitVersion#863]
May be I misssed an option, but in latest release 3.5.3 it doesn't work.

As a solution I can suggest to save in .git\gitversion_cache\effective_config.yml effective config and compare it with calculated effective config. As I understand how configuration is being overriden we have dynamic override (from command line and other sources) and static through GitVersion(Config).(yaml|yml) or other data in repository.
if It is dynamic - ignore caches and didn't persist result in cache
if it is static - compare cached effective config and calculated - if there are not equal - clear caches and run.

and add option /force to clean up everything and recalculate it each time.

Is my suggestion correct?

**Comment by asbjornu** [comment]
#808, which was included in [version 3.5.0](https://github.com/GitTools/GitVersion/releases/tag/v3.5.0) should have fixed this. It's strange that it's not. I'd rather not add any more command line arguments and instead try to fix the cache invalidation logic. Can you envision a solution to this problem without introducing any command line arguments? It would be nice if this took #870 into consideration as well, but that's just bonus.

**Comment by sergiorykov** [comment]
There are two bugs in code:
1) ConfigurationProvider expects to be called with `workingDirectory`. _init_ command uses it to create config file. _output_ command executes ExecuteCore.ExecuteInternal passing to it projectRoot:

`var configuration = ConfigurationProvider.Provide(projectRoot, fileSystem, overrideConfig: overrideConfig);`

So if I have my project in subdirectory I will catch that my config file will be completely ignored.

2) ConfigurationProvider suggests to use `GitVersion.yml` instead of `GitVersionConfig.yaml`, but `GitVersionCache.GetKey` uses only obsolete config file name: 

`var configPath = Path.Combine(repo.GetRepositoryDirectory(), "GitVersionConfig.yaml");`

Second bug is concrete, first one can cause errors if someone uses workingDirectory being subdirectory of projectRoot and it's not clear how to fix it with backward compability.

I think version calculation and show config command must fail if it will find config files in both directories workingDirectory and projectRoot, then all clients can decide which config file to use.

**Comment by sergiorykov** [comment]
#870 issue will be immediately fixed too.

**Comment by sergiorykov** [comment]
And GitVersionCache finds config file at projectRoot too (it's was a bit hidden too).

**Comment by sergiorykov** [comment]
show config command uses working directory too. So it's pretty hard to figure out why your config didn't applied.

**Comment by JakeGinnivan** [comment]
Fixed in 3.6.1
