### ISSUE TITLE
GitVersion init settings for private github repos with Appveyor

### ISSUE THREAD

**Issue by bigjonroberts** [GitTools/GitVersion#869]
Appveyor uses ssh to clone/fetch a repo as you can configure the public key for this operation in Github.

I wanted to enable Gitversion for my private repo on Appveyor. The suggested workarounds to use https and set environment variables weren't working for me as appveyor does not include encrypted environment variables (GITVERSION_REMOTE_PASSWORD) on PR builds for security reasons.

@JakeGinnivan suggested that I change the process to avoid the extra fetch instead of trying to use ssl.

This worked out and here's what I ended up with in my appveyor.yml:

```
before_build:
  - nuget restore
  - ps: gitversion $env:APPVEYOR_BUILD_FOLDER /l console /output buildserver /updateAssemblyInfo /nofetch /b $env:APPVEYOR_REPO_BRANCH
```

I think it would be a great idea to add a prompt in `gitversion init` asking if your repo is private and configuring appveyor output to match this when a repo is private.

I'll leave this open several days to see what people think.  If it seems a good idea, I should be able to make the changes this weekend and open a PR.

**Comment by gep13** [comment]
@bigjonroberts  this sounds like a good idea to me!

**Comment by JakeGinnivan** [comment]
Ditto, things like this are handy. Also would be good to add some info about using it with a private AppVeyor repo to the docs.

**Comment by bigjonroberts** [comment]
Looks like this is the place to make these code changes, correct?

https://github.com/GitTools/GitVersion/blob/master/src/GitVersionCore/Configuration/Init/BuildServer/AppVeyorSetup.cs

**Comment by bigjonroberts** [comment]
Hmmm..... This took me much longer than a few days to circle back around... :8ball: wasn't in fully working order back in May.

**Comment by pkiers** [comment]
Hi,

There are a couple of books that inspire me to do really great things, here is the list of that books <http://direct.uicpharmacogenomics.com/e2finbyp>

Kind regards, p.kiers@home.nl
