### ISSUE TITLE
'beta' prerelease tag is used on develop branch when we tag a version on release branch

### ISSUE THREAD

**Issue by jderrac** [GitTools/GitVersion#875]
Hi,
We are trying to use gitversion but we don't understand why develop inherit the 'beta' prerelease tag from the release/1.0.0 branch when we tag a version on the release branch.
Is this a normal behavior?
We are using gitflow with teamcity, there is no custom configuration.
Thanks!
![image](https://cloud.githubusercontent.com/assets/1788613/15499402/5a1d8104-21a4-11e6-8727-0c0dd410775b.png)

**Comment by pascalberger** [comment]
@jderrac Do you still see this issue with the latest release (3.6.1)?
