### ISSUE TITLE
Commit in master branch gets prerelease tag

### ISSUE THREAD

**Issue by labmonkey42** [GitTools/GitVersion#877]
Maybe I am misunderstanding the process here, but when we merge our development branch (devel) to master, whatever the semantic version is on the most recent devel commit merged is the version that GitVersion detects for master.

When we started using gitversion the devel commits were automatically determined to be 0.1.0-unstable.nn and the CI server tagged the commit upon successful build.  When we merged to master GitVersion determined the version to still be 0.1.0-unstable.xx (where xx was the tagged version for the commit which was merged.

I looked at our GitVersionConfig.yaml (has since been renamed to GitVersion.yml) and talked to our dev lead and discovered that the merge had been done with a rebase and we decided to not rebase merges in the future.  After deleting the unstable tag from master, manually tagging master as 0.1.0 and triggering another CI build, the master build came out as 0.1.0 and successive devel commits were tagged 0.2.0-unstable.nn.  So between my config changes (ContinuousDelivery vs ContinuousDeployment) it appeared to be resolved.  However, at the next merge to master instead of getting 0.3.0 we again got 0.2.0-unstable.xx which I had to manually fix again.

Our current line is up to 0.3.0 in master and 0.4.0-unstable.nn in devel and I would like to find a solution that doesn't require manual shuffling to get the merge versioned and tagged appropriately.  Am I misunderstanding how GitVersion works such that we should be tagging the master merge ourselves, or is this something that I still do not have configured correctly?

**Comment by labmonkey42** [comment]
Output with /showconfig
`assembly-versioning-scheme: MajorMinorPatch
mode: ContinuousDeployment
tag-prefix: ''
continuous-delivery-fallback-tag: ci
major-version-bump-message: '\+semver:\s?(breaking|major)'
minor-version-bump-message: '\+semver:\s?(feature|minor)'
patch-version-bump-message: '\+semver:\s?(fix|patch)'
legacy-semver-padding: 4
build-metadata-padding: 4
commits-since-version-source-padding: 4
commit-message-incrementing: Enabled
branches:
  master:
    mode: ContinuousDeployment
    tag: ''
    increment: Patch
    prevent-increment-of-merged-branch-version: true
    track-merge-target: false
  release(s)?[/-]:
    mode: ContinuousDeployment
    tag: beta
    increment: Patch
    prevent-increment-of-merged-branch-version: true
    track-merge-target: false
  features?[/-]:
    mode: ContinuousDeployment
    tag: useBranchName
    increment: Inherit
    prevent-increment-of-merged-branch-version: false
    track-merge-target: false
  (pull|pull\-request(s)?|pr)[/-]:
    mode: ContinuousDeployment
    tag: PullRequest
    increment: Inherit
    prevent-increment-of-merged-branch-version: false
    tag-number-pattern: '[/-](?<number>\d+)[-/]'
    track-merge-target: false
  hotfix(es)?[/-]:
    mode: ContinuousDeployment
    tag: beta
    increment: Patch
    prevent-increment-of-merged-branch-version: false
    track-merge-target: false
  support[/-]:
    mode: ContinuousDeployment
    tag: ''
    increment: Patch
    prevent-increment-of-merged-branch-version: true
    track-merge-target: false
  devel:
    mode: ContinuousDeployment
    tag: unstable
    increment: Minor
    prevent-increment-of-merged-branch-version: false
    track-merge-target: true
  releases?[/-]:
    mode: ContinuousDeployment
    tag: beta
    increment: Patch
    prevent-increment-of-merged-branch-version: true
    track-merge-target: false
  (pull|pull\-requests|pr)[/-]:
    mode: ContinuousDeployment
    tag: PullRequest
    increment: Inherit
    prevent-increment-of-merged-branch-version: false
    tag-number-pattern: '[/-](?<number>\d+)[-/]'
    track-merge-target: false
  dev(elop)?(ment)?$:
    mode: ContinuousDeployment
    tag: unstable
    increment: Minor
    prevent-increment-of-merged-branch-version: false
    track-merge-target: true
ignore:
  sha: []`

Current GitVersion.yml:
`assembly-versioning-scheme: MajorMinorPatch
mode: ContinuousDeployment
#mode: ContinuousDelivery
tag-prefix: ''
continuous-delivery-fallback-tag: ci
major-version-bump-message: '\+semver:\s?(breaking|major)'
minor-version-bump-message: '\+semver:\s?(feature|minor)'
patch-version-bump-message: '\+semver:\s?(fix|patch)'
legacy-semver-padding: 4
build-metadata-padding: 4
commit-message-incrementing: Enabled
branches:
  master:
    tag: ''
    increment: Patch
    prevent-increment-of-merged-branch-version: true
    track-merge-target: false
  release(s)?[/-]:
    tag: beta
    increment: Patch
    prevent-increment-of-merged-branch-version: true
    track-merge-target: false
  feature[/-]:
    tag: useBranchName
    increment: Inherit
    prevent-increment-of-merged-branch-version: false
    track-merge-target: false
  (pull|pull\-request(s)?|pr)[/-]:
    tag: PullRequest
    increment: Inherit
    tag-number-pattern: '[/-](?<number>\d+)[-/]'
    prevent-increment-of-merged-branch-version: false
    track-merge-target: false
  hotfix(es)?[/-]:
    tag: beta
    increment: Patch
    prevent-increment-of-merged-branch-version: false
    track-merge-target: false
  support[/-]:
    tag: ''
    increment: Patch
    prevent-increment-of-merged-branch-version: true
    track-merge-target: false
  devel:
    tag: unstable
    increment: Minor
    prevent-increment-of-merged-branch-version: false
    track-merge-target: true

`

Please let me know any other information I can provide to help troubleshoot.

**Comment by JakeGinnivan** [comment]
It may be an issue with not using a release/ branch which is dictated by GitFlow. With these sort of issues I always suggest submitting a PR with a failing test. Have a look at the Core/IntegrationTests folder and put together a sample of what you are doing and the version you expect. 

Or drop your git graph into a gist:

`git log --graph --format=""%h %cr %d"" --decorate --date=relative --all --remotes=* -n 100`

**Comment by JakeGinnivan** [comment]
Closing in favor of #889
