### ISSUE TITLE
GitVersion doesn't pick up version tags assigned to the latest commit

### ISSUE THREAD

**Issue by urig** [GitTools/GitVersion#878]
I've setup GitVersion as a build step in my TeamCity build configuration. 
1. Given that the most recent version tag on master is v1.2.3  
2. And TeamCity runs a build based on the latest commit on master
3. When I later tag that same commit with a new version tag: v1.2.4
4. Then when I manually run the TeamCity build, GitVersion ignores the new version tag and again outputs the previous version.

**UPDATE**: I've struck out the bits about "skipping fetching" below for the reason that fetching is no longer skipped in my build and yet the symptoms above still occur.
<s>In the build log I see the following message:

> INFO [05/10/16 7:52:05:74] Skipping fetching, if GitVersion does not calculate your version as expected you might need to allow fetching or use dynamic repositories

Why is GitVersion skipping fetching? How can I _"allow fetching"_?</s>

Note: 
- The VCS root is configured to run "automatically on client". 
- The GitVersion build step is based on the [GitVersion TeamCity meta-runner](https://github.com/JetBrains/meta-runner-power-pack/tree/master/gitversion).
- I get the exact same behavior even when I use dynamic repositories. :(

**Comment by asbjornu** [comment]
What are the command line arguments passed to GitVersion? And does changing the VCS Root checkout behavior to "Automatically on agent" change anything?

**Comment by asbjornu** [comment]
And as I wrote on Gitter, in TeamCity, `buildServer.PreventFetch()` will return `true` unless the environment variable `Git_Branch` is defined.

**Comment by urig** [comment]
Thanks @asbjornu . I have `Git_Branch` defined in the TeamCity build configuration as an environment variable. (Shows up as `env.Git_branch`).  
The VCS root checkout behavior is already set to "Automatically on agent". I get errors if I set it to "Automatically on server".  
My command line (generated by the meta-runner) is:
`gitversion.exe "D:\TeamCity\buildAgent\work\ac267eddc88660a" /output "buildserver" /l "D:\TeamCity\buildAgent\work\ac267eddc88660a\GitVersion3.log" /UpdateAssemblyInfo`

**Comment by urig** [comment]
I've made two gists with the relevant messages from the TC build log =
* One where the version tag on [latest commit is not picked up by GitVersion](https://gist.github.com/urig/b0395230b617175f841c5a09783373c2)
* And another where [it's picked up by GitVersion after another commit is made](https://gist.github.com/urig/b7375bf1e4c3bd9f11228cb4b2b5e240)

**Comment by asbjornu** [comment]
@urig It would be neat if the `https://github.com/TripChamp/middleware.git` repository or a variant of it showing the same problems were public, so I could execute the command line you have there locally and do some debugging. Is that a doable proposition at all?

**Comment by JakeGinnivan** [comment]
Is the sha GitVersion sees correct?

As far as the logs tell it's picking up the correct tags and moving forward.Interesting we are not seeing anything about dynamic repos. Maybe there is a bug with log output with the switch to Core?

**Comment by urig** [comment]
@asbjornu I'm afraid that wouldn't be possible. I'll see if I can setup a different private repo where I can repro then give you access to that. (Maybe the repo being private is a part of the root cause?)

@JakeGinnivan Yes, GitVersion is seeing the correct SHA but does not see the new tags applied to it. (Until a new commit is added further down master).

**Comment by urig** [comment]
@asbjornu I've created a new private repo and was able to reproduce there. I've sent you a "collaborator" invite to this repo. Feel free to try it out.

**Comment by urig** [comment]
I have a suspicion that the origin of this issue might be in the way TeamCity updates the git repo in "" mode. 
Below is the log of git commands that TC uses. Might anyone be able to figure out if somehow these fail to get the new tags over to the local repo (on the TC agent) that GitVersion is using?

>"revision: 84044ae5256b1a7238feef6fa9d72a69d4582330"
git show-ref
git -c core.askpass=D:\TeamCity\buildAgent\temp\buildTmp\pass2949790385075181105.bat ls-remote origin
git show-ref refs/heads/master
git show-ref refs/heads/master
"Cleaning D:\TeamCity\buildAgent\work\ac267eddc88660a"
"The .git directory is missing in 'D:\TeamCity\buildAgent\work\ac267eddc88660a'. Running 'git init'..."
git init
git remote add origin https://<redacted>.git
git pack-refs --all
git config core.sparseCheckout false
git show-ref
git -c core.askpass=D:\TeamCity\buildAgent\temp\buildTmp\pass5143212605327899971.bat ls-remote origin
git show-ref refs/remotes/origin/master
git log -n1 --pretty=format:%H%x20%s 84044ae5256b1a7238feef6fa9d72a69d4582330 --
git branch
git reset --hard 84044ae5256b1a7238feef6fa9d72a69d4582330

**Comment by asbjornu** [comment]
@urig Thanks. How did you reproduce the the problem in the `gitversion-bug` repository? I.e. which command did you run?

**Comment by urig** [comment]
@asbjornu Tx. Here's the full command line. Note that it's run by the TeamCity agent:
>C:\ProgramData\chocolatey\bin\gitversion.exe "D:\TeamCity\buildAgent\work\f8fcbd6382456458" /output "buildserver" /l "D:\TeamCity\buildAgent\work\f8fcbd6382456458\GitVersion3.log"

**Comment by asbjornu** [comment]
@urig Are you able to reproduce locally on the command line, or is it only visible within TeamCity?

**Comment by urig** [comment]
@asbjornu I'm unable to reproduce on the command line because gitversion ignores my dynamic repository command line switches (!). So currently only visible inside TC build log.  
I would love to grab 10 mins of your time online to demo these issues, if at all possible :)

**Comment by asbjornu** [comment]
I see. How about duplicating [this test](https://github.com/GitTools/GitVersion/blob/master/src/GitVersionExe.Tests/PullRequestInTeamCityTest.cs) and see if you can reproduce the problem there, somehow? That would be the best demonstration of the problem as well as the easiest way to fix it.

**Comment by pkiers** [comment]
Hello,

I've been looking for some  stuff on the web and suddenly came across that! You should see that, I swear you'll love it! More info here <http://explore.whowasgrandpa.com/e2asyq>

Very truly yours, p.kiers@home.nl

**Comment by pkiers** [comment]
Hello,

Here is a good news from our mutual friend, just read it here <http://explore.sawgrassglen.com/e2eaq>

All best, p.kiers@home.nl

**Comment by junkangli** [comment]
I am facing the same issue. Is there any updates on it?

**Comment by asbjornu** [comment]
@junkangli: No. We need a way to reproduce the problem.

**Comment by dylan-asos** [comment]
Was also facing this issue - running the build and choosing the 'clean all files in the checkout directory before the build' option forced it to use the tag I had applied to master after the last commit.

**Comment by asbjornu** [comment]
If [Clean Checkout](https://confluence.jetbrains.com/display/TCD10/Clean+Checkout) is a solution to the problem as @dylan-asos may indicate, can this be closed? If:

> Clean all files in the checkout directory before the build option in the "Version Control Settings" of the build configuration

... works for you @junkangli and @urig, please let us know.

**Comment by junkangli** [comment]
The setting "Clean all files in the checkout directory before the build" was enabled all the while.
I will need to investigate more on the issue happening in my repo and teamcity build.

**Comment by junkangli** [comment]
I found that running `git tag` in the repository directory on my teamcity agent did not list the latest tag. 
So it seems that the source of the problem lies with teamcity, as suspected by @urig mentioned in this [comment](https://github.com/GitTools/GitVersion/issues/878#issuecomment-222374712).

**Comment by junkangli** [comment]
It works now after I followed the solution [here](https://teamcity-support.jetbrains.com/hc/en-us/community/posts/205450030/comments/204877330), which is to disable "Use mirrors" under Agent Settings in TeamCity version control settings.

**Comment by dylan-asos** [comment]
So possibly the combination of 'Clean Checkout' and disable 'Use Mirrors' is the solution here? (Use Mirrors was disabled in my build)

**Comment by junkangli** [comment]
Yes, that could be it. But one thing is for sure is that it's not an issue with gitversion, but teamcity. So I guess it's fair to close this issue now.

**Comment by asbjornu** [comment]
Please have a look at what I've written here and see if that might help resolve this problem: https://github.com/GitTools/GitVersion/issues/912#issuecomment-314443855

**Comment by asbjornu** [comment]
I assume this is solved. Closing.

**Comment by paul-michalik** [comment]
Unfortunately I am running into this too. TeamCity Enterprise 2021.2.1

**Comment by dario-l** [comment]
Me too 😢 

When I create new release merging develop to master (GitFlow) on my local computer GitVersion properly generates all versions. The same execution made by TeamCity generates wrong versions. 😞
