### ISSUE TITLE
Consolidate AssemblyInfo update logic

### ISSUE THREAD

**Issue by asbjornu** [GitTools/GitVersion#883]
I added a few TODOs in cb4698d72b8d7aca6087769dfa402472abc3e9bc for consolidation of the AssemblyInfo update logic in `GitVersionTask` and `GitVersionExe` that should be tackled. There's quite a bit of duplicated functionality that leads to diverging support for different features and bugs in the task that might be well tested in the `.exe` and vice versa. Consolidating all of this into `GitVersionCore` with accompanying tests would be neat.

**Comment by bvirkler** [comment]
Came here from #1319, bumping to "un-stale".

**Comment by stunney** [comment]
@asbjornu what is left with this issue?

**Comment by asbjornu** [comment]
@stunney, pretty much everything I wrote in the issue desription is still applicable.

**Comment by arturcic** [comment]
@asbjornu I think we can close this one, as we moved the logic for AssemblyInfo update into GitVersion.Core, and both the `GitVersionTask` and `GitVersionExe` are using the same class

**Comment by asbjornu** [comment]
Is 55d066462c21acf02fd6a1a15ff5707317850ce5 the commit that did the consolidation, @arturcic?

**Comment by arturcic** [comment]
yes

**Comment by asbjornu** [comment]
Ok. Closing as resolved in 55d066462c21acf02fd6a1a15ff5707317850ce5.
