### ISSUE TITLE
TFS vNext build step yaml

### ISSUE THREAD

**Issue by roryprimrose** [GitTools/GitVersion#884]
Where should the gitversion.yaml file go under source control when using the GitVersion build step in VSO? There isn't a configuration value for it so I'm assuming there is a convention (solution root?)

**Comment by asbjornu** [comment]
Solution (or Git) root, yes.

**Comment by pascalberger** [comment]
@roryprimrose Is you question answered and can this issue be closed?

**Comment by JakeGinnivan** [comment]
We look for GitVersion.yaml in the repo root, not solution root. Let us know if this hasn't answered the question and we can reopen this issue

**Comment by roryprimrose** [comment]
Sorry, on holidays. Yes, it is all working well in the solution root that is also the repo root in my case.
