### ISSUE TITLE
AssemblyFileVersionAttribute format configurable

### ISSUE THREAD

**Issue by chrgei** [GitTools/GitVersion#886]
Thanks for this great tool.
It would be very nice, if we can configure the format of the AssemblyFileVersionAttribute with an extra variable. Is this possible for the next release?

**Comment by JakeGinnivan** [comment]
Could you give examples, or even implement a PR which adds this :)

**Comment by chrgei** [comment]
Yes I can. AssemblyFileVersionAttribute is formated as "Major.Minor.Patch.0" with fixed "0". We want it to format as "Major.Minor.Patch.CommitsSinceVersionSource". I know, it's not realy SemVer but it is better suited to our company rules.

**Comment by Eregrith** [comment]
I'm interested to know if AssemblyInformationalVersion has its format configurable as well. As mentionned in #1161, NuGet fails to parse current AssemblyInformationalVersion's format (Because it uses SemVer 2.0 dot notation) and I need to set the format to something SemVer 1.0-compatible.
For example I'll gladly take something like :

```
$ cat GitVersion.yml
assembly-informational-versioning-scheme: NuGetVersionV2
```

generating 
```
[assembly: AssemblyInformationalVersion("1.0.1-develop0009")]
```

**Comment by Eregrith** [comment]
Nevermind, [it seems ```assembly-informational-format``` might already what I needed.](https://github.com/GitTools/GitVersion/issues/1062). I should have searched better before posting.

**Comment by chrgei** [comment]
Okay. I wanted this Format:

`[assembly: AssemblyFileVersion("1.0.1.9")]
`

In the meantime, however, we are working according to Sem 1.0 rules.

Thank you for the response. It's a great tool.

**Comment by asbjornu** [comment]
Doesn't #1130 provide the required functionality here?
