### ISSUE TITLE
Feature suggestion: Pre-release tag that indicates commit (short SHA)

### ISSUE THREAD

**Issue by urig** [GitTools/GitVersion#887]
As a GitVersion user, I'd like to be able to generate a unique version for a given commit that indicates the identity of this commit. 

For example, when running on a branch where the latest commit is `e81220c95e5dd407ffc340baf2fbec7e21f76be9` I'd like to get a FullSemVer that looks like '1.3.8-commit.e81220c+2`.

As the person suggesting this feature I would suggest a new setting for the `tag` configuration setting: "`commit`". When "`commit`" is specified, the `UpdatePreReleaseTag()` method will fetch the current commit SHA, truncate it and use it for the `PreReleaseTag`.

**Comment by urig** [comment]
I volunteer to implement ;)

**Comment by simonejsing** [comment]
This is a feature I would also like to see. I'd suggest using
tag: {useCommitHash}
which is similar to {useBranchName}

**Comment by asbjornu** [comment]
`tag: useCommitHash` and `{CommitHash}` sound like useful additions! A PR with good test coverage of this would have a high probability of being merged. :smiley: :+1:

**Comment by pkiers** [comment]
Hi,

We are planning a small journey this month and I need you to take a look at our route and tell what you think <http://direct.lasermetalart.com/e2mogzwu>

p.kiers@home.nl

**Comment by superware** [comment]
Hey @urig, have you managed to implement this? anyone else maybe?

**Comment by santiagovm** [comment]
#1452 seems related to this

**Comment by urig** [comment]
As the OP, I concur. I think we can close this Issue in favor of https://github.com/GitTools/GitVersion/pull/1405 .

**Comment by pmiossec** [comment]
don't close the issue until it's merged... otherwise other people will think it's solved...
