### ISSUE TITLE
Add support for GitVersion.yml outside of git repo root

### ISSUE THREAD

**Issue by johncrim** [GitTools/GitVersion#894]
The ability to either use a global gitversion.yml, or the ability to point gitversion at a config file outside of the source tree, eg:

```
gitversion -config $env:HOME/GitVersion.yml
```

Would enable us to avoid duplicating a bunch of files in many repos. For companies with many git repos that use the same git patterns, requiring the config files to be in the root of each repo is a repo setup and maintenance burden.

If you're interested in accepting a PR for this I can provide it.

**Comment by asbjornu** [comment]
@johncrim That sounds like a great feature to add, indeed. If you can submit a PR with working test(s) for this, that would be awesome!

**Comment by pkiers** [comment]
Hey,

I think this app is gonna be helpful for you, read more here <http://experience.wp7ug.com/e2ilnj>

Yours, p.kiers@home.nl

**Comment by kyberias** [comment]
Apparently this hasn't been implemented yet. I'd like to try it since I need the feature.

**Comment by asbjornu** [comment]
@kyberias: It's up for grabs! Just grab it! 😄
