### ISSUE TITLE
Pull Request from other user, not building branch

### ISSUE THREAD

**Issue by matteobruni** [GitTools/GitVersion#896]
Hello,
I've a GitHub repository with a pull request from another user but it's not building the branch. It says " Waiting for status to be reported " with no red/yellow/green icon.
The pull request is [this](https://github.com/Ar3sDevelopment/Synology/pull/44)
What am I doing wrong?

**Comment by gep13** [comment]
@matteobruni looks like that PR is now merged.  Did you solve the issue?

**Comment by matteobruni** [comment]
The PR is merged but I had to disable the check on the other user branch from repo's settings.

**Comment by asbjornu** [comment]
@matteobruni I think we need to see a PR in the "Waiting for status to be reported" state to be able to understand what this problem is. Do you have an example of a PR that is in this unexpected state?

**Comment by matteobruni** [comment]
@asbjornu I've created a pull request from a fork. The PR has the issue and it is [this](https://github.com/Ar3sDevelopment/Synology/pull/57)

**Comment by asbjornu** [comment]
@matteobruni Ok, thanks. So, AppVeyor has completed the run of its `pr` build, but the `branch` build is halting. And you expect this is due to GitVersion? For what reason? Do you have build logs that can pinpoint the problem?

**Comment by matteobruni** [comment]
OOOPS!!! I opened the issue in the wrong place, I thought I was on AppVeyor, I don't remember what link take me here. Sorry!!

**Comment by pkiers** [comment]
Hi,

I'm so happy to hear the latest news from our friends, you may read it here <http://effort.rafikihotels.com/e2kvx>

Best regards, p.kiers@home.nl
