### ISSUE TITLE
Add IsTagged to output

### ISSUE THREAD

**Issue by JakeGinnivan** [GitTools/GitVersion#901]
Knowing if we are building a tag is useful for a number of reasons including triggering a deployment etc.

In #1052 it was asked for the actual tag as well. So lets add `IsTagged` and `GitCommitTag` (or something similar)

**Comment by gep13** [comment]
@JakeGinnivan can you confirm what you mean by `output`?  This information is available depending on which CI provider you are using.  For example, we do this here:

https://github.com/cake-build/cake/blob/develop/build/parameters.cake#L63

for appveyor.

**Comment by JakeGinnivan** [comment]
Yeah, I am using VSTS which Cake doesn't support. Id like it in GitVersion so I can grab the variable even if not using cake

**Comment by pascalberger** [comment]
@JakeGinnivan Even if you have this information available in a variable in a build definition, how do you trigger a deployment in VSTS based on this (with the current feature set)? I don't think there's a way currently to pass variable from build to deployment. At least it wasn't last time I asked MSFT about it. But certainly would be useful for different kind of things

**Comment by gep13** [comment]
>@JakeGinnivan said...
I am using VSTS which Cake doesn't support

Would happily accept a PR to support that Build System :-)

@JakeGinnivan could you get what you wanted using the Cake.Git addin?  https://github.com/WCOMAB/Cake_Git

@devlead does the above include information about the current tag?

**Comment by devlead** [comment]
@gep13 the [GitDescribe(DirectoryPath)​](http://cakebuild.net/api/cake.git/8654684f/36ae09ee) method will give you most recent tag.

**Comment by JakeGinnivan** [comment]
It is more that I don't need to get this from Cake, I can just add it to the version info. I think it's a useful feature for GitVersion, even if it's available in Cake

**Comment by asbjornu** [comment]
I agree with @JakeGinnivan that this is metadata that is useful in GitVersion, even though it's available in Cake. It's information consumers of (just) GitVersion will find useful too, I'm sure. :+1:

**Comment by gep13** [comment]
@JakeGinnivan @asbjornu sorry, I think I started commenting on this issue incorrectly.  When @JakeGinnivan posted this, he had also posted on two issues on the Cake repo, and I had assumed that this issue was created in the Cake repo as well, which is what confused me, and I was wondering why it was being asked for.  Now that I understand what you guys are talking about, this makes total sense.  Sorry for the confusion.
