### ISSUE TITLE
Version tag ignored @ TF - VSO Agent?

### ISSUE THREAD

**Issue by Pitterling** [GitTools/GitVersion#903]
only Master branch - 2 version tags - v1.1.0 & v1.2.0

Git Tags are ignored on TF (GitVersionTask 3.5.4) while running same commandline local, tags are found. 

> ******************************************************************************
> Starting task: GitVersion
> ******************************************************************************
> Set workingFolder to default: C:\TfsBuildAgents\VsoBuildAgent\tasks\GitVersion\3.5.4
> Executing the powershell script: C:\TfsBuildAgents\VsoBuildAgent\tasks\GitVersion\3.5.4\GitVersion.ps1
> Current Directory:  C:\TfsBuildAgents\VsoBuildAgent\tasks\GitVersion\3.5.4
> Sources Directory:  C:\TfsData\Build\_work\32d7189a\s
> Invoking GitVersion with C:\TfsData\Build\_work\32d7189a\s /output buildserver /nofetch
> C:\TfsBuildAgents\VsoBuildAgent\tasks\GitVersion\3.5.4\GitVersion.exe C:\TfsData\Build\_work\32d7189a\s /output buildserver /nofetch
> INFO [06/14/16 12:18:36:14] Working directory: C:\TfsData\Build\_work\32d7189a\s
> INFO [06/14/16 12:18:36:15] Running on Windows.
> INFO [06/14/16 12:18:36:15] Applicable build agent found: 'VsoAgent'.
> INFO [06/14/16 12:18:36:18] Project root is: C:\TfsData\Build\_work\32d7189a\s
> INFO [06/14/16 12:18:36:25] Begin: Loading version variables from disk cache
>   INFO [06/14/16 12:18:36:28] Cache file C:\TfsData\Build\_work\32d7189a\s\.git\gitversion_cache\828519616B3C49A08979DB850F92911AF168077E.yml not found.
> INFO [06/14/16 12:18:36:28] End: Loading version variables from disk cache (Took: 23.00ms)
> INFO [06/14/16 12:18:36:28] Branch from build environment: refs/heads/master
> INFO [06/14/16 12:18:36:42] Using latest commit on specified branch
> INFO [06/14/16 12:18:36:44] Running against branch: master (94245cf7f44580da27e2cc213fdc9f625b5d6ec7)
> INFO [06/14/16 12:18:36:45] Begin: Calculating base versions
>   INFO [06/14/16 12:18:36:49] Fallback base version: 0.1.0 with commit count source 2ea14edb6a0442787332b426810d02ca99317ef8
>   **INFO [06/14/16 12:18:36:59] Base version used: Fallback base version: 0.1.0 with commit count source 2ea14edb6a0442787332b426810d02ca99317ef8**
> INFO [06/14/16 12:18:36:59] End: Calculating base versions (Took: 145.00ms)
> INFO [06/14/16 12:18:36:60] Skipping version increment
> INFO [06/14/16 12:18:36:60] 19 commits found between 2ea14edb6a0442787332b426810d02ca99317ef8 and 94245cf7f44580da27e2cc213fdc9f625b5d6ec7
> INFO [06/14/16 12:18:36:62] Begin: Creating dictionary
> INFO [06/14/16 12:18:36:63] End: Creating dictionary (Took: 6.00ms)
> INFO [06/14/16 12:18:36:63] Begin: Storing version variables to cache file C:\TfsData\Build\_work\32d7189a\s\.git\gitversion_cache\DDFBD5AE705F119A96C8ACECEF4D54DC7A84795D.yml
> INFO [06/14/16 12:18:36:69] End: Storing version variables to cache file C:\TfsData\Build\_work\32d7189a\s\.git\gitversion_cache\DDFBD5AE705F119A96C8ACECEF4D54DC7A84795D.yml (Took: 60.00ms)
> INFO [06/14/16 12:18:36:69] Applicable build agent found: 'VsoAgent'.

while running local with same command line

> $ ../../GitVersion_3.5.4/GitVersion.exe -output buildserver -nofetch
> INFO [06/14/16 13:57:24:54] Working directory: C:\Code\STOR\HP_perf3par
> INFO [06/14/16 13:57:24:56] Running on Windows.
> INFO [06/14/16 13:57:24:62] Project root is: C:\Code\STOR\HP_perf3par
> INFO [06/14/16 13:57:24:75] Begin: Loading version variables from disk cache
>   INFO [06/14/16 13:57:24:79] Cache file C:\Code\STOR\HP_perf3par\.git\gitversion_cache\BDA54518C80AA1AAB4A7F1BF077C50F5E72D7967.yml not found.
> INFO [06/14/16 13:57:24:79] End: Loading version variables from disk cache (Took: 41.02ms)
> INFO [06/14/16 13:57:24:81] Using latest commit on specified branch
> INFO [06/14/16 13:57:24:89] Running against branch: master (94245cf7f44580da27e2cc213fdc9f625b5d6ec7)
> INFO [06/14/16 13:57:24:92] 0 commits found between 94245cf7f44580da27e2cc213fdc9f625b5d6ec7 and 94245cf7f44580da27e2cc213fdc9f625b5d6ec7
> INFO [06/14/16 13:57:24:94] Begin: Calculating base versions
>   INFO [06/14/16 13:57:24:99] Fallback base version: 0.1.0 with commit count source 2ea14edb6a0442787332b426810d02ca99317ef8
>   INFO [06/14/16 13:57:25:08] Git tag 'v1.2.0': 1.2.0 with commit count source 94245cf7f44580da27e2cc213fdc9f625b5d6ec7
>   INFO [06/14/16 13:57:25:09] Git tag 'v1.1.0': 1.1.0 with commit count source f95af1d35cbf3f1880a59cc6e21aea263421fe36
>   **INFO [06/14/16 13:57:25:15] Base version used: Git tag 'v1.2.0': 1.2.0 with commit count source 94245cf7f44580da27e2cc213fdc9f625b5d6ec7**
> INFO [06/14/16 13:57:25:15] End: Calculating base versions (Took: 216.24ms)
> INFO [06/14/16 13:57:25:16] Skipping version increment
> INFO [06/14/16 13:57:25:17] 0 commits found between 94245cf7f44580da27e2cc213fdc9f625b5d6ec7 and 94245cf7f44580da27e2cc213fdc9f625b5d6ec7
> INFO [06/14/16 13:57:25:19] Begin: Creating dictionary
> INFO [06/14/16 13:57:25:20] End: Creating dictionary (Took: 6.22ms)
> INFO [06/14/16 13:57:25:20] Begin: Storing version variables to cache file C:\Code\STOR\HP_perf3par\.git\gitversion_cache\BDA54518C80AA1AAB4A7F1BF077C50F5E72D7967.yml
> INFO [06/14/16 13:57:25:28] End: Storing version variables to cache file C:\Code\STOR\HP_perf3par\.git\gitversion_cache\BDA54518C80AA1AAB4A7F1BF077C50F5E72D7967.yml (Took: 87.52ms)

**Comment by pascalberger** [comment]
See [Known limitations](https://gitversion.readthedocs.io/en/latest/build-server-support/build-server/tfs-build-vnext/):

You need to make sure that all tags are fetched for the Git repository, otherwise you may end with wrong versions (e.g. `FullSemVer` like `1.2.0+5` instead of `1.2.0` for tagged releases) 
Just checking the `Clean Repository` check box in the build definition settings might not be enough since this will run a `git clean -fdx/reset --hard` without fetching all tags later. 
You can force deletion of the whole folder and a re-clone containing all tags by settings the variable `Build.Clean` to `all`.
This will take more time during build but makes sure that all tags are fetched.
In the future it is planned to allow using `git.exe` instead of current `libgit2sharp` for syncing the repos which might allow other possibilities to solve this issue. 
For details see this [GitHub issue](https://github.com/Microsoft/vso-agent-tasks/issues/1218).

**Comment by Pitterling** [comment]
@pascalberger thx. I added

Build.Clean = source

**Comment by pkiers** [comment]
Hi,

After a month of  journey I went back home, it was a lovely journey, take a look at some photos of it  <http://fact.snehankur.org/e2twl>

All best, p.kiers@home.nl
