### ISSUE TITLE
How do gaps in version numbers defeat the purpose of SemVer?

### ISSUE THREAD

**Issue by eatdrinksleepcode** [GitTools/GitVersion#904]
The GitVersion docs about [Version Incrementing](http://gitversion.readthedocs.io/en/latest/more-info/version-increments/) include what is to me a rather odd statement:

> Bumping one of the version components by more than 1 in a single release means you will have gaps in your version number, which defeats the purpose of SemVer.

I am confused as to how gaps in a version number defeat the purpose of SemVer. I can't find anything in the SemVer spec about _sequential_ version numbers; all I see is about _increasing_ version numbers.

I am asking because the desire to prevent gaps in version numbers seems to have driven a number of design decisions in GitVersion that make certain scenarios problematic (I think #889 is an example of this).

**Comment by JakeGinnivan** [comment]
Probably the wording is a little strong. But SemVer is about communication, if there are gaps it means that the version number has been increased but not released. To me that communicates that that release had bugs in it which caused it to fail in testing or some other part of the pipeline after the build artifacts were created.

If you are simply using SemVer for binary compatibility then yep, having gaps doesn't really matter.

**Comment by JakeGinnivan** [comment]
The way we are doing incrementing in continuous delivery mode takes inspiration from http://www.xavierdecoster.com/semantic-versioning-auto-incremented-nuget-package-versions

**Comment by JakeGinnivan** [comment]
Closing this as the discussion seems to have stopped.
