### ISSUE TITLE
ContinuousDeployment doesn't update NugetVersion for Pull Request updates?

### ISSUE THREAD

**Issue by Ashtonian** [GitTools/GitVersion#910]
We have a repo in ContinousDeployment mode and would like our PullReqeusts to produce packages that are differentiated so that the other tooling can detect changes appropriately.  

our gitversion is simply: 
```yaml
mode: ContinuousDeployment
branches: {}
```

right now we get: 
```
GitVersion.FullSemVer 0.1.0-PullRequest.5+1398
GitVersion.NuGetVersion 0.1.0-pullrequest0005
```
and 
```
GitVersion.FullSemVer 0.1.0-PullRequest.5+1399
GitVersion.NuGetVersion 0.1.0-pullrequest0005
```

Notice that the nuget version doesn't iterate. I tried using the FullSemVer and it broke as that is not a nuget compatible package version.

**Comment by Ashtonian** [comment]
not sure if this is related/fixed by https://github.com/GitTools/GitVersion/pull/906

**Comment by simonejsing** [comment]
Yes, this is the same issue we were facing. I'm waiting for Jake to sign off and get the fix merged.

**Comment by JakeGinnivan** [comment]
Hey, sorry about the delay. Have been converting a bunch of OSS projects to Core CLR and setting up better release pipelines so other ppl can release. Am trying to get back here soon

**Comment by simonejsing** [comment]
PR #906 has now been merged into master. It fixes this issue so I suggest you try it out and close this issue if it resolves your problem.

**Comment by JakeGinnivan** [comment]
This should be sorted by the next release. Closing. Post here or open another issue if it's still an issue after the next release
