### ISSUE TITLE
/updateassemblyinfo should ignore comments

### ISSUE THREAD

**Issue by pascalberger** [GitTools/GitVersion#929]
Consider the following content in an `assemblyinfo.cs` file:

```
// Version information for an assembly consists of the following four values:
//
//      Major Version
//      Minor Version 
//      Build Number
//      Revision
//
// You can specify all the values or you can default the Build and Revision Numbers 
// by using the '*' as shown below:
// [assembly: AssemblyVersion("1.0.*")]
```

After running `gitversion.exe /updateassemblyinfo` `AssemblyInformationalVersion` and `AssemblyFileVersion` are added. But not `AssemblyVersion`. Instead the comment containing the AssemblyVersion string is updated:

```
// Version information for an assembly consists of the following four values:
//
//      Major Version
//      Minor Version 
//      Build Number
//      Revision
//
// You can specify all the values or you can default the Build and Revision Numbers 
// by using the '*' as shown below:
// [assembly: AssemblyVersion("0.1.0.0")]
[assembly: AssemblyInformationalVersion("0.1.0-unstable.2+Branch.develop.Sha.6c7642d7f8cd06f334b21595d44e9e68bc243dec")]
[assembly: AssemblyFileVersion("0.1.0.0")]
```

Comments should be ignored by `/updateassemblyinfo`.

**Comment by tofutim** [comment]
yeah, I noticed this recently too

**Comment by asbjornu** [comment]
@tofutim You should only need GitVersionTask if all you want to do is version stamp your assemblies. If you need to expose the version number to the build process for other purposes, you unfortunately need `GitVersion.exe` until #983 is implemented.
