### ISSUE TITLE
choco 3.6 update?

### ISSUE THREAD

**Issue by tofutim** [GitTools/GitVersion#936]
Hi any chance of getting a chocolately release of 3.6?

**Comment by gep13** [comment]
@JakeGinnivan was this one of the "issues" that you saw during the deployment? Should we manually push the choco package?

**Comment by JakeGinnivan** [comment]
Yeah, wanted to do it yesterday got swamped. The only thing which happened was the GitHub release.

NuGet/Chocolatey pushed, getting the gem and VSTS Task done now. Sorry about that :)

**Comment by tofutim** [comment]
Thank you so much!
