### ISSUE TITLE
GitVersion not allowing me to specify next version / ignoring config file

### ISSUE THREAD

**Issue by TAGC** [GitTools/GitVersion#937]
I have a repository where my last release is 0.4.1 and I'm currently on the "develop" branch. When I run `GitVersion.exe -showvariable NugetVersionV2` it returns `0.5.0-unstable0006`.

However, I intend for the next release to be 0.4.2 and would like GitVersion to return `0.4.2-unstable0006`.

I've read the documentation and tried several things to rectify this:
 - amending my last commit on the develop branch to include "+semver; fix"
 - creating a `GitVersion.yml` (and `GitVersionConfig.yml`) file with `next-version` set to 0.4.2
 - playing around with ContinuousDelivery/ContinuousDeployment settings

None of these changes seemed to work. I then tried something really basic:

```
branches:
  dev(elop)?(ment)?$:
    increment: Major
```
Even then it still returns `0.5.0-unstable0006`. It's like it's completely ignoring all commit messages/configuration settings. Nothing I've done has changed it from returning the same version string.

Here's my current configuration:

```
$ GitVersion.exe -showconfig
assembly-versioning-scheme: MajorMinorPatch
mode: ContinuousDelivery
tag-prefix: '[vV]'
continuous-delivery-fallback-tag: ci
major-version-bump-message: '\+semver:\s?(breaking|major)'
minor-version-bump-message: '\+semver:\s?(feature|minor)'
patch-version-bump-message: '\+semver:\s?(fix|patch)'
legacy-semver-padding: 4
build-metadata-padding: 4
commits-since-version-source-padding: 4
commit-message-incrementing: Enabled
branches:
  dev(elop)?(ment)?$:
    mode: ContinuousDeployment
    tag: unstable
    increment: Major
    prevent-increment-of-merged-branch-version: false
    track-merge-target: true
  master:
    mode: ContinuousDelivery
    tag:
    increment: Patch
    prevent-increment-of-merged-branch-version: true
    track-merge-target: false
  releases?[/-]:
    mode: ContinuousDelivery
    tag: beta
    increment: Patch
    prevent-increment-of-merged-branch-version: true
    track-merge-target: false
  features?[/-]:
    mode: ContinuousDelivery
    tag: useBranchName
    increment: Inherit
    prevent-increment-of-merged-branch-version: false
    track-merge-target: false
  (pull|pull\-requests|pr)[/-]:
    mode: ContinuousDelivery
    tag: PullRequest
    increment: Inherit
    prevent-increment-of-merged-branch-version: false
    tag-number-pattern: '[/-](?<number>\d+)[-/]'
    track-merge-target: false
  hotfix(es)?[/-]:
    mode: ContinuousDelivery
    tag: beta
    increment: Patch
    prevent-increment-of-merged-branch-version: false
    track-merge-target: false
  support[/-]:
    mode: ContinuousDelivery
    tag:
    increment: Patch
    prevent-increment-of-merged-branch-version: true
    track-merge-target: false
```

**Comment by gep13** [comment]
@TAGC depending on what version of GitVersion you are using, you might have to clear out the gitversion cache folder.  After making modifications to the configuration, it is a "best practice" to always do this.

You can find this folder in the `.git\gitversion_cache` folder in your repo.

**Comment by TAGC** [comment]
Cheers for the reply.

I checked and found I was using an outdated version. I upgraded from version 3.4.4(?) to 3.6.0. I tried running `gfv init` to generate a config file that I could play around with and *this time* I could see the changes I was making being reflected with `gfv -showconfig`. Not sure why the update would change this as running `gitversion -help` with version 3.4.4 still says it will look at config options in a file called `GitVersion.yml` (possible bug?).

It was still giving me back `0.5.0-unstable0006` until I read your comment and deleted `gitversion_cache`, and now it's also giving me back a version string based on what I've configured in the YAML file.

However, it's still not respecting commit messages:

```
$ git lg -n 2 && gfv -showvariable NugetVersionV2
* e8b5f2f - (2 hours ago) +semver: fix TESTWEB-138 - <<TAGC>> (HEAD -> develop)
*   a759f3e - (3 weeks ago) Merge tag 'v0.4.1' into develop - <<TAGC>> (origin/develop)
|\
0.5.0-unstable0006
```

**Comment by TAGC** [comment]
Oh, this works:

```
$ git lg -n 2 && gfv -showvariable NugetVersionV2
* 72daa3a - (2 hours ago) TESTWEB-138 +semver: fix - <<TAGC>> (HEAD -> develop)
*   a759f3e - (3 weeks ago) Merge tag 'v0.4.1' into develop - <<TAGC> (origin/develop)
|\
0.4.2-unstable0003
```

I'd tried playing around with the location of "+semver: fix" (as well as seeing what happens if I omit the space) including this variation, but that was back with GitVersion 3.4.4(?) which I guess doesn't support checking commits.

I'm not sure why it can't work the original way since `\+semver:\s?(breaking|major)'` seems like it should match "+semver: fix" anywhere it appears (it doesn't have $ at the end), but it's not much of an issue.
