### ISSUE TITLE
how to call GitVersion /output buildserver and is it necessary?

### ISSUE THREAD

**Issue by PeterVermont** [GitTools/GitVersion#938]
I am using Jenkins. In the docs https://gitversion.readthedocs.io/en/latest/build-server-support/build-server/jenkins/ it says:

> Add an Execute Windows batch command build step with Command:  gitversion /output buildserver
> Add an Inject environment variables build step and use value 'gitversion.properties' for the Properties File Path parameter
> **This assumes GitVersion.exe is available on the command line.**

Why would GitVersion be on the command line? In my case it is installed by nuget and the path to it is changed with every version update (example relative to solution: packages\GitVersion.CommandLine.3.6.0\tools\GitVersion.exe)

All of this seems a little strange - I can see from the log that GitVersion detects it is running under Jenkins -- is there a way to get it to just automatically inject the environmental variables? If so, how do I configure this?

Thanks for your patience with a simple issue!

**Comment by tpluscode** [comment]
Are you using GetVersionTask? It sets variables and patches assembly infos automatically

**Comment by PeterVermont** [comment]
Thanks for responding.

I am using GitVersionTask and it does update the assembly info without problem. The issue is that I would like Jenkins to use the version information (in place of / in addition to) the build number. Following the docs I have to add several steps -- call gitversion /output buildserver which produces a file gitversion.properties and then a separate plugin called 'EnvInject' to read the gitversion.properties.

Calling gitversion is problematic since I do not wish to hard-code the path/version of gitversion into my jenkins job.

For now I have hard-coded the relative path to gitversion and I can see that the git variables are getting into the build environment but Jenkins doesn't seem to do anything with them.

**Comment by tpluscode** [comment]
Oh I remember using GitVersionTask with Jenkins in the past for a short while. Indeed it doesn't work that easily out of the box. We also ended up using EnvInject plugin. It is the method described on [GitVersion docs](https://gitversion.readthedocs.io/en/latest/build-server-support/build-server/jenkins/) after all.

I think it's a limitation of Jenkins. With TeamCity for example the MSBuild task sets environment variables which can be readily used in the build.

**Comment by PeterVermont** [comment]
Do you use TeamCity instead of Jenkins?

**Comment by tpluscode** [comment]
I do. We used Jenkins in a previous project.

**Comment by JakeGinnivan** [comment]
Yeah, there is no way to set environmental variables directly in Jenkins. GitVersion will write out the gitversion.properties file which you need to import with the EnvInject plugin as @tpluscode said.

**Comment by JakeGinnivan** [comment]
The docs are a little misleading, they could probably be re-written to just say run GitVersion rather than specifying the command line because that assumes you are using the exe.

**Comment by asbjornu** [comment]
If anyone wants to clarify the documentation, please submit a PR. Closing.
