### ISSUE TITLE
##teamcity[<messageName> name1='value1'] value1 needs to be escaped

### ISSUE THREAD

**Issue by johnsimons** [GitTools/GitVersion#94]
The following error is reported by TC when trying to:

```
[WriteVersionInfoToBuildLog] ##teamcity[setParameter name='GitFlowVersion.LongVersion' value='0.8.0-unstable568 Branch:'develop' Sha:'ee69bff1087ebc95c6b43aa2124bd58f5722e0cb'']
[WriteVersionInfoToBuildLog] Property value not found
Valid property list format is (name( )*=( )*'escaped_value'( )*)* where escape symbol is "|" 
```

For escaped values, TeamCity uses a vertical bar "|" as an escape character. In order to have certain characters properly interpreted by the TeamCity server they must be preceded by a vertical bar. 

Character    Should be escaped as:

<table class="confluenceTable"><tbody>
<tr>
<td class="confluenceTd"> Character </td>
<td class="confluenceTd"> Should be escaped as </td>
</tr>
<tr>
<td class="confluenceTd"> ' (apostrophe) </td>
<td class="confluenceTd"> |' </td>
</tr>
<tr>
<td class="confluenceTd"> \n (line feed) </td>
<td class="confluenceTd"> |n </td>
</tr>
<tr>
<td class="confluenceTd"> \r (carriage return) </td>
<td class="confluenceTd"> |r </td>
</tr>
<tr>
<td class="confluenceTd"> \uNNNN (unicode symbol with code 0xNNNN) </td>
<td class="confluenceTd"> |0xNNNN </td>
</tr>
<tr>
<td class="confluenceTd"> | (vertical bar) </td>
<td class="confluenceTd"> || </td>
</tr>
<tr>
<td class="confluenceTd"> [ (opening bracket) </td>
<td class="confluenceTd"> |[ </td>
</tr>
<tr>
<td class="confluenceTd"> ] (closing bracket) </td>
<td class="confluenceTd"> |] </td>
</tr>
</tbody></table>

**Comment by sandipgudmewar** [comment]
I have facing the issue at execution of job in team city it shows the following error message " Incorrect property name.Valid property list format is (name( )=( )'escaped_value'( )) where escape symbol is "|" "

Please suggest me the solution and steps where we need to update the setting.
