### ISSUE TITLE
Help needed: Ruby Gem deployment

### ISSUE THREAD

**Issue by JakeGinnivan** [GitTools/GitVersion#940]
I can't figure out how to simply pass an API key to the `gem push`. It seems I need to add it to a config file then refer to that via the command line.

My deployment script looks like this:

```
    var returnCode = StartProcess("cmd", new ProcessSettings
    {
        Arguments = " /c gem push ./releaseArtifacts/" + artifactLookup["GemBuild"] + " --key " + EnvironmentVariable("GemApiKey") + " && exit 0 || exit 1"
    });
```

I got the `GemApiKey` from my ruby config on my machine I was manually pushing from before. Will leave this as an up for grabs, the gem won't be updated until this is solved (it is already out of date at the moment :()

**Comment by gep13** [comment]
@JakeGinnivan hmm, I might need to look at this, as I have started creating a Gem Addin for Cake:

https://github.com/gep13/Cake.Gem

I will let you know if I come up with anything.

**Comment by gep13** [comment]
@JakeGinnivan I think I have this figured out now.  To say that it isn't immediately obvious would be an understatement.  I will confirm that everything is working the way I think it is, and then I will get back to you here.

**Comment by gep13** [comment]
@JakeGinnivan ok, fairly sure that you are running into the same thing that I was running into.  Namely that we assumed that the `key` property was actually the API key that you get from the Profile page on rubygems.org.  This isn't what is required.  Instead, it wants the name of the entry in the `.gem\credentials` file, which you can download from rubygems.org after providing your user name and password.  This is/was completely counter-intuitive to me, but I was eventually able to figure it out.

I have just pushed out version 0.2.0 of the Cake.Gem addin, which is documented here:

http://cakegem.readthedocs.io/en/develop/usage/

And once Cake 0.16.0 ships, I would suggest switching the GitVersion deploy.cake to use this.

Let me know what you think.
