### ISSUE TITLE
GitVersion CommandLine doesn't show its own version number

### ISSUE THREAD

**Issue by onovotny** [GitTools/GitVersion#947]
When running `GitVersion /?`, the output text doesn't show what the version is of GitVersion itself.

Running `GitVersion /?` and `GitVersion /l` should display the GitVersion version somewhere.

**Comment by gep13** [comment]
@onovotny no, but the exe is stamped with the full semantic version :wink: 

![image](https://cloud.githubusercontent.com/assets/1271146/16874694/a4af6aa4-4a92-11e6-90a2-5268d4101fdb.png)

You are right though, I think we need to include the version in the output.  Perhaps also include the `-v` and `--version` switch, similar to other tools.

**Comment by onovotny** [comment]
Yep...when in the path though via things like chocolatey, I can't easily right-click the file to find the properties :)

**Comment by gep13** [comment]
>@onovotny said...
Yep...when in the path though via things like chocolatey, I can't easily right-click the file to find the properties :)

Yip, understood.  Would you be in a position to submit a PR for getting this included?  Would be happy to accept it.

**Comment by pkiers** [comment]
Dear friend! 

I found the last catalogue of you favourite stuff, you  can  read it here <http://head.its-s.net/e6rgab>

All the best, p.kiers

**Comment by pkiers** [comment]
Hello, 


Just wanted  to  say hi and ask  how  you're doing? I'm OK, you may  read my latest  article here <http://oscar.stacybontis.com/e6hccmpq>

Cheers, p.kiers

**Comment by kjjuno** [comment]
I can take this on. Will you assign it to me?

**Comment by ghuntley** [comment]
Experienced this today. Thanks for taking this up @kjjuno <3
