### ISSUE TITLE
Is it possible to use for package that only contains simple file

### ISSUE THREAD

**Issue by tebeco** [GitTools/GitVersion#948]
Hi,

We're using GitVersionTask to version nuget packages for C# project for some project.
I've just discovered a package that only contains "*.Proto" files, no assembly/source code or whatever.

Can you confirm me that I could use GitVersion to easilly use it the (almost) same way to version this kind of packages over nuspec / nexus etc ....

**Comment by gep13** [comment]
@tebeco sorry, I am not sure I follow what you are asking.  Can you elaborate, or provide an example?

**Comment by JakeGinnivan** [comment]
As long as there is a .csproj file then yeah it should work fine. If not you can still fall back to the command line version.

But as @gep13 said, unsure exactly the question so going to close this until we get clarification?

**Comment by tebeco** [comment]
We are versioning .proto file only on git
Just like a simple zip of file (but in a nuget) for front app

No csproj or whatever, there's no workaround with am msbuild file or something else?

**Comment by asbjornu** [comment]
@tebeco You can use [GitVersion.exe](https://chocolatey.org/packages/GitVersion.Portable) to retrieve a version number that you then can use in your build script. Read [the documentation for the command line interface](http://gitversion.readthedocs.io/en/latest/usage/command-line/) to figure out how.
