### ISSUE TITLE
Cannot get dynamic repository to work

### ISSUE THREAD

**Issue by tpluscode** [GitTools/GitVersion#953]
Dynamic repository doesn't work for me with version 3.6.1 (installed GitVersion.Portable from Choco). Below is my command and output. As you see I'm running TC on Windows

```
[Step 1/4] Starting: C:\Windows\system32\cmd.exe /c gitversion /url https://bitbucket.org/*** /u buildsvr /p ******* /b refs/heads/XYZ /c 5a078f3ab356914a9ae9ff5c69146e6663c1c9f3 /output buildserver /updateassemblyinfo
[08:31:08][Step 1/4] in directory: C:\TeamCity\buildAgent_2\work\f18fd9d2d9018dcf
INFO [07/18/16 8:31:09:11] Working directory: C:\TeamCity\buildAgent_2\work\f18fd9d2d9018dcf
INFO [07/18/16 8:31:09:11] IsDynamicGitRepository: False
ERROR [07/18/16 8:31:09:16] An unexpected error occurred:
System.IO.DirectoryNotFoundException: Can't find the .git directory in C:\TeamCity\buildAgent_2\work\f18fd9d2d9018dcf
   at GitVersion.GitPreparer.GetDotGitDirectory()
   at GitVersion.GitPreparer.GetProjectRootDirectory()
   at GitVersion.ConfigurationProvider.Verify(GitPreparer gitPreparer, IFileSystem fileSystem)
   at GitVersion.Program.VerifyArgumentsAndRun()
INFO [07/18/16 8:31:09:16] 
INFO [07/18/16 8:31:09:16] Attempting to show the current git graph (please include in issue): 
INFO [07/18/16 8:31:09:16] Showing max of 100 commits
INFO [07/18/16 8:31:09:26] ERROR: fatal: Not a git repository (or any of the parent directories): .git

INFO [07/18/16 8:31:09:11] Working directory: C:\TeamCity\buildAgent_2\work\f18fd9d2d9018dcf
INFO [07/18/16 8:31:09:11] IsDynamicGitRepository: False
ERROR [07/18/16 8:31:09:16] An unexpected error occurred:
System.IO.DirectoryNotFoundException: Can't find the .git directory in C:\TeamCity\buildAgent_2\work\f18fd9d2d9018dcf
   at GitVersion.GitPreparer.GetDotGitDirectory()
   at GitVersion.GitPreparer.GetProjectRootDirectory()
   at GitVersion.ConfigurationProvider.Verify(GitPreparer gitPreparer, IFileSystem fileSystem)
   at GitVersion.Program.VerifyArgumentsAndRun()
INFO [07/18/16 8:31:09:16] 
INFO [07/18/16 8:31:09:16] Attempting to show the current git graph (please include in issue): 
INFO [07/18/16 8:31:09:16] Showing max of 100 commits
INFO [07/18/16 8:31:09:26] ERROR: fatal: Not a git repository (or any of the parent directories): .git

Process exited with code 1
Step GitVersion (Command Line) failed
```

Note the **IsDynamicGitRepository: False**. Why is that?

**Comment by sergiorykov** [comment]
>  Can't find the .git directory in C:\TeamCity\buildAgent_2\work\f18fd9d2d9018dcf
It seems you've been using VCS checkout mode 'Automatically on server'. In that case TC sends on agent only sources without '.git' directory. 
Set mode 'Automatically on agent' with Uploaded ssh key and GitVersion will be able to work on agent.

**Comment by tpluscode** [comment]
Thanks for replying. Yes, I'm using sever checkout - we've had issues with agent-checkout and BitBucket. Hence the [dynamic repository feature](https://gitversion.readthedocs.io/en/latest/more-info/dynamic-repositories/), which should help but doesn't work, at least with 3.6.1

I downgraded to an older version, namely 3.1.2 and dynamic repos work fine

**Comment by JackFrostStudios** [comment]
Hey Guys, This might shed a bit of light on this issue, we were having issues with dynamic repositories and when 3.6.1 came out we also ran into this issue.

It looks like when git Version is first run it needs the .git file in the location it is run and only after this does it check out the repository itself:

> Running: C:\ProgramData\Chocolatey\bin\gitversion.exe "T:\work\cd8b39b3c774c551" /url '****' /b 'refs/heads/release/1.3' /u '****' /p '*****' /output 'buildserver'
> [12:17:05][Step 1/1] INFO [07/19/16 12:17:05:29] Working directory: T:\work\cd8b39b3c774c551
> [12:17:05][Step 1/1] INFO [07/19/16 12:17:05:31] IsDynamicGitRepository: False
> [12:17:05][Step 1/1] INFO [07/19/16 12:17:05:35] Returning Project Root from DotGitDirectory: T:\work\cd8b39b3c774c551\.git - T:\work\cd8b39b3c774c551
> [12:17:05][Step 1/1] INFO [07/19/16 12:17:05:37] Running on Windows.
> [12:17:05][Step 1/1] INFO [07/19/16 12:17:05:39] Applicable build agent found: 'TeamCity'.
> [12:17:05][Step 1/1] INFO [07/19/16 12:17:05:40] Branch from build environment: refs/heads/release/1.3
> [12:17:05][Step 1/1] INFO [07/19/16 12:17:05:40] Creating dynamic repository at 'T:\TeamCity-BuildAgent\temp\buildTmp\***'
> [12:17:05][Step 1/1] INFO [07/19/16 12:17:05:41] Setting up credentials using name '***'
> [12:17:05][Step 1/1] INFO [07/19/16 12:17:05:41] Retrieving git info from url '*****'
> [12:17:43][Step 1/1] INFO [07/19/16 12:17:43:32] Returned path after repository clone: T:\TeamCity-BuildAgent\temp\buildTmp\****\.git\
> [12:17:50][Step 1/1] INFO [07/19/16 12:17:50:39] IsDynamicGitRepository: True

As you can see IsDynamicGitRepository is set to false initially but then it is set to true later. This works on our machines as we can enable agent checkout but if on server checkout it falls over like the above comments.

**Comment by JackFrostStudios** [comment]
@tpluscode as a note you should be able to use 3.6.0 if you want.

**Comment by rubenmamo** [comment]
I hadn't noticed this issue and created #981 on the same issue. I closed that since it's a duplicate.

The problem is with the way GitPreparer is being used in the configuration verification code as it is creating a new instance of GitPreparer and using without calling Initialise.

@asbjornu @JakeGinnivan , the GitPreparer class seems to be causing a number of recurring issues when changes are done since it seems to not be obvious that Initialise needs to be called in order for it to function correctly. Can we change the class so that if you try to use any of it's methods without calling the Initialise method first it throws an exception? This would cause tests to fail whenever GitPreparer is used incorrectly and hence avoid the recurrence of similar issues.

I'm happy to do the change in GitPreparer myself if you agree this is a good way forward.

**Comment by asbjornu** [comment]
@rubenmamo If it is indeed so that `Initialize()` needs to be invoked for any of `GitPreparer`'s methods to work, I think it would be better to just do the initialization in the constructor (and make the class non-`static`) or lazily before any of its methods are used.

Or are there any use-cases where `GitPreparer` is used where initializing would break anything?

**Comment by rubenmamo** [comment]
Unfortunately I'm not sure of all the possible use cases for GitPreparer, however the initialise method accepts parameters which alter the behaviour of the class and hence I'm not 100% sure that it would be correct to initialise these variables in the constructor.

The constructor contract is as follows:
```public GitPreparer(string targetUrl, string dynamicRepositoryLocation, Authentication authentication, bool noFetch, string targetPath)```

and the Initialise method contract is as follows:
```public void Initialise(bool normaliseGitDirectory, string currentBranch)```

The Initialise method is responsible for normalising the directory and to generate the dynamic repository if this is required. If the app is using dynamic repositories, the app will crash if Initialise is not called before using GitPreparer.

The class was created by @JakeGinnivan , maybe he can shed some light on this and give us his opinion?

**Comment by JakeGinnivan** [comment]
This just sounds like the bug is that if you run gitversion outside a git repo specifying a dynamic repo that it crashes. Should be pretty easy to verify locally. Just run GitVersion from somewhere using the same command lines and see if it crashes. If so we need to ensure that we init the dynamic repo and use it before trying to find the git repo relative to the working directory

**Comment by GeertvanHorrik** [comment]
I am having the same issue:

```
Parameters 
Working Directory: C:\CI_WS\Ws\96874\Source\Catel 
Executable: C:\Tools\GitVersion\GitVersion.exe
Arguments: /url https://github.com/Catel/Catel /b hotfix/4.5.4 /c c98430cdd75733f4ebdd1a41030bb0d3c088e619 /output buildserver
Environment Variables 
INFO [10/11/16 11:24:25:38] Working directory: C:\CI_WS\Ws\96874\Source\Catel 
INFO [10/11/16 11:24:25:38] IsDynamicGitRepository: False
ERROR [10/11/16 11:24:25:40] An unexpected error occurred: 
System.IO.DirectoryNotFoundException: Can't find the .git directory in C:\CI_WS\Ws\96874\Source\Catel 
at GitVersion.GitPreparer.GetDotGitDirectory()
at GitVersion.GitPreparer.GetProjectRootDirectory()
at GitVersion.ConfigurationProvider.Verify(GitPreparer gitPreparer, IFileSystem fileSystem)
at GitVersion.Program.VerifyArgumentsAndRun()
INFO [10/11/16 11:24:25:40] 
INFO [10/11/16 11:24:25:40] Attempting to show the current git graph (please include in issue): 
INFO [10/11/16 11:24:25:40] Showing max of 100 commits
INFO [10/11/16 11:24:25:44] ERROR: fatal: Not a git repository (or any of the parent directories): .git
```

**Comment by GeertvanHorrik** [comment]
Both 3.6.4 and 4.0 (beta 7) are broken. Going to investigate when this was introduced.

**Comment by GeertvanHorrik** [comment]
3.5.4 is also broken.

**Comment by rubenmamo** [comment]
@GeertvanHorrik it's been there for a while now. If I'm not mistaken, I had done a change to fix this but there was a side effect on something else and the issue was reintroduced.
#782 #874 are related to this

**Comment by GeertvanHorrik** [comment]
3.2.0 seems to work. I will see if I can find some time next week to try and fix this issue.

**Comment by rubenmamo** [comment]
@GeertvanHorrik I had found the cause of the problem (refer to [https://github.com/GitTools/GitVersion/issues/953#issuecomment-238221291]) however I'm not sure of the best way to solve this.

**Comment by GeertvanHorrik** [comment]
Writing unit tests for this now. It looks like dynamic repositories are inside GitVersion. Why is it not using the tooling from GitTools.Core @JakeGinnivan ?

**Comment by GeertvanHorrik** [comment]
I've fixed the issues, but it requires a new version of GitTools.Core.

**Comment by GeertvanHorrik** [comment]
![image](https://cloud.githubusercontent.com/assets/1246444/19766600/15a71820-9c4f-11e6-82db-6970e52a0f61.png)

**Comment by JakeGinnivan** [comment]
@GeertvanHorrik because nobody ended up switching it over fully unfortunately.

**Comment by brazilbean** [comment]
Any update on the status of this fix? 

I'm trying to use the TeamCity GitVersion meta-runner, which installs the latest version of GitVersion automatically, making it tricky to downgrade to a working version in the meantime. :P

**Comment by brazilbean** [comment]
Got agent checkout working, so we have a workaround for now. Keep up the good work!
