### ISSUE TITLE
Merge commit message as a base version

### ISSUE THREAD

**Issue by rostg** [GitTools/GitVersion#954]
When gitversion uses merge commit messages to find a base version, it finds the latest one and uses this commit for a base version. Please consider the following scenario:

1. Create a release branch out of develop branch - say, release/1.0.0
2. Commit a fix on release/1.0.0 branch
3. Merge release/1.0.0 branch back to develop.
4. Now, on develop branch gitversion will take this commit as a base version, bump minor version and will start counting the number of commits from that point.
5. Let's say you made 10 commits on develop, gitversion will come up with the version number 1.1.0+10
6. Commit one more fix on release/1.0.0 and merge it back to develop.
7. Gitversion will use this, the most recent commit with merge message, and reset commit count

So, my question is - do I understand this process correctly? Should gitversion find the earliest merge message with the same version number (1.0.0 in our scenario) and use that commit as a base version?

And one more question. Is there a way to disable using merge messages as version bases?

Thanks a lot!

**Comment by gep13** [comment]
@rostg are you following a particular branching strategy, similar to GitFlow?  If so, once the release branch was merged, you should be closing it, no?  As a result, I don't see how other commits would be added to it.

**Comment by rostg** [comment]
We create a release branch and deploy it to the Test environment for testing. As QA guys find bugs we fix them on the release branch and merge the fixes back to develop at the same time so that the develop branch always has those fixes. Once there are no more bugs and we are ready to deploy to production, we tag release branch, merge it back to develop and master, and delete it. As you see, there are multiple merges of the release branch to develop during the release branch's lifecycle.

**Comment by JakeGinnivan** [comment]
Can you try v4 beta. It fixed a heap of commit counting bugs

**Comment by rostg** [comment]
Thank you, Jake! This issue has been addressed in v4 beta1.
