### ISSUE TITLE
Introduce Verbose/Debug logging level

### ISSUE THREAD

**Issue by JakeGinnivan** [GitTools/GitVersion#955]
We are adding more and more logging in and often I want less info. We should create another logging level and enable it with a --debug switch or a config setting?

**Comment by asbjornu** [comment]
We should at least have this as a command line switch, so it's easy to have the applied logging level in tools using GitVersion, such as Cake, cascade down into GitVersion.

**Comment by gep13** [comment]
@asbjornu yes, this would make sense to me :+1:
