### ISSUE TITLE
commits-before syntax

### ISSUE THREAD

**Issue by sergey-s-betke** [GitTools/GitVersion#956]
I need set `commit-before`. But 

    ignore:
      commits-before: 7fab613

gives GitVersion error. `[7fab613]`, `'[7fab613]'`, `'7fab613'` - the same errors... Please, show one example for `commits-before` syntax!

**Comment by pascalberger** [comment]
`commits-before` should be a date. See [here](https://github.com/GitTools/GitVersion/blob/6a28b873b3c3b6a8f59baac7bde77a1f85f161cf/src/GitVersionCore.Tests/Configuration/IgnoreConfigTests.cs#L19) for an example.

    commits-before: 2015-10-23T12:23:15

**Comment by pascalberger** [comment]
@sergey-s-betke I created a PR which improves documentation: #976. Does this solve your question?

**Comment by sergey-s-betke** [comment]
Yes, @pascalberger , it is enough.
