### ISSUE TITLE
GitVersionTask caching possible?

### ISSUE THREAD

**Issue by tofutim** [GitTools/GitVersion#963]
I have a Visual Studio solution with maybe 12-13 projects, each one with GitVersionTask. Normally it isn't too bad but in CI (TeamCity) each GitVersionTask takes a long time to run. Is there a way to run GitVersionTask once to get the number and just update all the assemblies with that number? Recomputing seems overkill. Also this is a tagged build, e.g., 8.0.785 - so why is it taking so long to go through the repository (which admittedly is large). Any tips or workarounds much appreciated.

**Comment by pascalberger** [comment]
Which version are you using? There seems to be an issue introduced in 3.6.0 (see #942)

**Comment by tofutim** [comment]
I am using 3.6.0 and I did get the feeling it was faster before. I'll check
the issue.

**Comment by JakeGinnivan** [comment]
Roll back to 3.5.4 and it should fix your issue for the moment. Hope to get a fix out soon.

**Comment by asbjornu** [comment]
Just for brevity, this was fixed in #969.
