### ISSUE TITLE
When assembly-versioning-scheme is set to none, AssemblyInfoBulider should not emit AssemblyVersion attribute

### ISSUE THREAD

**Issue by cortex93** [GitTools/GitVersion#964]
Would it be possible that GitVersionTask do not write AssemblyVersion when assembly-versioning-scheme is set to none.
Actually, it writes `[assembly: AssemblyVersion("")]` which is not valid. It is not possible to add it's own AssemblyVersion attribute either as it will conflict.

Having the AssemblyInfoBuilder build the assemblyfile with only one format string does not allow opt-in/opt-out of version attribute.

**Comment by asbjornu** [comment]
Yes, this would be a nice feature to have. Please submit a PR.

**Comment by hazzik** [comment]
Issue is still not resolved. Please reopen.

**Comment by arturcic** [comment]
Fixed. should be available when next beta or stable version is released
