### ISSUE TITLE
Add strategy for incrementing the version by looking for commits tagged with version bumps

### ISSUE THREAD

**Issue by MikeLarah** [GitTools/GitVersion#971]
Similar to incrementing based off of commit messages containing `+semver:minor` or `+semver:major` - if we could tag commits with these messages and increment the version accordingly.

The reason being is that we want to do a binary comparison between the current build and the last master build to detect API changes (which obviously happens after the commit), then retrospectively tag the commit to state if there was a major or minor change.

**Comment by mwadams** [comment]
(Prior to a merge back into e.g. Develop or Master)

**Comment by JakeGinnivan** [comment]
I suggest the following for this scenario.

1. Upgrade to v4 beta
2. Switch to mainline mode
3. Add the `+semver: minor` or `+semver: breaking` to the merge commit when merging the PR.

If this works for you, it would be awesome to get this sort of flow documented somewhere in the docs!

**Comment by JakeGinnivan** [comment]
Going to close, I do not think we want to encourage abusing tags in this way. Would love a follow up from your side @MikeLarah if the above suggestion works for you
