### ISSUE TITLE
Issues labeled as questions should be excluded from release notes

### ISSUE THREAD

**Issue by pascalberger** [GitTools/GitVersion#979]
Issues with the "Question" label which are closed in a release should not be included in the release notes

**Comment by JakeGinnivan** [comment]
Needs https://github.com/GitTools/GitReleaseNotes/issues/93 to be implemented

**Comment by Franklin89** [comment]
I just looked at the source code, there is a possibility to add a filter to the IssueTrackerFilter. If this property would be mapped to some argument it could be possible to exclude different labels.

Of course the _IssueTracker_ has to make use of this Filter which currently does not seem to work with the GitHubIssue Tracker.

```
var filter = new IssueTrackerFilter
{
   Since = findIssuesSince,
   IncludeOpen = false,
   Filter = "-label:question"
};
```
