### ISSUE TITLE
Add additional output type for saving asserted version numbers to a file

### ISSUE THREAD

**Issue by gep13** [GitTools/GitVersion#983]
It would allow some consistency when calling GitVersion with `/output buildserver` where the variables are not output to the stdout, since this is not possible.

We are already creating the cache file on each run, so it should be simple enough to take a file path from the user, and save the file there also.

As discussed on Gitter here:

https://gitter.im/GitTools/GitVersion?at=5799fe2c93148c6b21e580a5

**Comment by kritisingh1** [comment]
@gep13 Hi. I would like to work on this issue. Please let me know if I may. I am a beginner and this would be my first contribution to open source.

**Comment by asbjornu** [comment]
@kritisingh1: Awesome! Please go ahead and:

1. [Fork the repository](https://help.github.com/articles/fork-a-repo/)
2. [Create a new branch](https://git-scm.com/book/en/v2/Git-Branching-Basic-Branching-and-Merging)
3. Commit the fixes to the branch
4. Push the branch to your remote fork
5. [Create a pull request](https://help.github.com/articles/creating-a-pull-request/)

If you have any questions, don't hesitate to ask them here or on [Gitter](https://gitter.im/GitTools/GitVersion).

**Comment by WhiteWaterCoder** [comment]
Is this issue still up for grabs? I might try and have a stab at it in my minimal spare time.

**Comment by asbjornu** [comment]
@WhiteWaterCoder: Yes, absolutely! That would be awesome!
