### ISSUE TITLE
How to properly configure GitVersion to make prerelease NuGet packages on every commit?

### ISSUE THREAD

**Issue by kpa6uk** [GitTools/GitVersion#987]
I installed GitVersionTask in my projects and build them via TeamCity and create NuGet packages.
I'm using GitFlow in my development.

I make feature branch, commit into it several times. I want TeamCity to produce different prerelease packages for every commit.
Now I have these properties calculated on some commit in feature branch:

>GitVersion.AssemblySemVer	1.2.0.0 
GitVersion.BranchName	feature/DL-591_remove_objSet 
GitVersion.BuildMetaData	35 
GitVersion.BuildMetaDataPadded	0035 
GitVersion.CommitDate	2016-08-03 
GitVersion.CommitsSinceVersionSource	35 
GitVersion.CommitsSinceVersionSourcePadded	0035 
GitVersion.FullBuildMetaData	35.Branch.feature/DL-591_remove_objSet.Sha.edba4c8cd195b7217117e8b5f85518f94f7753bf 
GitVersion.FullSemVer	1.2.0-DL-591-remove-objSet.1+35 
GitVersion.InformationalVersion	1.2.0-DL-591-remove-objSet.1+35.Branch.feature/DL-591_remove_objSet.Sha.edba4c8cd195b7217117e8b5f85518f94f7753bf 
GitVersion.LegacySemVer	1.2.0-DL-591-remove-objSe1 
GitVersion.LegacySemVerPadded	1.2.0-DL-591-remove-ob0001 
GitVersion.Major	1 
GitVersion.MajorMinorPatch	1.2.0 
GitVersion.Minor	2 
GitVersion.NuGetVersion	1.2.0-dl-591-remove-ob0001 
GitVersion.NuGetVersionV2	1.2.0-dl-591-remove-ob0001 
GitVersion.Patch	0 
GitVersion.PreReleaseLabel	DL-591-remove-objSet 
GitVersion.PreReleaseNumber	1 
GitVersion.PreReleaseTag	DL-591-remove-objSet.1 
GitVersion.PreReleaseTagWithDash	-DL-591-remove-objSet.1 
GitVersion.SemVer	1.2.0-DL-591-remove-objSet.1 
GitVersion.Sha	edba4c8cd195b7217117e8b5f85518f94f7753bf `

Now I use `GitVersion.NuGetVersionV2` as a version string for `nuget pack`, but I want something generated from `GitVersion.CommitsSinceVersionSourcePadded`.

Am I understand something wrong? Or maybe misconfiguration?

**Comment by JakeGinnivan** [comment]
> I make feature branch, commit into it several times. I want TeamCity to produce different prerelease packages for every commit.

Do you deploy every commit? The idea is if you deploy or have a chained build for the package then you simply tag when you do that then the version will bump. Otherwise continuous delivery probably is what you are after. Or mainline mode in v4

**Comment by kpa6uk** [comment]
Creating GitVersion.yml and setting there
`mode: ContinuousDeployment`
completely solved this problem.

Thanks
