### ISSUE TITLE
Update docs index to include missing files

### ISSUE THREAD

**Issue by JakeGinnivan** [GitTools/GitVersion#992]
There are a few pages in the docs which are not included in the mkdocs index file. Like https://github.com/GitTools/GitVersion/blob/master/docs/versioning-mode.md

We need to ensure nothing is missing

**Comment by asbjornu** [comment]
#989 adds `versioning-mode.md` to `mkdocs.yml`, but we should have a test that ensures all `.md` files in the `docs` directory are included, yeah.

**Comment by JakeGinnivan** [comment]
Nice.. Missed that one
