### ISSUE TITLE
Create Debian Package

### ISSUE THREAD

**Issue by asbjornu** [GitTools/GitVersion#994]
As Homebrew/homebrew-core#3709 is merged and GitVersion now available on Homebrew for OS X, it would be nice if it was also made available on Debian based Linux distributions such as Ubuntu by creating a `.deb` package, [as per these instructions](http://packaging.ubuntu.com/html/packaging-new-software.html).

**Comment by asbjornu** [comment]
We have GitVersion on Docker now. Closing.

**Comment by tsopokis** [comment]
@asbjornu is that a real answer?  You ve got pckage for choco, for brew and for debian we have docker? You can just say we dont care about debian and Linux. That would be a fair answer.

**Comment by asbjornu** [comment]
@tsopokis, it's not about not caring, it's about competence and time management. Personally, I would love to have a package of GitVersion for Debian, Alpine, Arch, RedHat, etc.

But I don't use Linux myself and I don't think any other maintainers of GitVersion do either, so we have no idea how to create a package to any Linux distribution and even if we did, we wouldn't use it ourselves.

The point of this issue was mostly about availability, not about providing a native package to all operating systems per se. Now that GitVersion is available in Docker, the availability is pretty up to Docker and not up to us. Everywhere Docker is available, GitVersion is available.

If the Docker image had been available sooner, we probably wouldn't have had a Homebrew package, since Docker would have solved the availability problem there. The reason we have a Homebrew package is because I use macOS, so I had the knowledge, interest and ability to test a Homebrew package.

Nobody gets paid to work on GitVersion. We need to prioritize what we spend our time on. If we get a pull request adding a Debian package and it doesn't require a lot of us to maintain, we will certainly merge it. But until we do, we won't have a Debian package and having an open issue that nobody addresses isn't going to fix that. Sorry. 🤷‍♂

**Comment by arturcic** [comment]
We could have a look at this https://github.com/qmfrederik/dotnet-packaging/ ....
